zen-panel-ui-workspaces-text = 다른 워크스페이스
zen-panel-ui-workspaces-create = 
    .label = Create Space
zen-panel-ui-workspaces-edit-text = 워크스페이스 편집
zen-panel-ui-workspaces-edit-save = 
    .label = 변경사항 저장
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = 취소
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = 워크스페이스 삭제
    .accesskey = D
zen-workspaces-panel-change-name = 
    .label = 이름 변경
zen-workspaces-panel-change-icon = 
    .label = 아이콘 변경
zen-workspaces-panel-context-manage = 
    .label = 워크스페이스 관리
    .accesskey = M
zen-workspaces-panel-context-open-in-container-tab = 
    .label = 기본 컨테이너 설정
    .accesskey = O
zen-workspaces-change-theme = 
    .label = Edit Theme
zen-workspaces-panel-context-open = 
    .label = 워크스페이스 열기
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = 기본 워크스페이스로 설정
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = 워크스페이스 편집
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = 다른 워크스페이스로 이동
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = 워크스페이스
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = 보색
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = 분할보색
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = 유사색
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = 삼색
zen-panel-ui-gradient-generator-algo-floating = 
    .label = 플로팅
zen-panel-ui-gradient-click-to-add = 클릭으로 색을 추가하세요
zen-workspace-creation-name = 
    .placeholder = Space Name
zen-workspace-creation-profile = Profile
    .tooltiptext = Profiles are used to separate cookies and site data between spaces.
zen-workspace-creation-title = Create a new Space
zen-workspace-creation-label = Spaces are used to organize your tabs and sessions.
