zen-toolbar-context-tabs-right = 
    .label = 우측 탭
    .accesskey = R
zen-toolbar-context-compact-mode = 
    .label = 간소화 모드
    .accesskey = C
zen-toolbar-context-compact-mode-enable = 
    .label = 간소화 모드 활성화
    .accesskey = D
zen-toolbar-context-compact-mode-just-tabs = 
    .label = 사이드바 숨기기
zen-toolbar-context-compact-mode-just-toolbar = 
    .label = 툴바 숨기기
zen-toolbar-context-compact-mode-hide-both = 
    .label = 둘 다 숨기기
    .accesskey = H
sidebar-zen-sidepanel = 
    .label = 사이드 패널
sidebar-zen-expand = 
    .label = 사이드바 확장
