zen-panel-ui-current-profile-text = 현재 프로필
unified-extensions-description = 확장은 { -brand-short-name }에 더 많은 추가 기능을 제공하는 데 사용됩니다.
tab-context-zen-reset-pinned-tab = 
    .label = Reset Pinned Tab
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Replace Pinned URL with Current
    .accesskey = C
tab-zen-unload = 
    .label = 탭 언로드
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = 탭 언로더 액션
    .accesskey = T
tab-zen-prevent-unload = 
    .label = 탭 언로드 방지
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Prevent Tab Unload
    .accesskey = I
