zen-panel-ui-workspaces-text = 다른 워크스페이스
zen-panel-ui-workspaces-create = 
    .label = 스페이스 만들기
zen-panel-ui-workspaces-edit-text = 워크스페이스 편집
zen-panel-ui-workspaces-edit-save = 
    .label = 변경사항 저장
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = 취소
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = 워크스페이스 삭제
    .accesskey = D
zen-workspaces-panel-change-name = 
    .label = 이름 변경
zen-workspaces-panel-change-icon = 
    .label = 아이콘 변경
zen-workspaces-panel-context-manage = 
    .label = 워크스페이스 관리
    .accesskey = M
zen-workspaces-panel-context-open-in-container-tab = 
    .label = 기본 컨테이너 설정
    .accesskey = O
zen-workspaces-how-to-reorder = 스페이스를 재정렬하려면 사이드바 하단의 아이콘을 드래그하십시오.
zen-workspaces-change-theme = 
    .label = 테마 편집
zen-workspaces-panel-context-open = 
    .label = 워크스페이스 열기
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = 기본 워크스페이스로 설정
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = 워크스페이스 편집
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = 다른 워크스페이스로 이동
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = 워크스페이스
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = 보색
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = 분할보색
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = 유사색
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = 삼색
zen-panel-ui-gradient-generator-algo-floating = 
    .label = 플로팅
zen-panel-ui-gradient-click-to-add = 클릭으로 색을 추가하세요
zen-workspace-creation-name = 
    .placeholder = 스페이스 이름
zen-workspaces-panel-context-reorder = 
    .label = 워크스페이스 재정렬
zen-workspace-creation-profile = 프로필
    .tooltiptext = 프로필은 스페이스 간의 쿠키와 사이트 데이터를 분리하기 위해 사용됩니다.
zen-workspace-creation-header = 스페이스 생성
zen-workspace-creation-label = 스페이스는 탭과 세션을 정리하기 위해 사용됩니다.
