zen-panel-ui-current-profile-text = 현재 프로필
unified-extensions-description = 확장은 { -brand-short-name }에 더 많은 추가 기능을 제공하는 데 사용됩니다.
tab-context-zen-reset-pinned-tab = 
    .label = 고정된 탭 초기화
    .accesskey = R
tab-context-zen-add-essential = 
    .label = Add to Essentials
    .accesskey = E
tab-context-zen-remove-essential = 
    .label = Remove from Essentials
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = 고정된 URL을 현재 URL로 변경
    .accesskey = C
tab-zen-unload = 
    .label = 탭 언로드
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = 탭 언로더 액션
    .accesskey = T
tab-zen-prevent-unload = 
    .label = 탭 언로드 방지
    .accesskey = P
tab-zen-ignore-unload = 
    .label = 탭 언로드 허용
    .accesskey = I
zen-themes-corrupted = { -brand-short-name } 모드 파일이 손상되었습니다. 기본 테마로 재설정되었습니다.
zen-shortcuts-corrupted = Your { -brand-short-name } shortcuts file is corrupted. They have been reset to the default shortcuts.
zen-panel-ui-gradient-generator-opacity-text = 대비
zen-panel-ui-gradient-generator-texture-text = 질감
zen-panel-ui-gradient-generator-custom-color = 커스텀 색상
zen-panel-ui-gradient-generator-saved-message = 성공적으로 그라데이션을 저장했습니다!
zen-copy-current-url-confirmation = The URL has been copied to the clipboard.
zen-rice-share-name = 
    .placeholder = Rice Name
zen-rice-share-author = By
zen-rice-share-author-input = 
    .placeholder = Your Name
zen-rice-share-cancel = Cancel
zen-rice-share-save = Share
zen-rice-share-include-userchrome = 
    .label = Include zen window styles (userChrome.css)
zen-rice-share-include-usercontent = 
    .label = Include website styles (userContent.css)
zen-rice-share-include-mods = 
    .label = Include enabled mods
zen-rice-share-include-mod-prefs = 
    .label = Include mod preferences
zen-rice-share-include-preferences = 
    .label = Include layout preferences
zen-rice-share-include-workspace-themes = 
    .label = Include workspace gradient themes
zen-rice-share-success = Successfully created a Rice!
zen-rice-share-success-link = Rice Share Link
zen-rice-share-accept = Accept
zen-rice-share-notice = Before sharing, please understand what a Rice is
# note: Do not translate the "<br/>" tags in the following string
zen-rice-share-notice-description =
    A Rice is a collection of customizations that can be shared with others.<br/>
    This includes your window styles, website styles, enabled mods, mod preferences, layout preferences, and workspace gradient themes.<br/>
    By sharing a Rice, you are sharing all of these customizations with others. Please be mindful of what you share.
zen-learn-more-text = Learn More
zen-rice-share-include = Export Options
appmenu-zen-share-rice = 
    .label = Share Zen Rice
zen-close-label = Close
