zen-web-side-panel-context-mute-panel = 
    .label = 웹 패널 음소거
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = 웹 패널 음소거 해제
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = 모바일 환경 비활성화
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = 모바일 환경 활성화
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = 웹 패널 로드 해제
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = 웹 패널 삭제
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = 새 탭으로 열기
    .accesskey = N
zen-web-side-panel-context-add-to-panel = 
    .label = 웹 패널에 추가
    .accesskey = A
zen-sidebar-introduction-title = Zen 사이드바에 잘 오셨습니다
zen-sidebar-introduction-description = Zen 사이드바는 웹을 브라우징하는 새로운 방식입니다. 아이콘을 아무거나 눌러 웹 패널을 열어보세요.
