zen-panel-ui-current-window-text = Current Window
zen-panel-ui-workspaces-text = Other Workspaces
zen-panel-ui-workspaces-create-text = Create Workspace
zen-panel-ui-workspaces-create-save = 
    .label = Create Workspace
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = Cancel
    .accesskey = C
zen-panel-ui-workspaces-edit-text = 편집 작업 공간
zen-panel-ui-workspaces-edit-save = 
    .label = 변경사항 저장
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = 취소
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = 작업 공간 삭제
    .accesskey = D
zen-workspaces-panel-context-open = 
    .label = 작업 공간 열기
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = 기본 작업 공간으로 설정
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = 편집 작업 공간
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Change Tab(s) To Workspace
    .accesskey = C
zen-workspaces-panel-context-open-in-container-tab = 
    .label = 기본 컨테이너 설정
    .accesskey = O
