zen-panel-ui-current-profile-text = 현재 프로필
unified-extensions-description = 확장은 { -brand-short-name }에 더 많은 추가 기능을 제공하는 데 사용됩니다.
tab-context-zen-reset-pinned-tab = 
    .label = 고정된 탭 초기화
    .accesskey = R
tab-context-zen-add-essential = 
    .label = Add to Essentials
    .accesskey = E
tab-context-zen-remove-essential = 
    .label = Remove from Essentials
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = 고정된 URL을 현재 URL로 변경
    .accesskey = C
tab-zen-unload = 
    .label = 탭 언로드
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = 탭 언로더 액션
    .accesskey = T
tab-zen-prevent-unload = 
    .label = 탭 언로드 방지
    .accesskey = P
tab-zen-ignore-unload = 
    .label = 탭 언로드 허용
    .accesskey = I
zen-themes-corrupted = { -brand-short-name } 모드 파일이 손상되었습니다. 기본 테마로 재설정되었습니다.
zen-panel-ui-gradient-generator-opacity-text = 대비
zen-panel-ui-gradient-generator-texture-text = 질감
zen-panel-ui-gradient-generator-custom-color = 커스텀 색상
zen-panel-ui-gradient-generator-saved-message = 성공적으로 그라데이션을 저장했습니다!
zen-copy-current-url-confirmation = The URL has been copied to the clipboard.
