zen-panel-ui-current-window-text = Mevcut Pencere
zen-panel-ui-workspaces-text = Diğer Çalışma Alanları
zen-panel-ui-workspaces-create-text = Çalışma Alanı Oluştur
zen-panel-ui-workspaces-create-save = 
    .label = Çalışma Alanı Oluştur
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = İptal
    .accesskey = C
zen-panel-ui-workspaces-edit-text = Çalışma Alanını Düzenle
zen-panel-ui-workspaces-edit-save = 
    .label = Değişiklikleri Kaydet
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = İptal
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Çalışma Alanını Sil
    .accesskey = D
zen-workspaces-panel-context-open = 
    .label = Çalışma Alanı Aç
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Varsayılan Çalışma Alanı Olarak Ayarla
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Çalışma Alanını Düzenle
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Sekme(ler)i Çalışma Alanına Değiştir
    .accesskey = C
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Set Default Container
    .accesskey = O
