zen-panel-ui-current-window-text = Mevcut Pencere
zen-panel-ui-workspaces-text = Diğer Çalışma Alanları
zen-panel-ui-workspaces-create-text = Çalışma Alanı Oluştur
zen-panel-ui-workspaces-create-save = 
    .label = Create Workspace
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = Cancel
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Delete Workspace
    .accesskey = D
zen-workspaces-panel-context-open = 
    .label = Çalışma Alanı Aç
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Set As Default Workspace
    .accesskey = S
context-zen-change-workspace-tab = 
    .label = Change Tab(s) To Workspace
    .accesskey = C
