zen-toolbar-context-tabs-right = 
    .label = Sağdaki sekmeler
    .accesskey = R
zen-toolbar-context-compact-mode = 
    .label = Kompakt mod
    .accesskey = C
zen-toolbar-context-compact-mode-enable = 
    .label = Komapkt moduu aktifleştir
    .accesskey = D
zen-toolbar-context-compact-mode-just-tabs = 
    .label = Kenar çubuğunu gizle
zen-toolbar-context-compact-mode-just-toolbar = 
    .label = Araç barını gizle
zen-toolbar-context-compact-mode-hide-both = 
    .label = İkisini de Gizle
    .accesskey = H
sidebar-zen-sidepanel = 
    .label = Yan Panaller
sidebar-zen-expand = 
    .label = Kenar Çubuğunu Genişlet
