zen-panel-ui-workspaces-text = Diğer Çalışma Alanları
zen-panel-ui-workspaces-create = 
    .label = Create Space
zen-panel-ui-workspaces-edit-text = Çalışma Alanını Düzenle
zen-panel-ui-workspaces-edit-save = 
    .label = Değişiklikleri Kaydet
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = İptal
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Çalışma Alanını Sil
    .accesskey = D
zen-workspaces-panel-change-name = 
    .label = İsmini Değiştir
zen-workspaces-panel-change-icon = 
    .label = Simgeyi Değiştir
zen-workspaces-panel-context-manage = 
    .label = Çalışma Alanlarını Yönet
    .accesskey = M
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Varsayılan Konteyner Olarak Seç
    .accesskey = O
zen-workspaces-change-theme = 
    .label = Edit Theme
zen-workspaces-panel-context-open = 
    .label = Çalışma Alanı Aç
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Varsayılan Çalışma Alanı Olarak Ayarla
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Çalışma Alanını Düzenle
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Sekme(ler)i Çalışma Alanına Değiştir
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Çalışma Alanları
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Tamamlayıcı
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Böl
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Analog
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Üçlü
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Kayan
zen-panel-ui-gradient-click-to-add = Renk eklemek için tıkla
zen-workspace-creation-name = 
    .placeholder = Space Name
zen-workspace-creation-profile = Profile
    .tooltiptext = Profiles are used to separate cookies and site data between spaces.
zen-workspace-creation-title = Create a new Space
zen-workspace-creation-label = Spaces are used to organize your tabs and sessions.
