zen-panel-ui-current-profile-text = mevcut profil
unified-extensions-description = Uzantılar { -brand-short-name } daha fazla işlevsellik kazandırmak için kullanılır.
tab-context-zen-reset-pinned-tab = 
    .label = Sabitlenen Sekmeyi Sıfırla
    .accesskey = R
tab-context-zen-add-essential = 
    .label = Temel Ögelere Ekle
    .accesskey = E
tab-context-zen-remove-essential = 
    .label = Temel Ögelerden Kaldır
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Sabitlenen URL'yi Mevcut ile Değiştir
    .accesskey = C
tab-zen-unload = 
    .label = Sekmeyi Uyku Moduna Al
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Uyku Modu Eylemleri
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Sekmenin Uyku Moduna Alınmasını Engelle
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Sekmenin Uyku Moduna Geçmesine İzin Ver
    .accesskey = I
zen-themes-corrupted = { -brand-short-name } adlı modun dosyaları hatalı. Varsayılan temaya sıfırlandılar.
zen-shortcuts-corrupted = Your { -brand-short-name } shortcuts file is corrupted. They have been reset to the default shortcuts.
zen-panel-ui-gradient-generator-opacity-text = Kontrast
zen-panel-ui-gradient-generator-texture-text = Doku
zen-panel-ui-gradient-generator-custom-color = Özel Renk
zen-panel-ui-gradient-generator-saved-message = Renkler başarıyla kaydedildi!
zen-copy-current-url-confirmation = The URL has been copied to the clipboard.
zen-rice-share-name = 
    .placeholder = Rice Name
zen-rice-share-author = By
zen-rice-share-author-input = 
    .placeholder = Your Name
zen-rice-share-cancel = Cancel
zen-rice-share-save = Share
zen-rice-share-include-userchrome = 
    .label = Include zen window styles (userChrome.css)
zen-rice-share-include-usercontent = 
    .label = Include website styles (userContent.css)
zen-rice-share-include-mods = 
    .label = Include enabled mods
zen-rice-share-include-mod-prefs = 
    .label = Include mod preferences
zen-rice-share-include-preferences = 
    .label = Include layout preferences
zen-rice-share-include-workspace-themes = 
    .label = Include workspace gradient themes
zen-rice-share-success = Successfully created a Rice!
zen-rice-share-success-link = Rice Share Link
zen-rice-share-accept = Accept
zen-rice-share-notice = Before sharing, please understand what a Rice is
# note: Do not translate the "<br/>" tags in the following string
zen-rice-share-notice-description =
    A Rice is a collection of customizations that can be shared with others.<br/>
    This includes your window styles, website styles, enabled mods, mod preferences, layout preferences, and workspace gradient themes.<br/>
    By sharing a Rice, you are sharing all of these customizations with others. Please be mindful of what you share.
zen-learn-more-text = Learn More
zen-rice-share-include = Export Options
appmenu-zen-share-rice = 
    .label = Share Zen Rice
zen-close-label = Close
