zen-web-side-panel-context-mute-panel = 
    .label = Web Panelini Sessize Al
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = Web Panelini Sessizden Çıkar
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = Mobil Kullanıcı Aracısını Devre Dışı Bırak
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Mobil Kullanıcı Aracısını Etkinleştir
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = Web Panelini Kaldır
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = Web Panelini Sil
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = Yeni Sekmede Aç
    .accesskey = N
zen-web-side-panel-context-open-in-container-tab = 
    .label = Open in Container Tab
    .accesskey = C
zen-web-side-panel-context-add-to-panel = 
    .label = Web Paneline Ekle
    .accesskey = A
zen-sidebar-introduction-title = Zen Kenar Çubuğuna Hoşgeldin
zen-sidebar-introduction-description = Zen Kenar Çubuğu, internette gezinmenin yeni bir yoludur. Bir web panelini açmak için simgelerden herhangi birine tıkla.
