zen-panel-ui-current-profile-text = mevcut profil
unified-extensions-description = Uzantılar { -brand-short-name } daha fazla işlevsellik kazandırmak için kullanılır.
tab-zen-unload = 
    .label = Sekmeyi Uyku Moduna Al
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Uyku Modu Eylemleri
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Sekmenin Uyku Moduna Alınmasını Engelle
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Sekmelerin Uyku Moduna Alınmasını Görmezden Gel
    .accesskey = I
