zen-web-side-panel-context-mute-panel = 
    .label = Web Panel'ini Sessize Al
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = Web Panel'ini Sessizden Çıkar
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = Mobil UserAgent'i Devre Dışı Bırak
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Mobil UserAgent'i Etkinleştir
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = Web Panel'ini Yükleyi Kes
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = Web Panel'ini Sil
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = Yeni Sekmede Aç
    .accesskey = N
zen-web-side-panel-context-add-to-panel = 
    .label = Web Panel'lerine Ekle
    .accesskey = A
zen-sidebar-introduction-title = Zen Sidebar'a Hoş Geldiniz
zen-sidebar-introduction-description = Zen Sidebar, internette dolaşmanın yeni bir şeklidir. Bir web panel'i açmak için herhangi bir ikona tıklayın.
