zen-panel-ui-current-profile-text = mevcut profil
unified-extensions-description = Uzantılar { -brand-short-name } daha fazla işlevsellik kazandırmak için kullanılır.
tab-zen-unload = 
    .label = Unload Tab
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Tabs Unloader Actions
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Prevent Tab Unload
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Ignore Tab Unload
    .accesskey = I
