pane-zen-looks-title = Uiterlijk en gevoel
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Het wijzigen van de standaardtaal kan het voor websites gemakkelijker maken om u te volgen.
zen-look-and-feel-colors-header = Kies een thema kleur
zen-look-and-feel-colors-description = Laat { -brand-short-name } eruitzien en aanvoelen zoals u wilt
zen-look-and-feel-themed-toolbar = 
    .label = Maak de werkbalk thematisch met de accentkleur
pane-zen-side-panels-title = Webzijpanelen
zen-side-panels-header = Algemene instellingen voor webpanelen
zen-side-panels-description = Verhoog de productiviteit door meerdere weergaven tegelijkertijd te hebben!
zen-side-panels-enabled = 
    .label = Schakel webzijpanelen in
zen-side-panels-close-on-blur = 
    .label = Sluit het paneel wanneer het de focus verliest, tenzij het is vastgezet
zen-vertical-tabs-show-bottom-border = 
    .label = Toon rand voor de onderste iconen
sync-currently-syncing-workspaces = Werkruimtes
sync-engine-workspaces = 
    .label = Werkruimtes
    .tooltiptext = Synchroniseer je werkruimtes tussen apparaten
    .accesskey = W
zen-look-and-feel-compact-view-header = In compacte weergave weergeven
zen-look-and-feel-compact-view-description = Toon alleen de werkbalken die u gebruikt!
zen-look-and-feel-compact-view-enabled = 
    .label = Schakel { -brand-short-name }'s compacte modus in
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Verberg de bovenste werkbalk ook in compacte modus
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Laat de werkbalk kort oppoppen bij het wisselen of openen van nieuwe tabbladen in compacte modus
zen-look-and-feel-buttons-header = Knopstijl
zen-look-and-feel-buttons-description = Kies de stijl van knoppen die u wilt zien
zen-look-and-feel-pilled-buttons = 
    .label = Ronde knoppen
pane-zen-tabs-title = Tabbladbeheer
category-zen-workspaces = 
    .tooltiptext = { pane-zen-tabs-title }
pane-settings-workspaces-title = Werkruimten
pane-zen-tabs-unloader-title = Tabblad Ontlader
zen-tabs-unloader-header = Algemene instellingen voor tabblad ontlader
zen-tabs-unloader-description = Automatisch ongebruikte tabbladen ontladen om geheugen te besparen
zen-tabs-unloader-enabled = 
    .label = Tabblad ontlader inschakelen
zen-tabs-unloader-unload-delay = 
    .label = Tabbladen ontladen na
zen-tabs-unloader-unload-delay-description = De tijd in minuten waarna tabbladen zullen worden ontladen
pane-zen-pinned-tab-manager-title = Vastgepinde tabbladen
zen-pinned-tab-manager-header = Algemene instellingen voor vastgepinde tabbladen
zen-pinned-tab-manager-description = Beheer aanvullend gedrag van vastgepinde tabbladen
zen-pinned-tab-manager-restore-pinned-tabs-to-pinned-url = 
    .label = Herstel vastgepinde tabbladen naar hun oorspronkelijk vastgepinde URL bij opstarten
zen-pinned-tab-manager-close-shortcut-behavior-label = Gedrag van sneltoets voor tabblad sluiten
zen-pinned-tab-manager-reset-unload-switch-close-shortcut-option = 
    .label = Reset URL, ontlaad en schakel over naar het volgende tabblad
zen-pinned-tab-manager-unload-switch-close-shortcut-option = 
    .label = Ontlaad en schakel over naar het volgende tabblad
zen-pinned-tab-manager-reset-switch-close-shortcut-option = 
    .label = Reset URL en schakel over naar het volgende tabblad
zen-pinned-tab-manager-switch-close-shortcut-option = 
    .label = Schakel over naar het volgende tabblad
zen-pinned-tab-manager-reset-close-shortcut-option = 
    .label = Reset URL
zen-pinned-tab-manager-close-close-shortcut-option = 
    .label = Sluit tabblad
pane-zen-workspaces-header = Werkruimtes
zen-settings-workspaces-header = Algemene instellingen voor werkruimten
zen-settings-workspaces-description = Met werkruimten kunt u meerdere browsersessies tegelijkertijd hebben!
zen-settings-workspaces-enabled = 
    .label = Werkruimten inschakelen (Experimenteel)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Verberg de standaard container indicator in de tabbladbalk
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Sta werkruimtes toe om hun eigen vastgepinde tabbladen te hebben
zen-key-unsafed = Ongeslagen sneltoets! Sla het op door op de "Escape" toets te drukken nadat je het opnieuw hebt getypt.
zen-key-conflict = Conflict met een andere sneltoets
pane-zen-theme-title = Thema-instellingen
zen-vertical-tabs-title = Zijbalk- en tabbladindeling
zen-vertical-tabs-header = Verticale tabbladen
zen-vertical-tabs-description = Beheer uw tabbladen in een verticale indeling
zen-vertical-tabs-show-expand-button = 
    .label = Toon uitbreidknop
zen-vertical-tabs-expand-tabs-by-default = Tabbladen standaard uitbreiden
zen-vertical-tabs-dont-expand-tabs-by-default = Tabbladen niet standaard uitbreiden
zen-vertical-tabs-expand-tabs-on-hover = Tabbladen uitbreiden bij zweven (Werkt niet in compacte modus)
zen-vertical-tabs-expand-tabs-header = Hoe tabbladen uit te breiden
zen-vertical-tabs-expand-tabs-description = Kies hoe u tabbladen in de zijbalk wilt uitbreiden
zen-theme-marketplace-header = Zen Mods
zen-theme-marketplace-description = Zoek en installeer thema's uit de winkel.
zen-theme-marketplace-remove-button = 
    .label = Thema verwijderen
zen-theme-marketplace-check-for-updates-button = 
    .label = Controleren op updates
zen-theme-marketplace-updates-success = Thema succesvol bijgewerkt
zen-theme-marketplace-updates-fail = Geen updates gevonden!
zen-theme-marketplace-toggle-enabled-button = 
    .title = Thema uitschakelen
zen-theme-marketplace-toggle-disabled-button = 
    .title = Thema inschakelen
zen-theme-marketplace-remove-confirmation = Weet je zeker dat je deze mod wilt verwijderen?
zen-theme-marketplace-close-modal = Sluit
zen-theme-marketplace-theme-header-title = 
    .title = CSS Selector: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = Geen
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Typ iets...
pane-zen-marketplace-title = Zen Mods
zen-settings-workspaces-display-as-icon-strip = 
    .label = Toon werkruimtes als een iconen strip
zen-theme-marketplace-link = Bezoek de winkel
zen-dark-theme-styles-header = Donkere thema stijlen
zen-dark-theme-styles-description = Pas het donkere thema aan naar jouw voorkeur
zen-dark-theme-styles-amoled = Nacht thema
zen-dark-theme-styles-default = Standaard Donker Thema
zen-dark-theme-styles-colorful = Kleurrijk Donker Thema
zen-split-view-title = Gesplitste Weergave
zen-split-view-header = Functionaliteit van Gesplitste Weergave
zen-split-view-description = Splits je browser in meerdere weergaven, zodat je meerdere websites tegelijk kunt bekijken
zen-split-view-change-on-hover = 
    .label = Verander tabbladen bij hover
zen-compact-mode-styles-left = Verberg tabbladbalk
zen-compact-mode-styles-top = Verberg bovenbalk
zen-compact-mode-styles-both = Beide verbergen
pane-zen-CKS-title = Toetsenbordsnelkoppelingen
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } Toetsenbordsnelkoppelingen
zen-settings-CKS-header = Pas uw toetsenbordsnelkoppelingen aan
zen-settings-CKS-description = Verander de standaard toetsenbordsnelkoppelingen naar uw wens en verbeter uw browse-ervaring
zen-settings-CKS-disable-firefox = 
    .label = Schakel de standaard toetsenbordsnelkoppelingen van { -brand-short-name } uit
zen-settings-CKS-duplicate-shortcut = 
    .label = Dupliceer sneltoets
zen-settings-CKS-reset-shortcuts = 
    .label = Reset naar Standaard
zenCKSOption-group-other = Anders
zenCKSOption-group-windowAndTabManagement = Venster- en Tabbladbeheer
zenCKSOption-group-navigation = Navigatie
zenCKSOption-group-searchAndFind = Zoeken en Vinden
zenCKSOption-group-pageOperations = Pagina-activiteiten
zenCKSOption-group-historyAndBookmarks = Geschiedenis en Bladwijzers
zenCKSOption-group-mediaAndDisplay = Media en Weergave
zenCKSOption-group-zen-compact-mode = Compacte Modus
zenCKSOption-group-zen-workspace = Werkruimtes
zenCKSOption-group-zen-other = Andere Zen functies
zenCKSOption-group-zen-split-view = Gesplitste Weergave
zen-key-quick-restart = Snelle Herstart
zen-window-new-shortcut = Nieuw Venster
zen-tab-new-shortcut = Nieuw Tabblad
zen-key-redo = Opnieuw uitvoeren
zen-restore-last-closed-tab-shortcut = Herstel Laatst Gesloten Tabblad
zen-location-open-shortcut = Open Locatie
zen-location-open-shortcut-alt = Open Locatie (Alt)
zen-key-undo-close-window = Ongedaan maken Sluiten Venster
zen-text-action-undo-shortcut = Ongedaan maken
zen-text-action-redo-shortcut = Opnieuw uitvoeren
zen-text-action-cut-shortcut = Knippen
zen-text-action-copy-shortcut = Kopiëren
zen-text-action-paste-shortcut = Plakken
zen-text-action-select-all-shortcut = Alles Selecteren
zen-text-action-delete-shortcut = Verwijderen
zen-history-show-all-shortcut-mac = Toon Alle Geschiedenis (Mac)
zen-full-screen-shortcut = Schakel Volledig Scherm In/Uit
zen-reader-mode-toggle-shortcut-windows = Schakel Lezersmodus In/Uit (Windows)
zen-picture-in-picture-toggle-shortcut-alt = Schakel Beeld-in-Beeld In/Uit (Alt)
zen-picture-in-picture-toggle-shortcut-mac = Schakel Beeld-in-Beeld In/Uit (Mac)
zen-picture-in-picture-toggle-shortcut-mac-alt = Schakel Beeld-in-Beeld In/Uit (Mac Alt)
zen-page-source-shortcut-safari = Bekijk Pagina Bron (Safari)
zen-nav-stop-shortcut = Stop Laden
zen-history-sidebar-shortcut = Toon Geschiedenis Zijbalk
zen-window-minimize-shortcut = Minimaliseer Venster
zen-help-shortcut = Open Help
zen-preferences-shortcut = Open Voorkeuren
zen-hide-app-shortcut = Verberg Toepassing
zen-hide-other-apps-shortcut = Verberg Andere Toepassingen
zen-search-focus-shortcut = Focus Zoekopdracht
zen-search-focus-shortcut-alt = Focus Zoekopdracht (Alt)
zen-downloads-shortcut = Open Downloads
zen-addons-shortcut = Open Add-ons
zen-file-open-shortcut = Open Bestand
zen-save-page-shortcut = Sla Pagina Op
zen-print-shortcut = Afdrukken Pagina
zen-close-shortcut-2 = Sluit Tabblad
zen-mute-toggle-shortcut = Schakel Stum In/Uit
zen-key-delete = Verwijdertoets
zen-key-go-back = Ga Terug
zen-key-go-forward = Ga Vooruit
zen-nav-back-shortcut-alt = Navigeer Terug (Alt)
zen-nav-fwd-shortcut-alt = Navigeer Vooruit (Alt)
zen-history-show-all-shortcut = Toon Alle Geschiedenis
zen-key-enter-full-screen = Voer Volledig Scherm In
zen-key-exit-full-screen = Verlaat Volledig Scherm
zen-reader-mode-toggle-shortcut-other = Schakel Lezersmodus In/Uit
zen-picture-in-picture-toggle-shortcut = Schakel Beeld-in-Beeld In/Uit
zen-nav-reload-shortcut-2 = Herlaad Pagina
zen-key-about-processes = Over Processen
zen-page-source-shortcut = Bekijk Pagina Bron
zen-page-info-shortcut = Bekijk Pagina informatie
zen-find-shortcut = Zoeken op Pagina
zen-search-find-again-shortcut = Opnieuw Vinden
zen-search-find-again-shortcut-prev = Vorige Vinden
zen-search-find-again-shortcut-2 = Opnieuw Vinden (Alt)
zen-bookmark-this-page-shortcut = Bladwijzer Deze Pagina
zen-bookmark-show-library-shortcut = Toon Bladwijzers bibliotheek
zen-key-stop = Stop Laden
zen-full-zoom-reduce-shortcut = Stop Laden
zen-full-zoom-enlarge-shortcut = Uitzoomen
zen-full-zoom-reset-shortcut = Reset Zoom
zen-bidi-switch-direction-shortcut = Wissel Tekstrichting
zen-private-browsing-shortcut = Privé Browsen
zen-screenshot-shortcut = Maak Screenshot
zen-key-sanitize = Wis Browsegegevens
zen-quit-app-shortcut = Verlaat Toepassing
zen-key-wr-capture-cmd = WR Capture Opdracht
zen-key-wr-toggle-capture-sequence-cmd = Schakel WR Capture Volgorde In/Uit
zen-nav-reload-shortcut = Herlaad Pagina
zen-nav-reload-shortcut-skip-cache = Herlaad Pagina (Sla Cache Over)
zen-close-shortcut = Sluit Venster
zen-close-tab-shortcut = Sluit Tabblad
zen-compact-mode-shortcut-show-sidebar = Schakel Drijvende Zijbalk In/Uit
zen-compact-mode-shortcut-show-toolbar = Schakel Drijvende Werkbalk In/Uit
zen-compact-mode-shortcut-toggle = Schakel Compacte Modus In/Uit
zen-workspace-shortcut-switch-1 = Schakel over naar Werkruimte 1
zen-workspace-shortcut-switch-2 = Schakel over naar Werkruimte 2
zen-workspace-shortcut-switch-3 = Schakel over naar Werkruimte 3
zen-workspace-shortcut-switch-4 = Schakel over naar Werkruimte 4
zen-workspace-shortcut-switch-5 = Schakel over naar Werkruimte 5
zen-workspace-shortcut-switch-6 = Schakel over naar Werkruimte 5
zen-workspace-shortcut-switch-7 = Schakel over naar Werkruimte 7
zen-workspace-shortcut-switch-8 = Schakel over naar Werkruimte 8
zen-workspace-shortcut-switch-9 = Schakel over naar Werkruimte 9
zen-workspace-shortcut-switch-10 = Schakel over naar Werkruimte 10
zen-workspace-shortcut-forward = Werkruimte Vooruit
zen-workspace-shortcut-backward = Werkruimte Achteruit
zen-web-panel-shortcut-toggle = Schakel Webpaneel In/Uit
zen-sidebar-shortcut-toggle = Schakel Breedte van de Zijbalk In/Uit
zen-pinned-tab-shortcut-reset = Reset Vastgepend Tabblad naar Vastgepende URL
zen-split-view-shortcut-grid = Schakel Gesplitste Weergave Raster In/Uit
zen-split-view-shortcut-vertical = Schakel Gesplitste Weergave Verticaal In/Uit
zen-split-view-shortcut-horizontal = Schakel Gesplitste Weergave Horizontaal In/Uit
zen-split-view-shortcut-unsplit = Sluit Gesplitste Weergave
zen-key-select-tab-1 = Selecteer tabblad #1
zen-key-select-tab-2 = Selecteer tabblad #2
zen-key-select-tab-3 = Selecteer tabblad #3
zen-key-select-tab-4 = Selecteer tabblad #4
zen-key-select-tab-5 = Selecteer tabblad #5
zen-key-select-tab-6 = Selecteer tabblad #6
zen-key-select-tab-7 = Selecteer tabblad #7
zen-key-select-tab-8 = Selecteer tabblad #8
zen-key-select-tab-last = Selecteer laatst tabblad
zen-key-show-all-tabs = Toon alle tabbladen
zen-key-goto-history = Ga naar geschiedenis
zen-key-go-home = Ga naar Startpagina
zen-bookmark-show-sidebar-shortcut = Toon Bladwijzers Zijbalk
zen-bookmark-show-toolbar-shortcut = Show Bookmarks Sidebar
