pane-zen-looks-title = Uiterlijk en gevoel
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Het veranderen van de standaardtaal kan het makkelijker maken voor websites om je te volgen.
zen-look-and-feel-colors-header = Kies een themakleur
zen-look-and-feel-colors-description = Laat { -brand-short-name } er zo uitzien als jij wilt
zen-look-and-feel-use-workspace-colors = 
    .label = Gebruik werkruimte kleuren als primaire kleur
pane-zen-side-panels-title = Webzijpanelen
zen-side-panels-header = Algemene instellingen voor web zijpanelen
zen-side-panels-description = Optimaliseer productiviteit door meerdere pagina's tegelijk te bekijken!
zen-side-panels-enabled = 
    .label = Web zijpanelen inschakelen
zen-side-panels-close-on-blur = 
    .label = Sluit het paneel wanneer die niet in focus is en als het niet vastgepind is
zen-vertical-tabs-show-bottom-border = 
    .label = Toon rand voor de onderste pictogrammen
zen-vertical-tabs-layout-header = Browser indeling
zen-vertical-tabs-layout-description = Kies een indeling die het best bij jou past
zen-layout-single-toolbar = Enkele werkbalk
zen-layout-multiple-toolbar = Meerdere werkbalken
zen-layout-collapsed-toolbar = Ingevouwen werkbalk
sync-currently-syncing-workspaces = Werkruimtes
sync-engine-workspaces = 
    .label = Werkruimtes
    .tooltiptext = Synchroniseer uw werkruimtes met verschillende apparaten
    .accesskey = W
zen-glance-title = Snel bekijken
zen-glance-header = Algemene instellingen voor snel bekijken
zen-glance-description = Krijg een snel overzicht van uw links zonder ze te openen in een nieuw tabblad
zen-glance-trigger-label = Activatie methode
zen-glance-enabled = 
    .label = Schakel snel bekijken in
zen-glance-trigger-ctrl-click = 
    .label = Ctrl + Klik
zen-glance-trigger-alt-click = 
    .label = Alt + Klik
zen-glance-trigger-shift-click = 
    .label = Shift + Klik
zen-glance-trigger-meta-click = 
    .label = Windows (Command) + Klik
zen-glance-trigger-mantain-click = 
    .label = Klikken ingedrukt houden (Komt binnenkort!)
zen-look-and-feel-compact-view-header = Toon in compacte weergave
zen-look-and-feel-compact-view-description = Toon alleen de werkbalken die u gebruikt!
zen-look-and-feel-compact-view-enabled = 
    .label = { -brand-short-name }'s compacte modus inschakelen
zen-look-and-feel-compact-view-top-toolbar = 
    .label = De bovenste werkbalk ook verbergen in compacte modus
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Laat kort de werkbalk zien bij het wisselen of openen van nieuwe tabbladen in compacte modus
zen-look-and-feel-buttons-header = Knoppen stijl
zen-look-and-feel-buttons-description = Kies de stijl van de knoppen die je wilt zien
zen-look-and-feel-pilled-buttons = 
    .label = Ovale knoppen
pane-zen-tabs-title = Tabblad Beheer
category-zen-workspaces = 
    .tooltiptext = { pane-zen-tabs-title }
pane-settings-workspaces-title = Werkruimtes
pane-zen-tabs-unloader-title = Tabblad ontladen
zen-tabs-unloader-header = Algemene instellingen voor tabblad ontladen
zen-tabs-unloader-description = Automatisch ongebruikte tabbladen niet laden om geheugen op te slaan
zen-tabs-unloader-enabled = 
    .label = Tabblad ontladen inschakelen
zen-tabs-unloader-unload-delay = 
    .label = Tabbladen uitschakelen na
zen-tabs-unloader-unload-delay-description = De tijd in minuten waarna tabbladen ontladen worden
zen-look-and-feel-compact-toolbar-themed = 
    .label = Gebruikte thema achtergrond voor compacte werkbalk
zen-look-and-feel-compact-sidebar-themed = 
    .label = Gebruikte thema achtergrond voor compacte werkbalk
pane-zen-pinned-tab-manager-title = Vastgezette tabbladen
zen-pinned-tab-manager-header = Algemene instellingen voor vastgezette tabbladen
zen-pinned-tab-manager-description = Aanvullend gedrag van vastgezette tabbladen beheren
zen-pinned-tab-manager-restore-pinned-tabs-to-pinned-url = 
    .label = Herstel vastgezette tabbladen naar hun oorspronkelijk vastgezette URL bij het opstarten
zen-pinned-tab-manager-container-specific-essentials-enabled = 
    .label = Essentiële container specifieke functies inschakelen
zen-pinned-tab-manager-close-shortcut-behavior-label = Sluit tabblad snelkoppeling gedrag
zen-pinned-tab-manager-reset-unload-switch-close-shortcut-option = 
    .label = URL resetten, ontladen en overschakelen naar volgend tabblad
zen-pinned-tab-manager-unload-switch-close-shortcut-option = 
    .label = Ontladen en overschakelen naar volgend tabblad
zen-pinned-tab-manager-reset-switch-close-shortcut-option = 
    .label = URL resetten en naar volgend tabblad overschakelen
zen-pinned-tab-manager-switch-close-shortcut-option = 
    .label = Wisselen naar volgend tabblad
zen-pinned-tab-manager-reset-close-shortcut-option = 
    .label = URL resetten
zen-pinned-tab-manager-close-close-shortcut-option = 
    .label = Tabblad sluiten
pane-zen-workspaces-header = Werkruimtes
zen-settings-workspaces-header = Algemene instellingen voor werkruimtes
zen-settings-workspaces-description = Met werkruimtes kan je meerdere browser sessies tegelijk hebben!
zen-settings-workspaces-enabled = 
    .label = Werkruimtes inschakelen (Experimenteel)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Verberg de standaard container indicator in de tabbalk
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Toestaan dat werkruimtes hun eigen vastgezette tabbladen hebben
zen-key-unsaved = Snelkoppeling is niet opgeslagen! Bewaar deze door op de "Escape" knop te drukken en het opnieuw in te typen.
zen-key-conflict = Conflict met een andere snelkoppeling
pane-zen-theme-title = Thema instellingen
zen-vertical-tabs-title = Zijbalk en tabbladen lay-out
zen-vertical-tabs-header = Verticale tabbladen
zen-vertical-tabs-description = Beheer uw tabbladen in een verticale lay-out
zen-vertical-tabs-show-expand-button = 
    .label = Toon uitvouw knop
zen-vertical-tabs-newtab-on-tab-list = 
    .label = Laat nieuwe tabblad knop zien op de tabblad lijst
zen-vertical-tabs-newtab-top-button-border = 
    .label = Laat scheidingslijn zien wanneer de nieuwe tabblad knop onderin is
zen-vertical-tabs-newtab-top-button-up = 
    .label = Verplaats de nieuwe tabblad knop naar bovenin
zen-vertical-tabs-expand-tabs-by-default = Tabbladen standaard uitvouwen
zen-vertical-tabs-dont-expand-tabs-by-default = Tabbladen standaard niet uitvouwen
zen-vertical-tabs-expand-tabs-on-hover = Tabbladen uitvouwen door eroverheen te zweven (zal niet werken in de compacte modus)
zen-vertical-tabs-expand-tabs-header = Hoe tabbladen uit te vouwen
zen-vertical-tabs-expand-tabs-description = Kies hoe tabbladen in de zijbalk uit te vouwen
zen-theme-marketplace-header = Zen Extensies
zen-theme-disable-all-enabled = 
    .title = Alle extensies uitschakelen
zen-theme-disable-all-disabled = 
    .title = Alle extensies inschakelen
zen-theme-marketplace-description = Zoek en installeer extensies in de winkel.
zen-theme-marketplace-remove-button = 
    .label = Extensie verwijderen
zen-theme-marketplace-check-for-updates-button = 
    .label = Controleren op updates
zen-theme-marketplace-updates-success = Extensies succesvol bijgewerkt
zen-theme-marketplace-updates-fail = Kon geen updates vinden!
zen-theme-marketplace-toggle-enabled-button = 
    .title = Extensie uitschakelen
zen-theme-marketplace-toggle-disabled-button = 
    .title = Extensie inschakelen
zen-theme-marketplace-remove-confirmation = Weet je zeker dat je deze extensie wilt verwijderen?
zen-theme-marketplace-close-modal = Afsluiten
zen-theme-marketplace-theme-header-title = 
    .title = CSS-kiezer: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = geen
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Typ iets...
pane-zen-marketplace-title = Zen Extensies
zen-settings-workspaces-display-as-icon-strip = 
    .label = Werkruimtes weergeven als een rij iconen
zen-settings-workspaces-force-container-tabs-to-workspace = 
    .label = Schakel over naar de werkruimte waar container als standaard is ingesteld bij het openen van container tabbladen
zen-settings-workspaces-hide-deactivated-workspaces = 
    .label = Verberg gedeactiveerde werkruimtes
zen-theme-marketplace-link = Bezoek winkel
zen-dark-theme-styles-header = Donker thema stijlen
zen-dark-theme-styles-description = Pas het donkere thema aan naar wens
zen-dark-theme-styles-amoled = Nacht Thema
zen-dark-theme-styles-default = Standaard donker thema
zen-dark-theme-styles-colorful = Kleurrijk donker thema
zen-split-view-title = Weergave splitsen
zen-split-view-header = Split weergave functionaliteit
zen-split-view-description = Splits je browser in meerdere weergaven, zodat je tegelijk meerdere websites kunt zien
zen-split-view-change-on-hover = 
    .label = Tabbladen wijzigen bij zweven
zen-compact-mode-styles-left = Tabbladbalk verbergen
zen-compact-mode-styles-top = Bovenste balk verbergen
zen-compact-mode-styles-both = Beide verbergen
zen-urlbar-title = Zen URL bar
zen-urlbar-header = Algemene instellingen voor de URL-balk
zen-urlbar-description = Pas de URL-balk aan naar uw wensen
zen-urlbar-behavior-label = Gedrag
zen-urlbar-behavior-normal = 
    .label = Normaal
zen-urlbar-behavior-floating-on-type = 
    .label = Alleen zweven tijdens typen
zen-urlbar-behavior-float = 
    .label = Altijd zweven
pane-zen-CKS-title = Sneltoetsen
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } Sneltoetsen
zen-settings-CKS-header = Aanpassen van je sneltoetsen
zen-settings-CKS-description = Verander de standaard sneltoetsen naar wens en verbeter je surfervaring
zen-settings-CKS-disable-firefox = 
    .label = { -brand-short-name } zijn standaard sneltoetsen uitschakelen
zen-settings-CKS-duplicate-shortcut = 
    .label = Sneltoets dupliceren
zen-settings-CKS-reset-shortcuts = 
    .label = Standaardinstellingen herstellen
zenCKSOption-group-other = Overig
zenCKSOption-group-windowAndTabManagement = Venster- & tabbladbeheer
zenCKSOption-group-navigation = Navigation
zenCKSOption-group-searchAndFind = Zoeken & vinden
zenCKSOption-group-pageOperations = Pagina beheer
zenCKSOption-group-historyAndBookmarks = Geschiedenis & Bladwijzers
zenCKSOption-group-mediaAndDisplay = Media & Weergave
zenCKSOption-group-zen-compact-mode = Compacte modus
zenCKSOption-group-zen-workspace = Werkruimtes
zenCKSOption-group-zen-other = Andere Zen functies
zenCKSOption-group-zen-split-view = Weergave splitsen
zenCKSOption-group-devTools = Developer Tools
zen-key-quick-restart = Snelle herstart
zen-window-new-shortcut = Nieuw venster
zen-tab-new-shortcut = New Tab
zen-key-redo = Opnieuw
zen-restore-last-closed-tab-shortcut = Herstel laatst gesloten tabblad
zen-location-open-shortcut = Open locatie
zen-location-open-shortcut-alt = Open locatie (alternatief)
zen-key-undo-close-window = Ongedaan maken venster sluiten
zen-text-action-undo-shortcut = Herstel
zen-text-action-redo-shortcut = Opnieuw
zen-text-action-cut-shortcut = Knippen
zen-text-action-copy-shortcut = Kopiëren
zen-text-action-copy-url-shortcut = Copy current URL
zen-text-action-paste-shortcut = Plakken
zen-text-action-select-all-shortcut = Alles selecteren
zen-text-action-delete-shortcut = Verwijderen
zen-history-show-all-shortcut-mac = Toon alle geschiedenis (Mac)
zen-full-screen-shortcut = Volledig scherm in-/uitschakelen
zen-reader-mode-toggle-shortcut-windows = Wissel leesmodus (Windows)
zen-picture-in-picture-toggle-shortcut-alt = Picture-in-Picture in-/uitschakelen (alternatief)
zen-picture-in-picture-toggle-shortcut-mac = Picture-in-Picture  in-/uitschakelen (Mac)
zen-picture-in-picture-toggle-shortcut-mac-alt = Picture-in-Picture in-/uitschakelen (Mac alternatief)
zen-page-source-shortcut-safari = Bekijk pagina bron (Safari)
zen-nav-stop-shortcut = Stop met laden
zen-history-sidebar-shortcut = Laat geschiedenis zijbalk zien
zen-window-minimize-shortcut = Venster minimaliseren
zen-help-shortcut = Open Hulp
zen-preferences-shortcut = Open Voorkeuren
zen-hide-app-shortcut = Verberg applicatie
zen-hide-other-apps-shortcut = Andere toepassingen verbergen
zen-search-focus-shortcut = Focus op zoeken
zen-search-focus-shortcut-alt = Focus op zoeken (alternatief)
zen-downloads-shortcut = Downloads openen
zen-addons-shortcut = Open add-ons
zen-file-open-shortcut = Open bestand
zen-save-page-shortcut = Pagina opslaan
zen-print-shortcut = Print Page
zen-close-shortcut-2 = Tabblad sluiten
zen-mute-toggle-shortcut = Dempen in-/uitschakelen
zen-key-delete = Sleutel verwijderen
zen-key-go-back = Ga terug
zen-key-go-forward = Ga vooruit
zen-nav-back-shortcut-alt = Navigeer terug (alternatief)
zen-nav-fwd-shortcut-alt = Navigeer naar voren (alternatief)
zen-history-show-all-shortcut = Alle geschiedenis weergeven
zen-key-enter-full-screen = Volledig Scherm openen
zen-key-exit-full-screen = Volledig Scherm afsluiten
zen-reader-mode-toggle-shortcut-other = Leesmodus in-/uitschakelen
zen-picture-in-picture-toggle-shortcut = Picture-in-Picture in-/uitschakelen
zen-nav-reload-shortcut-2 = Pagina opnieuw laden
zen-key-about-processes = Over processen
zen-page-source-shortcut = Paginabron bekijken
zen-page-info-shortcut = Pagina info bekijken
zen-find-shortcut = Op pagina zoeken
zen-search-find-again-shortcut = Opnieuw zoeken
zen-search-find-again-shortcut-prev = Vorige zoeken
zen-search-find-again-shortcut-2 = Opnieuw zoeken (alternatief)
zen-bookmark-this-page-shortcut = Bladwijzer deze pagina
zen-bookmark-show-library-shortcut = Bladwijzerbibliotheek tonen
zen-key-stop = Stop met laden
zen-full-zoom-reduce-shortcut = Zoom uit
zen-full-zoom-enlarge-shortcut = Zoom in
zen-full-zoom-reset-shortcut = Reset Zoom
zen-bidi-switch-direction-shortcut = Tekstrichting omschakelen
zen-private-browsing-shortcut = Privé browsen
zen-screenshot-shortcut = Maak Screenshot
zen-key-sanitize = Browsergegevens wissen
zen-quit-app-shortcut = Applicatie afsluiten
zen-key-wr-capture-cmd = Opname WR Opdracht
zen-key-wr-toggle-capture-sequence-cmd = WR opnamevolgorde in-/uitschakelen
zen-nav-reload-shortcut = Pagina opnieuw laden
zen-nav-reload-shortcut-skip-cache = Pagina opnieuw laden  (Skip Cache)
zen-close-shortcut = Sluit venster
zen-close-tab-shortcut = Tabblad sluiten
zen-compact-mode-shortcut-show-sidebar = Zwevende zijbalk in-/uitschakelen
zen-compact-mode-shortcut-show-toolbar = Zwevende werkbalk in-/uitschakelen
zen-compact-mode-shortcut-toggle = Compacte modus aan/uit
zen-workspace-shortcut-switch-1 = Overschakelen naar werkruimte 1
zen-workspace-shortcut-switch-2 = Overschakelen naar werkruimte 2
zen-workspace-shortcut-switch-3 = Overschakelen naar werkruimte 3
zen-workspace-shortcut-switch-4 = Overschakelen naar werkruimte 4
zen-workspace-shortcut-switch-5 = Overschakelen naar werkruimte 5
zen-workspace-shortcut-switch-6 = Overschakelen naar werkruimte 6
zen-workspace-shortcut-switch-7 = Overschakelen naar werkruimte 7
zen-workspace-shortcut-switch-8 = Overschakelen naar werkruimte 8
zen-workspace-shortcut-switch-9 = Overschakelen naar werkruimte 9
zen-workspace-shortcut-switch-10 = Overschakelen naar werkruimte 10
zen-workspace-shortcut-forward = Volgende werkruimte
zen-workspace-shortcut-backward = Vorige werkruimte
zen-web-panel-shortcut-toggle = Schakel Web Paneel
zen-sidebar-shortcut-toggle = Schakel zijbalk breedte
zen-pinned-tab-shortcut-reset = Reset de vastgezette tab naar de vastgezette URL
zen-split-view-shortcut-grid = Split-weergave raster in-/uitschakelen
zen-split-view-shortcut-vertical = Split-weergave verticaal in-/uitschakelen
zen-split-view-shortcut-horizontal = Split-Weergave horizontaal in-/uitschakelen
zen-split-view-shortcut-unsplit = Sluit Split-weergave
zen-key-select-tab-1 = Selecteer tabblad 1
zen-key-select-tab-2 = Selecteer tabblad 2
zen-key-select-tab-3 = Selecteer tabblad 3
zen-key-select-tab-4 = Selecteer tabblad 4
zen-key-select-tab-5 = Selecteer tabblad 5
zen-key-select-tab-6 = Selecteer tabblad 6
zen-key-select-tab-7 = Selecteer tabblad 7
zen-key-select-tab-8 = Selecteer tabblad 8
zen-key-select-tab-last = Selecteer laatste tabblad
zen-key-show-all-tabs = Alle tabbladen weergeven
zen-key-goto-history = Ga naar geschiedenis
zen-key-go-home = Ga naar home
zen-bookmark-show-sidebar-shortcut = Bladwijzerzijbalk tonen
zen-bookmark-show-toolbar-shortcut = Bladwijzerwerkbalk tonen
zen-devtools-toggle-shortcut = Toggle DevTools
zen-devtools-toggle-browser-toolbox-shortcut = Toggle Browser Toolbox
zen-devtools-toggle-browser-console-shortcut = Toggle Browser Console
zen-devtools-toggle-responsive-design-mode-shortcut = Toggle Responsive Design Mode
zen-devtools-toggle-inspector-shortcut = Toggle Inspector
zen-devtools-toggle-web-console-shortcut = Toggle Web Console
zen-devtools-toggle-js-debugger-shortcut = Toggle JavaScript Debugger
zen-devtools-toggle-net-monitor-shortcut = Toggle Network Monitor
zen-devtools-toggle-style-editor-shortcut = Toggle Style Editor
zen-devtools-toggle-performance-shortcut = Toggle Performance
zen-devtools-toggle-storage-shortcut = Toggle Storage
zen-devtools-toggle-dom-shortcut = Toggle DOM
zen-devtools-toggle-accessibility-shortcut = Toggle Accessibility
