pane-zen-looks-title = Uiterlijk en gevoel
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Het veranderen van de standaardtaal kan het makkelijker maken voor websites om je te volgen.
zen-look-and-feel-colors-header = Kies een themakleur
zen-look-and-feel-colors-description = Laat { -brand-short-name } er zo uitzien als jij wilt
zen-look-and-feel-use-workspace-colors = 
    .label = Gebruik werkruimte kleuren als voornaamste kleur
pane-zen-side-panels-title = Side Webpanelen
zen-side-panels-header = Algemene instellingen voor webpanelen
zen-side-panels-description = Verhoog de productiviteit door meerdere keer tegelijk te bekijken!
zen-side-panels-enabled = 
    .label = Web Side Panelen inschakelen
zen-side-panels-close-on-blur = 
    .label = Sluit het paneel wanneer de focus verloren gaat als het niet vastgepind is
zen-vertical-tabs-show-bottom-border = 
    .label = Toon rand voor de onderste pictogrammen
sync-currently-syncing-workspaces = Werkruimtes
sync-engine-workspaces = 
    .label = Werkruimtes
    .tooltiptext = Synchroniseer uw werkruimtes met verschillende apparaten
    .accesskey = W
zen-glance-title = Oogopslag
zen-glance-header = Algemene instellingen voor een oogopslag
zen-glance-description = Krijg een snel overzicht van uw links zonder ze te openen in een nieuw tabblad
zen-glance-trigger-label = Trigger methode
zen-glance-enabled = 
    .label = Schakel Glance in
zen-glance-trigger-ctrl-click = 
    .label = Ctrl + Click
zen-glance-trigger-alt-click = 
    .label = ALT + Klik
zen-glance-trigger-shift-click = 
    .label = Shift + klik
zen-glance-trigger-meta-click = 
    .label = Meta (controle) + klik
zen-glance-trigger-mantain-click = 
    .label = Mantain Klik
zen-look-and-feel-compact-view-header = Toon in compacte weergave
zen-look-and-feel-compact-view-description = Toon alleen de werkbalken die u gebruikt!
zen-look-and-feel-compact-view-enabled = 
    .label = { -brand-short-name }compacte modus inschakelen
zen-look-and-feel-compact-view-top-toolbar = 
    .label = De bovenste werkbalk ook verbergen in compacte modus
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Laat kort de werkbalk popup maken bij het wisselen of openen van nieuwe tabbladen in compacte modus
zen-look-and-feel-buttons-header = Stijl knop
zen-look-and-feel-buttons-description = Kies de stijl van de knoppen die je wilt zien
zen-look-and-feel-pilled-buttons = 
    .label = Knoppen bestolen
pane-zen-tabs-title = Tabblad Beheer
category-zen-workspaces = 
    .tooltiptext = { pane-zen-tabs-title }
pane-settings-workspaces-title = Werkruimtes
pane-zen-tabs-unloader-title = Tab Unloader
zen-tabs-unloader-header = Algemene instellingen voor tab unloader
zen-tabs-unloader-description = Automatisch ongebruikte tabbladen niet laden om geheugen op te slaan
zen-tabs-unloader-enabled = 
    .label = Tabblad Unloader inschakelen
zen-tabs-unloader-unload-delay = 
    .label = Tabbladen uitschakelen na
zen-tabs-unloader-unload-delay-description = De tijd in minuten waarna tabbladen worden losgeladen
zen-look-and-feel-compact-toolbar-themed = 
    .label = Gebruik thema achtergrond voor compacte werkbalk
zen-look-and-feel-compact-sidebar-themed = 
    .label = Gebruik thema achtergrond voor compacte werkbalk
pane-zen-pinned-tab-manager-title = Vastgezette tabbladen
zen-pinned-tab-manager-header = Algemene instellingen voor vastgezette tabbladen
zen-pinned-tab-manager-description = Aanvullend gedrag van vaste tabbladen beheren
zen-pinned-tab-manager-restore-pinned-tabs-to-pinned-url = 
    .label = Herstel vaste tabbladen naar hun oorspronkelijk vastgezette URL bij het opstarten
zen-pinned-tab-manager-close-shortcut-behavior-label = Sluit tab snelkoppeling gedrag
zen-pinned-tab-manager-reset-unload-switch-close-shortcut-option = 
    .label = URL, deladen en overschakelen naar volgend tabblad
zen-pinned-tab-manager-unload-switch-close-shortcut-option = 
    .label = Ontladen en overschakelen naar volgend tabblad
zen-pinned-tab-manager-reset-switch-close-shortcut-option = 
    .label = URL resetten en naar volgend tabblad overschakelen
zen-pinned-tab-manager-switch-close-shortcut-option = 
    .label = Wisselen naar volgend tabblad
zen-pinned-tab-manager-reset-close-shortcut-option = 
    .label = Reset URL
zen-pinned-tab-manager-close-close-shortcut-option = 
    .label = Tabblad sluiten
pane-zen-workspaces-header = Werkruimtes
zen-settings-workspaces-header = Algemene instellingen voor werkruimtes
zen-settings-workspaces-description = Met werkruimtes kan je meerdere surfsessies tegelijk hebben!
zen-settings-workspaces-enabled = 
    .label = Werkruimtes inschakelen (Experimenteel)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Verberg de standaard container indicator in de tabbalk
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Toestaan dat werkruimtes hun eigen vastgezette tabbladen hebben
zen-key-unsafed = Niet-opgeslagen snelkoppeling! Gelieve deze veilig te maken door op de "Ontsnap" toets te klikken na het opnieuw in te typen.
zen-key-conflict = Conflict met een andere snelkoppeling
pane-zen-theme-title = Thema instellingen
zen-vertical-tabs-title = Sidebar en tabs lay-out
zen-vertical-tabs-header = Verticale tabbladen
zen-vertical-tabs-description = Beheer uw tabbladen in een verticale layout
zen-vertical-tabs-show-expand-button = 
    .label = Toon Uitvouwknop
zen-vertical-tabs-newtab-under-last-tab = 
    .label = Toon nieuwe tab knop onder het laatste tabblad
zen-vertical-tabs-expand-tabs-by-default = Tabs standaard uitvouwen
zen-vertical-tabs-dont-expand-tabs-by-default = Tabs standaard niet uitbreiden
zen-vertical-tabs-expand-tabs-on-hover = Tabbladen op Hover uitvouwen (zal niet werken aan compacte modus)
zen-vertical-tabs-expand-tabs-header = Hoe tabbladen uitbreiden
zen-vertical-tabs-expand-tabs-description = Kies hoe tabbladen in de zijbalk uit te breiden
zen-theme-marketplace-header = Zen Mods
zen-theme-disable-all-enabled = 
    .title = Disable all mods
zen-theme-disable-all-disabled = 
    .title = Enable all mods
zen-theme-marketplace-description = Find and install mods from the store.
zen-theme-marketplace-remove-button = 
    .label = Remove mod
zen-theme-marketplace-check-for-updates-button = 
    .label = Controleren op updates
zen-theme-marketplace-updates-success = Mods updated successfully
zen-theme-marketplace-updates-fail = Kon geen updates vinden!
zen-theme-marketplace-toggle-enabled-button = 
    .title = Disable mod
zen-theme-marketplace-toggle-disabled-button = 
    .title = Enable mod
zen-theme-marketplace-remove-confirmation = Weet je zeker dat je deze modi wilt verwijderen?
zen-theme-marketplace-close-modal = Afsluiten
zen-theme-marketplace-theme-header-title = 
    .title = CSS-kiezer: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = geen
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Typ iets...
pane-zen-marketplace-title = Zen Mods
zen-settings-workspaces-display-as-icon-strip = 
    .label = Werkruimtes weergeven als pictogramstrip
zen-settings-workspaces-force-container-tabs-to-workspace = 
    .label = Schakel over naar de werkruimte waar container als standaard is ingesteld bij het openen van containertabbladen
zen-settings-workspaces-hide-deactivated-workspaces = 
    .label = Verberg gedeactiveerde werkruimtes
zen-theme-marketplace-link = Bezoek Winkel
zen-dark-theme-styles-header = Donker Thema Stijlen
zen-dark-theme-styles-description = Pas het donkere thema aan uw wens aan
zen-dark-theme-styles-amoled = Nacht Thema
zen-dark-theme-styles-default = Standaard Donker Thema
zen-dark-theme-styles-colorful = Kleurrijk donker thema
zen-split-view-title = Weergave splitsen
zen-split-view-header = Splits weergave functionaliteit
zen-split-view-description = Splits je browser in meerdere weergaven, zodat je tegelijk door meerdere websites kunt bladeren
zen-split-view-change-on-hover = 
    .label = Tabbladen wijzigen bij zweven
zen-compact-mode-styles-left = Tabbladbalk verbergen
zen-compact-mode-styles-top = Bovenste balk verbergen
zen-compact-mode-styles-both = Beide verbergen
pane-zen-CKS-title = Toetsenbord snelkoppelingen
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } Sneltoetsen
zen-settings-CKS-header = Aanpassen van je sneltoetsen
zen-settings-CKS-description = Verander de standaard sneltoetsen naar wens en verbeter je surfervaring
zen-settings-CKS-disable-firefox = 
    .label = { -brand-short-name }zijn standaard sneltoetsen uitschakelen
zen-settings-CKS-duplicate-shortcut = 
    .label = Duplicate Shortcut
zen-settings-CKS-reset-shortcuts = 
    .label = Standaardinstellingen herstellen
zenCKSOption-group-other = anders
zenCKSOption-group-windowAndTabManagement = Venster & Tabbladbeheer
zenCKSOption-group-navigation = Navigation
zenCKSOption-group-searchAndFind = Zoeken & zoeken
zenCKSOption-group-pageOperations = Pagina bewerkingen
zenCKSOption-group-historyAndBookmarks = Geschiedenis & Bladwijzers
zenCKSOption-group-mediaAndDisplay = Media & Weergave
zenCKSOption-group-zen-compact-mode = Compacte modus
zenCKSOption-group-zen-workspace = Werkruimtes
zenCKSOption-group-zen-other = Andere Zen functies
zenCKSOption-group-zen-split-view = Weergave splitsen
zen-key-quick-restart = Snelle herstart
zen-window-new-shortcut = Nieuw venster
zen-tab-new-shortcut = New Tab
zen-key-redo = Opnieuw
zen-restore-last-closed-tab-shortcut = Herstel laatste gesloten tabblad
zen-location-open-shortcut = Open locatie
zen-location-open-shortcut-alt = Open locatie (alternatief)
zen-key-undo-close-window = Ongedaan maken venster sluiten
zen-text-action-undo-shortcut = Herstel
zen-text-action-redo-shortcut = Opnieuw
zen-text-action-cut-shortcut = Knippen
zen-text-action-copy-shortcut = Kopiëren
zen-text-action-paste-shortcut = Plakken
zen-text-action-select-all-shortcut = Alles selecteren
zen-text-action-delete-shortcut = Verwijderen
zen-history-show-all-shortcut-mac = Toon alle geschiedenis (Mac)
zen-full-screen-shortcut = Volledig scherm in-/uitschakelen
zen-reader-mode-toggle-shortcut-windows = Wissel lezermodus (Windows)
zen-picture-in-picture-toggle-shortcut-alt = Afbeelding in-/uitschakelen (alternatief)
zen-picture-in-picture-toggle-shortcut-mac = Toggle Picture-in-Picture (Mac)
zen-picture-in-picture-toggle-shortcut-mac-alt = Picture-in-Picture in-/uitschakelen (Mac Alt)
zen-page-source-shortcut-safari = Bekijk pagina bron (Safari)
zen-nav-stop-shortcut = Stop met laden
zen-history-sidebar-shortcut = Show History Sidebar
zen-window-minimize-shortcut = Venster minimaliseren
zen-help-shortcut = Open Hulp
zen-preferences-shortcut = Open Voorkeuren
zen-hide-app-shortcut = Verberg applicatie
zen-hide-other-apps-shortcut = Andere toepassingen verbergen
zen-search-focus-shortcut = Focus zoeken
zen-search-focus-shortcut-alt = Focus zoeken (alternatief)
zen-downloads-shortcut = Downloads openen
zen-addons-shortcut = Open add-ons
zen-file-open-shortcut = Open bestand
zen-save-page-shortcut = Pagina opslaan
zen-print-shortcut = Print Page
zen-close-shortcut-2 = Tabblad sluiten
zen-mute-toggle-shortcut = Dempen in-/uitschakelen
zen-key-delete = Sleutel verwijderen
zen-key-go-back = Ga terug
zen-key-go-forward = Ga vooruit
zen-nav-back-shortcut-alt = Navigeer terug (alternatief)
zen-nav-fwd-shortcut-alt = Navigeer naar voren (alternatief)
zen-history-show-all-shortcut = Alle geschiedenis weergeven
zen-key-enter-full-screen = Schermvullende weergave invoeren
zen-key-exit-full-screen = Volledig Scherm afsluiten
zen-reader-mode-toggle-shortcut-other = Leesmodus in-/uitschakelen
zen-picture-in-picture-toggle-shortcut = Afbeelding in-/uitschakelen
zen-nav-reload-shortcut-2 = Pagina opnieuw laden
zen-key-about-processes = Over processen
zen-page-source-shortcut = Paginabron bekijken
zen-page-info-shortcut = Pagina-info bekijken
zen-find-shortcut = Op pagina zoeken
zen-search-find-again-shortcut = Opnieuw zoeken
zen-search-find-again-shortcut-prev = Vorige zoeken
zen-search-find-again-shortcut-2 = Opnieuw zoeken (alternatief)
zen-bookmark-this-page-shortcut = Bladwijzer deze pagina
zen-bookmark-show-library-shortcut = Bladwijzerbibliotheek tonen
zen-key-stop = Stop met laden
zen-full-zoom-reduce-shortcut = Zoom uit
zen-full-zoom-enlarge-shortcut = Zoom in
zen-full-zoom-reset-shortcut = Reset Zoom
zen-bidi-switch-direction-shortcut = Tekstrichting omschakelen
zen-private-browsing-shortcut = Privé browsen
zen-screenshot-shortcut = Maak Screenshot
zen-key-sanitize = Browsergegevens wissen
zen-quit-app-shortcut = Applicatie afsluiten
zen-key-wr-capture-cmd = Opname WR Opdracht
zen-key-wr-toggle-capture-sequence-cmd = WR-opnamevolgorde in-/uitschakelen
zen-nav-reload-shortcut = Pagina opnieuw laden
zen-nav-reload-shortcut-skip-cache = Reload Page (Skip Cache)
zen-close-shortcut = Sluit venster
zen-close-tab-shortcut = Tabblad sluiten
zen-compact-mode-shortcut-show-sidebar = Zwevende zijbalk in-/uitschakelen
zen-compact-mode-shortcut-show-toolbar = Zwevende werkbalk in-/uitschakelen
zen-compact-mode-shortcut-toggle = Compacte modus aan/uit
zen-workspace-shortcut-switch-1 = Overschakelen naar werkruimte 1
zen-workspace-shortcut-switch-2 = Overschakelen naar werkruimte 2
zen-workspace-shortcut-switch-3 = Overschakelen naar werkruimte 3
zen-workspace-shortcut-switch-4 = Overschakelen naar werkruimte 4
zen-workspace-shortcut-switch-5 = Overschakelen naar werkruimte 5
zen-workspace-shortcut-switch-6 = Overschakelen naar werkruimte 6
zen-workspace-shortcut-switch-7 = Overschakelen naar werkruimte 7
zen-workspace-shortcut-switch-8 = Overschakelen naar werkruimte 8
zen-workspace-shortcut-switch-9 = Overschakelen naar werkruimte 9
zen-workspace-shortcut-switch-10 = Overschakelen naar Werkruimte 10
zen-workspace-shortcut-forward = Doorsturen van werkruimte
zen-workspace-shortcut-backward = Achterwaarts werkruimte
zen-web-panel-shortcut-toggle = Schakel Web Paneel
zen-sidebar-shortcut-toggle = Schakel Sidebar's breedte
zen-pinned-tab-shortcut-reset = Reset de vastgezette tab naar de vastgezette URL
zen-split-view-shortcut-grid = Toggle Split-weergave raster
zen-split-view-shortcut-vertical = Wissel Split-weergave verticaal
zen-split-view-shortcut-horizontal = Toggle Split-Weergave horizontaal
zen-split-view-shortcut-unsplit = Sluit Split-weergave
zen-key-select-tab-1 = Select tab #1
zen-key-select-tab-2 = Select tab #2
zen-key-select-tab-3 = Select tab #3
zen-key-select-tab-4 = Selecteer tabblad #4
zen-key-select-tab-5 = Selecteer tabblad #5
zen-key-select-tab-6 = Select tab #6
zen-key-select-tab-7 = Selecteer tabblad #7
zen-key-select-tab-8 = Select tab #8
zen-key-select-tab-last = Selecteer laatste tabblad
zen-key-show-all-tabs = Alle tabbladen weergeven
zen-key-goto-history = Ga naar geschiedenis
zen-key-go-home = Ga naar huis
zen-bookmark-show-sidebar-shortcut = Bladwijzerzijbalk tonen
zen-bookmark-show-toolbar-shortcut = Bladwijzerwerkbalk tonen
