pane-zen-looks-title = Εμφάνιση και Αίσθηση
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Η αλλαγή της προεπιλεγμένης γλώσσας θα βοηθήσει τις ιστοσελίδες να σας παρακολουθούν.
zen-look-and-feel-colors-header = Διαλέξτε ένα χρώμα θέματος
zen-look-and-feel-colors-description = Κάντε το { -brand-short-name } να μοιάζει όπως σας αρέσει
zen-look-and-feel-themed-toolbar = 
    .label = Τροποποιήστε τη γραμμή εργαλείων με βάση το χρώμα έμφασης
pane-zen-side-panels-title = Πλαϊνοί Πίνακες Ιστού
zen-side-panels-header = Γενικές ρυθμίσεις για τους πίνακες ιστού
zen-side-panels-description = Αυξήστε την παραγωγικότητα έχοντας πολλαπλές προβολές ταυτόχρονα!
zen-side-panels-enabled = 
    .label = Ενεργοποίηση Πλαϊνών Πινάκων Ιστού
zen-side-panels-close-on-blur = 
    .label = Κλείσιμο πίνακα όταν χάνεται η εστίαση, αν δεν είναι καρφιτσωμένος
zen-look-and-feel-compact-view-header = Εμφάνιση σε συμπαγή προβολή
zen-look-and-feel-compact-view-description = Εμφάνιση μόνο των γραμμών εργαλείων που χρησιμοποιείτε!
zen-look-and-feel-compact-view-enabled = 
    .label = Ενεργοποίηση συμπαγούς λειτουργίας του { -brand-short-name }
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Απόκρυψη και της επάνω γραμμής εργαλείων σε συμπαγή λειτουργία
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Σύντομη ανάδυση της γραμμής εργαλείων κατά την εναλλαγή ή το άνοιγμα νέων καρτελών σε συμπαγή λειτουργία
zen-look-and-feel-buttons-header = Στυλ κουμπιού
zen-look-and-feel-buttons-description = Επιλέξτε το στυλ των κουμπιών που θέλετε να βλέπετε
zen-look-and-feel-pilled-buttons = 
    .label = Κουμπιά Σχήματος Χαπιού
pane-zen-workspaces-title = Χώροι εργασίας
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = Χώροι εργασίας
pane-zen-workspaces-header = Χώροι εργασίας
zen-settings-workspaces-header = Γενικές ρυθμίσεις για χώρους εργασίας
zen-settings-workspaces-description = Με τους χώρους εργασίας, μπορείτε να έχετε πολλαπλές συνεδρίες περιήγησης ταυτόχρονα!
zen-settings-workspaces-enabled = 
    .label = Ενεργοποίηση Χώρων Εργασίας (Πειραματικό)
pane-zen-theme-title = Ρυθμίσεις Θέματος
zen-vertical-tabs-title = Πλευρική γραμμή και διάταξη καρτελών
zen-vertical-tabs-header = Κάθετες Καρτέλες
zen-vertical-tabs-description = Διαχειριστείτε τις καρτέλες σας σε μια κάθετη διάταξη
zen-vertical-tabs-show-expand-button = 
    .label = Εμφάνιση Κουμπιού Επέκτασης
zen-vertical-tabs-expand-tabs-by-default = Επέκταση Καρτελών από Προεπιλογή
zen-vertical-tabs-dont-expand-tabs-by-default = Να μην Επεκτείνονται οι Καρτέλες από Προεπιλογή
zen-vertical-tabs-expand-tabs-on-hover = Επέκταση καρτελών κατά την Αιώρηση (δε δουλεύει σε συμπαγή λειτουργία)
zen-vertical-tabs-expand-tabs-header = Πώς να επεκτείνετε τις καρτέλες
zen-vertical-tabs-expand-tabs-description = Επιλέξτε πώς να επεκτείνετε τις καρτέλες στην πλευρική γραμμή
zen-theme-marketplace-header = Κατάστημα Θεμάτων
zen-theme-marketplace-description = Εύρεση και εγκατάσταση θεμάτων από το κατάστημα.
zen-theme-marketplace-remove-button = 
    .label = Αφαίρεση Θέματος
zen-theme-marketplace-check-for-updates-button = 
    .label = Έλεγχος για ενημερώσεις
zen-theme-marketplace-updates-success = Το θέμα ενημερώθηκε επιτυχώς
zen-theme-marketplace-updates-fail = Δεν βρέθηκε καμία ενημέρωση!
pane-zen-marketplace-title = Κατάστημα Θεμάτων
zen-look-and-feel-legacy-toolbar = 
    .label = Χρήση απαρχαιωμένης θέσης γραμμής εργαλείων. Απαιτείται επανεκκίνηση!
zen-theme-marketplace-link = Επισκεφθείτε το Κατάστημα
zen-dark-theme-styles-header = Στυλ Σκούρου Θέματος
zen-dark-theme-styles-description = Προσαρμόστε το σκοτεινό θέμα σύμφωνα με τις προτιμήσεις σας
zen-dark-theme-styles-amoled = Amoled Μαύρο
zen-dark-theme-styles-default = Προεπιλεγμένο Σκοτεινό Θέμα
zen-dark-theme-styles-colorful = Πολύχρωμο Σκοτεινό Θέμα
pane-zen-CKS-title = Συντομεύσεις Πληκτρολογίου
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = Συντομεύσεις Πληκτρολογίου { -brand-short-name }
zen-settings-CKS-header = Προσαρμόστε τις συντομεύσεις πληκτρολογίου
zen-settings-CKS-description = Προσαρμόστε τις προεπιλεγμένες συντομεύσεις πληκτρολογίου στις προτιμήσεις σας και βελτιώστε την εμπειρία περιήγησής σας
zen-settings-CKS-disable-firefox = 
    .label = Απενεργοποίηση των προεπιλεγμένων συντομεύσεων πληκτρολογίου του { -brand-short-name }
zen-cks-group-tab-action = Ενέργειες Καρτέλας
zen-cks-group-page-action = Ενέργειες Σελίδας
zen-cks-group-visible-action = Ορατές Ενέργειες
zen-cks-group-history-action = Ενέργειες Ιστορικού
zen-cks-group-search-action = Ενέργειες Αναζήτησης
zen-cks-group-tools-action = Ενέργειες Εργαλείων
zen-cks-group-bookmark-action = Ενέργειες Σελιδοδείκτη
zen-cks-group-open-page-action = Άνοιγμα Ενεργειών Σελίδας
zen-cks-group-downloads-action = Ενέργειες Λήψεων
zen-cks-group-sidebar-action = Ενέργειες Πλευρικής Γραμμής
zen-cks-group-compact-mode-action = Ενέργειες Συμπαγούς Λειτουργίας
zen-cks-group-split-view-action = Ενέργειες Διαιρεμένης Προβολής
zen-cks-group-workspace-action = Ενέργειες Χώρου Εργασίας
open-new-tab = Άνοιγμα Νέας Καρτέλας
close-tab = Κλείσιμο Καρτέλας
open-new-window = Άνοιγμα Νέου Παραθύρου
open-new-private-window = Άνοιγμα Νέου Ιδιωτικού Παραθύρου
close-window = Κλείσιμο Παραθύρου
restore-last-tab = Επαναφορά Τελευταίας Καρτέλας
restore-last-window = Επαναφορά Τελευταίου Παραθύρου
show-next-tab = Εμφάνιση Επόμενης Καρτέλας
show-previous-tab = Εμφάνιση Προηγούμενης Καρτέλας
show-all-tabs-panel = Εμφάνιση Πίνακα Όλες οι Καρτέλες
send-with-mail = Αποστολή σελίδας με Email
save-page = Αποθήκευση Σελίδας
print-page = Εκτύπωση Σελίδας
mute-current-tab = Σίγαση Τρέχουσας Καρτέλας
show-source-of-page = Εμφάνιση Πηγής Σελίδας
show-page-info = Προβολή Πληροφοριών Σελίδας
zoom-in = Μεγέθυνση
zoom-out = Σμίκρυνση
reset-zoom = Επαναφορά Μεγένθυνσης
back = Πίσω
forward = Μπροστά
stop = Διακοπή
reload = Επαναφόρτωση
force-reload = Επιβολή Επαναφόρτωσης
search-in-this-page = Αναζήτηση σ' Αυτή τη Σελίδα
show-next-search-result = Εμφάνιση Αποτέλεσματος Επόμενης Αναζήτησης
show-previous-search-result = Εμφάνιση Αποτέλεσματος Προηγούμενης Αναζήτησης
search-the-web = Αναζήτηση στον Ιστό
open-migration-wizard = Άνοιγμα Οδηγού Μετακίνησης
quit-from-application = Έξοδος Εφαρμογής
enter-into-customize-mode = Enter Customize Mode
enter-into-offline-mode = Enter Offline Mode
open-screen-capture = Open Screen Capture
bookmark-this-page = Bookmark This Page
open-bookmark-add-tool = Open Bookmark Add Tool
open-bookmarks-manager = Open Bookmarks Manager
toggle-bookmark-toolbar = Toggle Bookmark Toolbar
open-general-preferences = Open General Preferences
open-privacy-preferences = Open Privacy Preferences
open-workspaces-preferences = Open Workspaces Preferences
open-containers-preferences = Open Containers Preferences
open-search-preferences = Open Search Preferences
open-sync-preferences = Open Sync Preferences
open-task-manager = Open Task Manager
open-addons-manager = Open Add-ons Manager
open-home-page = Open Home Page
forget-history = Forget History
quick-forget-history = Quick Forget History
clear-recent-history = Clear Recent History
restore-last-session = Restore Last Session
search-history = Search History
manage-history = Manage History
open-downloads = Open Downloads
show-bookmark-sidebar = Show Bookmark Sidebar
show-history-sidebar = Show History Sidebar
show-synced-tabs-sidebar = Show Synced Tabs Sidebar
reverse-sidebar = Reverse Sidebar Position
hide-sidebar = Hide Sidebar
toggle-sidebar = Toggle Sidebar
zen-toggle-web-panels = Toggle Web Panels
zen-toggle-compact-mode = Toggle Compact Mode
zen-toggle-compact-mode-sidebar = Toggle Compact Mode Sidebar
zen-toggle-compact-mode-toolbar = Toggle Compact Mode Toolbar
zen-change-workspace = Cycle Workspaces
zen-split-view-grid = Split View Grid
zen-split-view-vertical = Split View Vertical
zen-split-view-horizontal = Split View Horizontal
zen-split-view-close = Close Split View
zen-expand-sidebar = Toggle Sidebar Expand
