zen-panel-ui-current-profile-text = nuværende profil
unified-extensions-description = Udvidelser bruges til at bringe mere ekstra funktionalitet ind i { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = Nulstil Fastgjort Faneblad
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Erstat fastgjort URL med Nuværende
    .accesskey = C
tab-zen-unload = 
    .label = Unload Tab
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Faner Fjerner Handlinger
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Forhindr Fanebladsaflastning
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Tillad Fanebladsaflastning
    .accesskey = I
zen-themes-corrupted = Din { -brand-short-name } mods-fil er beskadiget. De er blevet nulstillet til standardtemaet.
zen-panel-ui-gradient-generator-opacity-text = Contrast
zen-panel-ui-gradient-generator-texture-text = Tekstur
zen-panel-ui-gradient-generator-custom-color = Brugerdefineret Farve
zen-panel-ui-gradient-generator-saved-message = Gradienten blev gemt med succes!
