zen-panel-ui-current-profile-text = current profile
unified-extensions-description = Extensions are used to bring more extra functionality into { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = Reset Pinned Tab
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Replace Pinned URL with Current
    .accesskey = C
tab-zen-unload = 
    .label = Unload Tab
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Tabs Unloader Actions
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Prevent Tab Unload
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Allow Tab Unload
    .accesskey = I
