zen-web-side-panel-context-mute-panel = 
    .label = Lydløs Webpanel
    .accesskey = Læ
zen-web-side-panel-context-unmute-panel = 
    .label = Fjern Webpanel
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = Deaktiver Mobil UserAgent
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Aktiver Mobil UserAgent
    .accesskey = Læ
zen-web-side-panel-context-unload = 
    .label = Fjern Webpanel
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = Slet Webpanel
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = Åbn i nyt faneblad
    .accesskey = N
zen-web-side-panel-context-open-in-container-tab = 
    .label = Åbn i fanebladet Container
    .accesskey = C
zen-web-side-panel-context-add-to-panel = 
    .label = Tilføj til webpaneler
    .accesskey = A
zen-sidebar-introduction-title = Velkommen til Zen Sidebar
zen-sidebar-introduction-description = Zen Sidebar er en ny måde at surfe på nettet. Klik på et af ikonerne for at åbne et webpanel.
