zen-web-side-panel-context-mute-panel = 
    .label = Slå lyden fra i webpanel
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = Slå lyden til i webpanel
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = Deaktiver Mobil UserAgent
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Aktiver Mobil UserAgent
    .accesskey = Læ
zen-web-side-panel-context-unload = 
    .label = Fjern Webpanel
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = Slet Webpanel
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = Åbn i nyt faneblad
    .accesskey = N
zen-web-side-panel-context-open-in-container-tab = 
    .label = Åbn i fanebladet Container
    .accesskey = C
zen-web-side-panel-context-add-to-panel = 
    .label = Tilføj til webpaneler
    .accesskey = A
zen-webpanel-introduction-title = Velkommen til Zen Webpaneler
zen-webpanel-introduction-description = Webpaneler er en måde at have dine yndlingssider lige ved hånden.
