zen-panel-ui-workspaces-text = Arbejdsområder
zen-panel-ui-workspaces-create = 
    .label = Create Space
zen-panel-ui-workspaces-edit-text = Rediger arbejdsområde
zen-panel-ui-workspaces-edit-save = 
    .label = Gem ændringer
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Annuller
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Slet arbejdsområde
    .accesskey = D
zen-workspaces-panel-change-name = 
    .label = Skift navn
zen-workspaces-panel-change-icon = 
    .label = Skift ikon
zen-workspaces-panel-context-manage = 
    .label = Administrer arbejdsområder
    .accesskey = M
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Indstil standardbeholder
    .accesskey = O
zen-workspaces-change-theme = 
    .label = Edit Theme
zen-workspaces-panel-context-open = 
    .label = Åbn arbejdsområde
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Indstil som standardarbejdsområde
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Rediger arbejdsområde
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Skift fane(r) til arbejdsområde
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Arbejdsområder
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Komplementær
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Split
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Analog
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Triadisk
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Flydende
zen-panel-ui-gradient-click-to-add = Klik for at tilføje en farve
zen-workspace-creation-name = 
    .placeholder = Space Name
zen-workspace-creation-profile = Profile
    .tooltiptext = Profiles are used to separate cookies and site data between spaces.
zen-workspace-creation-title = Create a new Space
zen-workspace-creation-label = Spaces are used to organize your tabs and sessions.
