zen-panel-ui-workspaces-text = Arbejdsområder
zen-panel-ui-workspaces-create-text = Opret arbejdsområde
zen-panel-ui-workspaces-create-save = 
    .label = Opret arbejdsområde
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = Annuller
    .accesskey = C
zen-panel-ui-workspaces-edit-text = Rediger arbejdsområde
zen-panel-ui-workspaces-edit-save = 
    .label = Gem ændringer
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Annuller
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Slet arbejdsområde
    .accesskey = D
zen-workspaces-panel-change-name = 
    .label = Change Name
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Indstil standardbeholder
    .accesskey = O
zen-workspaces-change-gradient = 
    .label = Skift temafarver
    .accesskey = C
zen-workspaces-panel-context-open = 
    .label = Åbn arbejdsområde
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Indstil som standardarbejdsområde
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Rediger arbejdsområde
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Skift fane(r) til arbejdsområde
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Arbejdsområder
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Komplementær
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Split
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Analog
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Triadisk
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Flydende
zen-panel-ui-gradient-click-to-add = Klik for at tilføje en farve
