zen-panel-ui-current-profile-text = profil actuel
unified-extensions-description = Les extensions sont utilisées pour ajouter plus de fonctionnalités à { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = Réinitialiser l'onglet épinglé
    .accesskey = R
tab-context-zen-add-essential = 
    .label = Ajouter à Essentials
    .accesskey = E
tab-context-zen-remove-essential = 
    .label = Retirer d'Essentials
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Remplacer l'URL épinglée par l'actuelle
    .accesskey = C
tab-zen-unload = 
    .label = Décharger l'onglet
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Actions du déchargement des onglets
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Empêcher le déchargement des onglets
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Autoriser le déchargement des onglets
    .accesskey = I
zen-themes-corrupted = Votre fichier de modifs { -brand-short-name } est corrompu. Il a été réinitialisé au thème par défaut.
zen-shortcuts-corrupted = Votre fichier de raccourcis { -brand-short-name } est corrompu. Ils ont été réinitialisés aux raccourcis par défaut.
zen-panel-ui-gradient-generator-opacity-text = Contraste
zen-panel-ui-gradient-generator-texture-text = Texture
zen-panel-ui-gradient-generator-custom-color = Couleur personnalisée
zen-panel-ui-gradient-generator-saved-message = Le dégradé a été enregistré avec succès !
zen-copy-current-url-confirmation = L'URL a été copiée dans le presse-papier.
zen-rice-share-name = 
    .placeholder = Nom
zen-rice-share-author = Par
zen-rice-share-author-input = 
    .placeholder = Votre nom
zen-rice-share-cancel = Annuler
zen-rice-share-save = Partager
zen-rice-share-include-userchrome = 
    .label = Inclure les styles de fenêtre de Zen (userChrome.css)
zen-rice-share-include-usercontent = 
    .label = Inclure les styles du site (userContent.css)
zen-rice-share-include-mods = 
    .label = Inclure les mods activés
zen-rice-share-include-mod-prefs = 
    .label = Inclure les préférences des mods
zen-rice-share-include-preferences = 
    .label = Inclure les préférences de la disposition
zen-rice-share-include-workspace-themes = 
    .label = Inclure les thèmes avec dégradés de l'espace de travail
zen-rice-share-success = Un Rice a été créé avec succès !
zen-rice-share-success-link = Lien de partage Rice
zen-rice-share-accept = Accepter
zen-rice-share-notice = Avant de partager, veuillez comprendre ce qu'est un Rice
# note: Do not translate the "<br/>" tags in the following string
zen-rice-share-notice-description =
    Un Rice est un ensemble de personnalisations qui peuvent être partagées avec les autres.<br/>
    Il s'agit notamment des styles de fenêtre, des styles de site web, des mods activés, des préférences de mods, des préférences de disposition et des thèmes de dégradés de l'espace de travail.<br/>
    En partageant un Rice, vous partagez toutes ces personnalisations avec d'autres personnes. Veuillez faire attention à ce que vous partagez.
zen-learn-more-text = En savoir plus
zen-rice-share-include = Options d'exportation
appmenu-zen-share-rice = 
    .label = Partager le Zen Rice
zen-close-label = Fermer
