zen-web-side-panel-context-mute-panel = 
    .label = Bloquer le panneau Web
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = Réactiver le panneau Web
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = Désactiver l'agent utilisateur mobile
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Activer l'agent utilisateur mobile
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = Décharger le panneau Web
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = Supprimer le panneau Web
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = Ouvrir dans un nouvel onglet
    .accesskey = N
zen-web-side-panel-context-open-in-container-tab = 
    .label = Ouvrir dans l'onglet Conteneur
    .accesskey = C
zen-web-side-panel-context-add-to-panel = 
    .label = Ajouter aux panneaux Web
    .accesskey = A
zen-webpanel-introduction-title = Bienvenue sur Zen Web Panels
zen-webpanel-introduction-description = Les Web Panels sont un moyen de garder vos sites préférés à portée de main.
