zen-panel-ui-current-profile-text = profil actuel
unified-extensions-description = Les extensions sont utilisées pour ajouter plus de fonctionnalités à { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = Réinitialiser l'onglet épinglé
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Remplacer l'URL épinglée par l'actuelle
    .accesskey = C
tab-zen-unload = 
    .label = Décharger l'onglet
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Action de déchargement des onglets
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Empêcher le déchargement de l'onglet
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Permettre le déchargement de l'onglet
    .accesskey = I
