zen-web-side-panel-context-mute-panel = 
    .label = Rendre muet le panneau Web
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = Rétablir le son du panneau Web
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = Désactiver l'agent utilisateur mobile
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Activer l'agent utilisateur mobile
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = Décharger le panneau Web
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = Supprimer le panneau Web
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = Ouvrir dans un nouvel onglet
    .accesskey = N
zen-web-side-panel-context-add-to-panel = 
    .label = Ajouter aux panneaux Web
    .accesskey = A
zen-sidebar-introduction-title = Bienvenue dans la barre latérale de Zen
zen-sidebar-introduction-description = La barre latérale Zen est une nouvelle façon de naviguer sur le Web. Cliquez sur l'une des icônes pour ouvrir un panneau Web.
