zen-toolbar-context-tabs-right = 
    .label = Onglet sur la droite
    .accesskey = R
zen-toolbar-context-compact-mode = 
    .label = Mode compact
    .accesskey = C
zen-toolbar-context-compact-mode-enable = 
    .label = Activer le mode compact
    .accesskey = D
zen-toolbar-context-compact-mode-just-tabs = 
    .label = Masquer la barre latérale
zen-toolbar-context-compact-mode-just-toolbar = 
    .label = Masquer la barre d'outil
zen-toolbar-context-compact-mode-hide-both = 
    .label = Masquer les deux
    .accesskey = H
sidebar-zen-sidepanel = 
    .label = Panneau latéraux
sidebar-zen-expand = 
    .label = Expand Sidebar
