zen-panel-ui-current-profile-text = profil actuel
unified-extensions-description = Les extensions sont utilisées pour ajouter plus de fonctionnalités à { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = Réinitialiser l'onglet épinglé
    .accesskey = R
tab-context-zen-add-essential = 
    .label = Ajouter à Essentials
    .accesskey = E
tab-context-zen-remove-essential = 
    .label = Retirer d'Essentials
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Remplacer l'URL épinglée par l'actuelle
    .accesskey = C
tab-zen-unload = 
    .label = Décharger l'onglet
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Actions du déchargement des onglets
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Empêcher le déchargement des onglets
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Autoriser le déchargement des onglets
    .accesskey = I
zen-themes-corrupted = Votre fichier de modifs { -brand-short-name } est corrompu. Il a été réinitialisé au thème par défaut.
zen-panel-ui-gradient-generator-opacity-text = Contraste
zen-panel-ui-gradient-generator-texture-text = Texture
zen-panel-ui-gradient-generator-custom-color = Couleur personnalisée
zen-panel-ui-gradient-generator-saved-message = Le dégradé a été enregistré avec succès !
zen-copy-current-url-confirmation = L'URL a été copiée dans le presse-papier.
zen-rice-share-name = 
    .placeholder = Rice Name
zen-rice-share-author = By
zen-rice-share-author-input = 
    .placeholder = Your Name
zen-rice-share-cancel = Cancel
zen-rice-share-save = Share
zen-rice-share-include-userchrome = 
    .label = Include userChrome.css
zen-rice-share-include-usercontent = 
    .label = Include userContent.css
zen-rice-share-include-mods = 
    .label = Include enabled mods
zen-rice-share-include-mod-prefs = 
    .label = Include mod preferences
zen-rice-share-include-preferences = 
    .label = Include layout state
zen-rice-share-include-workspace-themes = 
    .label = Include workspace gradient themes
zen-rice-share-include = Export Options
