zen-panel-ui-workspaces-text = Espaces de travail
zen-panel-ui-workspaces-create-text = Créer un espace de travail
zen-panel-ui-workspaces-create-save = 
    .label = Créer un espace de travail
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = Annuler
    .accesskey = C
zen-panel-ui-workspaces-edit-text = Éditer l’espace de travail
zen-panel-ui-workspaces-edit-save = 
    .label = Enregistrer les modifications
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Annuler
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Supprimer l’espace de travail
    .accesskey = D
zen-workspaces-panel-change-name = 
    .label = Modifier le nom
zen-workspaces-panel-change-icon = 
    .label = Changer l'icône
zen-workspaces-panel-context-manage = 
    .label = Gérer les Espaces de travail
    .accesskey = M
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Définir le conteneur par défaut
    .accesskey = O
zen-workspaces-change-gradient = 
    .label = Changer les couleurs du thème
    .accesskey = C
zen-workspaces-panel-context-open = 
    .label = Ouvrir un espace de travail
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Définir comme espace de travail par défaut
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Éditer l’espace de travail
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Déplacer vers l’espace de travail
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Espaces de travail
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Complémentaire
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Fractionné
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Analogue
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Triadique
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Flottant
zen-panel-ui-gradient-click-to-add = Cliquez pour ajouter une couleur
