pane-zen-looks-title = Aparença
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Canviar l'idioma predeterminat podria facilitar que els llocs web et segueixin.
zen-look-and-feel-colors-header = Trieu un color de tema
zen-look-and-feel-colors-description = Fes que { -brand-short-name } tingui l'aspecte que més t'agradi
zen-look-and-feel-use-workspace-colors = 
    .label = Utilitza els colors de l'espai de treball com a color principal
pane-zen-side-panels-title = Panells Web Laterals
zen-side-panels-header = Configuració general per a les pàgines web laterals
zen-side-panels-description = Augmenta la productivitat tenint diverses vistes alhora!
zen-side-panels-enabled = 
    .label = Activa els panells web laterals
zen-side-panels-close-on-blur = 
    .label = Tanca el panell quan perdi el focus si no està fixat
zen-vertical-tabs-show-bottom-border = 
    .label = Mostra el contorn per els icones inferiors
zen-vertical-tabs-layout-header = Disposició del Navegador
zen-vertical-tabs-layout-description = Escull la disposició que et vagi millor
zen-layout-single-toolbar = Barra d'eines singular
zen-layout-multiple-toolbar = Múltiples barres d'eines
zen-layout-collapsed-toolbar = Barra d'eines col·lapsada
sync-currently-syncing-workspaces = Other Workspaces
sync-engine-workspaces = 
    .label = Other Workspaces
    .tooltiptext = Sincronitza l'espai de treball entre dispositius
    .accesskey = W
zen-glance-title = Dona un cop d'ull
zen-glance-header = Ajustaments generals per a donar un cop d'ull
zen-glance-description = Dona una ullada al teus enllaços sense obrir-los en una pestanya nova
zen-glance-trigger-label = Mètode d'activació
zen-glance-enabled = 
    .label = Habilitar el cop d'ull
zen-glance-trigger-ctrl-click = 
    .label = Ctrl + Clic
zen-glance-trigger-alt-click = 
    .label = Alt + Clic
zen-glance-trigger-shift-click = 
    .label = Shift + Click
zen-glance-trigger-meta-click = 
    .label = Meta (Comandament) + Clic
zen-glance-trigger-mantain-click = 
    .label = Mantain Click
zen-look-and-feel-compact-view-header = Mostra en vista compacta
zen-look-and-feel-compact-view-description = Mostra només les barres d'eines que utilitzis!
zen-look-and-feel-compact-view-enabled = 
    .label = Activa el mode compacte de { -brand-short-name }
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Amaga també la barra d'eines superior en mode compacte
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Briefly make the toolbar popup when switching or opening new tabs in compact mode
zen-look-and-feel-buttons-header = Estil del botó
zen-look-and-feel-buttons-description = Tria l'estil dels botons que vols veure
zen-look-and-feel-pilled-buttons = 
    .label = Botons amb forma de pastilla
pane-zen-tabs-title = Tab Management
category-zen-workspaces = 
    .tooltiptext = { pane-zen-tabs-title }
pane-settings-workspaces-title = Espais de treball
pane-zen-tabs-unloader-title = Tab Unloader
zen-tabs-unloader-header = General settings for tab unloader
zen-tabs-unloader-description = Automatically unload unused tabs to save memory
zen-tabs-unloader-enabled = 
    .label = Enable Tab Unloader
zen-tabs-unloader-unload-delay = 
    .label = Unload tabs after
zen-tabs-unloader-unload-delay-description = The time in minutes after which tabs will be unloaded
zen-look-and-feel-compact-toolbar-themed = 
    .label = Use themed background for compact toolbar
zen-look-and-feel-compact-sidebar-themed = 
    .label = Use themed background for compact sidebar
pane-zen-pinned-tab-manager-title = Pinned Tabs
zen-pinned-tab-manager-header = General settings for pinned tabs
zen-pinned-tab-manager-description = Manage additional behavior of pinned tabs
zen-pinned-tab-manager-restore-pinned-tabs-to-pinned-url = 
    .label = Restore pinned tabs to their originally pinned URL on startup
zen-pinned-tab-manager-container-specific-essentials-enabled = 
    .label = Enable container-specific essentials
zen-pinned-tab-manager-close-shortcut-behavior-label = Close Tab Shortcut Behavior
zen-pinned-tab-manager-reset-unload-switch-close-shortcut-option = 
    .label = Reset URL, unload and switch to next tab
zen-pinned-tab-manager-unload-switch-close-shortcut-option = 
    .label = Unload and switch to next tab
zen-pinned-tab-manager-reset-switch-close-shortcut-option = 
    .label = Reset URL and switch to next tab
zen-pinned-tab-manager-switch-close-shortcut-option = 
    .label = Switch to next tab
zen-pinned-tab-manager-reset-close-shortcut-option = 
    .label = Reset URL
zen-pinned-tab-manager-close-close-shortcut-option = 
    .label = Close tab
pane-zen-workspaces-header = Espais de treball
zen-settings-workspaces-header = Configuració general dels espais de treball
zen-settings-workspaces-description = Amb els espais de treball, pots tenir múltiples sessions de navegació alhora!
zen-settings-workspaces-enabled = 
    .label = Activa els espais de treball
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Hide the default container indicator in the tab bar
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Allow workspaces have their own pinned tabs
zen-key-unsaved = Unsaved shortcut! Please save it by clicking the "Escape" key after retyping it.
zen-key-conflict = Conflict with another shortcut
pane-zen-theme-title = Configuració del tema
zen-vertical-tabs-title = Disseny de la barra lateral i pestanyes
zen-vertical-tabs-header = Pestanyes Verticals
zen-vertical-tabs-description = Gestiona les teves pestanyes en un disseny vertical
zen-vertical-tabs-show-expand-button = 
    .label = Mostra el botó d'expansió
zen-vertical-tabs-newtab-on-tab-list = 
    .label = Show New Tab Button on Tab List
zen-vertical-tabs-newtab-top-button-border = 
    .label = Show separation border for when the new tab button is at the bottom
zen-vertical-tabs-newtab-top-button-up = 
    .label = Move the new tab button to the top
zen-vertical-tabs-expand-tabs-by-default = Expandeix les pestanyes per defecte
zen-vertical-tabs-dont-expand-tabs-by-default = No expandeix les pestanyes per defecte
zen-vertical-tabs-expand-tabs-on-hover = Expand Tabs on Hover (Won't work on compact mode)
zen-vertical-tabs-expand-tabs-header = Com expandir les pestanyes
zen-vertical-tabs-expand-tabs-description = Tria com expandir les pestanyes a la barra lateral
zen-theme-marketplace-header = Zen Mods
zen-theme-disable-all-enabled = 
    .title = Disable all themes
zen-theme-disable-all-disabled = 
    .title = Enable all themes
zen-theme-marketplace-description = Troba i instal·la temes des de la botiga.
zen-theme-marketplace-remove-button = 
    .label = Treure el tema
zen-theme-marketplace-check-for-updates-button = 
    .label = Comprova si hi ha actualitzacions
zen-theme-marketplace-updates-success = Tema actualitzat correctament
zen-theme-marketplace-updates-fail = No s'han trobat actualitzacions!
zen-theme-marketplace-toggle-enabled-button = 
    .title = Disable Theme
zen-theme-marketplace-toggle-disabled-button = 
    .title = Enable Theme
zen-theme-marketplace-remove-confirmation = Are you sure you want to remove this mod?
zen-theme-marketplace-close-modal = Close
zen-theme-marketplace-theme-header-title = 
    .title = CSS Selector: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = None
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Type something...
pane-zen-marketplace-title = Zen Mods
zen-settings-workspaces-display-as-icon-strip = 
    .label = Display workspaces as an icon strip
zen-settings-workspaces-force-container-tabs-to-workspace = 
    .label = Switch to workspace where container is set as default when opening container tabs
zen-settings-workspaces-hide-deactivated-workspaces = 
    .label = Hide deactivated workspaces
zen-theme-marketplace-link = Visita la botiga
zen-dark-theme-styles-header = Dark Theme Styles
zen-dark-theme-styles-description = Customize the dark theme to your liking
zen-dark-theme-styles-amoled = Night Theme
zen-dark-theme-styles-default = Default Dark Theme
zen-dark-theme-styles-colorful = Colorful Dark Theme
zen-split-view-title = Split View
zen-split-view-header = Split View Functionality
zen-split-view-description = Split your browser into multiple views, enabling you to browse multiple websites at once
zen-split-view-change-on-hover = 
    .label = Change tabs on hover
zen-compact-mode-styles-left = Hide Tab bar
zen-compact-mode-styles-top = Hide Top bar
zen-compact-mode-styles-both = Hide Both
zen-urlbar-title = Zen URL Bar
zen-urlbar-header = General settings for the URL bar
zen-urlbar-description = Customize the URL bar to your liking
zen-urlbar-behavior-label = Behavior
zen-urlbar-behavior-normal = 
    .label = Normal
zen-urlbar-behavior-floating-on-type = 
    .label = Floating only when typing
zen-urlbar-behavior-float = 
    .label = Always floating
pane-zen-CKS-title = Dreceres de teclat
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = Dreceres de teclat de { -brand-short-name }
zen-settings-CKS-header = Personalitza les teves dreceres de teclat
zen-settings-CKS-description = Canvia les dreceres de teclat per defecte segons les teves preferències i millora la teva experiència de navegació
zen-settings-CKS-disable-firefox = 
    .label = Desactiva les dreceres de teclat per defecte de { -brand-short-name }
zen-settings-CKS-duplicate-shortcut = 
    .label = Duplicate Shortcut
zen-settings-CKS-reset-shortcuts = 
    .label = Reset to Default
zenCKSOption-group-other = Other
zenCKSOption-group-windowAndTabManagement = Window & Tab Management
zenCKSOption-group-navigation = Navigation
zenCKSOption-group-searchAndFind = Search & Find
zenCKSOption-group-pageOperations = Page Operations
zenCKSOption-group-historyAndBookmarks = History & Bookmarks
zenCKSOption-group-mediaAndDisplay = Media & Display
zenCKSOption-group-zen-compact-mode = Compact Mode
zenCKSOption-group-zen-workspace = Other Workspaces
zenCKSOption-group-zen-other = Other Zen Features
zenCKSOption-group-zen-split-view = Split View
zenCKSOption-group-devTools = Developer Tools
zen-key-quick-restart = Quick Restart
zen-window-new-shortcut = New Window
zen-tab-new-shortcut = New Tab
zen-key-redo = Redo
zen-restore-last-closed-tab-shortcut = Restore Last Closed Tab
zen-location-open-shortcut = Open Location
zen-location-open-shortcut-alt = Open Location (Alt)
zen-key-undo-close-window = Undo Close Window
zen-text-action-undo-shortcut = Undo
zen-text-action-redo-shortcut = Redo
zen-text-action-cut-shortcut = Cut
zen-text-action-copy-shortcut = Copy
zen-text-action-copy-url-shortcut = Copy current URL
zen-text-action-copy-url-markdown-shortcut = Copy current URL as Markdown
zen-text-action-paste-shortcut = Paste
zen-text-action-select-all-shortcut = Select All
zen-text-action-delete-shortcut = Delete
zen-history-show-all-shortcut-mac = Show All History (Mac)
zen-full-screen-shortcut = Toggle Full Screen
zen-reader-mode-toggle-shortcut-windows = Toggle Reader Mode (Windows)
zen-picture-in-picture-toggle-shortcut-alt = Toggle Picture-in-Picture (Alt)
zen-picture-in-picture-toggle-shortcut-mac = Toggle Picture-in-Picture (Mac)
zen-picture-in-picture-toggle-shortcut-mac-alt = Toggle Picture-in-Picture (Mac Alt)
zen-page-source-shortcut-safari = View Page Source (Safari)
zen-nav-stop-shortcut = Stop Loading
zen-history-sidebar-shortcut = Mostra la barra lateral d'historial
zen-window-minimize-shortcut = Minimize Window
zen-help-shortcut = Open Help
zen-preferences-shortcut = Open Preferences
zen-hide-app-shortcut = Hide Application
zen-hide-other-apps-shortcut = Hide Other Applications
zen-search-focus-shortcut = Focus Search
zen-search-focus-shortcut-alt = Focus Search (Alt)
zen-downloads-shortcut = Obre les descàrregues
zen-addons-shortcut = Open Add-ons
zen-file-open-shortcut = Open File
zen-save-page-shortcut = Desa la pàgina
zen-print-shortcut = Imprimeix la pàgina
zen-close-shortcut-2 = Tanca la pestanya
zen-mute-toggle-shortcut = Toggle Mute
zen-key-delete = Delete Key
zen-key-go-back = Go Back
zen-key-go-forward = Go Forward
zen-nav-back-shortcut-alt = Navigate Back (Alt)
zen-nav-fwd-shortcut-alt = Navigate Forward (Alt)
zen-history-show-all-shortcut = Show All History
zen-key-enter-full-screen = Enter Full Screen
zen-key-exit-full-screen = Exit Full Screen
zen-reader-mode-toggle-shortcut-other = Toggle Reader Mode
zen-picture-in-picture-toggle-shortcut = Toggle Picture-in-Picture
zen-nav-reload-shortcut-2 = Reload Page
zen-key-about-processes = About Processes
zen-page-source-shortcut = View Page Source
zen-page-info-shortcut = View Page Info
zen-find-shortcut = Find on Page
zen-search-find-again-shortcut = Find Again
zen-search-find-again-shortcut-prev = Find Previous
zen-search-find-again-shortcut-2 = Find Again (Alt)
zen-bookmark-this-page-shortcut = Afegeix aquesta pàgina als marcadors
zen-bookmark-show-library-shortcut = Show Bookmarks Library
zen-key-stop = Stop Loading
zen-full-zoom-reduce-shortcut = Redueix el zoom
zen-full-zoom-enlarge-shortcut = Augmenta el zoom
zen-full-zoom-reset-shortcut = Restableix el zoom
zen-bidi-switch-direction-shortcut = Switch Text Direction
zen-private-browsing-shortcut = Private Browsing
zen-screenshot-shortcut = Take Screenshot
zen-key-sanitize = Clear Browsing Data
zen-quit-app-shortcut = Sortir de l'aplicació
zen-key-wr-capture-cmd = WR Capture Command
zen-key-wr-toggle-capture-sequence-cmd = Toggle WR Capture Sequence
zen-nav-reload-shortcut = Reload Page
zen-nav-reload-shortcut-skip-cache = Reload Page (Skip Cache)
zen-close-shortcut = Tanca la finestra
zen-close-tab-shortcut = Tanca la pestanya
zen-compact-mode-shortcut-show-sidebar = Toggle Floating Sidebar
zen-compact-mode-shortcut-show-toolbar = Toggle Floating Toolbar
zen-compact-mode-shortcut-toggle = Canvia el mode compacte
zen-workspace-shortcut-switch-1 = Switch to Workspace 1
zen-workspace-shortcut-switch-2 = Switch to Workspace 2
zen-workspace-shortcut-switch-3 = Switch to Workspace 3
zen-workspace-shortcut-switch-4 = Switch to Workspace 4
zen-workspace-shortcut-switch-5 = Switch to Workspace 5
zen-workspace-shortcut-switch-6 = Switch to Workspace 6
zen-workspace-shortcut-switch-7 = Switch to Workspace 7
zen-workspace-shortcut-switch-8 = Switch to Workspace 8
zen-workspace-shortcut-switch-9 = Switch to Workspace 9
zen-workspace-shortcut-switch-10 = Switch to Workspace 10
zen-workspace-shortcut-forward = Forward Workspace
zen-workspace-shortcut-backward = Backward Workspace
zen-web-panel-shortcut-toggle = Toggle Web Panel
zen-sidebar-shortcut-toggle = Toggle Sidebar's Width
zen-pinned-tab-shortcut-reset = Reset Pinned Tab to Pinned URL
zen-split-view-shortcut-grid = Toggle Split View Grid
zen-split-view-shortcut-vertical = Toggle Split View Vertical
zen-split-view-shortcut-horizontal = Toggle Split View Horizontal
zen-split-view-shortcut-unsplit = Tanca la vista dividida
zen-key-select-tab-1 = Select tab #1
zen-key-select-tab-2 = Select tab #2
zen-key-select-tab-3 = Select tab #3
zen-key-select-tab-4 = Select tab #4
zen-key-select-tab-5 = Select tab #5
zen-key-select-tab-6 = Select tab #6
zen-key-select-tab-7 = Select tab #7
zen-key-select-tab-8 = Select tab #8
zen-key-select-tab-last = Select last tab
zen-key-show-all-tabs = Show all tabs
zen-key-goto-history = Go to history
zen-key-go-home = Go Home
zen-bookmark-show-sidebar-shortcut = Show Bookmarks Sidebar
zen-bookmark-show-toolbar-shortcut = Show Bookmarks Toolbar
zen-devtools-toggle-shortcut = Toggle DevTools
zen-devtools-toggle-browser-toolbox-shortcut = Toggle Browser Toolbox
zen-devtools-toggle-browser-console-shortcut = Toggle Browser Console
zen-devtools-toggle-responsive-design-mode-shortcut = Toggle Responsive Design Mode
zen-devtools-toggle-inspector-shortcut = Toggle Inspector
zen-devtools-toggle-web-console-shortcut = Toggle Web Console
zen-devtools-toggle-js-debugger-shortcut = Toggle JavaScript Debugger
zen-devtools-toggle-net-monitor-shortcut = Toggle Network Monitor
zen-devtools-toggle-style-editor-shortcut = Toggle Style Editor
zen-devtools-toggle-performance-shortcut = Toggle Performance
zen-devtools-toggle-storage-shortcut = Toggle Storage
zen-devtools-toggle-dom-shortcut = Toggle DOM
zen-devtools-toggle-accessibility-shortcut = Toggle Accessibility
