pane-zen-looks-title = Aparença
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Canviar l'idioma predeterminat podria facilitar que els llocs web et segueixin.
zen-look-and-feel-colors-header = Trieu un color de tema
zen-look-and-feel-colors-description = Fes que { -brand-short-name } tingui l'aspecte que més t'agradi
zen-look-and-feel-themed-toolbar = 
    .label = Fes que la barra d'eines tingui el tema amb el color d'accent
pane-zen-side-panels-title = Panells Web Laterals
zen-side-panels-header = Configuració general per a les pàgines web laterals
zen-side-panels-description = Augmenta la productivitat tenint diverses vistes alhora!
zen-side-panels-enabled = 
    .label = Activa els panells web laterals
zen-side-panels-close-on-blur = 
    .label = Tanca el panell quan perdi el focus si no està fixat
zen-look-and-feel-compact-view-header = Mostra en vista compacta
zen-look-and-feel-compact-view-description = Mostra només les barres d'eines que utilitzis!
zen-look-and-feel-compact-view-enabled = 
    .label = Activa el mode compacte de { -brand-short-name }
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Amaga també la barra d'eines superior en mode compacte
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Briefly make the toolbar popup when switching or opening new tabs in compact mode
zen-look-and-feel-buttons-header = Estil del botó
zen-look-and-feel-buttons-description = Tria l'estil dels botons que vols veure
zen-look-and-feel-pilled-buttons = 
    .label = Botons amb forma de pastilla
pane-zen-workspaces-title = Espais de treball
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = Espais de treball
pane-zen-workspaces-header = Espais de treball
zen-settings-workspaces-header = Configuració general dels espais de treball
zen-settings-workspaces-description = Amb els espais de treball, pots tenir múltiples sessions de navegació alhora!
zen-settings-workspaces-enabled = 
    .label = Activa els espais de treball (Experimental)
pane-zen-theme-title = Configuració del tema
zen-vertical-tabs-title = Disseny de la barra lateral i pestanyes
zen-vertical-tabs-header = Pestanyes Verticals
zen-vertical-tabs-description = Gestiona les teves pestanyes en un disseny vertical
zen-vertical-tabs-show-expand-button = 
    .label = Mostra el botó d'expansió
zen-vertical-tabs-expand-tabs-by-default = Expandeix les pestanyes per defecte
zen-vertical-tabs-dont-expand-tabs-by-default = No expandeix les pestanyes per defecte
zen-vertical-tabs-expand-tabs-on-hover = Expandeix les pestanyes en passar el cursor (No funcionarà en mode compacte)
zen-vertical-tabs-expand-tabs-header = Com expandir les pestanyes
zen-vertical-tabs-expand-tabs-description = Tria com expandir les pestanyes a la barra lateral
zen-theme-marketplace-header = Botiga de Temes
zen-theme-marketplace-description = Troba i instal·la temes des de la botiga.
zen-theme-marketplace-remove-button = 
    .label = Treure el tema
zen-theme-marketplace-check-for-updates-button = 
    .label = Comprova si hi ha actualitzacions
zen-theme-marketplace-updates-success = Tema actualitzat correctament
zen-theme-marketplace-updates-fail = No s'han trobat actualitzacions!
pane-zen-marketplace-title = Botiga de Temes
zen-look-and-feel-legacy-toolbar = 
    .label = Use legacy toolbar position. Requires a restart!
zen-theme-marketplace-link = Visita la botiga
zen-dark-theme-styles-header = Dark Theme Styles
zen-dark-theme-styles-description = Customize the dark theme to your liking
zen-dark-theme-styles-amoled = Amoled Black
zen-dark-theme-styles-default = Default Dark Theme
zen-dark-theme-styles-colorful = Colorful Dark Theme
pane-zen-CKS-title = Dreceres de teclat
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = Dreceres de teclat de { -brand-short-name }
zen-settings-CKS-header = Personalitza les teves dreceres de teclat
zen-settings-CKS-description = Canvia les dreceres de teclat per defecte segons les teves preferències i millora la teva experiència de navegació
zen-settings-CKS-disable-firefox = 
    .label = Desactiva les dreceres de teclat per defecte de { -brand-short-name }
zen-cks-group-tab-action = Accions de Pestanya
zen-cks-group-page-action = Accions de Pàgina
zen-cks-group-visible-action = Accions Visibles
zen-cks-group-history-action = Accions d'Història
zen-cks-group-search-action = Accions de Cerca
zen-cks-group-tools-action = Accions d'Eines
zen-cks-group-bookmark-action = Accions de Marcador
zen-cks-group-open-page-action = Accions d'Obertura de Pàgina
zen-cks-group-downloads-action = Accions de Descarregues
zen-cks-group-sidebar-action = Accions de Barra Lateral
zen-cks-group-compact-mode-action = Accions de Mode Compacte
zen-cks-group-split-view-action = Accions de Vista Dividida
zen-cks-group-workspace-action = Accions d'Espai de Treball
open-new-tab = Obre una nova pestanya
close-tab = Tanca la pestanya
open-new-window = Obre una nova finestra
open-new-private-window = Obre una nova finestra privada
close-window = Tanca la finestra
restore-last-tab = Restaura la darrera pestanya
restore-last-window = Restaura la darrera finestra
show-next-tab = Mostra la següent pestanya
show-previous-tab = Mostra la pestanya anterior
show-all-tabs-panel = Mostra el panell de totes les pestanyes
send-with-mail = Envia la pàgina per correu
save-page = Desa la pàgina
print-page = Imprimeix la pàgina
mute-current-tab = Silencia la pestanya actual
show-source-of-page = Mostra el codi font de la pàgina
show-page-info = Mostra la informació de la pàgina
zoom-in = Augmenta el zoom
zoom-out = Redueix el zoom
reset-zoom = Restableix el zoom
back = Enrere
forward = Endavant
stop = Atura
reload = Torna a carregar
force-reload = Força la recàrrega
search-in-this-page = Cerca en aquesta pàgina
show-next-search-result = Mostra el següent resultat de cerca
show-previous-search-result = Mostra el resultat de cerca anterior
search-the-web = Cerca a la web
open-migration-wizard = Obre l'assistent de migració
quit-from-application = Sortir de l'aplicació
enter-into-customize-mode = Entrar en mode personalització
enter-into-offline-mode = Entrar en mode offline
open-screen-capture = Obre la captura de pantalla
bookmark-this-page = Afegeix aquesta pàgina als marcadors
open-bookmark-add-tool = Obre l'eina d'afegir marcador
open-bookmarks-manager = Obre el gestor de marcadors
toggle-bookmark-toolbar = Canvia la barra d'eines de marcadors
open-general-preferences = Obre les preferències generals
open-privacy-preferences = Obre les preferències de privadesa
open-workspaces-preferences = Obre les preferències d'espais de treball
open-containers-preferences = Obre les preferències de contenidors
open-search-preferences = Obre les preferències de cerca
open-sync-preferences = Obre les preferències de sincronització
open-task-manager = Obre el gestor de tasques
open-addons-manager = Obre el gestor d'extensions
open-home-page = Obre la pàgina d'inici
forget-history = Oblida l'historial
quick-forget-history = Oblida l'historial ràpidament
clear-recent-history = Neteja l'historial recent
restore-last-session = Restaura la darrera sessió
search-history = Cerca a l'historial
manage-history = Gestiona l'historial
open-downloads = Obre les descàrregues
show-bookmark-sidebar = Mostra la barra lateral de marcadors
show-history-sidebar = Mostra la barra lateral d'historial
show-synced-tabs-sidebar = Mostra la barra lateral de pestanyes sincronitzades
reverse-sidebar = Inverteix la posició de la barra lateral
hide-sidebar = Amaga la barra lateral
toggle-sidebar = Canvia la barra lateral
zen-toggle-web-panels = Canvia els panells web
zen-toggle-compact-mode = Canvia el mode compacte
zen-toggle-compact-mode-sidebar = Canvia la barra lateral del mode compacte
zen-toggle-compact-mode-toolbar = Canvia la barra d'eines del mode compacte
zen-change-workspace = Canvia els espais de treball
zen-split-view-grid = Vista dividida en reixeta
zen-split-view-vertical = Vista dividida vertical
zen-split-view-horizontal = Vista dividida horitzontal
zen-split-view-close = Tanca la vista dividida
zen-expand-sidebar = Toggle Sidebar Expand
