zen-web-side-panel-context-mute-panel = 
    .label = Σίγαση Πίνακα Ιστού
    .accesskey = Μ
zen-web-side-panel-context-unmute-panel = 
    .label = Κατάργηση Σίγασης Πίνακα Ιστού
    .accesskey = μ
zen-web-side-panel-context-disable-ua = 
    .label = Απενεργοποίηση Του Φορέα Χρήστη
    .accesskey = Θ
zen-web-side-panel-context-enable-ua = 
    .label = Ενεργοποίηση Φορέα Χρήστη Για Κινητά
    .accesskey = Μ
zen-web-side-panel-context-unload = 
    .label = Αποφόρτωση Πίνακα Ιστού
    .accesskey = ς
zen-web-side-panel-context-delete = 
    .label = Διαγραφή Πίνακα Ιστού
    .accesskey = Δ
zen-web-side-panel-open-in-new-tab = 
    .label = Άνοιγμα σε νέα καρτέλα
    .accesskey = N
zen-web-side-panel-context-open-in-container-tab = 
    .label = Άνοιγμα σε καρτέλα Container
    .accesskey = Ψ
zen-web-side-panel-context-add-to-panel = 
    .label = Προσθήκη στους Πίνακες Ιστού
    .accesskey = Α
zen-sidebar-introduction-title = Καλώς ήλθατε στη Πλευρική Γραμμή Zen
zen-sidebar-introduction-description = Η Πλευρική γραμμη Zen είναι ένας νέος τρόπος για να περιηγηθείτε στο διαδίκτυο. Κάντε κλικ σε οποιοδήποτε από τα εικονίδια για να ανοίξετε έναν πίνακα ιστού.
