zen-panel-ui-workspaces-text = Χώροι Εργασίας
zen-panel-ui-workspaces-create = 
    .label = Create Space
zen-panel-ui-workspaces-edit-text = Επεξεργασία Χώρου Εργασίας
zen-panel-ui-workspaces-edit-save = 
    .label = Αποθήκευση Αλλαγών
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Ακύρωση
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Διαγραφή Χώρου Εργασίας
    .accesskey = D
zen-workspaces-panel-change-name = 
    .label = Change Name
zen-workspaces-panel-change-icon = 
    .label = Change Icon
zen-workspaces-panel-context-manage = 
    .label = Manage Workspaces
    .accesskey = M
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Ορισμός Προεπιλεγμένου Περιέκτη
    .accesskey = O
zen-workspaces-how-to-reorder = To reorder spaces, drag and drop them from the space icons at the bottom of the sidebar.
zen-workspaces-change-theme = 
    .label = Edit Theme
zen-workspaces-panel-context-open = 
    .label = Άνοιγμα Χώρου Εργασίας
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Ορισμός Ως Προεπιλεγμένος Χώρος Εργασίας
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Επεξεργασία Χώρου Εργασίας
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Αλλαγή Καρτελών Σε Χώρο Εργασίας
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Χώροι Εργασίας
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Συμπληρωματικό
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Διάσπαση
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Ανάλογο
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Τριαδικό
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Αιωρούμενο
zen-panel-ui-gradient-click-to-add = Κλικ για προσθήκη χρώματος
zen-workspace-creation-name = 
    .placeholder = Space Name
zen-workspaces-panel-context-reorder = 
    .label = Reorder Workspaces
zen-workspace-creation-profile = Profile
    .tooltiptext = Profiles are used to separate cookies and site data between spaces.
zen-workspace-creation-title = Create a new Space
zen-workspace-creation-label = Spaces are used to organize your tabs and sessions.
