zen-toolbar-context-tabs-right = 
    .label = Καρτέλες στα δεξιά
    .accesskey = R
zen-toolbar-context-compact-mode = 
    .label = Συμπαγής λειτουργία
    .accesskey = C
zen-toolbar-context-compact-mode-enable = 
    .label = Ενεργοποίηση συμπαγούς λειτουργίας
    .accesskey = D
zen-toolbar-context-compact-mode-just-tabs = 
    .label = Hide sidebar
zen-toolbar-context-compact-mode-just-toolbar = 
    .label = Απόκρυψη γραμμής εργαλείων
zen-toolbar-context-compact-mode-hide-both = 
    .label = Απόκρυψη όλων
    .accesskey = H
sidebar-zen-sidepanel = 
    .label = Πλευρικοί Πάνελ
sidebar-zen-expand = 
    .label = Expand Sidebar
