zen-panel-ui-workspaces-text = Χώροι Εργασίας
zen-panel-ui-workspaces-create-text = Δημιουργία Χώρου Εργασίας
zen-panel-ui-workspaces-create-save = 
    .label = Δημιουργία Χώρου Εργασίας
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = Ακύρωση
    .accesskey = C
zen-panel-ui-workspaces-edit-text = Επεξεργασία Χώρου Εργασίας
zen-panel-ui-workspaces-edit-save = 
    .label = Αποθήκευση Αλλαγών
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Ακύρωση
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Διαγραφή Χώρου Εργασίας
    .accesskey = D
zen-workspaces-panel-context-open = 
    .label = Άνοιγμα Χώρου Εργασίας
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Ορισμός Ως Προεπιλεγμένος Χώρος Εργασίας
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Επεξεργασία Χώρου Εργασίας
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Αλλαγή Καρτελών Σε Χώρο Εργασίας
    .accesskey = C
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Ορισμός Προεπιλεγμένου Περιέκτη
    .accesskey = O
zen-workspaces-change-gradient = 
    .label = Αλλαγή Χρωμάτων Θέματος
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Χώροι Εργασίας
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Συμπληρωματικό
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Διάσπαση
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Ανάλογο
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Τριαδικό
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Αιωρούμενο
zen-panel-ui-gradient-click-to-add = Κλικ για προσθήκη χρώματος
