zen-web-side-panel-context-mute-panel = 
    .label = Σίγαση Πίνακα Ιστού
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = Άρση Σίγασης Πίνακα Ιστού
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = Απενεργοποίηση UserAgent κινητής συσκευής
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Ενεργοποίηση UserAgent κινητής συσκευής
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = Αποφόρτωση Πίνακα Ιστού
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = Διαγραφή Πίνακα Ιστού
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = Άνοιγμα σε Νέα Καρτέλα
    .accesskey = N
zen-web-side-panel-context-open-in-container-tab = 
    .label = Open in Container Tab
    .accesskey = C
zen-web-side-panel-context-add-to-panel = 
    .label = Προσθήκη σε Πίνακες Ιστού
    .accesskey = A
zen-sidebar-introduction-title = Καλώς ήλθατε στην Πλευρική Γραμμή του Zen
zen-sidebar-introduction-description = Η Πλευρική Γραμμή Zen είναι ένας νέος τρόπος για να περιηγηθείτε στο διαδίκτυο. Κάντε κλικ σε οποιοδήποτε από τα εικονίδια για να ανοίξετε έναν πίνακα ιστού.
