zen-panel-ui-current-profile-text = τρέχον προφίλ
unified-extensions-description = Οι επεκτάσεις χρησιμοποιούνται για να φέρουν περισσότερη επιπλέον λειτουργικότητα στο { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = Επαναφορά Καρφιτσωμένης Καρτέλας
    .accesskey = R
tab-context-zen-add-essential = 
    .label = Add to Essentials
    .accesskey = E
tab-context-zen-remove-essential = 
    .label = Remove from Essentials
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Αντικατάσταση καρφιτσωμένου URL με το τρέχον
    .accesskey = C
tab-zen-unload = 
    .label = Unload Tab
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Ενέργειες Εκφόρτωσης Καρτελών
    .accesskey = Τ
tab-zen-prevent-unload = 
    .label = Αποτροπή Εκφόρτωσης Καρτέλας
    .accesskey = Ρ
tab-zen-ignore-unload = 
    .label = Επιτρέψτε Την Αφαίρεση Καρτέλας
    .accesskey = I
zen-themes-corrupted = Το αρχείο { -brand-short-name } mods είναι κατεστραμμένο. Έχουν γίνει επαναφορά στο προεπιλεγμένο θέμα.
zen-panel-ui-gradient-generator-opacity-text = Contrast
zen-panel-ui-gradient-generator-texture-text = Υφή
zen-panel-ui-gradient-generator-custom-color = Προσαρμοσμένο Χρώμα
zen-panel-ui-gradient-generator-saved-message = Επιτυχής αποθήκευση της διαβάθμισης!
zen-copy-current-url-confirmation = The URL has been copied to the clipboard.
zen-rice-share-name = 
    .placeholder = Rice Name
zen-rice-share-author = By
zen-rice-share-author-input = 
    .placeholder = Your Name
zen-rice-share-cancel = Cancel
zen-rice-share-save = Share
zen-rice-share-include-userchrome = 
    .label = Include userChrome.css
zen-rice-share-include-usercontent = 
    .label = Include userContent.css
zen-rice-share-include-mods = 
    .label = Include enabled mods
zen-rice-share-include-mod-prefs = 
    .label = Include mod preferences
zen-rice-share-include-preferences = 
    .label = Include layout state
zen-rice-share-include-workspace-themes = 
    .label = Include workspace gradient themes
zen-rice-share-success = Successfully created a Rice!
zen-rice-share-success-link = Rice Share Link
zen-rice-share-include = Export Options
appmenu-zen-share-rice = 
    .label = Share Zen Rice
zen-close-label = Close
