zen-panel-ui-current-profile-text = τρέχον προφίλ
unified-extensions-description = Οι επεκτάσεις χρησιμοποιούνται για να φέρουν περισσότερη επιπλέον λειτουργικότητα στο { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = Επαναφορά Καρφιτσωμένης Καρτέλας
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Αντικατάσταση καρφιτσωμένου URL με το τρέχον
    .accesskey = C
tab-zen-unload = 
    .label = Unload Tab
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Ενέργειες Εκφόρτωσης Καρτελών
    .accesskey = Τ
tab-zen-prevent-unload = 
    .label = Αποτροπή Εκφόρτωσης Καρτέλας
    .accesskey = Ρ
tab-zen-ignore-unload = 
    .label = Επιτρέψτε Την Αφαίρεση Καρτέλας
    .accesskey = I
zen-themes-corrupted = Το αρχείο { -brand-short-name } mods είναι κατεστραμμένο. Έχουν γίνει επαναφορά στο προεπιλεγμένο θέμα.
zen-panel-ui-gradient-generator-opacity-text = Contrast
zen-panel-ui-gradient-generator-texture-text = Υφή
zen-panel-ui-gradient-generator-custom-color = Προσαρμοσμένο Χρώμα
zen-panel-ui-gradient-generator-saved-message = Επιτυχής αποθήκευση της διαβάθμισης!
