zen-panel-ui-current-window-text = Bieżące okno
zen-panel-ui-workspaces-text = Inne przestrzenie robocze
zen-panel-ui-workspaces-create-text = Stwórz przestrzeń roboczą
zen-panel-ui-workspaces-create-save = 
    .label = Stwórz przestrzeń roboczą
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = Anuluj
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Usuń Przestrzeń roboczą
    .accesskey = D
zen-workspaces-panel-context-open = 
    .label = Otwórz Przestrzeń roboczą
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Ustaw jako domyślną Przestrzeń roboczą
    .accesskey = S
context-zen-change-workspace-tab = 
    .label = Zmień Kart(ę/y) w Przestrzeń roboczą
    .accesskey = C
