zen-web-side-panel-context-mute-panel = 
    .label = Wycisz Panel internetowy
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = Wyłącz wyciszenie Panelu bocznego
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = Wyłącz mobilny UserAgent
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Wyłącz mobilny UserAgent
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = Rozładuj Panel internetowy
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = Usuń Panel internetowy
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = Otwórz w Nowej karcie
    .accesskey = N
zen-web-side-panel-context-add-to-panel = 
    .label = Dodaj do Paneli internetowych
    .accesskey = A
zen-sidebar-introduction-title = Witamy w Panelu bocznym Zen
zen-sidebar-introduction-description = Panel boczny Zen jest nowym sposobem na przeglądanie internetu. Kliknij ikonę, aby otworzyć panel internetowy.
