zen-panel-ui-current-profile-text = aktualny profil
unified-extensions-description = Rozszerzenia są używane, aby dodać więcej funkcji w { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = Reset Pinned Tab
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Replace Pinned URL with Current
    .accesskey = C
tab-zen-unload = 
    .label = Usuń z pamięci
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Akcje rozładowywania kart
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Zapobiegaj rozładowaniu karty
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Prevent Tab Unload
    .accesskey = I
