zen-toolbar-context-tabs-right = 
    .label = Karty po prawej
    .accesskey = R
zen-toolbar-context-compact-mode = 
    .label = Tryb kompaktowy
    .accesskey = C
zen-toolbar-context-compact-mode-enable = 
    .label = Włącz tryb kompaktowy
    .accesskey = D
zen-toolbar-context-compact-mode-just-tabs = 
    .label = Ukryj pasek boczny
zen-toolbar-context-compact-mode-just-toolbar = 
    .label = Ukryj pasek narzędzi
zen-toolbar-context-compact-mode-hide-both = 
    .label = Ukryj oba
    .accesskey = H
sidebar-zen-sidepanel = 
    .label = Panele boczne
sidebar-zen-expand = 
    .label = Rozszerz panel boczny
