zen-panel-ui-workspaces-text = Obszary robocze
zen-panel-ui-workspaces-create = 
    .label = Create Space
zen-workspaces-panel-context-delete = 
    .label = Usuń obszar roboczy
    .accesskey = D
zen-workspaces-panel-change-name = 
    .label = Zmień nazwę
zen-workspaces-panel-change-icon = 
    .label = Change Icon
zen-workspaces-panel-context-default-profile = 
    .label = Set Profile
zen-workspaces-how-to-reorder-title = How to reorder spaces
zen-workspaces-how-to-reorder-desc = Drag the space icons at the bottom of the sidebar to reorder them
zen-workspaces-change-theme = 
    .label = Edit Theme
zen-workspaces-panel-context-open = 
    .label = Otwórz obszar roboczy
    .accesskey = Pr
zen-workspaces-panel-context-set-default = 
    .label = Ustaw jako domyślny obszar roboczy
    .accesskey = Pr
zen-workspaces-panel-context-edit = 
    .label = Edytuj obszar roboczy
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Zmień zakładkę na obszar roboczy
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Obszary robocze
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Uzupełniający
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Podzielony
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Analogiczny
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Triadiczny
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Pływający
zen-panel-ui-gradient-click-to-add = Kliknij, aby dodać kolor
zen-workspace-creation-name = 
    .placeholder = Space Name
zen-workspaces-panel-context-reorder = 
    .label = Reorder Spaces
zen-workspace-creation-profile = Profile
    .tooltiptext = Profiles are used to separate cookies and site data between spaces.
zen-workspace-creation-header = Create a Space
zen-workspace-creation-label = Spaces are used to organize your tabs and sessions.
zen-workspaces-delete-workspace-title = Delete Workspace?
zen-workspaces-delete-workspace-body = Are you sure you want to delete this workspace? This action cannot be undone.
