zen-panel-ui-current-profile-text = aktualny profil
unified-extensions-description = Rozszerzenia są używane do zapewnienia większej liczby dodatkowych funkcji w { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = Resetuj przypiętą kartę
    .accesskey = R
tab-context-zen-add-essential = 
    .label = Dodaj do Niezbędnych
    .accesskey = E
tab-context-zen-remove-essential = 
    .label = Usuń z Niezbędnych
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Zastąp przypięty adres URL aktualnym
    .accesskey = C
tab-zen-unload = 
    .label = Uśpij kartę
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Akcje usypiania kart
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Zapobiegaj uśpieniu karty
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Zezwalaj na usypianie kart
    .accesskey = I
zen-themes-corrupted = Twój plik modów { -brand-short-name } jest uszkodzony. Zostały one zresetowane do domyślnego stanu.
zen-shortcuts-corrupted = Your { -brand-short-name } shortcuts file is corrupted. They have been reset to the default shortcuts.
zen-panel-ui-gradient-generator-opacity-text = Kontrast
zen-panel-ui-gradient-generator-texture-text = Tekstura
zen-panel-ui-gradient-generator-custom-color = Niestandardowy kolor
zen-panel-ui-gradient-generator-saved-message = Pomyślnie zapisano gradient!
zen-copy-current-url-confirmation = Adres URL został skopiowany do schowka.
zen-rice-share-name = 
    .placeholder = Nazwa Rice
zen-rice-share-author = Stworzone przez
zen-rice-share-author-input = 
    .placeholder = Twój podpis
zen-rice-share-cancel = Anuluj
zen-rice-share-save = Udostępnij
zen-rice-share-include-userchrome = 
    .label = Uwzględnij style okien Zen (userChrome.css)
zen-rice-share-include-usercontent = 
    .label = Uwzględnij style stron internetowych (userContent.css)
zen-rice-share-include-mods = 
    .label = Uwzględnij aktywne modyfikacje
zen-rice-share-include-mod-prefs = 
    .label = Uwzględnij właściwości modyfikacji
zen-rice-share-include-preferences = 
    .label = Uwzględnij preferencje układu
zen-rice-share-include-workspace-themes = 
    .label = Uwzględnij gradienty z wyglądu przestrzeni roboczych
zen-rice-share-success = Pomyślnie utworzono Rice!
zen-rice-share-success-link = Link do udostępnienia Rice
zen-rice-share-accept = Zaakceptuj
zen-rice-share-notice = Zanim udostępnisz, zrozum proszę czym jest Rice
# note: Do not translate the "<br/>" tags in the following string
zen-rice-share-notice-description =
    A Rice is a collection of customizations that can be shared with others.<br/>
    This includes your window styles, website styles, enabled mods, mod preferences, layout preferences, and workspace gradient themes.<br/>
    By sharing a Rice, you are sharing all of these customizations with others. Please be mindful of what you share.
zen-learn-more-text = Dowiedz się więcej
zen-rice-share-include = Opcje udostępniania
appmenu-zen-share-rice = 
    .label = Udostępnij Zen Rice
zen-close-label = Zamknij
