zen-web-side-panel-context-mute-panel = 
    .label = Wycisz Panel Internetowy
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = Włącz Dźwięk w Panelu Internetowym
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = Wyłącz mobilny UserAgent
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Wyłącz mobilny UserAgent
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = Rozładuj Panel Internetowy
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = Usuń Panel Internetowy
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = Otwórz w Nowej Karcie
    .accesskey = N
zen-web-side-panel-context-add-to-panel = 
    .label = Dodaj do Paneli Internetowych
    .accesskey = A
zen-sidebar-introduction-title = Witamy do Zen Panel Boczny
zen-sidebar-introduction-description = Zen Panel Boczny jest nowy sposób do przeglądania internetu. Kliknij ikonę, aby otworzyć panel internetowy.
