zen-panel-ui-workspaces-text = Inne Przestrzenie Robocze
zen-panel-ui-workspaces-create-text = Stwórz Przestrzeń Roboczą
zen-panel-ui-workspaces-create-save = 
    .label = Stwórz Przestrzeń Roboczą
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = Anuluj
    .accesskey = C
zen-panel-ui-workspaces-edit-text = Edytuj Przestrzeń Roboczą
zen-panel-ui-workspaces-edit-save = 
    .label = Zapisz Zmiany
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Anuluj
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Usuń Przestrzeń roboczą
    .accesskey = D
zen-workspaces-panel-context-open = 
    .label = Otwórz Przestrzeń Roboczą
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Ustaw jako Domyślną Przestrzeń Roboczą
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Edytuj Przestrzeń Roboczą
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Zmień Kart(ę/y) w Przestrzeń Roboczą
    .accesskey = C
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Ustaw domyślny kontener
    .accesskey = O
zen-workspaces-change-gradient = 
    .label = Zmień kolory motywu
    .accesskey = C
