files:
  - source: en-US/browser/zen-general.ftl
    translation: browser/zen-general.ftl

  - source: en-US/browser/zen-split-view.ftl
    translation: browser/zen-split-view.ftl
    
  - source: en-US/browser/zen-vertical-tabs.ftl
    translation: browser/zen-vertical-tabs.ftl

  - source: en-US/browser/zen-web-side-panels.ftl
    translation: browser/zen-web-side-panels.ftl

  - source: en-US/browser/zen-welcome.ftl
    translation: browser/zen-welcome.ftl

  - source: en-US/browser/zen-workspaces.ftl
    translation: browser/zen-workspaces.ftl

  - source: en-US/browser/zenAppExtensionFields.ftl
    translation: browser/zenAppExtensionFields.ftl

  - source: en-US/browser/zenNewWebPanel.ftl
    translation: browser/zenNewWebPanel.ftl

  - source: en-US/browser/preferences/zen-preferences.ftl
    translation: browser/preferences/zen-preferences.ftl
