zen-web-side-panel-context-mute-panel = 
    .label = 静音网页面板
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = 取消网页面板静音
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = 禁用移动 UserAgent
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = 启用移动 UserAgent
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = 卸载网页面板
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = 删除网页面板
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = 在新标签页中打开
    .accesskey = N
zen-web-side-panel-context-add-to-panel = 
    .label = 添加到网页面板
    .accesskey = A
zen-sidebar-introduction-title = 欢迎使用 Zen 侧边栏
zen-sidebar-introduction-description = Zen 侧边栏是一种新的上网方式。单击任意图标即可打开一个网络面板。
