zen-web-side-panel-context-mute-panel = 
    .label = Mute Web Panel
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = Unmute Web Panel
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = Disable Mobile UserAgent
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Enable Mobile UserAgent
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = Unload Web Panel
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = Delete Web Panel
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = Open in New Tab
    .accesskey = N
zen-web-side-panel-context-add-to-panel = 
    .label = Add to Web Panels
    .accesskey = A
zen-sidebar-introduction-title = Welcome to Zen Sidebar
zen-sidebar-introduction-description = Zen 侧边栏是一种上网新方式。单击任意图标即可打开网络面板。
