zen-panel-ui-current-window-text = 当前窗口
zen-panel-ui-workspaces-text = 其他工作区
zen-panel-ui-workspaces-create-text = 创建工作区
zen-panel-ui-workspaces-create-save = 
    .label = 创建工作区
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = 取消
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = 删除工作区
    .accesskey = D
zen-workspaces-panel-context-open = 
    .label = 开启工作区
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = 设为默认工作区
    .accesskey = S
context-zen-change-workspace-tab = 
    .label = 将标签页(们)切换至工作区
    .accesskey = C
