zen-panel-ui-current-profile-text = 当前配置
unified-extensions-description = 扩展用于为 { -brand-short-name } 带来更多额外功能。
tab-zen-unload = 
    .label = 卸载标签页
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = 标签页卸载动作
    .accesskey = T
tab-zen-prevent-unload = 
    .label = 阻止标签页卸载
    .accesskey = P
tab-zen-ignore-unload = 
    .label = 忽略标签页卸载
    .accesskey = I
