zen-web-side-panel-context-mute-panel = 
    .label = 静音Web 面板
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = 取消Web 面板静音
    .accesskey = 米
zen-web-side-panel-context-disable-ua = 
    .label = 禁用移动用户代理
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = 启用移动用户代理
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = 卸载Web 面板
    .accesskey = 瓦文
zen-web-side-panel-context-delete = 
    .label = 删除Web 面板
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = 在新标签中打开
    .accesskey = N
zen-web-side-panel-context-open-in-container-tab = 
    .label = 在容器选项卡中打开
    .accesskey = C
zen-web-side-panel-context-add-to-panel = 
    .label = 添加到网页版面板
    .accesskey = A
zen-sidebar-introduction-title = 欢迎来到Zen 侧边栏
zen-sidebar-introduction-description = Zen 侧边栏是浏览网页的新方式。点击任意图标打开网页面板。
