zen-toolbar-context-tabs-right = 
    .label = 右侧标签页
    .accesskey = R
zen-toolbar-context-compact-mode = 
    .label = 紧凑模式
    .accesskey = C
zen-toolbar-context-compact-mode-enable = 
    .label = 启用紧凑模式
    .accesskey = D
zen-toolbar-context-compact-mode-just-tabs = 
    .label = 隐藏侧边栏
zen-toolbar-context-compact-mode-just-toolbar = 
    .label = 隐藏工具栏
zen-toolbar-context-compact-mode-hide-both = 
    .label = 两者同时隐藏
    .accesskey = H
sidebar-zen-sidepanel = 
    .label = 侧边面板
sidebar-zen-expand = 
    .label = 展开侧边栏
