zen-panel-ui-current-profile-text = 当前配置
unified-extensions-description = 扩展用于为 { -brand-short-name } 带来更多额外功能。
tab-context-zen-reset-pinned-tab = 
    .label = 重置固定标签页
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = 将固定的 URL 替换为当前页面 URL
    .accesskey = C
tab-zen-unload = 
    .label = 卸载标签页
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = 标签页卸载行为
    .accesskey = T
tab-zen-prevent-unload = 
    .label = 防止标签页卸载
    .accesskey = P
tab-zen-ignore-unload = 
    .label = 允许标签页卸载
    .accesskey = I
zen-themes-corrupted = 您的 { -brand-short-name } 模组文件已损坏。它们已重置为默认主题。
zen-panel-ui-gradient-generator-opacity-text = 对比度
zen-panel-ui-gradient-generator-texture-text = 材质
zen-panel-ui-gradient-generator-custom-color = 自定义颜色
zen-panel-ui-gradient-generator-saved-message = 渐变保存成功！
