zen-panel-ui-current-window-text = 当前窗口
zen-panel-ui-workspaces-text = 其它工作空间
zen-panel-ui-workspaces-create-text = 创建工作空间
zen-panel-ui-workspaces-create-save = 
    .label = 创建工作空间
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = 取消
    .accesskey = C
zen-panel-ui-workspaces-edit-text = 编辑工作空间
zen-panel-ui-workspaces-edit-save = 
    .label = 保存更改
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = 取消
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = 删除工作空间
    .accesskey = D
zen-workspaces-panel-context-open = 
    .label = 打开工作空间
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = 设为默认工作空间
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = 编辑工作空间
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = 将标签页切换至工作空间
    .accesskey = C
zen-workspaces-panel-context-open-in-container-tab = 
    .label = 设为默认容器
    .accesskey = O
