zen-panel-ui-current-profile-text = 当前配置
unified-extensions-description = 扩展用于为 { -brand-short-name } 带来更多额外功能。
tab-context-zen-reset-pinned-tab = 
    .label = 重置置置顶标签
    .accesskey = R
tab-context-zen-add-essential = 
    .label = Add to Essentials
    .accesskey = E
tab-context-zen-remove-essential = 
    .label = Remove from Essentials
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = 用当前链接替换固定的 URL
    .accesskey = C
tab-zen-unload = 
    .label = Unload Tab
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = 标签卸载操作
    .accesskey = T
tab-zen-prevent-unload = 
    .label = 防止标签卸载
    .accesskey = P
tab-zen-ignore-unload = 
    .label = 允许标签卸载
    .accesskey = 一
zen-themes-corrupted = 您的 { -brand-short-name } 模组文件已损坏。它们已重置为默认主题。
zen-panel-ui-gradient-generator-opacity-text = Contrast
zen-panel-ui-gradient-generator-texture-text = 纹理
zen-panel-ui-gradient-generator-custom-color = 自定义颜色
zen-panel-ui-gradient-generator-saved-message = 成功保存渐变！
