pane-zen-looks-title = Hãy nhìn và cảm nhận
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Thay đổi ngôn ngữ mặc định có thể khiến các trang web theo dõi dễ dàng hơn.
zen-look-and-feel-colors-header = Chọn màu chủ đề
zen-look-and-feel-colors-description = Tùy chỉnh giao diện { -brand-short-name } theo cách của bạn
zen-look-and-feel-themed-toolbar = 
    .label = Làm cho thanh công cụ có cùng màu với màu điểm nhấn
pane-zen-side-panels-title = Bảng điều khiển bên của Web
zen-side-panels-header = Cài đặt chung cho bảng điều khiển web
zen-side-panels-description = Tăng năng suất với nhiều chế độ xem cùng lúc!
zen-side-panels-enabled = 
    .label = Kích hoạt Bảng điều khiển bên của Web
zen-side-panels-close-on-blur = 
    .label =
        Đóng bảng điều khiển khi mất tiêu điểm nếu
         không được ghim
zen-look-and-feel-compact-view-header = Hiển thị ở chế độ thu gọn
zen-look-and-feel-compact-view-description = Chỉ hiển thị các thanh công cụ mà bạn sử dụng!
zen-look-and-feel-compact-view-enabled = 
    .label = Bật chế độ thu gọn của { -brand-short-name }
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Ẩn thanh công cụ trên cùng trong chế độ thu gọn
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Briefly make the toolbar popup when switching or opening new tabs in compact mode
zen-look-and-feel-buttons-header = Kiểu nút nhấn
zen-look-and-feel-buttons-description = Chọn kiểu nút nhấn mà bạn muốn xem
zen-look-and-feel-pilled-buttons = 
    .label = Nút hình viên thuốc
pane-zen-workspaces-title = Không gian làm việc
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = Không gian làm việc
pane-zen-workspaces-header = Không gian làm việc
zen-settings-workspaces-header = Cài đặt chung cho không gian làm việc
zen-settings-workspaces-description = Bạn có thể lướt nhiều phiên duyệt web cùng lúc với không gian làm việc!
zen-settings-workspaces-enabled = 
    .label = Bật không gian làm việc (Thử nghiệm)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Hide the default container indicator in the tab bar
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Allow workspaces have their own pinned tabs
pane-zen-theme-title = Cài đặt chủ đề
zen-vertical-tabs-title = Bố cục thanh bên và tab
zen-vertical-tabs-header = Tab dọc
zen-vertical-tabs-description = Quản lý các tab của bạn trong bố cục dọc
zen-vertical-tabs-show-expand-button = 
    .label = Hiển thị nút Mở rộng
zen-vertical-tabs-expand-tabs-by-default = Mở rộng các tab theo mặc định
zen-vertical-tabs-dont-expand-tabs-by-default = Không mở rộng các tab theo mặc định
zen-vertical-tabs-expand-tabs-on-hover = Mở rộng các tab khi di chuột (Không hoạt động ở chế độ thu gọn)
zen-vertical-tabs-expand-tabs-header = Cách mở rộng tab
zen-vertical-tabs-expand-tabs-description = Chọn cách mở rộng tab trong thanh bên
zen-theme-marketplace-header = Zen Mods
zen-theme-marketplace-description = Tìm và cài đặt chủ đề từ cửa hàng
zen-theme-marketplace-remove-button = 
    .label = Xóa chủ đề
zen-theme-marketplace-check-for-updates-button = 
    .label = Check for Updates
zen-theme-marketplace-updates-success = Chủ đề được cập nhật thành công
zen-theme-marketplace-updates-fail = Không tìm thấy bản cập nhật!
zen-theme-marketplace-toggle-enabled-button = 
    .title = Disable Theme
zen-theme-marketplace-toggle-disabled-button = 
    .title = Enable Theme
zen-theme-marketplace-remove-confirmation = Are you sure you want to remove this theme?
zen-theme-marketplace-close-modal = Close
zen-theme-marketplace-theme-header-title = 
    .title = CSS Selector: { $name }
pane-zen-marketplace-title = Zen Mods
zen-settings-workspaces-display-as-icon-strip = 
    .label = Display workspaces as an icon strip
zen-theme-marketplace-link = Vào cửa hàng
zen-dark-theme-styles-header = Dark Theme Styles
zen-dark-theme-styles-description = Customize the dark theme to your liking
zen-dark-theme-styles-amoled = Night Theme
zen-dark-theme-styles-default = Default Dark Theme
zen-dark-theme-styles-colorful = Colorful Dark Theme
pane-zen-CKS-title = Phím tắt
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } Phím tắt
zen-settings-CKS-header = Tùy chỉnh phím tắt
zen-settings-CKS-description = Thay đổi các phím tắt mặc định theo sở thích và cải thiện trải nghiệm duyệt web của bạn
zen-settings-CKS-disable-firefox = 
    .label = Vô hiệu hóa các phím tắt mặc định của { -brand-short-name }
zen-cks-group-tab-action = Phím tắt tab
zen-cks-group-page-action = Hành động trang
zen-cks-group-visible-action = Hành động hiển thị
zen-cks-group-history-action = Hành động lịch sử
zen-cks-group-search-action = Hành động tìm kiếm
zen-cks-group-tools-action = Phím tắt công cụ
zen-cks-group-bookmark-action = Phím tắt dấu trang
zen-cks-group-open-page-action = Phím tắt mở trang
zen-cks-group-downloads-action = Phím tắt tải xuống
zen-cks-group-sidebar-action = Phím tắt thanh bên
zen-cks-group-compact-mode-action = Phím tắt chế độ thu gọn
zen-cks-group-split-view-action = Phím tắt chia chế độ xem
zen-cks-group-workspace-action = Phím tắt không gian làm việc
open-new-tab = Mở tab mới
close-tab = Đóng tab
open-new-window = Mở cửa sổ mới
open-new-private-window = Mở cửa sổ riêng tư mới
close-window = Đóng cửa sổ
restore-last-tab = Khôi phục lại tab mới nhất
restore-last-window = Khôi phục cửa sổ mới nhất
show-next-tab = Hiển thị tab tiếp theo
show-previous-tab = Hiển thị tab trước
show-all-tabs-panel = Hiển thị tất cả các tab
send-with-mail = Gửi trang qua email
save-page = Lưu trang
print-page = In trang
mute-current-tab = Tắt tiếng tab hiện tại
show-source-of-page = Xem nguồn trang
show-page-info = Xem thông tin trang
zoom-in = Phóng to
zoom-out = Thu nhỏ
reset-zoom = Đặt lại mức thu phóng
back = Quay lại
forward = Chuyển tiếp
stop = Dừng
reload = Tải lại
force-reload = Bắt buộc tải lại
search-in-this-page = Tìm kiếm trong trang
show-next-search-result = Hiển thị kết quả tìm tiếp theo
show-previous-search-result = Hiển thị kết quả tìm trước đó
search-the-web = Tìm trên Web
open-migration-wizard = Mở trình hướng dẫn chuyển dữ liệu
quit-from-application = Thoát ứng dụng
enter-into-customize-mode = Vào chế độ tùy chỉnh
enter-into-offline-mode = Vào chế độ ngoại tuyến
open-screen-capture = Chụp màn hình
bookmark-this-page = Thêm vào dấu trang
open-bookmark-add-tool = Mở công cụ thêm dấu trang
open-bookmarks-manager = Mở trình điều khiển dấu trang
toggle-bookmark-toolbar = Bật/tắt thanh công cụ đánh dấu trang
open-general-preferences = Mở cài đặt chung
open-privacy-preferences = Mở tùy chọn quyền riêng tư
open-workspaces-preferences = Mở tùy chọn không gian làm việc
open-containers-preferences = Mở tùy chọn khoang chứa
open-search-preferences = Mở tùy chọn tìm kiếm
open-sync-preferences = Mở tùy chọn đồng bộ
open-task-manager = Mở trình quản lý tác vụ
open-addons-manager = Mở trình quản lý tiện ích mở rộng
open-home-page = Mở Trang chủ
forget-history = Xóa lịch sử
quick-forget-history = Xóa nhanh lịch sử
clear-recent-history = Xóa lịch sử gần đây
restore-last-session = Khôi phục phiên gần nhất
search-history = Lịch sử tìm kiếm
manage-history = Quản lý lịch sử
open-downloads = Mở bảng tải xuống
show-bookmark-sidebar = Mở thanh bên dấu trang
show-history-sidebar = Mở thanh bên lịch sử
show-synced-tabs-sidebar = Hiển thị thanh bên tab đồng bộ
reverse-sidebar = Đảo ngược vị trí thanh bên
hide-sidebar = Ẩn thanh bên
toggle-sidebar = Bật/tắt thanh bên
zen-toggle-web-panels = Bật/tắt bảng điều khiển web
zen-toggle-compact-mode = Bật/tắt chế độ thu gọn
zen-toggle-compact-mode-sidebar = Bật/tắt chế độ thu gọn thanh bên
zen-toggle-compact-mode-toolbar = Bật/tắt chế độ thu gọn thanh công cụ
zen-change-workspace = Di chuyển giữa các không gian làm việc
zen-split-view-grid = Chia chế độ xem lưới
zen-split-view-vertical = Chia chế độ xem dọc
zen-split-view-horizontal = Chia chế độ xem ngang
zen-split-view-close = Đóng chế độ xem chia đôi
zen-expand-sidebar = Toggle Sidebar Expand
