pane-zen-looks-title = Giao diện
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Thay đổi ngôn ngữ mặc định có thể khiến các trang web theo dõi dễ dàng hơn.
zen-look-and-feel-colors-header = Chọn màu chủ đề
zen-look-and-feel-colors-description = Tùy chỉnh giao diện { -brand-short-name } theo cách của bạn
zen-look-and-feel-use-workspace-colors = 
    .label = Dùng màu của khu vực làm việc như màu chính
pane-zen-side-panels-title = Thanh bên của trang
zen-side-panels-header = Cài đặt chung cho bảng điều khiển web
zen-side-panels-description = Tăng năng suất với nhiều chế độ xem cùng lúc!
zen-side-panels-enabled = 
    .label = Bật thanh bên của trang web
zen-side-panels-close-on-blur = 
    .label =
        Đóng bảng điều khiển khi mất tiêu điểm nếu
         không được ghim
zen-vertical-tabs-layout-header = Giao diện trình duyệt
zen-vertical-tabs-layout-description = Chọn giao diện phù hợp với bạn nhất
zen-layout-single-toolbar = Thanh công cụ tích hợp
zen-layout-multiple-toolbar = Đa thanh công cụ
zen-layout-collapsed-toolbar = Thanh công cụ tinh giản
sync-currently-syncing-workspaces = Không gian làm việc khác
sync-engine-workspaces = 
    .label = Không gian làm việc
    .tooltiptext = Đồng bộ hóa không gian làm việc giữa các thiết bị
    .accesskey = W
zen-glance-title = Xem trước
zen-glance-header = Thiết lập chung cho xem trước
zen-glance-description = Xem trước đường dãn của bạn trong thẻ hiện tại
zen-glance-trigger-label = Phương pháp kích hoạt
zen-glance-enabled = 
    .label = Kích hoạt Glance
zen-glance-trigger-ctrl-click = 
    .label = Ctrl + Click
zen-glance-trigger-alt-click = 
    .label = Alt + Click
zen-glance-trigger-shift-click = 
    .label = Shift + Click
zen-glance-trigger-meta-click = 
    .label = Meta (Command) + Click
zen-glance-trigger-mantain-click = 
    .label = Mantain Click
zen-look-and-feel-compact-view-header = Hiển thị ở chế độ thu gọn
zen-look-and-feel-compact-view-description = Chỉ hiển thị các thanh công cụ mà bạn sử dụng!
zen-look-and-feel-compact-view-enabled = 
    .label = Bật chế độ thu gọn của { -brand-short-name }
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Ẩn thanh công cụ trên cùng trong chế độ thu gọn
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Thanh bên hiện lên khi chuyển tab hoặc mở tab mới trong chế độ thu gọn
pane-zen-tabs-title = Quản lí tab
category-zen-workspaces = 
    .tooltiptext = { pane-zen-tabs-title }
pane-settings-workspaces-title = Không gian làm việc
pane-zen-tabs-unloader-title = Giải phóng tab
zen-tabs-unloader-header = Cài đặt chung cho giải phóng tab
zen-tabs-unloader-description = Tự động giải phóng tab để tiết kiệm bộ nhớ
zen-tabs-unloader-enabled = 
    .label = Mở giải phóng tab
zen-tabs-unloader-unload-delay = 
    .label = Giải phóng tab sau
zen-tabs-unloader-unload-delay-description = Thời gian ở phút các tab sẽ bị giải phóng khi không sử dụng
zen-look-and-feel-compact-toolbar-themed = 
    .label = Sử dụng màu của trình duyệt cho thanh công cụ tích hợp
zen-look-and-feel-compact-sidebar-themed = 
    .label = Sử dụng màu của trình duyệt cho thành công cụ tinh giản
pane-zen-pinned-tab-manager-title = Gim thẻ
zen-pinned-tab-manager-header = Thiết lập chùng cho các thẻ đã gim
zen-pinned-tab-manager-description = Quản lý thêm hành vi của  các thẻ đã gim
zen-pinned-tab-manager-restore-pinned-tabs-to-pinned-url = 
    .label = Khôi phục thẻ đã gim về đường dẫn gốc khi khởi động trình duyệt
zen-pinned-tab-manager-container-specific-essentials-enabled = 
    .label = Enable container-specific essentials
zen-pinned-tab-manager-close-shortcut-behavior-label = Hành vi của phím tắt đóng thẻ
zen-pinned-tab-manager-reset-unload-switch-close-shortcut-option = 
    .label = Tải tại đường dẫn, đóng và chuyển sang thẻ tiếp theo
zen-pinned-tab-manager-unload-switch-close-shortcut-option = 
    .label = Đóng và chuyển sáng thẻ tiếp theo
zen-pinned-tab-manager-reset-switch-close-shortcut-option = 
    .label = Đặt lại URL và chuyển sang tab tiếp theo
zen-pinned-tab-manager-switch-close-shortcut-option = 
    .label = Chuyển sang tab tiếp theo
zen-pinned-tab-manager-reset-close-shortcut-option = 
    .label = Đặt lại URL
zen-pinned-tab-manager-close-close-shortcut-option = 
    .label = Đóng tab
pane-zen-workspaces-header = Không gian làm việc
zen-settings-workspaces-header = Cài đặt chung cho không gian làm việc
zen-settings-workspaces-description = Bạn có thể lướt nhiều phiên duyệt web cùng lúc với không gian làm việc!
zen-settings-workspaces-enabled = 
    .label = Bật không gian làm việc (Thử nghiệm)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Ẩn chỉ báo vùng chứa mặc định trên thanh tab
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Cho phép các không gian làm việc có thẻ ghim riêng
zen-key-unsaved = Lối tắt không an toàn! Xin hãy làm an toàn nó bằng cách ấn nút "Escape/Esc" sau khi nhập lại nó.
zen-key-conflict = Trùng với lối tắt khác
pane-zen-theme-title = Cài đặt chủ đề
zen-vertical-tabs-title = Bố cục thanh bên và tab
zen-vertical-tabs-header = Tab dọc
zen-vertical-tabs-description = Quản lý các tab của bạn trong bố cục dọc
zen-vertical-tabs-show-expand-button = 
    .label = Hiển thị nút Mở rộng
zen-vertical-tabs-newtab-on-tab-list = 
    .label = Bật nút thẻ mới trên thanh điều dường
zen-vertical-tabs-newtab-top-button-border = 
    .label = Thêm làn chia cắt cho nút thẻ mới khi nằm ở dưới 
zen-vertical-tabs-newtab-top-button-up = 
    .label = Di chuyển nút thẻ mới lên đầu 
zen-vertical-tabs-expand-tabs-by-default = Mở rộng các tab theo mặc định
zen-vertical-tabs-dont-expand-tabs-by-default = Không mở rộng các tab theo mặc định
zen-vertical-tabs-expand-tabs-on-hover = Mở rộng khi rê chuột qua (Không hoạt động trong chế độ tinh gọn)
zen-vertical-tabs-expand-tabs-header = Cách mở rộng tab
zen-vertical-tabs-expand-tabs-description = Chọn cách mở rộng tab trong thanh bên
zen-theme-marketplace-header = Zen Mods
zen-theme-disable-all-enabled = 
    .title = Disable all themes
zen-theme-disable-all-disabled = 
    .title = Enable all themes
zen-theme-marketplace-description = Tìm và cài đặt chủ đề từ cửa hàng
zen-theme-marketplace-remove-button = 
    .label = Xóa chủ đề
zen-theme-marketplace-check-for-updates-button = 
    .label = Check for Updates
zen-theme-marketplace-updates-success = Chủ đề được cập nhật thành công
zen-theme-marketplace-updates-fail = Không tìm thấy bản cập nhật!
zen-theme-marketplace-toggle-enabled-button = 
    .title = Tắt chủ đề
zen-theme-marketplace-toggle-disabled-button = 
    .title = Bật chủ đề
zen-theme-marketplace-remove-confirmation = Bạn có chắc muốn xóa Mod này không?
zen-theme-marketplace-close-modal = Đóng
zen-theme-marketplace-theme-header-title = 
    .title = Bộ chọn CSS: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = Không có
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Gõ gì đó...
pane-zen-marketplace-title = Zen Mods
zen-settings-workspaces-display-as-icon-strip = 
    .label = Thay thế không giâm làm việc bằng biểu tượng
zen-settings-workspaces-force-container-tabs-to-workspace = 
    .label = Switch to workspace where container is set as default when opening container tabs
zen-settings-workspaces-hide-deactivated-workspaces = 
    .label = Ẩn các không gian làm việc không kích hoạt 
zen-theme-marketplace-link = Vào cửa hàng
zen-dark-theme-styles-header = Các kiểu chủ đề tối
zen-dark-theme-styles-description = Tùy chỉnh chủ đề tối theo sở thích
zen-dark-theme-styles-amoled = Chủ đề tối
zen-dark-theme-styles-default = Chủ đề tối mặc định
zen-dark-theme-styles-colorful = Chủ đề tối rực rỡ
zen-split-view-title = Chế độ xem chia đôi
zen-split-view-header = Chức năng Chia các tab
zen-split-view-description = Chia nhỏ không gian, cho phép xem nhiều trang web cùng một lúc
zen-split-view-change-on-hover = 
    .label = Thay đổi các thẻ khi di vào
zen-compact-mode-styles-left = Ẩn thanh tab
zen-compact-mode-styles-top = Ẩn thanh trên cùng
zen-compact-mode-styles-both = Ẩn cả hai
zen-urlbar-title = Thanh đường dẫn
zen-urlbar-header = Thiệt lập chung cho thanh đường dẫn 
zen-urlbar-description = Tùy chỉnh thanh đường dẫn theo sở thích
zen-urlbar-behavior-label = Hành vi thanh đường dẫn 
zen-urlbar-behavior-normal = 
    .label = Bình thường
zen-urlbar-behavior-floating-on-type = 
    .label = Tách ra khi nhập 
zen-urlbar-behavior-float = 
    .label = Luôn luôn tách
pane-zen-CKS-title = Phím tắt
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } Phím tắt
zen-settings-CKS-header = Tùy chỉnh phím tắt
zen-settings-CKS-description = Thay đổi các phím tắt mặc định theo sở thích và cải thiện trải nghiệm duyệt web của bạn
zen-settings-CKS-disable-firefox = 
    .label = Vô hiệu hóa các phím tắt mặc định của { -brand-short-name }
zen-settings-CKS-duplicate-shortcut = 
    .label = Lối tắt bị trùng
zen-settings-CKS-reset-shortcuts = 
    .label = Khôi phục về mặc định
zenCKSOption-group-other = Khác
zenCKSOption-group-windowAndTabManagement = Quản lý tab và cửa sổ
zenCKSOption-group-navigation = Điều hướng
zenCKSOption-group-searchAndFind = Tìm kiếm
zenCKSOption-group-pageOperations = Các thao tác trang
zenCKSOption-group-historyAndBookmarks = Lịch sử & Dấu trang
zenCKSOption-group-mediaAndDisplay = Phương tiện và hiển thị
zenCKSOption-group-zen-compact-mode = Chế độ thu gọn
zenCKSOption-group-zen-workspace = Không gian làm việc
zenCKSOption-group-zen-other = Các tính năng khác của Zen
zenCKSOption-group-zen-split-view = Chế độ xem chia đôi
zenCKSOption-group-devTools = Công cụ nhà phát triển
zen-key-quick-restart = Khởi động lại nhanh
zen-window-new-shortcut = Cửa sổ mới
zen-tab-new-shortcut = Tab mới
zen-key-redo = Hoàn tác
zen-restore-last-closed-tab-shortcut = Khôi phục lại tab gần nhất đã đóng
zen-location-open-shortcut = Mở đường dẫn
zen-location-open-shortcut-alt = Mở tại (Alt)
zen-key-undo-close-window = Mở lại cửa sổ đã đóng
zen-text-action-undo-shortcut = Hoàn tác
zen-text-action-redo-shortcut = Làm lại
zen-text-action-cut-shortcut = Cắt
zen-text-action-copy-shortcut = Sao chép
zen-text-action-copy-url-shortcut = Sao chép URL hiện tại
zen-text-action-copy-url-markdown-shortcut = Copy current URL as Markdown
zen-text-action-paste-shortcut = Dán
zen-text-action-select-all-shortcut = Chọn tất cả
zen-text-action-delete-shortcut = Xóa
zen-history-show-all-shortcut-mac = Hiện toàn bị lịch sử (Mac)
zen-full-screen-shortcut = Chuyển đổi chế độ toàn màn hình
zen-reader-mode-toggle-shortcut-windows = Bật/tắt chế độ đọc (Windows)
zen-picture-in-picture-toggle-shortcut-alt = Hình trong hình (Alt)
zen-picture-in-picture-toggle-shortcut-mac = Bật/tắt chế độ hình-trong-hình (Mac)
zen-picture-in-picture-toggle-shortcut-mac-alt = Bật/tắt chế độ hình-trong-hình (Mac Alt)
zen-page-source-shortcut-safari = Xem nguồn trang (Safari)
zen-nav-stop-shortcut = Dừng tải
zen-history-sidebar-shortcut = Mở thanh bên lịch sử
zen-window-minimize-shortcut = Thu nhỏ cửa sổ
zen-help-shortcut = Mở trợ giúp
zen-preferences-shortcut = Mở Tuỳ chọn
zen-hide-app-shortcut = Ẩn ứng dụng
zen-hide-other-apps-shortcut = Ẩn các ứng dụng khác
zen-search-focus-shortcut = Focus Search
zen-search-focus-shortcut-alt = Focus Search (Alt)
zen-downloads-shortcut = Mở bảng tải xuống
zen-addons-shortcut = Mở tiện ích
zen-file-open-shortcut = Mở tập tin
zen-save-page-shortcut = Lưu trang
zen-print-shortcut = In trang
zen-close-shortcut-2 = Đóng Tab
zen-mute-toggle-shortcut = Chuyển chế độ im lặng
zen-key-delete = Xóa phím
zen-key-go-back = Quay lại
zen-key-go-forward = Tiếp theo
zen-nav-back-shortcut-alt = Điều hướng quay lại (Alt)
zen-nav-fwd-shortcut-alt = Điều hướng chuyển tiếp (Alt)
zen-history-show-all-shortcut = Hiện tất cả lịch sử
zen-key-enter-full-screen = Xem toàn màn hình
zen-key-exit-full-screen = Thoát toàn màn hình
zen-ai-chatbot-sidebar-shortcut = Toggle AI Chatbot Sidebar
zen-key-inspector-mac = Toggle Inspector (Mac)
zen-toggle-sidebar-shortcut = Bật thanh bên (Firefox)
zen-reader-mode-toggle-shortcut-other = Chế độ đọc
zen-picture-in-picture-toggle-shortcut = Hình trong hình
zen-nav-reload-shortcut-2 = Tải lại trang
zen-key-about-processes = Về các tiến trình
zen-page-source-shortcut = Xem nguồn trang
zen-page-info-shortcut = Xem thông tin trang
zen-find-shortcut = Tìm kiếm trên trang
zen-search-find-again-shortcut = Tìm lại
zen-search-find-again-shortcut-prev = Tìm trước đó
zen-search-find-again-shortcut-2 = Tìm lại (Alt)
zen-bookmark-this-page-shortcut = Đánh dấu trang này
zen-bookmark-show-library-shortcut = Hiển thị thư viện dấu trang
zen-key-stop = Dừng tải
zen-full-zoom-reduce-shortcut = Thu nhỏ
zen-full-zoom-enlarge-shortcut = Phóng to
zen-full-zoom-reset-shortcut = Đặt lại mức thu phóng
zen-bidi-switch-direction-shortcut = Đổi chiều hiển thị văn bản
zen-private-browsing-shortcut = Duyệt web riêng tư
zen-screenshot-shortcut = Chụp ảnh màn hình
zen-key-sanitize = Dọn dữ liệu duyệt
zen-quit-app-shortcut = Thoát ứng dụng
zen-key-wr-capture-cmd = WR Capture Command
zen-key-wr-toggle-capture-sequence-cmd = Toggle WR Capture Sequence
zen-nav-reload-shortcut = Tải lại trang
zen-nav-reload-shortcut-skip-cache = Tải lại trang (Bỏ qua bộ nhớ đệm)
zen-close-shortcut = Đóng cửa sổ
zen-close-tab-shortcut = Đóng Tab
zen-compact-mode-shortcut-show-sidebar = Bật/Tắt thanh bên lơ lửng
zen-compact-mode-shortcut-show-toolbar = Bật/Tắt thanh công cụ lơ lửng
zen-compact-mode-shortcut-toggle = Bật/tắt chế độ thu gọn
zen-workspace-shortcut-switch-1 = Chuyển sang không gian làm việc 1
zen-workspace-shortcut-switch-2 = Chuyển sang không gian làm việc 2
zen-workspace-shortcut-switch-3 = Chuyển sang không gian làm việc 3
zen-workspace-shortcut-switch-4 = Chuyển sang không gian làm việc 4
zen-workspace-shortcut-switch-5 = Chuyển sang không gian làm việc 5
zen-workspace-shortcut-switch-6 = Chuyển sang không gian làm việc 6
zen-workspace-shortcut-switch-7 = Chuyển sang không gian làm việc 7
zen-workspace-shortcut-switch-8 = Chuyển sang không gian làm việc 8
zen-workspace-shortcut-switch-9 = Chuyển sang không gian làm việc 9
zen-workspace-shortcut-switch-10 = Chuyển sang không gian làm việc 10
zen-workspace-shortcut-forward = Không gian làm việc tiếp theo
zen-workspace-shortcut-backward = Không gian làm việc trước
zen-web-panel-shortcut-toggle = Toggle Web Panel
zen-sidebar-shortcut-toggle = Điều chỉnh độ rộng thanh bên
zen-pinned-tab-shortcut-reset = Reset Pinned Tab to Pinned URL
zen-split-view-shortcut-grid = Toggle Split View Grid
zen-split-view-shortcut-vertical = Toggle Split View Vertical
zen-split-view-shortcut-horizontal = Toggle Split View Horizontal
zen-split-view-shortcut-unsplit = Đóng chế độ xem chia đôi
zen-key-select-tab-1 = Chọn tab #1
zen-key-select-tab-2 = Chọn tab #2
zen-key-select-tab-3 = Chọn tab #3
zen-key-select-tab-4 = Chọn tab #4
zen-key-select-tab-5 = Chọn tab #5
zen-key-select-tab-6 = Chọn tab #6
zen-key-select-tab-7 = Chọn tab #7
zen-key-select-tab-8 = Chọn tab #8
zen-key-select-tab-last = Chọn tab cuối cùng
zen-key-show-all-tabs = Hiện tất cả tab
zen-key-goto-history = Đi đến lịch sử
zen-key-go-home = Về trang chủ
zen-bookmark-show-sidebar-shortcut = Hiện trang đánh dấu ở thanh bên
zen-bookmark-show-toolbar-shortcut = Hiện trang đánh dấu ở thanh công cụ
zen-devtools-toggle-shortcut = Bật/tắt DevTools
zen-devtools-toggle-browser-toolbox-shortcut = Toggle Browser Toolbox
zen-devtools-toggle-browser-console-shortcut = Toggle Browser Console
zen-devtools-toggle-responsive-design-mode-shortcut = Toggle Responsive Design Mode
zen-devtools-toggle-inspector-shortcut = Toggle Inspector
zen-devtools-toggle-web-console-shortcut = Toggle Web Console
zen-devtools-toggle-js-debugger-shortcut = Toggle JavaScript Debugger
zen-devtools-toggle-net-monitor-shortcut = Toggle Network Monitor
zen-devtools-toggle-style-editor-shortcut = Toggle Style Editor
zen-devtools-toggle-performance-shortcut = Toggle Performance
zen-devtools-toggle-storage-shortcut = Toggle Storage
zen-devtools-toggle-dom-shortcut = Toggle DOM
zen-devtools-toggle-accessibility-shortcut = Toggle Accessibility
