pane-zen-looks-title = Hãy nhìn và cảm nhận
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Thay đổi ngôn ngữ mặc định có thể khiến các trang web theo dõi dễ dàng hơn.
zen-look-and-feel-colors-header = Chọn màu chủ đề
zen-look-and-feel-colors-description = Tùy chỉnh giao diện { -brand-short-name } theo cách của bạn
zen-look-and-feel-themed-toolbar = 
    .label = Làm cho thanh công cụ có cùng màu với màu điểm nhấn
pane-zen-side-panels-title = Bảng điều khiển bên của Web
zen-side-panels-header = Cài đặt chung cho bảng điều khiển web
zen-side-panels-description = Tăng năng suất với nhiều chế độ xem cùng lúc!
zen-side-panels-enabled = 
    .label = Kích hoạt Bảng điều khiển bên của Web
zen-side-panels-close-on-blur = 
    .label =
        Đóng bảng điều khiển khi mất tiêu điểm nếu
         không được ghim
zen-look-and-feel-compact-view-header = Hiển thị ở chế độ thu gọn
zen-look-and-feel-compact-view-description = Chỉ hiển thị các thanh công cụ mà bạn sử dụng!
zen-look-and-feel-compact-view-enabled = 
    .label = Bật chế độ thu gọn của { -brand-short-name }
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Ẩn thanh công cụ trên cùng trong chế độ thu gọn
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Thanh bên hiện lên khi chuyển tab hoặc mở tab mới trong chế độ thu gọn
zen-look-and-feel-buttons-header = Kiểu nút nhấn
zen-look-and-feel-buttons-description = Chọn kiểu nút nhấn mà bạn muốn xem
zen-look-and-feel-pilled-buttons = 
    .label = Nút hình viên thuốc
pane-zen-tabs-title = Quản lí tab
category-zen-workspaces = 
    .tooltiptext = { pane-zen-tabs-title }
pane-settings-workspaces-title = Không gian làm việc
pane-zen-tabs-unloader-title = Giải phóng tab
zen-tabs-unloader-header = Cài đặt chung cho giải phóng tab
zen-tabs-unloader-description = Tự động giải phóng tab để tiết kiệm bộ nhớ
zen-tabs-unloader-enabled = 
    .label = Mở giải phóng tab
zen-tabs-unloader-unload-delay = 
    .label = Giải phóng tab sau
zen-tabs-unloader-unload-delay-description = Thời gian ở phút các tab sẽ bị giải phóng khi không sử dụng
pane-zen-workspaces-header = Không gian làm việc
zen-settings-workspaces-header = Cài đặt chung cho không gian làm việc
zen-settings-workspaces-description = Bạn có thể lướt nhiều phiên duyệt web cùng lúc với không gian làm việc!
zen-settings-workspaces-enabled = 
    .label = Bật không gian làm việc (Thử nghiệm)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Ẩn chỉ báo vùng chứa mặc định trên thanh tab
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Allow workspaces have their own pinned tabs
zen-key-unsafed = Unsafed shortcut! Please safe it by clicking the "Escape" key after retyping it.
zen-key-conflict = Trùng với lối tắt khác
pane-zen-theme-title = Cài đặt chủ đề
zen-vertical-tabs-title = Bố cục thanh bên và tab
zen-vertical-tabs-header = Tab dọc
zen-vertical-tabs-description = Quản lý các tab của bạn trong bố cục dọc
zen-vertical-tabs-show-expand-button = 
    .label = Hiển thị nút Mở rộng
zen-vertical-tabs-expand-tabs-by-default = Mở rộng các tab theo mặc định
zen-vertical-tabs-dont-expand-tabs-by-default = Không mở rộng các tab theo mặc định
zen-vertical-tabs-expand-tabs-on-hover = Mở rộng các tab khi di chuột (Không hoạt động ở chế độ thu gọn)
zen-vertical-tabs-expand-tabs-header = Cách mở rộng tab
zen-vertical-tabs-expand-tabs-description = Chọn cách mở rộng tab trong thanh bên
zen-theme-marketplace-header = Zen Mods
zen-theme-marketplace-description = Tìm và cài đặt chủ đề từ cửa hàng
zen-theme-marketplace-remove-button = 
    .label = Xóa chủ đề
zen-theme-marketplace-check-for-updates-button = 
    .label = Check for Updates
zen-theme-marketplace-updates-success = Chủ đề được cập nhật thành công
zen-theme-marketplace-updates-fail = Không tìm thấy bản cập nhật!
zen-theme-marketplace-toggle-enabled-button = 
    .title = Tắt chủ đề
zen-theme-marketplace-toggle-disabled-button = 
    .title = Bật chủ đề
zen-theme-marketplace-remove-confirmation = Bạn có chắc muốn xóa Mod này không?
zen-theme-marketplace-close-modal = Đóng
zen-theme-marketplace-theme-header-title = 
    .title = CSS Selector: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = Không có
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Gõ gì đó...
pane-zen-marketplace-title = Zen Mods
zen-settings-workspaces-display-as-icon-strip = 
    .label = Display workspaces as an icon strip
zen-theme-marketplace-link = Vào cửa hàng
zen-dark-theme-styles-header = Các kiểu chủ đề tối
zen-dark-theme-styles-description = Tùy chỉnh chủ đề tối theo sở thích
zen-dark-theme-styles-amoled = Chủ đề tối
zen-dark-theme-styles-default = Chủ đề tối mặc định
zen-dark-theme-styles-colorful = Chủ đề tối rực rỡ
zen-split-view-title = Chế độ xem chia đôi
zen-split-view-header = Split View Functionality
zen-split-view-description = Split your browser into multiple views, enabling you to browse multiple websites at once
zen-split-view-change-on-hover = 
    .label = Change tabs on hover
zen-compact-mode-styles-left = Ẩn thanh tab
zen-compact-mode-styles-top = Ẩn thanh trên cùng
zen-compact-mode-styles-both = Ẩn cả hai
pane-zen-CKS-title = Phím tắt
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } Phím tắt
zen-settings-CKS-header = Tùy chỉnh phím tắt
zen-settings-CKS-description = Thay đổi các phím tắt mặc định theo sở thích và cải thiện trải nghiệm duyệt web của bạn
zen-settings-CKS-disable-firefox = 
    .label = Vô hiệu hóa các phím tắt mặc định của { -brand-short-name }
zen-settings-CKS-duplicate-shortcut = 
    .label = Lối tắt bị trùng
zen-settings-CKS-reset-shortcuts = 
    .label = Khôi phục về mặc định
zenCKSOption-group-other = Khác
zenCKSOption-group-windowAndTabManagement = Window & Tab Management
zenCKSOption-group-navigation = Điều hướng
zenCKSOption-group-searchAndFind = Search & Find
zenCKSOption-group-pageOperations = Page Operations
zenCKSOption-group-historyAndBookmarks = Lịch sử & Dấu trang
zenCKSOption-group-mediaAndDisplay = Media & Display
zenCKSOption-group-zen-compact-mode = Chế độ thu gọn
zenCKSOption-group-zen-workspace = Không gian làm việc
zenCKSOption-group-zen-other = Các tính năng khác của Zen
zenCKSOption-group-zen-split-view = Chế độ xem chia đôi
zen-key-quick-restart = Khởi động lại nhanh
zen-window-new-shortcut = Cửa sổ mới
zen-tab-new-shortcut = Tab mới
zen-key-redo = Hoàn tác
zen-restore-last-closed-tab-shortcut = Khôi phục lại tab gần nhất đã đóng
zen-location-open-shortcut = Mở đường dẫn
zen-location-open-shortcut-alt = Open Location (Alt)
zen-key-undo-close-window = Mở lại cửa sổ đã đóng
zen-text-action-undo-shortcut = Hoàn tác
zen-text-action-redo-shortcut = Làm lại
zen-text-action-cut-shortcut = Cắt
zen-text-action-copy-shortcut = Sao chép
zen-text-action-paste-shortcut = Dán
zen-text-action-select-all-shortcut = Chọn tất cả
zen-text-action-delete-shortcut = Xóa
zen-history-show-all-shortcut-mac = Show All History (Mac)
zen-full-screen-shortcut = Chuyển đổi chế độ toàn màn hình
zen-reader-mode-toggle-shortcut-windows = Toggle Reader Mode (Windows)
zen-picture-in-picture-toggle-shortcut-alt = Hình trong hình (Alt)
zen-picture-in-picture-toggle-shortcut-mac = Toggle Picture-in-Picture (Mac)
zen-picture-in-picture-toggle-shortcut-mac-alt = Toggle Picture-in-Picture (Mac Alt)
zen-page-source-shortcut-safari = View Page Source (Safari)
zen-nav-stop-shortcut = Dừng tải
zen-history-sidebar-shortcut = Mở thanh bên lịch sử
zen-window-minimize-shortcut = Thu nhỏ cửa sổ
zen-help-shortcut = Mở trợ giúp
zen-preferences-shortcut = Mở Tuỳ chọn
zen-hide-app-shortcut = Ẩn ứng dụng
zen-hide-other-apps-shortcut = Ẩn các ứng dụng khác
zen-search-focus-shortcut = Focus Search
zen-search-focus-shortcut-alt = Focus Search (Alt)
zen-downloads-shortcut = Mở bảng tải xuống
zen-addons-shortcut = Open Add-ons
zen-file-open-shortcut = Mở tập tin
zen-save-page-shortcut = Lưu trang
zen-print-shortcut = In trang
zen-close-shortcut-2 = Đóng Tab
zen-mute-toggle-shortcut = Chuyển chế độ im lặng
zen-key-delete = Xóa phím
zen-key-go-back = Quay lại
zen-key-go-forward = Tiếp theo
zen-nav-back-shortcut-alt = Navigate Back (Alt)
zen-nav-fwd-shortcut-alt = Navigate Forward (Alt)
zen-history-show-all-shortcut = Hiện tất cả lịch sử
zen-key-enter-full-screen = Xem toàn màn hình
zen-key-exit-full-screen = Thoát toàn màn hình
zen-reader-mode-toggle-shortcut-other = Chế độ đọc
zen-picture-in-picture-toggle-shortcut = Hình trong hình
zen-nav-reload-shortcut-2 = Tải lại trang
zen-key-about-processes = Về các tiến trình
zen-page-source-shortcut = Xem nguồn trang
zen-page-info-shortcut = Xem thông tin trang
zen-find-shortcut = Tìm kiếm trên trang
zen-search-find-again-shortcut = Tìm lại
zen-search-find-again-shortcut-prev = Tìm trước đó
zen-search-find-again-shortcut-2 = Find Again (Alt)
zen-bookmark-this-page-shortcut = Đánh dấu trang này
zen-bookmark-show-library-shortcut = Hiển thị thư viện dấu trang
zen-key-stop = Dừng tải
zen-full-zoom-reduce-shortcut = Thu nhỏ
zen-full-zoom-enlarge-shortcut = Phóng to
zen-full-zoom-reset-shortcut = Đặt lại mức thu phóng
zen-bidi-switch-direction-shortcut = Switch Text Direction
zen-private-browsing-shortcut = Duyệt web riêng tư
zen-screenshot-shortcut = Chụp ảnh màn hình
zen-key-sanitize = Dọn dữ liệu duyệt
zen-quit-app-shortcut = Thoát ứng dụng
zen-key-wr-capture-cmd = WR Capture Command
zen-key-wr-toggle-capture-sequence-cmd = Toggle WR Capture Sequence
zen-nav-reload-shortcut = Tải lại trang
zen-nav-reload-shortcut-skip-cache = Tải lại trang (Bỏ qua bộ nhớ đệm)
zen-close-shortcut = Đóng cửa sổ
zen-close-tab-shortcut = Đóng Tab
zen-compact-mode-shortcut-show-sidebar = Toggle Floating Sidebar
zen-compact-mode-shortcut-show-toolbar = Toggle Floating Toolbar
zen-compact-mode-shortcut-toggle = Bật/tắt chế độ thu gọn
zen-workspace-shortcut-switch-1 = Chuyển sang không gian làm việc 1
zen-workspace-shortcut-switch-2 = Chuyển sang không gian làm việc 2
zen-workspace-shortcut-switch-3 = Chuyển sang không gian làm việc 3
zen-workspace-shortcut-switch-4 = Chuyển sang không gian làm việc 4
zen-workspace-shortcut-switch-5 = Chuyển sang không gian làm việc 5
zen-workspace-shortcut-switch-6 = Chuyển sang không gian làm việc 6
zen-workspace-shortcut-switch-7 = Chuyển sang không gian làm việc 7
zen-workspace-shortcut-switch-8 = Chuyển sang không gian làm việc 8
zen-workspace-shortcut-switch-9 = Chuyển sang không gian làm việc 9
zen-workspace-shortcut-switch-10 = Chuyển sang không gian làm việc 10
zen-workspace-shortcut-forward = Forward Workspace
zen-workspace-shortcut-backward = Backward Workspace
zen-web-panel-shortcut-toggle = Toggle Web Panel
zen-sidebar-shortcut-toggle = Toggle Sidebar's Width
zen-split-view-shortcut-grid = Toggle Split View Grid
zen-split-view-shortcut-vertical = Toggle Split View Vertical
zen-split-view-shortcut-horizontal = Toggle Split View Horizontal
zen-split-view-shortcut-unsplit = Đóng chế độ xem chia đôi
zen-key-select-tab-1 = Chọn tab #1
zen-key-select-tab-2 = Chọn tab #2
zen-key-select-tab-3 = Chọn tab #3
zen-key-select-tab-4 = Chọn tab #4
zen-key-select-tab-5 = Chọn tab #5
zen-key-select-tab-6 = Chọn tab #6
zen-key-select-tab-7 = Chọn tab #7
zen-key-select-tab-8 = Chọn tab #8
zen-key-select-tab-last = Chọn tab cuối cùng
zen-key-show-all-tabs = Hiện tất cả tab
zen-key-goto-history = Đi đến lịch sử
zen-key-go-home = Về trang chủ
zen-bookmark-show-sidebar-shortcut = Hiện trang đánh dấu ở thanh bên
zen-bookmark-show-toolbar-shortcut = Hiện trang đánh dấu ở thanh công cụ
