zen-panel-ui-workspaces-text = Spásanna Oibre Eile
zen-panel-ui-workspaces-create = 
    .label = Cruthaigh Spás
zen-panel-ui-workspaces-edit-text = Cuir Spás Oibre in Eagar
zen-panel-ui-workspaces-edit-save = 
    .label = Sábháil Athruithe
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Cealaigh
    .accesskey = D’Athraigh Chluaisíní(s) go Spás Oibre
zen-workspaces-panel-context-delete = 
    .label = Scrios Spás Oibre
    .accesskey = D
zen-workspaces-panel-change-name = 
    .label = Athraigh Ainm
zen-workspaces-panel-change-icon = 
    .label = Athraigh Deilbhín
zen-workspaces-panel-context-manage = 
    .label = Bainistigh Spásanna Oibre
    .accesskey = M
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Socraigh Coimeádán Réamhshocraithe
    .accesskey = O
zen-workspaces-how-to-reorder = To reorder spaces, drag and drop them from the space icons at the bottom of the sidebar.
zen-workspaces-change-theme = 
    .label = Cuir an Téama in Eagar
zen-workspaces-panel-context-open = 
    .label = D’Oscail Spás Oibre
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Socraigh mar spás oibre réamhshocraithe
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Cuir Spás Oibre in Eagar
    .accesskey = Agus
context-zen-change-workspace-tab = 
    .label = D’Athraigh Chluaisíní(s) go Spás Oibre
    .accesskey = D’Athraigh Chluaisíní(s) go Spás Oibre
zen-bookmark-edit-panel-workspace-selector = 
    .value = Spásanna Oibre
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Comhlántach
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Scoilt
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Analógach
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Triadach
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Ar snámh
zen-panel-ui-gradient-click-to-add = Cliceáil chun dath a chur leis
zen-workspace-creation-name = 
    .placeholder = Ainm an Spáis
zen-workspaces-panel-context-reorder = 
    .label = Reorder Workspaces
zen-workspace-creation-profile = Próifíl
    .tooltiptext = Úsáidtear próifílí chun fianáin agus sonraí suímh a dheighilt idir spásanna.
zen-workspace-creation-title = Cruthaigh Spás nua
zen-workspace-creation-label = Úsáidtear spásanna chun do chluaisíní agus do sheisiúin a eagrú.
