zen-panel-ui-current-profile-text = ppróifíl reatha
unified-extensions-description = Extensions are used to bring more extra functionality into { -brand-short-name }.
tab-zen-unload = 
    .label = Díluchtaigh Cluaisín
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Gníomhartha Díluchtaithe Cluaisíní
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Cosc a chur ar dhíluchtú cluaisíní
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Déan neamhaird de dhíluchtú na gcluaisíní
    .accesskey = I
