zen-panel-ui-workspaces-text = Spásanna Oibre Eile
zen-panel-ui-workspaces-create-text = Cruthaigh Spás Oibre
zen-panel-ui-workspaces-create-save = 
    .label = Cruthaigh Spás Oibre
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = Cancel
    .accesskey = D’Athraigh Chluaisíní(s) go Spás Oibre
zen-panel-ui-workspaces-edit-text = Cuir Spás Oibre in Eagar
zen-panel-ui-workspaces-edit-save = 
    .label = Save Changes
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Cancel
    .accesskey = D’Athraigh Chluaisíní(s) go Spás Oibre
zen-workspaces-panel-context-delete = 
    .label = Scrios Spás Oibre
    .accesskey = D
zen-workspaces-panel-change-name = 
    .label = Change Name
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Socraigh Coimeádán Réamhshocraithe
    .accesskey = O
zen-workspaces-change-gradient = 
    .label = Change Theme Colors
    .accesskey = D’Athraigh Chluaisíní(s) go Spás Oibre
zen-bookmark-edit-panel-workspace-selector = 
    .value = Workspaces
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Complementary
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Split
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Analogous
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Triadic
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Floating
zen-panel-ui-gradient-click-to-add = Click to add a color
