pane-zen-looks-title = デザイン
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Changing the default language could make it easier for Websites to track you.
zen-look-and-feel-colors-header = テーマの色を選択する
zen-look-and-feel-colors-description = { -brand-short-name } の見た目を好きなようにカスタマイズしましょう
zen-look-and-feel-themed-toolbar = 
    .label = ツールバーの色をアクセントカラーに合わせる
pane-zen-side-panels-title = サイドウェブパネル
zen-side-panels-header = ウェブパネルの設定
zen-side-panels-description = 一度に複数のビューを表示することで生産性を向上させましょう！
zen-side-panels-enabled = 
    .label = ウェブサイドパネルを有効化
zen-side-panels-close-on-blur = 
    .label = ピン留めされていないとき、そのパネルがピン留めされていなければ閉じる
zen-look-and-feel-compact-view-header = コンパクトビューで表示
zen-look-and-feel-compact-view-description = 使用しているツールバーのみを表示します！
zen-look-and-feel-compact-view-enabled = 
    .label = { -brand-short-name } のコンパクトモードを有効化
zen-look-and-feel-compact-view-top-toolbar = 
    .label = 上部のツールバーをコンパクトモード使用時に非表示にする
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = コンパクトモードでタブを切り替えたり、新しいタブを開いたりするときに、ツールバーを簡単にポップアップできます。
zen-look-and-feel-buttons-header = ボタンのスタイル
zen-look-and-feel-buttons-description = 表示したいボタンのスタイルを選択してください
zen-look-and-feel-pilled-buttons = 
    .label = Pilled Buttons
pane-zen-workspaces-title = ワークスペース
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = ワークスペース
pane-zen-workspaces-header = ワークスペース
zen-settings-workspaces-header = ワークスペースの一般設定
zen-settings-workspaces-description = ワークスペースを使用すると、同時に複数のブラウジングセッションを行うことができます!
zen-settings-workspaces-enabled = 
    .label = ワークスペース機能を有効にする (実験的)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Hide the default container indicator in the tab bar
pane-zen-theme-title = テーマ設定
zen-vertical-tabs-title = サイドバーとタブのレイアウト
zen-vertical-tabs-header = 垂直タブ
zen-vertical-tabs-description = タブを縦方向に管理します
zen-vertical-tabs-show-expand-button = 
    .label = 展開ボタンを表示する
zen-vertical-tabs-expand-tabs-by-default = デフォルトでタブを展開する
zen-vertical-tabs-dont-expand-tabs-by-default = デフォルトでタブを展開しない
zen-vertical-tabs-expand-tabs-on-hover = ホバーでタブを展開 (コンパクトモードでは動作しません)
zen-vertical-tabs-expand-tabs-header = タブの展開方法
zen-vertical-tabs-expand-tabs-description = サイドバーのタブの展開方法を選択してください
zen-theme-marketplace-header = テーマストア
zen-theme-marketplace-description = Find and install themes from the store.
zen-theme-marketplace-remove-button = 
    .label = テーマを削除
zen-theme-marketplace-check-for-updates-button = 
    .label = ソフトウェアの更新を確認
zen-theme-marketplace-updates-success = テーマが正常に更新されました
zen-theme-marketplace-updates-fail = 更新は見つかりませんでした
pane-zen-marketplace-title = テーマストア
zen-look-and-feel-legacy-toolbar = 
    .label = レガシーのツールバーの位置を使用します。再起動が必要です！
zen-theme-marketplace-link = ストアを開く
zen-dark-theme-styles-header = Dark Theme Styles
zen-dark-theme-styles-description = Customize the dark theme to your liking
zen-dark-theme-styles-amoled = Amoled Black
zen-dark-theme-styles-default = Default Dark Theme
zen-dark-theme-styles-colorful = Colorful Dark Theme
pane-zen-CKS-title = キーボードショートカット
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } キーボードショートカット
zen-settings-CKS-header = キーボードショートカットをカスタマイズしましょう
zen-settings-CKS-description = デフォルトのキーボードショートカットを好みに変更し、ブラウジング体験を向上させましょう
zen-settings-CKS-disable-firefox = 
    .label = { -brand-short-name } のデフォルトキーボードショートカットを無効にする
zen-cks-group-tab-action = タブのアクション
zen-cks-group-page-action = ページのアクション
zen-cks-group-visible-action = 表示方法のアクション
zen-cks-group-history-action = 履歴のアクション
zen-cks-group-search-action = 検索のアクション
zen-cks-group-tools-action = ツールのアクション
zen-cks-group-bookmark-action = ブックマークのアクション
zen-cks-group-open-page-action = ページを開くアクション
zen-cks-group-downloads-action = ダウンロードのアクション
zen-cks-group-sidebar-action = サイドバーのアクション
zen-cks-group-compact-mode-action = コンパクトモードのアクション
zen-cks-group-split-view-action = 分割ビューのアクション
zen-cks-group-workspace-action = ワークスペースのアクション
open-new-tab = 新規タブを開く
close-tab = タブを閉じる
open-new-window = 新規ウィンドウを開く
open-new-private-window = 新規プライベートウィンドウを開く
close-window = ウィンドウを閉じる
restore-last-tab = 以前のタブを復元
restore-last-window = 以前のウィンドウを復元
show-next-tab = 次のタブを表示
show-previous-tab = 前のタブを表示
show-all-tabs-panel = すべてのタブパネルを表示する
send-with-mail = ページをメールで送信
save-page = 保存
print-page = プリント
mute-current-tab = 現在のタブをミュート
show-source-of-page = ページのソースを表示
show-page-info = ページの情報を表示
zoom-in = 拡大
zoom-out = 縮小
reset-zoom = 等倍
back = 戻る
forward = 進む
stop = 停止
reload = 再読み込み
force-reload = 強制再読み込み
search-in-this-page = ページ内を検索
show-next-search-result = 次を検索
show-previous-search-result = 以前の検索結果を表示
search-the-web = ウェブを検索
open-migration-wizard = 移行ツールを開く
quit-from-application = アプリケーションを終了
enter-into-customize-mode = カスタマイズモードに入る
enter-into-offline-mode = オフラインモードにする
open-screen-capture = 画面キャプチャを開く
bookmark-this-page = このページをブックマーク
open-bookmark-add-tool = ブックマーク追加ツールを開く
open-bookmarks-manager = ブックマークマネージャーを開く
toggle-bookmark-toolbar = ブックマークツールバーの切り替え
open-general-preferences = 一般 設定を開く
open-privacy-preferences = プライバシー設定を開く
open-workspaces-preferences = ワークスペース設定を開く
open-containers-preferences = コンテナ設定を開く
open-search-preferences = 検索設定を開く
open-sync-preferences = 同期設定を開く
open-task-manager = Open Task Manager
open-addons-manager = アドオンマネージャーを開く
open-home-page = ホームページを開く
forget-history = 履歴を消去
quick-forget-history = Quick Forget History
clear-recent-history = 最近の履歴を消去
restore-last-session = 以前のセッションを復元
search-history = 履歴を検索
manage-history = 履歴を管理
open-downloads = ダウンロードを表示
show-bookmark-sidebar = ブックマークサイドバーを表示
show-history-sidebar = 履歴のサイドバーを表示
show-synced-tabs-sidebar = 同期タブサイドバーを開く
reverse-sidebar = サイドバーの位置を反対にする
hide-sidebar = サイドバーを隠す
toggle-sidebar = サイドバーの切り替え
zen-toggle-web-panels = ウェブパネルの切り替え
zen-toggle-compact-mode = コンパクトモードの切り替え
zen-toggle-compact-mode-sidebar = コンパクトモードのサイドバーを切り替える
zen-toggle-compact-mode-toolbar = コンパクトモードのツールバーを切り替える
zen-change-workspace = ワークスペースをサイクルする
zen-split-view-grid = 格子状に分割する
zen-split-view-vertical = 垂直に分割
zen-split-view-horizontal = 水平に分割
zen-split-view-close = 分割ビューを閉じる
zen-expand-sidebar = サイドバーの展開を切り替える
