pane-zen-looks-title = ルック＆フィール
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = デフォルト言語を変更すると、ウェブサイトがあなたを追跡しやすくなります。
zen-look-and-feel-colors-header = テーマの色を選択
zen-look-and-feel-colors-description = { -brand-short-name } を好きなように見せてください
zen-look-and-feel-use-workspace-colors = 
    .label = Use workspace colors as primary color
pane-zen-side-panels-title = サイドウェブパネル
zen-side-panels-header = ウェブパネルの一般設定
zen-side-panels-description = 一度に複数のビューを表示することで生産性を向上させます！
zen-side-panels-enabled = 
    .label = Web サイドパネルを有効にする
zen-side-panels-close-on-blur = 
    .label = ピン留めされていない場合はフォーカスを失ったときにパネルを閉じます
zen-vertical-tabs-show-bottom-border = 
    .label = 下部アイコンの境界線を表示する
sync-currently-syncing-workspaces = ワークスペース
sync-engine-workspaces = 
    .label = ワークスペース
    .tooltiptext = 端末間でワークスペースを同期
    .accesskey = W
zen-glance-title = Glance
zen-glance-header = 一般的な設定
zen-glance-description = 新しいタブで開かずにリンクの簡単な概要を取得します
zen-glance-trigger-label = トリガーメソッド
zen-glance-enabled = 
    .label = Enable Glance
zen-glance-trigger-ctrl-click = 
    .label = Ctrl + Click
zen-glance-trigger-alt-click = 
    .label = Alt + Click
zen-glance-trigger-shift-click = 
    .label = Shift + クリック
zen-glance-trigger-meta-click = 
    .label = Meta (Command) + Click
zen-glance-trigger-mantain-click = 
    .label = Hold Click (Coming Soon!)
zen-look-and-feel-compact-view-header = コンパクトビューで表示
zen-look-and-feel-compact-view-description = 使用しているツールバーのみを表示します！
zen-look-and-feel-compact-view-enabled = 
    .label = { -brand-short-name }のコンパクトモードを有効にする
zen-look-and-feel-compact-view-top-toolbar = 
    .label = 上部のツールバーをコンパクトモードで非表示にする
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = コンパクトモードで新しいタブを切り替えたり開いたりするときに、簡単にツールバーをポップアップさせる
zen-look-and-feel-buttons-header = ボタンのスタイル
zen-look-and-feel-buttons-description = 表示したいボタンのスタイルを選択してください
zen-look-and-feel-pilled-buttons = 
    .label = 押し込みボタン
pane-zen-tabs-title = タブ管理
category-zen-workspaces = 
    .tooltiptext = { pane-zen-tabs-title }
pane-settings-workspaces-title = ワークスペース
pane-zen-tabs-unloader-title = Tab Unloader
zen-tabs-unloader-header = タブのアンローダーの一般設定
zen-tabs-unloader-description = 未使用のタブを自動的にアンロードしてメモリを節約します
zen-tabs-unloader-enabled = 
    .label = タブのアンローダーを有効にする
zen-tabs-unloader-unload-delay = 
    .label = タブをアンロードした後
zen-tabs-unloader-unload-delay-description = タブがアンロードされるまでの時間
zen-look-and-feel-compact-toolbar-themed = 
    .label = Use themed background for compact toolbar
zen-look-and-feel-compact-sidebar-themed = 
    .label = Use themed background for compact sidebar
pane-zen-pinned-tab-manager-title = ピン留めされたタブ
zen-pinned-tab-manager-header = ピン留めされたタブの一般設定
zen-pinned-tab-manager-description = ピン留めされたタブの追加動作を管理
zen-pinned-tab-manager-restore-pinned-tabs-to-pinned-url = 
    .label = ピン留めされたタブを起動時に元のピン留めされた URL に復元します
zen-pinned-tab-manager-close-shortcut-behavior-label = タブを閉じる ショートカットの動作
zen-pinned-tab-manager-reset-unload-switch-close-shortcut-option = 
    .label = URLをリセットし、アンロードして次のタブに切り替える
zen-pinned-tab-manager-unload-switch-close-shortcut-option = 
    .label = アンロードし、次のタブに切り替える
zen-pinned-tab-manager-reset-switch-close-shortcut-option = 
    .label = URL をリセットして次のタブに切り替える
zen-pinned-tab-manager-switch-close-shortcut-option = 
    .label = 次のタブに切り替える
zen-pinned-tab-manager-reset-close-shortcut-option = 
    .label = Reset URL
zen-pinned-tab-manager-close-close-shortcut-option = 
    .label = タブを閉じる
pane-zen-workspaces-header = ワークスペース
zen-settings-workspaces-header = ワークスペースの一般設定
zen-settings-workspaces-description = ワークスペースを使用すると、一度に複数のブラウジングセッションを行うことができます!
zen-settings-workspaces-enabled = 
    .label = ワークスペースを有効にする (実験的)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = タブバー内のデフォルトのコンテナインジケーターを非表示にする
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = ワークスペースに独自のピン留めされたタブがあることを許可する
zen-key-unsafed = 未保存のショートカットです！再入力後、「エスケープ」キーをクリックして安全にしてください。
zen-key-conflict = 他のショートカットと競合します
pane-zen-theme-title = テーマ設定
zen-vertical-tabs-title = サイドバーとタブのレイアウト
zen-vertical-tabs-header = 垂直タブ
zen-vertical-tabs-description = 垂直レイアウトでタブを管理
zen-vertical-tabs-show-expand-button = 
    .label = 展開ボタンを表示
zen-vertical-tabs-newtab-under-last-tab = 
    .label = 最後のタブの下に新しいタブボタンを表示する
zen-vertical-tabs-expand-tabs-by-default = デフォルトでタブを展開
zen-vertical-tabs-dont-expand-tabs-by-default = デフォルトでタブを展開しない
zen-vertical-tabs-expand-tabs-on-hover = Hover でタブを展開(コンパクトモードでは動作しません)
zen-vertical-tabs-expand-tabs-header = タブを展開する方法
zen-vertical-tabs-expand-tabs-description = サイドバーのタブを展開する方法を選択します
zen-theme-marketplace-header = Zen Mods
zen-theme-disable-all-enabled = 
    .title = すべてのテーマを無効にする
zen-theme-disable-all-disabled = 
    .title = すべてのテーマを有効にする
zen-theme-marketplace-description = ストアからテーマを見つけてインストールします。
zen-theme-marketplace-remove-button = 
    .label = テーマを削除
zen-theme-marketplace-check-for-updates-button = 
    .label = アップデートの確認
zen-theme-marketplace-updates-success = テーマが正常に更新されました
zen-theme-marketplace-updates-fail = アップデートが見つかりませんでした！
zen-theme-marketplace-toggle-enabled-button = 
    .title = テーマを無効にする
zen-theme-marketplace-toggle-disabled-button = 
    .title = テーマを有効化
zen-theme-marketplace-remove-confirmation = このModを削除してもよろしいですか？
zen-theme-marketplace-close-modal = 閉じる
zen-theme-marketplace-theme-header-title = 
    .title = CSS セレクター: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = なし
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = 何かを入力...
pane-zen-marketplace-title = Zen Mods
zen-settings-workspaces-display-as-icon-strip = 
    .label = ワークスペースをアイコンストリップとして表示
zen-settings-workspaces-force-container-tabs-to-workspace = 
    .label = コンテナタブを開くときにコンテナがデフォルトとして設定されているワークスペースに切り替える
zen-settings-workspaces-hide-deactivated-workspaces = 
    .label = 無効なワークスペースを非表示
zen-theme-marketplace-link = ストアを訪問
zen-dark-theme-styles-header = ダークテーマのスタイル
zen-dark-theme-styles-description = 好みに合わせてダークテーマをカスタマイズする
zen-dark-theme-styles-amoled = 夜のテーマ
zen-dark-theme-styles-default = デフォルトのダークテーマ
zen-dark-theme-styles-colorful = カラフルなダークテーマ
zen-split-view-title = 分割ビュー
zen-split-view-header = 分割ビュー機能
zen-split-view-description = ブラウザーを複数のビューに分割し、複数のウェブサイトを一度に閲覧できるようにします
zen-split-view-change-on-hover = 
    .label = ホバー時のタブの変更
zen-compact-mode-styles-left = タブバーを隠す
zen-compact-mode-styles-top = 上部バーを非表示
zen-compact-mode-styles-both = 両方を隠す
pane-zen-CKS-title = キーボードショートカット
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } キーボードショートカット
zen-settings-CKS-header = キーボードショートカットをカスタマイズする
zen-settings-CKS-description = デフォルトのキーボードショートカットを好みに変更し、ブラウジング体験を向上させましょう
zen-settings-CKS-disable-firefox = 
    .label = { -brand-short-name }のデフォルトのキーボードショートカットを無効にする
zen-settings-CKS-duplicate-shortcut = 
    .label = Duplicate Shortcut
zen-settings-CKS-reset-shortcuts = 
    .label = デフォルトにリセット
zenCKSOption-group-other = その他
zenCKSOption-group-windowAndTabManagement = ウィンドウとタブ管理
zenCKSOption-group-navigation = Navigation
zenCKSOption-group-searchAndFind = 検索と検索
zenCKSOption-group-pageOperations = ページ操作
zenCKSOption-group-historyAndBookmarks = 履歴とブックマーク
zenCKSOption-group-mediaAndDisplay = メディア & 表示
zenCKSOption-group-zen-compact-mode = コンパクトモード
zenCKSOption-group-zen-workspace = ワークスペース
zenCKSOption-group-zen-other = その他の禅の特徴
zenCKSOption-group-zen-split-view = 分割ビュー
zen-key-quick-restart = クイック再起動
zen-window-new-shortcut = 新しいウィンドウ
zen-tab-new-shortcut = New Tab
zen-key-redo = やり直し
zen-restore-last-closed-tab-shortcut = 最後に閉じたタブを復元
zen-location-open-shortcut = 場所を開く
zen-location-open-shortcut-alt = 場所を開く (Alt)
zen-key-undo-close-window = 閉じたウィンドウを元に戻す
zen-text-action-undo-shortcut = 元に戻す
zen-text-action-redo-shortcut = Redo
zen-text-action-cut-shortcut = 切り取り
zen-text-action-copy-shortcut = コピー
zen-text-action-paste-shortcut = 貼り付け
zen-text-action-select-all-shortcut = すべて選択
zen-text-action-delete-shortcut = 削除
zen-history-show-all-shortcut-mac = すべての履歴を表示(Mac)
zen-full-screen-shortcut = 全画面表示の切り替え
zen-reader-mode-toggle-shortcut-windows = リーダーモードの切り替え (Windows)
zen-picture-in-picture-toggle-shortcut-alt = ピクチャーインピクチャーの切り替え (Alt)
zen-picture-in-picture-toggle-shortcut-mac = ピクチャーインピクチャー（Mac）の切り替え
zen-picture-in-picture-toggle-shortcut-mac-alt = ピクチャーインピクチャーの切り替え (Mac Alt)
zen-page-source-shortcut-safari = ページソースの表示 (Safari)
zen-nav-stop-shortcut = 読み込みを停止
zen-history-sidebar-shortcut = Show History Sidebar
zen-window-minimize-shortcut = ウィンドウを最小化する
zen-help-shortcut = ヘルプを開く
zen-preferences-shortcut = 設定を開く
zen-hide-app-shortcut = アプリケーションを隠す
zen-hide-other-apps-shortcut = 他のアプリを隠す
zen-search-focus-shortcut = フォーカス検索
zen-search-focus-shortcut-alt = フォーカス検索 (Alt)
zen-downloads-shortcut = ダウンロードを開く
zen-addons-shortcut = アドオンを開く
zen-file-open-shortcut = ファイルを開く
zen-save-page-shortcut = ページを保存
zen-print-shortcut = Print Page
zen-close-shortcut-2 = タブを閉じる
zen-mute-toggle-shortcut = ミュートの切り替え
zen-key-delete = キーを削除
zen-key-go-back = 戻る
zen-key-go-forward = 前に進む
zen-nav-back-shortcut-alt = 戻る(Alt)
zen-nav-fwd-shortcut-alt = 前方に移動 (Alt)
zen-history-show-all-shortcut = すべての履歴を表示
zen-key-enter-full-screen = 全画面表示にする
zen-key-exit-full-screen = 全画面表示を終了
zen-reader-mode-toggle-shortcut-other = リーダーモードの切り替え
zen-picture-in-picture-toggle-shortcut = ピクチャーインピクチャーの切り替え
zen-nav-reload-shortcut-2 = ページを再読み込み
zen-key-about-processes = プロセスについて
zen-page-source-shortcut = ページソースの表示
zen-page-info-shortcut = ページ情報を表示
zen-find-shortcut = ページ上で検索
zen-search-find-again-shortcut = 再検索
zen-search-find-again-shortcut-prev = 前を検索
zen-search-find-again-shortcut-2 = 再検索 (Alt)
zen-bookmark-this-page-shortcut = このページをブックマーク
zen-bookmark-show-library-shortcut = ブックマークライブラリを表示
zen-key-stop = 読み込みを中止
zen-full-zoom-reduce-shortcut = 縮小
zen-full-zoom-enlarge-shortcut = 拡大
zen-full-zoom-reset-shortcut = 等倍
zen-bidi-switch-direction-shortcut = テキストの方向を切り替える
zen-private-browsing-shortcut = プライベート閲覧
zen-screenshot-shortcut = スクリーンショットを撮影
zen-key-sanitize = ブラウジングデータをクリア
zen-quit-app-shortcut = アプリケーションを終了
zen-key-wr-capture-cmd = WRキャプチャコマンド
zen-key-wr-toggle-capture-sequence-cmd = WRキャプチャシーケンスの切り替え
zen-nav-reload-shortcut = ページを再読み込み
zen-nav-reload-shortcut-skip-cache = Reload Page (Skip Cache)
zen-close-shortcut = ウィンドウを閉じる
zen-close-tab-shortcut = タブを閉じる
zen-compact-mode-shortcut-show-sidebar = フローティングサイドバーの切り替え
zen-compact-mode-shortcut-show-toolbar = フローティングツールバーの切り替え
zen-compact-mode-shortcut-toggle = コンパクトモードの切り替え
zen-workspace-shortcut-switch-1 = ワークスペース1に切り替える
zen-workspace-shortcut-switch-2 = ワークスペース2に切り替える
zen-workspace-shortcut-switch-3 = ワークスペース3に切り替える
zen-workspace-shortcut-switch-4 = ワークスペース4に切り替える
zen-workspace-shortcut-switch-5 = ワークスペース5に切り替える
zen-workspace-shortcut-switch-6 = ワークスペース6に切り替える
zen-workspace-shortcut-switch-7 = ワークスペース7に切り替える
zen-workspace-shortcut-switch-8 = ワークスペース8に切り替える
zen-workspace-shortcut-switch-9 = ワークスペース9に切り替える
zen-workspace-shortcut-switch-10 = ワークスペース10に切り替える
zen-workspace-shortcut-forward = ワークスペースを転送
zen-workspace-shortcut-backward = 後方ワークスペース
zen-web-panel-shortcut-toggle = ウェブパネルの切り替え
zen-sidebar-shortcut-toggle = サイドバーの幅を切り替える
zen-pinned-tab-shortcut-reset = ピン留めされたタブをピン留めしたURLにリセット
zen-split-view-shortcut-grid = 分割表示グリッドの切り替え
zen-split-view-shortcut-vertical = 分割ビューを垂直に切り替える
zen-split-view-shortcut-horizontal = 分割ビューを水平に切り替える
zen-split-view-shortcut-unsplit = 分割ビューを閉じる
zen-key-select-tab-1 = Select tab #1
zen-key-select-tab-2 = Select tab #2
zen-key-select-tab-3 = Select tab #3
zen-key-select-tab-4 = タブを選択 #4
zen-key-select-tab-5 = タブを選択 #5
zen-key-select-tab-6 = Select tab #6
zen-key-select-tab-7 = タブを選択
zen-key-select-tab-8 = Select tab #8
zen-key-select-tab-last = 最後のタブを選択
zen-key-show-all-tabs = すべてのタブを表示
zen-key-goto-history = 履歴へ移動
zen-key-go-home = 帰還する
zen-bookmark-show-sidebar-shortcut = ブックマークサイドバーを表示
zen-bookmark-show-toolbar-shortcut = ブックマークツールバーを表示
