pane-zen-looks-title = デザイン
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Changing the default language could make it easier for Websites to track you.
zen-look-and-feel-colors-header = テーマの色を選択する
zen-look-and-feel-colors-description = { -brand-short-name } の見た目を好きなようにカスタマイズしましょう
zen-look-and-feel-themed-toolbar = 
    .label = ツールバーの色をアクセントカラーに合わせる
pane-zen-side-panels-title = サイドウェブパネル
zen-side-panels-header = ウェブパネルの設定
zen-side-panels-description = 一度に複数のビューを表示することで生産性を向上させましょう！
zen-side-panels-enabled = 
    .label = ウェブサイドパネルを有効化
zen-side-panels-close-on-blur = 
    .label = ピン留めされていないとき、そのパネルがピン留めされていなければ閉じる
zen-look-and-feel-compact-view-header = コンパクトビューで表示
zen-look-and-feel-compact-view-description = 使用しているツールバーのみを表示します！
zen-look-and-feel-compact-view-enabled = 
    .label = { -brand-short-name } のコンパクトモードを有効化
zen-look-and-feel-compact-view-top-toolbar = 
    .label = 上部のツールバーをコンパクトモード使用時に非表示にする
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = コンパクトモードでタブを切り替えたり、新しいタブを開いたりするときに、ツールバーを簡単にポップアップできます。
zen-look-and-feel-buttons-header = ボタンのスタイル
zen-look-and-feel-buttons-description = 表示したいボタンのスタイルを選択してください
zen-look-and-feel-pilled-buttons = 
    .label = Pilled Buttons
pane-zen-workspaces-title = ワークスペース
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = ワークスペース
pane-zen-workspaces-header = ワークスペース
zen-settings-workspaces-header = ワークスペースの一般設定
zen-settings-workspaces-description = ワークスペースを使用すると、同時に複数のブラウジングセッションを行うことができます!
zen-settings-workspaces-enabled = 
    .label = ワークスペース機能を有効にする (実験的)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = タブバーにあるデフォルトのコンテナーのインジケータを隠す
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Allow workspaces have their own pinned tabs
pane-zen-theme-title = テーマ設定
zen-vertical-tabs-title = サイドバーとタブのレイアウト
zen-vertical-tabs-header = 垂直タブ
zen-vertical-tabs-description = タブを縦方向に管理します
zen-vertical-tabs-show-expand-button = 
    .label = 展開ボタンを表示する
zen-vertical-tabs-expand-tabs-by-default = デフォルトでタブを展開する
zen-vertical-tabs-dont-expand-tabs-by-default = デフォルトでタブを展開しない
zen-vertical-tabs-expand-tabs-on-hover = ホバーでタブを展開 (コンパクトモードでは動作しません)
zen-vertical-tabs-expand-tabs-header = タブの展開方法
zen-vertical-tabs-expand-tabs-description = サイドバーのタブの展開方法を選択してください
zen-theme-marketplace-header = Zen Mods
zen-theme-marketplace-description = Find and install themes from the store.
zen-theme-marketplace-remove-button = 
    .label = テーマを削除
zen-theme-marketplace-check-for-updates-button = 
    .label = ソフトウェアの更新を確認
zen-theme-marketplace-updates-success = テーマが正常に更新されました
zen-theme-marketplace-updates-fail = 更新は見つかりませんでした
zen-theme-marketplace-toggle-enabled-button = 
    .title = テーマを無効にする
zen-theme-marketplace-toggle-disabled-button = 
    .title = テーマを有効にする
zen-theme-marketplace-remove-confirmation = Are you sure you want to remove this mod?
zen-theme-marketplace-close-modal = 閉じる
zen-theme-marketplace-theme-header-title = 
    .title = CSS Selector: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = None
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Type something...
pane-zen-marketplace-title = Zen Mods
zen-settings-workspaces-display-as-icon-strip = 
    .label = Display workspaces as an icon strip
zen-theme-marketplace-link = ストアを開く
zen-dark-theme-styles-header = ダークテーマのスタイル
zen-dark-theme-styles-description = 好みに合わせてダークテーマをカスタマイズする
zen-dark-theme-styles-amoled = Night Theme
zen-dark-theme-styles-default = デフォルトのダークテーマ
zen-dark-theme-styles-colorful = カラフルなダークテーマ
zen-compact-mode-styles-left = Hide Tab bar
zen-compact-mode-styles-top = Hide Top bar
zen-compact-mode-styles-both = Hide Both
pane-zen-CKS-title = キーボードショートカット
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } キーボードショートカット
zen-settings-CKS-header = キーボードショートカットをカスタマイズしましょう
zen-settings-CKS-description = デフォルトのキーボードショートカットを好みに変更し、ブラウジング体験を向上させましょう
zen-settings-CKS-disable-firefox = 
    .label = { -brand-short-name } のデフォルトキーボードショートカットを無効にする
zen-settings-CKS-duplicate-shortcut = 
    .label = Duplicate Shortcut
zenCKSOption-group-other = Other
zenCKSOption-group-windowAndTabManagement = Window & Tab Management
zenCKSOption-group-navigation = Navigation
zenCKSOption-group-searchAndFind = Search & Find
zenCKSOption-group-pageOperations = Page Operations
zenCKSOption-group-historyAndBookmarks = History & Bookmarks
zenCKSOption-group-mediaAndDisplay = Media & Display
zenCKSOption-group-zen-compact-mode = Compact Mode
zenCKSOption-group-zen-workspace = Workspaces
zenCKSOption-group-zen-other = Other Zen Features
zenCKSOption-group-zen-split-view = Split View
zen-key-quick-restart = Quick Restart
zen-window-new-shortcut = New Window
zen-tab-new-shortcut = New Tab
zen-location-open-shortcut = Open Location
zen-location-open-shortcut-alt = Open Location (Alt)
zen-search-focus-shortcut = Focus Search
zen-search-focus-shortcut-alt = Focus Search (Alt)
zen-downloads-shortcut = Open Downloads
zen-addons-shortcut = Open Add-ons
zen-file-open-shortcut = Open File
zen-save-page-shortcut = Save Page
zen-print-shortcut = Print Page
zen-close-shortcut-2 = Close Tab
zen-mute-toggle-shortcut = Toggle Mute
zen-key-delete = Delete Key
zen-key-go-back = Go Back
zen-key-go-forward = Go Forward
zen-nav-back-shortcut-alt = Navigate Back (Alt)
zen-nav-fwd-shortcut-alt = Navigate Forward (Alt)
zen-history-show-all-shortcut = Show All History
zen-key-enter-full-screen = Enter Full Screen
zen-key-exit-full-screen = Exit Full Screen
zen-reader-mode-toggle-shortcut-other = Toggle Reader Mode
zen-picture-in-picture-toggle-shortcut = Toggle Picture-in-Picture
zen-nav-reload-shortcut-2 = Reload Page
zen-key-about-processes = About Processes
zen-page-source-shortcut = View Page Source
zen-page-info-shortcut = View Page Info
zen-find-shortcut = Find on Page
zen-search-find-again-shortcut = Find Again
zen-search-find-again-shortcut-prev = Find Previous
zen-search-find-again-shortcut-2 = Find Again (Alt)
zen-bookmark-this-page-shortcut = Bookmark This Page
zen-bookmark-show-library-shortcut = Show Bookmarks Library
zen-key-stop = Stop Loading
zen-full-zoom-reduce-shortcut = Zoom Out
zen-full-zoom-enlarge-shortcut = Zoom In
zen-full-zoom-reset-shortcut = Reset Zoom
zen-bidi-switch-direction-shortcut = Switch Text Direction
zen-private-browsing-shortcut = Private Browsing
zen-screenshot-shortcut = Take Screenshot
zen-key-sanitize = Clear Browsing Data
zen-quit-app-shortcut = Quit Application
zen-key-wr-capture-cmd = WR Capture Command
zen-key-wr-toggle-capture-sequence-cmd = Toggle WR Capture Sequence
zen-nav-reload-shortcut = Reload Page
zen-nav-reload-shortcut-skip-cache = Reload Page (Skip Cache)
zen-close-shortcut = Close Window
zen-close-tab-shortcut = Close Tab
zen-compact-mode-shortcut-show-sidebar = Toggle Floating Sidebar
zen-compact-mode-shortcut-show-toolbar = Toggle Floating Toolbar
zen-compact-mode-shortcut-toggle = Toggle Compact Mode
zen-workspace-shortcut-switch-1 = Switch to Workspace 1
zen-workspace-shortcut-switch-2 = Switch to Workspace 2
zen-workspace-shortcut-switch-3 = Switch to Workspace 3
zen-workspace-shortcut-switch-4 = Switch to Workspace 4
zen-workspace-shortcut-switch-5 = Switch to Workspace 5
zen-workspace-shortcut-switch-6 = Switch to Workspace 6
zen-workspace-shortcut-switch-7 = Switch to Workspace 7
zen-workspace-shortcut-switch-8 = Switch to Workspace 8
zen-workspace-shortcut-switch-9 = Switch to Workspace 9
zen-workspace-shortcut-switch-10 = Switch to Workspace 10
zen-workspace-shortcut-forward = Forward Workspace
zen-workspace-shortcut-backward = Backward Workspace
zen-web-panel-shortcut-toggle = Toggle Web Panel
zen-sidebar-shortcut-toggle = Toggle Sidebar's Width
zen-split-view-shortcut-grid = Toggle Split View Grid
zen-split-view-shortcut-vertical = Toggle Split View Vertical
zen-split-view-shortcut-horizontal = Toggle Split View Horizontal
zen-split-view-shortcut-unsplit = Close Split View
