pane-zen-looks-title = Ulkoasu ja tuntuma
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Oletuskielen vaihtaminen voi helpottaa verkkosivustoja sinun jäljittämisessä.
zen-look-and-feel-colors-header = Valitse teeman väri
zen-look-and-feel-colors-description = Tee { -brand-short-name }istä haluamasi näköinen
zen-look-and-feel-themed-toolbar = 
    .label = Tee työkalupalkista aksenttivärin mukainen
pane-zen-side-panels-title = Sivu nettipaneeli
zen-side-panels-header = Verkkopaneelin yleiset asetukset
zen-side-panels-description = Lisää tuottavauuttasi käyttämällä useaa näkymää kerralla!
zen-side-panels-enabled = 
    .label = Ota netti sivupaneelit käyttöön
zen-side-panels-close-on-blur = 
    .label = Sulje paneeli, kun se menettää tarkennuksen jos se ei ole kiinnitetty
zen-look-and-feel-compact-view-header = Näytä kompaktissa näkymätilassa
zen-look-and-feel-compact-view-description = Näytä vain käyttämäsi työkalusi!
zen-look-and-feel-compact-view-enabled = 
    .label = Ota käyttöön { -brand-short-name }in kompakti tila
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Piilota ylin työkalupalkki kompaktissa tilassa
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Ponnahda työkalupalkki
zen-look-and-feel-buttons-header = Painike tyyli
zen-look-and-feel-buttons-description = Valitse painikkeiden tyyli jonka haluat nähdä
zen-look-and-feel-pilled-buttons = 
    .label = Pyöristetyt painikkeet
pane-zen-workspaces-title = Työtilat
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = Työtilat
pane-zen-workspaces-header = Työtilat
zen-settings-workspaces-header = Työtilojen yleisasetukset
zen-settings-workspaces-description = Työtilojen avulla, sinulla voi olla monta selausistuntoa kerralla!
zen-settings-workspaces-enabled = 
    .label = Ota työtilat käyttöön (kokeellinen)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Piilota oletussäiliön ilmaisin välilehtipalkista
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Salli työtiloille omat kiinnitetyt välilehdet
pane-zen-theme-title = Teema asetukset
zen-vertical-tabs-title = Sivupalkki ja välilehti asettelu
zen-vertical-tabs-header = Pystysuora palkki
zen-vertical-tabs-description = Hallitse välilehtiä pystysuorassa
zen-vertical-tabs-show-expand-button = 
    .label = Näytä laajenna painike
zen-vertical-tabs-expand-tabs-by-default = Laajenna välilehdet oletuksena
zen-vertical-tabs-dont-expand-tabs-by-default = Älä laajenna välilehtiä oletuksena
zen-vertical-tabs-expand-tabs-on-hover = Laajenna välilehdet siirtämällä hiiri päälle (ei toimi kompakti tilassa)
zen-vertical-tabs-expand-tabs-header = Kuinka laajentaa välilehdet
zen-vertical-tabs-expand-tabs-description = Valitse kuinke laajentaa välilehdet sivupalkissa
zen-theme-marketplace-header = Zen modit
zen-theme-marketplace-description = Etsi ja asenna teemoja kaupasta.
zen-theme-marketplace-remove-button = 
    .label = Poista teema
zen-theme-marketplace-check-for-updates-button = 
    .label = Tarkista päivityksiltä
zen-theme-marketplace-updates-success = Teema päivitetty onnistuneesti
zen-theme-marketplace-updates-fail = Päivityksiä ei löytynt!
zen-theme-marketplace-toggle-enabled-button = 
    .title = Poista teema käytöstä
zen-theme-marketplace-toggle-disabled-button = 
    .title = Ota teema käyttöön
zen-theme-marketplace-remove-confirmation = Oletko varma, että haluat poistaa tämän modin?
zen-theme-marketplace-close-modal = Sulje
zen-theme-marketplace-theme-header-title = 
    .title = CSS-valinta: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = Ei mitään
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Kirjoita jotain
pane-zen-marketplace-title = Zen modit
zen-settings-workspaces-display-as-icon-strip = 
    .label = Työtilojen näyttäminen kuvakkeena
zen-theme-marketplace-link = Käy kaupassa
zen-dark-theme-styles-header = Tumma teema tyylejä
zen-dark-theme-styles-description = Mukauta tumma teema mieleiseksesi
zen-dark-theme-styles-amoled = Yö teema
zen-dark-theme-styles-default = Oletus tumma teema
zen-dark-theme-styles-colorful = Värillinen tumma teema
zen-compact-mode-styles-left = Piilota välilehtipalkki
zen-compact-mode-styles-top = Piilota yläpalkki
zen-compact-mode-styles-both = Piilota molemmat
pane-zen-CKS-title = Näppäinkomennot
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } Näppäinkomennot
zen-settings-CKS-header = Muokkaa näppäinkomentoja
zen-settings-CKS-description = Vaihda oletus näppäinkomennot mieleiseksesi ja paranna selauskokemustasi
zen-settings-CKS-disable-firefox = 
    .label = Ota pois käytöstä { -brand-short-name }in oletus näppäinkomennot
zen-settings-CKS-duplicate-shortcut = 
    .label = Duplicate Shortcut
zenCKSOption-group-other = Other
zenCKSOption-group-windowAndTabManagement = Window & Tab Management
zenCKSOption-group-navigation = Navigation
zenCKSOption-group-searchAndFind = Search & Find
zenCKSOption-group-pageOperations = Page Operations
zenCKSOption-group-historyAndBookmarks = History & Bookmarks
zenCKSOption-group-mediaAndDisplay = Media & Display
zenCKSOption-group-zen-compact-mode = Compact Mode
zenCKSOption-group-zen-workspace = Workspaces
zenCKSOption-group-zen-other = Other Zen Features
zen-key-quick-restart = Quick Restart
zen-window-new-shortcut = New Window
zen-tab-new-shortcut = New Tab
zen-location-open-shortcut = Open Location
zen-location-open-shortcut-alt = Open Location (Alt)
zen-search-focus-shortcut = Focus Search
zen-search-focus-shortcut-alt = Focus Search (Alt)
zen-downloads-shortcut = Open Downloads
zen-addons-shortcut = Open Add-ons
zen-file-open-shortcut = Open File
zen-save-page-shortcut = Save Page
zen-print-shortcut = Print Page
zen-close-shortcut-2 = Close Tab
zen-mute-toggle-shortcut = Toggle Mute
zen-key-delete = Delete Key
zen-key-go-back = Go Back
zen-key-go-forward = Go Forward
zen-nav-back-shortcut-alt = Navigate Back (Alt)
zen-nav-fwd-shortcut-alt = Navigate Forward (Alt)
zen-history-show-all-shortcut = Show All History
zen-key-enter-full-screen = Enter Full Screen
zen-key-exit-full-screen = Exit Full Screen
zen-reader-mode-toggle-shortcut-other = Toggle Reader Mode
zen-picture-in-picture-toggle-shortcut = Toggle Picture-in-Picture
zen-nav-reload-shortcut-2 = Reload Page
zen-key-about-processes = About Processes
zen-page-source-shortcut = View Page Source
zen-page-info-shortcut = View Page Info
zen-find-shortcut = Find on Page
zen-search-find-again-shortcut = Find Again
zen-search-find-again-shortcut-prev = Find Previous
zen-search-find-again-shortcut-2 = Find Again (Alt)
zen-bookmark-this-page-shortcut = Bookmark This Page
zen-bookmark-show-library-shortcut = Show Bookmarks Library
zen-key-stop = Stop Loading
zen-full-zoom-reduce-shortcut = Zoom Out
zen-full-zoom-enlarge-shortcut = Zoom In
zen-full-zoom-reset-shortcut = Reset Zoom
zen-bidi-switch-direction-shortcut = Switch Text Direction
zen-private-browsing-shortcut = Private Browsing
zen-screenshot-shortcut = Take Screenshot
zen-key-sanitize = Clear Browsing Data
zen-quit-app-shortcut = Quit Application
zen-key-wr-capture-cmd = WR Capture Command
zen-key-wr-toggle-capture-sequence-cmd = Toggle WR Capture Sequence
zen-nav-reload-shortcut = Reload Page
zen-nav-reload-shortcut-skip-cache = Reload Page (Skip Cache)
zen-close-shortcut = Close Window
zen-close-tab-shortcut = Close Tab
zen-compact-mode-shortcut-show-sidebar = Toggle Floating Sidebar
zen-compact-mode-shortcut-show-toolbar = Toggle Floating Toolbar
zen-compact-mode-shortcut-toggle = Toggle Compact Mode
zen-workspace-shortcut-switch-1 = Switch to Workspace 1
zen-workspace-shortcut-switch-2 = Switch to Workspace 2
zen-workspace-shortcut-switch-3 = Switch to Workspace 3
zen-workspace-shortcut-switch-4 = Switch to Workspace 4
zen-workspace-shortcut-switch-5 = Switch to Workspace 5
zen-workspace-shortcut-switch-6 = Switch to Workspace 6
zen-workspace-shortcut-switch-7 = Switch to Workspace 7
zen-workspace-shortcut-switch-8 = Switch to Workspace 8
zen-workspace-shortcut-switch-9 = Switch to Workspace 9
zen-workspace-shortcut-switch-10 = Switch to Workspace 10
zen-workspace-shortcut-forward = Forward Workspace
zen-workspace-shortcut-backward = Backward Workspace
zen-web-panel-shortcut-toggle = Toggle Web Panel
zen-sidebar-shortcut-toggle = Toggle Sidebar's Width
