pane-zen-looks-title = Katso ja tunne
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Muuttaminen oletuskieli voisi helpottaa Websites seurata sinua.
zen-look-and-feel-colors-header = Valitse teeman väri
zen-look-and-feel-colors-description = Tee { -brand-short-name } näyttää ja tuntuu haluamallasi tavalla
zen-look-and-feel-use-workspace-colors = 
    .label = Use workspace colors as primary color
pane-zen-side-panels-title = Side Web Panels
zen-side-panels-header = Web-paneelien yleiset asetukset
zen-side-panels-description = Lisää tuottavuutta ottamalla useita näkemyksiä kerrallaan!
zen-side-panels-enabled = 
    .label = Ota Käyttöön Sivupaneelit
zen-side-panels-close-on-blur = 
    .label = Sulje paneeli, kun se menettää tarkennuksen, jos sitä ei ole kiinnitetty
zen-vertical-tabs-show-bottom-border = 
    .label = Näytä ala- kuvakkeiden raja
sync-currently-syncing-workspaces = Työtilat
sync-engine-workspaces = 
    .label = Työtilat
    .tooltiptext = Synkronoi työtilat eri laitteiden välillä
    .accesskey = W
zen-glance-title = Vilkaisu
zen-glance-header = Yleiset asetukset silmäykselle
zen-glance-description = Hanki nopea yleiskatsaus linkeistäsi avaamatta niitä uudessa välilehdessä
zen-glance-trigger-label = Käynnistimen menetelmä
zen-glance-enabled = Enable Glance
zen-glance-trigger-ctrl-click = 
    .label = Ctrl + Click
zen-glance-trigger-alt-click = 
    .label = Alt + Klikkaa
zen-glance-trigger-shift-click = 
    .label = Vaihto + Napsauta
zen-glance-trigger-meta-click = 
    .label = Meta (Command) + Click
zen-glance-trigger-mantain-click = 
    .label = Mantain Klikkaa
zen-look-and-feel-compact-view-header = Näytä kompaktissa näkymätilassa
zen-look-and-feel-compact-view-description = Näytä vain käyttämäsi työkalupalkit!
zen-look-and-feel-compact-view-enabled = 
    .label = Ota käyttöön { -brand-short-name }kompakti tila
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Piilota työkalupalkki niin myös kompaktissa tilassa
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Tee työkalurivin ponnahdusikkuna lyhyesti, kun vaihdat tai avaat uusia välilehtiä kompaktitilassa
zen-look-and-feel-buttons-header = Painikkeen tyyli
zen-look-and-feel-buttons-description = Valitse painikkeiden tyyli jonka haluat nähdä
zen-look-and-feel-pilled-buttons = 
    .label = Täytetyt Painikkeet
pane-zen-tabs-title = Välilehtien Hallinta
category-zen-workspaces = 
    .tooltiptext = { pane-zen-tabs-title }
pane-settings-workspaces-title = Työtilat
pane-zen-tabs-unloader-title = Tab Unloader
zen-tabs-unloader-header = Yleiset asetukset välilehdelle unloadader
zen-tabs-unloader-description = Poista käyttämättömät välilehdet automaattisesti tallentaaksesi muistia
zen-tabs-unloader-enabled = 
    .label = Ota Käyttöön Välilehti Lataajan Poisto
zen-tabs-unloader-unload-delay = 
    .label = Poista välilehdet
zen-tabs-unloader-unload-delay-description = Aika minuutteina, jonka jälkeen välilehdet poistetaan
pane-zen-pinned-tab-manager-title = Kiinnitetyt Välilehdet
zen-pinned-tab-manager-header = Yleiset asetukset kiinnitettäville välilehteille
zen-pinned-tab-manager-description = Hallitse lisäkäyttäytymistä kiinnitettyjen välilehtien osalta
zen-pinned-tab-manager-restore-pinned-tabs-to-pinned-url = 
    .label = Palauta kiinnitetty välilehdet niiden alun perin kiinnitetty URL käynnistettäessä
zen-pinned-tab-manager-close-shortcut-behavior-label = Sulje Pikakuvakkeen Käyttäytyminen
zen-pinned-tab-manager-reset-unload-switch-close-shortcut-option = 
    .label = Nollaa URL, pura ja vaihda seuraavaan välilehteen
zen-pinned-tab-manager-unload-switch-close-shortcut-option = 
    .label = Pura ja vaihda seuraavaan välilehteen
zen-pinned-tab-manager-reset-switch-close-shortcut-option = 
    .label = Nollaa URL ja vaihda seuraavaan välilehteen
zen-pinned-tab-manager-switch-close-shortcut-option = 
    .label = Siirry seuraavaan välilehteen
zen-pinned-tab-manager-reset-close-shortcut-option = 
    .label = Reset URL
zen-pinned-tab-manager-close-close-shortcut-option = 
    .label = Sulje välilehti
pane-zen-workspaces-header = Työtilat
zen-settings-workspaces-header = Työtilojen yleiset asetukset
zen-settings-workspaces-description = Työtiloilla voi olla kerralla useita selaustilaisuuksia!
zen-settings-workspaces-enabled = 
    .label = Ota Käyttöön Työtilat (Kokeellinen)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Piilota säiliön oletusmerkkivalo välilehdessä - palkki
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Salli työtilojen omat pinned välilehdet
zen-key-unsafed = Tallentamaton pikakuvake! Ole hyvä ja turvaa se painamalla "paeta" -näppäintä kirjoittamisen jälkeen.
zen-key-conflict = Ristiriita toisen pikakuvakkeen kanssa
pane-zen-theme-title = Teeman Asetukset
zen-vertical-tabs-title = Sivupalkin ja välilehtien asettelu
zen-vertical-tabs-header = Pystysuorat Välilehdet
zen-vertical-tabs-description = Hallitse välilehteäsi pystysuoraan asetteluun
zen-vertical-tabs-show-expand-button = 
    .label = Näytä Laajenna Painike
zen-vertical-tabs-newtab-under-last-tab = 
    .label = Näytä uusi välilehti painike viimeisen välilehden alla
zen-vertical-tabs-expand-tabs-by-default = Laajenna välilehdet oletuksena
zen-vertical-tabs-dont-expand-tabs-by-default = Älä laajenna välilehtiä oletuksena
zen-vertical-tabs-expand-tabs-on-hover = Laajenna välilehdet Hoverissa (Ei toimi kompaktitilassa)
zen-vertical-tabs-expand-tabs-header = Kuinka laajentaa välilehdet
zen-vertical-tabs-expand-tabs-description = Valitse, miten voit laajentaa välilehtiä sivupalkissa
zen-theme-marketplace-header = Zen Mods
zen-theme-disable-all-enabled = 
    .title = Poista kaikki teemat käytöstä
zen-theme-disable-all-disabled = 
    .title = Ota käyttöön kaikki teemat
zen-theme-marketplace-description = Etsi ja asenna teemoja kaupasta.
zen-theme-marketplace-remove-button = 
    .label = Poista Teema
zen-theme-marketplace-check-for-updates-button = 
    .label = Tarkista päivitykset
zen-theme-marketplace-updates-success = Teema päivitetty onnistuneesti
zen-theme-marketplace-updates-fail = Päivityksiä ei löytynyt!
zen-theme-marketplace-toggle-enabled-button = 
    .title = Poista Teema Käytöstä
zen-theme-marketplace-toggle-disabled-button = 
    .title = Ota Teema Käyttöön
zen-theme-marketplace-remove-confirmation = Oletko varma, että haluat poistaa tämän tilan?
zen-theme-marketplace-close-modal = Sulje
zen-theme-marketplace-theme-header-title = 
    .title = CSS Valitin: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = Ei Mitään
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Kirjoita jotain...
pane-zen-marketplace-title = Zen Mods
zen-settings-workspaces-display-as-icon-strip = 
    .label = Näytä työtilat kuvakkeen liuskaisena
zen-settings-workspaces-force-container-tabs-to-workspace = 
    .label = Vaihda työtilaan, jossa säiliö on asetettu oletusarvoiseksi avattaessa säiliön välilehtiä
zen-settings-workspaces-hide-deactivated-workspaces = 
    .label = Piilota käytöstä poistetut työtilat
zen-theme-marketplace-link = Vieraile Kaupassa
zen-dark-theme-styles-header = Tumma Teeman Tyylit
zen-dark-theme-styles-description = Mukauta tumma teema mieleesi
zen-dark-theme-styles-amoled = Yön Teema
zen-dark-theme-styles-default = Tumman Oletusteema
zen-dark-theme-styles-colorful = Värikäs Tumma Teema
zen-split-view-title = Jaettu Näkymä
zen-split-view-header = Split View -toiminnallisuus
zen-split-view-description = Jaa selaimesi useisiin näkymiin, jolloin voit selata useita sivustoja kerralla
zen-split-view-change-on-hover = 
    .label = Vaihda välilehtiä hiiren päällä
zen-compact-mode-styles-left = Piilota välilehti
zen-compact-mode-styles-top = Piilota yläpalkki
zen-compact-mode-styles-both = Piilota Molemmat
pane-zen-CKS-title = Näppäimistön Pikanäppäimet
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } Näppäimistön Pikakuvakkeet
zen-settings-CKS-header = Muokkaa näppäimistön pikakuvakkeita
zen-settings-CKS-description = Muuta oletus näppäimistön pikakuvakkeet mieltymykseesi ja paranna selauskokemustasi
zen-settings-CKS-disable-firefox = 
    .label = Poista { -brand-short-name }oletusnäppäimistön pikakuvakkeet käytöstä
zen-settings-CKS-duplicate-shortcut = 
    .label = Duplicate Shortcut
zen-settings-CKS-reset-shortcuts = 
    .label = Palauta oletukset
zenCKSOption-group-other = Muu
zenCKSOption-group-windowAndTabManagement = Ikkunan & Välilehden Hallinta
zenCKSOption-group-navigation = Navigation
zenCKSOption-group-searchAndFind = Etsi & Etsi
zenCKSOption-group-pageOperations = Sivun Toiminnot
zenCKSOption-group-historyAndBookmarks = Historia Ja Kirjanmerkit
zenCKSOption-group-mediaAndDisplay = Media & Näyttö
zenCKSOption-group-zen-compact-mode = Kompakti Tila
zenCKSOption-group-zen-workspace = Työtilat
zenCKSOption-group-zen-other = Muut Zen-ominaisuudet
zenCKSOption-group-zen-split-view = Jaettu Näkymä
zen-key-quick-restart = Nopea Uudelleenkäynnistys
zen-window-new-shortcut = Uusi Ikkuna
zen-tab-new-shortcut = New Tab
zen-key-redo = Toista
zen-restore-last-closed-tab-shortcut = Palauta Viimeksi Suljettu Välilehti
zen-location-open-shortcut = Avaa Sijainti
zen-location-open-shortcut-alt = Avaa Sijainti (Alt)
zen-key-undo-close-window = Kumoa Sulje Ikkuna
zen-text-action-undo-shortcut = Kumoa
zen-text-action-redo-shortcut = Toista
zen-text-action-cut-shortcut = Leikkaa
zen-text-action-copy-shortcut = Kopioi
zen-text-action-paste-shortcut = Liitä
zen-text-action-select-all-shortcut = Valitse Kaikki
zen-text-action-delete-shortcut = Poista
zen-history-show-all-shortcut-mac = Näytä Kaikki Historia (Mac)
zen-full-screen-shortcut = Vaihda Kokoruututilaan
zen-reader-mode-toggle-shortcut-windows = Vaihda Lukijan Tila (Windows)
zen-picture-in-picture-toggle-shortcut-alt = Vaihda Kuva-Kuva (Alt)
zen-picture-in-picture-toggle-shortcut-mac = Valitse Kuva (kuva)
zen-picture-in-picture-toggle-shortcut-mac-alt = Vaihda Kuva-Kuva (Mac Alt)
zen-page-source-shortcut-safari = Näytä Sivulähde (Safari)
zen-nav-stop-shortcut = Lopeta Lataaminen
zen-history-sidebar-shortcut = Show History Sidebar
zen-window-minimize-shortcut = Pienennä Ikkuna
zen-help-shortcut = Avaa Ohje
zen-preferences-shortcut = Avoimet Asetukset
zen-hide-app-shortcut = Piilota Sovellus
zen-hide-other-apps-shortcut = Piilota Muut Sovellukset
zen-search-focus-shortcut = Tarkenna Haku
zen-search-focus-shortcut-alt = Kohdistus Haku (Alt)
zen-downloads-shortcut = Avaa Lataukset
zen-addons-shortcut = Avaa Lisäosat
zen-file-open-shortcut = Avaa Tiedosto
zen-save-page-shortcut = Tallenna Sivu
zen-print-shortcut = Print Page
zen-close-shortcut-2 = Sulje Välilehti
zen-mute-toggle-shortcut = Vaihda Mykistystä
zen-key-delete = Poista Avain
zen-key-go-back = Siirry Takaisin
zen-key-go-forward = Siirry Eteenpäin
zen-nav-back-shortcut-alt = Navigoi Takaisin (Alt)
zen-nav-fwd-shortcut-alt = Siirry Eteenpäin (Alt)
zen-history-show-all-shortcut = Näytä Kaikki Historia
zen-key-enter-full-screen = Anna Koko Näyttö
zen-key-exit-full-screen = Poistu Koko Näyttötilasta
zen-reader-mode-toggle-shortcut-other = Vaihda Lukijan Tila
zen-picture-in-picture-toggle-shortcut = Vaihda Kuva Kuvaksi
zen-nav-reload-shortcut-2 = Lataa Sivu Uudelleen
zen-key-about-processes = Tietoja Prosesseista
zen-page-source-shortcut = Näytä Sivun Lähdekoodi
zen-page-info-shortcut = Näytä Sivun Tiedot
zen-find-shortcut = Etsi sivulta
zen-search-find-again-shortcut = Etsi Uudelleen
zen-search-find-again-shortcut-prev = Etsi Edellinen
zen-search-find-again-shortcut-2 = Etsi Uudelleen (Alt)
zen-bookmark-this-page-shortcut = Lisää Tämä Sivu Kirjanmerkkeihin
zen-bookmark-show-library-shortcut = Näytä Kirjanmerkkikirjasto
zen-key-stop = Lopeta Lataaminen
zen-full-zoom-reduce-shortcut = Zoomaa Ulos
zen-full-zoom-enlarge-shortcut = Zoomaa Sisään
zen-full-zoom-reset-shortcut = Reset Zoom
zen-bidi-switch-direction-shortcut = Vaihda Tekstin Suuntaa
zen-private-browsing-shortcut = Yksityinen Selaus
zen-screenshot-shortcut = Ota Kuvakaappaus
zen-key-sanitize = Tyhjennä Selaustiedot
zen-quit-app-shortcut = Lopeta Sovellus
zen-key-wr-capture-cmd = Wr Kaappaus Komento
zen-key-wr-toggle-capture-sequence-cmd = Vaihda Wr Kaappausjärjestystä
zen-nav-reload-shortcut = Lataa Sivu Uudelleen
zen-nav-reload-shortcut-skip-cache = Reload Page (Skip Cache)
zen-close-shortcut = Sulje Ikkuna
zen-close-tab-shortcut = Sulje Välilehti
zen-compact-mode-shortcut-show-sidebar = Vaihda Kelluvan Sivupalkin Tilaa
zen-compact-mode-shortcut-show-toolbar = Vaihda Kelluva Työkalurivi
zen-compact-mode-shortcut-toggle = Vaihda Kompaktitila
zen-workspace-shortcut-switch-1 = Vaihda työtilaan 1
zen-workspace-shortcut-switch-2 = Vaihda työtilaan 2
zen-workspace-shortcut-switch-3 = Vaihda työtilaan 3
zen-workspace-shortcut-switch-4 = Vaihda työtilaan 4
zen-workspace-shortcut-switch-5 = Vaihda työtilaan 5
zen-workspace-shortcut-switch-6 = Vaihda työtilaan 6
zen-workspace-shortcut-switch-7 = Vaihda työtilaan 7
zen-workspace-shortcut-switch-8 = Vaihda työtilaan 8
zen-workspace-shortcut-switch-9 = Vaihda työtilaan 9
zen-workspace-shortcut-switch-10 = Vaihda työtilaan 10
zen-workspace-shortcut-forward = Välitä Työtila
zen-workspace-shortcut-backward = Taaksepäin Työtila
zen-web-panel-shortcut-toggle = Vaihda Web-paneeliin
zen-sidebar-shortcut-toggle = Vaihda Sivupalkin Leveys
zen-pinned-tab-shortcut-reset = Nollaa kiinnitetty välilehti kiinnitettyyn URL-osoitteeseen
zen-split-view-shortcut-grid = Vaihda Jaa Näkymäruudukkoon
zen-split-view-shortcut-vertical = Vaihda Jaettu Näkymä Pystysuunnassa
zen-split-view-shortcut-horizontal = Vaihda Jaa Näkymä Vaakasuoraan
zen-split-view-shortcut-unsplit = Sulje Jaettu Näkymä
zen-key-select-tab-1 = Select tab #1
zen-key-select-tab-2 = Select tab #2
zen-key-select-tab-3 = Select tab #3
zen-key-select-tab-4 = Valitse välilehti #4
zen-key-select-tab-5 = Valitse välilehti #5
zen-key-select-tab-6 = Select tab #6
zen-key-select-tab-7 = Valitse välilehti #7
zen-key-select-tab-8 = Select tab #8
zen-key-select-tab-last = Valitse viimeinen välilehti
zen-key-show-all-tabs = Näytä kaikki välilehdet
zen-key-goto-history = Siirry historiaan
zen-key-go-home = Siirry Kotiin
zen-bookmark-show-sidebar-shortcut = Näytä Kirjanmerkkien Sivupalkki
zen-bookmark-show-toolbar-shortcut = Näytä Kirjanmerkkipalkki
