pane-zen-looks-title = Ulkoasu ja tuntuma
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Oletuskielen vaihtaminen voi helpottaa verkkosivustoja sinun jäljittämisessä.
zen-look-and-feel-colors-header = Valitse teeman väri
zen-look-and-feel-colors-description = Tee { -brand-short-name }istä haluamasi näköinen
zen-look-and-feel-themed-toolbar = 
    .label = Tee työkalupalkista aksenttivärin mukainen
pane-zen-side-panels-title = Sivu nettipaneeli
zen-side-panels-header = Verkkopaneelin yleiset asetukset
zen-side-panels-description = Lisää tuottavauuttasi käyttämällä useaa näkymää kerralla!
zen-side-panels-enabled = 
    .label = Ota netti sivupaneelit käyttöön
zen-side-panels-close-on-blur = 
    .label = Sulje paneeli, kun se menettää tarkennuksen jos se ei ole kiinnitetty
zen-vertical-tabs-show-bottom-border = 
    .label = Show border for the bottom icons
zen-look-and-feel-compact-view-header = Näytä kompaktissa näkymätilassa
zen-look-and-feel-compact-view-description = Näytä vain käyttämäsi työkalusi!
zen-look-and-feel-compact-view-enabled = 
    .label = Ota käyttöön { -brand-short-name }in kompakti tila
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Piilota ylin työkalupalkki kompaktissa tilassa
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Ponnahda työkalupalkki
zen-look-and-feel-buttons-header = Painike tyyli
zen-look-and-feel-buttons-description = Valitse painikkeiden tyyli jonka haluat nähdä
zen-look-and-feel-pilled-buttons = 
    .label = Pyöristetyt painikkeet
pane-zen-tabs-title = Välilehtien hallinta
category-zen-workspaces = 
    .tooltiptext = { pane-zen-tabs-title }
pane-settings-workspaces-title = Työtilat
pane-zen-tabs-unloader-title = Välilehtien purkaus
zen-tabs-unloader-header = Asetuksia välilehtien purkausta vartem
zen-tabs-unloader-description = Automaattisesti pura käyttämättömiä välilehtiä, säästääkseen muistia
zen-tabs-unloader-enabled = 
    .label = Ota käyttöön välilehtien purkaminen
zen-tabs-unloader-unload-delay = 
    .label = Pura välilehti tämän jälkeen
zen-tabs-unloader-unload-delay-description = Aika minuutteina kunnes välilehdet puretaan
pane-zen-workspaces-header = Työtilat
zen-settings-workspaces-header = Työtilojen yleisasetukset
zen-settings-workspaces-description = Työtilojen avulla, sinulla voi olla monta selausistuntoa kerralla!
zen-settings-workspaces-enabled = 
    .label = Ota työtilat käyttöön (kokeellinen)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Piilota oletussäiliön ilmaisin välilehtipalkista
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Salli työtiloille omat kiinnitetyt välilehdet
zen-key-unsafed = Unsafed shortcut! Please safe it by clicking the "Escape" key after retyping it.
zen-key-conflict = Konflikti toisen pikanäppäimen kanssa
pane-zen-theme-title = Teema asetukset
zen-vertical-tabs-title = Sivupalkki ja välilehti asettelu
zen-vertical-tabs-header = Pystysuora palkki
zen-vertical-tabs-description = Hallitse välilehtiä pystysuorassa
zen-vertical-tabs-show-expand-button = 
    .label = Näytä laajenna painike
zen-vertical-tabs-expand-tabs-by-default = Laajenna välilehdet oletuksena
zen-vertical-tabs-dont-expand-tabs-by-default = Älä laajenna välilehtiä oletuksena
zen-vertical-tabs-expand-tabs-on-hover = Laajenna välilehdet siirtämällä hiiri päälle (ei toimi kompakti tilassa)
zen-vertical-tabs-expand-tabs-header = Kuinka laajentaa välilehdet
zen-vertical-tabs-expand-tabs-description = Valitse kuinke laajentaa välilehdet sivupalkissa
zen-theme-marketplace-header = Zen modit
zen-theme-marketplace-description = Etsi ja asenna teemoja kaupasta.
zen-theme-marketplace-remove-button = 
    .label = Poista teema
zen-theme-marketplace-check-for-updates-button = 
    .label = Tarkista päivityksiltä
zen-theme-marketplace-updates-success = Teema päivitetty onnistuneesti
zen-theme-marketplace-updates-fail = Päivityksiä ei löytynt!
zen-theme-marketplace-toggle-enabled-button = 
    .title = Poista teema käytöstä
zen-theme-marketplace-toggle-disabled-button = 
    .title = Ota teema käyttöön
zen-theme-marketplace-remove-confirmation = Oletko varma, että haluat poistaa tämän modin?
zen-theme-marketplace-close-modal = Sulje
zen-theme-marketplace-theme-header-title = 
    .title = CSS-valinta: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = Ei mitään
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Kirjoita jotain
pane-zen-marketplace-title = Zen modit
zen-settings-workspaces-display-as-icon-strip = 
    .label = Työtilojen näyttäminen kuvakkeena
zen-theme-marketplace-link = Käy kaupassa
zen-dark-theme-styles-header = Tumma teema tyylejä
zen-dark-theme-styles-description = Mukauta tumma teema mieleiseksesi
zen-dark-theme-styles-amoled = Yö teema
zen-dark-theme-styles-default = Oletus tumma teema
zen-dark-theme-styles-colorful = Värillinen tumma teema
zen-split-view-title = Jaettu näkymä
zen-split-view-header = Jaetun näkymän toiminnalisuus
zen-split-view-description = Jaa sinun selain useampaan näkymään, jotta voit selata usempaa sivustoa samaan aikaan
zen-split-view-change-on-hover = 
    .label = Vaihda välilehteä siirtämällä hiiri päälle
zen-compact-mode-styles-left = Piilota välilehtipalkki
zen-compact-mode-styles-top = Piilota yläpalkki
zen-compact-mode-styles-both = Piilota molemmat
pane-zen-CKS-title = Näppäinkomennot
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } Näppäinkomennot
zen-settings-CKS-header = Muokkaa näppäinkomentoja
zen-settings-CKS-description = Vaihda oletus näppäinkomennot mieleiseksesi ja paranna selauskokemustasi
zen-settings-CKS-disable-firefox = 
    .label = Ota pois käytöstä { -brand-short-name }in oletus näppäinkomennot
zen-settings-CKS-duplicate-shortcut = 
    .label = Monista pikanäppäin
zen-settings-CKS-reset-shortcuts = 
    .label = Resetoi oletukseksi
zenCKSOption-group-other = Muu
zenCKSOption-group-windowAndTabManagement = Ikkuna ja välilehti hallintointi
zenCKSOption-group-navigation = Navigointi
zenCKSOption-group-searchAndFind = Etsi ja Löydä
zenCKSOption-group-pageOperations = Sivu toiminnot
zenCKSOption-group-historyAndBookmarks = Historia ja Kirjanmerkit
zenCKSOption-group-mediaAndDisplay = Media ja näyttö
zenCKSOption-group-zen-compact-mode = Kompakti tila
zenCKSOption-group-zen-workspace = Työtilat
zenCKSOption-group-zen-other = Muita Zen ominaisuuksia
zenCKSOption-group-zen-split-view = Jaettu näkymä
zen-key-quick-restart = Nopea uudelleenkäynnistys
zen-window-new-shortcut = Uusi Ikkuna
zen-tab-new-shortcut = Uusi välilehti
zen-key-redo = Tee uudelleen
zen-restore-last-closed-tab-shortcut = Palauta viimeisin suljettu välilehti
zen-location-open-shortcut = Avaa Sijainti
zen-location-open-shortcut-alt = Avaa sijainti (vaihtoehtoinen)
zen-key-undo-close-window = Peruuta ikkunan sulkeminen
zen-text-action-undo-shortcut = Peruuta
zen-text-action-redo-shortcut = Toista
zen-text-action-cut-shortcut = Leikkaa
zen-text-action-copy-shortcut = Kopioi
zen-text-action-paste-shortcut = Liitä
zen-text-action-select-all-shortcut = Valitse kaikki
zen-text-action-delete-shortcut = Poista
zen-history-show-all-shortcut-mac = Näytä koko historia (Max)
zen-full-screen-shortcut = Ota koko näyttö tila käyttöön
zen-reader-mode-toggle-shortcut-windows = Vaihda lukija tilaan (Windows)
zen-picture-in-picture-toggle-shortcut-alt = Ota käyttöön kuva kuvassa (Vaihtoehtoinen)
zen-picture-in-picture-toggle-shortcut-mac = Ota käyttöön kuva kuvassa (Mac)
zen-picture-in-picture-toggle-shortcut-mac-alt = Ota käyttöön kuva kuvassa (Mac vaihtoehtoinen)
zen-page-source-shortcut-safari = Katso sivun lähde (Safari)
zen-nav-stop-shortcut = Lopeta lataaminen
zen-history-sidebar-shortcut = Näytä historia sivupalkissa
zen-window-minimize-shortcut = Minimoi ikkuna
zen-help-shortcut = Avaa apu
zen-preferences-shortcut = Avaa preferenssit
zen-hide-app-shortcut = Piilota sovellus
zen-hide-other-apps-shortcut = Piilota muita sovelluksia
zen-search-focus-shortcut = Keskitytä hakuun
zen-search-focus-shortcut-alt = Keskitytyä hakuun (vaihtoehtoinen)
zen-downloads-shortcut = Avaa lataukset
zen-addons-shortcut = Avaa lisäosat
zen-file-open-shortcut = Avaa tiedosto
zen-save-page-shortcut = Tallenna sivu
zen-print-shortcut = Tulosta sivu
zen-close-shortcut-2 = Sulje välilehti
zen-mute-toggle-shortcut = Mykistä
zen-key-delete = Delete näppäin
zen-key-go-back = Mene takaisin
zen-key-go-forward = Mene eteenpäin
zen-nav-back-shortcut-alt = Navigoi takaisin (Vaihtoehtoinen)
zen-nav-fwd-shortcut-alt = Navigoi eteenpäin (Vaihtoehtoinen)
zen-history-show-all-shortcut = Näytä koko historia
zen-key-enter-full-screen = Mene koko näytön tilaan
zen-key-exit-full-screen = Poistu koko näytön tilasta
zen-reader-mode-toggle-shortcut-other = Lukijatilaan vaihtaminen
zen-picture-in-picture-toggle-shortcut = Kuva kuvassa
zen-nav-reload-shortcut-2 = Pävitä sivu
zen-key-about-processes = Tietoa prosesseista
zen-page-source-shortcut = Katso sivun lähde
zen-page-info-shortcut = Katso sivun tiedot
zen-find-shortcut = Etsi sivulta
zen-search-find-again-shortcut = Etsi uusiksi
zen-search-find-again-shortcut-prev = Etsi edellinen
zen-search-find-again-shortcut-2 = Etsi uusiksi (Vaihtoehtoinen)
zen-bookmark-this-page-shortcut = Kirjanmerkitse tämä sivu
zen-bookmark-show-library-shortcut = Näytä kirjanmerkki kirjasto
zen-key-stop = Lopeta lataaminen
zen-full-zoom-reduce-shortcut = Zoomaa ulos
zen-full-zoom-enlarge-shortcut = Zoomaa sisään
zen-full-zoom-reset-shortcut = Resetoi zoomaus
zen-bidi-switch-direction-shortcut = Vaihda tekstin suuntaa
zen-private-browsing-shortcut = Yksityinen selaaminen
zen-screenshot-shortcut = Ota kuvakaappaus
zen-key-sanitize = Tyhjennä selaus data
zen-quit-app-shortcut = Sulje sovellus
zen-key-wr-capture-cmd = WR Capture Command
zen-key-wr-toggle-capture-sequence-cmd = Toggle WR Capture Sequence
zen-nav-reload-shortcut = Lataa sivu uudelleen
zen-nav-reload-shortcut-skip-cache = Lataa sivu uudelleen (ohita välimuisti)
zen-close-shortcut = Sulje ikkuna
zen-close-tab-shortcut = Sulje välilehti
zen-compact-mode-shortcut-show-sidebar = Ota leijuva sivupalkki käyttöön
zen-compact-mode-shortcut-show-toolbar = Ota leijuva työkalupalkki käyttöön
zen-compact-mode-shortcut-toggle = Ota kompakti tila käyttöön
zen-workspace-shortcut-switch-1 = Vaihda työtilaan 1
zen-workspace-shortcut-switch-2 = Vaihda työtilaan 2
zen-workspace-shortcut-switch-3 = Vaihda työtilaan 3
zen-workspace-shortcut-switch-4 = Vaihda työtilaan 4
zen-workspace-shortcut-switch-5 = Vaihda työtilaan 5
zen-workspace-shortcut-switch-6 = Vaihda työtilaan 6
zen-workspace-shortcut-switch-7 = Vaihda työtilaan 7
zen-workspace-shortcut-switch-8 = Vaihda työtilaan 8
zen-workspace-shortcut-switch-9 = Vaihda työtilaan 9
zen-workspace-shortcut-switch-10 = Vaihda työtilaan 10
zen-workspace-shortcut-forward = Seuraava työtila
zen-workspace-shortcut-backward = Aikaisempi työtila
zen-web-panel-shortcut-toggle = Ota käyttöön verkkopaneeli
zen-sidebar-shortcut-toggle = Laajenna sivupalkki
zen-split-view-shortcut-grid = Jaettu näkymä ruudukolla
zen-split-view-shortcut-vertical = Jaettu näkymä pystysuorassa
zen-split-view-shortcut-horizontal = Jaettu näkymä vaakasuorassa
zen-split-view-shortcut-unsplit = Sulje jaettu näkymä
zen-key-select-tab-1 = Valitse välilehti 1
zen-key-select-tab-2 = Valitse välilehti 2
zen-key-select-tab-3 = Valitse välilehti 3
zen-key-select-tab-4 = Valitse välilehti 4
zen-key-select-tab-5 = Valitse välilehti 5
zen-key-select-tab-6 = Valitse välilehti 6
zen-key-select-tab-7 = Valitse välilehti 7
zen-key-select-tab-8 = Valitse välilehti 8
zen-key-select-tab-last = Valitse viimeisin välilehti
zen-key-show-all-tabs = Näytä kaikki välilehdet
zen-key-goto-history = Mene historiaan
zen-key-go-home = Mene kotiin
zen-bookmark-show-sidebar-shortcut = Näytä kirjamerkkien sivupalkki
zen-bookmark-show-toolbar-shortcut = Näytä kirjamerkkien työkalupalkki
