pane-zen-looks-title = 外觀與樣式
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = 更改預設的語言可能會讓網站更好的追蹤你。
zen-look-and-feel-colors-header = 選擇一個顏色主題
zen-look-and-feel-colors-description = 讓 { -brand-short-name } 成為你理想中的瀏覽器
zen-look-and-feel-themed-toolbar = 
    .label = 使工具列主題使用強調色
pane-zen-side-panels-title = 網頁側版
zen-side-panels-header = 網頁側版的一般設定
zen-side-panels-description = 用多個視窗來精進你的生產力！
zen-side-panels-enabled = 
    .label = 啟用網頁側板
zen-side-panels-close-on-blur = 
    .label = 當失去焦點且沒被盯選時關閉網頁側版
zen-look-and-feel-compact-view-header = 在緊湊模式下顯示
zen-look-and-feel-compact-view-description = 只顯示你需要用的工具欄！
zen-look-and-feel-compact-view-enabled = 
    .label = 啟用 { -brand-short-name } 的緊湊模式
zen-look-and-feel-compact-view-top-toolbar = 
    .label = 在緊湊模式中也隱藏頂部的工具欄
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = 在緊湊模式下切換或開啟新分頁時短暫彈出工具列
zen-look-and-feel-buttons-header = 按鈕樣式
zen-look-and-feel-buttons-description = 選擇你想要看到的按鈕樣式
zen-look-and-feel-pilled-buttons = 
    .label = Pilled 按鈕
pane-zen-workspaces-title = 工作區
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = 工作區
pane-zen-workspaces-header = 工作區
zen-settings-workspaces-header = 工作區的一般設定
zen-settings-workspaces-description = 有了工作區，你就可以同時瀏覽多個頁面！
zen-settings-workspaces-enabled = 
    .label = 啟用工作區 (實驗性的)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Hide the default container indicator in the tab bar
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = 允許工作區有自訂的固定分頁
pane-zen-theme-title = 主題設定
zen-vertical-tabs-title = 側邊欄與分頁排版
zen-vertical-tabs-header = 垂直分頁
zen-vertical-tabs-description = 用垂直的排版來管理你的分頁
zen-vertical-tabs-show-expand-button = 
    .label = 顯示擴展按鈕
zen-vertical-tabs-expand-tabs-by-default = 預設展開分頁
zen-vertical-tabs-dont-expand-tabs-by-default = 預設不展開分頁
zen-vertical-tabs-expand-tabs-on-hover = 懸停時預覽資訊卡 (無法在緊湊模式下使用)
zen-vertical-tabs-expand-tabs-header = 如何擴展分頁
zen-vertical-tabs-expand-tabs-description = 選擇要如何擴展側邊欄中的分頁
zen-theme-marketplace-header = Zen模式
zen-theme-marketplace-description = 從商店尋找並安裝主題。
zen-theme-marketplace-remove-button = 
    .label = 移除主題
zen-theme-marketplace-check-for-updates-button = 
    .label = 檢查更新
zen-theme-marketplace-updates-success = 主題更新成功
zen-theme-marketplace-updates-fail = 找不到任何更新！
zen-theme-marketplace-toggle-enabled-button = 
    .title = Disable Theme
zen-theme-marketplace-toggle-disabled-button = 
    .title = Enable Theme
zen-theme-marketplace-remove-confirmation = Are you sure you want to remove this theme?
zen-theme-marketplace-close-modal = Close
zen-theme-marketplace-theme-header-title = 
    .title = CSS Selector: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = None
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Type something...
pane-zen-marketplace-title = Zen模式
zen-settings-workspaces-display-as-icon-strip = 
    .label = Display workspaces as an icon strip
zen-theme-marketplace-link = 造訪商店
zen-dark-theme-styles-header = 深色主題
zen-dark-theme-styles-description = 根據喜好客製化深色主題
zen-dark-theme-styles-amoled = 夜間主題
zen-dark-theme-styles-default = 預設深色主題
zen-dark-theme-styles-colorful = 有趣的深色主題
zen-compact-mode-styles-left = Hide Tab bar
zen-compact-mode-styles-top = Hide Top bar
zen-compact-mode-styles-both = Hide Both
pane-zen-CKS-title = 快捷鍵
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } 快捷鍵
zen-settings-CKS-header = 自定義你的快捷鍵
zen-settings-CKS-description = 依據你的愛好來更改預設的快捷鍵以近一步改善你的瀏覽體驗
zen-settings-CKS-disable-firefox = 
    .label = 停用 { -brand-short-name } 的預設快捷鍵
zen-cks-group-tab-action = 分頁
zen-cks-group-page-action = 頁面
zen-cks-group-visible-action = 視覺
zen-cks-group-history-action = 歷史
zen-cks-group-search-action = 搜尋
zen-cks-group-tools-action = 工具
zen-cks-group-bookmark-action = 書籤
zen-cks-group-open-page-action = 打開頁面
zen-cks-group-downloads-action = 下載
zen-cks-group-sidebar-action = 側邊欄
zen-cks-group-compact-mode-action = 緊湊模式
zen-cks-group-split-view-action = 分割畫面操作
zen-cks-group-workspace-action = 工作空間
open-new-tab = 打開新分頁
close-tab = 關閉分頁
open-new-window = 打開新視窗
open-new-private-window = 打開新的無痕視窗
close-window = 關閉視窗
restore-last-tab = 恢復上一個分頁
restore-last-window = 恢復上一個視窗
show-next-tab = 顯示下一個分頁
show-previous-tab = 顯示上一個分頁
show-all-tabs-panel = Show All Tabs Panel
send-with-mail = 用電子郵件發送該頁面
save-page = 保存頁面
print-page = 列印頁面
mute-current-tab = 靜音當前的分頁
show-source-of-page = 顯示頁面的原始碼
show-page-info = 顯示頁面資訊
zoom-in = 放大
zoom-out = 縮小
reset-zoom = 重置縮放
back = 上一頁
forward = 下一頁
stop = 停止載入
reload = 重新載入
force-reload = 強制重新載入
search-in-this-page = 在此頁搜尋
show-next-search-result = 顯示下一個搜尋結果
show-previous-search-result = 顯示上一個搜尋結果
search-the-web = 搜尋網絡
open-migration-wizard = 打開遷移小精靈
quit-from-application = 退出應用程式
enter-into-customize-mode = 進入自定義模式
enter-into-offline-mode = 進入離線模式
open-screen-capture = 打開螢幕擷取
bookmark-this-page = 將此頁加入書籤
open-bookmark-add-tool = 打開書籤增加工具
open-bookmarks-manager = 打開書籤管理器
toggle-bookmark-toolbar = 打開書籤工具欄
open-general-preferences = 打一般設定
open-privacy-preferences = 打開隱私設定
open-workspaces-preferences = 打開工作空間設定
open-containers-preferences = 打開容器設定
open-search-preferences = 打開搜尋設定
open-sync-preferences = 打開擴充功能設定
open-task-manager = 打開工作管理器
open-addons-manager = 打開擴展功能管理器
open-home-page = 開啟主頁面
forget-history = Forget History
quick-forget-history = Quick Forget History
clear-recent-history = 清除最近的歷史記錄
restore-last-session = 恢復上次的瀏覽狀態
search-history = 搜尋歷史
manage-history = 管理歷史
open-downloads = 打開下載清單
show-bookmark-sidebar = 顯示書籤側邊欄
show-history-sidebar = 顯示歷史側邊欄
show-synced-tabs-sidebar = 顯示同步分頁側邊欄
reverse-sidebar = 反轉側邊欄的位置
hide-sidebar = 隱藏側邊欄
toggle-sidebar = 切換側邊欄
zen-toggle-web-panels = 切換網頁側板
zen-toggle-compact-mode = 切換緊湊模式
zen-toggle-compact-mode-sidebar = 切換緊湊模式側邊欄
zen-toggle-compact-mode-toolbar = 切換緊湊模式工具列
zen-change-workspace = 循環工作空間
zen-split-view-grid = 分割網格檢視
zen-split-view-vertical = 分割垂直檢視
zen-split-view-horizontal = 水平分割檢視
zen-split-view-close = 關閉分割檢視
zen-expand-sidebar = 切換側邊欄展開
