pane-zen-looks-title = 外觀與樣式
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = 更改預設的語言可能會讓網站更好的追蹤你。
zen-look-and-feel-colors-header = 選擇一個顏色主題
zen-look-and-feel-colors-description = 讓 { -brand-short-name } 成為你理想中的瀏覽器
zen-look-and-feel-use-workspace-colors = 
    .label = Use workspace colors as primary color
pane-zen-side-panels-title = 網頁側版
zen-side-panels-header = 網頁側版的一般設定
zen-side-panels-description = 用多個視窗來精進你的生產力！
zen-side-panels-enabled = 
    .label = 啟用網頁側板
zen-side-panels-close-on-blur = 
    .label = 當失去焦點且沒被盯選時關閉網頁側版
zen-vertical-tabs-show-bottom-border = 
    .label = 顯示底部圖示邊框
zen-vertical-tabs-layout-header = Browser Layout
zen-vertical-tabs-layout-description = Choose the layout that suits you best
zen-layout-single-toolbar = Single toolbar
zen-layout-multiple-toolbar = Multiple toolbars
zen-layout-collapsed-toolbar = Collapsed toolbar
sync-currently-syncing-workspaces = 工作區
sync-engine-workspaces = 
    .label = 工作區
    .tooltiptext = 在不同的裝置間同步您的工作區
    .accesskey = Ｗ
zen-glance-title = Glance
zen-glance-header = General settings for glance
zen-glance-description = Get a quick overview of your links without opening them in a new tab
zen-glance-trigger-label = Trigger method
zen-glance-enabled = 
    .label = Enable Glance
zen-glance-trigger-ctrl-click = 
    .label = Ctrl + Click
zen-glance-trigger-alt-click = 
    .label = Alt + Click
zen-glance-trigger-shift-click = 
    .label = Shift + Click
zen-glance-trigger-meta-click = 
    .label = Meta (Command) + Click
zen-glance-trigger-mantain-click = 
    .label = Mantain Click
zen-look-and-feel-compact-view-header = 在緊湊模式下顯示
zen-look-and-feel-compact-view-description = 只顯示你需要用的工具欄！
zen-look-and-feel-compact-view-enabled = 
    .label = 啟用 { -brand-short-name } 的緊湊模式
zen-look-and-feel-compact-view-top-toolbar = 
    .label = 在緊湊模式中也隱藏頂部的工具欄
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = 在緊湊模式下切換或開啟新分頁時短暫彈出工具列
zen-look-and-feel-buttons-header = 按鈕樣式
zen-look-and-feel-buttons-description = 選擇你想要看到的按鈕樣式
zen-look-and-feel-pilled-buttons = 
    .label = Pilled 按鈕
pane-zen-tabs-title = 分頁管理
category-zen-workspaces = 
    .tooltiptext = { pane-zen-tabs-title }
pane-settings-workspaces-title = 工作區
pane-zen-tabs-unloader-title = 分頁卸載器
zen-tabs-unloader-header = 分頁卸載器一般設定
zen-tabs-unloader-description = 自動卸載未使用的分頁以節省記憶體
zen-tabs-unloader-enabled = 
    .label = 啟用分頁卸載器
zen-tabs-unloader-unload-delay = 
    .label = 在指定時間後卸載分頁
zen-tabs-unloader-unload-delay-description = 卸載分頁的時間（以分鐘為單位）
zen-look-and-feel-compact-toolbar-themed = 
    .label = Use themed background for compact toolbar
zen-look-and-feel-compact-sidebar-themed = 
    .label = Use themed background for compact sidebar
pane-zen-pinned-tab-manager-title = 釘選分頁
zen-pinned-tab-manager-header = 釘選分頁的一般設定
zen-pinned-tab-manager-description = 釘選分頁的額外行為
zen-pinned-tab-manager-restore-pinned-tabs-to-pinned-url = 
    .label = 啟動時恢復釘選分頁至其初始的網址
zen-pinned-tab-manager-container-specific-essentials-enabled = 
    .label = Enable container-specific essentials
zen-pinned-tab-manager-close-shortcut-behavior-label = 關閉分頁快捷鍵的行為
zen-pinned-tab-manager-reset-unload-switch-close-shortcut-option = 
    .label = 重置網址，卸載並切換到下一個分頁
zen-pinned-tab-manager-unload-switch-close-shortcut-option = 
    .label = 卸載並切換到下一個分頁
zen-pinned-tab-manager-reset-switch-close-shortcut-option = 
    .label = 重置網址並切換到下一個分頁
zen-pinned-tab-manager-switch-close-shortcut-option = 
    .label = 切換到下一個分頁
zen-pinned-tab-manager-reset-close-shortcut-option = 
    .label = 重置網址
zen-pinned-tab-manager-close-close-shortcut-option = 
    .label = 關閉分頁
pane-zen-workspaces-header = 工作區
zen-settings-workspaces-header = 工作區的一般設定
zen-settings-workspaces-description = 有了工作區，你就可以同時瀏覽多個頁面！
zen-settings-workspaces-enabled = 
    .label = 啟用工作區 (實驗性的)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = 隱藏分頁欄中的容器指標
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = 允許工作區有自訂的固定分頁
zen-key-unsaved = 快捷鍵未儲存！請重新輸入並按下 "Escape" 鍵來儲存快捷鍵
zen-key-conflict = 與其它快捷鍵發生衝突
pane-zen-theme-title = 主題設定
zen-vertical-tabs-title = 側邊欄與分頁排版
zen-vertical-tabs-header = 垂直分頁
zen-vertical-tabs-description = 用垂直的排版來管理你的分頁
zen-vertical-tabs-show-expand-button = 
    .label = 顯示擴展按鈕
zen-vertical-tabs-newtab-on-tab-list = 
    .label = Show New Tab Button on Tab List
zen-vertical-tabs-newtab-top-button-border = 
    .label = Show separation border for when the new tab button is at the bottom
zen-vertical-tabs-newtab-top-button-up = 
    .label = Move the new tab button to the top
zen-vertical-tabs-expand-tabs-by-default = 預設展開分頁
zen-vertical-tabs-dont-expand-tabs-by-default = 預設不展開分頁
zen-vertical-tabs-expand-tabs-on-hover = 懸停時擴展分頁 (無法在緊湊模式下使用)
zen-vertical-tabs-expand-tabs-header = 如何擴展分頁
zen-vertical-tabs-expand-tabs-description = 選擇要如何擴展側邊欄中的分頁
zen-theme-marketplace-header = Zen模式
zen-theme-disable-all-enabled = 
    .title = 啟用所有主題
zen-theme-disable-all-disabled = 
    .title = 停用所有主題
zen-theme-marketplace-description = 從商店尋找並安裝主題。
zen-theme-marketplace-remove-button = 
    .label = 移除主題
zen-theme-marketplace-check-for-updates-button = 
    .label = 檢查更新
zen-theme-marketplace-updates-success = 主題更新成功
zen-theme-marketplace-updates-fail = 找不到任何更新！
zen-theme-marketplace-toggle-enabled-button = 
    .title = 關閉佈景主題
zen-theme-marketplace-toggle-disabled-button = 
    .title = 啟用佈景主題
zen-theme-marketplace-remove-confirmation = 您確定要移除此模組?
zen-theme-marketplace-close-modal = 關閉
zen-theme-marketplace-theme-header-title = 
    .title = CSS 選擇器：{ $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = 無
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = 請輸入
pane-zen-marketplace-title = Zen 模式
zen-settings-workspaces-display-as-icon-strip = 
    .label = 工作區用圖示顯示
zen-settings-workspaces-force-container-tabs-to-workspace = 
    .label = 開啟容器分頁時，切換到容器設定為預設值的工作區
zen-settings-workspaces-hide-deactivated-workspaces = 
    .label = 隱藏已停用的工作區
zen-theme-marketplace-link = 造訪商店
zen-dark-theme-styles-header = 深色主題
zen-dark-theme-styles-description = 根據喜好客製化深色主題
zen-dark-theme-styles-amoled = 夜間主題
zen-dark-theme-styles-default = 預設深色主題
zen-dark-theme-styles-colorful = 有趣的深色主題
zen-split-view-title = 分割畫面
zen-split-view-header = 分割畫面功能
zen-split-view-description = 在瀏覽器中分割多個畫面，允許你同時瀏覽多個網頁
zen-split-view-change-on-hover = 
    .label = 懸停時切換分頁
zen-compact-mode-styles-left = 隱藏分頁欄
zen-compact-mode-styles-top = 隱藏功能列
zen-compact-mode-styles-both = 隱藏兩者
zen-urlbar-title = Zen URL Bar
zen-urlbar-header = General settings for the URL bar
zen-urlbar-description = Customize the URL bar to your liking
zen-urlbar-behavior-label = Behavior
zen-urlbar-behavior-normal = 
    .label = Normal
zen-urlbar-behavior-floating-on-type = 
    .label = Floating only when typing
zen-urlbar-behavior-float = 
    .label = Always floating
pane-zen-CKS-title = 快捷鍵
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } 快捷鍵
zen-settings-CKS-header = 自定義你的快捷鍵
zen-settings-CKS-description = 依據你的愛好來更改預設的快捷鍵以近一步改善你的瀏覽體驗
zen-settings-CKS-disable-firefox = 
    .label = 停用 { -brand-short-name } 的預設快捷鍵
zen-settings-CKS-duplicate-shortcut = 
    .label = 重複的快捷鍵
zen-settings-CKS-reset-shortcuts = 
    .label = 重設為預設值
zenCKSOption-group-other = 其它
zenCKSOption-group-windowAndTabManagement = 視窗與分頁管理
zenCKSOption-group-navigation = 導航
zenCKSOption-group-searchAndFind = 搜尋與尋找
zenCKSOption-group-pageOperations = 頁面操作
zenCKSOption-group-historyAndBookmarks = 瀏覽紀錄與書籤
zenCKSOption-group-mediaAndDisplay = 媒體與顯示
zenCKSOption-group-zen-compact-mode = 緊湊模式
zenCKSOption-group-zen-workspace = 工作區
zenCKSOption-group-zen-other = 其它 Zen 功能
zenCKSOption-group-zen-split-view = 分割畫面
zenCKSOption-group-devTools = Developer Tools
zen-key-quick-restart = 快速重啟
zen-window-new-shortcut = 開新視窗
zen-tab-new-shortcut = 開新分頁
zen-key-redo = 取消「復原」
zen-restore-last-closed-tab-shortcut = 復原上次關閉的分頁
zen-location-open-shortcut = 選取網址列
zen-location-open-shortcut-alt = 選取網址列 (備用)
zen-key-undo-close-window = 還原已關閉視窗
zen-text-action-undo-shortcut = 復原
zen-text-action-redo-shortcut = 取消「復原」
zen-text-action-cut-shortcut = 剪下
zen-text-action-copy-shortcut = 複製
zen-text-action-copy-url-shortcut = Copy current URL
zen-text-action-paste-shortcut = 貼上
zen-text-action-select-all-shortcut = 全選
zen-text-action-delete-shortcut = 刪除
zen-history-show-all-shortcut-mac = 顯示所有瀏覽紀錄 (Mac)
zen-full-screen-shortcut = 切換全螢幕模式
zen-reader-mode-toggle-shortcut-windows = 切換閱讀模式 (Windows)
zen-picture-in-picture-toggle-shortcut-alt = 切換子母畫面 (備用)
zen-picture-in-picture-toggle-shortcut-mac = 切換子母畫面 (Mac)
zen-picture-in-picture-toggle-shortcut-mac-alt = 切換子母畫面 (Mac 備用)
zen-page-source-shortcut-safari = 頁面原始碼 (Safari)
zen-nav-stop-shortcut = 停止載入
zen-history-sidebar-shortcut = 歷史側邊欄
zen-window-minimize-shortcut = 最小化視窗
zen-help-shortcut = 取得幫助
zen-preferences-shortcut = 設定
zen-hide-app-shortcut = 隱藏應用程式
zen-hide-other-apps-shortcut = 隱藏其它應用程式
zen-search-focus-shortcut = 輸入焦點移至搜尋列
zen-search-focus-shortcut-alt = 輸入焦點移至搜尋列 (備用)
zen-downloads-shortcut = 開啟下載項目
zen-addons-shortcut = 開啟擴充套件
zen-file-open-shortcut = 開啟檔案
zen-save-page-shortcut = 儲存頁面
zen-print-shortcut = 列印頁面
zen-close-shortcut-2 = 關閉分頁
zen-mute-toggle-shortcut = 切換靜音
zen-key-delete = 刪除鍵
zen-key-go-back = 返回
zen-key-go-forward = 前進
zen-nav-back-shortcut-alt = 導航返回 (備用)
zen-nav-fwd-shortcut-alt = 導航前進 (備用)
zen-history-show-all-shortcut = 顯示所有歷史
zen-key-enter-full-screen = 進入全畫面模式
zen-key-exit-full-screen = 離開全畫面模式
zen-reader-mode-toggle-shortcut-other = 切換閱讀模式
zen-picture-in-picture-toggle-shortcut = 切換子母畫面
zen-nav-reload-shortcut-2 = 重新整理
zen-key-about-processes = 關於執行程序
zen-page-source-shortcut = 頁面原始碼
zen-page-info-shortcut = 頁面資訊
zen-find-shortcut = 尋找
zen-search-find-again-shortcut = 找下一個
zen-search-find-again-shortcut-prev = 找上一個
zen-search-find-again-shortcut-2 = 再次尋找 (備用)
zen-bookmark-this-page-shortcut = 將目前頁面加入書籤
zen-bookmark-show-library-shortcut = 顯示書籤庫
zen-key-stop = 停止載入
zen-full-zoom-reduce-shortcut = 縮小
zen-full-zoom-enlarge-shortcut = 放大
zen-full-zoom-reset-shortcut = 縮放重設
zen-bidi-switch-direction-shortcut = 切換文字方向
zen-private-browsing-shortcut = 隱私瀏覽
zen-screenshot-shortcut = 截圖
zen-key-sanitize = 清除瀏覽紀錄
zen-quit-app-shortcut = 離開應用程式
zen-key-wr-capture-cmd = WR 抓取指令
zen-key-wr-toggle-capture-sequence-cmd = 切換 WR 抓取佇列
zen-nav-reload-shortcut = 重新整理頁面
zen-nav-reload-shortcut-skip-cache = 重新整理頁面 (忽略快取)
zen-close-shortcut = 關閉視窗
zen-close-tab-shortcut = 關閉分頁
zen-compact-mode-shortcut-show-sidebar = 切換浮動側邊欄
zen-compact-mode-shortcut-show-toolbar = 切換浮動工具列
zen-compact-mode-shortcut-toggle = 切換緊湊模式
zen-workspace-shortcut-switch-1 = 切換至工作區 1
zen-workspace-shortcut-switch-2 = 切換至工作區 2
zen-workspace-shortcut-switch-3 = 切換至工作區 3
zen-workspace-shortcut-switch-4 = 切換至工作區 4
zen-workspace-shortcut-switch-5 = 切換至工作區 5
zen-workspace-shortcut-switch-6 = 切換至工作區 6
zen-workspace-shortcut-switch-7 = 切換至工作區 7
zen-workspace-shortcut-switch-8 = 切換至工作區 8
zen-workspace-shortcut-switch-9 = 切換至工作區 9
zen-workspace-shortcut-switch-10 = 切換至工作區 10
zen-workspace-shortcut-forward = 下一個工作區
zen-workspace-shortcut-backward = 上一個工作區
zen-web-panel-shortcut-toggle = 切換網頁側邊欄
zen-sidebar-shortcut-toggle = 切換側邊欄寬度
zen-pinned-tab-shortcut-reset = 重置釘選分頁至其初始的網址
zen-split-view-shortcut-grid = 切換分割畫面
zen-split-view-shortcut-vertical = 切換垂直分割畫面
zen-split-view-shortcut-horizontal = 切換水平分割畫面
zen-split-view-shortcut-unsplit = 關閉分割畫面
zen-key-select-tab-1 = 選擇分頁 #1
zen-key-select-tab-2 = 選擇分頁 #2
zen-key-select-tab-3 = 選擇分頁 #3
zen-key-select-tab-4 = 選擇分頁 #4
zen-key-select-tab-5 = 選擇分頁 #5
zen-key-select-tab-6 = 選擇分頁 #6
zen-key-select-tab-7 = 選擇分頁 #7
zen-key-select-tab-8 = 選擇分頁 #8
zen-key-select-tab-last = 選擇最後一個分頁
zen-key-show-all-tabs = 顯示所有分頁
zen-key-goto-history = 前往歷史紀錄
zen-key-go-home = 返回首頁
zen-bookmark-show-sidebar-shortcut = 顯示書籤側邊欄
zen-bookmark-show-toolbar-shortcut = 顯示書籤工具列
zen-devtools-toggle-shortcut = Toggle DevTools
zen-devtools-toggle-browser-toolbox-shortcut = Toggle Browser Toolbox
zen-devtools-toggle-browser-console-shortcut = Toggle Browser Console
zen-devtools-toggle-responsive-design-mode-shortcut = Toggle Responsive Design Mode
zen-devtools-toggle-inspector-shortcut = Toggle Inspector
zen-devtools-toggle-web-console-shortcut = Toggle Web Console
zen-devtools-toggle-js-debugger-shortcut = Toggle JavaScript Debugger
zen-devtools-toggle-net-monitor-shortcut = Toggle Network Monitor
zen-devtools-toggle-style-editor-shortcut = Toggle Style Editor
zen-devtools-toggle-performance-shortcut = Toggle Performance
zen-devtools-toggle-storage-shortcut = Toggle Storage
zen-devtools-toggle-dom-shortcut = Toggle DOM
zen-devtools-toggle-accessibility-shortcut = Toggle Accessibility
