pane-zen-looks-title = 外觀與樣式
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = 更改預設的語言可能會讓網站更好的追蹤你。
zen-look-and-feel-colors-header = 選擇一個顏色主題
zen-look-and-feel-colors-description = 讓 { -brand-short-name } 成為你理想中的瀏覽器
zen-look-and-feel-themed-toolbar = 
    .label = 使工具列主題使用強調色
pane-zen-side-panels-title = 網頁側版
zen-side-panels-header = 網頁側版的一般設定
zen-side-panels-description = 用多個視窗來精進你的生產力！
zen-side-panels-enabled = 
    .label = 啟用網頁側板
zen-side-panels-close-on-blur = 
    .label = 當失去焦點且沒被盯選時關閉網頁側版
zen-look-and-feel-compact-view-header = 在緊湊模式下顯示
zen-look-and-feel-compact-view-description = 只顯示你需要用的工具欄！
zen-look-and-feel-compact-view-enabled = 
    .label = 啟用 { -brand-short-name } 的緊湊模式
zen-look-and-feel-compact-view-top-toolbar = 
    .label = 在緊湊模式中也隱藏頂部的工具欄
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = 在緊湊模式下切換或開啟新分頁時短暫彈出工具列
zen-look-and-feel-buttons-header = 按鈕樣式
zen-look-and-feel-buttons-description = 選擇你想要看到的按鈕樣式
zen-look-and-feel-pilled-buttons = 
    .label = Pilled 按鈕
pane-zen-workspaces-title = 工作區
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = 工作區
pane-zen-workspaces-header = 工作區
zen-settings-workspaces-header = 工作區的一般設定
zen-settings-workspaces-description = 有了工作區，你就可以同時瀏覽多個頁面！
zen-settings-workspaces-enabled = 
    .label = 啟用工作區 (實驗性的)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Hide the default container indicator in the tab bar
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = 允許工作區有自訂的固定分頁
pane-zen-theme-title = 主題設定
zen-vertical-tabs-title = 側邊欄與分頁排版
zen-vertical-tabs-header = 垂直分頁
zen-vertical-tabs-description = 用垂直的排版來管理你的分頁
zen-vertical-tabs-show-expand-button = 
    .label = 顯示擴展按鈕
zen-vertical-tabs-expand-tabs-by-default = 預設展開分頁
zen-vertical-tabs-dont-expand-tabs-by-default = 預設不展開分頁
zen-vertical-tabs-expand-tabs-on-hover = 懸停時預覽資訊卡 (無法在緊湊模式下使用)
zen-vertical-tabs-expand-tabs-header = 如何擴展分頁
zen-vertical-tabs-expand-tabs-description = 選擇要如何擴展側邊欄中的分頁
zen-theme-marketplace-header = Zen模式
zen-theme-marketplace-description = 從商店尋找並安裝主題。
zen-theme-marketplace-remove-button = 
    .label = 移除主題
zen-theme-marketplace-check-for-updates-button = 
    .label = 檢查更新
zen-theme-marketplace-updates-success = 主題更新成功
zen-theme-marketplace-updates-fail = 找不到任何更新！
zen-theme-marketplace-toggle-enabled-button = 
    .title = 關閉佈景主題
zen-theme-marketplace-toggle-disabled-button = 
    .title = 啟用佈景主題
zen-theme-marketplace-remove-confirmation = 您確定要移除此模組?
zen-theme-marketplace-close-modal = 關閉
zen-theme-marketplace-theme-header-title = 
    .title = CSS Selector: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = None
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Type something...
pane-zen-marketplace-title = Zen模式
zen-settings-workspaces-display-as-icon-strip = 
    .label = Display workspaces as an icon strip
zen-theme-marketplace-link = 造訪商店
zen-dark-theme-styles-header = 深色主題
zen-dark-theme-styles-description = 根據喜好客製化深色主題
zen-dark-theme-styles-amoled = 夜間主題
zen-dark-theme-styles-default = 預設深色主題
zen-dark-theme-styles-colorful = 有趣的深色主題
zen-compact-mode-styles-left = Hide Tab bar
zen-compact-mode-styles-top = Hide Top bar
zen-compact-mode-styles-both = Hide Both
pane-zen-CKS-title = 快捷鍵
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } 快捷鍵
zen-settings-CKS-header = 自定義你的快捷鍵
zen-settings-CKS-description = 依據你的愛好來更改預設的快捷鍵以近一步改善你的瀏覽體驗
zen-settings-CKS-disable-firefox = 
    .label = 停用 { -brand-short-name } 的預設快捷鍵
zen-settings-CKS-duplicate-shortcut = 
    .label = Duplicate Shortcut
zen-settings-CKS-reset-shortcuts = 
    .label = 重設為預設值
zenCKSOption-group-other = Other
zenCKSOption-group-windowAndTabManagement = Window & Tab Management
zenCKSOption-group-navigation = Navigation
zenCKSOption-group-searchAndFind = Search & Find
zenCKSOption-group-pageOperations = Page Operations
zenCKSOption-group-historyAndBookmarks = 瀏覽紀錄與書籤
zenCKSOption-group-mediaAndDisplay = Media & Display
zenCKSOption-group-zen-compact-mode = 緊湊模式
zenCKSOption-group-zen-workspace = 工作區
zenCKSOption-group-zen-other = 其它 Zen 功能
zenCKSOption-group-zen-split-view = 分割畫面
zen-key-quick-restart = 快速重啟
zen-window-new-shortcut = 開新視窗
zen-tab-new-shortcut = 開新分頁
zen-location-open-shortcut = 選取網址列
zen-location-open-shortcut-alt = 選取網址列 (Alt)
zen-key-undo-close-window = 還原已關閉視窗
zen-text-action-undo-shortcut = 復原
zen-text-action-redo-shortcut = 取消「復原」
zen-text-action-cut-shortcut = 剪下
zen-text-action-copy-shortcut = 複製
zen-text-action-paste-shortcut = 貼上
zen-text-action-select-all-shortcut = 全選
zen-text-action-delete-shortcut = 刪除
zen-history-show-all-shortcut-mac = 顯示所有瀏覽紀錄 (Mac)
zen-full-screen-shortcut = 切換全螢幕模式
zen-reader-mode-toggle-shortcut-windows = 切換閱讀模式 (Windows)
zen-picture-in-picture-toggle-shortcut-alt = 切換子母畫面 (Alt)
zen-picture-in-picture-toggle-shortcut-mac = 切換子母畫面 (Mac)
zen-picture-in-picture-toggle-shortcut-mac-alt = 切換子母畫面 (Mac Alt)
zen-page-source-shortcut-safari = 頁面原始碼 (Safari)
zen-nav-stop-shortcut = 停止載入
zen-history-sidebar-shortcut = 歷史側邊欄
zen-window-minimize-shortcut = 最小化視窗
zen-help-shortcut = 取得幫助
zen-preferences-shortcut = 設定
zen-hide-app-shortcut = Hide Application
zen-hide-other-apps-shortcut = Hide Other Applications
zen-search-focus-shortcut = Focus Search
zen-search-focus-shortcut-alt = Focus Search (Alt)
zen-downloads-shortcut = Open Downloads
zen-addons-shortcut = Open Add-ons
zen-file-open-shortcut = Open File
zen-save-page-shortcut = Save Page
zen-print-shortcut = Print Page
zen-close-shortcut-2 = Close Tab
zen-mute-toggle-shortcut = Toggle Mute
zen-key-delete = Delete Key
zen-key-go-back = Go Back
zen-key-go-forward = Go Forward
zen-nav-back-shortcut-alt = Navigate Back (Alt)
zen-nav-fwd-shortcut-alt = Navigate Forward (Alt)
zen-history-show-all-shortcut = Show All History
zen-key-enter-full-screen = Enter Full Screen
zen-key-exit-full-screen = Exit Full Screen
zen-reader-mode-toggle-shortcut-other = Toggle Reader Mode
zen-picture-in-picture-toggle-shortcut = Toggle Picture-in-Picture
zen-nav-reload-shortcut-2 = Reload Page
zen-key-about-processes = About Processes
zen-page-source-shortcut = 頁面原始碼
zen-page-info-shortcut = 頁面資訊
zen-find-shortcut = 尋找
zen-search-find-again-shortcut = Find Again
zen-search-find-again-shortcut-prev = Find Previous
zen-search-find-again-shortcut-2 = Find Again (Alt)
zen-bookmark-this-page-shortcut = 將目前頁面加入書籤
zen-bookmark-show-library-shortcut = Show Bookmarks Library
zen-key-stop = 停止載入
zen-full-zoom-reduce-shortcut = 縮小
zen-full-zoom-enlarge-shortcut = 放大
zen-full-zoom-reset-shortcut = 縮放重設
zen-bidi-switch-direction-shortcut = Switch Text Direction
zen-private-browsing-shortcut = Private Browsing
zen-screenshot-shortcut = Take Screenshot
zen-key-sanitize = Clear Browsing Data
zen-quit-app-shortcut = Quit Application
zen-key-wr-capture-cmd = WR Capture Command
zen-key-wr-toggle-capture-sequence-cmd = Toggle WR Capture Sequence
zen-nav-reload-shortcut = Reload Page
zen-nav-reload-shortcut-skip-cache = Reload Page (Skip Cache)
zen-close-shortcut = Close Window
zen-close-tab-shortcut = Close Tab
zen-compact-mode-shortcut-show-sidebar = Toggle Floating Sidebar
zen-compact-mode-shortcut-show-toolbar = Toggle Floating Toolbar
zen-compact-mode-shortcut-toggle = Toggle Compact Mode
zen-workspace-shortcut-switch-1 = Switch to Workspace 1
zen-workspace-shortcut-switch-2 = Switch to Workspace 2
zen-workspace-shortcut-switch-3 = Switch to Workspace 3
zen-workspace-shortcut-switch-4 = Switch to Workspace 4
zen-workspace-shortcut-switch-5 = Switch to Workspace 5
zen-workspace-shortcut-switch-6 = Switch to Workspace 6
zen-workspace-shortcut-switch-7 = Switch to Workspace 7
zen-workspace-shortcut-switch-8 = Switch to Workspace 8
zen-workspace-shortcut-switch-9 = Switch to Workspace 9
zen-workspace-shortcut-switch-10 = Switch to Workspace 10
zen-workspace-shortcut-forward = Forward Workspace
zen-workspace-shortcut-backward = Backward Workspace
zen-web-panel-shortcut-toggle = Toggle Web Panel
zen-sidebar-shortcut-toggle = Toggle Sidebar's Width
zen-split-view-shortcut-grid = Toggle Split View Grid
zen-split-view-shortcut-vertical = Toggle Split View Vertical
zen-split-view-shortcut-horizontal = Toggle Split View Horizontal
zen-split-view-shortcut-unsplit = Close Split View
zen-key-select-tab-1 = Select tab #1
zen-key-select-tab-2 = Select tab #2
zen-key-select-tab-3 = Select tab #3
zen-key-select-tab-4 = Select tab #4
zen-key-select-tab-5 = Select tab #5
zen-key-select-tab-6 = Select tab #6
zen-key-select-tab-7 = Select tab #7
zen-key-select-tab-8 = Select tab #8
zen-key-select-tab-last = Select last tab
zen-key-show-all-tabs = Show all tabs
zen-key-goto-history = Go to history
zen-key-go-home = Go Home
zen-bookmark-show-sidebar-shortcut = Show Bookmarks Sidebar
zen-bookmark-show-toolbar-shortcut = Show Bookmarks Toolbar
