zen-panel-ui-workspaces-text = Другие рабочие области
zen-panel-ui-workspaces-create-text = Создать рабочую область
zen-panel-ui-workspaces-create-save = 
    .label = Создать рабочую область
    .accesskey = С
zen-panel-ui-workspaces-create-cancel = 
    .label = Отмена
    .accesskey = С
zen-panel-ui-workspaces-edit-text = Редактировать проект
zen-panel-ui-workspaces-edit-save = 
    .label = Сохранить изменения
    .accesskey = С
zen-panel-ui-workspaces-edit-cancel = 
    .label = Отмена
    .accesskey = С
zen-workspaces-panel-context-delete = 
    .label = Удалить проект
    .accesskey = Д
zen-workspaces-panel-context-open = 
    .label = Открыть проект
    .accesskey = О
zen-workspaces-panel-context-set-default = 
    .label = Установить как проект по умолчанию
    .accesskey = С
zen-workspaces-panel-context-edit = 
    .label = Редактировать проект
    .accesskey = В
context-zen-change-workspace-tab = 
    .label = Перенести вкладку(-ки) на рабочую область
    .accesskey = С
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Установить контейнер по умолчанию
    .accesskey = О
zen-workspaces-change-gradient = 
    .label = Изменить цвета темы
    .accesskey = С
zen-bookmark-edit-panel-workspace-selector = 
    .value = Workspaces
    .accesskey = W
