zen-toolbar-context-tabs-right = 
    .label = Вкладки справа
    .accesskey = R
zen-toolbar-context-compact-mode = 
    .label = Компактный вид
    .accesskey = C
zen-toolbar-context-compact-mode-enable = 
    .label = Включить компактный вид
    .accesskey = D
zen-toolbar-context-compact-mode-just-tabs = 
    .label = Скрыть боковую панель
zen-toolbar-context-compact-mode-just-toolbar = 
    .label = Скрыть панель инструментов
zen-toolbar-context-compact-mode-hide-both = 
    .label = Скрыть обе панели
    .accesskey = H
sidebar-zen-sidepanel = 
    .label = Боковые панели
sidebar-zen-expand = 
    .label = Развернуть боковую панель
