zen-web-side-panel-context-mute-panel = 
    .label = Отключить звук
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = Включить звук
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = Отключить мобильный UserAgent
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Включить мобильный UserAgent
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = Выгрузить веб-панель
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = Удалить веб-панель
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = Открыть в новой вкладке
    .accesskey = N
zen-web-side-panel-context-open-in-container-tab = 
    .label = Open in Container Tab
    .accesskey = C
zen-web-side-panel-context-add-to-panel = 
    .label = Добавить в веб-панель
    .accesskey = A
zen-sidebar-introduction-title = Добро пожаловать в боковую панель Zen
zen-sidebar-introduction-description = Боковая панель Zen - новый способ просмотра веб-страниц. Нажмите на любую иконку, чтобы открыть веб-панель.
