zen-panel-ui-current-profile-text = текущий профиль
unified-extensions-description = Расширения используются для расширения функциональности { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = Сбросить закрепленную вкладку
    .accesskey = Р
tab-context-zen-add-essential = 
    .label = Add to Essentials
    .accesskey = E
tab-context-zen-remove-essential = 
    .label = Remove from Essentials
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Заменить прикрепленный URL текущим
    .accesskey = С
tab-zen-unload = 
    .label = Unload Tab
    .accesskey = У
zen-tabs-unloader-tab-actions = 
    .label = Действия выгрузчика вкладок
    .accesskey = Т
tab-zen-prevent-unload = 
    .label = Запретить выгрузку вкладки
    .accesskey = П
tab-zen-ignore-unload = 
    .label = Разрешить выгрузку вкладок
    .accesskey = В
zen-themes-corrupted = Ваш файл модов { -brand-short-name } повреждён. Он был сброшен к шаблону по умолчанию.
zen-panel-ui-gradient-generator-opacity-text = Contrast
zen-panel-ui-gradient-generator-texture-text = Текстура
zen-panel-ui-gradient-generator-custom-color = Пользовательский цвет
zen-panel-ui-gradient-generator-saved-message = Градиент успешно сохранен!
