zen-panel-ui-current-profile-text = текущий профиль
unified-extensions-description = Расширения используются для расширения функциональности { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = Сбросить закрепленную вкладку
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Заменить URL закрепленной вкладки текущим
    .accesskey = C
tab-zen-unload = 
    .label = Выгрузить вкладки
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Действия выгрузки вкладок
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Запретить выгрузку вкладок
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Allow Tab Unload
    .accesskey = I
