zen-panel-ui-current-window-text = Текущее окно
zen-panel-ui-workspaces-text = Другие рабочие области
zen-panel-ui-workspaces-create-text = Создать рабочую область
zen-panel-ui-workspaces-create-save=
  .label = Создать рабочую область
  .accesskey = S
zen-panel-ui-workspaces-create-cancel =
  .label = Отменить
  .accesskey = C
zen-workspaces-panel-context-delete =
    .label = Удалить рабочую область
    .accesskey = D
zen-workspaces-panel-context-open =
    .label = Открыть рабочую область
    .accesskey = O
zen-workspaces-panel-context-set-default =
    .label = Установить рабочую область по умолчанию
    .accesskey = S
context-zen-change-workspace-tab =
    .label = Изменить вкладку на рабочую область
    .accesskey = C
