zen-panel-ui-workspaces-text = Рабочие пространства
zen-panel-ui-workspaces-create = 
    .label = Create Space
zen-workspaces-panel-context-delete = 
    .label = Удалить пространство
    .accesskey = D
zen-workspaces-panel-change-name = 
    .label = Переименовать
zen-workspaces-panel-change-icon = 
    .label = Change Icon
zen-workspaces-panel-context-default-profile = 
    .label = Set Profile
zen-workspaces-how-to-reorder-title = How to reorder spaces
zen-workspaces-how-to-reorder-desc = Drag the space icons at the bottom of the sidebar to reorder them
zen-workspaces-change-theme = 
    .label = Edit Theme
zen-workspaces-panel-context-open = 
    .label = Открыть пространство
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Установить как пространство по умолчанию
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Редактировать пространство
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Перенести вкладку(-ки) на рабочее пространство
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Рабочие пространства
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Комплементарное
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Раздельное
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Аналоговое
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Триада
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Плавающее
zen-panel-ui-gradient-click-to-add = Нажмите, чтобы добавить цвет
zen-workspace-creation-name = 
    .placeholder = Space Name
zen-workspaces-panel-context-reorder = 
    .label = Reorder Spaces
zen-workspace-creation-profile = Profile
    .tooltiptext = Profiles are used to separate cookies and site data between spaces.
zen-workspace-creation-header = Create a Space
zen-workspace-creation-label = Spaces are used to organize your tabs and sessions.
zen-workspaces-delete-workspace-title = Delete Workspace?
zen-workspaces-delete-workspace-body = Are you sure you want to delete this workspace? This action cannot be undone.
