pane-zen-looks-title = Tampilan dan Nuansa
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Mengubah bahasa default dapat mempermudah situs web untuk melacak Anda.
zen-look-and-feel-colors-header = Pilih warna tema
zen-look-and-feel-colors-description = Buat { -brand-short-name } terlihat dan terasa seperti yang Anda suka
zen-look-and-feel-themed-toolbar = 
    .label = Buat toolbar bertema dengan warna aksen
pane-zen-side-panels-title = Panel Web Samping
zen-side-panels-header = Pengaturan umum untuk panel web
zen-side-panels-description = Tingkatkan produktivitas dengan memiliki beberapa tampilan sekaligus!
zen-side-panels-enabled = 
    .label = Aktifkan Panel Web Samping
zen-side-panels-close-on-blur = 
    .label = Tutup panel saat kehilangan fokus jika tidak dipin
zen-look-and-feel-compact-view-header = Tampilkan dalam tampilan ringkas
zen-look-and-feel-compact-view-description = Tampilkan hanya toolbar yang Anda gunakan!
zen-look-and-feel-compact-view-enabled = 
    .label = Aktifkan mode ringkas { -brand-short-name }
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Sembunyikan juga toolbar atas dalam mode ringkas
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Memunculkan menu alat saat mengganti tab atau membuka tab baru di mode ringkas
zen-look-and-feel-buttons-header = Gaya tombol
zen-look-and-feel-buttons-description = Pilih gaya tombol yang ingin Anda lihat
zen-look-and-feel-pilled-buttons = 
    .label = Tombol sudut melengkung
pane-zen-workspaces-title = Ruang Kerja
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = Ruang Kerja
pane-zen-workspaces-header = Ruang Kerja
zen-settings-workspaces-header = Pengaturan umum untuk ruang kerja
zen-settings-workspaces-description = Dengan ruang kerja, Anda bisa memiliki beberapa sesi browsing sekaligus!
zen-settings-workspaces-enabled = 
    .label = Aktifkan Ruang Kerja (Eksperimental)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Sembunyikan indikator kontainer default di bilah tab
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Memperbolehkan tab dipin di area Ruang Kerja
pane-zen-theme-title = Pengaturan Tema
zen-vertical-tabs-title = Susunan sidebar dan tab
zen-vertical-tabs-header = Tab Vertikal
zen-vertical-tabs-description = Kelola tab Anda dalam susunan vertikal
zen-vertical-tabs-show-expand-button = 
    .label = Tampilkan Tombol Perluas
zen-vertical-tabs-expand-tabs-by-default = Perluas Tab Secara Default
zen-vertical-tabs-dont-expand-tabs-by-default = Jangan Perluas Tab Secara Default
zen-vertical-tabs-expand-tabs-on-hover = Perluas Tab Saat Mengarahkan Kursor (Tidak berfungsi pada mode ringkas)
zen-vertical-tabs-expand-tabs-header = Cara memperluas tab
zen-vertical-tabs-expand-tabs-description = Pilih cara memperluas tab di sidebar
zen-theme-marketplace-header = Zen Mods
zen-theme-marketplace-description = Temukan dan pasang tema dari toko.
zen-theme-marketplace-remove-button = 
    .label = Hapus Tema
zen-theme-marketplace-check-for-updates-button = 
    .label = Periksa Pembaruan
zen-theme-marketplace-updates-success = Tema berhasil diperbarui
zen-theme-marketplace-updates-fail = Tidak dapat menemukan pembaruan!
zen-theme-marketplace-toggle-enabled-button = 
    .title = Nonaktifkan Tema
zen-theme-marketplace-toggle-disabled-button = 
    .title = Aktifkan Tema
zen-theme-marketplace-remove-confirmation = Apakah kamu yakin ingin menghapus mod ini?
zen-theme-marketplace-close-modal = Tutup
zen-theme-marketplace-theme-header-title = 
    .title = Selektor CSS: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = Tak ada
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Ketik sesuatu...
pane-zen-marketplace-title = Zen Mods
zen-settings-workspaces-display-as-icon-strip = 
    .label = Tampilkan ruang kerja sebagai strip ikon
zen-theme-marketplace-link = Kunjungi Toko
zen-dark-theme-styles-header = Gaya Tema Gelap
zen-dark-theme-styles-description = Mengkustomisasi mode gelap sesuai kemauanmu
zen-dark-theme-styles-amoled = Tema Gelap
zen-dark-theme-styles-default = Tema Gelap Bawaan
zen-dark-theme-styles-colorful = Tema Gelap Berwarna
zen-compact-mode-styles-left = Sembunyikan bilah tab
zen-compact-mode-styles-top = Sembunyikan Bilah atas
zen-compact-mode-styles-both = Sembunyikan Keduanya
pane-zen-CKS-title = Pintasan Keyboard
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = Pintasan Keyboard { -brand-short-name }
zen-settings-CKS-header = Sesuaikan pintasan keyboard Anda
zen-settings-CKS-description = Ubah pintasan keyboard default sesuai keinginan Anda dan tingkatkan pengalaman browsing Anda
zen-settings-CKS-disable-firefox = 
    .label = Nonaktifkan pintasan keyboard default { -brand-short-name }
zen-settings-CKS-duplicate-shortcut = 
    .label = Duplicate Shortcut
zenCKSOption-group-other = Other
zenCKSOption-group-windowAndTabManagement = Window & Tab Management
zenCKSOption-group-navigation = Navigation
zenCKSOption-group-searchAndFind = Search & Find
zenCKSOption-group-pageOperations = Page Operations
zenCKSOption-group-historyAndBookmarks = History & Bookmarks
zenCKSOption-group-mediaAndDisplay = Media & Display
zenCKSOption-group-zen-compact-mode = Compact Mode
zenCKSOption-group-zen-workspace = Workspaces
zenCKSOption-group-zen-other = Other Zen Features
zenCKSOption-group-zen-split-view = Split View
zen-key-quick-restart = Quick Restart
zen-window-new-shortcut = New Window
zen-tab-new-shortcut = New Tab
zen-location-open-shortcut = Open Location
zen-location-open-shortcut-alt = Open Location (Alt)
zen-search-focus-shortcut = Focus Search
zen-search-focus-shortcut-alt = Focus Search (Alt)
zen-downloads-shortcut = Open Downloads
zen-addons-shortcut = Open Add-ons
zen-file-open-shortcut = Open File
zen-save-page-shortcut = Save Page
zen-print-shortcut = Print Page
zen-close-shortcut-2 = Close Tab
zen-mute-toggle-shortcut = Toggle Mute
zen-key-delete = Delete Key
zen-key-go-back = Go Back
zen-key-go-forward = Go Forward
zen-nav-back-shortcut-alt = Navigate Back (Alt)
zen-nav-fwd-shortcut-alt = Navigate Forward (Alt)
zen-history-show-all-shortcut = Show All History
zen-key-enter-full-screen = Enter Full Screen
zen-key-exit-full-screen = Exit Full Screen
zen-reader-mode-toggle-shortcut-other = Toggle Reader Mode
zen-picture-in-picture-toggle-shortcut = Toggle Picture-in-Picture
zen-nav-reload-shortcut-2 = Reload Page
zen-key-about-processes = About Processes
zen-page-source-shortcut = View Page Source
zen-page-info-shortcut = View Page Info
zen-find-shortcut = Find on Page
zen-search-find-again-shortcut = Find Again
zen-search-find-again-shortcut-prev = Find Previous
zen-search-find-again-shortcut-2 = Find Again (Alt)
zen-bookmark-this-page-shortcut = Bookmark This Page
zen-bookmark-show-library-shortcut = Show Bookmarks Library
zen-key-stop = Stop Loading
zen-full-zoom-reduce-shortcut = Zoom Out
zen-full-zoom-enlarge-shortcut = Zoom In
zen-full-zoom-reset-shortcut = Reset Zoom
zen-bidi-switch-direction-shortcut = Switch Text Direction
zen-private-browsing-shortcut = Private Browsing
zen-screenshot-shortcut = Take Screenshot
zen-key-sanitize = Clear Browsing Data
zen-quit-app-shortcut = Quit Application
zen-key-wr-capture-cmd = WR Capture Command
zen-key-wr-toggle-capture-sequence-cmd = Toggle WR Capture Sequence
zen-nav-reload-shortcut = Reload Page
zen-nav-reload-shortcut-skip-cache = Reload Page (Skip Cache)
zen-close-shortcut = Close Window
zen-close-tab-shortcut = Close Tab
zen-compact-mode-shortcut-show-sidebar = Toggle Floating Sidebar
zen-compact-mode-shortcut-show-toolbar = Toggle Floating Toolbar
zen-compact-mode-shortcut-toggle = Toggle Compact Mode
zen-workspace-shortcut-switch-1 = Switch to Workspace 1
zen-workspace-shortcut-switch-2 = Switch to Workspace 2
zen-workspace-shortcut-switch-3 = Switch to Workspace 3
zen-workspace-shortcut-switch-4 = Switch to Workspace 4
zen-workspace-shortcut-switch-5 = Switch to Workspace 5
zen-workspace-shortcut-switch-6 = Switch to Workspace 6
zen-workspace-shortcut-switch-7 = Switch to Workspace 7
zen-workspace-shortcut-switch-8 = Switch to Workspace 8
zen-workspace-shortcut-switch-9 = Switch to Workspace 9
zen-workspace-shortcut-switch-10 = Switch to Workspace 10
zen-workspace-shortcut-forward = Forward Workspace
zen-workspace-shortcut-backward = Backward Workspace
zen-web-panel-shortcut-toggle = Toggle Web Panel
zen-sidebar-shortcut-toggle = Toggle Sidebar's Width
zen-split-view-shortcut-grid = Toggle Split View Grid
zen-split-view-shortcut-vertical = Toggle Split View Vertical
zen-split-view-shortcut-horizontal = Toggle Split View Horizontal
zen-split-view-shortcut-unsplit = Close Split View
