pane-zen-looks-title = Tampilan dan Nuansa
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Mengubah bahasa default dapat mempermudah situs web untuk melacak Anda.
zen-look-and-feel-colors-header = Pilih warna tema
zen-look-and-feel-colors-description = Buat { -brand-short-name } terlihat dan terasa seperti yang Anda suka
zen-look-and-feel-use-workspace-colors = 
    .label = Use workspace colors as primary color
pane-zen-side-panels-title = Panel Web Samping
zen-side-panels-header = Pengaturan umum untuk panel web
zen-side-panels-description = Tingkatkan produktivitas dengan memiliki beberapa tampilan sekaligus!
zen-side-panels-enabled = 
    .label = Aktifkan Panel Web Samping
zen-side-panels-close-on-blur = 
    .label = Tutup panel saat kehilangan fokus jika tidak di-pin
zen-vertical-tabs-show-bottom-border = 
    .label = Tampilkan batas untuk ikon bawah
zen-vertical-tabs-layout-header = Tata Letak Browser
zen-vertical-tabs-layout-description = Pilih tata letak yang paling cocok untuk Anda
zen-layout-single-toolbar = Toolbar Tunggal
zen-layout-multiple-toolbar = Toolbar Terpisah
zen-layout-collapsed-toolbar = Toolbar yang Diciutkan
sync-currently-syncing-workspaces = Ruang Kerja
sync-engine-workspaces = 
    .label = Ruang Kerja
    .tooltiptext = Sinkronkan ruang kerja Anda di seluruh perangkat
    .accesskey = W
zen-glance-title = Glance
zen-glance-header = General settings for glance
zen-glance-description = Get a quick overview of your links without opening them in a new tab
zen-glance-trigger-label = Trigger method
zen-glance-enabled = 
    .label = Enable Glance
zen-glance-trigger-ctrl-click = 
    .label = Ctrl + Klik
zen-glance-trigger-alt-click = 
    .label = Alt + Klik
zen-glance-trigger-shift-click = 
    .label = Shift + Klik
zen-glance-trigger-meta-click = 
    .label = Windows (Command) + Klik
zen-glance-trigger-mantain-click = 
    .label = Mantain Click
zen-look-and-feel-compact-view-header = Tampilkan dalam tampilan ringkas
zen-look-and-feel-compact-view-description = Tampilkan hanya toolbar yang Anda gunakan!
zen-look-and-feel-compact-view-enabled = 
    .label = Aktifkan mode ringkas { -brand-short-name }
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Sembunyikan juga toolbar atas dalam mode ringkas
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Buat bilah tab muncul sebentar saat beralih atau membuka tab baru dalam mode ringkas
zen-look-and-feel-buttons-header = Gaya tombol
zen-look-and-feel-buttons-description = Pilih gaya tombol yang ingin Anda lihat
zen-look-and-feel-pilled-buttons = 
    .label = Tombol sudut melengkung
pane-zen-tabs-title = Pengelolaan Tab
category-zen-workspaces = 
    .tooltiptext = { pane-zen-tabs-title }
pane-settings-workspaces-title = Ruang Kerja
pane-zen-tabs-unloader-title = Pelepas Tab
zen-tabs-unloader-header = Pengaturan umum untuk pelepas tab
zen-tabs-unloader-description = Secara otomatis lepaskan tab yang tidak digunakan untuk menghemat memori
zen-tabs-unloader-enabled = 
    .label = Aktifkan Pelepas Tab
zen-tabs-unloader-unload-delay = 
    .label = Lepaskan tab setelah
zen-tabs-unloader-unload-delay-description = Waktu dalam menit setelah tab akan dilepaskan
zen-look-and-feel-compact-toolbar-themed = 
    .label = Gunakan latar belakang bertema untuk bilah atas di mode ringkas
zen-look-and-feel-compact-sidebar-themed = 
    .label = Gunakan latar belakang bertema untuk bilah tab di mode ringkas
pane-zen-pinned-tab-manager-title = Tab yang Disematkan
zen-pinned-tab-manager-header = Pengaturan umum untuk tab yang disematkan
zen-pinned-tab-manager-description = Kelola perilaku tambahan dari tab yang disematkan
zen-pinned-tab-manager-restore-pinned-tabs-to-pinned-url = 
    .label = Pulihkan tab yang disematkan ke URL semula saat mulai ulang
zen-pinned-tab-manager-container-specific-essentials-enabled = 
    .label = Aktifkan kontainer-spesific essentials
zen-pinned-tab-manager-close-shortcut-behavior-label = Perilaku Pintasan Tutup Tab
zen-pinned-tab-manager-reset-unload-switch-close-shortcut-option = 
    .label = Setel Ulang URL, lepaskan, dan beralih ke tab berikutnya
zen-pinned-tab-manager-unload-switch-close-shortcut-option = 
    .label = Lepaskan dan beralih ke tab berikutnya
zen-pinned-tab-manager-reset-switch-close-shortcut-option = 
    .label = Setel Ulang URL dan beralih ke tab berikutnya
zen-pinned-tab-manager-switch-close-shortcut-option = 
    .label = Beralih ke tab berikutnya
zen-pinned-tab-manager-reset-close-shortcut-option = 
    .label = Setel Ulang URL
zen-pinned-tab-manager-close-close-shortcut-option = 
    .label = Tutup tab
pane-zen-workspaces-header = Ruang Kerja
zen-settings-workspaces-header = Pengaturan umum untuk ruang kerja
zen-settings-workspaces-description = Dengan ruang kerja, Anda bisa memiliki beberapa sesi browsing sekaligus!
zen-settings-workspaces-enabled = 
    .label = Aktifkan Ruang Kerja (Eksperimental)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Sembunyikan indikator kontainer default di bilah tab
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Izinkan ruang kerja memiliki tab yang disematkan sendiri
zen-key-unsafed = Pintasan belum tersimpan! Simpan dengan mengklik tombol "Escape" setelah mengetik ulang.
zen-key-conflict = Konflik dengan pintasan lain
pane-zen-theme-title = Pengaturan Tema
zen-vertical-tabs-title = Susunan sidebar dan tab
zen-vertical-tabs-header = Tab Vertikal
zen-vertical-tabs-description = Kelola tab Anda dalam susunan vertikal
zen-vertical-tabs-show-expand-button = 
    .label = Tampilkan Tombol Perluas
zen-vertical-tabs-newtab-on-tab-list = 
    .label = Tampilkan Tombol Tab Baru pada Daftar Tab
zen-vertical-tabs-newtab-top-button-border = 
    .label = Tampilkan batas pemisah ketika tombol tab baru ada di bagian bawah
zen-vertical-tabs-newtab-top-button-up = 
    .label = Pindahkan tombol tab baru ke atas
zen-vertical-tabs-expand-tabs-by-default = Perluas Tab Secara Default
zen-vertical-tabs-dont-expand-tabs-by-default = Jangan Perluas Tab Secara Default
zen-vertical-tabs-expand-tabs-on-hover = Expand Tabs on Hover (Won't work on compact mode)
zen-vertical-tabs-expand-tabs-header = Cara memperluas tab
zen-vertical-tabs-expand-tabs-description = Pilih cara memperluas tab di sidebar
zen-theme-marketplace-header = Zen Mods
zen-theme-disable-all-enabled = 
    .title = Disable all themes
zen-theme-disable-all-disabled = 
    .title = Enable all themes
zen-theme-marketplace-description = Temukan dan pasang tema dari toko.
zen-theme-marketplace-remove-button = 
    .label = Hapus Tema
zen-theme-marketplace-check-for-updates-button = 
    .label = Periksa Pembaruan
zen-theme-marketplace-updates-success = Tema berhasil diperbarui
zen-theme-marketplace-updates-fail = Tidak dapat menemukan pembaruan!
zen-theme-marketplace-toggle-enabled-button = 
    .title = Nonaktifkan Tema
zen-theme-marketplace-toggle-disabled-button = 
    .title = Aktifkan Tema
zen-theme-marketplace-remove-confirmation = Apakah kamu yakin ingin menghapus mod ini?
zen-theme-marketplace-close-modal = Tutup
zen-theme-marketplace-theme-header-title = 
    .title = Selektor CSS: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = Tak ada
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Ketik sesuatu...
pane-zen-marketplace-title = Zen Mods
zen-settings-workspaces-display-as-icon-strip = 
    .label = Tampilkan ruang kerja sebagai strip ikon
zen-settings-workspaces-force-container-tabs-to-workspace = 
    .label = Saat membuka tab kontainer, otomatis pindahkan ke ruang kerja default kontainer tab itu
zen-settings-workspaces-hide-deactivated-workspaces = 
    .label = Samarkan ikon ruang kerja yang tidak digunakan
zen-theme-marketplace-link = Kunjungi Toko
zen-dark-theme-styles-header = Gaya Tema Gelap
zen-dark-theme-styles-description = Mengkustomisasi mode gelap sesuai kemauanmu
zen-dark-theme-styles-amoled = Tema Gelap (Amoled)
zen-dark-theme-styles-default = Tema Gelap Bawaan
zen-dark-theme-styles-colorful = Tema Gelap Berwarna
zen-split-view-title = Tampilan Belah
zen-split-view-header = Fungsionalitas Tampilan Belah
zen-split-view-description = Bagi browser Anda menjadi beberapa tampilan, memungkinkan Anda menjelajahi beberapa situs web sekaligus
zen-split-view-change-on-hover = 
    .label = Ubah tab saat melayangkan kursor
zen-compact-mode-styles-left = Sembunyikan Bilah Tab
zen-compact-mode-styles-top = Sembunyikan Bilah Atas
zen-compact-mode-styles-both = Sembunyikan Keduanya
zen-urlbar-title = Bilah URL Zen
zen-urlbar-header = Pengaturan umum untuk bilah URL
zen-urlbar-description = Sesuaikan bilah URL sesuai keinginan Anda
zen-urlbar-behavior-label = Perilaku
zen-urlbar-behavior-normal = 
    .label = Normal
zen-urlbar-behavior-floating-on-type = 
    .label = Hanya mengambang saat mengetik
zen-urlbar-behavior-float = 
    .label = Selalu mengambang
pane-zen-CKS-title = Pintasan Keyboard
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = Pintasan Keyboard { -brand-short-name }
zen-settings-CKS-header = Sesuaikan pintasan keyboard Anda
zen-settings-CKS-description = Ubah pintasan keyboard default sesuai keinginan Anda dan tingkatkan pengalaman browsing Anda
zen-settings-CKS-disable-firefox = 
    .label = Nonaktifkan pintasan keyboard default { -brand-short-name }
zen-settings-CKS-duplicate-shortcut = 
    .label = Gandakan Pintasan
zen-settings-CKS-reset-shortcuts = 
    .label = Kembalikan ke Setelan Awal
zenCKSOption-group-other = Lainnya
zenCKSOption-group-windowAndTabManagement = Pengelolaan Tab & Jendela
zenCKSOption-group-navigation = Navigasi
zenCKSOption-group-searchAndFind = Cari & Temukan
zenCKSOption-group-pageOperations = Page Operations
zenCKSOption-group-historyAndBookmarks = Riwayat & Markah
zenCKSOption-group-mediaAndDisplay = Media & Tampilan
zenCKSOption-group-zen-compact-mode = Mode Ringkas
zenCKSOption-group-zen-workspace = Ruang Kerja
zenCKSOption-group-zen-other = Fitur Zen Lainnya
zenCKSOption-group-zen-split-view = Tampilan Belah
zenCKSOption-group-devTools = Developer Tools
zen-key-quick-restart = Mulai Ulang Cepat
zen-window-new-shortcut = Jendela Baru
zen-tab-new-shortcut = Tab Baru
zen-key-redo = Ulangi
zen-restore-last-closed-tab-shortcut = Pulihkan Tab yang Terakhir Ditutup
zen-location-open-shortcut = Buka Lokasi
zen-location-open-shortcut-alt = Buka Lokasi
zen-key-undo-close-window = Batalkan Tutup Jendela
zen-text-action-undo-shortcut = Batalkan
zen-text-action-redo-shortcut = Ulangi
zen-text-action-cut-shortcut = Potong
zen-text-action-copy-shortcut = Salin
zen-text-action-copy-url-shortcut = Salin URL saat ini
zen-text-action-paste-shortcut = Tempel
zen-text-action-select-all-shortcut = Pilih Semua
zen-text-action-delete-shortcut = Hapus
zen-history-show-all-shortcut-mac = Tampilkan Semua Riwayat (Mac)
zen-full-screen-shortcut = Aktif/Nonaktifkan Layar Penuh
zen-reader-mode-toggle-shortcut-windows = Toggle Reader Mode (Windows)
zen-picture-in-picture-toggle-shortcut-alt = Toggle Picture-in-Picture (Alt)
zen-picture-in-picture-toggle-shortcut-mac = Toggle Picture-in-Picture (Mac)
zen-picture-in-picture-toggle-shortcut-mac-alt = Toggle Picture-in-Picture (Mac Alt)
zen-page-source-shortcut-safari = Lihat Sumber Halaman (Safari)
zen-nav-stop-shortcut = Berhenti Memuat
zen-history-sidebar-shortcut = Tampilkan Sidebar Riwayat
zen-window-minimize-shortcut = Minimalkan Jendela
zen-help-shortcut = Buka Bantuan
zen-preferences-shortcut = Buka Preferensi
zen-hide-app-shortcut = Sembunyikan Aplikasi
zen-hide-other-apps-shortcut = Sembunyikan Aplikasi Lain
zen-search-focus-shortcut = Focus Search
zen-search-focus-shortcut-alt = Focus Search (Alt)
zen-downloads-shortcut = Buka Unduhan
zen-addons-shortcut = Buka Add-on
zen-file-open-shortcut = Buka Berkas
zen-save-page-shortcut = Simpan Halaman
zen-print-shortcut = Cetak Halaman
zen-close-shortcut-2 = Tutup Tab
zen-mute-toggle-shortcut = Bisukan/Bunyikan Audio
zen-key-delete = Hapus Kunci
zen-key-go-back = Kembali
zen-key-go-forward = Lanjut
zen-nav-back-shortcut-alt = Navigate Back (Alt)
zen-nav-fwd-shortcut-alt = Navigate Forward (Alt)
zen-history-show-all-shortcut = Tampilkan Semua Riwayat
zen-key-enter-full-screen = Masuk Layar Penuh
zen-key-exit-full-screen = Keluar Dari Layar Penuh
zen-reader-mode-toggle-shortcut-other = Aktif/nonaktifkan Mode Membaca
zen-picture-in-picture-toggle-shortcut = Aktif/nonaktifkan Picture-in-Picture
zen-nav-reload-shortcut-2 = Muat Ulang Halaman
zen-key-about-processes = Tentang Proses
zen-page-source-shortcut = Lihat Sumber Halaman
zen-page-info-shortcut = Lihat Info Halaman
zen-find-shortcut = Temukan di Halaman
zen-search-find-again-shortcut = Temukan Lagi
zen-search-find-again-shortcut-prev = Cari Sebelumnya
zen-search-find-again-shortcut-2 = Cari Lagi (Alt)
zen-bookmark-this-page-shortcut = Markahi Laman Ini
zen-bookmark-show-library-shortcut = Tampilkan Pustaka Bookmark
zen-key-stop = Berhenti Memuat
zen-full-zoom-reduce-shortcut = Perkecil
zen-full-zoom-enlarge-shortcut = Perbesar
zen-full-zoom-reset-shortcut = Reset Perbesaran
zen-bidi-switch-direction-shortcut = Beralih Arah Teks
zen-private-browsing-shortcut = Penjelajahan Pribadi
zen-screenshot-shortcut = Ambil Tangkapan Layar
zen-key-sanitize = Hapus Data Penelusuran
zen-quit-app-shortcut = Keluar dari Aplikasi
zen-key-wr-capture-cmd = WR Capture Command
zen-key-wr-toggle-capture-sequence-cmd = Toggle WR Capture Sequence
zen-nav-reload-shortcut = Muat Ulang Halaman
zen-nav-reload-shortcut-skip-cache = Muat Ulang Halaman (Lewati Cache)
zen-close-shortcut = Tutup Jendela
zen-close-tab-shortcut = Tutup Tab
zen-compact-mode-shortcut-show-sidebar = Toggle Floating Sidebar
zen-compact-mode-shortcut-show-toolbar = Toggle Floating Toolbar
zen-compact-mode-shortcut-toggle = Aktifkan/Sembunyikan Mode Ringkas
zen-workspace-shortcut-switch-1 = Beralih ke Ruang Kerja 1
zen-workspace-shortcut-switch-2 = Beralih ke Ruang Kerja 2
zen-workspace-shortcut-switch-3 = Beralih ke Ruang Kerja 3
zen-workspace-shortcut-switch-4 = Beralih ke Ruang Kerja 4
zen-workspace-shortcut-switch-5 = Beralih ke Ruang Kerja 5
zen-workspace-shortcut-switch-6 = Beralih ke Ruang Kerja 6
zen-workspace-shortcut-switch-7 = Beralih ke Ruang Kerja 7
zen-workspace-shortcut-switch-8 = Beralih ke Ruang Kerja 8
zen-workspace-shortcut-switch-9 = Beralih ke Ruang Kerja 9
zen-workspace-shortcut-switch-10 = Beralih ke Ruang Kerja 10
zen-workspace-shortcut-forward = Forward Workspace
zen-workspace-shortcut-backward = Backward Workspace
zen-web-panel-shortcut-toggle = Aktifkan/Sembunyikan Panel Web
zen-sidebar-shortcut-toggle = Toggle Sidebar's Width
zen-pinned-tab-shortcut-reset = Reset Pinned Tab to Pinned URL
zen-split-view-shortcut-grid = Toggle Split View Grid
zen-split-view-shortcut-vertical = Toggle Split View Vertical
zen-split-view-shortcut-horizontal = Toggle Split View Horizontal
zen-split-view-shortcut-unsplit = Tutup Tampilan Belah
zen-key-select-tab-1 = Pilih tab #1
zen-key-select-tab-2 = Pilih tab #2
zen-key-select-tab-3 = Pilih tab #3
zen-key-select-tab-4 = Pilih tab #4
zen-key-select-tab-5 = Pilih tab #5
zen-key-select-tab-6 = Pilih tab #6
zen-key-select-tab-7 = Pilih tab #7
zen-key-select-tab-8 = Pilih tab #8
zen-key-select-tab-last = Pilih tab terakhir
zen-key-show-all-tabs = Tampilkan semua tab
zen-key-goto-history = Pergi ke riwayat
zen-key-go-home = Go Home
zen-bookmark-show-sidebar-shortcut = Tampilkan Bilah Samping Markah
zen-bookmark-show-toolbar-shortcut = Tampilkan Bilah Alat Markah
zen-devtools-toggle-shortcut = Toggle DevTools
zen-devtools-toggle-browser-toolbox-shortcut = Toggle Browser Toolbox
zen-devtools-toggle-browser-console-shortcut = Toggle Browser Console
zen-devtools-toggle-responsive-design-mode-shortcut = Toggle Responsive Design Mode
zen-devtools-toggle-inspector-shortcut = Toggle Inspector
zen-devtools-toggle-web-console-shortcut = Toggle Web Console
zen-devtools-toggle-js-debugger-shortcut = Toggle JavaScript Debugger
zen-devtools-toggle-net-monitor-shortcut = Toggle Network Monitor
zen-devtools-toggle-style-editor-shortcut = Toggle Style Editor
zen-devtools-toggle-performance-shortcut = Toggle Performance
zen-devtools-toggle-storage-shortcut = Toggle Storage
zen-devtools-toggle-dom-shortcut = Toggle DOM
zen-devtools-toggle-accessibility-shortcut = Toggle Accessibility
