pane-zen-looks-title = Tampilan dan Nuansa
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Mengubah bahasa default dapat mempermudah situs web untuk melacak Anda.
zen-look-and-feel-colors-header = Pilih warna tema
zen-look-and-feel-colors-description = Buat { -brand-short-name } terlihat dan terasa seperti yang Anda suka
zen-look-and-feel-themed-toolbar = 
    .label = Buat toolbar bertema dengan warna aksen
pane-zen-side-panels-title = Panel Web Samping
zen-side-panels-header = Pengaturan umum untuk panel web
zen-side-panels-description = Tingkatkan produktivitas dengan memiliki beberapa tampilan sekaligus!
zen-side-panels-enabled = 
    .label = Aktifkan Panel Web Samping
zen-side-panels-close-on-blur = 
    .label = Tutup panel saat kehilangan fokus jika tidak dipin
zen-look-and-feel-compact-view-header = Tampilkan dalam tampilan ringkas
zen-look-and-feel-compact-view-description = Tampilkan hanya toolbar yang Anda gunakan!
zen-look-and-feel-compact-view-enabled = 
    .label = Aktifkan mode ringkas { -brand-short-name }
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Sembunyikan juga toolbar atas dalam mode ringkas
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Memunculkan menu alat saat mengganti tab atau membuka tab baru di mode ringkas
zen-look-and-feel-buttons-header = Gaya tombol
zen-look-and-feel-buttons-description = Pilih gaya tombol yang ingin Anda lihat
zen-look-and-feel-pilled-buttons = 
    .label = Tombol sudut melengkung
pane-zen-workspaces-title = Ruang Kerja
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = Ruang Kerja
pane-zen-workspaces-header = Ruang Kerja
zen-settings-workspaces-header = Pengaturan umum untuk ruang kerja
zen-settings-workspaces-description = Dengan ruang kerja, Anda bisa memiliki beberapa sesi browsing sekaligus!
zen-settings-workspaces-enabled = 
    .label = Aktifkan Ruang Kerja (Eksperimental)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Menyembunyikan indikator kontainer bawaan di barisan tab
pane-zen-theme-title = Pengaturan Tema
zen-vertical-tabs-title = Susunan sidebar dan tab
zen-vertical-tabs-header = Tab Vertikal
zen-vertical-tabs-description = Kelola tab Anda dalam susunan vertikal
zen-vertical-tabs-show-expand-button = 
    .label = Tampilkan Tombol Perluas
zen-vertical-tabs-expand-tabs-by-default = Perluas Tab Secara Default
zen-vertical-tabs-dont-expand-tabs-by-default = Jangan Perluas Tab Secara Default
zen-vertical-tabs-expand-tabs-on-hover = Perluas Tab Saat Mengarahkan Kursor (Tidak berfungsi pada mode ringkas)
zen-vertical-tabs-expand-tabs-header = Cara memperluas tab
zen-vertical-tabs-expand-tabs-description = Pilih cara memperluas tab di sidebar
zen-theme-marketplace-header = Toko Tema
zen-theme-marketplace-description = Temukan dan pasang tema dari toko.
zen-theme-marketplace-remove-button = 
    .label = Hapus Tema
zen-theme-marketplace-check-for-updates-button = 
    .label = Periksa Pembaruan
zen-theme-marketplace-updates-success = Tema berhasil diperbarui
zen-theme-marketplace-updates-fail = Tidak dapat menemukan pembaruan!
pane-zen-marketplace-title = Toko Tema
zen-look-and-feel-legacy-toolbar = 
    .label = Menggunakan posisi lawas untuk menu alat. Harus restart!
zen-theme-marketplace-link = Kunjungi Toko
zen-dark-theme-styles-header = Gaya Tema Gelap
zen-dark-theme-styles-description = Mengkustomisasi mode gelap sesuai kemauanmu
zen-dark-theme-styles-amoled = Hitam Amoled
zen-dark-theme-styles-default = Tema Gelap Bawaan
zen-dark-theme-styles-colorful = Tema Gelap Berwarna
pane-zen-CKS-title = Pintasan Keyboard
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = Pintasan Keyboard { -brand-short-name }
zen-settings-CKS-header = Sesuaikan pintasan keyboard Anda
zen-settings-CKS-description = Ubah pintasan keyboard default sesuai keinginan Anda dan tingkatkan pengalaman browsing Anda
zen-settings-CKS-disable-firefox = 
    .label = Nonaktifkan pintasan keyboard default { -brand-short-name }
zen-cks-group-tab-action = Aksi Tab
zen-cks-group-page-action = Aksi Halaman
zen-cks-group-visible-action = Aksi Terlihat
zen-cks-group-history-action = Aksi Riwayat
zen-cks-group-search-action = Aksi Pencarian
zen-cks-group-tools-action = Aksi Alat
zen-cks-group-bookmark-action = Aksi Bookmark
zen-cks-group-open-page-action = Aksi Buka Halaman
zen-cks-group-downloads-action = Aksi Unduhan
zen-cks-group-sidebar-action = Aksi Sidebar
zen-cks-group-compact-mode-action = Aksi Mode Ringkas
zen-cks-group-split-view-action = Aksi Tampilan Terpisah
zen-cks-group-workspace-action = Aksi Ruang Kerja
open-new-tab = Buka Tab Baru
close-tab = Tutup Tab
open-new-window = Buka Jendela Baru
open-new-private-window = Buka Jendela Pribadi Baru
close-window = Tutup Jendela
restore-last-tab = Pulihkan Tab Terakhir
restore-last-window = Pulihkan Jendela Terakhir
show-next-tab = Tampilkan Tab Berikutnya
show-previous-tab = Tampilkan Tab Sebelumnya
show-all-tabs-panel = Tampilkan Panel Semua Tab
send-with-mail = Kirim Halaman dengan Email
save-page = Simpan Halaman
print-page = Cetak Halaman
mute-current-tab = Bisukan Tab Saat Ini
show-source-of-page = Tampilkan Sumber Halaman
show-page-info = Tampilkan Info Halaman
zoom-in = Perbesar
zoom-out = Perkecil
reset-zoom = Reset Perbesaran
back = Kembali
forward = Maju
stop = Berhenti
reload = Muat Ulang
force-reload = Muat Ulang Paksa
search-in-this-page = Cari di Halaman Ini
show-next-search-result = Tampilkan Hasil Pencarian Berikutnya
show-previous-search-result = Tampilkan Hasil Pencarian Sebelumnya
search-the-web = Cari di Web
open-migration-wizard = Buka Panduan Migrasi
quit-from-application = Keluar dari Aplikasi
enter-into-customize-mode = Masuk ke Mode Kustomisasi
enter-into-offline-mode = Masuk ke Mode Luring
open-screen-capture = Buka Tangkap Layar
bookmark-this-page = Tambahkan Halaman Ini ke Bookmark
open-bookmark-add-tool = Buka Alat Tambah Bookmark
open-bookmarks-manager = Buka Pengelola Bookmark
toggle-bookmark-toolbar = Aktifkan/Sembunyikan Toolbar Bookmark
open-general-preferences = Buka Preferensi Umum
open-privacy-preferences = Buka Preferensi Privasi
open-workspaces-preferences = Buka Preferensi Ruang Kerja
open-containers-preferences = Buka Preferensi Kontainer
open-search-preferences = Buka Preferensi Pencarian
open-sync-preferences = Buka Preferensi Sinkronisasi
open-task-manager = Buka Pengelola Tugas
open-addons-manager = Buka Pengelola Add-on
open-home-page = Buka Halaman Utama
forget-history = Lupakan Riwayat
quick-forget-history = Cepat Lupakan Riwayat
clear-recent-history = Hapus Riwayat Terbaru
restore-last-session = Pulihkan Sesi Terakhir
search-history = Cari Riwayat
manage-history = Kelola Riwayat
open-downloads = Buka Unduhan
show-bookmark-sidebar = Tampilkan Sidebar Bookmark
show-history-sidebar = Tampilkan Sidebar Riwayat
show-synced-tabs-sidebar = Tampilkan Sidebar Tab yang Disinkronkan
reverse-sidebar = Balikkan Posisi Sidebar
hide-sidebar = Sembunyikan Sidebar
toggle-sidebar = Aktifkan/Sembunyikan Sidebar
zen-toggle-web-panels = Aktifkan/Sembunyikan Panel Web
zen-toggle-compact-mode = Aktifkan/Sembunyikan Mode Ringkas
zen-toggle-compact-mode-sidebar = Aktifkan/Sembunyikan Sidebar Mode Ringkas
zen-toggle-compact-mode-toolbar = Aktifkan/Sembunyikan Toolbar Mode Ringkas
zen-change-workspace = Ganti Ruang Kerja
zen-split-view-grid = Tampilan Terpisah Kotak
zen-split-view-vertical = Tampilan Terpisah Vertikal
zen-split-view-horizontal = Tampilan Terpisah Horizontal
zen-split-view-close = Tutup Tampilan Terpisah
zen-expand-sidebar = Aktifkan/Sembunyikan Ekspansi Sidebar
