pane-zen-looks-title = Aspect et convivialité
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Changer la langue par défaut pourrait faciliter les sites web à vous traquer.
zen-look-and-feel-colors-header = Choisissez une couleur de thème
zen-look-and-feel-colors-description = Personnalisez l'apparence et la convivialité de { -brand-short-name } selon vos préférences
zen-look-and-feel-themed-toolbar = 
    .label = Appliquez la couleur d'accentuation au thème de la barre d'outils
pane-zen-side-panels-title = Panneaux Web latéraux
zen-side-panels-header = Paramètres généraux pour les panneaux Web
zen-side-panels-description = Augmentez votre productivité en ayant plusieurs vues simultanément !
zen-side-panels-enabled = 
    .label = Activer les panneaux Web latéraux
zen-side-panels-close-on-blur = 
    .label = Fermer le panneau lorsqu'il perd le focus s'il n'est pas épinglé
zen-look-and-feel-compact-view-header = Afficher en vue compacte
zen-look-and-feel-compact-view-description = Affichez uniquement les barres d'outils que vous utilisez !
zen-look-and-feel-compact-view-enabled = 
    .label = Activer le mode compact de { -brand-short-name }
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Masquer également la barre d'outils supérieure en mode compact
zen-look-and-feel-buttons-header = Style des boutons
zen-look-and-feel-buttons-description = Choisissez le style des boutons que vous souhaitez voir
zen-look-and-feel-pilled-buttons = 
    .label = Boutons arrondis
pane-zen-workspaces-title = Espaces de travail
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = Espaces de travail
pane-zen-workspaces-header = Espaces de travail
zen-settings-workspaces-header = Paramètres généraux pour les espaces de travail
zen-settings-workspaces-description = Avec les espaces de travail, vous pouvez avoir plusieurs sessions de navigation en même temps !
zen-settings-workspaces-enabled = 
    .label = Activer les espaces de travail (expérimental)
pane-zen-theme-title = Paramètres du thème
zen-vertical-tabs-title = Disposition de la barre latérale et des onglets
zen-vertical-tabs-header = Onglets verticaux
zen-vertical-tabs-description = Gérez vos onglets dans une disposition verticale
zen-vertical-tabs-show-expand-button = 
    .label = Afficher le bouton d'extension
zen-vertical-tabs-expand-tabs-by-default = Développer les onglets par défaut
zen-vertical-tabs-dont-expand-tabs-by-default = Ne pas développer les onglets par défaut
zen-vertical-tabs-expand-tabs-on-hover = Développer les onglets au survol (ne fonctionnera pas en mode compact)
zen-vertical-tabs-expand-tabs-header = Comment développer les onglets
zen-vertical-tabs-expand-tabs-description = Choisissez comment développer les onglets dans la barre latérale
zen-theme-marketplace-header = Boutique de thèmes
zen-theme-marketplace-description = Trouvez et installez des thèmes depuis la boutique.
zen-theme-marketplace-remove-button = 
    .label = Supprimer le thème
zen-theme-marketplace-link = Visitez la boutique
pane-zen-CKS-title = Raccourcis clavier
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = Raccourcis clavier { -brand-short-name }
zen-settings-CKS-header = Personnalisez vos raccourcis clavier
zen-settings-CKS-description = Modifiez les raccourcis clavier par défaut selon vos préférences et améliorez votre expérience de navigation
zen-settings-CKS-disable-firefox = 
    .label = Désactiver les raccourcis clavier par défaut de { -brand-short-name }
zen-cks-group-tab-action = Actions des onglets
zen-cks-group-page-action = Actions de la page
zen-cks-group-visible-action = Actions visibles
zen-cks-group-history-action = Actions liées à l'historique
zen-cks-group-search-action = Actions de recherche
zen-cks-group-tools-action = Actions des outils
zen-cks-group-bookmark-action = Actions de signets
zen-cks-group-open-page-action = Actions pour ouvrir la page
zen-cks-group-downloads-action = Actions de téléchargement
zen-cks-group-sidebar-action = Actions de la barre latérale
zen-cks-group-compact-mode-action = Actions du mode compact
zen-cks-group-split-view-action = Actions de la vue fractionnée
zen-cks-group-workspace-action = Actions des espaces de travail
open-new-tab = Ouvrir un nouvel onglet
close-tab = Fermer l'onglet
open-new-window = Ouvrir une nouvelle fenêtre
open-new-private-window = Ouvrir une nouvelle fenêtre privée
close-window = Fermer la fenêtre
restore-last-tab = Rouvrir le dernier onglet
restore-last-window = Rouvrir la dernière fenêtre
show-next-tab = Afficher l'onglet suivant
show-previous-tab = Afficher l'onglet précédent
show-all-tabs-panel = Afficher le panneau de tous les onglets
send-with-mail = Envoyer la page par e-mail
save-page = Enregistrer la page
print-page = Imprimer la page
mute-current-tab = Mettre l'onglet actuel en sourdine
show-source-of-page = Afficher le code source de la page
show-page-info = Afficher les informations de la page
zoom-in = Zoom avant
zoom-out = Zoom arrière
reset-zoom = Réinitialiser le zoom
back = Revenir en arrière
forward = Avancer
stop = Arrêter
reload = Recharger
force-reload = Forcer le rechargement
search-in-this-page = Rechercher dans cette page
show-next-search-result = Afficher le résultat de la recherche suivante
show-previous-search-result = Afficher le résultat de la recherche précédente
search-the-web = Rechercher sur le Web
open-migration-wizard = Assistant de migration ouverte
quit-from-application = Quitter l'application
enter-into-customize-mode = Passer en mode personnalisation
enter-into-offline-mode = Passer en mode hors-ligne
open-screen-capture = Ouvrir la capture d'écran
bookmark-this-page = Ajouter cette page aux favoris
open-bookmark-add-tool = Ouvrir l'outil d'ajout de signets
open-bookmarks-manager = Ouvrir le gestionnaire de signets
toggle-bookmark-toolbar = Activer/désactiver La barre de signets
open-general-preferences = Ouvrir les préférences générales
open-privacy-preferences = Ouvrir les préférences de confidentialité
open-workspaces-preferences = Ouvrir les préférences des espaces de travail
open-containers-preferences = Ouvrir les préférences des conteneurs
open-search-preferences = Ouvrir les préférences de recherche
open-sync-preferences = Ouvrir les préférences de synchronisation
open-task-manager = Ouvrir le gestionnaire de tâches
open-addons-manager = Ouvrir le gestionnaire des modules complémentaires
open-home-page = Ouvrir la page d'accueil
forget-history = Oublier l'historique
quick-forget-history = Historique de l'oubli rapide
clear-recent-history = Effacer l'historique récent
restore-last-session = Restaurer la dernière session
search-history = Rechercher dans l'historique
manage-history = Gérer l'historique
open-downloads = Ouvrir les téléchargements
show-bookmark-sidebar = Afficher la barre latérale des favoris
show-history-sidebar = Afficher la barre latérale de l'historique
show-synced-tabs-sidebar = Afficher la barre latérale des onglets synchronisés
reverse-sidebar = Inverser la position de la barre latérale
hide-sidebar = Masquer la barre latérale
toggle-sidebar = Activer/désactiver La barre latérale
zen-toggle-web-panels = Activer/désactiver Les panneaux Web
zen-toggle-compact-mode = Activer/désactiver Le mode compact
zen-toggle-compact-mode-sidebar = Activer/désactiver La barre latérale du mode compact
zen-toggle-compact-mode-toolbar = Basculer la barre d'outils en mode compact
zen-change-workspace = Parcourir les espaces de travail
zen-split-view-grid = Vue fractionnée en grille
zen-split-view-vertical = Vue fractionnée verticale
zen-split-view-horizontal = Vue fractionnée horizontale
zen-split-view-close = Fermer la vue fractionnaire
