pane-zen-looks-title = Aspect et convivialité
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Changer la langue par défaut pourrait faciliter les sites web à vous traquer.
zen-look-and-feel-colors-header = Choisissez une couleur de thème
zen-look-and-feel-colors-description = Personnalisez l'apparence et la convivialité de { -brand-short-name } selon vos préférences
zen-look-and-feel-themed-toolbar = 
    .label = Appliquez la couleur d'accentuation au thème de la barre d'outils
pane-zen-side-panels-title = Panneaux Web latéraux
zen-side-panels-header = Paramètres généraux pour les panneaux Web
zen-side-panels-description = Augmentez votre productivité en ayant plusieurs vues simultanément !
zen-side-panels-enabled = 
    .label = Activer les panneaux Web latéraux
zen-side-panels-close-on-blur = 
    .label = Fermer le panneau lorsqu'il perd le focus s'il n'est pas épinglé
zen-look-and-feel-compact-view-header = Afficher en vue compacte
zen-look-and-feel-compact-view-description = Affichez uniquement les barres d'outils que vous utilisez !
zen-look-and-feel-compact-view-enabled = 
    .label = Activer le mode compact de { -brand-short-name }
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Masquer également la barre d'outils supérieure en mode compact
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Rendre visible brièvement la fenêtre pop-up de la barre d'outils lors d'un changement ou de l'ouverture de nouveaux onglets en mode compact
zen-look-and-feel-buttons-header = Style des boutons
zen-look-and-feel-buttons-description = Choisissez le style des boutons que vous souhaitez voir
zen-look-and-feel-pilled-buttons = 
    .label = Boutons arrondis
pane-zen-workspaces-title = Espaces de travail
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = Espaces de travail
pane-zen-workspaces-header = Espaces de travail
zen-settings-workspaces-header = Paramètres généraux pour les espaces de travail
zen-settings-workspaces-description = Avec les espaces de travail, vous pouvez avoir plusieurs sessions de navigation en même temps !
zen-settings-workspaces-enabled = 
    .label = Activer les espaces de travail (expérimental)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Masquer l'indicateur de conteneur par défaut dans la barre d'onglets
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Permettre à tous les espaces de travail d'avoir leurs propres onglets épinglés
pane-zen-theme-title = Paramètres du thème
zen-vertical-tabs-title = Disposition de la barre latérale et des onglets
zen-vertical-tabs-header = Onglets verticaux
zen-vertical-tabs-description = Gérez vos onglets dans une disposition verticale
zen-vertical-tabs-show-expand-button = 
    .label = Afficher le bouton d'extension
zen-vertical-tabs-expand-tabs-by-default = Développer les onglets par défaut
zen-vertical-tabs-dont-expand-tabs-by-default = Ne pas développer les onglets par défaut
zen-vertical-tabs-expand-tabs-on-hover = Développer les onglets au survol (ne fonctionnera pas en mode compact)
zen-vertical-tabs-expand-tabs-header = Comment développer les onglets
zen-vertical-tabs-expand-tabs-description = Choisissez comment développer les onglets dans la barre latérale
zen-theme-marketplace-header = Zen Mods
zen-theme-marketplace-description = Trouvez et installez des thèmes depuis la boutique.
zen-theme-marketplace-remove-button = 
    .label = Supprimer le thème
zen-theme-marketplace-check-for-updates-button = 
    .label = Vérifier les mises à jour
zen-theme-marketplace-updates-success = Thème mis à jour avec succès
zen-theme-marketplace-updates-fail = Aucune mise à jour trouvée !
zen-theme-marketplace-toggle-enabled-button = 
    .title = Désactiver le thème
zen-theme-marketplace-toggle-disabled-button = 
    .title = Activer le thème
zen-theme-marketplace-remove-confirmation = Êtes-vous sûr de vouloir désactiver ce mod ?
zen-theme-marketplace-close-modal = Fermer
zen-theme-marketplace-theme-header-title = 
    .title = CSS Selector: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = None
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Type something...
pane-zen-marketplace-title = Zen Mods
zen-settings-workspaces-display-as-icon-strip = 
    .label = Display workspaces as an icon strip
zen-theme-marketplace-link = Visitez la boutique
zen-dark-theme-styles-header = Styles de thème sombre
zen-dark-theme-styles-description = Personnaliser le thème sombre selon vos goûts
zen-dark-theme-styles-amoled = Thème Nuit
zen-dark-theme-styles-default = Thème sombre par défaut
zen-dark-theme-styles-colorful = Thème sombre coloré
zen-compact-mode-styles-left = Hide Tab bar
zen-compact-mode-styles-top = Hide Top bar
zen-compact-mode-styles-both = Hide Both
pane-zen-CKS-title = Raccourcis clavier
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = Raccourcis clavier { -brand-short-name }
zen-settings-CKS-header = Personnalisez vos raccourcis clavier
zen-settings-CKS-description = Modifiez les raccourcis clavier par défaut selon vos préférences et améliorez votre expérience de navigation
zen-settings-CKS-disable-firefox = 
    .label = Désactiver les raccourcis clavier par défaut de { -brand-short-name }
zen-settings-CKS-duplicate-shortcut = 
    .label = Duplicate Shortcut
zenCKSOption-group-other = Other
zenCKSOption-group-windowAndTabManagement = Window & Tab Management
zenCKSOption-group-navigation = Navigation
zenCKSOption-group-searchAndFind = Search & Find
zenCKSOption-group-pageOperations = Page Operations
zenCKSOption-group-historyAndBookmarks = History & Bookmarks
zenCKSOption-group-mediaAndDisplay = Media & Display
zenCKSOption-group-zen-compact-mode = Compact Mode
zenCKSOption-group-zen-workspace = Workspaces
zenCKSOption-group-zen-other = Other Zen Features
zenCKSOption-group-zen-split-view = Split View
zen-key-quick-restart = Quick Restart
zen-window-new-shortcut = New Window
zen-tab-new-shortcut = New Tab
zen-location-open-shortcut = Open Location
zen-location-open-shortcut-alt = Open Location (Alt)
zen-search-focus-shortcut = Focus Search
zen-search-focus-shortcut-alt = Focus Search (Alt)
zen-downloads-shortcut = Open Downloads
zen-addons-shortcut = Open Add-ons
zen-file-open-shortcut = Open File
zen-save-page-shortcut = Save Page
zen-print-shortcut = Print Page
zen-close-shortcut-2 = Close Tab
zen-mute-toggle-shortcut = Toggle Mute
zen-key-delete = Delete Key
zen-key-go-back = Go Back
zen-key-go-forward = Go Forward
zen-nav-back-shortcut-alt = Navigate Back (Alt)
zen-nav-fwd-shortcut-alt = Navigate Forward (Alt)
zen-history-show-all-shortcut = Show All History
zen-key-enter-full-screen = Enter Full Screen
zen-key-exit-full-screen = Exit Full Screen
zen-reader-mode-toggle-shortcut-other = Toggle Reader Mode
zen-picture-in-picture-toggle-shortcut = Toggle Picture-in-Picture
zen-nav-reload-shortcut-2 = Reload Page
zen-key-about-processes = About Processes
zen-page-source-shortcut = View Page Source
zen-page-info-shortcut = View Page Info
zen-find-shortcut = Find on Page
zen-search-find-again-shortcut = Find Again
zen-search-find-again-shortcut-prev = Find Previous
zen-search-find-again-shortcut-2 = Find Again (Alt)
zen-bookmark-this-page-shortcut = Bookmark This Page
zen-bookmark-show-library-shortcut = Show Bookmarks Library
zen-key-stop = Stop Loading
zen-full-zoom-reduce-shortcut = Zoom Out
zen-full-zoom-enlarge-shortcut = Zoom In
zen-full-zoom-reset-shortcut = Reset Zoom
zen-bidi-switch-direction-shortcut = Switch Text Direction
zen-private-browsing-shortcut = Private Browsing
zen-screenshot-shortcut = Take Screenshot
zen-key-sanitize = Clear Browsing Data
zen-quit-app-shortcut = Quit Application
zen-key-wr-capture-cmd = WR Capture Command
zen-key-wr-toggle-capture-sequence-cmd = Toggle WR Capture Sequence
zen-nav-reload-shortcut = Reload Page
zen-nav-reload-shortcut-skip-cache = Reload Page (Skip Cache)
zen-close-shortcut = Close Window
zen-close-tab-shortcut = Close Tab
zen-compact-mode-shortcut-show-sidebar = Toggle Floating Sidebar
zen-compact-mode-shortcut-show-toolbar = Toggle Floating Toolbar
zen-compact-mode-shortcut-toggle = Toggle Compact Mode
zen-workspace-shortcut-switch-1 = Switch to Workspace 1
zen-workspace-shortcut-switch-2 = Switch to Workspace 2
zen-workspace-shortcut-switch-3 = Switch to Workspace 3
zen-workspace-shortcut-switch-4 = Switch to Workspace 4
zen-workspace-shortcut-switch-5 = Switch to Workspace 5
zen-workspace-shortcut-switch-6 = Switch to Workspace 6
zen-workspace-shortcut-switch-7 = Switch to Workspace 7
zen-workspace-shortcut-switch-8 = Switch to Workspace 8
zen-workspace-shortcut-switch-9 = Switch to Workspace 9
zen-workspace-shortcut-switch-10 = Switch to Workspace 10
zen-workspace-shortcut-forward = Forward Workspace
zen-workspace-shortcut-backward = Backward Workspace
zen-web-panel-shortcut-toggle = Toggle Web Panel
zen-sidebar-shortcut-toggle = Toggle Sidebar's Width
zen-split-view-shortcut-grid = Toggle Split View Grid
zen-split-view-shortcut-vertical = Toggle Split View Vertical
zen-split-view-shortcut-horizontal = Toggle Split View Horizontal
zen-split-view-shortcut-unsplit = Close Split View
