pane-zen-looks-title = Aspect et convivialité
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Changer la langue par défaut pourrait faciliter les sites web à vous traquer.
zen-look-and-feel-colors-header = Choisissez une couleur de thème
zen-look-and-feel-colors-description = Personnalisez l'apparence et la convivialité de { -brand-short-name } selon vos préférences
zen-look-and-feel-themed-toolbar = 
    .label = Appliquez la couleur d'accentuation au thème de la barre d'outils
pane-zen-side-panels-title = Panneaux Web latéraux
zen-side-panels-header = Paramètres généraux pour les panneaux Web
zen-side-panels-description = Augmentez votre productivité en ayant plusieurs vues simultanément !
zen-side-panels-enabled = 
    .label = Activer les panneaux Web latéraux
zen-side-panels-close-on-blur = 
    .label = Fermer le panneau lorsqu'il perd le focus s'il n'est pas épinglé
zen-vertical-tabs-show-bottom-border = 
    .label = Show border for the bottom icons
sync-currently-syncing-workspaces = Workspaces
sync-engine-workspaces = 
    .label = Workspaces
    .tooltiptext = Sync your workspaces across devices
    .accesskey = W
zen-look-and-feel-compact-view-header = Afficher en vue compacte
zen-look-and-feel-compact-view-description = Affichez uniquement les barres d'outils que vous utilisez !
zen-look-and-feel-compact-view-enabled = 
    .label = Activer le mode compact de { -brand-short-name }
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Masquer également la barre d'outils supérieure en mode compact
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Rendre visible brièvement la fenêtre pop-up de la barre d'outils lors d'un changement ou de l'ouverture de nouveaux onglets en mode compact
zen-look-and-feel-buttons-header = Style des boutons
zen-look-and-feel-buttons-description = Choisissez le style des boutons que vous souhaitez voir
zen-look-and-feel-pilled-buttons = 
    .label = Boutons arrondis
pane-zen-tabs-title = Gestion d'onglet
category-zen-workspaces = 
    .tooltiptext = { pane-zen-tabs-title }
pane-settings-workspaces-title = Espaces de travail
pane-zen-tabs-unloader-title = Déchargeur d'onglet
zen-tabs-unloader-header = Paramètres généraux pour le déchargeur d'onglet
zen-tabs-unloader-description = Décharger automatiquement les onglets non utilisés pour économiser de la mémoire
zen-tabs-unloader-enabled = 
    .label = Autoriser le déchargeur d'onglet
zen-tabs-unloader-unload-delay = 
    .label = Décharger les onglets après
zen-tabs-unloader-unload-delay-description = La durée en minutes après laquelle un onglet est déchargé
pane-zen-pinned-tab-manager-title = Pinned Tabs
zen-pinned-tab-manager-header = General settings for pinned tabs
zen-pinned-tab-manager-description = Manage additional behavior of pinned tabs
zen-pinned-tab-manager-restore-pinned-tabs-to-pinned-url = 
    .label = Restore pinned tabs to their originally pinned URL on startup
zen-pinned-tab-manager-close-shortcut-behavior-label = Close Tab Shortcut Behavior
zen-pinned-tab-manager-reset-unload-switch-close-shortcut-option = 
    .label = Reset URL, unload and switch to next tab
zen-pinned-tab-manager-unload-switch-close-shortcut-option = 
    .label = Unload and switch to next tab
zen-pinned-tab-manager-reset-switch-close-shortcut-option = 
    .label = Reset URL and switch to next tab
zen-pinned-tab-manager-switch-close-shortcut-option = 
    .label = Switch to next tab
zen-pinned-tab-manager-reset-close-shortcut-option = 
    .label = Reset URL
zen-pinned-tab-manager-close-close-shortcut-option = 
    .label = Close tab
pane-zen-workspaces-header = Espaces de travail
zen-settings-workspaces-header = Paramètres généraux pour les espaces de travail
zen-settings-workspaces-description = Avec les espaces de travail, vous pouvez avoir plusieurs sessions de navigation en même temps !
zen-settings-workspaces-enabled = 
    .label = Activer les espaces de travail (expérimental)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Masquer l'indicateur de conteneur par défaut dans la barre d'onglets
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Permettre à tous les espaces de travail d'avoir leurs propres onglets épinglés
zen-key-unsafed = Unsaved shortcut! Please safe it by clicking the "Escape" key after retyping it.
zen-key-conflict = Conflit avec un autre raccourcie
pane-zen-theme-title = Paramètres du thème
zen-vertical-tabs-title = Disposition de la barre latérale et des onglets
zen-vertical-tabs-header = Onglets verticaux
zen-vertical-tabs-description = Gérez vos onglets dans une disposition verticale
zen-vertical-tabs-show-expand-button = 
    .label = Afficher le bouton d'extension
zen-vertical-tabs-expand-tabs-by-default = Développer les onglets par défaut
zen-vertical-tabs-dont-expand-tabs-by-default = Ne pas développer les onglets par défaut
zen-vertical-tabs-expand-tabs-on-hover = Développer les onglets au survol (ne fonctionnera pas en mode compact)
zen-vertical-tabs-expand-tabs-header = Comment développer les onglets
zen-vertical-tabs-expand-tabs-description = Choisissez comment développer les onglets dans la barre latérale
zen-theme-marketplace-header = Mods de Zen
zen-theme-marketplace-description = Trouvez et installez des thèmes depuis la boutique.
zen-theme-marketplace-remove-button = 
    .label = Supprimer le thème
zen-theme-marketplace-check-for-updates-button = 
    .label = Vérifier les mises à jour
zen-theme-marketplace-updates-success = Thème mis à jour avec succès
zen-theme-marketplace-updates-fail = Aucune mise à jour trouvée !
zen-theme-marketplace-toggle-enabled-button = 
    .title = Désactiver le thème
zen-theme-marketplace-toggle-disabled-button = 
    .title = Activer le thème
zen-theme-marketplace-remove-confirmation = Êtes-vous sûr de vouloir désactiver ce mod ?
zen-theme-marketplace-close-modal = Fermer
zen-theme-marketplace-theme-header-title = 
    .title = CSS Selecteur: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = Aucun
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Tapez quelque chose...
pane-zen-marketplace-title = Mods de Zen
zen-settings-workspaces-display-as-icon-strip = 
    .label = Afficher l'espace de travail sous forme d'une bande d'icônes
zen-theme-marketplace-link = Visitez la boutique
zen-dark-theme-styles-header = Styles de thème sombre
zen-dark-theme-styles-description = Personnaliser le thème sombre selon vos goûts
zen-dark-theme-styles-amoled = Thème Nuit
zen-dark-theme-styles-default = Thème sombre par défaut
zen-dark-theme-styles-colorful = Thème sombre coloré
zen-split-view-title = Vue fractionnée
zen-split-view-header = Fonctionnalité de la vue fractionnée
zen-split-view-description = Fractionner votre navigateur en plusieurs vues pour parcourir plusieurs sites web à la fois
zen-split-view-change-on-hover = 
    .label = Changer d'onglet au survol
zen-compact-mode-styles-left = Cacher la barre des onglets
zen-compact-mode-styles-top = Cacher la barre supérieure
zen-compact-mode-styles-both = Cacher les deux barres
pane-zen-CKS-title = Raccourcis clavier
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = Raccourcis clavier { -brand-short-name }
zen-settings-CKS-header = Personnalisez vos raccourcis clavier
zen-settings-CKS-description = Modifiez les raccourcis clavier par défaut selon vos préférences et améliorez votre expérience de navigation
zen-settings-CKS-disable-firefox = 
    .label = Désactiver les raccourcis clavier par défaut de { -brand-short-name }
zen-settings-CKS-duplicate-shortcut = 
    .label = Copier le raccourci
zen-settings-CKS-reset-shortcuts = 
    .label = Réinitialiser les paramètres par défaut
zenCKSOption-group-other = Autre
zenCKSOption-group-windowAndTabManagement = Gestion de la fenêtre et des onglets
zenCKSOption-group-navigation = Navigation
zenCKSOption-group-searchAndFind = Rechercher et Trouver
zenCKSOption-group-pageOperations = Opérations de page
zenCKSOption-group-historyAndBookmarks = Historique et Favoris
zenCKSOption-group-mediaAndDisplay = Affichage et Média
zenCKSOption-group-zen-compact-mode = Mode compacte
zenCKSOption-group-zen-workspace = Espace de travail
zenCKSOption-group-zen-other = Autres fonctionnalités de Zen
zenCKSOption-group-zen-split-view = Vue fractionnée
zen-key-quick-restart = Redémarrage rapide
zen-window-new-shortcut = Nouvelle fenêtre
zen-tab-new-shortcut = Nouvel onglet
zen-key-redo = refaire
zen-restore-last-closed-tab-shortcut = Restaurer le dernier onglet fermé
zen-location-open-shortcut = Ouvrir la localisation
zen-location-open-shortcut-alt = Ouvrir la localisation (Alt)
zen-key-undo-close-window = Annuler la fermeture de la fenêtre
zen-text-action-undo-shortcut = Annuler
zen-text-action-redo-shortcut = Refaire
zen-text-action-cut-shortcut = Couper
zen-text-action-copy-shortcut = Copier
zen-text-action-paste-shortcut = Coller
zen-text-action-select-all-shortcut = Tout sélectionner
zen-text-action-delete-shortcut = Supprimer
zen-history-show-all-shortcut-mac = Afficher tout l'historique (Mac)
zen-full-screen-shortcut = Basculer en mode plein écran
zen-reader-mode-toggle-shortcut-windows = Basculer en mode fenêtré
zen-picture-in-picture-toggle-shortcut-alt = Basculer en incrustation d'image (Alt)
zen-picture-in-picture-toggle-shortcut-mac = Basculer en incrustation d'image (Mac)
zen-picture-in-picture-toggle-shortcut-mac-alt = Basculer en incrustation d'image (Mac Alt)
zen-page-source-shortcut-safari = Afficher la source de la page (Safari)
zen-nav-stop-shortcut = Arrêter le chargement
zen-history-sidebar-shortcut = Afficher la barre latérale d'historique
zen-window-minimize-shortcut = Minimiser la fenêtre
zen-help-shortcut = Ouvrir l'aide
zen-preferences-shortcut = Ouvrir les préférences
zen-hide-app-shortcut = Cacher l'application
zen-hide-other-apps-shortcut = Cacher les autres applications
zen-search-focus-shortcut = Focus Search
zen-search-focus-shortcut-alt = Focus Search (Alt)
zen-downloads-shortcut = Ouvrir les téléchargements
zen-addons-shortcut = Ouvrir les extensions
zen-file-open-shortcut = Ouvrir un fichier
zen-save-page-shortcut = Sauvegarder la page
zen-print-shortcut = Imprimer la page
zen-close-shortcut-2 = Fermer l'onglet
zen-mute-toggle-shortcut = Basculer en mode muet
zen-key-delete = Touche supprimer
zen-key-go-back = Retour
zen-key-go-forward = Avancer
zen-nav-back-shortcut-alt = Naviguer en arrière
zen-nav-fwd-shortcut-alt = Naviguer en avant
zen-history-show-all-shortcut = Afficher tout l'historique
zen-key-enter-full-screen = Afficher en plein écran
zen-key-exit-full-screen = Quitter le plein écran
zen-reader-mode-toggle-shortcut-other = Basculer en mode lecture
zen-picture-in-picture-toggle-shortcut = Basculer en mode incrustation d'image
zen-nav-reload-shortcut-2 = Recharger la page
zen-key-about-processes = A propos des processus
zen-page-source-shortcut = Afficher la source de la page
zen-page-info-shortcut = Afficher les informations de la page
zen-find-shortcut = Rechercher sur la page
zen-search-find-again-shortcut = Rechercher à nouveau
zen-search-find-again-shortcut-prev = Recherche précédente
zen-search-find-again-shortcut-2 = Rechercher à nouveau (Alt)
zen-bookmark-this-page-shortcut = Mettre cette page en favoris
zen-bookmark-show-library-shortcut = Afficher la bibliothèque des favoris
zen-key-stop = Arrêter le chargement
zen-full-zoom-reduce-shortcut = Dézoomer
zen-full-zoom-enlarge-shortcut = Zoomer
zen-full-zoom-reset-shortcut = Redémarrer le zoom
zen-bidi-switch-direction-shortcut = Changer la direction du texte
zen-private-browsing-shortcut = Navigation privée
zen-screenshot-shortcut = Prendre une capture d'écran
zen-key-sanitize = Vider les données de recherches
zen-quit-app-shortcut = Quit Application
zen-key-wr-capture-cmd = Commande de capture de rendu web
zen-key-wr-toggle-capture-sequence-cmd = Basculer en mode de capture de rendu web
zen-nav-reload-shortcut = Recharger la page
zen-nav-reload-shortcut-skip-cache = Recharger la page (ignorer le cache)
zen-close-shortcut = Fermer la fenêtre
zen-close-tab-shortcut = Fermer l'onglet
zen-compact-mode-shortcut-show-sidebar = Toggle Floating Sidebar
zen-compact-mode-shortcut-show-toolbar = Toggle Floating Toolbar
zen-compact-mode-shortcut-toggle = Toggle Compact Mode
zen-workspace-shortcut-switch-1 = Passer à l'espace de travail 1
zen-workspace-shortcut-switch-2 = Passer à l'espace de travail 2
zen-workspace-shortcut-switch-3 = Passer à l'espace de travail 3
zen-workspace-shortcut-switch-4 = Passer à l'espace de travail 4
zen-workspace-shortcut-switch-5 = Passer à l'espace de travail 5
zen-workspace-shortcut-switch-6 = Passer à l'espace de travail 6
zen-workspace-shortcut-switch-7 = Passer à l'espace de travail 7
zen-workspace-shortcut-switch-8 = Passer à l'espace de travail 8
zen-workspace-shortcut-switch-9 = Passer à l'espace de travail 9
zen-workspace-shortcut-switch-10 = Passer à l'espace de travail 10
zen-workspace-shortcut-forward = Espace de travail suivant
zen-workspace-shortcut-backward = Espace de travail précédent
zen-web-panel-shortcut-toggle = Basculer le panneau web
zen-sidebar-shortcut-toggle = Toggle Sidebar's Width
zen-pinned-tab-shortcut-reset = Reset Pinned Tab to Pinned URL
zen-split-view-shortcut-grid = Toggle Split View Grid
zen-split-view-shortcut-vertical = Toggle Split View Vertical
zen-split-view-shortcut-horizontal = Toggle Split View Horizontal
zen-split-view-shortcut-unsplit = Fermer la vue fractionner
zen-key-select-tab-1 = Sélectionner l'onglet #1
zen-key-select-tab-2 = Sélectionner l'onglet #2
zen-key-select-tab-3 = Sélectionner l'onglet #3
zen-key-select-tab-4 = Sélectionner l'onglet #4
zen-key-select-tab-5 = Sélectionner l'onglet #5
zen-key-select-tab-6 = Sélectionner l'onglet #6
zen-key-select-tab-7 = Sélectionner l'onglet #7
zen-key-select-tab-8 = Sélectionner l'onglet #8
zen-key-select-tab-last = Sélectionner le dernier onglet
zen-key-show-all-tabs = Afficher tous les onglets
zen-key-goto-history = Aller à l'historique
zen-key-go-home = Aller à la page d'accueil
zen-bookmark-show-sidebar-shortcut = Afficher la barre latérale des favoris
zen-bookmark-show-toolbar-shortcut = Afficher la barre d'outils des favoris
