zen-toolbar-context-tabs-right = 
    .label = Schede a destra
    .accesskey = R
zen-toolbar-context-compact-mode = 
    .label = Modalità compatta
    .accesskey = C
zen-toolbar-context-compact-mode-enable = 
    .label = Abilita modalità compatta
    .accesskey = D
zen-toolbar-context-compact-mode-just-tabs = 
    .label = Hide sidebar
zen-toolbar-context-compact-mode-just-toolbar = 
    .label = Nascondi barra strumenti
zen-toolbar-context-compact-mode-hide-both = 
    .label = Nascondi entrambi
    .accesskey = H
sidebar-zen-sidepanel = 
    .label = Pannelli Laterali
sidebar-zen-expand = 
    .label = Expand Sidebar
