zen-web-side-panel-context-mute-panel = 
    .label = Silenzia Pannello Web
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = Attiva l'audio del Pannello Web
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = Disattiva l'UserAgent mobile
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Attiva l'UserAgent mobile
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = Chiudi Pannello Web
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = Elimina Pannello Web
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = Apri in Nuova Scheda
    .accesskey = N
zen-web-side-panel-context-add-to-panel = 
    .label = Aggiungi ai Pannelli Web
    .accesskey = A
zen-sidebar-introduction-title = Benvenutə sulla Barra Laterale di Zen
zen-sidebar-introduction-description = La Barra Laterale di Zen è un nuovo modo di navigare il web. Clicca un'icona per aprirne uno.
