zen-panel-ui-workspaces-text = Workspace
zen-panel-ui-workspaces-create = 
    .label = Crea Spazio
zen-workspaces-panel-context-delete = 
    .label = Elimina lo spazio di lavoro
    .accesskey = D
zen-workspaces-panel-change-name = 
    .label = Cambia Nome
zen-workspaces-panel-change-icon = 
    .label = Cambia Icona
zen-workspaces-panel-context-default-profile = 
    .label = Set Profile
zen-workspaces-how-to-reorder-title = How to reorder spaces
zen-workspaces-how-to-reorder-desc = Drag the space icons at the bottom of the sidebar to reorder them
zen-workspaces-change-theme = 
    .label = Modifica Tema
zen-workspaces-panel-context-open = 
    .label = Apri Workspace
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Imposta Come Workspace Predefinito
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Modifica Workspace
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Metti scheda/e su uno spazio di lavoro
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Spazi di lavoro
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Complementare
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Dividi
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Analogo
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Triadico
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Fluttuante
zen-panel-ui-gradient-click-to-add = Clicca per aggiungere un colore
zen-workspace-creation-name = 
    .placeholder = Nome dello Spazio
zen-workspaces-panel-context-reorder = 
    .label = Riordina i Workspace
zen-workspace-creation-profile = Profilo
    .tooltiptext = I profili vengono usati per separare i cookie e i dati dei siti tra gli spazi.
zen-workspace-creation-header = Create a Space
zen-workspace-creation-label = Gli Spazi sono usati per organizzare le tue schede e sessioni.
