zen-web-side-panel-context-mute-panel = 
    .label = Silenzia pannello web
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = Attiva l'audio del pannello web
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = Disattiva l'User Agent mobile
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Attiva l'User Agent mobile
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = Chiudi pannello web
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = Elimina pannello web
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = Apri in nuova scheda
    .accesskey = N
zen-web-side-panel-context-add-to-panel = 
    .label = Aggiungi ai pannelli web
    .accesskey = A
zen-sidebar-introduction-title = Benvenuto sulla Barra Laterale di Zen
zen-sidebar-introduction-description = La Barra Laterale di Zen è un nuovo modo di navigare il web. Clicca su un'icona qualsiasi per aprirne un pannello.
