zen-toolbar-context-tabs-right = 
    .label = Tabs on the right
    .accesskey = R
zen-toolbar-context-compact-mode = 
    .label = Modalità Compatta
    .accesskey = C
zen-toolbar-context-compact-mode-enable = 
    .label = Abilita la modalità compatta
    .accesskey = D
zen-toolbar-context-compact-mode-just-tabs = 
    .label = Nascondi la Barra laterale
zen-toolbar-context-compact-mode-just-toolbar = 
    .label = Nascondi la barra degli strumenti
zen-toolbar-context-compact-mode-hide-both = 
    .label = Nascondi entrambe
    .accesskey = H
sidebar-zen-sidepanel = 
    .label = Pannelli laterali
sidebar-zen-expand = 
    .label = Espandi la barra laterale
