zen-web-side-panel-context-mute-panel = 
    .label = Silenzia pannello web
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = Riattiva Pannello Web
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = Disabilita Mobile UserAgent
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Abilita Mobile UserAgent
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = Scarica Pannello Web
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = Elimina pannello web
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = Apri in una nuova scheda
    .accesskey = N
zen-web-side-panel-context-open-in-container-tab = 
    .label = Apri nella scheda Contenitore
    .accesskey = C
zen-web-side-panel-context-add-to-panel = 
    .label = Aggiungi ai pannelli web
    .accesskey = A
zen-sidebar-introduction-title = Benvenuto nella barra laterale Zen
zen-sidebar-introduction-description = Zen Sidebar è un nuovo modo per navigare sul web. Fare clic su una qualsiasi delle icone per aprire un pannello web.
