zen-panel-ui-current-profile-text = profilo in uso
unified-extensions-description = Le estensioni sono usate per portare più funzionalità extra in { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = Reimposta Scheda Bloccata
    .accesskey = R
tab-context-zen-pin-tab-global = 
    .label = Add tab to essentials
    .accesskey = P
tab-context-zen-replace-pinned-url-with-current = 
    .label = Sostituisci URL fissato con quello corrente
    .accesskey = C
tab-zen-unload = 
    .label = Unload Tab
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Azioni Scaricatore Schede
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Permetti di scaricare le schede
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Consenti Scaricamento Scheda
    .accesskey = I
zen-themes-corrupted = Il tuo file { -brand-short-name } mods è danneggiato. Sono stati reimpostati al tema predefinito.
zen-panel-ui-gradient-generator-opacity-text = Contrast
zen-panel-ui-gradient-generator-texture-text = Texture
zen-panel-ui-gradient-generator-custom-color = Colore Personalizzato
zen-panel-ui-gradient-generator-saved-message = Gradiente salvato con successo!
