zen-panel-ui-workspaces-text = Workspaces
zen-panel-ui-workspaces-create-text = Crea uno spazio di lavoro
zen-panel-ui-workspaces-create-save = 
    .label = Crea uno spazio di lavoro
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = Annulla
    .accesskey = C
zen-panel-ui-workspaces-edit-text = Modifica lo spazio di lavoro
zen-panel-ui-workspaces-edit-save = 
    .label = Salva modifiche
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Annulla
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Elimina lo spazio di lavoro
    .accesskey = D
zen-workspaces-panel-context-open = 
    .label = Apri lo spazio di lavoro
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Imposta come spazio di lavoro predefinito
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Modifica lo spazio di lavoro
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Metti scheda/e su uno spazio di lavoro
    .accesskey = C
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Imposta il container default
    .accesskey = O
