zen-panel-ui-current-profile-text = profilo in uso
unified-extensions-description = Le estensioni sono usate per portare più funzionalità extra in { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = Reimposta Scheda Bloccata
    .accesskey = R
tab-context-zen-add-essential = 
    .label = Aggiungi agli Essenziali
    .accesskey = E
tab-context-zen-remove-essential = 
    .label = Rimuovi dagli Essenziali
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Sostituisci URL fissato con quello corrente
    .accesskey = C
tab-zen-unload = 
    .label = Scarica scheda
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Azioni Scaricatore Schede
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Permetti di scaricare le schede
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Consenti Scaricamento Scheda
    .accesskey = I
zen-themes-corrupted = Il tuo file { -brand-short-name } mods è danneggiato. Sono stati reimpostati al tema predefinito.
zen-shortcuts-corrupted = Your { -brand-short-name } shortcuts file is corrupted. They have been reset to the default shortcuts.
zen-panel-ui-gradient-generator-opacity-text = Contrasto
zen-panel-ui-gradient-generator-texture-text = Texture
zen-panel-ui-gradient-generator-custom-color = Colore Personalizzato
zen-panel-ui-gradient-generator-saved-message = Gradiente salvato con successo!
zen-copy-current-url-confirmation = The URL has been copied to the clipboard.
zen-rice-share-name = 
    .placeholder = Rice Name
zen-rice-share-author = By
zen-rice-share-author-input = 
    .placeholder = Your Name
zen-rice-share-cancel = Cancel
zen-rice-share-save = Share
zen-rice-share-include-userchrome = 
    .label = Include zen window styles (userChrome.css)
zen-rice-share-include-usercontent = 
    .label = Include website styles (userContent.css)
zen-rice-share-include-mods = 
    .label = Include enabled mods
zen-rice-share-include-mod-prefs = 
    .label = Include mod preferences
zen-rice-share-include-preferences = 
    .label = Include layout preferences
zen-rice-share-include-workspace-themes = 
    .label = Include workspace gradient themes
zen-rice-share-success = Successfully created a Rice!
zen-rice-share-success-link = Rice Share Link
zen-rice-share-accept = Accept
zen-rice-share-notice = Before sharing, please understand what a Rice is
# note: Do not translate the "<br/>" tags in the following string
zen-rice-share-notice-description =
    A Rice is a collection of customizations that can be shared with others.<br/>
    This includes your window styles, website styles, enabled mods, mod preferences, layout preferences, and workspace gradient themes.<br/>
    By sharing a Rice, you are sharing all of these customizations with others. Please be mindful of what you share.
zen-learn-more-text = Learn More
zen-rice-share-include = Export Options
appmenu-zen-share-rice = 
    .label = Share Zen Rice
zen-close-label = Close
