pane-zen-looks-title = Apariencia
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Cambiar el idioma por defecto puede facilitar el seguimiento de algunos sitios.
zen-look-and-feel-colors-header = Escoge un tema
zen-look-and-feel-colors-description = Hacer que { -brand-short-name } se vea como prefieras
zen-look-and-feel-themed-toolbar = 
    .label = Utilizar el color secundario para la barra de herramientas
pane-zen-side-panels-title = Paneles Laterales
zen-side-panels-header = Ajustes de los Paneles Laterales
zen-side-panels-description = ¡Incrementa tu productividad teniendo múltiples paneles a la vez!
zen-side-panels-enabled = 
    .label = Habilitar Paneles Laterales
zen-side-panels-close-on-blur = 
    .label = Cerrar el panel al desenfocar si no está fijado
zen-look-and-feel-compact-view-header = Mostrar en modo compacto
zen-look-and-feel-compact-view-description = ¡Mostrar solo las barras de herramientas que utilices!
zen-look-and-feel-compact-view-enabled = 
    .label = Habilitar modo compacto de { -brand-short-name }
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Esconder la barra de herramientas en modo compacto
zen-look-and-feel-buttons-header = Estilo de botones
zen-look-and-feel-buttons-description = Escoge el estilo de botones que quieras ver
zen-look-and-feel-pilled-buttons = 
    .label = Botones Redondeados
pane-zen-workspaces-title = Áreas de trabajo
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = Áreas de trabajo
pane-zen-workspaces-header = Áreas de trabajo
zen-settings-workspaces-header = Ajustes de las áreas de trabajo
zen-settings-workspaces-description = Con las áreas de trabajo, ¡puedes tener múltiples sesiones de navegación a la vez!
zen-settings-workspaces-enabled = 
    .label = Habilitar áreas de trabajo (Experimental)
pane-zen-theme-title = Ajustes del tema
zen-vertical-tabs-title = Disposición de la barra lateral y pestañas
zen-vertical-tabs-header = Pestañas verticales
zen-vertical-tabs-description = Mostrar las pestañas verticalmente
zen-vertical-tabs-show-expand-button = 
    .label = Mostrar el botón de expandir
zen-vertical-tabs-expand-tabs-by-default = Expandir por defecto
zen-vertical-tabs-dont-expand-tabs-by-default = No expandir por defecto
zen-vertical-tabs-expand-tabs-on-hover = Expandir al pasar el ratón sobre las pestañas (No funciona en modo compacto)
zen-vertical-tabs-expand-tabs-header = Modo de extensión
zen-vertical-tabs-expand-tabs-description = Escoge como expandir la barra de pestañas
zen-theme-marketplace-header = Tienda de Temas
zen-theme-marketplace-description = Encontrar e instalar temas de la tienda.
zen-theme-marketplace-remove-button = 
    .label = Eliminar tema
zen-theme-marketplace-link = Ir a la tienda
pane-zen-CKS-title = Atajos de teclado
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = Atajos de teclado de { -brand-short-name }
zen-settings-CKS-header = Personaliza tus atajos de teclado
zen-settings-CKS-description = Cambia los atajos de teclado por defecto a tu gusto y mejora tu experiencia de navegación
zen-settings-CKS-disable-firefox = 
    .label = Deshabilita los atajos de teclado por defecto de { -brand-short-name }
zen-cks-group-tab-action = Acciones de pestaña
zen-cks-group-page-action = Acciones de página
zen-cks-group-visible-action = Acciones visibles
zen-cks-group-history-action = Acciones de historial
zen-cks-group-search-action = Acciones de búsqueda
zen-cks-group-tools-action = Acciones de herramientas
zen-cks-group-bookmark-action = Acciones de marcadores
zen-cks-group-open-page-action = Acciones de apertura de páginas
zen-cks-group-downloads-action = Acciones de descarga
zen-cks-group-sidebar-action = Acciones de barra lateral
zen-cks-group-compact-mode-action = Acciones de modo compacto
zen-cks-group-split-view-action = Acciones de vista separada
zen-cks-group-workspace-action = Acciones de área de trabajo
open-new-tab = Abrir nueva pestaña
close-tab = Cerrar pestaña
open-new-window = Abrir nueva ventana
open-new-private-window = Abrir nueva ventana privada
close-window = Cerrar ventana
restore-last-tab = Restaurar última pestaña
restore-last-window = Restaurar última ventana
show-next-tab = Mostrar siguiente pestaña
show-previous-tab = Mostrar pestaña anterior
show-all-tabs-panel = Mostrar el panel de todas las pestañas
send-with-mail = Enviar página por correo
save-page = Guardar página
print-page = Imprimir página
mute-current-tab = Silenciar pestaña actual
show-source-of-page = Mostrar código fuente de la página
show-page-info = Mostrar información de la página
zoom-in = Acercar
zoom-out = Alejar
reset-zoom = Reiniciar zoom
back = Atrás
forward = Adelante
stop = Detener
reload = Recargar
force-reload = Forzar recarga
search-in-this-page = Buscar en esta página
show-next-search-result = Mostrar siguiente resultado de búsqueda
show-previous-search-result = Mostrar resultado anterior de búsqueda
search-the-web = Buscar en la web
open-migration-wizard = Abrir el asistente de migración
quit-from-application = Salir de la aplicación
enter-into-customize-mode = Entrar a modo personalizado
enter-into-offline-mode = Entrar en modo sin conexión
open-screen-capture = Abrir captura de pantalla
bookmark-this-page = Marcar esta página como favorita
open-bookmark-add-tool = Abrir herramienta para agregar marcadores
open-bookmarks-manager = Abrir administrador de marcadores
toggle-bookmark-toolbar = Alternar barra de herramientas de marcadores
open-general-preferences = Abrir preferencias generales
open-privacy-preferences = Abrir preferencias de privacidad
open-workspaces-preferences = Abrir preferencias de áreas de trabajo
open-containers-preferences = Abrir preferencias de contenedores
open-search-preferences = Abrir preferencias de búsqueda
open-sync-preferences = Abrir preferencias de sincronización
open-task-manager = Abrir Administrador de Tareas
open-addons-manager = Abrir administrador de extensiones
open-home-page = Abrir página de inicio
forget-history = Olvidar historial
quick-forget-history = Borrar el historial rápidamente
clear-recent-history = Limpiar historial reciente
restore-last-session = Restaurar última sesión
search-history = Historial de búsqueda
manage-history = Administrar Historial
open-downloads = Abrir Descargas
show-bookmark-sidebar = Mostrar barra lateral de favoritos
show-history-sidebar = Mostrar barra lateral del historial
show-synced-tabs-sidebar = Mostrar pestañas sincronizadas barra lateral
reverse-sidebar = Invertir posición de barra lateral
hide-sidebar = Ocultar barra lateral
toggle-sidebar = Alternar barra lateral
zen-toggle-web-panels = Alternar paneles web
zen-toggle-compact-mode = Alternar modo compacto
zen-toggle-compact-mode-sidebar = Alternar la barra lateral del modo compacto
zen-toggle-compact-mode-toolbar = Alternar la barra de herramientas del modo compacto
zen-change-workspace = Recorrer áreas de trabajo en ciclo
zen-split-view-grid = Separación en vista cuadriculada
zen-split-view-vertical = Separación en vista vertical
zen-split-view-horizontal = Separación en vista horizontal
zen-split-view-close = Cerrar vista separada
