pane-zen-looks-title = Išvaizda ir turinys
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Pakeitus numatytąją kalbą, svetainėms gali būti lengviau jus sekti.
zen-look-and-feel-colors-header = Pasirinkite temos spalvą
zen-look-and-feel-colors-description = Padarykite, kad „{ -brand-short-name }“ atrodytų ir jaustųsi taip, kaip jums patinka
zen-look-and-feel-themed-toolbar = 
    .label = Padarykite įrankių juostą teminę su akcento spalva
pane-zen-side-panels-title = Šoniniai saityno skydeliai
zen-side-panels-header = Bendrieji saityno skydelių nustatymai
zen-side-panels-description = Padidinkite produktyvumą turint kelis rodinius vienu metu!
zen-side-panels-enabled = 
    .label = Įjungti šoninius saityno skydelius
zen-side-panels-close-on-blur = 
    .label = Užverti skydelį, kai jis praranda židinį, jei jis nėra prisegtas
zen-look-and-feel-compact-view-header = Rodyti kompaktiniame rodinyje
zen-look-and-feel-compact-view-description = Rodyti tik tas įrankių juostas, kurias naudojate!
zen-look-and-feel-compact-view-enabled = 
    .label = Įjungti „{ -brand-short-name }“ kompaktinį režimą
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Slėpti viršutinę įrankių juostą ir kompaktiniu režimu
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Trumpai padaryti, kad įrankių juosta iškyltų perjungiant arba atidarant naujas korteles kompaktiniu režimu
zen-look-and-feel-buttons-header = Mygtukų stilius
zen-look-and-feel-buttons-description = Pasirinkite mygtukų stilių, kurį norite matyti
zen-look-and-feel-pilled-buttons = 
    .label = Pildyti mygtukai
pane-zen-tabs-title = Tab Management
category-zen-workspaces = 
    .tooltiptext = { pane-zen-tabs-title }
pane-settings-workspaces-title = Darbo sritys
pane-zen-tabs-unloader-title = Tab Unloader
zen-tabs-unloader-header = General settings for tab unloader
zen-tabs-unloader-description = Automatically unload unused tabs to save memory
zen-tabs-unloader-enabled = 
    .label = Enable Tab Unloader
zen-tabs-unloader-unload-delay = 
    .label = Unload tabs after
zen-tabs-unloader-unload-delay-description = The time in minutes after which tabs will be unloaded
pane-zen-workspaces-header = Darbo sritys
zen-settings-workspaces-header = Bendrieji darbo sričių nustatymai
zen-settings-workspaces-description = Su darbo sritimis galite vienu metu atlikti kelias naršymo seansus!
zen-settings-workspaces-enabled = 
    .label = Įjungti darbo sritis (eksperimentinė)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Slėpti numatytojo konteinerio indikatorių kortelių juostoje
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Leisti darbo sritims turėti savo prisegtas korteles
pane-zen-theme-title = Temų nustatymai
zen-vertical-tabs-title = Šoninė juosta ir kortelių išdėstymas
zen-vertical-tabs-header = Vertikalios kortelės
zen-vertical-tabs-description = Tvarkykite korteles vertikaliame išdėstyme
zen-vertical-tabs-show-expand-button = 
    .label = Rodyti išskleidimo mygtuką
zen-vertical-tabs-expand-tabs-by-default = Išskleisti korteles pagal numatytąją nustatymą
zen-vertical-tabs-dont-expand-tabs-by-default = Neišskleisti kortelių pagal numatytąją nustatymą
zen-vertical-tabs-expand-tabs-on-hover = Išskleisti korteles užvedus (neveikia kompaktiniame režime)
zen-vertical-tabs-expand-tabs-header = Kaip išskleisti korteles
zen-vertical-tabs-expand-tabs-description = Pasirinkite, kaip išskleisti kortelės šoninėje juostoje
zen-theme-marketplace-header = „Zen“ modifikacijos
zen-theme-marketplace-description = Raskite ir įdiekite temas iš parduotuvės.
zen-theme-marketplace-remove-button = 
    .label = Pašalinti temą
zen-theme-marketplace-check-for-updates-button = 
    .label = Tikrinti, ar yra naujinimų
zen-theme-marketplace-updates-success = Tema sėkmingai atnaujinta
zen-theme-marketplace-updates-fail = Nepavyko rasti jokių naujinimų.
zen-theme-marketplace-toggle-enabled-button = 
    .title = Išjungti temą
zen-theme-marketplace-toggle-disabled-button = 
    .title = Įjungti temą
zen-theme-marketplace-remove-confirmation = Ar tikrai norite pašalinti šį modifikaciją?
zen-theme-marketplace-close-modal = Užverti
zen-theme-marketplace-theme-header-title = 
    .title = CSS parinkiklis: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = Nėra
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Įrašykite kažką...
pane-zen-marketplace-title = „Zen“ modifikacijos
zen-settings-workspaces-display-as-icon-strip = 
    .label = Rodyti darbo sritis kaip piktogramų juostą
zen-theme-marketplace-link = Aplankyti parduotuvę
zen-dark-theme-styles-header = Tamsios temos stiliai
zen-dark-theme-styles-description = Tinkinkite tamsią temą pagal savo poreikius
zen-dark-theme-styles-amoled = Naktinė tema
zen-dark-theme-styles-default = Numatytoji tamsi tema
zen-dark-theme-styles-colorful = Spalvinga tamsi tema
zen-compact-mode-styles-left = Slėpti kortelių juostą
zen-compact-mode-styles-top = Slėpti viršutinę juostą
zen-compact-mode-styles-both = Slėpti abiejus
pane-zen-CKS-title = Klaviatūros spartieji klavišai
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = „{ -brand-short-name }“ klaviatūros spartieji klavišai
zen-settings-CKS-header = Tinkinkite klaviatūros sparčiuosius klavišus
zen-settings-CKS-description = Keiskite numatytąsias klaviatūros sparčiąsias klavišus pagal savo pageidavimus ir patobulinkite naršymo potyrį
zen-settings-CKS-disable-firefox = 
    .label = Išjungti „{ -brand-short-name }“ numatytuosius klaviatūros sparčiuosius klavišus
zen-settings-CKS-duplicate-shortcut = 
    .label = Duplicate Shortcut
zen-settings-CKS-reset-shortcuts = 
    .label = Atkurti į numatytuosius nustatymus
zenCKSOption-group-other = Kita
zenCKSOption-group-windowAndTabManagement = Langų ir kortelių tvarkymas
zenCKSOption-group-navigation = Naršymas
zenCKSOption-group-searchAndFind = Ieškoti ir rasti
zenCKSOption-group-pageOperations = Page Operations
zenCKSOption-group-historyAndBookmarks = History & Bookmarks
zenCKSOption-group-mediaAndDisplay = Media & Display
zenCKSOption-group-zen-compact-mode = Kompaktinis režimas
zenCKSOption-group-zen-workspace = Darbo sritys
zenCKSOption-group-zen-other = Other Zen Features
zenCKSOption-group-zen-split-view = Split View
zen-key-quick-restart = Quick Restart
zen-window-new-shortcut = New Window
zen-tab-new-shortcut = New Tab
zen-location-open-shortcut = Open Location
zen-location-open-shortcut-alt = Open Location (Alt)
zen-key-undo-close-window = Undo Close Window
zen-text-action-undo-shortcut = Undo
zen-text-action-redo-shortcut = Redo
zen-text-action-cut-shortcut = Cut
zen-text-action-copy-shortcut = Copy
zen-text-action-paste-shortcut = Paste
zen-text-action-select-all-shortcut = Select All
zen-text-action-delete-shortcut = Delete
zen-history-show-all-shortcut-mac = Show All History (Mac)
zen-full-screen-shortcut = Toggle Full Screen
zen-reader-mode-toggle-shortcut-windows = Toggle Reader Mode (Windows)
zen-picture-in-picture-toggle-shortcut-alt = Toggle Picture-in-Picture (Alt)
zen-picture-in-picture-toggle-shortcut-mac = Toggle Picture-in-Picture (Mac)
zen-picture-in-picture-toggle-shortcut-mac-alt = Toggle Picture-in-Picture (Mac Alt)
zen-page-source-shortcut-safari = View Page Source (Safari)
zen-nav-stop-shortcut = Stop Loading
zen-history-sidebar-shortcut = Show History Sidebar
zen-window-minimize-shortcut = Minimize Window
zen-help-shortcut = Open Help
zen-preferences-shortcut = Open Preferences
zen-hide-app-shortcut = Hide Application
zen-hide-other-apps-shortcut = Hide Other Applications
zen-search-focus-shortcut = Focus Search
zen-search-focus-shortcut-alt = Focus Search (Alt)
zen-downloads-shortcut = Open Downloads
zen-addons-shortcut = Open Add-ons
zen-file-open-shortcut = Open File
zen-save-page-shortcut = Save Page
zen-print-shortcut = Print Page
zen-close-shortcut-2 = Close Tab
zen-mute-toggle-shortcut = Toggle Mute
zen-key-delete = Delete Key
zen-key-go-back = Go Back
zen-key-go-forward = Go Forward
zen-nav-back-shortcut-alt = Navigate Back (Alt)
zen-nav-fwd-shortcut-alt = Navigate Forward (Alt)
zen-history-show-all-shortcut = Show All History
zen-key-enter-full-screen = Enter Full Screen
zen-key-exit-full-screen = Exit Full Screen
zen-reader-mode-toggle-shortcut-other = Toggle Reader Mode
zen-picture-in-picture-toggle-shortcut = Toggle Picture-in-Picture
zen-nav-reload-shortcut-2 = Perkrauti puslapį
zen-key-about-processes = About Processes
zen-page-source-shortcut = Peržiūrėti puslapio šaltinį
zen-page-info-shortcut = Peržiūrėti puslapio informaciją
zen-find-shortcut = Rasti puslapyje
zen-search-find-again-shortcut = Find Again
zen-search-find-again-shortcut-prev = Find Previous
zen-search-find-again-shortcut-2 = Rasti dar kartą (Vald.)
zen-bookmark-this-page-shortcut = Pridėti šį puslapį į adresyną
zen-bookmark-show-library-shortcut = Show Bookmarks Library
zen-key-stop = Stop Loading
zen-full-zoom-reduce-shortcut = Zoom Out
zen-full-zoom-enlarge-shortcut = Zoom In
zen-full-zoom-reset-shortcut = Reset Zoom
zen-bidi-switch-direction-shortcut = Switch Text Direction
zen-private-browsing-shortcut = Private Browsing
zen-screenshot-shortcut = Take Screenshot
zen-key-sanitize = Clear Browsing Data
zen-quit-app-shortcut = Quit Application
zen-key-wr-capture-cmd = WR Capture Command
zen-key-wr-toggle-capture-sequence-cmd = Toggle WR Capture Sequence
zen-nav-reload-shortcut = Reload Page
zen-nav-reload-shortcut-skip-cache = Reload Page (Skip Cache)
zen-close-shortcut = Close Window
zen-close-tab-shortcut = Close Tab
zen-compact-mode-shortcut-show-sidebar = Toggle Floating Sidebar
zen-compact-mode-shortcut-show-toolbar = Toggle Floating Toolbar
zen-compact-mode-shortcut-toggle = Toggle Compact Mode
zen-workspace-shortcut-switch-1 = Switch to Workspace 1
zen-workspace-shortcut-switch-2 = Switch to Workspace 2
zen-workspace-shortcut-switch-3 = Switch to Workspace 3
zen-workspace-shortcut-switch-4 = Switch to Workspace 4
zen-workspace-shortcut-switch-5 = Switch to Workspace 5
zen-workspace-shortcut-switch-6 = Switch to Workspace 6
zen-workspace-shortcut-switch-7 = Switch to Workspace 7
zen-workspace-shortcut-switch-8 = Switch to Workspace 8
zen-workspace-shortcut-switch-9 = Switch to Workspace 9
zen-workspace-shortcut-switch-10 = Switch to Workspace 10
zen-workspace-shortcut-forward = Forward Workspace
zen-workspace-shortcut-backward = Backward Workspace
zen-web-panel-shortcut-toggle = Toggle Web Panel
zen-sidebar-shortcut-toggle = Toggle Sidebar's Width
zen-split-view-shortcut-grid = Toggle Split View Grid
zen-split-view-shortcut-vertical = Toggle Split View Vertical
zen-split-view-shortcut-horizontal = Toggle Split View Horizontal
zen-split-view-shortcut-unsplit = Close Split View
zen-key-select-tab-1 = Select tab #1
zen-key-select-tab-2 = Select tab #2
zen-key-select-tab-3 = Select tab #3
zen-key-select-tab-4 = Select tab #4
zen-key-select-tab-5 = Select tab #5
zen-key-select-tab-6 = Select tab #6
zen-key-select-tab-7 = Select tab #7
zen-key-select-tab-8 = Select tab #8
zen-key-select-tab-last = Select last tab
zen-key-show-all-tabs = Show all tabs
zen-key-goto-history = Go to history
zen-key-go-home = Eiti į pagrindinį
zen-bookmark-show-sidebar-shortcut = Rodyti adresyno šoninę juostą
zen-bookmark-show-toolbar-shortcut = Rodyti adresyno įrankių juostą
