pane-zen-looks-title = Išvaizda ir turinys
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Pakeitus numatytąją kalbą, svetainėms gali būti lengviau jus sekti.
zen-look-and-feel-colors-header = Pasirinkite temos spalvą
zen-look-and-feel-colors-description = Padarykite, kad „{ -brand-short-name }“ atrodytų ir jaustųsi taip, kaip jums patinka
zen-look-and-feel-themed-toolbar = 
    .label = Padarykite įrankių juostą teminę su akcento spalva
pane-zen-side-panels-title = Šoniniai saityno skydeliai
zen-side-panels-header = Bendrieji saityno skydelių nustatymai
zen-side-panels-description = Padidinkite produktyvumą turint kelis rodinius vienu metu!
zen-side-panels-enabled = 
    .label = Įjungti šoninius saityno skydelius
zen-side-panels-close-on-blur = 
    .label = Užverti skydelį, kai jis praranda židinį, jei jis nėra prisegtas
zen-look-and-feel-compact-view-header = Rodyti kompaktiniame rodinyje
zen-look-and-feel-compact-view-description = Rodyti tik tas įrankių juostas, kurias naudojate!
zen-look-and-feel-compact-view-enabled = 
    .label = Įjungti „{ -brand-short-name }“ kompaktinį režimą
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Slėpti viršutinę įrankių juostą ir kompaktiniu režimu
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Trumpai padaryti, kad įrankių juosta iškyltų perjungiant arba atidarant naujas korteles kompaktiniu režimu
zen-look-and-feel-buttons-header = Mygtukų stilius
zen-look-and-feel-buttons-description = Pasirinkite mygtukų stilių, kurį norite matyti
zen-look-and-feel-pilled-buttons = 
    .label = Pildyti mygtukai
pane-zen-workspaces-title = Darbo sritys
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = Darbo sritys
pane-zen-workspaces-header = Darbo sritys
zen-settings-workspaces-header = Bendrieji darbo sričių nustatymai
zen-settings-workspaces-description = Su darbo sritimis galite vienu metu atlikti kelias naršymo seansus!
zen-settings-workspaces-enabled = 
    .label = Įjungti darbo sritis (eksperimentinė)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Slėpti numatytojo konteinerio indikatorių kortelių juostoje
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Leisti darbo sritims turėti savo prisegtas korteles
pane-zen-theme-title = Temų nustatymai
zen-vertical-tabs-title = Šoninė juosta ir kortelių išdėstymas
zen-vertical-tabs-header = Vertikalios kortelės
zen-vertical-tabs-description = Tvarkykite korteles vertikaliame išdėstyme
zen-vertical-tabs-show-expand-button = 
    .label = Rodyti išskleidimo mygtuką
zen-vertical-tabs-expand-tabs-by-default = Išskleisti korteles pagal numatytąją nustatymą
zen-vertical-tabs-dont-expand-tabs-by-default = Neišskleisti kortelių pagal numatytąją nustatymą
zen-vertical-tabs-expand-tabs-on-hover = Išskleisti korteles užvedus (neveikia kompaktiniame režime)
zen-vertical-tabs-expand-tabs-header = Kaip išskleisti korteles
zen-vertical-tabs-expand-tabs-description = Pasirinkite, kaip išskleisti kortelės šoninėje juostoje
zen-theme-marketplace-header = „Zen“ modifikacijos
zen-theme-marketplace-description = Raskite ir įdiekite temas iš parduotuvės.
zen-theme-marketplace-remove-button = 
    .label = Pašalinti temą
zen-theme-marketplace-check-for-updates-button = 
    .label = Tikrinti, ar yra naujinimų
zen-theme-marketplace-updates-success = Tema sėkmingai atnaujinta
zen-theme-marketplace-updates-fail = Nepavyko rasti jokių naujinimų.
zen-theme-marketplace-toggle-enabled-button = 
    .title = Išjungti temą
zen-theme-marketplace-toggle-disabled-button = 
    .title = Įjungti temą
zen-theme-marketplace-remove-confirmation = Ar tikrai norite pašalinti šią temą?
zen-theme-marketplace-close-modal = Užverti
zen-theme-marketplace-theme-header-title = 
    .title = CSS parinkiklis: { $name }
pane-zen-marketplace-title = „Zen“ modifikacijos
zen-theme-marketplace-link = Aplankyti parduotuvę
zen-dark-theme-styles-header = Tamsios temos stiliai
zen-dark-theme-styles-description = Tinkinkite tamsią temą pagal savo poreikius
zen-dark-theme-styles-amoled = Naktinė tema
zen-dark-theme-styles-default = Numatytoji tamsi tema
zen-dark-theme-styles-colorful = Spalvinga tamsi tema
pane-zen-CKS-title = Klaviatūros spartieji klavišai
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = „{ -brand-short-name }“ klaviatūros spartieji klavišai
zen-settings-CKS-header = Customize your keyboard shortcuts
zen-settings-CKS-description = Change the default keyboard shortcuts to your liking and improve your browsing experience
zen-settings-CKS-disable-firefox = 
    .label = Disable { -brand-short-name }'s default keyboard shortcuts
zen-cks-group-tab-action = Tab Actions
zen-cks-group-page-action = Page Actions
zen-cks-group-visible-action = Visible Actions
zen-cks-group-history-action = History Actions
zen-cks-group-search-action = Search Actions
zen-cks-group-tools-action = Tools Actions
zen-cks-group-bookmark-action = Bookmark Actions
zen-cks-group-open-page-action = Open Page Actions
zen-cks-group-downloads-action = Downloads Actions
zen-cks-group-sidebar-action = Sidebar Actions
zen-cks-group-compact-mode-action = Compact Mode Actions
zen-cks-group-split-view-action = Split View Actions
zen-cks-group-workspace-action = Workspace Actions
open-new-tab = Open New Tab
close-tab = Close Tab
open-new-window = Open New Window
open-new-private-window = Atverti naują privatų langą
close-window = Užverti langą
restore-last-tab = Atkurti paskutinį kortelę
restore-last-window = Atkurti paskutinį langą
show-next-tab = Show Next Tab
show-previous-tab = Show Previous Tab
show-all-tabs-panel = Show All Tabs Panel
send-with-mail = Send Page with Mail
save-page = Save Page
print-page = Spausdinti puslapį
mute-current-tab = Mute Current Tab
show-source-of-page = Show Source of Page
show-page-info = Show Page Info
zoom-in = Padidinti
zoom-out = Sumažinti
reset-zoom = Atkurti mastelį
back = Atgal
forward = Pirmyn
stop = Stop
reload = Perkrauti
force-reload = Priverstinai perkrauti
search-in-this-page = Ieškoti šiame puslapyje
show-next-search-result = Show Next Search Result
show-previous-search-result = Show Previous Search Result
search-the-web = Search the Web
open-migration-wizard = Open Migration Wizard
quit-from-application = Quit Application
enter-into-customize-mode = Enter Customize Mode
enter-into-offline-mode = Enter Offline Mode
open-screen-capture = Open Screen Capture
bookmark-this-page = Bookmark This Page
open-bookmark-add-tool = Open Bookmark Add Tool
open-bookmarks-manager = Open Bookmarks Manager
toggle-bookmark-toolbar = Toggle Bookmark Toolbar
open-general-preferences = Open General Preferences
open-privacy-preferences = Open Privacy Preferences
open-workspaces-preferences = Open Workspaces Preferences
open-containers-preferences = Open Containers Preferences
open-search-preferences = Open Search Preferences
open-sync-preferences = Open Sync Preferences
open-task-manager = Open Task Manager
open-addons-manager = Open Add-ons Manager
open-home-page = Open Home Page
forget-history = Forget History
quick-forget-history = Quick Forget History
clear-recent-history = Clear Recent History
restore-last-session = Restore Last Session
search-history = Search History
manage-history = Manage History
open-downloads = Atverti atsisiuntimus
show-bookmark-sidebar = Rodyti adresyno šoninę juostą
show-history-sidebar = Rodyti istorijos šoninę juostą
show-synced-tabs-sidebar = Rodyti sinchronizuotų kortelių šoninę juostą
reverse-sidebar = Atvirkštinė šoninės juostos vieta
hide-sidebar = Slėpti šoninę juostą
toggle-sidebar = Perjungti šoninę juostą
zen-toggle-web-panels = Perjungti saityno skydelius
zen-toggle-compact-mode = Perjungti kompaktinį režimą
zen-toggle-compact-mode-sidebar = Perjungti kompaktinio režimo šoninę juostą
zen-toggle-compact-mode-toolbar = Perjungti kompaktinio režimo įrankių juostą
zen-change-workspace = Apkeisti darbo sritys
zen-split-view-grid = Skaidymo rodinys tinklelis
zen-split-view-vertical = Skaidymo rodinys vertikaliai
zen-split-view-horizontal = Skaidymo rodinys horizontaliai
zen-split-view-close = Užverti skaidymo rodinį
zen-expand-sidebar = Perjungti šoninės juostos išskleidimą
