pane-zen-looks-title = Išvaizda ir turinys
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Pakeitus numatytąją kalbą, svetainėms gali būti lengviau jus sekti.
zen-look-and-feel-colors-header = Pasirinkite temos spalvą
zen-look-and-feel-colors-description = Padarykite, kad „{ -brand-short-name }“ atrodytų ir jaustųsi taip, kaip jums patinka
zen-look-and-feel-themed-toolbar = 
    .label = Padarykite įrankių juostą teminę su akcento spalva
pane-zen-side-panels-title = Šoniniai saityno skydeliai
zen-side-panels-header = Bendrieji saityno skydelių nustatymai
zen-side-panels-description = Padidinkite produktyvumą turint kelis rodinius vienu metu!
zen-side-panels-enabled = 
    .label = Įjungti šoninius saityno skydelius
zen-side-panels-close-on-blur = 
    .label = Užverti skydelį, kai jis praranda židinį, jei jis nėra prisegtas
zen-look-and-feel-compact-view-header = Rodyti kompaktiniame rodinyje
zen-look-and-feel-compact-view-description = Rodyti tik tas įrankių juostas, kurias naudojate!
zen-look-and-feel-compact-view-enabled = 
    .label = Įjungti „{ -brand-short-name }“ kompaktinį režimą
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Slėpti viršutinę įrankių juostą ir kompaktiniu režimu
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Trumpai padaryti, kad įrankių juosta iškyltų perjungiant arba atidarant naujas korteles kompaktiniu režimu
zen-look-and-feel-buttons-header = Mygtukų stilius
zen-look-and-feel-buttons-description = Pasirinkite mygtukų stilių, kurį norite matyti
zen-look-and-feel-pilled-buttons = 
    .label = Pildyti mygtukai
pane-zen-workspaces-title = Darbo sritys
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = Darbo sritys
pane-zen-workspaces-header = Darbo sritys
zen-settings-workspaces-header = Bendrieji darbo sričių nustatymai
zen-settings-workspaces-description = Su darbo sritimis galite vienu metu atlikti kelias naršymo seansus!
zen-settings-workspaces-enabled = 
    .label = Įjungti darbo sritis (eksperimentinė)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Slėpti numatytojo konteinerio indikatorių kortelių juostoje
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Leisti darbo sritims turėti savo prisegtas korteles
pane-zen-theme-title = Temų nustatymai
zen-vertical-tabs-title = Šoninė juosta ir kortelių išdėstymas
zen-vertical-tabs-header = Vertikalios kortelės
zen-vertical-tabs-description = Tvarkykite korteles vertikaliame išdėstyme
zen-vertical-tabs-show-expand-button = 
    .label = Rodyti išskleidimo mygtuką
zen-vertical-tabs-expand-tabs-by-default = Išskleisti korteles pagal numatytąją nustatymą
zen-vertical-tabs-dont-expand-tabs-by-default = Neišskleisti kortelių pagal numatytąją nustatymą
zen-vertical-tabs-expand-tabs-on-hover = Išskleisti korteles užvedus (neveikia kompaktiniame režime)
zen-vertical-tabs-expand-tabs-header = Kaip išskleisti korteles
zen-vertical-tabs-expand-tabs-description = Pasirinkite, kaip išskleisti kortelės šoninėje juostoje
zen-theme-marketplace-header = „Zen“ modifikacijos
zen-theme-marketplace-description = Raskite ir įdiekite temas iš parduotuvės.
zen-theme-marketplace-remove-button = 
    .label = Pašalinti temą
zen-theme-marketplace-check-for-updates-button = 
    .label = Tikrinti, ar yra naujinimų
zen-theme-marketplace-updates-success = Tema sėkmingai atnaujinta
zen-theme-marketplace-updates-fail = Nepavyko rasti jokių naujinimų.
zen-theme-marketplace-toggle-enabled-button = 
    .title = Išjungti temą
zen-theme-marketplace-toggle-disabled-button = 
    .title = Įjungti temą
zen-theme-marketplace-remove-confirmation = Ar tikrai norite pašalinti šią temą?
zen-theme-marketplace-close-modal = Užverti
zen-theme-marketplace-theme-header-title = 
    .title = CSS parinkiklis: { $name }
pane-zen-marketplace-title = „Zen“ modifikacijos
zen-settings-workspaces-display-as-icon-strip = 
    .label = Rodyti darbo sritis kaip piktogramų juostą
zen-theme-marketplace-link = Aplankyti parduotuvę
zen-dark-theme-styles-header = Tamsios temos stiliai
zen-dark-theme-styles-description = Tinkinkite tamsią temą pagal savo poreikius
zen-dark-theme-styles-amoled = Naktinė tema
zen-dark-theme-styles-default = Numatytoji tamsi tema
zen-dark-theme-styles-colorful = Spalvinga tamsi tema
pane-zen-CKS-title = Klaviatūros spartieji klavišai
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = „{ -brand-short-name }“ klaviatūros spartieji klavišai
zen-settings-CKS-header = Tinkinkite klaviatūros sparčiuosius klavišus
zen-settings-CKS-description = Keiskite numatytąsias klaviatūros sparčiąsias klavišus pagal savo pageidavimus ir patobulinkite naršymo potyrį
zen-settings-CKS-disable-firefox = 
    .label = Išjungti „{ -brand-short-name }“ numatytuosius klaviatūros sparčiuosius klavišus
zen-cks-group-tab-action = Kortelės veiksmai
zen-cks-group-page-action = Page Actions
zen-cks-group-visible-action = Visible Actions
zen-cks-group-history-action = History Actions
zen-cks-group-search-action = Paieškos veiksmai
zen-cks-group-tools-action = Įrankių veiksmai
zen-cks-group-bookmark-action = Bookmark Actions
zen-cks-group-open-page-action = Open Page Actions
zen-cks-group-downloads-action = Atsisiuntimų veiksmai
zen-cks-group-sidebar-action = Sidebar Actions
zen-cks-group-compact-mode-action = Compact Mode Actions
zen-cks-group-split-view-action = Split View Actions
zen-cks-group-workspace-action = Darbo srities veiksmai
open-new-tab = Atverti naują kortelę
close-tab = Užverti kortelę
open-new-window = Atverti naują langą
open-new-private-window = Atverti naują privatų langą
close-window = Užverti langą
restore-last-tab = Atkurti paskutinį kortelę
restore-last-window = Atkurti paskutinį langą
show-next-tab = Rodyti sekantį kortelę
show-previous-tab = Rodyti ankstesnę kortelę
show-all-tabs-panel = Rodyti visų kortelių skydelį
send-with-mail = Siųsti puslapį su paštu
save-page = Įrašyti puslapį
print-page = Spausdinti puslapį
mute-current-tab = Išjungti dabartinės kortelės garsą
show-source-of-page = Rodyti puslapio šaltinį
show-page-info = Rodyti puslapio informaciją
zoom-in = Padidinti
zoom-out = Sumažinti
reset-zoom = Atkurti mastelį
back = Atgal
forward = Pirmyn
stop = Sustabdyti
reload = Perkrauti
force-reload = Priverstinai perkrauti
search-in-this-page = Ieškoti šiame puslapyje
show-next-search-result = Rodyti kitą paieškos rezultatą
show-previous-search-result = Rodyti ankstesnį paieškos rezultatą
search-the-web = Ieškoti saityną
open-migration-wizard = Atverti perkėlimo vediklį
quit-from-application = Išeiti iš programos
enter-into-customize-mode = Įeiti į tinkinimo režimą
enter-into-offline-mode = Įeiti į neprisijungusį režimą
open-screen-capture = Atverti ekrano kopiją
bookmark-this-page = Bookmark This Page
open-bookmark-add-tool = Open Bookmark Add Tool
open-bookmarks-manager = Open Bookmarks Manager
toggle-bookmark-toolbar = Toggle Bookmark Toolbar
open-general-preferences = Open General Preferences
open-privacy-preferences = Atverti privatumo nuostatas
open-workspaces-preferences = Atverti darbo sričių nuostatas
open-containers-preferences = Atverti konteinerių nuostatas
open-search-preferences = Atverti paieškos nuostatas
open-sync-preferences = Atverti sinchronizavimo nuostatas
open-task-manager = Atverti užduočių tvarkytuvę
open-addons-manager = Atverti priedų tvarkytuvę
open-home-page = Atverti pagrindinį puslapį
forget-history = Pamiršti istoriją
quick-forget-history = Greitai pamiršti istoriją
clear-recent-history = Valyti naujausią istoriją
restore-last-session = Atkurti paskutinę seansą
search-history = Ieškoti istoriją
manage-history = Tvarkyti istoriją
open-downloads = Atverti atsisiuntimus
show-bookmark-sidebar = Rodyti adresyno šoninę juostą
show-history-sidebar = Rodyti istorijos šoninę juostą
show-synced-tabs-sidebar = Rodyti sinchronizuotų kortelių šoninę juostą
reverse-sidebar = Atvirkštinė šoninės juostos vieta
hide-sidebar = Slėpti šoninę juostą
toggle-sidebar = Perjungti šoninę juostą
zen-toggle-web-panels = Perjungti saityno skydelius
zen-toggle-compact-mode = Perjungti kompaktinį režimą
zen-toggle-compact-mode-sidebar = Perjungti kompaktinio režimo šoninę juostą
zen-toggle-compact-mode-toolbar = Perjungti kompaktinio režimo įrankių juostą
zen-change-workspace = Apkeisti darbo sritys
zen-split-view-grid = Skaidymo rodinys tinklelis
zen-split-view-vertical = Skaidymo rodinys vertikaliai
zen-split-view-horizontal = Skaidymo rodinys horizontaliai
zen-split-view-close = Užverti skaidymo rodinį
zen-expand-sidebar = Perjungti šoninės juostos išskleidimą
