pane-zen-looks-title = Внешний вид
category-zen-looks =
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Изменение языка по умолчанию может облегчить веб-сайтам отслеживание вас.
zen-look-and-feel-colors-header = Выберите цвет темы
zen-look-and-feel-colors-description = Сделайте { -brand-short-name} таким, как вам нравится
zen-look-and-feel-theme-toolbar =
    .label = Использовать цветовой акцент для темы панели инструментов
pane-zen-side-panels-title = Боковые веб-панели
zen-side-panels-header = Общие настройки для веб-панелей
zen-side-panels-description = Повышение продуктивности с помощью нескольких страниц одновременно!
zen-side-panels-enabled =
    .label = Включить веб-панели
zen-side-panels-close-on-blur =
    .label = Закрывать панель, когда она теряет фокус, если она не закреплена
zen-look-and-feel-compact-view-header = Показывать в компактном виде
zen-look-and-feel-compact-view-description = Показывать только панели инструментов, которые вы используете!
zen-look-and-feel-compact-view-enabled =
    .label = Включить компактный режим для { -brand-short-name}
zen-look-and-feel-compact-view-top-toolbar =
    .label = Скрывать верхнюю панель инструментов в компактном режиме
zen-look-and-feel-buttons-header = Стиль кнопок
zen-look-and-feel-buttons-description = Выберите стиль кнопок, который вы хотите видеть
zen-look-and-feel-pilled-buttons =
    .label = Кнопки с закруглением
pane-zen-workspaces-title = Рабочие области
category-zen-workspaces =
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = Рабочие области
pane-zen-workspaces-header = Рабочие области
zen-settings-workspaces-header = Общие настройки для рабочих пространств
zen-settings-workspaces-description = С помощью рабочих пространств вы можете иметь несколько сеансов просмотра одновременно!
zen-settings-workspaces-enabled =
    .label = Включить рабочие области (экспериментально)
pane-zen-theme-title = Настройка темы
zen-vertical-tabs-title = Расположение боковой панели и вкладок
zen-vertical-tabs-header = Вертикальные вкладки
zen-vertical-tabs-description = Управление вкладками в вертикальном расположении
zen-vertical-tabs-show-expand-button =
    .label = Показывать кнопку развертывания
zen-vertical-tabs-expand-tabs-by-default = Разворачивать вкладки по умолчанию
zen-vertical-tabs-dont-expand-tabs-by-default = Не разворачивать вкладки по умолчанию
zen-vertical-tabs-expand-tabs-on-hover = Разворачивать вкладки при наведении (не будет работать в компактном режиме)
zen-vertical-tabs-expand-tabs-header = Как разворачивать вкладки
zen-vertical-tabs-expand-tabs-description = Выбор способа разворачивания вкладок на боковой панели
zen-theme-marketplace-header = Магазин тем
zen-theme-marketplace-description = Найти и установить темы из магазина.
zen-theme-marketplace-remove-button =
    .label = Удалить тему
zen-theme-marketplace-link = Посетить магазин
pane-zen-CKS-title = Комбинации клавиш
category-zen-CKS =
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } Комбинации клавиш
zen-settings-CKS-header = Настроить комбинации клавиш
zen-settings-CKS-description = Измените стандартные комбинации клавиш на ваши предпочтения и улучшите удобство работы в интернете
zen-settings-CKS-disable-firefox =
    .label = Отключить стандартные комбинации клавиш { -brand-short-name} для { -brand-short-name}.
zen-cks-group-tab-action = Действия на вкладках
zen-cks-group-page-action = Действия на странице
zen-cks-group-visible-action = Видимые действия
zen-cks-group-history-action = Действия с историей
zen-cks-group-search-action = Действия поиска
zen-cks-group-tools-action = Действия с инструментами
zen-cks-group-bookmark-action = Действия с закладками
zen-cks-group-open-page-action = Действия по открытию страницы
zen-cks-group-downloads-action = Действия для загрузок
zen-cks-group-sidebar-action = Действия боковой панели
zen-cks-group-compact-mode-action = Действия компактного режима
zen-cks-group-split-view-action = Действия разделенного просмотра
zen-cks-group-workspace-action = Действия рабочего пространства
open-new-tab = Открыть новую вкладку
close-tab = Закрыть вкладку
open-new-window = Открыть новое окно
open-new-private-window = Открыть новое приватное окно
close-window = Закрыть окно
restore-last-tab = Восстановить последнюю вкладку
restore-last-window = Восстановить последнее окно
show-next-tab = Следующая вкладка
show-previous-tab = Предыдущая вкладка
show-all-tabs-panel = Показать панель вкладок
send-with-mail = Отправить страницу с почтой
save-page = Сохранить страницу
print-page = Печать страницы
mute-current-tab = Отключить текущую вкладку
show-source-of-page = Показать источник страницы
show-page-info = Показать информацию о странице
zoom-in = Увеличить
zoom-out = Уменьшить масштаб
reset-zoom = Сбросить масштаб
back = Назад
forward = Вперед
stop = Стоп
reload = Перезагрузить
force-reload = Принудительная перезагрузка
search-in-this-page = Искать на этой странице
show-next-search-result = Показать следующий результат поиска
show-previous-search-result = Показать предыдущий результат поиска
search-the-web = Искать в Интернете
open-migration-wizard = Открыть мастер миграции
quit-from-application = Выйти из приложения
enter-into-customize-mode = Войти в режим настройки
enter-into-offline-mode = Войти в автономный режим
open-screen-capture = Сделать снимок экрана
bookmark-this-page = Добавить эту страницу в закладки
open-bookmark-add-tool = Открыть инструмент добавления закладок
open-bookmarks-manager = Открыть менеджер закладок
toggle-bookmark-toolbar = Переключить панель инструментов закладок
open-general-preferences = Открыть общие настройки
open-privacy-preferences = Открыть настройки конфиденциальности
open-workspaces-preferences = Открыть настройки рабочих пространств
open-containers-preferences = Открыть настройки контейнеров
open-search-preferences = Открыть параметры поиска
open-sync-preferences = Открыть параметры синхронизации
open-task-manager = Открыть менеджер задач
open-addons-manager = Открыть менеджер дополнений
open-home-page = Открыть домашнюю страницу
forget-history = Забыть историю
quick-forget-history = Быстро забыть историю
clear-recent-history = Очистить недавнюю историю
restore-last-session = Восстановить последнюю сессию
search-history = История поиска = История поиска
manage-history = Управлять историей
open-downloads = Открыть загрузки
show-bookmark-sidebar = Показать боковую панель закладок
show-history-sidebar = Показать боковую панель истории
show-synced-tabs-sidebar = Показать боковую панель синхронизированных вкладок
reverse-sidebar = Изменить положение боковой панели
hide-sidebar = Скрыть боковую панель
toggle-sidebar = Переключить боковую панель
zen-toggle-web-panels = Переключить веб-панели
zen-toggle-compact-mode = Включить компактный режим
zen-toggle-compact-mode-sidebar = Включить боковую панель в компактном режиме
zen-toggle-compact-mode-toolbar = Включить панель инструментов в компактном режиме
zen-change-workspace = Рабочие области цикла
zen-split-view-grid = Сетка разделенного просмотра
zen-split-view-vertical = Разделенный вид по вертикали
zen-split-view-horizontal = Разделенный вид по горизонтали
zen-split-view-close = Закрыть разделенный вид
