pane-zen-looks-title = Внешний вид
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Изменение языка по умолчанию может упростить отслеживание вас на сайтах.
zen-look-and-feel-colors-header = Выберите цветовую тему
zen-look-and-feel-colors-description = Сделайте так, чтобы { -brand-short-name } выглядел так, как вам нравится
zen-look-and-feel-themed-toolbar = 
    .label = Использовать цветовой акцент для темы панели инструментов
pane-zen-side-panels-title = Боковые веб-панели
zen-side-panels-header = Общие настройки боковых веб-панелей
zen-side-panels-description = Повысьте продуктивность, используя несколько страниц одновременно!
zen-side-panels-enabled = 
    .label = Включить боковые веб-панели
zen-side-panels-close-on-blur = 
    .label = Закрывать панель при потере фокуса, если она не закреплена
zen-look-and-feel-compact-view-header = Показать в компактном виде
zen-look-and-feel-compact-view-description = Отображать только те панели, которые вы используете!
zen-look-and-feel-compact-view-enabled = 
    .label = Включить компактный вид в { -brand-short-name }
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Скрыть верхнюю панель в компактном виде
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Кратко отображать панель инструментов при переключении или открытии новых вкладок в компактном режиме
zen-look-and-feel-buttons-header = Стиль кнопок
zen-look-and-feel-buttons-description = Выберите стиль кнопок, которые вы хотите видеть
zen-look-and-feel-pilled-buttons = 
    .label = Скругленные кнопки
pane-zen-workspaces-title = Рабочие области
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = Рабочие области
pane-zen-workspaces-header = Рабочие области
zen-settings-workspaces-header = Общие настройки рабочих областей
zen-settings-workspaces-description = Благодаря рабочим областям, вы можете использовать несколько сессий одновременно!
zen-settings-workspaces-enabled = 
    .label = Включить рабочие области (экспериментально)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Скрыть индикатор контейнера по умолчанию на панели вкладок
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Разрешить рабочим областям иметь разные закрепленные вкладки
pane-zen-theme-title = Настройка темы
zen-vertical-tabs-title = Расположение боковой панели и вкладок
zen-vertical-tabs-header = Вертикальные вкладки
zen-vertical-tabs-description = Управляйте вкладками в вертикальном расположении
zen-vertical-tabs-show-expand-button = 
    .label = Показать кнопку разворачивания
zen-vertical-tabs-expand-tabs-by-default = Разворачивать вкладки по умолчанию
zen-vertical-tabs-dont-expand-tabs-by-default = Не разворачивать вкладки по умолчанию
zen-vertical-tabs-expand-tabs-on-hover = Разворачивать вкладки при наведении (не работает в компактном виде)
zen-vertical-tabs-expand-tabs-header = Каким образом разворачивать вкладки
zen-vertical-tabs-expand-tabs-description = Выберите, как разворачивать вкладки в боковой панели
zen-theme-marketplace-header = Модификации Zen
zen-theme-marketplace-description = Найдите и установите темы из магазина.
zen-theme-marketplace-remove-button = 
    .label = Удалить тему
zen-theme-marketplace-check-for-updates-button = 
    .label = Проверить наличие обновлений
zen-theme-marketplace-updates-success = Тема успешно обновлена
zen-theme-marketplace-updates-fail = Обновлений не найдено!
zen-theme-marketplace-toggle-enabled-button = 
    .title = Отключить тему
zen-theme-marketplace-toggle-disabled-button = 
    .title = Включить тему
zen-theme-marketplace-remove-confirmation = Вы уверены, что хотите удалить эту модификацию?
zen-theme-marketplace-close-modal = Закрыть
zen-theme-marketplace-theme-header-title = 
    .title = Селектор CSS: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = Ничего
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Напишите что-нибудь...
pane-zen-marketplace-title = Модификации Zen
zen-settings-workspaces-display-as-icon-strip = 
    .label = Отображать рабочие области в ряд
zen-theme-marketplace-link = Посетить магазин
zen-dark-theme-styles-header = Стили темной темы
zen-dark-theme-styles-description = Настройте темную тему по своему вкусу
zen-dark-theme-styles-amoled = Ночная тема
zen-dark-theme-styles-default = Стандартная темная тема
zen-dark-theme-styles-colorful = Цветная темная тема
zen-compact-mode-styles-left = Скрыть панель вкладок
zen-compact-mode-styles-top = Скрыть верхнюю панель
zen-compact-mode-styles-both = Скрыть обе панели
pane-zen-CKS-title = Комбинации клавиш
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = Комбинации клавиш в { -brand-short-name }
zen-settings-CKS-header = Изменить комбинации клавиш
zen-settings-CKS-description = Измените комбинации клавиш по умолчанию и улучшите ваш опыт пользования браузером
zen-settings-CKS-disable-firefox = 
    .label = Отключить комбинации клавиш по умолчанию в { -brand-short-name }
zen-settings-CKS-duplicate-shortcut = 
    .label = Дублировать комбинацию клавиш
zen-settings-CKS-reset-shortcuts = 
    .label = Сбросить настройки
zenCKSOption-group-other = Прочее
zenCKSOption-group-windowAndTabManagement = Управление окнами и вкладками
zenCKSOption-group-navigation = Навигация
zenCKSOption-group-searchAndFind = Поиск
zenCKSOption-group-pageOperations = Операции на странице
zenCKSOption-group-historyAndBookmarks = История и закладки
zenCKSOption-group-mediaAndDisplay = Медиа и отображение
zenCKSOption-group-zen-compact-mode = Компактный режим
zenCKSOption-group-zen-workspace = Рабочие области
zenCKSOption-group-zen-other = Другие функции Zen
zenCKSOption-group-zen-split-view = Раздельный вид
zen-key-quick-restart = Быстрый перезапуск
zen-window-new-shortcut = Новое окно
zen-tab-new-shortcut = Новая вкладка
zen-location-open-shortcut = Открыть расположение
zen-location-open-shortcut-alt = Открыть расположение (Alt)
zen-key-undo-close-window = Отменить закрытие окна
zen-text-action-undo-shortcut = Отменить
zen-text-action-redo-shortcut = Повторить
zen-text-action-cut-shortcut = Вырезать
zen-text-action-copy-shortcut = Копировать
zen-text-action-paste-shortcut = Вставить
zen-text-action-select-all-shortcut = Выбрать все
zen-text-action-delete-shortcut = Удалить
zen-history-show-all-shortcut-mac = Показать полную историю (Mac)
zen-full-screen-shortcut = Переключить полноэкранный режим
zen-reader-mode-toggle-shortcut-windows = Переключить режим чтения (Windows)
zen-picture-in-picture-toggle-shortcut-alt = Переключить режим картинка в картинке (Alt)
zen-picture-in-picture-toggle-shortcut-mac = Переключить режим картинка в картинке (Mac)
zen-picture-in-picture-toggle-shortcut-mac-alt = Переключить режим картинка в картинке (Mac Alt)
zen-page-source-shortcut-safari = Исходный код страницы (Safari)
zen-nav-stop-shortcut = Отменить загрузку
zen-history-sidebar-shortcut = Отобразить боковую панель истории
zen-window-minimize-shortcut = Свернуть окно
zen-help-shortcut = Открыть справку
zen-preferences-shortcut = Открыть настройки
zen-hide-app-shortcut = Скрыть приложение
zen-hide-other-apps-shortcut = Скрыть другие приложения
zen-search-focus-shortcut = Поиск в фокусе
zen-search-focus-shortcut-alt = Поиск в фокусе (Alt)
zen-downloads-shortcut = Открыть загрузки
zen-addons-shortcut = Открыть дополнения
zen-file-open-shortcut = Открыть файл
zen-save-page-shortcut = Сохранить страницу
zen-print-shortcut = Распечатать страницу
zen-close-shortcut-2 = Закрыть вкладку
zen-mute-toggle-shortcut = Вкл/выкл звук
zen-key-delete = Удалить кнопку
zen-key-go-back = Назад
zen-key-go-forward = Вперед
zen-nav-back-shortcut-alt = Перейти назад (Alt)
zen-nav-fwd-shortcut-alt = Перейти вперед (Alt)
zen-history-show-all-shortcut = Показать полную историю
zen-key-enter-full-screen = Полноэкранный режим
zen-key-exit-full-screen = Выйти из полноэкранного режима
zen-reader-mode-toggle-shortcut-other = Toggle Reader Mode
zen-picture-in-picture-toggle-shortcut = Toggle Picture-in-Picture
zen-nav-reload-shortcut-2 = Reload Page
zen-key-about-processes = About Processes
zen-page-source-shortcut = View Page Source
zen-page-info-shortcut = View Page Info
zen-find-shortcut = Find on Page
zen-search-find-again-shortcut = Find Again
zen-search-find-again-shortcut-prev = Find Previous
zen-search-find-again-shortcut-2 = Find Again (Alt)
zen-bookmark-this-page-shortcut = Bookmark This Page
zen-bookmark-show-library-shortcut = Show Bookmarks Library
zen-key-stop = Stop Loading
zen-full-zoom-reduce-shortcut = Zoom Out
zen-full-zoom-enlarge-shortcut = Zoom In
zen-full-zoom-reset-shortcut = Reset Zoom
zen-bidi-switch-direction-shortcut = Switch Text Direction
zen-private-browsing-shortcut = Private Browsing
zen-screenshot-shortcut = Take Screenshot
zen-key-sanitize = Clear Browsing Data
zen-quit-app-shortcut = Quit Application
zen-key-wr-capture-cmd = WR Capture Command
zen-key-wr-toggle-capture-sequence-cmd = Toggle WR Capture Sequence
zen-nav-reload-shortcut = Reload Page
zen-nav-reload-shortcut-skip-cache = Reload Page (Skip Cache)
zen-close-shortcut = Close Window
zen-close-tab-shortcut = Close Tab
zen-compact-mode-shortcut-show-sidebar = Toggle Floating Sidebar
zen-compact-mode-shortcut-show-toolbar = Toggle Floating Toolbar
zen-compact-mode-shortcut-toggle = Toggle Compact Mode
zen-workspace-shortcut-switch-1 = Switch to Workspace 1
zen-workspace-shortcut-switch-2 = Switch to Workspace 2
zen-workspace-shortcut-switch-3 = Switch to Workspace 3
zen-workspace-shortcut-switch-4 = Switch to Workspace 4
zen-workspace-shortcut-switch-5 = Switch to Workspace 5
zen-workspace-shortcut-switch-6 = Switch to Workspace 6
zen-workspace-shortcut-switch-7 = Switch to Workspace 7
zen-workspace-shortcut-switch-8 = Switch to Workspace 8
zen-workspace-shortcut-switch-9 = Switch to Workspace 9
zen-workspace-shortcut-switch-10 = Switch to Workspace 10
zen-workspace-shortcut-forward = Forward Workspace
zen-workspace-shortcut-backward = Backward Workspace
zen-web-panel-shortcut-toggle = Toggle Web Panel
zen-sidebar-shortcut-toggle = Toggle Sidebar's Width
zen-split-view-shortcut-grid = Toggle Split View Grid
zen-split-view-shortcut-vertical = Toggle Split View Vertical
zen-split-view-shortcut-horizontal = Toggle Split View Horizontal
zen-split-view-shortcut-unsplit = Close Split View
zen-key-select-tab-1 = Select tab #1
zen-key-select-tab-2 = Select tab #2
zen-key-select-tab-3 = Select tab #3
zen-key-select-tab-4 = Select tab #4
zen-key-select-tab-5 = Select tab #5
zen-key-select-tab-6 = Select tab #6
zen-key-select-tab-7 = Select tab #7
zen-key-select-tab-8 = Select tab #8
zen-key-select-tab-last = Select last tab
zen-key-show-all-tabs = Show all tabs
zen-key-goto-history = Go to history
zen-key-go-home = Go Home
zen-bookmark-show-sidebar-shortcut = Show Bookmarks Sidebar
zen-bookmark-show-toolbar-shortcut = Show Bookmarks Toolbar
