zen-toolbar-context-tabs-right = 
    .label = Tabs auf der rechten Seite
    .accesskey = R
zen-toolbar-context-compact-mode = 
    .label = Kompaktmodus
    .accesskey = C
zen-toolbar-context-compact-mode-enable = 
    .label = Kompaktmodus aktivieren
    .accesskey = D
zen-toolbar-context-compact-mode-just-tabs = 
    .label = Hide sidebar
zen-toolbar-context-compact-mode-just-toolbar = 
    .label = Hide toolbar
zen-toolbar-context-compact-mode-hide-both = 
    .label = Hide both
    .accesskey = H
sidebar-zen-sidepanel = 
    .label = Side Panels
sidebar-zen-expand = 
    .label = Expand Sidebar
