zen-web-side-panel-context-mute-panel = 
    .label = Web-Panel stummschalten
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = Web-Panel Stummschaltung aufheben
    .accesskey = M
zen-web-side-panel-context-disable-ua = 
    .label = Mobilen Nutzeragenten deaktivieren
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Mobilen Nutzeragenten aktivieren
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = Web-Panel entladen
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = Web-Panel löschen
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = In neuem Tab öffnen
    .accesskey = N
zen-web-side-panel-context-add-to-panel = 
    .label = Zu Web-Panels hinzufügen
    .accesskey = A
zen-sidebar-introduction-title = Willkommen zur Zen-Sidebar
zen-sidebar-introduction-description = Die Zen-Sidebar ist ein neuer Weg, um durch das Internet zu surfen. Klicke auf ein beliebiges Icon, um ein Web-Panel zu öffnen.
