zen-toolbar-context-tabs-right = 
    .label = Tabs auf der rechten Seite
    .accesskey = R
zen-toolbar-context-compact-mode = 
    .label = Kompaktmodus
    .accesskey = C
zen-toolbar-context-compact-mode-enable = 
    .label = Kompaktmodus aktivieren
    .accesskey = D
zen-toolbar-context-compact-mode-just-tabs = 
    .label = Seitenleiste verstecken
zen-toolbar-context-compact-mode-just-toolbar = 
    .label = Werkzeugleiste verstecken
zen-toolbar-context-compact-mode-hide-both = 
    .label = Beide Leisten verstecken
    .accesskey = H
sidebar-zen-sidepanel = 
    .label = Seitenpanele
sidebar-zen-expand = 
    .label = Seitenleiste erweitern
