zen-panel-ui-current-window-text = Aktuelles Fenster
zen-panel-ui-workspaces-text = Andere Arbeitsbereiche
zen-panel-ui-workspaces-create-text = Arbeitsbereich Erstellen
zen-panel-ui-workspaces-create-save = 
    .label = Arbeitsbereich Erstellen
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = Abbrechen
    .accesskey = C
zen-panel-ui-workspaces-edit-text = Edit Workspace
zen-panel-ui-workspaces-edit-save = 
    .label = Save Changes
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Cancel
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Arbeitsbereich Löschen
    .accesskey = D
zen-workspaces-panel-context-open = 
    .label = Arbeitsbereich Öffnen
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Als Standard-Arbeitsbereich festlegen
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Edit Workspace
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Tab(s) zu Arbeitsbereich verschieben
    .accesskey = C
