zen-panel-ui-current-window-text = Aktuelles Fenster
zen-panel-ui-workspaces-text = Andere Arbeitsbereiche
zen-panel-ui-workspaces-create-text = Arbeitsbereich Erstellen
zen-panel-ui-workspaces-create-save = 
    .label = Arbeitsbereich Erstellen
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = Abbrechen
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Arbeitsbereich Löschen
    .accesskey = D
zen-workspaces-panel-context-open = 
    .label = Arbeitsbereich Öffnen
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Als standard Arbeitsbereich festlegen
    .accesskey = S
context-zen-change-workspace-tab = 
    .label = Tab(s) zu Arbeitsbereich verschieben
    .accesskey = C
