zen-web-side-panel-context-mute-panel = 
    .label = Mute Web Panel
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = Unmute Web Panel
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = Disable Mobile UserAgent
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Enable Mobile UserAgent
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = Unload Web Panel
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = Delete Web Panel
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = In neuen Tab öffnen
    .accesskey = N
zen-web-side-panel-context-add-to-panel = 
    .label = Zu Web Panels hinzufügen
    .accesskey = A
zen-sidebar-introduction-title = Willkommen zur Zen Sidebar
zen-sidebar-introduction-description = Die Zen Sidebar ist ein neuer Weg, um durch das Internet zu surfen. Klicke auf ein beliebiges Icon, um ein Web-Panel zu öffnen.
