zen-panel-ui-current-profile-text = Aktuelles Profil
unified-extensions-description = Erweiterungen fügen { -brand-short-name } zusätzliche Funktionen hinzu.
tab-context-zen-reset-pinned-tab = 
    .label = Pinned Tab zurücksetzen
    .accesskey = L
tab-context-zen-replace-pinned-url-with-current = 
    .label = Pinned URL durch aktuelle ersetzen
    .accesskey = C
tab-zen-unload = 
    .label = Unload Tab
    .accesskey = H
zen-tabs-unloader-tab-actions = 
    .label = Tabs Entlader Aktionen
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Tab-Entladen verhindern
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Tab-Entladen erlauben
    .accesskey = I
zen-themes-corrupted = Ihre { -brand-short-name } Mods Datei ist beschädigt. Sie wurden auf das Standard-Template zurückgesetzt.
zen-panel-ui-gradient-generator-opacity-text = Contrast
zen-panel-ui-gradient-generator-texture-text = Textur
zen-panel-ui-gradient-generator-custom-color = Eigene Farbe
zen-panel-ui-gradient-generator-saved-message = Verlauf erfolgreich gespeichert!
