zen-panel-ui-workspaces-text = Arbeitsbereiche
zen-panel-ui-workspaces-create = 
    .label = Create Space
zen-panel-ui-workspaces-edit-text = Arbeitsbereich bearbeiten
zen-panel-ui-workspaces-edit-save = 
    .label = Änderungen speichern
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Abbrechen
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Arbeitsbereich löschen
    .accesskey = D
zen-workspaces-panel-change-name = 
    .label = Name ändern
zen-workspaces-panel-change-icon = 
    .label = Symbol ändern
zen-workspaces-panel-context-manage = 
    .label = Arbeitsbereiche verwalten
    .accesskey = M
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Standard-Container festlegen
    .accesskey = O
zen-workspaces-how-to-reorder = To reorder spaces, drag and drop them from the space icons at the bottom of the sidebar.
zen-workspaces-change-theme = 
    .label = Edit Theme
zen-workspaces-panel-context-open = 
    .label = Arbeitsbereich öffnen
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Als Standard-Arbeitsbereich festlegen
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Arbeitsbereich bearbeiten
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Tab(s) zu Arbeitsbereich verschieben
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Arbeitsbereiche
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Ergänzend
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Geteilt
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Analog
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Triadisch
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Schwebend
zen-panel-ui-gradient-click-to-add = Klicke, um eine Farbe hinzuzufügen
zen-workspace-creation-name = 
    .placeholder = Space Name
zen-workspaces-panel-context-reorder = 
    .label = Reorder Workspaces
zen-workspace-creation-profile = Profile
    .tooltiptext = Profiles are used to separate cookies and site data between spaces.
zen-workspace-creation-title = Create a new Space
zen-workspace-creation-label = Spaces are used to organize your tabs and sessions.
