zen-panel-ui-current-profile-text = Aktuelles Profil
unified-extensions-description = Erweiterungen fügen { -brand-short-name } zusätzliche Funktionen hinzu.
tab-context-zen-reset-pinned-tab = 
    .label = Angepinnten Tab zurücksetzen
    .accesskey = L
tab-context-zen-add-essential = 
    .label = Zu Essentials hinzufügen
    .accesskey = E
tab-context-zen-remove-essential = 
    .label = Von Essentials entfernen
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Angepinnte URL durch aktuelle ersetzen
    .accesskey = C
tab-zen-unload = 
    .label = Tab-Speicher freigeben
    .accesskey = H
zen-tabs-unloader-tab-actions = 
    .label = Tabs Entlader Aktionen
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Tab-Speicherfreigabe verhindern
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Tab-Speicherfreigabe erlauben
    .accesskey = I
zen-themes-corrupted = Ihre { -brand-short-name } Mods Datei ist beschädigt. Sie wurden auf das Standard-Template zurückgesetzt.
zen-shortcuts-corrupted = Deine { -brand-short-name }-Verknüpfungsdatei ist beschädigt. Sie wurde auf die Standard-Verknüpfungen zurückgesetzt.
zen-panel-ui-gradient-generator-opacity-text = Contrast
zen-panel-ui-gradient-generator-texture-text = Textur
zen-panel-ui-gradient-generator-custom-color = Eigene Farbe
zen-panel-ui-gradient-generator-saved-message = Verlauf erfolgreich gespeichert!
zen-copy-current-url-confirmation = Die URL wurde in der Zwischenablage gespeichert.
zen-rice-share-name = 
    .placeholder = Rice Name
zen-rice-share-author = Von
zen-rice-share-author-input = 
    .placeholder = Dein Name
zen-rice-share-cancel = Abbrechen
zen-rice-share-save = Teilen
zen-rice-share-include-userchrome = 
    .label = Nutze Zen Fensterstyle (userChrome.css)
zen-rice-share-include-usercontent = 
    .label = Nutze Webseitestyle (userContent.css)
zen-rice-share-include-mods = 
    .label = Nutze aktivierte Mods
zen-rice-share-include-mod-prefs = 
    .label = Nutze Mod-Einstellungen
zen-rice-share-include-preferences = 
    .label = Nutze Layouteinstellungen
zen-rice-share-include-workspace-themes = 
    .label = Include workspace gradient themes
zen-rice-share-success = Rice erfolgreich erstellt!
zen-rice-share-success-link = Link zum Teilen von Rice
zen-rice-share-accept = Akzeptieren
zen-rice-share-notice = Bevor du teilst, bitte verstehe, was eine Rice ist
# note: Do not translate the "<br/>" tags in the following string
zen-rice-share-notice-description =
    Eine Rice ist eine Sammlung von Anpassungen, die mit anderen geteilt werden kann.
    Dazu gehören deine Fensterstile, Website-Stile, aktivierte Mods, Mod-Einstellungen, Layout-Präferenzen und Arbeitsbereichs-Verlaufsthemen.
    Indem du eine Rice teilst, teilst du all diese Anpassungen mit anderen. Bitte sei achtsam, was du teilst.
zen-learn-more-text = Mehr erfahren
zen-rice-share-include = Exportoptionen
appmenu-zen-share-rice = 
    .label = Zen Rice Teilen
zen-close-label = Schließen
