zen-web-side-panel-context-mute-panel = 
    .label = Desactivar sonido de Panel Web
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = Activar sonido de Panel Web
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = Desactivar Mobile UserAgent
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Activar Mobile UserAgent
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = Hibernar Panel Web
    .accesskey = M
zen-web-side-panel-context-delete = 
    .label = Eliminar Panel Web
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = Abrir en nueva pestaña
    .accesskey = N
zen-web-side-panel-context-open-in-container-tab = 
    .label = Abrir en la pestaña de contenedores
    .accesskey = C
zen-web-side-panel-context-add-to-panel = 
    .label = Añadir a los paneles web
    .accesskey = A
zen-webpanel-introduction-title = Bienvenido a Web Panels de Zen
zen-webpanel-introduction-description = Los Web Panels son una forma de mantener tus sitios web favoritos al alcance de la mano.
