zen-panel-ui-workspaces-text = Espacios de trabajo
zen-panel-ui-workspaces-create-text = Crear espacio de trabajo
zen-panel-ui-workspaces-create-save = 
    .label = Crear espacio de trabajo
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = Cancelar
    .accesskey = C
zen-panel-ui-workspaces-edit-text = Editar espacio de trabajo
zen-panel-ui-workspaces-edit-save = 
    .label = Guardar cambios
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Cancelar
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Eliminar espacio de trabajo
    .accesskey = D
zen-workspaces-panel-context-open = 
    .label = Abrir espacio de trabajo
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Establecer como espacio de trabajo predeterminado
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Editar espacio de trabajo
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Cambiar pestaña(s) a espacio de trabajo
    .accesskey = C
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Establecer contenedor predeterminado
    .accesskey = O
zen-workspaces-change-gradient = 
    .label = Cambiar colores del tema
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Espacios de trabajo
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Complementario
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Dividir
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Análogo
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Triádico
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Variable
