zen-toolbar-context-tabs-right = 
    .label = Pestañas a la derecha
    .accesskey = R
zen-toolbar-context-compact-mode = 
    .label = Modo de pacto
    .accesskey = C
zen-toolbar-context-compact-mode-enable = 
    .label = Activar modo compacto
    .accesskey = D
zen-toolbar-context-compact-mode-just-tabs = 
    .label = Hide sidebar
zen-toolbar-context-compact-mode-just-toolbar = 
    .label = Ocultar barra de herramientas
zen-toolbar-context-compact-mode-hide-both = 
    .label = Ocultar ambos
    .accesskey = D
sidebar-zen-sidepanel = 
    .label = Paneles laterales
sidebar-zen-expand = 
    .label = Expand Sidebar
