zen-panel-ui-current-window-text = Ventana actual
zen-panel-ui-workspaces-text = Otras áreas de trabajo
zen-panel-ui-workspaces-create-text = Crear área de trabajo
zen-panel-ui-workspaces-create-save = 
    .label = Crear área de trabajo
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = Cancelar
    .accesskey = C
zen-panel-ui-workspaces-edit-text = Edit Workspace
zen-panel-ui-workspaces-edit-save = 
    .label = Save Changes
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Cancel
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Eliminar área de trabajo
    .accesskey = D
zen-workspaces-panel-context-open = 
    .label = Abrir área de trabajo
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Establecer como área de trabajo por defecto
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Edit Workspace
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Cambiar pestaña(s) a área de trabajo
    .accesskey = C
