zen-web-side-panel-context-mute-panel = 
    .label = Silenciar panel web
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = Desilenciar panel web
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = Deshabilitar agente de usuario móvil
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Habilitar agente de usuario móvil
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = Descargar panel web
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = Eliminar panel web
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = Abrir en nueva pestaña
    .accesskey = N
zen-web-side-panel-context-add-to-panel = 
    .label = Agregar a paneles web
    .accesskey = A
zen-sidebar-introduction-title = Bienvenido a Zen Sidebar
zen-sidebar-introduction-description = Zen Sidebar es una nueva forma de navegar la web. Clickea en cualquiera de los íconos para abrir un panel web.
