zen-panel-ui-current-profile-text = perfil actual
unified-extensions-description = Las extensiones se utilizan para agregar más funcionalidades a { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = Restablecer Pestaña Anclada
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Reemplazar URL Anclada con la URL Actual
    .accesskey = C
tab-zen-unload = 
    .label = Hibernar Pestaña
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Acciones de la Hibernación de Pestañas
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Prevenir Hibernación de Pestaña
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Permitir Hibernación de Pestaña
    .accesskey = I
zen-themes-corrupted = Your { -brand-short-name } mods file is corrupted. They have been reset to the default theme.
