zen-panel-ui-current-profile-text = perfil actual
unified-extensions-description = Las extensiones se utilizan para aportar más funcionalidad extra a { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = Reiniciar pestaña fijada
    .accesskey = R
tab-context-zen-add-essential = 
    .label = Agregar a esenciales
    .accesskey = E
tab-context-zen-remove-essential = 
    .label = Remover de esenciales
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Reemplazar URL Fijada con la actual
    .accesskey = C
tab-zen-unload = 
    .label = Hibernar Pestaña
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Acciones de la Hibernación de Pestañas
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Prevenir Hibernación de Pestaña
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Permitir Hibernación de Pestaña
    .accesskey = I
zen-themes-corrupted = Su archivo de mods de { -brand-short-name } está corrupto. Se ha restablecido el tema por defecto.
zen-panel-ui-gradient-generator-opacity-text = Contraste
zen-panel-ui-gradient-generator-texture-text = Textura
zen-panel-ui-gradient-generator-custom-color = Color personalizado
zen-panel-ui-gradient-generator-saved-message = ¡Gradiente guardado con éxito!
zen-copy-current-url-confirmation = La URL se ha copiado al portapapeles.
zen-rice-share-name = 
    .placeholder = Nombre del Rice
zen-rice-share-author = Por
zen-rice-share-author-input = 
    .placeholder = Tu nombre
zen-rice-share-cancel = Cancelar
zen-rice-share-save = Compartir
zen-rice-share-include-userchrome = 
    .label = Incluir estilos de ventana zen (userChrome.css)
zen-rice-share-include-usercontent = 
    .label = Incluir estilos de sitio web (userChrome.css)
zen-rice-share-include-mods = 
    .label = Incluir mods habilitados
zen-rice-share-include-mod-prefs = 
    .label = Incluir preferencias de mods
zen-rice-share-include-preferences = 
    .label = Incluir preferencias de diseño
zen-rice-share-include-workspace-themes = 
    .label = Incluir temas de degradado del espacio de trabajo
zen-rice-share-success = ¡Se ha creado con éxito un Rice!
zen-rice-share-success-link = Enlace para compartir el Rice
zen-rice-share-accept = Aceptar
zen-rice-share-notice = Antes de compartirlo, entiende qué es un Rice
# note: Do not translate the "<br/>" tags in the following string
zen-rice-share-notice-description =
    A Rice is a collection of customizations that can be shared with others.<br/>
    This includes your window styles, website styles, enabled mods, mod preferences, layout preferences, and workspace gradient themes.<br/>
    By sharing a Rice, you are sharing all of these customizations with others. Please be mindful of what you share.
zen-learn-more-text = Más información
zen-rice-share-include = Exportar opciones
appmenu-zen-share-rice = 
    .label = Compartir Zen Rice
zen-close-label = Cerrar
