zen-toolbar-context-tabs-right = 
    .label = Pestañas a la derecha
    .accesskey = R
zen-toolbar-context-compact-mode = 
    .label = Modo compacto
    .accesskey = C
zen-toolbar-context-compact-mode-enable = 
    .label = Activar modo compacto
    .accesskey = D
zen-toolbar-context-compact-mode-just-tabs = 
    .label = Ocultar barra lateral
zen-toolbar-context-compact-mode-just-toolbar = 
    .label = Ocultar barra de herramientas
zen-toolbar-context-compact-mode-hide-both = 
    .label = Ocultar ambas
    .accesskey = H
sidebar-zen-sidepanel = 
    .label = Paneles Laterales
sidebar-zen-expand = 
    .label = Expandir Barra Lateral
