pane-zen-looks-title = Vzhled a dojem
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Změna výchozího jazyka může usnadnit stránkám vás sledovat.
zen-look-and-feel-colors-header = Vyberte barvu motivu
zen-look-and-feel-colors-description = Přizpůsobte si { -brand-short-name } dle vašich preferencí
zen-look-and-feel-themed-toolbar = 
    .label = Vytvořte motiv panelu nástrojů s kontrastní barvou
pane-zen-side-panels-title = Webové panely stránky
zen-side-panels-header = Základní nastavení pro webové panely
zen-side-panels-description = Vylepšete produktivitu s více zobrazeními najednou!
zen-side-panels-enabled = 
    .label = Povolte boční webové panely
zen-side-panels-close-on-blur = 
    .label = Zavři panel, pokud ztratí pozornost a není připnutý
zen-look-and-feel-compact-view-header = Zobrazit v kompaktním režimu
zen-look-and-feel-compact-view-description = Zobrazte pouze panely nástrojů, které používáte!
zen-look-and-feel-compact-view-enabled = 
    .label = Povolit { -brand-short-name } kompaktní režim
zen-look-and-feel-compact-view-top-toolbar = 
    .label = V kompaktním režimu schovat také horní panel nástrojů
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Briefly make the toolbar popup when switching or opening new tabs in compact mode
zen-look-and-feel-buttons-header = Styl tlačítek
zen-look-and-feel-buttons-description = Vyberte si styl tlačítek, který chcete vidět
zen-look-and-feel-pilled-buttons = 
    .label = Plněná tlačítka
pane-zen-workspaces-title = Pracoviště
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = Pracoviště
pane-zen-workspaces-header = Pracoviště
zen-settings-workspaces-header = Základní nastavení pro pracoviště
zen-settings-workspaces-description = S pracovišti můžete mít více sezení procházení najednou!
zen-settings-workspaces-enabled = 
    .label = Povolit pracovište (Experimentální)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Hide the default container indicator in the tab bar
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Allow workspaces have their own pinned tabs
pane-zen-theme-title = Nastavení motivu
zen-vertical-tabs-title = Boční panel a rozložení karet
zen-vertical-tabs-header = Vertikální karty
zen-vertical-tabs-description = Spravujte vaše karty ve vertikálním rozložení
zen-vertical-tabs-show-expand-button = 
    .label = Zobrazit tlačítko zvětšení
zen-vertical-tabs-expand-tabs-by-default = Zvětšovat karty ve výchozím nastavení
zen-vertical-tabs-dont-expand-tabs-by-default = Nezvětšovat karty ve výchozím nastavení
zen-vertical-tabs-expand-tabs-on-hover = Zvětšit karty na najetí myší (Nebude fungovat v kompaktním režimu)
zen-vertical-tabs-expand-tabs-header = Jak zvětšit karty
zen-vertical-tabs-expand-tabs-description = Vyberte si, jak zvětšit karty v bočním panelu
zen-theme-marketplace-header = Zen Mods
zen-theme-marketplace-description = Najít a instalovat motivy z obchodu.
zen-theme-marketplace-remove-button = 
    .label = Odebrat motiv
zen-theme-marketplace-check-for-updates-button = 
    .label = Zkontrolovat dostupné aktualizace
zen-theme-marketplace-updates-success = Motiv úspěšně aktualizován
zen-theme-marketplace-updates-fail = Nebyly nalezeny žádné aktualizace!
zen-theme-marketplace-toggle-enabled-button = 
    .title = Disable Theme
zen-theme-marketplace-toggle-disabled-button = 
    .title = Enable Theme
zen-theme-marketplace-remove-confirmation = Are you sure you want to remove this mod?
zen-theme-marketplace-close-modal = Close
zen-theme-marketplace-theme-header-title = 
    .title = CSS Selector: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = None
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Type something...
pane-zen-marketplace-title = Zen Mods
zen-settings-workspaces-display-as-icon-strip = 
    .label = Display workspaces as an icon strip
zen-theme-marketplace-link = Navštívit obchod
zen-dark-theme-styles-header = Dark Theme Styles
zen-dark-theme-styles-description = Customize the dark theme to your liking
zen-dark-theme-styles-amoled = Night Theme
zen-dark-theme-styles-default = Default Dark Theme
zen-dark-theme-styles-colorful = Colorful Dark Theme
zen-compact-mode-styles-left = Hide Tab bar
zen-compact-mode-styles-top = Hide Top bar
zen-compact-mode-styles-both = Hide Both
pane-zen-CKS-title = Klávesové zkratky
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = Klávesové zkratky { -brand-short-name }
zen-settings-CKS-header = Přizpůsobte si klávesové zkratky
zen-settings-CKS-description = Změňte si výchozí klávesové zkratky dle vašich preferencí a vylepšete si zážitek z prohlížení
zen-settings-CKS-disable-firefox = 
    .label = Vypnout výchozí { -brand-short-name } klávesové zkratky
zen-settings-CKS-duplicate-shortcut = 
    .label = Duplicate Shortcut
zenCKSOption-group-other = Other
zenCKSOption-group-windowAndTabManagement = Window & Tab Management
zenCKSOption-group-navigation = Navigation
zenCKSOption-group-searchAndFind = Search & Find
zenCKSOption-group-pageOperations = Page Operations
zenCKSOption-group-historyAndBookmarks = History & Bookmarks
zenCKSOption-group-mediaAndDisplay = Media & Display
zenCKSOption-group-zen-compact-mode = Compact Mode
zenCKSOption-group-zen-workspace = Workspaces
zenCKSOption-group-zen-other = Other Zen Features
zenCKSOption-group-zen-split-view = Split View
zen-key-quick-restart = Quick Restart
zen-window-new-shortcut = New Window
zen-tab-new-shortcut = New Tab
zen-location-open-shortcut = Open Location
zen-location-open-shortcut-alt = Open Location (Alt)
zen-search-focus-shortcut = Focus Search
zen-search-focus-shortcut-alt = Focus Search (Alt)
zen-downloads-shortcut = Open Downloads
zen-addons-shortcut = Open Add-ons
zen-file-open-shortcut = Open File
zen-save-page-shortcut = Save Page
zen-print-shortcut = Print Page
zen-close-shortcut-2 = Close Tab
zen-mute-toggle-shortcut = Toggle Mute
zen-key-delete = Delete Key
zen-key-go-back = Go Back
zen-key-go-forward = Go Forward
zen-nav-back-shortcut-alt = Navigate Back (Alt)
zen-nav-fwd-shortcut-alt = Navigate Forward (Alt)
zen-history-show-all-shortcut = Show All History
zen-key-enter-full-screen = Enter Full Screen
zen-key-exit-full-screen = Exit Full Screen
zen-reader-mode-toggle-shortcut-other = Toggle Reader Mode
zen-picture-in-picture-toggle-shortcut = Toggle Picture-in-Picture
zen-nav-reload-shortcut-2 = Reload Page
zen-key-about-processes = About Processes
zen-page-source-shortcut = View Page Source
zen-page-info-shortcut = View Page Info
zen-find-shortcut = Find on Page
zen-search-find-again-shortcut = Find Again
zen-search-find-again-shortcut-prev = Find Previous
zen-search-find-again-shortcut-2 = Find Again (Alt)
zen-bookmark-this-page-shortcut = Bookmark This Page
zen-bookmark-show-library-shortcut = Show Bookmarks Library
zen-key-stop = Stop Loading
zen-full-zoom-reduce-shortcut = Zoom Out
zen-full-zoom-enlarge-shortcut = Zoom In
zen-full-zoom-reset-shortcut = Reset Zoom
zen-bidi-switch-direction-shortcut = Switch Text Direction
zen-private-browsing-shortcut = Private Browsing
zen-screenshot-shortcut = Take Screenshot
zen-key-sanitize = Clear Browsing Data
zen-quit-app-shortcut = Quit Application
zen-key-wr-capture-cmd = WR Capture Command
zen-key-wr-toggle-capture-sequence-cmd = Toggle WR Capture Sequence
zen-nav-reload-shortcut = Reload Page
zen-nav-reload-shortcut-skip-cache = Reload Page (Skip Cache)
zen-close-shortcut = Close Window
zen-close-tab-shortcut = Close Tab
zen-compact-mode-shortcut-show-sidebar = Toggle Floating Sidebar
zen-compact-mode-shortcut-show-toolbar = Toggle Floating Toolbar
zen-compact-mode-shortcut-toggle = Toggle Compact Mode
zen-workspace-shortcut-switch-1 = Switch to Workspace 1
zen-workspace-shortcut-switch-2 = Switch to Workspace 2
zen-workspace-shortcut-switch-3 = Switch to Workspace 3
zen-workspace-shortcut-switch-4 = Switch to Workspace 4
zen-workspace-shortcut-switch-5 = Switch to Workspace 5
zen-workspace-shortcut-switch-6 = Switch to Workspace 6
zen-workspace-shortcut-switch-7 = Switch to Workspace 7
zen-workspace-shortcut-switch-8 = Switch to Workspace 8
zen-workspace-shortcut-switch-9 = Switch to Workspace 9
zen-workspace-shortcut-switch-10 = Switch to Workspace 10
zen-workspace-shortcut-forward = Forward Workspace
zen-workspace-shortcut-backward = Backward Workspace
zen-web-panel-shortcut-toggle = Toggle Web Panel
zen-sidebar-shortcut-toggle = Toggle Sidebar's Width
zen-split-view-shortcut-grid = Toggle Split View Grid
zen-split-view-shortcut-vertical = Toggle Split View Vertical
zen-split-view-shortcut-horizontal = Toggle Split View Horizontal
zen-split-view-shortcut-unsplit = Close Split View
