pane-zen-looks-title = Vzhled a dojem
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Změna výchozího jazyka může usnadnit stránkám vás sledovat.
zen-look-and-feel-colors-header = Vyberte barvu motivu
zen-look-and-feel-colors-description = Přizpůsobte si { -brand-short-name } dle vašich preferencí
zen-look-and-feel-themed-toolbar = 
    .label = Vytvořte motiv panelu nástrojů s kontrastní barvou
pane-zen-side-panels-title = Webové panely stránky
zen-side-panels-header = Základní nastavení pro webové panely
zen-side-panels-description = Vylepšete produktivitu s více zobrazeními najednou!
zen-side-panels-enabled = 
    .label = Povolte boční webové panely
zen-side-panels-close-on-blur = 
    .label = Zavři panel, pokud ztratí pozornost a není připnutý
zen-vertical-tabs-show-bottom-border = 
    .label = Show border for the bottom icons
sync-currently-syncing-workspaces = Workspaces
sync-engine-workspaces = 
    .label = Workspaces
    .tooltiptext = Sync your workspaces across devices
    .accesskey = W
zen-look-and-feel-compact-view-header = Zobrazit v kompaktním režimu
zen-look-and-feel-compact-view-description = Zobrazte pouze panely nástrojů, které používáte!
zen-look-and-feel-compact-view-enabled = 
    .label = Povolit { -brand-short-name } kompaktní režim
zen-look-and-feel-compact-view-top-toolbar = 
    .label = V kompaktním režimu schovat také horní panel nástrojů
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Briefly make the toolbar popup when switching or opening new tabs in compact mode
zen-look-and-feel-buttons-header = Styl tlačítek
zen-look-and-feel-buttons-description = Vyberte si styl tlačítek, který chcete vidět
zen-look-and-feel-pilled-buttons = 
    .label = Plněná tlačítka
pane-zen-tabs-title = Tab Management
category-zen-workspaces = 
    .tooltiptext = { pane-zen-tabs-title }
pane-settings-workspaces-title = Pracoviště
pane-zen-tabs-unloader-title = Tab Unloader
zen-tabs-unloader-header = General settings for tab unloader
zen-tabs-unloader-description = Automatically unload unused tabs to save memory
zen-tabs-unloader-enabled = 
    .label = Enable Tab Unloader
zen-tabs-unloader-unload-delay = 
    .label = Unload tabs after
zen-tabs-unloader-unload-delay-description = The time in minutes after which tabs will be unloaded
pane-zen-workspaces-header = Pracoviště
zen-settings-workspaces-header = Základní nastavení pro pracoviště
zen-settings-workspaces-description = S pracovišti můžete mít více sezení procházení najednou!
zen-settings-workspaces-enabled = 
    .label = Povolit pracoviště (experimentální)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Skrýt výchozí indikátor kójí na webovém panelu
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Povolit pro pracoviště vlastní připnuté karty
zen-key-unsafed = Unsaved shortcut! Please safe it by clicking the "Escape" key after retyping it.
zen-key-conflict = Conflict with another shortcut
pane-zen-theme-title = Nastavení motivu
zen-vertical-tabs-title = Boční panel a rozložení karet
zen-vertical-tabs-header = Vertikální karty
zen-vertical-tabs-description = Spravujte vaše karty ve vertikálním rozložení
zen-vertical-tabs-show-expand-button = 
    .label = Zobrazit tlačítko zvětšení
zen-vertical-tabs-expand-tabs-by-default = Zvětšovat karty ve výchozím nastavení
zen-vertical-tabs-dont-expand-tabs-by-default = Nezvětšovat karty ve výchozím nastavení
zen-vertical-tabs-expand-tabs-on-hover = Zvětšit karty na najetí myší (Nebude fungovat v kompaktním režimu)
zen-vertical-tabs-expand-tabs-header = Jak zvětšit karty
zen-vertical-tabs-expand-tabs-description = Vyberte si, jak zvětšit karty v bočním panelu
zen-theme-marketplace-header = Zen Mody
zen-theme-marketplace-description = Najít a instalovat motivy z obchodu.
zen-theme-marketplace-remove-button = 
    .label = Odebrat motiv
zen-theme-marketplace-check-for-updates-button = 
    .label = Zkontrolovat dostupné aktualizace
zen-theme-marketplace-updates-success = Motiv úspěšně aktualizován
zen-theme-marketplace-updates-fail = Nebyly nalezeny žádné aktualizace!
zen-theme-marketplace-toggle-enabled-button = 
    .title = Zakázat motiv
zen-theme-marketplace-toggle-disabled-button = 
    .title = Povolit motiv
zen-theme-marketplace-remove-confirmation = Opravdu chcete odstranit tento mod?
zen-theme-marketplace-close-modal = Zavřít
zen-theme-marketplace-theme-header-title = 
    .title = CSS Selector: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = Žádný
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Napište něco...
pane-zen-marketplace-title = Zen Mody
zen-settings-workspaces-display-as-icon-strip = 
    .label = Zobrazit pracoviště jako proužek s ikonou
zen-theme-marketplace-link = Navštívit obchod
zen-dark-theme-styles-header = Tmavé motivy
zen-dark-theme-styles-description = Přizpůsobte si tmavý motiv, jak vám hrdlo ráčí
zen-dark-theme-styles-amoled = Noční motiv
zen-dark-theme-styles-default = Výchozí tmavý motiv
zen-dark-theme-styles-colorful = Barevný tmavý motiv
zen-split-view-title = Split View
zen-split-view-header = Split View Functionality
zen-split-view-description = Split your browser into multiple views, enabling you to browse multiple websites at once
zen-split-view-change-on-hover = 
    .label = Change tabs on hover
zen-compact-mode-styles-left = Skrýt panel karet
zen-compact-mode-styles-top = Skrýt horní panel
zen-compact-mode-styles-both = Skrýt obojí
pane-zen-CKS-title = Klávesové zkratky
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = Klávesové zkratky { -brand-short-name }
zen-settings-CKS-header = Přizpůsobte si klávesové zkratky
zen-settings-CKS-description = Změňte si výchozí klávesové zkratky dle vašich preferencí a vylepšete si zážitek z prohlížení
zen-settings-CKS-disable-firefox = 
    .label = Vypnout výchozí { -brand-short-name } klávesové zkratky
zen-settings-CKS-duplicate-shortcut = 
    .label = Duplicate Shortcut
zen-settings-CKS-reset-shortcuts = 
    .label = Reset to Default
zenCKSOption-group-other = Other
zenCKSOption-group-windowAndTabManagement = Správa oken a karet
zenCKSOption-group-navigation = Navigace
zenCKSOption-group-searchAndFind = Najít
zenCKSOption-group-pageOperations = Page Operations
zenCKSOption-group-historyAndBookmarks = Historie a záložky
zenCKSOption-group-mediaAndDisplay = Média a zobrazení
zenCKSOption-group-zen-compact-mode = Kompaktní režim
zenCKSOption-group-zen-workspace = Pracoviště
zenCKSOption-group-zen-other = Ostatní funkce Zenu
zenCKSOption-group-zen-split-view = Rozdělený režim
zen-key-quick-restart = Rychlý restart
zen-window-new-shortcut = Nové okno
zen-tab-new-shortcut = Nová karta
zen-key-redo = Redo
zen-restore-last-closed-tab-shortcut = Restore Last Closed Tab
zen-location-open-shortcut = Otevřít umístění
zen-location-open-shortcut-alt = Otevřít umístění (alt)
zen-key-undo-close-window = Zpět zavřít okno
zen-text-action-undo-shortcut = Zpět
zen-text-action-redo-shortcut = Znovu
zen-text-action-cut-shortcut = Vyjmout
zen-text-action-copy-shortcut = Kopírovat
zen-text-action-paste-shortcut = Vložit
zen-text-action-select-all-shortcut = Vybrat vše
zen-text-action-delete-shortcut = Odstranit
zen-history-show-all-shortcut-mac = Zobrazit všechno historii (Mac)
zen-full-screen-shortcut = Povolit režim celé obrazovky
zen-reader-mode-toggle-shortcut-windows = Toggle Reader Mode (Windows)
zen-picture-in-picture-toggle-shortcut-alt = Toggle Picture-in-Picture (Alt)
zen-picture-in-picture-toggle-shortcut-mac = Toggle Picture-in-Picture (Mac)
zen-picture-in-picture-toggle-shortcut-mac-alt = Toggle Picture-in-Picture (Mac Alt)
zen-page-source-shortcut-safari = View Page Source (Safari)
zen-nav-stop-shortcut = Stop Loading
zen-history-sidebar-shortcut = Show History Sidebar
zen-window-minimize-shortcut = Minimize Window
zen-help-shortcut = Open Help
zen-preferences-shortcut = Open Preferences
zen-hide-app-shortcut = Hide Application
zen-hide-other-apps-shortcut = Hide Other Applications
zen-search-focus-shortcut = Focus Search
zen-search-focus-shortcut-alt = Focus Search (Alt)
zen-downloads-shortcut = Otevřít stažené
zen-addons-shortcut = Otevřít doplňky
zen-file-open-shortcut = Otevřít soubor
zen-save-page-shortcut = Save Page
zen-print-shortcut = Print Page
zen-close-shortcut-2 = Close Tab
zen-mute-toggle-shortcut = Toggle Mute
zen-key-delete = Delete Key
zen-key-go-back = Jít zpět
zen-key-go-forward = Go Forward
zen-nav-back-shortcut-alt = Navigate Back (Alt)
zen-nav-fwd-shortcut-alt = Navigate Forward (Alt)
zen-history-show-all-shortcut = Show All History
zen-key-enter-full-screen = Enter Full Screen
zen-key-exit-full-screen = Exit Full Screen
zen-reader-mode-toggle-shortcut-other = Toggle Reader Mode
zen-picture-in-picture-toggle-shortcut = Toggle Picture-in-Picture
zen-nav-reload-shortcut-2 = Reload Page
zen-key-about-processes = About Processes
zen-page-source-shortcut = View Page Source
zen-page-info-shortcut = View Page Info
zen-find-shortcut = Find on Page
zen-search-find-again-shortcut = Find Again
zen-search-find-again-shortcut-prev = Find Previous
zen-search-find-again-shortcut-2 = Find Again (Alt)
zen-bookmark-this-page-shortcut = Bookmark This Page
zen-bookmark-show-library-shortcut = Show Bookmarks Library
zen-key-stop = Stop Loading
zen-full-zoom-reduce-shortcut = Zoom Out
zen-full-zoom-enlarge-shortcut = Zoom In
zen-full-zoom-reset-shortcut = Reset Zoom
zen-bidi-switch-direction-shortcut = Switch Text Direction
zen-private-browsing-shortcut = Private Browsing
zen-screenshot-shortcut = Take Screenshot
zen-key-sanitize = Clear Browsing Data
zen-quit-app-shortcut = Quit Application
zen-key-wr-capture-cmd = WR Capture Command
zen-key-wr-toggle-capture-sequence-cmd = Toggle WR Capture Sequence
zen-nav-reload-shortcut = Reload Page
zen-nav-reload-shortcut-skip-cache = Reload Page (Skip Cache)
zen-close-shortcut = Zavřít okno
zen-close-tab-shortcut = Close Tab
zen-compact-mode-shortcut-show-sidebar = Toggle Floating Sidebar
zen-compact-mode-shortcut-show-toolbar = Toggle Floating Toolbar
zen-compact-mode-shortcut-toggle = Toggle Compact Mode
zen-workspace-shortcut-switch-1 = Switch to Workspace 1
zen-workspace-shortcut-switch-2 = Switch to Workspace 2
zen-workspace-shortcut-switch-3 = Switch to Workspace 3
zen-workspace-shortcut-switch-4 = Switch to Workspace 4
zen-workspace-shortcut-switch-5 = Switch to Workspace 5
zen-workspace-shortcut-switch-6 = Switch to Workspace 6
zen-workspace-shortcut-switch-7 = Switch to Workspace 7
zen-workspace-shortcut-switch-8 = Switch to Workspace 8
zen-workspace-shortcut-switch-9 = Switch to Workspace 9
zen-workspace-shortcut-switch-10 = Switch to Workspace 10
zen-workspace-shortcut-forward = Forward Workspace
zen-workspace-shortcut-backward = Backward Workspace
zen-web-panel-shortcut-toggle = Toggle Web Panel
zen-sidebar-shortcut-toggle = Toggle Sidebar's Width
zen-split-view-shortcut-grid = Toggle Split View Grid
zen-split-view-shortcut-vertical = Toggle Split View Vertical
zen-split-view-shortcut-horizontal = Toggle Split View Horizontal
zen-split-view-shortcut-unsplit = Close Split View
zen-key-select-tab-1 = Vybrat kartu č.1
zen-key-select-tab-2 = Vybrat kartu č.2
zen-key-select-tab-3 = Vybrat kartu č.3
zen-key-select-tab-4 = Vybrat kartu č.4
zen-key-select-tab-5 = Vybrat kartu č.5
zen-key-select-tab-6 = Vybrat kartu č.6
zen-key-select-tab-7 = Vybrat kartu č.7
zen-key-select-tab-8 = Vybrat kartu č.8
zen-key-select-tab-last = Select last tab
zen-key-show-all-tabs = Show all tabs
zen-key-goto-history = Go to history
zen-key-go-home = Go Home
zen-bookmark-show-sidebar-shortcut = Show Bookmarks Sidebar
zen-bookmark-show-toolbar-shortcut = Show Bookmarks Toolbar
