pane-zen-looks-title = Vzhled a dojem
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Změna výchozího jazyka může usnadnit stránkám vás sledovat.
zen-look-and-feel-colors-header = Vyberte barvu motivu
zen-look-and-feel-colors-description = Přizpůsobte si { -brand-short-name } dle vašich preferencí
zen-look-and-feel-themed-toolbar = 
    .label = Vytvořte motiv panelu nástrojů s kontrastní barvou
pane-zen-side-panels-title = Side Web Panels
zen-side-panels-header = General settings for web panels
zen-side-panels-description = Vylepšete produktivitu s více zobrazeními najednou!
zen-side-panels-enabled = 
    .label = Povolte boční webové panely
zen-side-panels-close-on-blur = 
    .label = Zavři panel, pokud ztratí pozornost a není připnutý
zen-look-and-feel-compact-view-header = Zobrazit v kompaktním režimu
zen-look-and-feel-compact-view-description = Zobrazte pouze panely nástrojů, které používáte!
zen-look-and-feel-compact-view-enabled = 
    .label = Povolit { -brand-short-name } kompaktní režim
zen-look-and-feel-compact-view-top-toolbar = 
    .label = V kompaktním režimu schovat také horní panel nástrojů
zen-look-and-feel-buttons-header = Styl tlačítek
zen-look-and-feel-buttons-description = Vyberte si styl tlačítek, který chcete vidět
zen-look-and-feel-pilled-buttons = 
    .label = Plněná tlačítka
pane-zen-workspaces-title = Pracovní prostory
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = Pracovní prostory
pane-zen-workspaces-header = Workspaces
zen-settings-workspaces-header = Základní nastavení pro pracovní prostory
zen-settings-workspaces-description = S pracovními prostory můžete mít více sezení procházení najednou!
zen-settings-workspaces-enabled = 
    .label = Povolit pracovní prostory (Experimentální)
pane-zen-theme-title = Nastavení motivu
zen-vertical-tabs-title = Boční panel a rozložení karet
zen-vertical-tabs-header = Vertikální karty
zen-vertical-tabs-description = Spravujte vaše karty ve vertikálním rozložení
zen-vertical-tabs-show-expand-button = 
    .label = Zobrazit tlačítko zvětšení
zen-vertical-tabs-expand-tabs-by-default = Zvětšovat karty ve výchozím nastavení
zen-vertical-tabs-dont-expand-tabs-by-default = Nezvětšovat karty ve výchozím nastavení
zen-vertical-tabs-expand-tabs-on-hover = Zvětšit karty na najetí myší (Nebude fungovat v kompaktním režimu)
zen-vertical-tabs-expand-tabs-header = Jak zvětšit karty
zen-vertical-tabs-expand-tabs-description = Vyberte si, jak zvětšit karty v bočním panelu
zen-theme-marketplace-header = Obchod motivů
zen-theme-marketplace-description = Najít a instalovat motivy z obchodu.
zen-theme-marketplace-remove-button = 
    .label = Odebrat motiv
zen-theme-marketplace-check-for-updates-button = 
    .label = Zkontrolovat dostupné aktualizace
zen-theme-marketplace-updates-success = Theme updated successfully
zen-theme-marketplace-updates-fail = Coudn't find any updates!
pane-zen-marketplace-title = Theme Store
zen-theme-marketplace-link = Navštívit obchod
pane-zen-CKS-title = Klávesové zkratky
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = Klávesové zkratky { -brand-short-name }
zen-settings-CKS-header = Přizpůsobte si klávesové zkratky
zen-settings-CKS-description = Změntě si výchozí klávesové zkratky dle vašich preferencí a vylepšete si zážitek z prohlížení
zen-settings-CKS-disable-firefox = 
    .label = Vypnout výchozí { -brand-short-name } klávesové zkratky
zen-cks-group-tab-action = Akce karet
zen-cks-group-page-action = Akce stránek
zen-cks-group-visible-action = Viditelné akce
zen-cks-group-history-action = Historické akce
zen-cks-group-search-action = Search Actions
zen-cks-group-tools-action = Tools Actions
zen-cks-group-bookmark-action = Bookmark Actions
zen-cks-group-open-page-action = Open Page Actions
zen-cks-group-downloads-action = Downloads Actions
zen-cks-group-sidebar-action = Sidebar Actions
zen-cks-group-compact-mode-action = Compact Mode Actions
zen-cks-group-split-view-action = Split View Actions
zen-cks-group-workspace-action = Workspace Actions
open-new-tab = Open New Tab
close-tab = Close Tab
open-new-window = Open New Window
open-new-private-window = Open New Private Window
close-window = Close Window
restore-last-tab = Restore Last Tab
restore-last-window = Restore Last Window
show-next-tab = Show Next Tab
show-previous-tab = Show Previous Tab
show-all-tabs-panel = Show All Tabs Panel
send-with-mail = Send Page with Mail
save-page = Save Page
print-page = Print Page
mute-current-tab = Mute Current Tab
show-source-of-page = Show Source of Page
show-page-info = Show Page Info
zoom-in = Zoom In
zoom-out = Zoom Out
reset-zoom = Reset Zoom
back = Back
forward = Forward
stop = Stop
reload = Reload
force-reload = Force Reload
search-in-this-page = Search in This Page
show-next-search-result = Show Next Search Result
show-previous-search-result = Show Previous Search Result
search-the-web = Search the Web
open-migration-wizard = Open Migration Wizard
quit-from-application = Quit Application
enter-into-customize-mode = Enter Customize Mode
enter-into-offline-mode = Enter Offline Mode
open-screen-capture = Open Screen Capture
bookmark-this-page = Bookmark This Page
open-bookmark-add-tool = Open Bookmark Add Tool
open-bookmarks-manager = Open Bookmarks Manager
toggle-bookmark-toolbar = Toggle Bookmark Toolbar
open-general-preferences = Open General Preferences
open-privacy-preferences = Open Privacy Preferences
open-workspaces-preferences = Open Workspaces Preferences
open-containers-preferences = Open Containers Preferences
open-search-preferences = Open Search Preferences
open-sync-preferences = Open Sync Preferences
open-task-manager = Open Task Manager
open-addons-manager = Open Add-ons Manager
open-home-page = Open Home Page
forget-history = Forget History
quick-forget-history = Quick Forget History
clear-recent-history = Clear Recent History
restore-last-session = Restore Last Session
search-history = Search History
manage-history = Manage History
open-downloads = Open Downloads
show-bookmark-sidebar = Show Bookmark Sidebar
show-history-sidebar = Show History Sidebar
show-synced-tabs-sidebar = Show Synced Tabs Sidebar
reverse-sidebar = Reverse Sidebar Position
hide-sidebar = Hide Sidebar
toggle-sidebar = Toggle Sidebar
zen-toggle-web-panels = Toggle Web Panels
zen-toggle-compact-mode = Toggle Compact Mode
zen-toggle-compact-mode-sidebar = Toggle Compact Mode Sidebar
zen-toggle-compact-mode-toolbar = Toggle Compact Mode Toolbar
zen-change-workspace = Cycle Workspaces
zen-split-view-grid = Split View Grid
zen-split-view-vertical = Split View Vertical
zen-split-view-horizontal = Split View Horizontal
zen-split-view-close = Close Split View
