zen-web-side-panel-context-mute-panel = 
    .label = Web panel némítása
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = Web panel némításának feloldása
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = Telefonos UserAgent kikapcsolása
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Telefonos UserAgent bekapcsolása
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = Web panel ürítése
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = Web panel törlése
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = Megnyitás új lapon
    .accesskey = N
zen-web-side-panel-context-open-in-container-tab = 
    .label = Megnyitás konténer lapon
    .accesskey = C
zen-web-side-panel-context-add-to-panel = 
    .label = Hozzáadás a web panelek közé
    .accesskey = A
zen-webpanel-introduction-title = Üdvözöljük a Zen web paneleknél
zen-webpanel-introduction-description = A webpanelek segítségével kedvenc webhelyeit mindig kéznél tarthatja.
