zen-panel-ui-workspaces-text = Más munkakörnyezetek
zen-panel-ui-workspaces-create = 
    .label = Create Space
zen-panel-ui-workspaces-edit-text = Munkakörnyezet módosítása
zen-panel-ui-workspaces-edit-save = 
    .label = Beállítások mentése
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Mégsem
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Munkakörnyezet törlése
    .accesskey = D
zen-workspaces-panel-change-name = 
    .label = Átnevezés
zen-workspaces-panel-change-icon = 
    .label = Ikon módosítása
zen-workspaces-panel-context-manage = 
    .label = Munkakörnyezetek kezelése
    .accesskey = M
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Alapértelmezett konténer beállítása
    .accesskey = O
zen-workspaces-change-theme = 
    .label = Edit Theme
zen-workspaces-panel-context-open = 
    .label = Munkakörnyezet megnyitása
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Beállítás alapértelmezett munkakörnyezetnek
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Munkakörnyezet módosítása
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Lap(ok) mozgatása munkakörnyezetbe
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Munkakörnyezetek
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Komplementer
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Szétválasztás
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Analóg
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Triád
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Lebegő
zen-panel-ui-gradient-click-to-add = Kattintson egy szín hozzáadásához
zen-workspace-creation-name = 
    .placeholder = Space Name
zen-workspace-creation-profile = Profile
    .tooltiptext = Profiles are used to separate cookies and site data between spaces.
zen-workspace-creation-title = Create a new Space
zen-workspace-creation-label = Spaces are used to organize your tabs and sessions.
