zen-web-side-panel-context-mute-panel = 
    .label = Web Panel Némítása
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = Web Panel Némításának Feloldása
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = Mobilos UserAgent Kikapcsolása
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Mobilos UserAgent Bekapcsolása
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = Web Panel Leállítása
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = Web Panel Törlése
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = Megnyitás Új Lapon
    .accesskey = N
zen-web-side-panel-context-open-in-container-tab = 
    .label = Megnyitás Konténer Lapon
    .accesskey = C
zen-web-side-panel-context-add-to-panel = 
    .label = Hozzáadás a Web Panelek Közé
    .accesskey = A
zen-sidebar-introduction-title = Üdv a Zen Sidebar-ban
zen-sidebar-introduction-description = A Zen Sidebar egy új mondja az Interneten való böngészésnek. Kattints valamelyik ikonra, hogy megnyiss egy web panelt.
