zen-panel-ui-workspaces-text = Más munkakörnyezetek
zen-panel-ui-workspaces-create-text = Munkakörnyezet létrehozása
zen-panel-ui-workspaces-create-save = 
    .label = Munkakörnyezet létrehozása
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = Mégsem
    .accesskey = C
zen-panel-ui-workspaces-edit-text = Munkakörnyezet módosítása
zen-panel-ui-workspaces-edit-save = 
    .label = Beállítások mentése
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Mégsem
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Munkakörnyezet törlése
    .accesskey = D
zen-workspaces-panel-context-open = 
    .label = Munkakörnyezet megnyitása
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Beállítás alapértelmezett munkakörnyezetnek
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Munkakörnyezet módosítása
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Lap(ok) mozgatása munkakörnyezetbe
    .accesskey = C
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Alapértelmezett konténer beállítása
    .accesskey = O
zen-workspaces-change-gradient = 
    .label = Téma színeinek módosítása
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Munkakörnyezetek
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Complementary
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Szétválasztás
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Analogous
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Triadic
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Lebegő
zen-panel-ui-gradient-click-to-add = Kattintson egy szín hozzáadásához
