zen-panel-ui-current-profile-text = jelenlegi profil
unified-extensions-description = A bővítmények a { -brand-short-name }-t új funkciókkal látják el.
tab-context-zen-reset-pinned-tab = 
    .label = Kitűzött lap visszaállítása
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Kitűzött lap cseréje a jelenlegi URL-el
    .accesskey = C
tab-zen-unload = 
    .label = Lap ürítése
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Lap ürítő opciók
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Lap ürítés megakadályozása
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Lap űrítésének engedélyezése
    .accesskey = I
zen-themes-corrupted = A te { -brand-short-name } mod fájljaid károsodtak. Vissza lettek állítva az eredeti témára.
