pane-zen-looks-title = Apariencia
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Cambiar el idioma por defecto podría facilitar el seguimiento de los sitios web.
zen-look-and-feel-colors-header = Elige un color de tema
zen-look-and-feel-colors-description = Haga que { -brand-short-name } se sienta a su gusto
zen-look-and-feel-use-workspace-colors = 
    .label = Usar color de espacio de trabajo como color primario
pane-zen-side-panels-title = Paneles web lateral
zen-side-panels-header = Ajustes generales para paneles web
zen-side-panels-description = ¡Aumente la productividad teniendo múltiples vistas a la vez!
zen-side-panels-enabled = 
    .label = Habilitar paneles web laterales
zen-side-panels-close-on-blur = 
    .label = Cerrar el panel cuando pierda el foco si no está fijado
zen-vertical-tabs-show-bottom-border = 
    .label = Mostrar borde para los iconos de la parte inferior
zen-vertical-tabs-layout-header = Diseño del navegador
zen-vertical-tabs-layout-description = Escoge el diseño que más te convenga
zen-layout-single-toolbar = Barra de herramientas única
zen-layout-multiple-toolbar = Múltiples barras de herramientas
zen-layout-collapsed-toolbar = Barra de herramientas contraída
sync-currently-syncing-workspaces = Espacios de trabajo
sync-engine-workspaces = 
    .label = Espacios de trabajo
    .tooltiptext = Sincroniza tus espacios de trabajo en todos los dispositivos
    .accesskey = M
zen-glance-title = Vistazo
zen-glance-header = Configuración general de Vistazo
zen-glance-description = Obtén un resumen rápido de tus enlaces sin abrirlos en una nueva pestaña
zen-glance-trigger-label = Método de activación
zen-glance-enabled = 
    .label = Activar Glance
zen-glance-trigger-ctrl-click = 
    .label = Ctrl + Click
zen-glance-trigger-alt-click = 
    .label = Alt + Clic
zen-glance-trigger-shift-click = 
    .label = Mayús + Clic
zen-glance-trigger-meta-click = 
    .label = Meta (Command) + Clic
zen-glance-trigger-mantain-click = 
    .label = Mantener pulsado (¡Próximamente!)
zen-look-and-feel-compact-view-header = Mostrar en vista compacta
zen-look-and-feel-compact-view-description = ¡Mostrar sólo las barras de herramientas que usas!
zen-look-and-feel-compact-view-enabled = 
    .label = Habilita el modo compacto de { -brand-short-name }
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Ocultar la barra de herramientas superior también en modo compacto
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Hacer emerger brevemente la barra de herramientas al cambiar o abrir nuevas pestañas en el modo compacto
zen-look-and-feel-buttons-header = Estilo de botón
zen-look-and-feel-buttons-description = Elija el estilo de los botones que desea ver
zen-look-and-feel-pilled-buttons = 
    .label = Botones rellenados
pane-zen-tabs-title = Administración de pestañas
category-zen-workspaces = 
    .tooltiptext = { pane-zen-tabs-title }
pane-settings-workspaces-title = Espacios de trabajo
pane-zen-tabs-unloader-title = Suspensión de Pestañas
zen-tabs-unloader-header = Configuración general para la Suspensión de Pestañas
zen-tabs-unloader-description = Pon en suspensión las pestañas de manera automática para ahorrar memoria
zen-tabs-unloader-enabled = 
    .label = Activar Suspensión de Pestañas
zen-tabs-unloader-unload-delay = 
    .label = Suspender pestañas después de
zen-tabs-unloader-unload-delay-description = El tiempo en minutos después del cual se suspenderán las pestañas
zen-look-and-feel-compact-toolbar-themed = 
    .label = Usar fondo temático para barra de herramientas compacta
zen-look-and-feel-compact-sidebar-themed = 
    .label = Usar fondo temático para barra lateral compacta
pane-zen-pinned-tab-manager-title = Pestañas Ancladas
zen-pinned-tab-manager-header = Configuración general de pestañas fijadas
zen-pinned-tab-manager-description = Administrar comportamiento adicional de pestañas fijadas
zen-pinned-tab-manager-restore-pinned-tabs-to-pinned-url = 
    .label = Restaurar pestañas ancladas a su URL original fijada en el inicio
zen-pinned-tab-manager-container-specific-essentials-enabled = 
    .label = Activar elementos esenciales específicos de contenedor
zen-pinned-tab-manager-close-shortcut-behavior-label = Cerrar comportamiento de corte directo
zen-pinned-tab-manager-reset-unload-switch-close-shortcut-option = 
    .label = Restablecer URL, suspender y cambiar a la pestaña siguiente
zen-pinned-tab-manager-unload-switch-close-shortcut-option = 
    .label = Suspender y cambiar a la pestaña siguiente
zen-pinned-tab-manager-reset-switch-close-shortcut-option = 
    .label = Restablecer URL y cambiar a la pestaña siguiente
zen-pinned-tab-manager-switch-close-shortcut-option = 
    .label = Cambiar a la pestaña siguiente
zen-pinned-tab-manager-reset-close-shortcut-option = 
    .label = Reset URL
zen-pinned-tab-manager-close-close-shortcut-option = 
    .label = Cerrar pestaña
pane-zen-workspaces-header = Espacios de trabajo
zen-settings-workspaces-header = Configuración general de las áreas de trabajo
zen-settings-workspaces-description = Con espacios de trabajo, ¡puede tener varias sesiones de navegación a la vez!
zen-settings-workspaces-enabled = 
    .label = Activar espacios de trabajo
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Ocultar el indicador de contenedor por defecto en la barra de pestañas
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Permitir que las áreas de trabajo tengan sus propias pestañas fijadas
zen-key-unsaved = Unsaved shortcut! Please safe it by clicking the "Escape" key after retyping it.
zen-key-conflict = Conflicto con otro acceso directo
pane-zen-theme-title = Ajustes del tema
zen-vertical-tabs-title = Diseño de la barra lateral y pestañas
zen-vertical-tabs-header = Pestañas verticales
zen-vertical-tabs-description = Administra tus pestañas en un diseño vertical
zen-vertical-tabs-show-expand-button = 
    .label = Mostrar botón Expandir
zen-vertical-tabs-newtab-on-tab-list = 
    .label = Mostrar botón de nueva pestaña en la lista de pestañas
zen-vertical-tabs-newtab-top-button-border = 
    .label = Mostrar borde de separación para el botón de nueva pestaña cuando está en la parte inferior
zen-vertical-tabs-newtab-top-button-up = 
    .label = Mover el botón de nueva pestaña a la parte superior
zen-vertical-tabs-expand-tabs-by-default = Expandir las pestañas por defecto
zen-vertical-tabs-dont-expand-tabs-by-default = No expandir las pestañas por defecto
zen-vertical-tabs-expand-tabs-on-hover = Expandir pestañas al pasar el cursor por encima (No funcionará en modo compacto)
zen-vertical-tabs-expand-tabs-header = Cómo expandir pestañas
zen-vertical-tabs-expand-tabs-description = Elegir cómo expandir pestañas en la barra lateral
zen-theme-marketplace-header = Zen Mods
zen-theme-disable-all-enabled = 
    .title = Desactivar todos los temas
zen-theme-disable-all-disabled = 
    .title = Activar todos los temas
zen-theme-marketplace-description = Buscar e instalar temas de la tienda.
zen-theme-marketplace-remove-button = 
    .label = Eliminar tema
zen-theme-marketplace-check-for-updates-button = 
    .label = Buscar actualizaciones
zen-theme-marketplace-updates-success = Tema actualizado correctamente
zen-theme-marketplace-updates-fail = ¡No se pudo encontrar ninguna actualización!
zen-theme-marketplace-toggle-enabled-button = 
    .title = Desactivar tema
zen-theme-marketplace-toggle-disabled-button = 
    .title = Activar tema
zen-theme-marketplace-remove-confirmation = ¿Estás seguro de que quieres eliminar este mod?
zen-theme-marketplace-close-modal = Cerrar
zen-theme-marketplace-theme-header-title = 
    .title = Selector CSS: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = Ninguna
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Escriba algo...
pane-zen-marketplace-title = Zen Mods
zen-settings-workspaces-display-as-icon-strip = 
    .label = Mostrar áreas de trabajo como un clip de icono
zen-settings-workspaces-force-container-tabs-to-workspace = 
    .label = Cambiar a espacio de trabajo donde el contenedor se establece por defecto al abrir pestañas de contenedor
zen-settings-workspaces-hide-deactivated-workspaces = 
    .label = Ocultar áreas de trabajo desactivadas
zen-theme-marketplace-link = Visitar tienda
zen-dark-theme-styles-header = Estilos del tema oscuro
zen-dark-theme-styles-description = Personaliza el tema oscuro a tu gusto
zen-dark-theme-styles-amoled = Tema nocturno
zen-dark-theme-styles-default = Tema Oscuro por defecto
zen-dark-theme-styles-colorful = Tema oscuro colorido
zen-split-view-title = Dividir vista
zen-split-view-header = Dividir función de vista
zen-split-view-description = Divida tu navegador en múltiples vistas, permitiéndote navegar por varios sitios web a la vez
zen-split-view-change-on-hover = 
    .label = Cambiar pestañas al pasar el cursor
zen-compact-mode-styles-left = Ocultar barra de pestañas
zen-compact-mode-styles-top = Ocultar barra superior
zen-compact-mode-styles-both = Ocultar ambos
zen-urlbar-title = Barra de direcciones de Zen
zen-urlbar-header = Configuración general de la barra de direcciones
zen-urlbar-description = Personaliza la barra de direcciones a tu gusto
zen-urlbar-behavior-label = Comportamiento
zen-urlbar-behavior-normal = 
    .label = Normal
zen-urlbar-behavior-floating-on-type = 
    .label = Flotante solo al escribir
zen-urlbar-behavior-float = 
    .label = Flotante siempre
pane-zen-CKS-title = Atajos de Teclado
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } atajos de teclado
zen-settings-CKS-header = Personalice tus atajos de teclado
zen-settings-CKS-description = Cambie los atajos de teclado por defecto a su gusto y mejore su experiencia de navegación
zen-settings-CKS-disable-firefox = 
    .label = Desactivar los atajos de teclado por defecto de { -brand-short-name }
zen-settings-CKS-duplicate-shortcut = 
    .label = Duplicate Shortcut
zen-settings-CKS-reset-shortcuts = 
    .label = Restablecer por defecto
zenCKSOption-group-other = Otro
zenCKSOption-group-windowAndTabManagement = Gestión de ventanas y tabuladores
zenCKSOption-group-navigation = Navigation
zenCKSOption-group-searchAndFind = Buscar y buscar
zenCKSOption-group-pageOperations = Operaciones de página
zenCKSOption-group-historyAndBookmarks = Historial y Marcadores
zenCKSOption-group-mediaAndDisplay = Multimedia y pantalla
zenCKSOption-group-zen-compact-mode = Modo compacto
zenCKSOption-group-zen-workspace = Espacios de trabajo
zenCKSOption-group-zen-other = Otras características Zen
zenCKSOption-group-zen-split-view = Dividir vista
zenCKSOption-group-devTools = Herramientas de desarrollador
zen-key-quick-restart = Reinicio rápido
zen-window-new-shortcut = Nueva ventana
zen-tab-new-shortcut = Nueva pestaña
zen-key-redo = Rehacer
zen-restore-last-closed-tab-shortcut = Restaurar última pestaña cerrada
zen-location-open-shortcut = Abrir ubicación
zen-location-open-shortcut-alt = Abrir ubicación (Alt)
zen-key-undo-close-window = Deshacer cerrar ventana
zen-text-action-undo-shortcut = Deshacer
zen-text-action-redo-shortcut = Rehacer
zen-text-action-cut-shortcut = Cortar
zen-text-action-copy-shortcut = Copiar
zen-text-action-copy-url-shortcut = Copiar URL actual
zen-text-action-paste-shortcut = Pegar
zen-text-action-select-all-shortcut = Seleccionar todo
zen-text-action-delete-shortcut = Eliminar
zen-history-show-all-shortcut-mac = Mostrar todo el historial (Mac)
zen-full-screen-shortcut = Cambiar a pantalla completa
zen-reader-mode-toggle-shortcut-windows = Cambiar Modo Lector (Windows)
zen-picture-in-picture-toggle-shortcut-alt = Cambiar imagen en foto (Alt)
zen-picture-in-picture-toggle-shortcut-mac = Alternar foto en foto (Mac)
zen-picture-in-picture-toggle-shortcut-mac-alt = Alternar foto en foto (Mac Alt)
zen-page-source-shortcut-safari = Ver fuente de página (Safari)
zen-nav-stop-shortcut = Detener la carga
zen-history-sidebar-shortcut = Show History Sidebar
zen-window-minimize-shortcut = Minimizar ventana
zen-help-shortcut = Abrir Ayuda
zen-preferences-shortcut = Abrir preferencias
zen-hide-app-shortcut = Ocultar aplicación
zen-hide-other-apps-shortcut = Ocultar otras aplicaciones
zen-search-focus-shortcut = Búsqueda en foco
zen-search-focus-shortcut-alt = Búsqueda en foco (Alt)
zen-downloads-shortcut = Abrir descargas
zen-addons-shortcut = Abrir complementos
zen-file-open-shortcut = Abrir archivo
zen-save-page-shortcut = Guardar página
zen-print-shortcut = Print Page
zen-close-shortcut-2 = Cerrar pestaña
zen-mute-toggle-shortcut = Silenciar
zen-key-delete = Borrar Clave
zen-key-go-back = Volver
zen-key-go-forward = Ir adelante
zen-nav-back-shortcut-alt = Navegar atrás (Alt)
zen-nav-fwd-shortcut-alt = Navegar hacia adelante (Alt)
zen-history-show-all-shortcut = Mostrar todo el historial
zen-key-enter-full-screen = Entrar en pantalla completa
zen-key-exit-full-screen = Salir de pantalla completa
zen-reader-mode-toggle-shortcut-other = Cambiar modo Lector
zen-picture-in-picture-toggle-shortcut = Alternar foto en foto
zen-nav-reload-shortcut-2 = Recargar página
zen-key-about-processes = Acerca de procesos
zen-page-source-shortcut = Ver fuente de página
zen-page-info-shortcut = Ver Información de Página
zen-find-shortcut = Buscar en la página
zen-search-find-again-shortcut = Encontrar de nuevo
zen-search-find-again-shortcut-prev = Buscar Anterior
zen-search-find-again-shortcut-2 = Buscar de nuevo (Alt)
zen-bookmark-this-page-shortcut = Marcar esta página
zen-bookmark-show-library-shortcut = Mostrar librería de marcadores
zen-key-stop = Detener la carga
zen-full-zoom-reduce-shortcut = Apagar
zen-full-zoom-enlarge-shortcut = Acercar en
zen-full-zoom-reset-shortcut = Reset Zoom
zen-bidi-switch-direction-shortcut = Cambiar Dirección de Texto
zen-private-browsing-shortcut = Navegación privada
zen-screenshot-shortcut = Captura de pantalla
zen-key-sanitize = Borrar datos de navegación
zen-quit-app-shortcut = Salir de la aplicación
zen-key-wr-capture-cmd = Comando de captura WR
zen-key-wr-toggle-capture-sequence-cmd = Cambiar secuencia de captura WR
zen-nav-reload-shortcut = Recargar página
zen-nav-reload-shortcut-skip-cache = Reload Page (Skip Cache)
zen-close-shortcut = Cerrar ventana
zen-close-tab-shortcut = Cerrar pestaña
zen-compact-mode-shortcut-show-sidebar = Alternar barra lateral flotante
zen-compact-mode-shortcut-show-toolbar = Alternar barra de herramientas flotante
zen-compact-mode-shortcut-toggle = Alternar modo compato
zen-workspace-shortcut-switch-1 = Cambiar a Espacio de Trabajo 1
zen-workspace-shortcut-switch-2 = Cambiar a Espacio de Trabajo 2
zen-workspace-shortcut-switch-3 = Cambiar al espacio de trabajo 3
zen-workspace-shortcut-switch-4 = Cambiar al espacio de trabajo 4
zen-workspace-shortcut-switch-5 = Cambiar al espacio de trabajo 5
zen-workspace-shortcut-switch-6 = Cambiar al espacio de trabajo 6
zen-workspace-shortcut-switch-7 = Cambiar al espacio de trabajo 7
zen-workspace-shortcut-switch-8 = Cambiar al espacio de trabajo 8
zen-workspace-shortcut-switch-9 = Cambiar al espacio de trabajo 9
zen-workspace-shortcut-switch-10 = Cambiar al espacio de trabajo 10
zen-workspace-shortcut-forward = Reenviar espacio de trabajo
zen-workspace-shortcut-backward = Retroceder espacio de trabajo
zen-web-panel-shortcut-toggle = Alternar Panel Web
zen-sidebar-shortcut-toggle = Alternar Ancho de Barra lateral
zen-pinned-tab-shortcut-reset = Restablecer la Tabla Anclada a la URL Anclada
zen-split-view-shortcut-grid = Cambiar la cuadrícula de vista dividida
zen-split-view-shortcut-vertical = Cambiar a dividir vista vertical
zen-split-view-shortcut-horizontal = Cambiar vista horizontal
zen-split-view-shortcut-unsplit = Cerrar vista separada
zen-key-select-tab-1 = Seleccionar pestaña 1
zen-key-select-tab-2 = Seleccionar pestaña 2
zen-key-select-tab-3 = Seleccionar pestaña 3
zen-key-select-tab-4 = Seleccionar pestaña 4
zen-key-select-tab-5 = Seleccionar pestaña 5
zen-key-select-tab-6 = Seleccionar pestaña 6
zen-key-select-tab-7 = Seleccionar pestaña 7
zen-key-select-tab-8 = Seleccionar pestaña 8
zen-key-select-tab-last = Seleccionar última pestaña
zen-key-show-all-tabs = Mostrar todas las pestañas
zen-key-goto-history = Abrir el Historial
zen-key-go-home = Ir a la página de inicio
zen-bookmark-show-sidebar-shortcut = Mostrar barra lateral de marcadores
zen-bookmark-show-toolbar-shortcut = Mostrar barra de marcadores
zen-devtools-toggle-shortcut = Alternar herramientas de desarrollador
zen-devtools-toggle-browser-toolbox-shortcut = Alternar caja de herramientas del navegador
zen-devtools-toggle-browser-console-shortcut = Alternar consola del navegador
zen-devtools-toggle-responsive-design-mode-shortcut = Alternar modo de diseño adaptable
zen-devtools-toggle-inspector-shortcut = Alternar inspector
zen-devtools-toggle-web-console-shortcut = Alternar consola web
zen-devtools-toggle-js-debugger-shortcut = Alternar depurador de JavaScript
zen-devtools-toggle-net-monitor-shortcut = Alternar monitor de red
zen-devtools-toggle-style-editor-shortcut = Alternar editor de estilos
zen-devtools-toggle-performance-shortcut = Alternar rendimiento
zen-devtools-toggle-storage-shortcut = Alternar almacenamiento
zen-devtools-toggle-dom-shortcut = Alternar DOM
zen-devtools-toggle-accessibility-shortcut = Alternar accesibilidad
