pane-zen-looks-title = Apariencia y experiencia
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Cambiar el idioma por defecto puede provocar que seas más rastreable por los sitios web que visitas.
zen-look-and-feel-colors-header = Selecciona un color de tema
zen-look-and-feel-colors-description = Haz que { -brand-short-name } se vea y se sienta como te gusta
zen-look-and-feel-themed-toolbar = 
    .label = Hacer que la barra de herramientas use el color de acento
pane-zen-side-panels-title = Paneles web laterales
zen-side-panels-header = Ajustes generales para paneles web
zen-side-panels-description = ¡Aumenta tu productividad teniendo múltiples vistas a la vez!
zen-side-panels-enabled = 
    .label = Habilitar paneles web laterales
zen-side-panels-close-on-blur = 
    .label = Cerrar el panel cuando pierde el foco si no está fijado
zen-look-and-feel-compact-view-header = Mostrar en vista compacta
zen-look-and-feel-compact-view-description = ¡Mostrar solo las barras de herramienta que utilizas!
zen-look-and-feel-compact-view-enabled = 
    .label = Habilitar el modo compacto de { -brand-short-name }
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Ocultar la barra de herramientas superior en modo compacto
zen-look-and-feel-buttons-header = Estilo de botones
zen-look-and-feel-buttons-description = Selecciona el estilo de botones que quieres ver
zen-look-and-feel-pilled-buttons = 
    .label = Botones tipo pastilla
pane-zen-workspaces-title = Áreas de trabajo
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = Áreas de trabajo
pane-zen-workspaces-header = Áreas de trabajo
zen-settings-workspaces-header = Ajustes generales de áreas de trabajo
zen-settings-workspaces-description = Con las áreas de trabajo, ¡puedes tener múltiples sesiones de navegación al mismo tiempo!
zen-settings-workspaces-enabled = 
    .label = Habilitar áreas de trabajo (experimental)
pane-zen-theme-title = Ajustes de tema
zen-vertical-tabs-title = Ajustes de pestañas
zen-vertical-tabs-header = Pestañas verticales
zen-vertical-tabs-description = Administra tus pestañas en una disposición vertical
zen-vertical-tabs-show-expand-button = 
    .label = Mostrar botón para expandir
zen-vertical-tabs-expand-tabs-by-default = Expandir pestañas por defecto
zen-vertical-tabs-dont-expand-tabs-by-default = No expandir pestañas por defecto
zen-vertical-tabs-expand-tabs-on-hover = Expandir pestañas al pasar el cursor por encima (no funcionará en modo compacto)
zen-vertical-tabs-expand-tabs-header = Como expandir pestañas
zen-vertical-tabs-expand-tabs-description = Elegir como expandir las pestañas en la barra lateral
zen-theme-marketplace-header = Tienda de temas
zen-theme-marketplace-description = Encuentra e instala temas desde la tienda.
zen-theme-marketplace-remove-button = 
    .label = Eliminar tema
zen-theme-marketplace-link = Visitar tienda
pane-zen-CKS-title = Atajos de teclado
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = Atajos de teclado de { -brand-short-name }
zen-settings-CKS-header = Personaliza tus atajos de teclado
zen-settings-CKS-description = Cambia los atajos de teclado predeterminados a tu gusto y mejora tu experiencia de navegación
zen-settings-CKS-disable-firefox = 
    .label = Deshabilitar los atajos de teclado predeterminados de { -brand-short-name }
zen-cks-group-tab-action = Acciones de pestaña
zen-cks-group-page-action = Acciones de página
zen-cks-group-visible-action = Acciones de visibilidad
zen-cks-group-history-action = Acciones de historial
zen-cks-group-search-action = Acciones de búsqueda
zen-cks-group-tools-action = Acciones de herramientas
zen-cks-group-bookmark-action = Acciones de marcadores
zen-cks-group-open-page-action = Acciones de apertura de páginas
zen-cks-group-downloads-action = Acciones de descargas
zen-cks-group-sidebar-action = Acciones de barra lateral
zen-cks-group-compact-mode-action = Acciones de modo compacto
zen-cks-group-split-view-action = Acciones de vista separada
zen-cks-group-workspace-action = Acciones de áreas de trabajo
open-new-tab = Abrir nueva pestaña
close-tab = Cerrar pestaña
open-new-window = Abrir nueva ventana
open-new-private-window = Abrir nueva ventana privada
close-window = Cerrar ventana
restore-last-tab = Restaurar última pestaña
restore-last-window = Restaurar última ventana
show-next-tab = Mostrar siguiente pestaña
show-previous-tab = Mostrar pestaña anterior
show-all-tabs-panel = Mostrar el panel de todas las pestañas
send-with-mail = Enviar página en correo
save-page = Guardar página
print-page = Imprimir página
mute-current-tab = Silenciar pestaña actual
show-source-of-page = Mostrar código fuente del sitio web
show-page-info = Mostrar información del sitio
zoom-in = Acercar
zoom-out = Alejar
reset-zoom = Reiniciar zoom
back = Atrás
forward = Adelante
stop = Detener
reload = Recargar
force-reload = Forzar recargar
search-in-this-page = Buscar en esta página
show-next-search-result = Mostrar siguiente resultado de búsqueda
show-previous-search-result = Mostrar resultado de búsqueda anterior
search-the-web = Buscar en la web
open-migration-wizard = Abrir asistente de migración
quit-from-application = Salir de la aplicación
enter-into-customize-mode = Entrar al modo personalización
enter-into-offline-mode = Entrar al modo fuera de línea
open-screen-capture = Abrir captura de pantalla
bookmark-this-page = Agregar esta página a marcadores
open-bookmark-add-tool = Abrir herramienta de agregar a marcadores
open-bookmarks-manager = Abrir administrador de marcadores
toggle-bookmark-toolbar = Alternar barra de herramientas de marcadores
open-general-preferences = Abrir ajustes generales
open-privacy-preferences = Abrir ajustes de privacidad
open-workspaces-preferences = Abrir ajustes de áreas de trabajo
open-containers-preferences = Abrir ajustes de contenedores
open-search-preferences = Abrir ajustes de búsqueda
open-sync-preferences = Abrir ajustes de sincronización
open-task-manager = Abrir administrador de tareas
open-addons-manager = Abrir administrador de extensiones
open-home-page = Abrir página de inicio
forget-history = Olvidar historial
quick-forget-history = Olvidar historial rápido
clear-recent-history = Limpiar historial reciente
restore-last-session = Restaurar última sesión
search-history = Historial de búsqueda
manage-history = Administrar historial
open-downloads = Abrir descargas
show-bookmark-sidebar = Mostrar marcadores en barra lateral
show-history-sidebar = Mostrar historial en barra lateral
show-synced-tabs-sidebar = Mostrar pestañas sincronizadas en barra lateral
reverse-sidebar = Invertir posición de barra lateral
hide-sidebar = Esconder barra lateral
toggle-sidebar = Alternar barra lateral
zen-toggle-web-panels = Alternar paneles web
zen-toggle-compact-mode = Alternar modo compacto
zen-toggle-compact-mode-sidebar = Alternar panel lateral en modo compacto
zen-toggle-compact-mode-toolbar = Alternar barra de herramientas en modo compacto
zen-change-workspace = Navegar por áreas de trabajo en ciclo
zen-split-view-grid = Separar en vista cuadriculada
zen-split-view-vertical = Separar en vista vertical
zen-split-view-horizontal = Separar en vista horizontal
zen-split-view-close = Cerrar vista separada
