pane-zen-looks-title = Apariencia
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Cambiar el idioma por defecto puede hacer que los sitios web puedan rastrearte más fácil.
zen-look-and-feel-colors-header = Selecciona un color de tema
zen-look-and-feel-colors-description = Haz que { -brand-short-name } se sienta como te guste
zen-look-and-feel-themed-toolbar = 
    .label = Hacer que la barra de herramientas utilice el color de acento
pane-zen-side-panels-title = Paneles web laterales
zen-side-panels-header = Ajustes generales de paneles web
zen-side-panels-description = ¡Aumenta tu productividad teniendo múltiples vistas a la vez!
zen-side-panels-enabled = 
    .label = Habilitar paneles web laterales
zen-side-panels-close-on-blur = 
    .label = Cerrar el panel cuando pierde el foco si no está fijado
zen-look-and-feel-compact-view-header = Mostrar en vista compacta
zen-look-and-feel-compact-view-description = ¡Solo muestra las barras de herramientas que utilices!
zen-look-and-feel-compact-view-enabled = 
    .label = Habilita el modo compacto de { -brand-short-name }
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Ocultar la barra de herramientas superior en el modo compacto
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Flotar brevemente la barra de herramientas al cambiar o abrir nuevas pestañas en modo compacto
zen-look-and-feel-buttons-header = Estilo de botones
zen-look-and-feel-buttons-description = Selecciona el estilo de botones que deseas ver
zen-look-and-feel-pilled-buttons = 
    .label = Botones redondeados
pane-zen-workspaces-title = Áreas de trabajo
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = Áreas de trabajo
pane-zen-workspaces-header = Áreas de trabajo
zen-settings-workspaces-header = Ajustes generales de áreas de trabajo
zen-settings-workspaces-description = Con las áreas de trabajo, ¡puedes tener múltiples sesiones de navegación a la vez!
zen-settings-workspaces-enabled = 
    .label = Habilitar áreas de trabajo (Experimental)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Ocultar el indicador de contenedor predeterminado en la barra de pestañas
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Permitir a los espacios de trabajo tener sus propias pestañas fijadas
pane-zen-theme-title = Ajustes de temas
zen-vertical-tabs-title = Barra lateral y pestañas
zen-vertical-tabs-header = Pestañas verticales
zen-vertical-tabs-description = Administra tus pestañas en una disposición vertical
zen-vertical-tabs-show-expand-button = 
    .label = Mostrar botón para expandir
zen-vertical-tabs-expand-tabs-by-default = Expandir pestañas por defecto
zen-vertical-tabs-dont-expand-tabs-by-default = No expandir pestañas por defecto
zen-vertical-tabs-expand-tabs-on-hover = Expandir pestañas al pasar el ratón por encima (no funcionará en modo compacto)
zen-vertical-tabs-expand-tabs-header = Cómo expandir pestañas
zen-vertical-tabs-expand-tabs-description = Selecciona como expandir las pestañas en la barra lateral
zen-theme-marketplace-header = Modificaciones de Zen
zen-theme-marketplace-description = Encuentra e instala temas desde la tienda.
zen-theme-marketplace-remove-button = 
    .label = Eliminar tema
zen-theme-marketplace-check-for-updates-button = 
    .label = Buscar actualizaciones
zen-theme-marketplace-updates-success = Tema actualizado exitosamente
zen-theme-marketplace-updates-fail = ¡No se encontraron actualizaciones!
zen-theme-marketplace-toggle-enabled-button = 
    .title = Desactivar Tema
zen-theme-marketplace-toggle-disabled-button = 
    .title = Activar Tema
zen-theme-marketplace-remove-confirmation = ¿Realmente desea remover este mod?
zen-theme-marketplace-close-modal = Cerrar
zen-theme-marketplace-theme-header-title = 
    .title = Selector de CSS: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = Ninguno
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Escriba algo...
pane-zen-marketplace-title = Mods de Zen
zen-settings-workspaces-display-as-icon-strip = 
    .label = Mostrar espacios de trabajo como tiras de íconos
zen-theme-marketplace-link = Visitar la tienda
zen-dark-theme-styles-header = Estilos de temas oscuros
zen-dark-theme-styles-description = Personalice el tema oscuro a su gusto
zen-dark-theme-styles-amoled = Tema Nocturno
zen-dark-theme-styles-default = Tema oscuro predeterminado
zen-dark-theme-styles-colorful = Tema oscuro colorido
zen-compact-mode-styles-left = Ocultar Barra de Pestañas
zen-compact-mode-styles-top = Ocultar Barra Superior
zen-compact-mode-styles-both = Ocultar Ambas
pane-zen-CKS-title = Atajos de teclado
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = Atajos de teclado de { -brand-short-name }
zen-settings-CKS-header = Personaliza tus atajos de teclado
zen-settings-CKS-description = Cambia los atajos de teclado predeterminados a tu gusto y mejora tu experiencia de navegación
zen-settings-CKS-disable-firefox = 
    .label = Deshabilita los atajos de teclado por defecto de { -brand-short-name }
zen-settings-CKS-duplicate-shortcut = 
    .label = Duplicate Shortcut
zenCKSOption-group-other = Other
zenCKSOption-group-windowAndTabManagement = Window & Tab Management
zenCKSOption-group-navigation = Navigation
zenCKSOption-group-searchAndFind = Search & Find
zenCKSOption-group-pageOperations = Page Operations
zenCKSOption-group-historyAndBookmarks = History & Bookmarks
zenCKSOption-group-mediaAndDisplay = Media & Display
zenCKSOption-group-zen-compact-mode = Compact Mode
zenCKSOption-group-zen-workspace = Workspaces
zenCKSOption-group-zen-other = Other Zen Features
zenCKSOption-group-zen-split-view = Split View
zen-key-quick-restart = Quick Restart
zen-window-new-shortcut = New Window
zen-tab-new-shortcut = New Tab
zen-location-open-shortcut = Open Location
zen-location-open-shortcut-alt = Open Location (Alt)
zen-search-focus-shortcut = Focus Search
zen-search-focus-shortcut-alt = Focus Search (Alt)
zen-downloads-shortcut = Open Downloads
zen-addons-shortcut = Open Add-ons
zen-file-open-shortcut = Open File
zen-save-page-shortcut = Save Page
zen-print-shortcut = Print Page
zen-close-shortcut-2 = Close Tab
zen-mute-toggle-shortcut = Toggle Mute
zen-key-delete = Delete Key
zen-key-go-back = Go Back
zen-key-go-forward = Go Forward
zen-nav-back-shortcut-alt = Navigate Back (Alt)
zen-nav-fwd-shortcut-alt = Navigate Forward (Alt)
zen-history-show-all-shortcut = Show All History
zen-key-enter-full-screen = Enter Full Screen
zen-key-exit-full-screen = Exit Full Screen
zen-reader-mode-toggle-shortcut-other = Toggle Reader Mode
zen-picture-in-picture-toggle-shortcut = Toggle Picture-in-Picture
zen-nav-reload-shortcut-2 = Reload Page
zen-key-about-processes = About Processes
zen-page-source-shortcut = View Page Source
zen-page-info-shortcut = View Page Info
zen-find-shortcut = Find on Page
zen-search-find-again-shortcut = Find Again
zen-search-find-again-shortcut-prev = Find Previous
zen-search-find-again-shortcut-2 = Find Again (Alt)
zen-bookmark-this-page-shortcut = Bookmark This Page
zen-bookmark-show-library-shortcut = Show Bookmarks Library
zen-key-stop = Stop Loading
zen-full-zoom-reduce-shortcut = Zoom Out
zen-full-zoom-enlarge-shortcut = Zoom In
zen-full-zoom-reset-shortcut = Reset Zoom
zen-bidi-switch-direction-shortcut = Switch Text Direction
zen-private-browsing-shortcut = Private Browsing
zen-screenshot-shortcut = Take Screenshot
zen-key-sanitize = Clear Browsing Data
zen-quit-app-shortcut = Quit Application
zen-key-wr-capture-cmd = WR Capture Command
zen-key-wr-toggle-capture-sequence-cmd = Toggle WR Capture Sequence
zen-nav-reload-shortcut = Reload Page
zen-nav-reload-shortcut-skip-cache = Reload Page (Skip Cache)
zen-close-shortcut = Close Window
zen-close-tab-shortcut = Close Tab
zen-compact-mode-shortcut-show-sidebar = Toggle Floating Sidebar
zen-compact-mode-shortcut-show-toolbar = Toggle Floating Toolbar
zen-compact-mode-shortcut-toggle = Toggle Compact Mode
zen-workspace-shortcut-switch-1 = Switch to Workspace 1
zen-workspace-shortcut-switch-2 = Switch to Workspace 2
zen-workspace-shortcut-switch-3 = Switch to Workspace 3
zen-workspace-shortcut-switch-4 = Switch to Workspace 4
zen-workspace-shortcut-switch-5 = Switch to Workspace 5
zen-workspace-shortcut-switch-6 = Switch to Workspace 6
zen-workspace-shortcut-switch-7 = Switch to Workspace 7
zen-workspace-shortcut-switch-8 = Switch to Workspace 8
zen-workspace-shortcut-switch-9 = Switch to Workspace 9
zen-workspace-shortcut-switch-10 = Switch to Workspace 10
zen-workspace-shortcut-forward = Forward Workspace
zen-workspace-shortcut-backward = Backward Workspace
zen-web-panel-shortcut-toggle = Toggle Web Panel
zen-sidebar-shortcut-toggle = Toggle Sidebar's Width
zen-split-view-shortcut-grid = Toggle Split View Grid
zen-split-view-shortcut-vertical = Toggle Split View Vertical
zen-split-view-shortcut-horizontal = Toggle Split View Horizontal
zen-split-view-shortcut-unsplit = Close Split View
