pane-zen-looks-title = Aspetto
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Cambiare la lingua predefinita potrebbe rendere più facile ai siti di tracciarti.
zen-look-and-feel-colors-header = Scegli un colore del tema
zen-look-and-feel-colors-description = Rendi { -brand-short-name } dell'aspetto che preferisci
zen-look-and-feel-themed-toolbar = 
    .label = Make the toolbar themed with the accent color
pane-zen-side-panels-title = Side Web Panels
zen-side-panels-header = General settings for web panels
zen-side-panels-description = Increase productivity by having multiple views at once!
zen-side-panels-enabled = 
    .label = Enable Web Side Panels
zen-side-panels-close-on-blur = 
    .label = Close the panel when it loses focus if it's not pinned
zen-look-and-feel-compact-view-header = Show in compact view
zen-look-and-feel-compact-view-description = Only show the toolbars you use!
zen-look-and-feel-compact-view-enabled = 
    .label = Attiva la modalità compatta di { -brand-short-name }
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Nascondi anche la toolbar in modalità compatta
zen-look-and-feel-buttons-header = Stile dei pulsanti
zen-look-and-feel-buttons-description = Scegli lo stile dei pulsanti che vuoi vedere
zen-look-and-feel-pilled-buttons = 
    .label = Pilled Buttons
pane-zen-workspaces-title = Spazi di lavoro
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = Spazi di lavoro
pane-zen-workspaces-header = Spazi di lavoro
zen-settings-workspaces-header = Impostazioni generali per gli spazi di lavoro
zen-settings-workspaces-description = Con gli spazi di lavoro, puoi avere più sessioni attive contemporaneamente!
zen-settings-workspaces-enabled = 
    .label = Attiva gli spazi di lavoro (sperimentale)
pane-zen-theme-title = Theme Settings
zen-vertical-tabs-title = Sidebar and tabs layout
zen-vertical-tabs-header = Vertical Tabs
zen-vertical-tabs-description = Manage your tabs in a vertical layout
zen-vertical-tabs-show-expand-button = 
    .label = Show Expand Button
zen-vertical-tabs-expand-tabs-by-default = Expand Tabs by Default
zen-vertical-tabs-dont-expand-tabs-by-default = Don't Expand Tabs by Default
zen-vertical-tabs-expand-tabs-on-hover = Expand Tabs on Hover (Wont work on compact mode)
zen-vertical-tabs-expand-tabs-header = How to expand tabs
zen-vertical-tabs-expand-tabs-description = Choose how to expand tabs in the sidebar
zen-theme-marketplace-header = Negozio dei temi
zen-theme-marketplace-description = Trova e installa temi dal negozio.
zen-theme-marketplace-remove-button = 
    .label = Rimuovi tema
zen-theme-marketplace-check-for-updates-button = 
    .label = Cerca aggiornamenti
zen-theme-marketplace-updates-success = Tema aggiornato con successo
zen-theme-marketplace-updates-fail = Non sono stati trovati aggiornamenti!
pane-zen-marketplace-title = Negozio dei temi
zen-theme-marketplace-link = Visita il negozio
pane-zen-CKS-title = Abbreviazioni da tastiera
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } Keyboard Shortcuts
zen-settings-CKS-header = Customize your keyboard shortcuts
zen-settings-CKS-description = Change the default keyboard shortcuts to your liking and improve your browsing experience
zen-settings-CKS-disable-firefox = 
    .label = Disable { -brand-short-name }'s default keyboard shortcuts
zen-cks-group-tab-action = Tab Actions
zen-cks-group-page-action = Page Actions
zen-cks-group-visible-action = Visible Actions
zen-cks-group-history-action = History Actions
zen-cks-group-search-action = Search Actions
zen-cks-group-tools-action = Tools Actions
zen-cks-group-bookmark-action = Bookmark Actions
zen-cks-group-open-page-action = Open Page Actions
zen-cks-group-downloads-action = Downloads Actions
zen-cks-group-sidebar-action = Sidebar Actions
zen-cks-group-compact-mode-action = Compact Mode Actions
zen-cks-group-split-view-action = Split View Actions
zen-cks-group-workspace-action = Workspace Actions
open-new-tab = Open New Tab
close-tab = Close Tab
open-new-window = Open New Window
open-new-private-window = Open New Private Window
close-window = Close Window
restore-last-tab = Restore Last Tab
restore-last-window = Restore Last Window
show-next-tab = Show Next Tab
show-previous-tab = Show Previous Tab
show-all-tabs-panel = Show All Tabs Panel
send-with-mail = Send Page with Mail
save-page = Save Page
print-page = Print Page
mute-current-tab = Mute Current Tab
show-source-of-page = Show Source of Page
show-page-info = Show Page Info
zoom-in = Zoom In
zoom-out = Zoom Out
reset-zoom = Reset Zoom
back = Back
forward = Forward
stop = Stop
reload = Reload
force-reload = Force Reload
search-in-this-page = Search in This Page
show-next-search-result = Show Next Search Result
show-previous-search-result = Show Previous Search Result
search-the-web = Search the Web
open-migration-wizard = Open Migration Wizard
quit-from-application = Chiudi l'applicazione
enter-into-customize-mode = Enter Customize Mode
enter-into-offline-mode = Enter Offline Mode
open-screen-capture = Open Screen Capture
bookmark-this-page = Bookmark This Page
open-bookmark-add-tool = Open Bookmark Add Tool
open-bookmarks-manager = Open Bookmarks Manager
toggle-bookmark-toolbar = Toggle Bookmark Toolbar
open-general-preferences = Open General Preferences
open-privacy-preferences = Open Privacy Preferences
open-workspaces-preferences = Open Workspaces Preferences
open-containers-preferences = Open Containers Preferences
open-search-preferences = Open Search Preferences
open-sync-preferences = Open Sync Preferences
open-task-manager = Apri il task manager
open-addons-manager = Apri il manager delle estensioni
open-home-page = Apri l'home page
forget-history = Forget History
quick-forget-history = Quick Forget History
clear-recent-history = Clear Recent History
restore-last-session = Restore Last Session
search-history = Search History
manage-history = Manage History
open-downloads = Apri i download
show-bookmark-sidebar = Show Bookmark Sidebar
show-history-sidebar = Show History Sidebar
show-synced-tabs-sidebar = Show Synced Tabs Sidebar
reverse-sidebar = Reverse Sidebar Position
hide-sidebar = Hide Sidebar
toggle-sidebar = Toggle Sidebar
zen-toggle-web-panels = Toggle Web Panels
zen-toggle-compact-mode = Toggle Compact Mode
zen-toggle-compact-mode-sidebar = Toggle Compact Mode Sidebar
zen-toggle-compact-mode-toolbar = Toggle Compact Mode Toolbar
zen-change-workspace = Cycle Workspaces
zen-split-view-grid = Split View Grid
zen-split-view-vertical = Split View Vertical
zen-split-view-horizontal = Split View Horizontal
zen-split-view-close = Close Split View
