pane-zen-looks-title = Aspetto
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Cambiare la lingua predefinita potrebbe agevolare i siti nel tracciarti.
zen-look-and-feel-colors-header = Scegli un colore del tema
zen-look-and-feel-colors-description = Rendi { -brand-short-name } dell'aspetto che preferisci
zen-look-and-feel-themed-toolbar = 
    .label = Usa il colore secondario sulla barra degli strumenti
pane-zen-side-panels-title = Pannelli web laterali
zen-side-panels-header = Impostazioni generali per i pannelli web
zen-side-panels-description = Sii più produttivo avendo più schede alla volta!
zen-side-panels-enabled = 
    .label = Attiva Pannelli Web Laterali
zen-side-panels-close-on-blur = 
    .label = Chiudi il pannello quando non è in utilizzo se non è fissato
zen-look-and-feel-compact-view-header = Visualizza in modalità compatta
zen-look-and-feel-compact-view-description = Mostra soltanto le barre degli strumenti che usi!
zen-look-and-feel-compact-view-enabled = 
    .label = Attiva la modalità compatta di { -brand-short-name }
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Nascondi la barra degli strumenti in modalità compatta
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Briefly make the toolbar popup when switching or opening new tabs in compact mode
zen-look-and-feel-buttons-header = Stile dei pulsanti
zen-look-and-feel-buttons-description = Scegli lo stile dei pulsanti che vuoi vedere
zen-look-and-feel-pilled-buttons = 
    .label = Pulsanti a pillola
pane-zen-workspaces-title = Spazi di lavoro
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = Spazi di lavoro
pane-zen-workspaces-header = Spazi di lavoro
zen-settings-workspaces-header = Impostazioni generali per gli spazi di lavoro
zen-settings-workspaces-description = Con gli spazi di lavoro, puoi avere più sessioni attive contemporaneamente!
zen-settings-workspaces-enabled = 
    .label = Attiva gli spazi di lavoro (sperimentale)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Hide the default container indicator in the tab bar
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Allow workspaces have theyr own pinned tabs
pane-zen-theme-title = Impostazioni tema
zen-vertical-tabs-title = Layout barra laterale e schede
zen-vertical-tabs-header = Schede verticali
zen-vertical-tabs-description = Gestisci le schede in un layout verticale
zen-vertical-tabs-show-expand-button = 
    .label = Mostra pulsante di espansione
zen-vertical-tabs-expand-tabs-by-default = Espandi le schede di default
zen-vertical-tabs-dont-expand-tabs-by-default = Non espandere le schede di default
zen-vertical-tabs-expand-tabs-on-hover = Espandi le schede passandoci sopra il mouse (non funziona in modalità compatta)
zen-vertical-tabs-expand-tabs-header = Come espandere le schede
zen-vertical-tabs-expand-tabs-description = Scegli come espandere le schede nella barra laterale
zen-theme-marketplace-header = Negozio temi
zen-theme-marketplace-description = Trova e installa temi dal negozio.
zen-theme-marketplace-remove-button = 
    .label = Rimuovi tema
zen-theme-marketplace-check-for-updates-button = 
    .label = Cerca aggiornamenti
zen-theme-marketplace-updates-success = Tema aggiornato con successo
zen-theme-marketplace-updates-fail = Non sono stati trovati aggiornamenti!
pane-zen-marketplace-title = Negozio dei temi
zen-look-and-feel-legacy-toolbar = 
    .label = Usa la posizione legacy della barra degli strumenti. Richiede il riavvio!
zen-theme-marketplace-link = Visita il negozio
zen-dark-theme-styles-header = Dark Theme Styles
zen-dark-theme-styles-description = Customize the dark theme to your liking
zen-dark-theme-styles-amoled = Amoled Black
zen-dark-theme-styles-default = Default Dark Theme
zen-dark-theme-styles-colorful = Colorful Dark Theme
pane-zen-CKS-title = Scorciatoie da tastiera
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = Scorciatoie da tastiera di { -brand-short-name }
zen-settings-CKS-header = Modifica le tue scorciatoie da tastiera
zen-settings-CKS-description = Imposta le scorciatoie da tastiera come preferisci e migliora la tua esperienza di navigazione
zen-settings-CKS-disable-firefox = 
    .label = Disattiva le scorciatoie da tastiera di default di { -brand-short-name }
zen-cks-group-tab-action = Azioni scheda
zen-cks-group-page-action = Azioni pagina
zen-cks-group-visible-action = Azioni visibili
zen-cks-group-history-action = Azioni cronologia
zen-cks-group-search-action = Azioni ricerca
zen-cks-group-tools-action = Azioni strumenti
zen-cks-group-bookmark-action = Azioni preferiti
zen-cks-group-open-page-action = Apri le azioni pagina
zen-cks-group-downloads-action = Azioni download
zen-cks-group-sidebar-action = Azioni barra laterale
zen-cks-group-compact-mode-action = Azioni modalità compatta
zen-cks-group-split-view-action = Azioni vista divisa
zen-cks-group-workspace-action = Azioni spazio di lavoro
open-new-tab = Apri nuova scheda
close-tab = Chiudi scheda
open-new-window = Apri nuova finestra
open-new-private-window = Apri nuova finestra privata
close-window = Chiudi finestra
restore-last-tab = Ripristina ultima scheda
restore-last-window = Ripristina ultima finestra
show-next-tab = Mostra scheda successiva
show-previous-tab = Mostra scheda precedente
show-all-tabs-panel = Mostra pannello tutte le schede
send-with-mail = Invia la pagina tramite e-mail
save-page = Salva pagina
print-page = Stampa pagina
mute-current-tab = Silenzia scheda attuale
show-source-of-page = Mostra la sorgente della pagina
show-page-info = Mostra informazioni pagina
zoom-in = Zoom avanti
zoom-out = Zoom indietro
reset-zoom = Resetta zoom
back = Indietro
forward = Avanti
stop = Stop
reload = Ricarica
force-reload = Forza ricarica
search-in-this-page = Cerca in questa pagina
show-next-search-result = Mostra prossimo risultato di ricerca
show-previous-search-result = Mostra il precedente risultato di ricerca
search-the-web = Cerca nel web
open-migration-wizard = Apri procedura guidata di migrazione
quit-from-application = Chiudi l'applicazione
enter-into-customize-mode = Entra modalità personalizzazione
enter-into-offline-mode = Entra modalità offline
open-screen-capture = Apri cattura schermo
bookmark-this-page = Aggiungi questa pagina ai segnalibri
open-bookmark-add-tool = Open Bookmark Add Tool
open-bookmarks-manager = Apri manager dei segnalibri
toggle-bookmark-toolbar = Attiva/disattiva barra dei segnalibri
open-general-preferences = Apri impostazioni generali
open-privacy-preferences = Apri impostazioni di privacy
open-workspaces-preferences = Apri impostazioni spazi di lavoro
open-containers-preferences = Apri impostazioni contenitori
open-search-preferences = Apri impostazioni di ricerca
open-sync-preferences = Apri impostazioni di sincronizzazione
open-task-manager = Apri il task manager
open-addons-manager = Apri il manager delle estensioni
open-home-page = Apri l'home page
forget-history = Dimentica cronologia
quick-forget-history = Dimentica cronologia veloce
clear-recent-history = Cancella cronologia recente
restore-last-session = Recupera ultima sessione
search-history = Cronologia di ricerca
manage-history = Manage History
open-downloads = Apri i download
show-bookmark-sidebar = Mostra barra laterale dei segnalibri
show-history-sidebar = Mostra barra laterale della cronologia
show-synced-tabs-sidebar = Show Synced Tabs Sidebar
reverse-sidebar = Reverse Sidebar Position
hide-sidebar = Nascondi barra laterale
toggle-sidebar = Attiva/disattiva barra laterale
zen-toggle-web-panels = Attiva/disattiva pannelli web
zen-toggle-compact-mode = Attiva/disattiva modalità compatta
zen-toggle-compact-mode-sidebar = Attiva/disattiva barra laterale in modalità compatta
zen-toggle-compact-mode-toolbar = Attiva/disattiva barra degli strumenti in modalità compatta
zen-change-workspace = Cicla tra spazi di lavoro
zen-split-view-grid = Griglia vista divisa
zen-split-view-vertical = Vista divisa verticale
zen-split-view-horizontal = Vista divisa orizzontale
zen-split-view-close = Chiudi vista divisa
zen-expand-sidebar = Toggle Sidebar Expand
