pane-zen-looks-title = Utseende och känsla
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Att ändra standardspråk kan göra det lättare för webbplatser att spåra dig.
zen-look-and-feel-colors-header = Välj ett temafärg
zen-look-and-feel-colors-description = Få { -brand-short-name } att se ut och kännas som du vill
zen-look-and-feel-themed-toolbar = 
    .label = Gör verktygsfältet tematiskt med accentfärgen
pane-zen-side-panels-title = Sidopaneler
zen-side-panels-header = Allmänna inställningar för webbpaneler
zen-side-panels-description = Öka produktiviteten genom att ha flera vyer samtidigt!
zen-side-panels-enabled = 
    .label = Aktivera Webbsidepaneler
zen-side-panels-close-on-blur = 
    .label = Stäng panelen när den tappar fokus om den inte är fäst
zen-look-and-feel-compact-view-header = Visa i kompakt vy
zen-look-and-feel-compact-view-description = Visa endast de verktygsfält du använder!
zen-look-and-feel-compact-view-enabled = 
    .label = Aktivera { -brand-short-name }'s kompakta läge
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Dölj det övre verktygsfältet även i kompakt läge
zen-look-and-feel-buttons-header = Knapputsende
zen-look-and-feel-buttons-description = Välj stilen på knapparna du vill se
zen-look-and-feel-pilled-buttons = 
    .label = Rundade knappar
pane-zen-workspaces-title = Arbetsytor
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = Arbetsytor
pane-zen-workspaces-header = Arbetsytor
zen-settings-workspaces-header = Allmänna inställningar för arbetsytor
zen-settings-workspaces-description = Med arbetsytor kan du ha flera webbläsarsessioner samtidigt!
zen-settings-workspaces-enabled = 
    .label = Aktivera arbetsytor (experimentell)
pane-zen-theme-title = Temainställningar
zen-vertical-tabs-title = Sidopanel och fliklayout
zen-vertical-tabs-header = Vertikala flikar
zen-vertical-tabs-description = Hantera dina flikar i en vertikal layout
zen-vertical-tabs-show-expand-button = 
    .label = Visa expanderingsknapp
zen-vertical-tabs-expand-tabs-by-default = Expandera flikar som standard
zen-vertical-tabs-dont-expand-tabs-by-default = Expandera inte flikar som standard
zen-vertical-tabs-expand-tabs-on-hover = Expandera flikar vid hovring (Fungerar inte i kompakt läge)
zen-vertical-tabs-expand-tabs-header = Hur man expanderar flikar
zen-vertical-tabs-expand-tabs-description = Välj hur du vill expandera flikar i sidopanelen
zen-theme-marketplace-header = Temamarknad
zen-theme-marketplace-description = Hitta och installera teman från marknaden.
zen-theme-marketplace-remove-button = 
    .label = Ta bort tema
zen-theme-marketplace-link = Besök marknad
pane-zen-CKS-title = Kortkommandon
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } Kortkommandon
zen-settings-CKS-header = Anpassa dina kortkommandon
zen-settings-CKS-description = Ändra standardkortkommandon till din smak och förbättra din webbläsarupplevelse
zen-settings-CKS-disable-firefox = 
    .label = Inaktivera { -brand-short-name }'s standardkortkommandon
zen-cks-group-tab-action = Flikåtgärder
zen-cks-group-page-action = Sidaåtgärder
zen-cks-group-visible-action = Synliga åtgärder
zen-cks-group-history-action = Historikåtgärder
zen-cks-group-search-action = Söka åtgärder
zen-cks-group-tools-action = Verktygåtgärder
zen-cks-group-bookmark-action = Bokmärkeåtgärder
zen-cks-group-open-page-action = Öppna sida åtgärder
zen-cks-group-downloads-action = Nedladdningar åtgärder
zen-cks-group-sidebar-action = Sidopanel åtgärder
zen-cks-group-compact-mode-action = Kompakt läge åtgärder
zen-cks-group-split-view-action = Delad vy åtgärder
zen-cks-group-workspace-action = Arbetsyta åtgärder
open-new-tab = Öppna ny flik
close-tab = Stäng flik
open-new-window = Öppna nytt fönster
open-new-private-window = Öppna nytt privat fönster
close-window = Stäng fönster
restore-last-tab = Återställ senaste flik
restore-last-window = Återställ senaste fönster
show-next-tab = Visa nästa flik
show-previous-tab = Visa föregående flik
show-all-tabs-panel = Visa alla flikpanel
send-with-mail = Skicka sida med e-post
save-page = Spara sida
print-page = Skriv ut sida
mute-current-tab = Stäng av ljudet på aktuell flik
show-source-of-page = Visa källa till sidan
show-page-info = Visa sidinformation
zoom-in = Zooma in
zoom-out = Zooma ut
reset-zoom = Återställ zoom
back = Tillbaka
forward = Framåt
stop = Stoppa
reload = Ladda om
force-reload = Tvinga omladdning
search-in-this-page = Sök på denna sida
show-next-search-result = Visa nästa sökresultat
show-previous-search-result = Visa föregående sökresultat
search-the-web = Sök på nätet
open-migration-wizard = Öppna migrationsguide
quit-from-application = Avsluta applikation
enter-into-customize-mode = Gå in i anpassningsläge
enter-into-offline-mode = Gå in i offlineläge
open-screen-capture = Öppna skärmdump
bookmark-this-page = Bokmärk denna sida
open-bookmark-add-tool = Öppna bokmärkesverktyg
open-bookmarks-manager = Öppna bokmärkeshanterare
toggle-bookmark-toolbar = Växla bokmärkesverktygsfält
open-general-preferences = Öppna allmänna inställningar
open-privacy-preferences = Öppna sekretessinställningar
open-workspaces-preferences = Öppna arbetsytor inställningar
open-containers-preferences = Öppna behållare inställningar
open-search-preferences = Öppna sökinställningar
open-sync-preferences = Öppna synkroniseringsinställningar
open-task-manager = Öppna aktivitetshanteraren
open-addons-manager = Öppna tilläggshanteraren
open-home-page = Öppna startsida
forget-history = Glöm historik
quick-forget-history = Snabb glöm historik
clear-recent-history = Rensa senaste historiken
restore-last-session = Återställ senaste session
search-history = Sök i historik
manage-history = Hantera historik
open-downloads = Öppna nedladdningar
show-bookmark-sidebar = Visa bokmärkessidopanel
show-history-sidebar = Visa historik sidopanel
show-synced-tabs-sidebar = Visa synkade flikar sidopanel
reverse-sidebar = Omvänd sidopanelposition
hide-sidebar = Dölj sidopanel
toggle-sidebar = Växla sidopanel
zen-toggle-web-panels = Växla webbpaneler
zen-toggle-compact-mode = Växla kompakt läge
zen-toggle-compact-mode-sidebar = Växla kompakt läge sidopanel
zen-toggle-compact-mode-toolbar = Växla kompakt läge verktygsfält
zen-change-workspace = Växla arbetsytor
zen-split-view-grid = Delad vy rutnät
zen-split-view-vertical = Delad vy vertikal
zen-split-view-horizontal = Delad vy horisontell
zen-split-view-close = Stäng delad vy