pane-zen-looks-title = Utseende och Känsla
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Att ändra standardspråket kan göra det lättare för Webbplatser att spåra dig.
zen-look-and-feel-colors-header = Välj temafärg
zen-look-and-feel-colors-description = Gör { -brand-short-name } så som du vill att det ska se ut och upplevas
zen-look-and-feel-themed-toolbar = 
    .label = Gör verktygsfältet tematiserat med accentfärgen
pane-zen-side-panels-title = Webbpaneler På Sidan
zen-side-panels-header = Allmänna inställningar för webbpaneler
zen-side-panels-description = Öka produktiviteten genom att ha flera vyer samtidigt!
zen-side-panels-enabled = 
    .label = Aktivera Webbsidopaneler
zen-side-panels-close-on-blur = 
    .label = Stäng panelen när den förlorar fokus om den inte är fastnålad
zen-vertical-tabs-show-bottom-border = 
    .label = Visa kantlinje för de nedre ikonerna
sync-currently-syncing-workspaces = Arbetsytor
sync-engine-workspaces = 
    .label = Arbetsytor
    .tooltiptext = Synkronisera dina arbetsytor mellan enheter
    .accesskey = W
zen-look-and-feel-compact-view-header = Visa i kompakt vy
zen-look-and-feel-compact-view-description = Visa endast de verktygsfält du använder!
zen-look-and-feel-compact-view-enabled = 
    .label = Aktivera { -brand-short-name }s kompakta läge
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Dölj också den övre verktygsraden i kompakta läget
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Visa verktygsfältet kortvarigt vid byte eller öppning av nya flikar i kompakt läge
zen-look-and-feel-buttons-header = Knapparnas stil
zen-look-and-feel-buttons-description = Välj den stil av knappar du vill se
zen-look-and-feel-pilled-buttons = 
    .label = Runda Knappar
pane-zen-tabs-title = Flikhantering
category-zen-workspaces = 
    .tooltiptext = { pane-zen-tabs-title }
pane-settings-workspaces-title = Arbetsytor
pane-zen-tabs-unloader-title = Flikavlastare
zen-tabs-unloader-header = Allmänna inställningar för flikavlastaren
zen-tabs-unloader-description = Avlasta oanvända flikar automatiskt för att spara minne
zen-tabs-unloader-enabled = 
    .label = Aktivera flikavlastaren
zen-tabs-unloader-unload-delay = 
    .label = Avlasta flikar efter
zen-tabs-unloader-unload-delay-description = Tiden i minuter efter vilken flikar kommer att avlastas
pane-zen-pinned-tab-manager-title = Pinned Tabs
zen-pinned-tab-manager-header = General settings for pinned tabs
zen-pinned-tab-manager-description = Manage additional behavior of pinned tabs
zen-pinned-tab-manager-restore-pinned-tabs-to-pinned-url = 
    .label = Restore pinned tabs to their originally pinned URL on startup
zen-pinned-tab-manager-close-shortcut-behavior-label = Close Tab Shortcut Behavior
zen-pinned-tab-manager-reset-unload-switch-close-shortcut-option = 
    .label = Reset URL, unload and switch to next tab
zen-pinned-tab-manager-unload-switch-close-shortcut-option = 
    .label = Unload and switch to next tab
zen-pinned-tab-manager-reset-switch-close-shortcut-option = 
    .label = Reset URL and switch to next tab
zen-pinned-tab-manager-switch-close-shortcut-option = 
    .label = Switch to next tab
zen-pinned-tab-manager-reset-close-shortcut-option = 
    .label = Reset URL
zen-pinned-tab-manager-close-close-shortcut-option = 
    .label = Close tab
pane-zen-workspaces-header = Arbetsytor
zen-settings-workspaces-header = Allmänna inställningar för arbetsytor
zen-settings-workspaces-description = Med arbetsytor kan du ha flera webbläsarsessioner samtidigt!
zen-settings-workspaces-enabled = 
    .label = Aktivera Arbetsytor (Experimentell)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Dölj standardbehållarens indikator i flikfältet
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Tillåt arbetsytor att ha sina egna fästa flikar
zen-key-unsafed = Osparad genväg! Vänligen spara den genom att klicka på "Escape"-tangenten efter att du återigen har angett den.
zen-key-conflict = Konflikt med en annan genväg
pane-zen-theme-title = Tema Inställningar
zen-vertical-tabs-title = Sidofält och fliklayout
zen-vertical-tabs-header = Vertikala Flikar
zen-vertical-tabs-description = Hantera dina flikar i ett vertikalt läge
zen-vertical-tabs-show-expand-button = 
    .label = Visa Expandera-Knapp
zen-vertical-tabs-expand-tabs-by-default = Utöka Flikar som Standard
zen-vertical-tabs-dont-expand-tabs-by-default = Utöka Inte Flikar som Standard
zen-vertical-tabs-expand-tabs-on-hover = Expand Tabs on Hover (Won't work on compact mode)
zen-vertical-tabs-expand-tabs-header = Hur man utökar flikar
zen-vertical-tabs-expand-tabs-description = Välj hur du vill utöka flikarna i sidofältet
zen-theme-marketplace-header = Zen Mods
zen-theme-disable-all-enabled = 
    .title = Disable all themes
zen-theme-disable-all-disabled = 
    .title = Enable all themes
zen-theme-marketplace-description = Hitta och installera teman från butiken.
zen-theme-marketplace-remove-button = 
    .label = Ta bort Tema
zen-theme-marketplace-check-for-updates-button = 
    .label = Kontrollera efter Uppdateringar
zen-theme-marketplace-updates-success = Temat uppdaterades
zen-theme-marketplace-updates-fail = Hittade inga uppdateringar!
zen-theme-marketplace-toggle-enabled-button = 
    .title = Inaktivera Tema
zen-theme-marketplace-toggle-disabled-button = 
    .title = Aktivera Tema
zen-theme-marketplace-remove-confirmation = Är du säker på att du vill ta bort denna mod?
zen-theme-marketplace-close-modal = Stäng
zen-theme-marketplace-theme-header-title = 
    .title = CSS-väljare: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = Ingen
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Skriv något...
pane-zen-marketplace-title = Zen Mods
zen-settings-workspaces-display-as-icon-strip = 
    .label = Visa arbetsytor som en ikonrad
zen-settings-workspaces-force-container-tabs-to-workspace = 
    .label = Switch to workspace where container is set as default when opening container tabs
zen-settings-workspaces-hide-deactivated-workspaces = 
    .label = Hide deactivated workspaces
zen-theme-marketplace-link = Visit Store
zen-dark-theme-styles-header = Mörka Teman
zen-dark-theme-styles-description = Anpassa det mörka temat efter dina önskemål
zen-dark-theme-styles-amoled = Natt-tema
zen-dark-theme-styles-default = Standard Mörkt Tema
zen-dark-theme-styles-colorful = Färgglatt Mörkt Tema
zen-split-view-title = Delad Vy
zen-split-view-header = Funktionalitet för delad vy
zen-split-view-description = Dela din webbläsare i flera vyer, vilket gör att du kan surfa på flera webbplatser samtidigt
zen-split-view-change-on-hover = 
    .label = Byt flikar vid hovring
zen-compact-mode-styles-left = Dölj Flikfältet
zen-compact-mode-styles-top = Dölj Översta Fältet
zen-compact-mode-styles-both = Dölj Båda
pane-zen-CKS-title = Keyboard Shortcuts
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } Keyboard Shortcuts
zen-settings-CKS-header = Customize your keyboard shortcuts
zen-settings-CKS-description = Change the default keyboard shortcuts to your liking and improve your browsing experience
zen-settings-CKS-disable-firefox = 
    .label = Disable { -brand-short-name }'s default keyboard shortcuts
zen-settings-CKS-duplicate-shortcut = 
    .label = Duplicera Genväg
zen-settings-CKS-reset-shortcuts = 
    .label = Återställ till Standard
zenCKSOption-group-other = Övrigt
zenCKSOption-group-windowAndTabManagement = Fönster & Flikhantering
zenCKSOption-group-navigation = Navigering
zenCKSOption-group-searchAndFind = Sök & Hitta
zenCKSOption-group-pageOperations = Operationer för Sidor
zenCKSOption-group-historyAndBookmarks = Historik & Bokmärken
zenCKSOption-group-mediaAndDisplay = Media & Visning
zenCKSOption-group-zen-compact-mode = Kompakt Läge
zenCKSOption-group-zen-workspace = Arbetsytor
zenCKSOption-group-zen-other = Övriga Zen Funktioner
zenCKSOption-group-zen-split-view = Delad Vy
zen-key-quick-restart = Snabb Omstart
zen-window-new-shortcut = Nytt Fönster
zen-tab-new-shortcut = Ny Flik
zen-key-redo = Gör om
zen-restore-last-closed-tab-shortcut = Återställ Senaste Stängda Flik
zen-location-open-shortcut = Öppna Plats
zen-location-open-shortcut-alt = Öppna Plats (Alt)
zen-key-undo-close-window = Ångra Stängning av Fönster
zen-text-action-undo-shortcut = Ångra
zen-text-action-redo-shortcut = Gör om
zen-text-action-cut-shortcut = Klipp ut
zen-text-action-copy-shortcut = Kopiera
zen-text-action-paste-shortcut = Klistra in
zen-text-action-select-all-shortcut = Markera Alla
zen-text-action-delete-shortcut = Radera
zen-history-show-all-shortcut-mac = Visa All Historik (Mac)
zen-full-screen-shortcut = Växla Helskärm
zen-reader-mode-toggle-shortcut-windows = Växla Läsläge (Windows)
zen-picture-in-picture-toggle-shortcut-alt = Växla Bild-i-Bild (Alt)
zen-picture-in-picture-toggle-shortcut-mac = Växla Bild-i-Bild (Mac)
zen-picture-in-picture-toggle-shortcut-mac-alt = Växla Bild-i-Bild (Mac Alt)
zen-page-source-shortcut-safari = Visa Sidkälla (Safari)
zen-nav-stop-shortcut = Stoppa Inläsning
zen-history-sidebar-shortcut = Visa Sidofält för Historik
zen-window-minimize-shortcut = Minimera Fönster
zen-help-shortcut = Öppna Hjälp
zen-preferences-shortcut = Öppna Preferenser
zen-hide-app-shortcut = Dölj Applikation
zen-hide-other-apps-shortcut = Dölj Andra Applikationer
zen-search-focus-shortcut = Fokusera Sökning
zen-search-focus-shortcut-alt = Fokusera Sökning (Alt)
zen-downloads-shortcut = Öppna Hämtningar
zen-addons-shortcut = Öppna Tillägg
zen-file-open-shortcut = Öppna Fil
zen-save-page-shortcut = Spara Sida
zen-print-shortcut = Skriv ut Sidan
zen-close-shortcut-2 = Stäng Flik
zen-mute-toggle-shortcut = Växla Ljudavstängning
zen-key-delete = Delete-tangenten
zen-key-go-back = Gå Tillbaka
zen-key-go-forward = Gå Framåt
zen-nav-back-shortcut-alt = Navigera Tillbaka (Alt)
zen-nav-fwd-shortcut-alt = Navigera Framåt (Alt)
zen-history-show-all-shortcut = Visa All Historik
zen-key-enter-full-screen = Helskärm
zen-key-exit-full-screen = Avsluta Helskärm
zen-reader-mode-toggle-shortcut-other = Växla Läsläge
zen-picture-in-picture-toggle-shortcut = Växla Bild-i-Bild
zen-nav-reload-shortcut-2 = Ladda Om Sidan
zen-key-about-processes = Om Processer
zen-page-source-shortcut = Visa Sidkälla
zen-page-info-shortcut = Visa Sidinformation
zen-find-shortcut = Sök på Sidan
zen-search-find-again-shortcut = Sök Igen
zen-search-find-again-shortcut-prev = Sök Föregående
zen-search-find-again-shortcut-2 = Sök Igen (Alt)
zen-bookmark-this-page-shortcut = Bokmärk Denna Sidan
zen-bookmark-show-library-shortcut = Visa Bokmärkeshanteraren
zen-key-stop = Stoppa Inläsning
zen-full-zoom-reduce-shortcut = Zooma Ut
zen-full-zoom-enlarge-shortcut = Zooma In
zen-full-zoom-reset-shortcut = Återställ Zoom
zen-bidi-switch-direction-shortcut = Växla Textriktning
zen-private-browsing-shortcut = Privat Webbläsning
zen-screenshot-shortcut = Ta Skärmdump
zen-key-sanitize = Rensa Webbläsardata
zen-quit-app-shortcut = Avsluta Applikationen
zen-key-wr-capture-cmd = WR Fånga Kommando
zen-key-wr-toggle-capture-sequence-cmd = Växla WR Fångstsekvens
zen-nav-reload-shortcut = Ladda Om Sidan
zen-nav-reload-shortcut-skip-cache = Ladda Om Sidan (Hoppa Över Cache)
zen-close-shortcut = Stäng Fönster
zen-close-tab-shortcut = Stäng Flik
zen-compact-mode-shortcut-show-sidebar = Växla Flytande Sidofält
zen-compact-mode-shortcut-show-toolbar = Växla Flytande Verktygsrad
zen-compact-mode-shortcut-toggle = Växla Kompakt Läge
zen-workspace-shortcut-switch-1 = Byt till Arbetsyta 1
zen-workspace-shortcut-switch-2 = Byt till Arbetsyta 2
zen-workspace-shortcut-switch-3 = Byt till Arbetsyta 3
zen-workspace-shortcut-switch-4 = Byt till Arbetsyta 4
zen-workspace-shortcut-switch-5 = Byt till Arbetsyta 5
zen-workspace-shortcut-switch-6 = Byt till Arbetsyta 6
zen-workspace-shortcut-switch-7 = Byt till Arbetsyta 7
zen-workspace-shortcut-switch-8 = Byt till Arbetsyta 8
zen-workspace-shortcut-switch-9 = Byt till Arbetsyta 9
zen-workspace-shortcut-switch-10 = Byt till Arbetsyta 10
zen-workspace-shortcut-forward = Framåt Arbetsyta
zen-workspace-shortcut-backward = Bakåt Arbetsyta
zen-web-panel-shortcut-toggle = Växla Webbpanel
zen-sidebar-shortcut-toggle = Växla Sidofältets Bredd
zen-pinned-tab-shortcut-reset = Reset Pinned Tab to Pinned URL
zen-split-view-shortcut-grid = Växla Delad Vy-Rutnät
zen-split-view-shortcut-vertical = Växla Delad Vy Vertikalt
zen-split-view-shortcut-horizontal = Växla Delad Vy Horisontellt
zen-split-view-shortcut-unsplit = Stäng Delad Vy
zen-key-select-tab-1 = Välj flik #1
zen-key-select-tab-2 = Välj flik #2
zen-key-select-tab-3 = Välj flik #3
zen-key-select-tab-4 = Välj flik #4
zen-key-select-tab-5 = Välj flik #5
zen-key-select-tab-6 = Välj flik #6
zen-key-select-tab-7 = Välj flik #7
zen-key-select-tab-8 = Välj flik #8
zen-key-select-tab-last = Välj sista flik
zen-key-show-all-tabs = Visa alla flikar
zen-key-goto-history = Gå till historik
zen-key-go-home = Gå Hem
zen-bookmark-show-sidebar-shortcut = Visa Sidofält för Bokmärken
zen-bookmark-show-toolbar-shortcut = Visa Verktygsrad för Bokmärken
