zen-panel-ui-current-profile-text = dabartinis profilis
unified-extensions-description = Plėtiniai naudojami norint į „{ -brand-short-name }“ įtraukti daugiau papildomų funkcijų.
tab-context-zen-reset-pinned-tab = 
    .label = Atkurti prisegtą kortelę
    .accesskey = R
tab-context-zen-add-essential = 
    .label = Pridėti prie būtiniausių
    .accesskey = E
tab-context-zen-remove-essential = 
    .label = Šalinti iš būtiniausių
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Pakeisti prisegtą URL adresą dabartiniu
    .accesskey = C
tab-zen-unload = 
    .label = Iškelti kortelę
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Kortelių iškelėtojo veiksmai
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Neleisti iškelti kortelės
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Leisti kortelės iškėlimą
    .accesskey = I
zen-themes-corrupted = Jūsų „{ -brand-short-name }“ modifikacijos failas sugadintas. Jie buvo atkurti į numatytąją temą.
zen-panel-ui-gradient-generator-opacity-text = Kontrastas
zen-panel-ui-gradient-generator-texture-text = Tekstūra
zen-panel-ui-gradient-generator-custom-color = Pasirinktinė spalva
zen-panel-ui-gradient-generator-saved-message = Gradientas sėkmingai išsaugotas.
zen-copy-current-url-confirmation = URL buvo nukopijuotas į iškarpinę.
zen-rice-share-name = 
    .placeholder = Rice Name
zen-rice-share-author = By
zen-rice-share-author-input = 
    .placeholder = Your Name
zen-rice-share-cancel = Cancel
zen-rice-share-save = Share
zen-rice-share-include-userchrome = 
    .label = Include userChrome.css
zen-rice-share-include-usercontent = 
    .label = Include userContent.css
zen-rice-share-include-mods = 
    .label = Include enabled mods
zen-rice-share-include-mod-prefs = 
    .label = Include mod preferences
zen-rice-share-include-preferences = 
    .label = Include layout state
zen-rice-share-include-workspace-themes = 
    .label = Include workspace gradient themes
zen-rice-share-include = Export Options
