zen-panel-ui-current-profile-text = dabartinis profilis
unified-extensions-description = Plėtiniai naudojami norint į „{ -brand-short-name }“ įtraukti daugiau papildomų funkcijų.
tab-context-zen-reset-pinned-tab = 
    .label = Atkurti prisegtą kortelę
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Pakeisti prisegtą URL adresą dabartiniu
    .accesskey = C
tab-zen-unload = 
    .label = Iškelti kortelę
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Kortelių iškelėtojo veiksmai
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Neleisti iškelti kortelės
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Leisti kortelės iškėlimą
    .accesskey = I
zen-themes-corrupted = Your { -brand-short-name } mods file is corrupted. They have been reset to the default theme.
