zen-panel-ui-workspaces-text = Darbo sritys
zen-panel-ui-workspaces-create-text = Kurti darbo sritį
zen-panel-ui-workspaces-create-save = 
    .label = Kurti darbo sritį
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = Atšaukti
    .accesskey = C
zen-panel-ui-workspaces-edit-text = Redaguoti darbo sritį
zen-panel-ui-workspaces-edit-save = 
    .label = Įrašyti pakeitimus
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Atšaukti
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Ištrinti darbo sritį
    .accesskey = D
zen-workspaces-panel-change-name = 
    .label = Keisti pavadinimą
zen-workspaces-panel-change-icon = 
    .label = Change Icon
zen-workspaces-panel-context-manage = 
    .label = Manage Workspaces
    .accesskey = M
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Nustatyti numatytąją konteinerį
    .accesskey = O
zen-workspaces-change-gradient = 
    .label = Keisti temos spalvas
    .accesskey = C
zen-workspaces-panel-context-open = 
    .label = Atverti darbo sritį
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Nustatyti kaip numatytąją darbo sritį
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Redaguoti darbo sritį
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Keisti kortelę (-es) į darbo sritį
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Darbo sritys
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Papildomas
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Skaidymas
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Analoginis
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Triadinis
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Slankusis
zen-panel-ui-gradient-click-to-add = Spustelėkite, kad pridėtumėte spalvą
