zen-toolbar-context-tabs-right = 
    .label = Kortelės dešinėje
    .accesskey = R
zen-toolbar-context-compact-mode = 
    .label = Kompaktinis režimas
    .accesskey = C
zen-toolbar-context-compact-mode-enable = 
    .label = Įjungti kompaktinį režimą
    .accesskey = D
zen-toolbar-context-compact-mode-just-tabs = 
    .label = Slėpti šoninę juostą
zen-toolbar-context-compact-mode-just-toolbar = 
    .label = Slėpti įrankių juostą
zen-toolbar-context-compact-mode-hide-both = 
    .label = Slėpti abiejus
    .accesskey = H
sidebar-zen-sidepanel = 
    .label = Šoniniai skydeliai
sidebar-zen-expand = 
    .label = Išskleisti šoninę juostą
