zen-panel-ui-current-profile-text = dabartinis profilis
unified-extensions-description = Plėtiniai naudojami norint į „{ -brand-short-name }“ įtraukti daugiau papildomų funkcijų.
tab-context-zen-reset-pinned-tab = 
    .label = Atkurti prisegtą kortelę
    .accesskey = R
tab-context-zen-add-essential = 
    .label = Add to Essentials
    .accesskey = E
tab-context-zen-remove-essential = 
    .label = Remove from Essentials
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Pakeisti prisegtą URL adresą dabartiniu
    .accesskey = C
tab-zen-unload = 
    .label = Iškelti kortelę
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Kortelių iškelėtojo veiksmai
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Neleisti iškelti kortelės
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Leisti kortelės iškėlimą
    .accesskey = I
zen-themes-corrupted = Jūsų „{ -brand-short-name }“ modifikacijų failas sugadintas. Jie buvo atkurti į numatytąją temą.
zen-panel-ui-gradient-generator-opacity-text = Kontrastas
zen-panel-ui-gradient-generator-texture-text = Tekstūra
zen-panel-ui-gradient-generator-custom-color = Pasirinktinė spalva
zen-panel-ui-gradient-generator-saved-message = Gradientas sėkmingai išsaugotas.
