zen-panel-ui-workspaces-text = Spaces
zen-panel-ui-workspaces-create = 
    .label = Kurti erdvę
zen-workspaces-panel-context-delete = 
    .label = Delete Space
    .accesskey = D
zen-workspaces-panel-change-name = 
    .label = Keisti pavadinimą
zen-workspaces-panel-change-icon = 
    .label = Keisti piktogramą
zen-workspaces-panel-context-default-profile = 
    .label = Set Profile
zen-workspaces-how-to-reorder-title = How to reorder spaces
zen-workspaces-how-to-reorder-desc = Drag the space icons at the bottom of the sidebar to reorder them
zen-workspaces-change-theme = 
    .label = Redaguoti temą
zen-workspaces-panel-context-open = 
    .label = Atverti darbo sritį
    .accesskey = O
zen-workspaces-panel-context-edit = 
    .label = Edit Space
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Keisti kortelę (-es) į darbo sritį
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Darbo sritys
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Papildomas
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Skaidymas
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Analoginis
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Triadinis
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Slankusis
zen-panel-ui-gradient-click-to-add = Spustelėkite, kad pridėtumėte spalvą
zen-workspace-creation-name = 
    .placeholder = Erdvės pavadinimas
zen-workspaces-panel-context-reorder = 
    .label = Reorder Spaces
zen-workspace-creation-profile = Profilis
    .tooltiptext = Profiliai naudojami atskirti slapukus ir svetainės duomenis tarp erdvių.
zen-workspace-creation-header = Create a Space
zen-workspace-creation-label = Erdvės naudojamos tvarkyti jūsų korteles ir seansus.
zen-workspaces-delete-workspace-title = Delete Space?
zen-workspaces-delete-workspace-body = Are you sure you want to delete this space? This action cannot be undone.
