zen-panel-ui-current-window-text = Janela atual
zen-panel-ui-workspaces-text = Outros Espaços de Trabalho
zen-panel-ui-workspaces-create-text = Criar Espaço de Trabalho
zen-panel-ui-workspaces-create-save = 
    .label = Criar Espaço de Trabalho
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = Cancelar
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Excluir Espaço de Trabalho
    .accesskey = D
zen-workspaces-panel-context-open = 
    .label = Abrir Espaço de Trabalho
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Definir como Área de Trabalho Padrão
    .accesskey = S
context-zen-change-workspace-tab = 
    .label = Mover Aba(s) para Espaço de Trabalho
    .accesskey = C
