zen-panel-ui-current-profile-text = perfil atual
unified-extensions-description = As extensões são usadas para trazer mais funcionalidades extras para o { -brand-short-name }.
tab-zen-unload = 
    .label = Descarregar aba
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Ações de descarregador de abas
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Prevenir abas de descarregar
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Ignorar abas descarregadas
    .accesskey = I
