zen-panel-ui-current-profile-text = perfil atual
unified-extensions-description = As extensões são usadas para trazer mais funcionalidades extras para o { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = Redefinir aba fixada
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Substituir URL fixado com atual
    .accesskey = C
tab-zen-unload = 
    .label = Descarregar aba
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Ações de descarregador de abas
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Prevenir abas de descarregar
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Allow Tab Unload
    .accesskey = I
