zen-toolbar-context-tabs-right = 
    .label = Abas à direita
    .accesskey = R
zen-toolbar-context-compact-mode = 
    .label = Modo compacto
    .accesskey = C
zen-toolbar-context-compact-mode-enable = 
    .label = Ativar modo compacto
    .accesskey = D
zen-toolbar-context-compact-mode-just-tabs = 
    .label = Ocultar barra lateral
zen-toolbar-context-compact-mode-just-toolbar = 
    .label = Ocultar barra de ferramentas
zen-toolbar-context-compact-mode-hide-both = 
    .label = Ocultar ambos
    .accesskey = H
sidebar-zen-sidepanel = 
    .label = Painéis laterais
sidebar-zen-expand = 
    .label = Expandir barra lateral
