zen-panel-ui-current-profile-text = perfil atual
unified-extensions-description = As extensões são usadas para trazer mais recursos adicionais para o { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = Redefinir aba fixada
    .accesskey = R
tab-context-zen-pin-tab-global = 
    .label = Add tab to essentials
    .accesskey = P
tab-context-zen-replace-pinned-url-with-current = 
    .label = Substituir URL fixado com atual
    .accesskey = C
tab-zen-unload = 
    .label = Descarregar aba
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Ações de descarregador de abas
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Prevenir abas de descarregar
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Permitir descarregamento de abas
    .accesskey = I
zen-themes-corrupted = Seu arquivo de modificações { -brand-short-name } está corrompido. Eles foram redefinidos para o tem padrão.
zen-panel-ui-gradient-generator-opacity-text = Contraste
zen-panel-ui-gradient-generator-texture-text = Textura
zen-panel-ui-gradient-generator-custom-color = Cor personalizada
zen-panel-ui-gradient-generator-saved-message = Gradiente salvo com sucesso!
