zen-web-side-panel-context-mute-panel = 
    .label = Silenciar Painel Web
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = Reativar som do Painel Web
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = Desativar UserAgent Móvel
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Ativar UserAgent Móvel
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = Descarregar Painel Web
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = Excluir Painel Web
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = Abrir em uma nova aba
    .accesskey = N
zen-web-side-panel-context-add-to-panel = 
    .label = Adicionar aos painéis web
    .accesskey = A
zen-sidebar-introduction-title = Bem-vindo ao Zen Sidebar
zen-sidebar-introduction-description = A Zen Sidebar é uma nova forma de navegar na web. Clique em qualquer um dos ícones para abrir um painel web.
