zen-panel-ui-workspaces-text = Projetos
zen-panel-ui-workspaces-create = 
    .label = Create Space
zen-workspaces-panel-context-delete = 
    .label = Excluir Projeto
    .accesskey = D
zen-workspaces-panel-change-name = 
    .label = Change Name
zen-workspaces-panel-change-icon = 
    .label = Change Icon
zen-workspaces-panel-context-default-profile = 
    .label = Set Profile
zen-workspaces-how-to-reorder-title = How to reorder spaces
zen-workspaces-how-to-reorder-desc = Drag the space icons at the bottom of the sidebar to reorder them
zen-workspaces-change-theme = 
    .label = Edit Theme
zen-workspaces-panel-context-open = 
    .label = Abrir espaço de trabalho
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Definir como Espaço de Trabalho Padrão
    .accesskey = S.O.
zen-workspaces-panel-context-edit = 
    .label = Editar Projeto
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Alterar aba(s) para espaço de trabalho
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Espaços de trabalho
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Complementar
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Dividir
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Analógico
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Três cores combinadas
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Flutuante
zen-panel-ui-gradient-click-to-add = Clique para adicionar uma cor
zen-workspace-creation-name = 
    .placeholder = Space Name
zen-workspaces-panel-context-reorder = 
    .label = Reorder Spaces
zen-workspace-creation-profile = Profile
    .tooltiptext = Profiles are used to separate cookies and site data between spaces.
zen-workspace-creation-header = Create a Space
zen-workspace-creation-label = Spaces are used to organize your tabs and sessions.
zen-workspaces-delete-workspace-title = Delete Workspace?
zen-workspaces-delete-workspace-body = Are you sure you want to delete this workspace? This action cannot be undone.
