zen-panel-ui-workspaces-text = Projetos
zen-panel-ui-workspaces-create = 
    .label = Create Space
zen-panel-ui-workspaces-edit-text = Editar Projeto
zen-panel-ui-workspaces-edit-save = 
    .label = Salvar as alterações
    .accesskey = S.O.
zen-panel-ui-workspaces-edit-cancel = 
    .label = cancelar
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Excluir Projeto
    .accesskey = D
zen-workspaces-panel-change-name = 
    .label = Change Name
zen-workspaces-panel-change-icon = 
    .label = Change Icon
zen-workspaces-panel-context-manage = 
    .label = Manage Workspaces
    .accesskey = M
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Definir container padrão
    .accesskey = O
zen-workspaces-change-theme = 
    .label = Edit Theme
zen-workspaces-panel-context-open = 
    .label = Abrir espaço de trabalho
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Definir como Espaço de Trabalho Padrão
    .accesskey = S.O.
zen-workspaces-panel-context-edit = 
    .label = Editar Projeto
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Alterar aba(s) para espaço de trabalho
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Espaços de trabalho
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Complementar
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Dividir
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Analógico
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Três cores combinadas
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Flutuante
zen-panel-ui-gradient-click-to-add = Clique para adicionar uma cor
zen-workspace-creation-name = 
    .placeholder = Space Name
zen-workspace-creation-profile = Profile
    .tooltiptext = Profiles are used to separate cookies and site data between spaces.
zen-workspace-creation-title = Create a new Space
zen-workspace-creation-label = Spaces are used to organize your tabs and sessions.
