zen-panel-ui-workspaces-text = Työtilat
zen-panel-ui-workspaces-create-text = Luo työtila
zen-panel-ui-workspaces-create-save = 
    .label = Luo työtila
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = Peruuta
    .accesskey = C
zen-panel-ui-workspaces-edit-text = Muokkaa työtilaa
zen-panel-ui-workspaces-edit-save = 
    .label = Tallenna muutokset
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Peruuta
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Poista työtila
    .accesskey = D
zen-workspaces-panel-context-open = 
    .label = Avaa työtila
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Aseta oletustyötilaksi
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Muokkaa työtilaa
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Vaihda välilehti työtilaan
    .accesskey = C
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Aseta oletussäiliö
    .accesskey = O
