zen-web-side-panel-context-mute-panel = 
    .label = Mykistä selainpaneeli
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = Poista mykistys selainpaneelista
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = Disable Mobile UserAgent
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Enable Mobile UserAgent
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = Verkkopaneelin purkaminen
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = Poista verkkopaneeli
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = Avaa uudessa välilehdessä
    .accesskey = N
zen-web-side-panel-context-add-to-panel = 
    .label = Lisää verkkopaneeliin
    .accesskey = A
zen-sidebar-introduction-title = Tervetuloa Zen sivupalkkiin
zen-sidebar-introduction-description = Zen sivupalkki on uusi tapa selata verkkoa. Avaa verkkopaneeli painamalla mitä tahansa kuvaketta.
