zen-toolbar-context-tabs-right = 
    .label = Välilehdet oikealle
    .accesskey = R
zen-toolbar-context-compact-mode = 
    .label = Kompakti tila
    .accesskey = C
zen-toolbar-context-compact-mode-enable = 
    .label = Ota kompakti tila käyttöön
    .accesskey = D
zen-toolbar-context-compact-mode-just-tabs = 
    .label = Piilota sivupalkki
zen-toolbar-context-compact-mode-just-toolbar = 
    .label = Piilota työkalupalkki
zen-toolbar-context-compact-mode-hide-both = 
    .label = Piilota molemmat
    .accesskey = H
sidebar-zen-sidepanel = 
    .label = Sivu paneelit
sidebar-zen-expand = 
    .label = Laajenna sivupalkkia
