zen-panel-ui-current-profile-text = nykyinen profiili
unified-extensions-description = Laajennuksia käytetään tuomaan lisää lisätoimintoja { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = Reset Pinned Tab
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Replace Pinned URL with Current
    .accesskey = C
tab-zen-unload = 
    .label = Välehden purku
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Välehden purku toiminnot
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Estä välilehden purkaminen
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Älä huomioi välilehden purkamista
    .accesskey = I
