zen-panel-ui-workspaces-text = Työtilat
zen-panel-ui-workspaces-create-text = Luo Työtila
zen-panel-ui-workspaces-create-save = 
    .label = Luo Työtila
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = Peruuta
    .accesskey = C
zen-panel-ui-workspaces-edit-text = Muokkaa Työtilaa
zen-panel-ui-workspaces-edit-save = 
    .label = Tallenna Muutokset
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Peruuta
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Poista Työtila
    .accesskey = D
zen-workspaces-panel-change-name = 
    .label = Change Name
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Aseta Oletuskontti
    .accesskey = O
zen-workspaces-change-gradient = 
    .label = Vaihda Teeman Värit
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Työtilat
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Complementary
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Split
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Analogous
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Triadic
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Floating
zen-panel-ui-gradient-click-to-add = Click to add a color
