zen-panel-ui-current-profile-text = nykyinen profiili
unified-extensions-description = Laajennuksia käytetään tuomaan lisää lisätoimintoja { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = Resetoi kinnittetty välilehti
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Korvaa kiinnitetty URL nykyisellä osoitteella
    .accesskey = C
tab-zen-unload = 
    .label = Välehden purku
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Välehden purku toiminnot
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Estä välilehden purkaminen
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Allow Tab Unload
    .accesskey = I
