pane-zen-looks-title = Aparência
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Ao alterar o idioma padrão está-se a tormar mais rastreável.
zen-look-and-feel-colors-header = Escolha a cor do tema
zen-look-and-feel-colors-description = Faz com que o { -brand-short-name } tenha a aparência que prefere
zen-look-and-feel-themed-toolbar = 
    .label = Make the toolbar themed with the accent color
pane-zen-side-panels-title = Side Web Panels
zen-side-panels-header = General settings for web panels
zen-side-panels-description = Increase productivity by having multiple views at once!
zen-side-panels-enabled = 
    .label = Enable Web Side Panels
zen-side-panels-close-on-blur = 
    .label = Close the panel when it loses focus if it's not pinned
zen-vertical-tabs-show-bottom-border = 
    .label = Show border for the bottom icons
sync-currently-syncing-workspaces = Workspaces
sync-engine-workspaces = 
    .label = Workspaces
    .tooltiptext = Sync your workspaces across devices
    .accesskey = W
zen-look-and-feel-compact-view-header = Show in compact view
zen-look-and-feel-compact-view-description = Only show the toolbars you use!
zen-look-and-feel-compact-view-enabled = 
    .label = Enable { -brand-short-name }'s compact mode
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Hide the top toolbar as well in compact mode
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Faz um breve popup da barra de ferramentas ao alterar ou abrir novas abas no modo compacto
zen-look-and-feel-buttons-header = Button style
zen-look-and-feel-buttons-description = Choose the style of buttons you want to see
zen-look-and-feel-pilled-buttons = 
    .label = Pilled Buttons
pane-zen-tabs-title = Tab Management
category-zen-workspaces = 
    .tooltiptext = { pane-zen-tabs-title }
pane-settings-workspaces-title = Workspaces
pane-zen-tabs-unloader-title = Tab Unloader
zen-tabs-unloader-header = General settings for tab unloader
zen-tabs-unloader-description = Automatically unload unused tabs to save memory
zen-tabs-unloader-enabled = 
    .label = Enable Tab Unloader
zen-tabs-unloader-unload-delay = 
    .label = Unload tabs after
zen-tabs-unloader-unload-delay-description = The time in minutes after which tabs will be unloaded
pane-zen-pinned-tab-manager-title = Pinned Tabs
zen-pinned-tab-manager-header = General settings for pinned tabs
zen-pinned-tab-manager-description = Manage additional behavior of pinned tabs
zen-pinned-tab-manager-restore-pinned-tabs-to-pinned-url = 
    .label = Restore pinned tabs to their originally pinned URL on startup
zen-pinned-tab-manager-close-shortcut-behavior-label = Close Tab Shortcut Behavior
zen-pinned-tab-manager-reset-unload-switch-close-shortcut-option = 
    .label = Reset URL, unload and switch to next tab
zen-pinned-tab-manager-unload-switch-close-shortcut-option = 
    .label = Unload and switch to next tab
zen-pinned-tab-manager-reset-switch-close-shortcut-option = 
    .label = Reset URL and switch to next tab
zen-pinned-tab-manager-switch-close-shortcut-option = 
    .label = Switch to next tab
zen-pinned-tab-manager-reset-close-shortcut-option = 
    .label = Reset URL
zen-pinned-tab-manager-close-close-shortcut-option = 
    .label = Close tab
pane-zen-workspaces-header = Workspaces
zen-settings-workspaces-header = General settings for workspaces
zen-settings-workspaces-description = With workspaces, you can have multiple browsing sessions at once!
zen-settings-workspaces-enabled = 
    .label = Enable Workspaces (Experimental)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Hide the default container indicator in the tab bar
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Allow workspaces have their own pinned tabs
zen-key-unsafed = Unsaved shortcut! Please safe it by clicking the "Escape" key after retyping it.
zen-key-conflict = Conflict with another shortcut
pane-zen-theme-title = Theme Settings
zen-vertical-tabs-title = Sidebar and tabs layout
zen-vertical-tabs-header = Vertical Tabs
zen-vertical-tabs-description = Manage your tabs in a vertical layout
zen-vertical-tabs-show-expand-button = 
    .label = Show Expand Button
zen-vertical-tabs-expand-tabs-by-default = Expand Tabs by Default
zen-vertical-tabs-dont-expand-tabs-by-default = Don't Expand Tabs by Default
zen-vertical-tabs-expand-tabs-on-hover = Expand Tabs on Hover (Won't work on compact mode)
zen-vertical-tabs-expand-tabs-header = How to expand tabs
zen-vertical-tabs-expand-tabs-description = Choose how to expand tabs in the sidebar
zen-theme-marketplace-header = Zen Mods
zen-theme-disable-all-enabled = 
    .title = Disable all themes
zen-theme-disable-all-disabled = 
    .title = Enable all themes
zen-theme-marketplace-description = Find and install themes from the store.
zen-theme-marketplace-remove-button = 
    .label = Remove Theme
zen-theme-marketplace-check-for-updates-button = 
    .label = Check for Updates
zen-theme-marketplace-updates-success = Theme updated successfully
zen-theme-marketplace-updates-fail = Couldn't find any updates!
zen-theme-marketplace-toggle-enabled-button = 
    .title = Disable Theme
zen-theme-marketplace-toggle-disabled-button = 
    .title = Enable Theme
zen-theme-marketplace-remove-confirmation = Are you sure you want to remove this mod?
zen-theme-marketplace-close-modal = Close
zen-theme-marketplace-theme-header-title = 
    .title = CSS Selector: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = None
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Type something...
pane-zen-marketplace-title = Zen Mods
zen-settings-workspaces-display-as-icon-strip = 
    .label = Mostrar áreas de trabalho como tira de ícones
zen-settings-workspaces-force-container-tabs-to-workspace = 
    .label = Switch to workspace where container is set as default when opening container tabs
zen-settings-workspaces-hide-deactivated-workspaces = 
    .label = Ocultar áreas de trabalho desativadas
zen-theme-marketplace-link = Visit Store
zen-dark-theme-styles-header = Estilos de Tema Escuro
zen-dark-theme-styles-description = Personalize o tema escuro ao seu gosto
zen-dark-theme-styles-amoled = Tema Noturno
zen-dark-theme-styles-default = Tema Escuro Padrão
zen-dark-theme-styles-colorful = Tema Escuro Colorido
zen-split-view-title = Vista Dividida
zen-split-view-header = Funcionalidade de Vista Dividida
zen-split-view-description = Dividir o seu navegador em múltiplas vistas, permitindo navegar em várias páginas de uma só vez
zen-split-view-change-on-hover = 
    .label = Trocar de separador com posição do cursor
zen-compact-mode-styles-left = Ocultar barra de Separadores
zen-compact-mode-styles-top = Ocultar barra Superior
zen-compact-mode-styles-both = Ocultar Ambas
pane-zen-CKS-title = Atalhos do Teclado
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = Atalhos de Teclado { -brand-short-name }
zen-settings-CKS-header = Personalize os seus atalhos de teclado
zen-settings-CKS-description = Altere os atalhos de teclado padrão ao seu gosto e melhore a sua experiência de navegação
zen-settings-CKS-disable-firefox = 
    .label = Desativar os atalhos de teclado padrão do { -brand-short-name }
zen-settings-CKS-duplicate-shortcut = 
    .label = Duplicar Atalho
zen-settings-CKS-reset-shortcuts = 
    .label = Repor para o Padrão
zenCKSOption-group-other = Outros
zenCKSOption-group-windowAndTabManagement = Gestão de Janelas e Separadores
zenCKSOption-group-navigation = Navegação
zenCKSOption-group-searchAndFind = Procurar e Encontrar
zenCKSOption-group-pageOperations = Operações de Página
zenCKSOption-group-historyAndBookmarks = Histórico e Favoritos
zenCKSOption-group-mediaAndDisplay = Média e Visualização
zenCKSOption-group-zen-compact-mode = Modo Compacto
zenCKSOption-group-zen-workspace = Espaços de Trabalho
zenCKSOption-group-zen-other = Outras Funcionalidades do Zen
zenCKSOption-group-zen-split-view = Vista Dividida
zen-key-quick-restart = Reinício Rápido
zen-window-new-shortcut = Nova Janela
zen-tab-new-shortcut = Novo Separador
zen-key-redo = Refazer
zen-restore-last-closed-tab-shortcut = Restaurar o Último Separador Fechado
zen-location-open-shortcut = Abrir Localização
zen-location-open-shortcut-alt = Abrir Localização (Alt)
zen-key-undo-close-window = Anular Fecho da Janela
zen-text-action-undo-shortcut = Anular
zen-text-action-redo-shortcut = Refazer
zen-text-action-cut-shortcut = Cortar
zen-text-action-copy-shortcut = Copiar
zen-text-action-paste-shortcut = Colar
zen-text-action-select-all-shortcut = Selecionar Tudo
zen-text-action-delete-shortcut = Eliminar
zen-history-show-all-shortcut-mac = Mostrar Todo o Histórico (Mac)
zen-full-screen-shortcut = Alternar Modo de Ecrã Inteiro
zen-reader-mode-toggle-shortcut-windows = Alternar Modo de Leitor (Windows)
zen-picture-in-picture-toggle-shortcut-alt = Alternar Imagem-em-Imagem (Alt)
zen-picture-in-picture-toggle-shortcut-mac = Alternar Imagem-em-Imagem (Mac)
zen-picture-in-picture-toggle-shortcut-mac-alt = Alternar Imagem-em-Imagem (Mac Alt)
zen-page-source-shortcut-safari = Ver Código-Fonte da Página (Safari)
zen-nav-stop-shortcut = Parar Carregamento
zen-history-sidebar-shortcut = Mostrar Barra Lateral do Histórico
zen-window-minimize-shortcut = Minimizar Janela
zen-help-shortcut = Abrir Ajuda
zen-preferences-shortcut = Abrir Preferências
zen-hide-app-shortcut = Ocultar Aplicação
zen-hide-other-apps-shortcut = Ocultar Outras Aplicações
zen-search-focus-shortcut = Focus Search
zen-search-focus-shortcut-alt = Focus Search (Alt)
zen-downloads-shortcut = Abrir Transferências
zen-addons-shortcut = Abrir Complementos
zen-file-open-shortcut = Abrir Ficheiro
zen-save-page-shortcut = Guardar Página
zen-print-shortcut = Imprimir Página
zen-close-shortcut-2 = Fechar Separador
zen-mute-toggle-shortcut = Alternar Silenciamento
zen-key-delete = Tecla de Eliminação
zen-key-go-back = Ir para Trás
zen-key-go-forward = Ir para a Frente
zen-nav-back-shortcut-alt = Navegar para Trás (Alt)
zen-nav-fwd-shortcut-alt = Navegar para Frente (Alt)
zen-history-show-all-shortcut = Mostrar Todo o Histórico
zen-key-enter-full-screen = Entrar no Modo de Ecrã Inteiro
zen-key-exit-full-screen = Sair do Modo de Ecrã Inteiro
zen-reader-mode-toggle-shortcut-other = Alternar Modo de Leitor
zen-picture-in-picture-toggle-shortcut = Alternar Imagem-em-Imagem
zen-nav-reload-shortcut-2 = Recarregar Página
zen-key-about-processes = Sobre os Processos
zen-page-source-shortcut = Ver Código-Fonte da Página
zen-page-info-shortcut = Ver Informação da Página
zen-find-shortcut = Procurar na Página
zen-search-find-again-shortcut = Procurar Seguinte
zen-search-find-again-shortcut-prev = Procurar Anterior
zen-search-find-again-shortcut-2 = Procurar Seguinte (Alt)
zen-bookmark-this-page-shortcut = Adicionar esta Página aos Favoritos
zen-bookmark-show-library-shortcut = Mostrar Biblioteca de Favoritos
zen-key-stop = Parar Carregamento
zen-full-zoom-reduce-shortcut = Diminuir Zoom
zen-full-zoom-enlarge-shortcut = Aumentar Zoom
zen-full-zoom-reset-shortcut = Repor Zoom
zen-bidi-switch-direction-shortcut = Alterar Direção do Texto
zen-private-browsing-shortcut = Navegação Privada
zen-screenshot-shortcut = Tirar Captura de Ecrã
zen-key-sanitize = Limpar Dados da Navegação
zen-quit-app-shortcut = Sair da Aplicação
zen-key-wr-capture-cmd = Comando de Captura WR
zen-key-wr-toggle-capture-sequence-cmd = Alternar Sequência de Captura WR
zen-nav-reload-shortcut = Recarregar Página
zen-nav-reload-shortcut-skip-cache = Recarregar Página (Ignorar Cache)
zen-close-shortcut = Fechar Janela
zen-close-tab-shortcut = Fechar Separador
zen-compact-mode-shortcut-show-sidebar = Alternar Barra de Lateral Flutuante
zen-compact-mode-shortcut-show-toolbar = Ativar/Desativar Barra de Ferramentas Flutuante
zen-compact-mode-shortcut-toggle = Alternar Modo Compacto
zen-workspace-shortcut-switch-1 = Mudar para a Área de Trabalho 1
zen-workspace-shortcut-switch-2 = Mudar para a Área de Trabalho 2
zen-workspace-shortcut-switch-3 = Mudar para a Área de Trabalho 3
zen-workspace-shortcut-switch-4 = Mudar para a Área de Trabalho 4
zen-workspace-shortcut-switch-5 = Mudar para a Área de Trabalho 5
zen-workspace-shortcut-switch-6 = Mudar para a Área de Trabalho 6
zen-workspace-shortcut-switch-7 = Mudar para a Área de Trabalho 7
zen-workspace-shortcut-switch-8 = Mudar para a Área de Trabalho 8
zen-workspace-shortcut-switch-9 = Mudar para a Área de Trabalho 9
zen-workspace-shortcut-switch-10 = Mudar para a Área de Trabalho 10
zen-workspace-shortcut-forward = Área de Trabalho Seguinte
zen-workspace-shortcut-backward = Área de Trabalho Anterior
zen-web-panel-shortcut-toggle = Ativar/Desativar Painel Web
zen-sidebar-shortcut-toggle = Alternar largura do Painel Lateral
zen-pinned-tab-shortcut-reset = Repor o Separador Fixado para a URL Fixada
zen-split-view-shortcut-grid = Ativar Vista Dividida em Grelha
zen-split-view-shortcut-vertical = Ativar Vista Dividida Vertical
zen-split-view-shortcut-horizontal = Ativar Vista Dividida Horizontal
zen-split-view-shortcut-unsplit = Fechar a Vista Dividida
zen-key-select-tab-1 = Selecionar separador #1
zen-key-select-tab-2 = Selecionar separador #2
zen-key-select-tab-3 = Selecionar separador #3
zen-key-select-tab-4 = Selecionar separador #4
zen-key-select-tab-5 = Selecionar separador #5
zen-key-select-tab-6 = Selecionar separador #6
zen-key-select-tab-7 = Selecionar separador #7
zen-key-select-tab-8 = Selecionar separador #8
zen-key-select-tab-last = Selecionar o último separador
zen-key-show-all-tabs = Mostrar todos os separadores
zen-key-goto-history = Ir para o histórico
zen-key-go-home = Ir para Casa
zen-bookmark-show-sidebar-shortcut = Mostrar a Barra Lateral de Favoritos
zen-bookmark-show-toolbar-shortcut = Mostrar a Barra de Ferramentas de Favoritos
