zen-panel-ui-current-window-text = 當前視窗
zen-panel-ui-workspaces-text = 其他工作空間
zen-panel-ui-workspaces-create-text = 創建工作空間
zen-panel-ui-workspaces-create-save = 
    .label = 創建工作空間
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = 取消
    .accesskey = C
zen-panel-ui-workspaces-edit-text = Edit Workspace
zen-panel-ui-workspaces-edit-save = 
    .label = Save Changes
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Cancel
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = 刪除工作空間
    .accesskey = D
zen-workspaces-panel-context-open = 
    .label = 打開工作空間
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = 設置為預設工作空間
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Edit Workspace
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = 將分頁轉成工作空間
    .accesskey = C
