zen-web-side-panel-context-mute-panel = 
    .label = 靜音網頁側版
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = 取消靜音網頁側版
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = Disable Mobile UserAgent
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Enable Mobile UserAgent
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = Unload Web Panel
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = 刪除網頁側版
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = 在新分頁中開啟
    .accesskey = N
zen-web-side-panel-context-add-to-panel = 
    .label = 添加至網頁側版
    .accesskey = A
zen-sidebar-introduction-title = 歡迎使用 Zen 側邊欄
zen-sidebar-introduction-description = Zen Sidebar is a new way to browse the web. Click on any of the icons to open a web panel.
