zen-panel-ui-workspaces-text = 其他工作區
zen-panel-ui-workspaces-create = 
    .label = Create Space
zen-panel-ui-workspaces-edit-text = 編輯工作區
zen-panel-ui-workspaces-edit-save = 
    .label = 儲存
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = 取消
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = 刪除工作區
    .accesskey = D
zen-workspaces-panel-change-name = 
    .label = Change Name
zen-workspaces-panel-change-icon = 
    .label = Change Icon
zen-workspaces-panel-context-manage = 
    .label = Manage Workspaces
    .accesskey = M
zen-workspaces-panel-context-open-in-container-tab = 
    .label = 設定預設容器
    .accesskey = O
zen-workspaces-how-to-reorder = To reorder spaces, drag and drop them from the space icons at the bottom of the sidebar.
zen-workspaces-change-theme = 
    .label = Edit Theme
zen-workspaces-panel-context-open = 
    .label = 打開工作區
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = 設定為預設工作區
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = 編輯工作區
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = 將分頁(含多個)移至工作區
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = 選擇工作區
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = 互補色
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = 補色分割
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = 相似色
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = 三等分色
zen-panel-ui-gradient-generator-algo-floating = 
    .label = 懸浮
zen-panel-ui-gradient-click-to-add = 點擊新增顏色
zen-workspace-creation-name = 
    .placeholder = Space Name
zen-workspaces-panel-context-reorder = 
    .label = Reorder Workspaces
zen-workspace-creation-profile = Profile
    .tooltiptext = Profiles are used to separate cookies and site data between spaces.
zen-workspace-creation-title = Create a new Space
zen-workspace-creation-label = Spaces are used to organize your tabs and sessions.
