zen-panel-ui-current-profile-text = 當前設定檔
unified-extensions-description = 擴充功能用於為 { -brand-short-name } 帶來更多功能。
tab-context-zen-reset-pinned-tab = 
    .label = 重置釘選的分頁
    .accesskey = R
tab-context-zen-add-essential = 
    .label = Add to Essentials
    .accesskey = E
tab-context-zen-remove-essential = 
    .label = Remove from Essentials
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = 將釘選的網址換成目前的網址
    .accesskey = C
tab-zen-unload = 
    .label = 卸載分頁
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = 卸載分頁操作
    .accesskey = T
tab-zen-prevent-unload = 
    .label = 避免卸載分頁
    .accesskey = P
tab-zen-ignore-unload = 
    .label = 允許卸載分頁
    .accesskey = I
zen-themes-corrupted = 你的 { -brand-short-name } 模組文件已損壞，它們已重置為預設佈景主題
zen-shortcuts-corrupted = Your { -brand-short-name } shortcuts file is corrupted. They have been reset to the default shortcuts.
zen-panel-ui-gradient-generator-opacity-text = 對比度
zen-panel-ui-gradient-generator-texture-text = 材質
zen-panel-ui-gradient-generator-custom-color = 自訂顏色
zen-panel-ui-gradient-generator-saved-message = 漸層儲存成功！
zen-copy-current-url-confirmation = 網址已複製到剪貼簿。
zen-rice-share-name = 
    .placeholder = Rice Name
zen-rice-share-author = By
zen-rice-share-author-input = 
    .placeholder = Your Name
zen-rice-share-cancel = 取消
zen-rice-share-save = 分享
zen-rice-share-include-userchrome = 
    .label = Include zen window styles (userChrome.css)
zen-rice-share-include-usercontent = 
    .label = Include website styles (userContent.css)
zen-rice-share-include-mods = 
    .label = Include enabled mods
zen-rice-share-include-mod-prefs = 
    .label = Include mod preferences
zen-rice-share-include-preferences = 
    .label = Include layout preferences
zen-rice-share-include-workspace-themes = 
    .label = Include workspace gradient themes
zen-rice-share-success = Successfully created a Rice!
zen-rice-share-success-link = Rice Share Link
zen-rice-share-accept = 同意
zen-rice-share-notice = Before sharing, please understand what a Rice is
# note: Do not translate the "<br/>" tags in the following string
zen-rice-share-notice-description =
    A Rice is a collection of customizations that can be shared with others.<br/>
    This includes your window styles, website styles, enabled mods, mod preferences, layout preferences, and workspace gradient themes.<br/>
    By sharing a Rice, you are sharing all of these customizations with others. Please be mindful of what you share.
zen-learn-more-text = 瞭解更多
zen-rice-share-include = 匯出選項
appmenu-zen-share-rice = 
    .label = Share Zen Rice
zen-close-label = 關閉
