zen-panel-ui-current-profile-text = 當前設定檔
unified-extensions-description = 擴充功能用於為 { -brand-short-name } 帶來更多功能。
tab-context-zen-reset-pinned-tab = 
    .label = 重置釘選的分頁
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = 將釘選的網址換成目前的網址
    .accesskey = C
tab-zen-unload = 
    .label = 卸載分頁
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = 卸載分頁操作
    .accesskey = T
tab-zen-prevent-unload = 
    .label = 避免分頁卸載
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Allow Tab Unload
    .accesskey = I
zen-themes-corrupted = Your { -brand-short-name } mods file is corrupted. They have been reset to the default theme.
