zen-panel-ui-workspaces-text = 其他工作區
zen-panel-ui-workspaces-create-text = 建立工作區
zen-panel-ui-workspaces-create-save = 
    .label = 建立工作區
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = 取消
    .accesskey = C
zen-panel-ui-workspaces-edit-text = 編輯工作區
zen-panel-ui-workspaces-edit-save = 
    .label = 儲存
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = 取消
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = 刪除工作區
    .accesskey = D
zen-workspaces-panel-change-name = 
    .label = Change Name
zen-workspaces-panel-context-open-in-container-tab = 
    .label = 設定預設容器
    .accesskey = O
zen-workspaces-change-gradient = 
    .label = 更改佈景主題顏色
    .accesskey = C
zen-workspaces-panel-context-open = 
    .label = Open Workspace
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Set As Default Workspace
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Edit Workspace
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Change Tab(s) To Workspace
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = 選擇工作區
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = 互補色
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = 補色分割
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = 相似色
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = 三等分色
zen-panel-ui-gradient-generator-algo-floating = 
    .label = 懸浮
zen-panel-ui-gradient-click-to-add = 點擊新增顏色
