zen-panel-ui-current-profile-text = 當前設定檔
unified-extensions-description = 擴充功能用於為 { -brand-short-name } 帶來更多功能。
tab-context-zen-reset-pinned-tab = 
    .label = Reset Pinned Tab
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Replace Pinned URL with Current
    .accesskey = C
tab-zen-unload = 
    .label = 卸載分頁
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = 卸載分頁操作
    .accesskey = T
tab-zen-prevent-unload = 
    .label = 避免分頁卸載
    .accesskey = P
tab-zen-ignore-unload = 
    .label = 忽略分頁卸載
    .accesskey = I
