pane-zen-looks-title = Wygląd i Działanie
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Zmiana domyślnego języka może sprawić, że witrynom łatwiej będzie Cię śledzić.
zen-look-and-feel-colors-header = Wybierz kolor motywu
zen-look-and-feel-colors-description = Spraw, by { -brand-short-name } wyglądał i działał tak, jak chcesz
zen-look-and-feel-themed-toolbar = 
    .label = Użyj koloru akcentu na pasku narzędzi
pane-zen-side-panels-title = Panele Boczne
zen-side-panels-header = Ustawienia ogólne paneli bocznych
zen-side-panels-description = Zwiększ produktywność, wyświetlając jednocześnie wiele widoków!
zen-side-panels-enabled = 
    .label = Włącz Panele Boczne Stron
zen-side-panels-close-on-blur = 
    .label = Zamknij panel, gdy przestaniesz go używać i jeśli nie jest przypięty
zen-look-and-feel-compact-view-header = Pokaż w widoku kompaktowym
zen-look-and-feel-compact-view-description = Pokaż tylko paski narzędzi, których używasz!
zen-look-and-feel-compact-view-enabled = 
    .label = Włącz tryb kompaktowy { -brand-short-name }
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Ukryj górny pasek narzędzi w trybie kompaktowym
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Krótkie wyskakiwanie paska narzędzi podczas przełączania lub otwierania nowych kart w trybie kompaktowym
zen-look-and-feel-buttons-header = Styl przycisków
zen-look-and-feel-buttons-description = Wybierz styl przycisków, które chcesz zobaczyć
zen-look-and-feel-pilled-buttons = 
    .label = Zaokrąglone przyciski
pane-zen-workspaces-title = Przestrzenie robocze
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = Przestrzenie robocze
pane-zen-workspaces-header = Przestrzenie robocze
zen-settings-workspaces-header = Ustawienia ogólne przestrzeni roboczych
zen-settings-workspaces-description = Korzystając z przestrzeni roboczych, możesz prowadzić kilka sesji przeglądania w jednym momencie!
zen-settings-workspaces-enabled = 
    .label = Włącz Przestrzenie robocze (Eksperymentalne)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Ukryj domyślny wskaźnik kontenera na pasku kart
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Zezwól przestrzenią roboczym na posiadanie własnych przypiętych kart
pane-zen-theme-title = Ustawienia Motywu
zen-vertical-tabs-title = Pasek boczny i układ kart
zen-vertical-tabs-header = Pionowe Karty
zen-vertical-tabs-description = Zarządzaj swoimi kartami w układzie pionowym
zen-vertical-tabs-show-expand-button = 
    .label = Pokaż Przycisk rozwijania
zen-vertical-tabs-expand-tabs-by-default = Domyślnie rozwijaj karty
zen-vertical-tabs-dont-expand-tabs-by-default = Wyłącz natychmiastowe rozwijanie kart
zen-vertical-tabs-expand-tabs-on-hover = Rozwijaj karty po najechaniu (Nie będzie działać w trybie kompaktowym)
zen-vertical-tabs-expand-tabs-header = Jak rozwijać karty
zen-vertical-tabs-expand-tabs-description = Wybierz jak rozwijać karty w panelu bocznym
zen-theme-marketplace-header = Modyfikacje Zen
zen-theme-marketplace-description = Znajdź i zainstaluj motywy ze sklepu.
zen-theme-marketplace-remove-button = 
    .label = Usuń Motyw
zen-theme-marketplace-check-for-updates-button = 
    .label = Sprawdź dostępność aktualizacji
zen-theme-marketplace-updates-success = Motyw został zaktualizowany
zen-theme-marketplace-updates-fail = Nie znaleziono żadnych aktualizacji!
zen-theme-marketplace-toggle-enabled-button = 
    .title = Wyłącz motyw
zen-theme-marketplace-toggle-disabled-button = 
    .title = Włącz motyw
zen-theme-marketplace-remove-confirmation = Czy na pewno chcesz usunąć tę modyfikację?
zen-theme-marketplace-close-modal = Zamknij
zen-theme-marketplace-theme-header-title = 
    .title = Selektor CSS: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = Brak
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Napisz cokolwiek...
pane-zen-marketplace-title = Modyfikację Zen
zen-settings-workspaces-display-as-icon-strip = 
    .label = Wyświetlaj przestrzenie robocze jako pasek ikon
zen-theme-marketplace-link = Odwiedź Sklep
zen-dark-theme-styles-header = Styl Motywu Ciemnego
zen-dark-theme-styles-description = Dostosuj ciemny motyw do swoich preferencji
zen-dark-theme-styles-amoled = Motyw Ciemny
zen-dark-theme-styles-default = Domyślny ciemny motyw
zen-dark-theme-styles-colorful = Kolorowy ciemny motyw
zen-compact-mode-styles-left = Ukryj panel kart
zen-compact-mode-styles-top = Ukryj górny panel
zen-compact-mode-styles-both = Ukryj oba
pane-zen-CKS-title = Skróty klawiszowe
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = Skróty klawiszowe { -brand-short-name }
zen-settings-CKS-header = Dostosuj skróty klawiszowe
zen-settings-CKS-description = Zmień domyślne skróty klawiszowe tak, jak lubisz i popraw swoje doświadczenie przeglądania
zen-settings-CKS-disable-firefox = 
    .label = Wyłącz domyślne skróty klawiszowe { -brand-short-name }
zen-settings-CKS-duplicate-shortcut = 
    .label = Sklonuj Skrót
zenCKSOption-group-other = Inne
zenCKSOption-group-windowAndTabManagement = Zarządzanie Oknami i Kartami
zenCKSOption-group-navigation = Nawigacja
zenCKSOption-group-searchAndFind = Szukaj i Znajdź
zenCKSOption-group-pageOperations = Page Operations
zenCKSOption-group-historyAndBookmarks = Historia i zakładki
zenCKSOption-group-mediaAndDisplay = Media & Display
zenCKSOption-group-zen-compact-mode = Tryb kompaktowy
zenCKSOption-group-zen-workspace = Przestrzenie robocze
zenCKSOption-group-zen-other = Inne funkcje Zen
zenCKSOption-group-zen-split-view = Split View
zen-key-quick-restart = Szybki Restart
zen-window-new-shortcut = Nowe okno
zen-tab-new-shortcut = Nowa karta
zen-location-open-shortcut = Otwórz Lokalizację
zen-location-open-shortcut-alt = Otwórz Lokalizację (Alt)
zen-search-focus-shortcut = Focus Search
zen-search-focus-shortcut-alt = Focus Search (Alt)
zen-downloads-shortcut = Otwórz pobrane
zen-addons-shortcut = Otwórz rozszerzenia
zen-file-open-shortcut = Otwórz plik
zen-save-page-shortcut = Zapisz stronę
zen-print-shortcut = Drukuj stronę
zen-close-shortcut-2 = Zamknij kartę
zen-mute-toggle-shortcut = Toggle Mute
zen-key-delete = Delete Key
zen-key-go-back = Wróć
zen-key-go-forward = Idź Do Przodu
zen-nav-back-shortcut-alt = Wróć (Alt)
zen-nav-fwd-shortcut-alt = Idź Do Przodu
zen-history-show-all-shortcut = Pokaż Całą Historię
zen-key-enter-full-screen = Otwórz tryb pełnoekranowy
zen-key-exit-full-screen = Zamknij tryb pełnoekranowy
zen-reader-mode-toggle-shortcut-other = Włącz Tryb Czytnika
zen-picture-in-picture-toggle-shortcut = Włącz Obraz-w-Obrazie
zen-nav-reload-shortcut-2 = Odśwież Stronę
zen-key-about-processes = O Procesach
zen-page-source-shortcut = Zobacz Źródło Strony
zen-page-info-shortcut = Zobacz Informacje o Stronie
zen-find-shortcut = Znajdź na Stronie
zen-search-find-again-shortcut = Znajdź Ponownie
zen-search-find-again-shortcut-prev = Find Previous
zen-search-find-again-shortcut-2 = Find Again (Alt)
zen-bookmark-this-page-shortcut = Dodaj do Zakładek
zen-bookmark-show-library-shortcut = Pokaż Wszystkie Zakładki
zen-key-stop = Przestań Ładować
zen-full-zoom-reduce-shortcut = Oddal
zen-full-zoom-enlarge-shortcut = Przybliż
zen-full-zoom-reset-shortcut = Zresetuj Przybliżenie
zen-bidi-switch-direction-shortcut = Zamień
zen-private-browsing-shortcut = Prywatne Wyszukiwanie
zen-screenshot-shortcut = Zrób Zrzut Ekranu
zen-key-sanitize = Wyczyść Dane Przeglądania
zen-quit-app-shortcut = Wyjdź z Aplikacji
zen-key-wr-capture-cmd = WR Capture Command
zen-key-wr-toggle-capture-sequence-cmd = Toggle WR Capture Sequence
zen-nav-reload-shortcut = Odśwież Stronę
zen-nav-reload-shortcut-skip-cache = Odśwież Stronę (Pomiń Pamięć Podręczną)
zen-close-shortcut = Zamknij Okno
zen-close-tab-shortcut = Zamknij Kartę
zen-compact-mode-shortcut-show-sidebar = Toggle Floating Sidebar
zen-compact-mode-shortcut-show-toolbar = Toggle Floating Toolbar
zen-compact-mode-shortcut-toggle = Toggle Compact Mode
zen-workspace-shortcut-switch-1 = Przełącz na Obszar 1
zen-workspace-shortcut-switch-2 = Przełącz na Obszar 2
zen-workspace-shortcut-switch-3 = Przełącz na Obszar 3
zen-workspace-shortcut-switch-4 = Przełącz na Obszar 4
zen-workspace-shortcut-switch-5 = Przełącz na Obszar 5
zen-workspace-shortcut-switch-6 = Przełącz na Obszar 6
zen-workspace-shortcut-switch-7 = Przełącz na Obszar 7
zen-workspace-shortcut-switch-8 = Przełącz na Obszar 8
zen-workspace-shortcut-switch-9 = Przełącz na Obszar 9
zen-workspace-shortcut-switch-10 = Przełącz na Obszar 10
zen-workspace-shortcut-forward = Forward Workspace
zen-workspace-shortcut-backward = Backward Workspace
zen-web-panel-shortcut-toggle = Toggle Web Panel
zen-sidebar-shortcut-toggle = Toggle Sidebar's Width
zen-split-view-shortcut-grid = Toggle Split View Grid
zen-split-view-shortcut-vertical = Toggle Split View Vertical
zen-split-view-shortcut-horizontal = Toggle Split View Horizontal
zen-split-view-shortcut-unsplit = Close Split View
