pane-zen-looks-title = Wygląd i Działanie
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Zmiana domyślnego języka może sprawić, że witrynom łatwiej będzie Cię śledzić.
zen-look-and-feel-colors-header = Wybierz kolor motywu
zen-look-and-feel-colors-description = Spraw, by { -brand-short-name } wyglądał i działał tak, jak chcesz
zen-look-and-feel-themed-toolbar = 
    .label = Kolor akcentu na pasku narzędzi
pane-zen-side-panels-title = Panele Boczne
zen-side-panels-header = Ustawienia ogólne paneli bocznych
zen-side-panels-description = Zwiększ produktywność, wyświetlając jednocześnie wiele widoków!
zen-side-panels-enabled = 
    .label = Włącz Panele Boczne
zen-side-panels-close-on-blur = 
    .label = Zamknij panel, gdy przestaniesz go używać i jeśli nie jest przypięty
zen-look-and-feel-compact-view-header = Pokaż w widoku kompaktowym
zen-look-and-feel-compact-view-description = Pokaż tylko paski narzędzi, których używasz!
zen-look-and-feel-compact-view-enabled = 
    .label = Włącz tryb kompaktowy { -brand-short-name }
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Ukryj górny pasek narzędzi w trybie kompaktowym
zen-look-and-feel-buttons-header = Styl przycisków
zen-look-and-feel-buttons-description = Wybierz styl przycisków, które chcesz zobaczyć
zen-look-and-feel-pilled-buttons = 
    .label = Okrągłe Przyciski
pane-zen-workspaces-title = Przestrzenie robocze
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = Przestrzenie robocze
pane-zen-workspaces-header = Przestrzenie robocze
zen-settings-workspaces-header = Ustawienia ogólne przestrzeni roboczych
zen-settings-workspaces-description = Korzystając z przestrzeni roboczych, możesz prowadzić kilka sesji przeglądania w jednym momencie!
zen-settings-workspaces-enabled = 
    .label = Włącz Przestrzenie robocze (Eksperymentalne)
pane-zen-theme-title = Ustawienia Motywu
zen-vertical-tabs-title = Pasek boczny i układ kart
zen-vertical-tabs-header = Karty Pionowe
zen-vertical-tabs-description = Zarządzaj swoimi kartami w układzie pionowym
zen-vertical-tabs-show-expand-button = 
    .label = Pokaż Przycisk Rozwijania
zen-vertical-tabs-expand-tabs-by-default = Domyślnie rozwijaj karty
zen-vertical-tabs-dont-expand-tabs-by-default = Domyślnie nie rozwijaj kart
zen-vertical-tabs-expand-tabs-on-hover = Rozwijaj Karty Po Najechaniu Kursorem (Nie działa w trybie kompaktowym)
zen-vertical-tabs-expand-tabs-header = Jak rozwijać karty
zen-vertical-tabs-expand-tabs-description = Wybierz jak rozwijać karty w panelu bocznym
zen-theme-marketplace-header = Sklep z motywami
zen-theme-marketplace-description = Znajdź i zainstaluj motywy ze sklepu.
zen-theme-marketplace-remove-button = 
    .label = Usuń Motyw
zen-theme-marketplace-check-for-updates-button = 
    .label = Check for Updates
zen-theme-marketplace-link = Odwiedź Sklep
pane-zen-CKS-title = Skróty Klawiszowe
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = Skróty Klawiszowe { -brand-short-name }
zen-settings-CKS-header = Dostosuj skróty klawiszowe
zen-settings-CKS-description = Zmień domyślne skróty klawiszowe tak, jak lubisz i popraw swoje doświadczenie przeglądania
zen-settings-CKS-disable-firefox = 
    .label = Wyłącz domyślne skróty klawiszowe { -brand-short-name }
zen-cks-group-tab-action = Akcje Kartek
zen-cks-group-page-action = Akcje Strony
zen-cks-group-visible-action = Widoczne Akcje
zen-cks-group-history-action = Akcje Historii
zen-cks-group-search-action = Akcje Wyszukania
zen-cks-group-tools-action = Akcje Narzędzi
zen-cks-group-bookmark-action = Akcje Zakładek
zen-cks-group-open-page-action = Otwórz Akcje Strony
zen-cks-group-downloads-action = Akcje Pobrania
zen-cks-group-sidebar-action = Akcje Paska Bocznego
zen-cks-group-compact-mode-action = Akcje Trybu Kompaktowego
zen-cks-group-split-view-action = Akcje Podzielonego Widoku
zen-cks-group-workspace-action = Akcje Projektu
open-new-tab = Otwórz Nową Kartę
close-tab = Zamknij Kartę
open-new-window = Otwórz Nowe Okno
open-new-private-window = Otwórz Nowe Okno Prywatne
close-window = Zamknij Okno
restore-last-tab = Przywróć Ostatnią Kartę
restore-last-window = Przywróć Ostatnie Okno
show-next-tab = Pokaż Następną Kartę
show-previous-tab = Pokaż Poprzednią Kartę
show-all-tabs-panel = Pokaż Wszystkie Karty
send-with-mail = Wyślij Stronę z Pocztą
save-page = Zapisz Stronę
print-page = Drukuj Stronę
mute-current-tab = Wycisz Obecną Kartę
show-source-of-page = Pokaż Źródło Strony
show-page-info = Pokaż Informacje O Stronie
zoom-in = Powiększ
zoom-out = Zmniejsz
reset-zoom = Zresetuj Powiększenie
back = Wróć
forward = Dalej
stop = Zatrzymaj
reload = Odśwież
force-reload = Wymuś Odświeżenie
search-in-this-page = Szukaj w tej stronie
show-next-search-result = Pokaż następny wynik wyszukiwania
show-previous-search-result = Pokaż Ostatni Wynik Wyszukiwania
search-the-web = Szukaj w Internecie
open-migration-wizard = Otwórz Kreatora Migracji
quit-from-application = Zamknij Aplikację
enter-into-customize-mode = Wejdź w Tryb Dostosowania
enter-into-offline-mode = Wejdź w Tryb Offline
open-screen-capture = Otwórz Zrzut Ekranu
bookmark-this-page = Dodaj Stronę do Zakładek
open-bookmark-add-tool = Otwórz Narzędzie do Dodawania Zakładek
open-bookmarks-manager = Otwórz Menedżer Zakładek
toggle-bookmark-toolbar = Przełącz Pasek Zakładek
open-general-preferences = Otwórz Ustawienia Ogólne
open-privacy-preferences = Otwórz Ustawienia Prywatności
open-workspaces-preferences = Otwórz Ustawienia Projektów
open-containers-preferences = Otwórz Ustawienia Kontenerów
open-search-preferences = Otwórz Ustawienia Wyszukiwania
open-sync-preferences = Otwórz Ustawienia Synchronizacji
open-task-manager = Otwórz Menedżera Zadań
open-addons-manager = Otwórz Menedżer Dodatek
open-home-page = Otwórz Stronę Główną
forget-history = Zapomnij o Historii
quick-forget-history = Zapomnij o Historii Szybko
clear-recent-history = Wyczyść Ostatnią Historię
restore-last-session = Przywróć Ostatnią Sesję
search-history = Historia Wyszukiwania
manage-history = Zarządzaj Historią
open-downloads = Otwórz Pobrania
show-bookmark-sidebar = Pokaż Pasek Zakładek
show-history-sidebar = Pokaż Pasek Historii
show-synced-tabs-sidebar = Pokaż Zsynchronizowane Karty
reverse-sidebar = Odwróć Pozycję Paska Bocznego
hide-sidebar = Ukryj Pasek Boczny
toggle-sidebar = Przełącz Pasek Boczny
zen-toggle-web-panels = Przełącz Panele Internetowe
zen-toggle-compact-mode = Przełącz Tryb Kompaktowy
zen-toggle-compact-mode-sidebar = Przełącz Pasek Boczny w Trybie Kompaktowym
zen-toggle-compact-mode-toolbar = Przełącz Pasek Narzędzi w Trybie Kompaktowym
zen-change-workspace = Przepłacaj Projekty
zen-split-view-grid = Podzielony Widok: Siatka
zen-split-view-vertical = Podzielony Widok: Pionowy
zen-split-view-horizontal = Podzielony Widok: Poziomy
zen-split-view-close = Zamknij Widok Podzielony
