pane-zen-looks-title = Ilme
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Vaikimisi keele vahetamine võib muuta teid veebisaitidel kergemini jälgitavaks.
zen-look-and-feel-colors-header = Vali teema värv
zen-look-and-feel-colors-description = Muuda { -brand-short-name }i ilmet nii kuidas meelepärane on
zen-look-and-feel-use-workspace-colors = 
    .label = Kasuta põhivärvina tööruumi värve
pane-zen-side-panels-title = Külgmised veebipaneelid
zen-side-panels-header = Veebipaneelide üldised sätted
zen-side-panels-description = Suurenda produktiivsust avades mitut vaadet korraga!
zen-side-panels-enabled = 
    .label = Luba külgmised veebipaneelid
zen-side-panels-close-on-blur = 
    .label = Sulge kinnitamata paneel kui tehakse toiming sellest väljaspool
zen-vertical-tabs-show-bottom-border = 
    .label = Kuva eraldajat enne alumisi ikoone
sync-currently-syncing-workspaces = Tööruumid
sync-engine-workspaces = 
    .label = Tööruumid
    .tooltiptext = Sünkroniseeri tööruume seadmete vahel
    .accesskey = t
zen-glance-title = Pilk
zen-glance-header = Pilgu üldised sätted
zen-glance-description = Saa kiire ülevaade linkidest ilma neid uuel kaardil avamata
zen-glance-trigger-label = Aktiveerimise viis
zen-glance-enabled = 
    .label = Luba Pilk
zen-glance-trigger-ctrl-click = 
    .label = Ctrl + Klõps
zen-glance-trigger-alt-click = 
    .label = Alt + Klõps
zen-glance-trigger-shift-click = 
    .label = Shift + Klõps
zen-glance-trigger-meta-click = 
    .label = Meta (Command) + Klõps
zen-glance-trigger-mantain-click = 
    .label = Hoia hiireklahvi all (valmib varsti!)
zen-look-and-feel-compact-view-header = Näita kompaktses vaates
zen-look-and-feel-compact-view-description = Näita ainult tööriistaribasid, mida aktiivselt kasutad!
zen-look-and-feel-compact-view-enabled = 
    .label = Luba { -brand-short-name }i kompaktne vaade
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Peida ka ülemine tööriistariba kompaktses vaates
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Lühidalt kuva tööriistariba hüpikut kui vahetatakse kaarti või avatakse uus kaart kompaktses režiimis
zen-look-and-feel-buttons-header = Nuppude stiil
zen-look-and-feel-buttons-description = Vali nuppude stiil, mida soovid näha
zen-look-and-feel-pilled-buttons = 
    .label = Ümaramad nupud
pane-zen-tabs-title = Kaartide haldamine
category-zen-workspaces = 
    .tooltiptext = { pane-zen-tabs-title }
pane-settings-workspaces-title = Tööruumid
pane-zen-tabs-unloader-title = Kaartide mälust eemaldamine
zen-tabs-unloader-header = Kaartide mälust eemaldaja üldised sätted
zen-tabs-unloader-description = Mälu säästmiseks eemaldatakse mõnda aega kasutamata kaardid mälust automaatselt
zen-tabs-unloader-enabled = 
    .label = Luba kaartide mälust eemaldamine
zen-tabs-unloader-unload-delay = 
    .label = Eemalda kaardid mälust pärast
zen-tabs-unloader-unload-delay-description = Aeg minutites, pärast mida aktiivsuseta kaardid mälust eemaldatakse
zen-look-and-feel-compact-toolbar-themed = 
    .label = Kasuta kompaktsel tööriistaribal teema poolt küljendatud tausta
zen-look-and-feel-compact-sidebar-themed = 
    .label = Kasuta kompaktsel külgribal teema poolt küljendatud tausta
pane-zen-pinned-tab-manager-title = Püsikaardid
zen-pinned-tab-manager-header = Püsikaartide üldised sätted
zen-pinned-tab-manager-description = Täiendav püsikaartide käitumise haldamine
zen-pinned-tab-manager-restore-pinned-tabs-to-pinned-url = 
    .label = Brauseri käivitamisel taasta püsikaardid algselt määratud URL-ile
zen-pinned-tab-manager-close-shortcut-behavior-label = Close Tab Shortcut Behavior
zen-pinned-tab-manager-reset-unload-switch-close-shortcut-option = 
    .label = Reset URL, unload and switch to next tab
zen-pinned-tab-manager-unload-switch-close-shortcut-option = 
    .label = Unload and switch to next tab
zen-pinned-tab-manager-reset-switch-close-shortcut-option = 
    .label = Reset URL and switch to next tab
zen-pinned-tab-manager-switch-close-shortcut-option = 
    .label = Switch to next tab
zen-pinned-tab-manager-reset-close-shortcut-option = 
    .label = Reset URL
zen-pinned-tab-manager-close-close-shortcut-option = 
    .label = Close tab
pane-zen-workspaces-header = Workspaces
zen-settings-workspaces-header = General settings for workspaces
zen-settings-workspaces-description = With workspaces, you can have multiple browsing sessions at once!
zen-settings-workspaces-enabled = 
    .label = Enable Workspaces (Experimental)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Hide the default container indicator in the tab bar
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Allow workspaces have their own pinned tabs
zen-key-unsafed = Unsaved shortcut! Please safe it by clicking the "Escape" key after retyping it.
zen-key-conflict = Conflict with another shortcut
pane-zen-theme-title = Theme Settings
zen-vertical-tabs-title = Sidebar and tabs layout
zen-vertical-tabs-header = Vertical Tabs
zen-vertical-tabs-description = Manage your tabs in a vertical layout
zen-vertical-tabs-show-expand-button = 
    .label = Show Expand Button
zen-vertical-tabs-newtab-on-tab-list = 
    .label = Show New Tab Button on Tab List
zen-vertical-tabs-newtab-top-button-border = 
    .label = Show separation border for when the new tab button is at the bottom
zen-vertical-tabs-newtab-top-button-up = 
    .label = Move the new tab button to the top
zen-vertical-tabs-expand-tabs-by-default = Expand Tabs by Default
zen-vertical-tabs-dont-expand-tabs-by-default = Don't Expand Tabs by Default
zen-vertical-tabs-expand-tabs-on-hover = Expand Tabs on Hover (Won't work on compact mode)
zen-vertical-tabs-expand-tabs-header = How to expand tabs
zen-vertical-tabs-expand-tabs-description = Choose how to expand tabs in the sidebar
zen-theme-marketplace-header = Zen Mods
zen-theme-disable-all-enabled = 
    .title = Disable all mods
zen-theme-disable-all-disabled = 
    .title = Enable all mods
zen-theme-marketplace-description = Find and install mods from the store.
zen-theme-marketplace-remove-button = 
    .label = Remove mod
zen-theme-marketplace-check-for-updates-button = 
    .label = Check for Updates
zen-theme-marketplace-updates-success = Mods updated successfully
zen-theme-marketplace-updates-fail = Couldn't find any updates!
zen-theme-marketplace-toggle-enabled-button = 
    .title = Disable mod
zen-theme-marketplace-toggle-disabled-button = 
    .title = Enable mod
zen-theme-marketplace-remove-confirmation = Are you sure you want to remove this mod?
zen-theme-marketplace-close-modal = Close
zen-theme-marketplace-theme-header-title = 
    .title = CSS Selector: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = None
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Type something...
pane-zen-marketplace-title = Zen Mods
zen-settings-workspaces-display-as-icon-strip = 
    .label = Display workspaces as an icon strip
zen-settings-workspaces-force-container-tabs-to-workspace = 
    .label = Switch to workspace where container is set as default when opening container tabs
zen-settings-workspaces-hide-deactivated-workspaces = 
    .label = Hide deactivated workspaces
zen-theme-marketplace-link = Visit Store
zen-dark-theme-styles-header = Dark Theme Styles
zen-dark-theme-styles-description = Customize the dark theme to your liking
zen-dark-theme-styles-amoled = Night Theme
zen-dark-theme-styles-default = Default Dark Theme
zen-dark-theme-styles-colorful = Colorful Dark Theme
zen-split-view-title = Split View
zen-split-view-header = Split View Functionality
zen-split-view-description = Split your browser into multiple views, enabling you to browse multiple websites at once
zen-split-view-change-on-hover = 
    .label = Change tabs on hover
zen-compact-mode-styles-left = Hide Tab bar
zen-compact-mode-styles-top = Hide Top bar
zen-compact-mode-styles-both = Hide Both
pane-zen-CKS-title = Keyboard Shortcuts
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } Keyboard Shortcuts
zen-settings-CKS-header = Customize your keyboard shortcuts
zen-settings-CKS-description = Change the default keyboard shortcuts to your liking and improve your browsing experience
zen-settings-CKS-disable-firefox = 
    .label = Disable { -brand-short-name }'s default keyboard shortcuts
zen-settings-CKS-duplicate-shortcut = 
    .label = Duplicate Shortcut
zen-settings-CKS-reset-shortcuts = 
    .label = Reset to Default
zenCKSOption-group-other = Other
zenCKSOption-group-windowAndTabManagement = Window & Tab Management
zenCKSOption-group-navigation = Navigation
zenCKSOption-group-searchAndFind = Search & Find
zenCKSOption-group-pageOperations = Page Operations
zenCKSOption-group-historyAndBookmarks = History & Bookmarks
zenCKSOption-group-mediaAndDisplay = Media & Display
zenCKSOption-group-zen-compact-mode = Compact Mode
zenCKSOption-group-zen-workspace = Workspaces
zenCKSOption-group-zen-other = Other Zen Features
zenCKSOption-group-zen-split-view = Split View
zen-key-quick-restart = Quick Restart
zen-window-new-shortcut = New Window
zen-tab-new-shortcut = New Tab
zen-key-redo = Redo
zen-restore-last-closed-tab-shortcut = Restore Last Closed Tab
zen-location-open-shortcut = Open Location
zen-location-open-shortcut-alt = Open Location (Alt)
zen-key-undo-close-window = Undo Close Window
zen-text-action-undo-shortcut = Undo
zen-text-action-redo-shortcut = Redo
zen-text-action-cut-shortcut = Cut
zen-text-action-copy-shortcut = Copy
zen-text-action-paste-shortcut = Paste
zen-text-action-select-all-shortcut = Select All
zen-text-action-delete-shortcut = Delete
zen-history-show-all-shortcut-mac = Show All History (Mac)
zen-full-screen-shortcut = Toggle Full Screen
zen-reader-mode-toggle-shortcut-windows = Toggle Reader Mode (Windows)
zen-picture-in-picture-toggle-shortcut-alt = Toggle Picture-in-Picture (Alt)
zen-picture-in-picture-toggle-shortcut-mac = Toggle Picture-in-Picture (Mac)
zen-picture-in-picture-toggle-shortcut-mac-alt = Toggle Picture-in-Picture (Mac Alt)
zen-page-source-shortcut-safari = View Page Source (Safari)
zen-nav-stop-shortcut = Stop Loading
zen-history-sidebar-shortcut = Show History Sidebar
zen-window-minimize-shortcut = Minimize Window
zen-help-shortcut = Open Help
zen-preferences-shortcut = Open Preferences
zen-hide-app-shortcut = Hide Application
zen-hide-other-apps-shortcut = Hide Other Applications
zen-search-focus-shortcut = Focus Search
zen-search-focus-shortcut-alt = Focus Search (Alt)
zen-downloads-shortcut = Open Downloads
zen-addons-shortcut = Open Add-ons
zen-file-open-shortcut = Open File
zen-save-page-shortcut = Save Page
zen-print-shortcut = Print Page
zen-close-shortcut-2 = Close Tab
zen-mute-toggle-shortcut = Toggle Mute
zen-key-delete = Delete Key
zen-key-go-back = Go Back
zen-key-go-forward = Go Forward
zen-nav-back-shortcut-alt = Navigate Back (Alt)
zen-nav-fwd-shortcut-alt = Navigate Forward (Alt)
zen-history-show-all-shortcut = Show All History
zen-key-enter-full-screen = Enter Full Screen
zen-key-exit-full-screen = Exit Full Screen
zen-reader-mode-toggle-shortcut-other = Toggle Reader Mode
zen-picture-in-picture-toggle-shortcut = Toggle Picture-in-Picture
zen-nav-reload-shortcut-2 = Reload Page
zen-key-about-processes = About Processes
zen-page-source-shortcut = View Page Source
zen-page-info-shortcut = View Page Info
zen-find-shortcut = Find on Page
zen-search-find-again-shortcut = Find Again
zen-search-find-again-shortcut-prev = Find Previous
zen-search-find-again-shortcut-2 = Find Again (Alt)
zen-bookmark-this-page-shortcut = Bookmark This Page
zen-bookmark-show-library-shortcut = Show Bookmarks Library
zen-key-stop = Stop Loading
zen-full-zoom-reduce-shortcut = Zoom Out
zen-full-zoom-enlarge-shortcut = Zoom In
zen-full-zoom-reset-shortcut = Reset Zoom
zen-bidi-switch-direction-shortcut = Switch Text Direction
zen-private-browsing-shortcut = Private Browsing
zen-screenshot-shortcut = Take Screenshot
zen-key-sanitize = Clear Browsing Data
zen-quit-app-shortcut = Quit Application
zen-key-wr-capture-cmd = WR Capture Command
zen-key-wr-toggle-capture-sequence-cmd = Toggle WR Capture Sequence
zen-nav-reload-shortcut = Reload Page
zen-nav-reload-shortcut-skip-cache = Reload Page (Skip Cache)
zen-close-shortcut = Close Window
zen-close-tab-shortcut = Close Tab
zen-compact-mode-shortcut-show-sidebar = Toggle Floating Sidebar
zen-compact-mode-shortcut-show-toolbar = Toggle Floating Toolbar
zen-compact-mode-shortcut-toggle = Toggle Compact Mode
zen-workspace-shortcut-switch-1 = Switch to Workspace 1
zen-workspace-shortcut-switch-2 = Switch to Workspace 2
zen-workspace-shortcut-switch-3 = Switch to Workspace 3
zen-workspace-shortcut-switch-4 = Switch to Workspace 4
zen-workspace-shortcut-switch-5 = Switch to Workspace 5
zen-workspace-shortcut-switch-6 = Switch to Workspace 6
zen-workspace-shortcut-switch-7 = Switch to Workspace 7
zen-workspace-shortcut-switch-8 = Switch to Workspace 8
zen-workspace-shortcut-switch-9 = Switch to Workspace 9
zen-workspace-shortcut-switch-10 = Switch to Workspace 10
zen-workspace-shortcut-forward = Forward Workspace
zen-workspace-shortcut-backward = Backward Workspace
zen-web-panel-shortcut-toggle = Toggle Web Panel
zen-sidebar-shortcut-toggle = Toggle Sidebar's Width
zen-pinned-tab-shortcut-reset = Reset Pinned Tab to Pinned URL
zen-split-view-shortcut-grid = Toggle Split View Grid
zen-split-view-shortcut-vertical = Toggle Split View Vertical
zen-split-view-shortcut-horizontal = Toggle Split View Horizontal
zen-split-view-shortcut-unsplit = Close Split View
zen-key-select-tab-1 = Select tab #1
zen-key-select-tab-2 = Select tab #2
zen-key-select-tab-3 = Select tab #3
zen-key-select-tab-4 = Select tab #4
zen-key-select-tab-5 = Select tab #5
zen-key-select-tab-6 = Select tab #6
zen-key-select-tab-7 = Select tab #7
zen-key-select-tab-8 = Select tab #8
zen-key-select-tab-last = Select last tab
zen-key-show-all-tabs = Show all tabs
zen-key-goto-history = Go to history
zen-key-go-home = Go Home
zen-bookmark-show-sidebar-shortcut = Show Bookmarks Sidebar
zen-bookmark-show-toolbar-shortcut = Show Bookmarks Toolbar
