pane-zen-looks-title = Tema e experiência
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Alterar o idioma padrão pode facilitar para que os sites te rastreiem.
zen-look-and-feel-colors-header = Selecione uma cor temática
zen-look-and-feel-colors-description = Faça o { -brand-short-name } com o tema e a experiência da maneira que você desejar
zen-look-and-feel-themed-toolbar = 
    .label = Faça a barra de ferramentas temática com a cor de destaque
pane-zen-side-panels-title = Painéis laterais do site
zen-side-panels-header = Opções gerais para os painéis do site
zen-side-panels-description = Aumente a produtividade por ter várias visualizações de uma só vez!
zen-side-panels-enabled = 
    .label = Ativar painéis laterais do site
zen-side-panels-close-on-blur = 
    .label = Fechar o painel quando perder o foco, caso não estiver fixo
zen-vertical-tabs-show-bottom-border = 
    .label = Mostrar borda para ícones inferiores
sync-currently-syncing-workspaces = Espaços de trabalho
sync-engine-workspaces = 
    .label = Espaços de trabalho
    .tooltiptext = Sincronize seus espaços de trabalho entre dispositivos
    .accesskey = W
zen-look-and-feel-compact-view-header = Exibir em vista compacta
zen-look-and-feel-compact-view-description = Apenas mostre as barras de ferramentas que você usa!
zen-look-and-feel-compact-view-enabled = 
    .label = Ativar o modo compacto do { -brand-short-name }
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Ocultar a barra de ferramentas superior e também no modo compacto
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Faça um breve popup da barra de ferramentas ao alterar ou abrir novas abas no modo compacto
zen-look-and-feel-buttons-header = Estilo de botão
zen-look-and-feel-buttons-description = Selecione o estilo dos botões que você queira ver
zen-look-and-feel-pilled-buttons = 
    .label = Botões redondos
pane-zen-tabs-title = Gerenciamento de abas
category-zen-workspaces = 
    .tooltiptext = { pane-zen-tabs-title }
pane-settings-workspaces-title = Espaços de trabalho
pane-zen-tabs-unloader-title = Descarregador de abas
zen-tabs-unloader-header = Opções gerais para descarregador de abas
zen-tabs-unloader-description = Descarregar abas inúteis automaticamente para salvar armazenamento
zen-tabs-unloader-enabled = 
    .label = Ativar descarregador de abas
zen-tabs-unloader-unload-delay = 
    .label = Descarregar abas após
zen-tabs-unloader-unload-delay-description = O tempo em minutos após cada aba será descarregada
pane-zen-workspaces-header = Espaços de trabalho
zen-settings-workspaces-header = Opções gerais para espaços de trabalho
zen-settings-workspaces-description = Com os espaços de trabalho, você pode ter várias sessões de busca de uma só vez!
zen-settings-workspaces-enabled = 
    .label = Ativar espaços de trabalho (Experimental)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Ocultar o indicador padrão de contêiner na barra de abas
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Permitir os espaços de trabalho ter as próprias abas fixadas
zen-key-unsafed = Atalho inseguro! Segure-o por clicar na tecla "Escape" após redigitá-lo.
zen-key-conflict = Conflitar com outro atalho
pane-zen-theme-title = Opções de tema
zen-vertical-tabs-title = Layout de abas e barras laterais
zen-vertical-tabs-header = Abas verticais
zen-vertical-tabs-description = Gerencie suas abas no layout vertical
zen-vertical-tabs-show-expand-button = 
    .label = Mostrar botão de expandir
zen-vertical-tabs-expand-tabs-by-default = Expandir abas por padrão
zen-vertical-tabs-dont-expand-tabs-by-default = Não expandir abas por padrão
zen-vertical-tabs-expand-tabs-on-hover = Expandir abas ao passar o mouse (Não funcionará no modo compacto)
zen-vertical-tabs-expand-tabs-header = Como expandir abas
zen-vertical-tabs-expand-tabs-description = Escolha como expandir abas na barra lateral
zen-theme-marketplace-header = Mods zen
zen-theme-marketplace-description = Encontre e instale temas da loja.
zen-theme-marketplace-remove-button = 
    .label = Remover tema
zen-theme-marketplace-check-for-updates-button = 
    .label = Procurar por atualizações
zen-theme-marketplace-updates-success = Tema atualizado com sucesso
zen-theme-marketplace-updates-fail = Não foi possível encontrar atualizações!
zen-theme-marketplace-toggle-enabled-button = 
    .title = Desativar tema
zen-theme-marketplace-toggle-disabled-button = 
    .title = Ativar tema
zen-theme-marketplace-remove-confirmation = Você tem certeza que quer remover esse mod?
zen-theme-marketplace-close-modal = Fechar
zen-theme-marketplace-theme-header-title = 
    .title = Seletor CSS: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = Nenhum
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Escreva algo...
pane-zen-marketplace-title = Mods zen
zen-settings-workspaces-display-as-icon-strip = 
    .label = Exibir áreas de trabalho como uma faixa de ícone
zen-theme-marketplace-link = Visitar loja
zen-dark-theme-styles-header = Estilos de tema escuro
zen-dark-theme-styles-description = Personalize o tema escuro como quiser
zen-dark-theme-styles-amoled = Tema noturno
zen-dark-theme-styles-default = Modo escuro (padrão)
zen-dark-theme-styles-colorful = Modo escuro colorido
zen-split-view-title = Vista dividida
zen-split-view-header = Funcionalidade de vista dividida
zen-split-view-description = Divida o seu navegador em várias vistas, permitindo você navegar em vários sites de uma só vez
zen-split-view-change-on-hover = 
    .label = Alterar abas ao passar mouse
zen-compact-mode-styles-left = Ocultar barra de abas
zen-compact-mode-styles-top = Ocultar barra superior
zen-compact-mode-styles-both = Ocultar ambos
pane-zen-CKS-title = Atalhos do teclado
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = Atalhos de teclado do { -brand-short-name }
zen-settings-CKS-header = Personalize seus atalhos de teclado
zen-settings-CKS-description = Mude os atalhos de teclado padrão como quiser e melhore sua experiência em navegação
zen-settings-CKS-disable-firefox = 
    .label = Desativar os atalhos de teclado padrão do { -brand-short-name }
zen-settings-CKS-duplicate-shortcut = 
    .label = Duplicar atalho
zen-settings-CKS-reset-shortcuts = 
    .label = Restaurar ao padrão
zenCKSOption-group-other = Outro
zenCKSOption-group-windowAndTabManagement = Gerenciamento de janela e aba
zenCKSOption-group-navigation = Navegação
zenCKSOption-group-searchAndFind = Pesquise e encontre
zenCKSOption-group-pageOperations = Operações de página
zenCKSOption-group-historyAndBookmarks = Histórico e favoritos
zenCKSOption-group-mediaAndDisplay = Mídia e exibição
zenCKSOption-group-zen-compact-mode = Modo compacto
zenCKSOption-group-zen-workspace = Espaços de trabalho
zenCKSOption-group-zen-other = Outros recursos zen
zenCKSOption-group-zen-split-view = Vista dividida
zen-key-quick-restart = Reinicialização rápida
zen-window-new-shortcut = Nova janela
zen-tab-new-shortcut = Nova aba
zen-key-redo = Refazer
zen-restore-last-closed-tab-shortcut = Restaurar última aba fechada
zen-location-open-shortcut = Abrir local
zen-location-open-shortcut-alt = Abrir local (alt)
zen-key-undo-close-window = Desfazer janela fechada
zen-text-action-undo-shortcut = Desfazer
zen-text-action-redo-shortcut = Refazer
zen-text-action-cut-shortcut = Cortar
zen-text-action-copy-shortcut = Copiar
zen-text-action-paste-shortcut = Colar
zen-text-action-select-all-shortcut = Selecionar tudo
zen-text-action-delete-shortcut = Excluir
zen-history-show-all-shortcut-mac = Mostrar histórico (Mac)
zen-full-screen-shortcut = Alternar tela cheia
zen-reader-mode-toggle-shortcut-windows = Alternar modo leitor (Windows)
zen-picture-in-picture-toggle-shortcut-alt = Alternar imagem em imagem (Alt)
zen-picture-in-picture-toggle-shortcut-mac = Alternar imagem em imagem (Mac)
zen-picture-in-picture-toggle-shortcut-mac-alt = Alternar Picture-in-Picture (Mac Alt)
zen-page-source-shortcut-safari = Ver origem da página (Safari)
zen-nav-stop-shortcut = Parar carregamento
zen-history-sidebar-shortcut = Mostrar histórico na barra lateral
zen-window-minimize-shortcut = Minimizar Janela
zen-help-shortcut = Abrir Ajuda
zen-preferences-shortcut = Abrir Preferências
zen-hide-app-shortcut = Ocultar Aplicação
zen-hide-other-apps-shortcut = Ocultar Outras Aplicações
zen-search-focus-shortcut = Pesquisa focada
zen-search-focus-shortcut-alt = Pesquisa focada (alt)
zen-downloads-shortcut = Abrir transferências
zen-addons-shortcut = Abrir extensões
zen-file-open-shortcut = Abrir arquivo
zen-save-page-shortcut = Salvar página
zen-print-shortcut = Imprimir página
zen-close-shortcut-2 = Fechar aba
zen-mute-toggle-shortcut = Alternar mudo
zen-key-delete = Excluir chave
zen-key-go-back = Voltar
zen-key-go-forward = Avançar
zen-nav-back-shortcut-alt = Navegar para trás (Alt)
zen-nav-fwd-shortcut-alt = Navegar para frente (Alt)
zen-history-show-all-shortcut = Mostrar todo histórico
zen-key-enter-full-screen = Entrar em tela cheia
zen-key-exit-full-screen = Sair da tela cheia
zen-reader-mode-toggle-shortcut-other = Alternar modo leitor
zen-picture-in-picture-toggle-shortcut = Alternar imagem em imagem
zen-nav-reload-shortcut-2 = Atualizar página
zen-key-about-processes = Sobre processos
zen-page-source-shortcut = Ver fonte da página
zen-page-info-shortcut = Ver informações da página
zen-find-shortcut = Pesquisar na página
zen-search-find-again-shortcut = Pesquisar novamente
zen-search-find-again-shortcut-prev = Pesquisar anterior
zen-search-find-again-shortcut-2 = Pesquisar novamente (Alt)
zen-bookmark-this-page-shortcut = Favoritar esta página
zen-bookmark-show-library-shortcut = Exibir histórico de favoritos
zen-key-stop = Parar de carregar
zen-full-zoom-reduce-shortcut = Reduzir
zen-full-zoom-enlarge-shortcut = Ampliar
zen-full-zoom-reset-shortcut = Redefinir ampliação
zen-bidi-switch-direction-shortcut = Alterar direção do texto
zen-private-browsing-shortcut = Navegação privada
zen-screenshot-shortcut = Tirar captura de tela
zen-key-sanitize = Limpar dados de navegação
zen-quit-app-shortcut = Sair do aplicativo
zen-key-wr-capture-cmd = Comando de captura WR
zen-key-wr-toggle-capture-sequence-cmd = Alternar sequência de captura WR
zen-nav-reload-shortcut = Atualizar página
zen-nav-reload-shortcut-skip-cache = Atualizar página (Pular cache)
zen-close-shortcut = Fechar janela
zen-close-tab-shortcut = Fechar aba
zen-compact-mode-shortcut-show-sidebar = Alternar barra lateral flutuante
zen-compact-mode-shortcut-show-toolbar = Alternar barra de ferramentas flutuante
zen-compact-mode-shortcut-toggle = Alternar modo compacto
zen-workspace-shortcut-switch-1 = Mudar para espaço de trabalho 1
zen-workspace-shortcut-switch-2 = Mudar para espaço de trabalho 2
zen-workspace-shortcut-switch-3 = Mudar para espaço de trabalho 3
zen-workspace-shortcut-switch-4 = Mudar para espaço de trabalho 4
zen-workspace-shortcut-switch-5 = Mudar para espaço de trabalho 5
zen-workspace-shortcut-switch-6 = Mudar para espaço de trabalho 6
zen-workspace-shortcut-switch-7 = Mudar para espaço de trabalho 7
zen-workspace-shortcut-switch-8 = Mudar para espaço de trabalho 8
zen-workspace-shortcut-switch-9 = Mudar para espaço de trabalho 9
zen-workspace-shortcut-switch-10 = Mudar para espaço de trabalho 10
zen-workspace-shortcut-forward = Avançar espaço de trabalho
zen-workspace-shortcut-backward = Voltar espaço de trabalho
zen-web-panel-shortcut-toggle = Alternar painel web
zen-sidebar-shortcut-toggle = Alternar largura da barra lateral
zen-split-view-shortcut-grid = Alternar grade de vista dividida
zen-split-view-shortcut-vertical = Alternar vista dividida vertical
zen-split-view-shortcut-horizontal = Alternar vista dividida horizontal
zen-split-view-shortcut-unsplit = Fechar vista dividida
zen-key-select-tab-1 = Selecionar guia #1
zen-key-select-tab-2 = Selecionar guia #2
zen-key-select-tab-3 = Selecionar guia #3
zen-key-select-tab-4 = Selecionar guia #4
zen-key-select-tab-5 = Selecionar guia #5
zen-key-select-tab-6 = Selecionar guia #6
zen-key-select-tab-7 = Selecionar guia #7
zen-key-select-tab-8 = Selecionar guia #8
zen-key-select-tab-last = Selecionar última guia
zen-key-show-all-tabs = Mostrar todas as abas
zen-key-goto-history = Ir ao histórico
zen-key-go-home = Ir à página inicial
zen-bookmark-show-sidebar-shortcut = Mostrar favoritos na barra lateral
zen-bookmark-show-toolbar-shortcut = Mostrar barra de favoritos
