pane-zen-looks-title = Aparência e Experiência
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Alterar o idioma padrão pode facilitar que sites rastreiem você.
zen-look-and-feel-colors-header = Escolha a cor do tema
zen-look-and-feel-colors-description = Deixe o { -brand-short-name } com a aparência e estilo que você gosta
zen-look-and-feel-themed-toolbar = 
    .label = Personalize a barra de ferramentas com a cor de destaque
pane-zen-side-panels-title = Painéis Web Laterais
zen-side-panels-header = Configurações gerais para painéis web
zen-side-panels-description = Aumente a produtividade tendo várias visualizações simultaneamente!
zen-side-panels-enabled = 
    .label = Habilitar Painéis Web Laterais
zen-side-panels-close-on-blur = 
    .label = Fechar o painel quando perder o foco, caso não esteja fixo
zen-look-and-feel-compact-view-header = Exibir em visualização compacta
zen-look-and-feel-compact-view-description = Mostre apenas as barras de ferramentas que você usa!
zen-look-and-feel-compact-view-enabled = 
    .label = Habilitar o modo compacto do { -brand-short-name }
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Ocultar a barra de ferramentas superior também no modo compacto
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Briefly make the toolbar popup when switching or opening new tabs in compact mode
zen-look-and-feel-buttons-header = Estilo do botão
zen-look-and-feel-buttons-description = Escolha o estilo dos botões que você deseja ver
zen-look-and-feel-pilled-buttons = 
    .label = Botões Arredondados
pane-zen-workspaces-title = Espaços de Trabalho
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = Espaços de Trabalho
pane-zen-workspaces-header = Espaços de Trabalho
zen-settings-workspaces-header = Configurações gerais para espaços de trabalho
zen-settings-workspaces-description = Com os espaços de trabalho, você pode ter várias sessões de navegação simultaneamente!
zen-settings-workspaces-enabled = 
    .label = Habilitar Espaços de Trabalho (Experimental)
pane-zen-theme-title = Configurações de tema
zen-vertical-tabs-title = Layout da Barra Lateral e Abas
zen-vertical-tabs-header = Abas Verticais
zen-vertical-tabs-description = Gerencie suas abas em um layout vertical
zen-vertical-tabs-show-expand-button = 
    .label = Mostrar botão Expandir
zen-vertical-tabs-expand-tabs-by-default = Expandir Abas por Padrão
zen-vertical-tabs-dont-expand-tabs-by-default = Não Expandir Abas por Padrão
zen-vertical-tabs-expand-tabs-on-hover = Expandir Abas ao passar o mouse (Não funciona no modo compacto)
zen-vertical-tabs-expand-tabs-header = Como expandir as abas
zen-vertical-tabs-expand-tabs-description = Escolha como expandir as abas na barra lateral
zen-theme-marketplace-header = Loja de Temas
zen-theme-marketplace-description = Encontre e instale temas na loja.
zen-theme-marketplace-remove-button = 
    .label = Remover tema
zen-theme-marketplace-check-for-updates-button = 
    .label = Checar por Atualizações
zen-theme-marketplace-updates-success = Tema atualizado com sucesso
zen-theme-marketplace-updates-fail = Não foi possível encontrar nenhuma atualização!
pane-zen-marketplace-title = Loja de Temas
zen-look-and-feel-legacy-toolbar = 
    .label = Use legacy toolbar position. Requires a restart!
zen-theme-marketplace-link = Visitar Loja
zen-dark-theme-styles-header = Dark Theme Styles
zen-dark-theme-styles-description = Customize the dark theme to your liking
zen-dark-theme-styles-amoled = Amoled Black
zen-dark-theme-styles-default = Default Dark Theme
zen-dark-theme-styles-colorful = Colorful Dark Theme
pane-zen-CKS-title = Atalhos do teclado
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = Atalhos de Teclado do { -brand-short-name }
zen-settings-CKS-header = Personalize seus atalhos de teclado
zen-settings-CKS-description = Altere os atalhos de teclado padrão de acordo com sua preferência e melhore sua experiência de navegação
zen-settings-CKS-disable-firefox = 
    .label = Desativar os atalhos de teclado padrão do { -brand-short-name }
zen-cks-group-tab-action = Ações da Aba
zen-cks-group-page-action = Ações de Página
zen-cks-group-visible-action = Ações Visíveis
zen-cks-group-history-action = Ações de Histórico
zen-cks-group-search-action = Ações de Pesquisa
zen-cks-group-tools-action = Ações de Ferramentas
zen-cks-group-bookmark-action = Ações de Favoritos
zen-cks-group-open-page-action = Ações de Abrir Página
zen-cks-group-downloads-action = Ações de Downloads
zen-cks-group-sidebar-action = Ações da Sidebar
zen-cks-group-compact-mode-action = Ações do Modo Compacto
zen-cks-group-split-view-action = Ações de Visualização Dividida
zen-cks-group-workspace-action = Ações de Espaço de Trabalho
open-new-tab = Abrir Nova Aba
close-tab = Fechar Aba
open-new-window = Abrir Nova Janela
open-new-private-window = Abrir Nova Janela Privada
close-window = Fechar Janela
restore-last-tab = Restaurar Última Aba
restore-last-window = Restaurar Última Janela
show-next-tab = Mostrar Próxima Aba
show-previous-tab = Mostrar Aba Anterior
show-all-tabs-panel = Mostrar todas as abas
send-with-mail = Enviar Página por E-mail
save-page = Salvar Página
print-page = Imprimir Página
mute-current-tab = Silenciar Aba Atual
show-source-of-page = Mostrar Código Fonte da Página
show-page-info = Mostrar Informações da Página
zoom-in = Aumentar Zoom
zoom-out = Diminuir o Zoom
reset-zoom = Restaurar Zoom
back = Anterior
forward = Avançar
stop = Parar
reload = Recarregar
force-reload = Forçar Recarregamento
search-in-this-page = Pesquisar nessa Página
show-next-search-result = Mostrar Próximo Resultado
show-previous-search-result = Mostrar Resultado Anterior
search-the-web = Procurar na Web
open-migration-wizard = Abrir Assistente de Migração
quit-from-application = Fechar Aplicativo
enter-into-customize-mode = Abrir Modo de Personalização
enter-into-offline-mode = Ativar Modo Offline
open-screen-capture = Abrir Captura de Tela
bookmark-this-page = Adicionar esta Página aos Favoritos
open-bookmark-add-tool = Abrir Adicionar aos Favoritos
open-bookmarks-manager = Abrir Gerenciador de Favoritos
toggle-bookmark-toolbar = Alternar Barra de Favoritos
open-general-preferences = Preferências
open-privacy-preferences = Preferências de Privacidade
open-workspaces-preferences = Preferências de Espaços de Trabalho
open-containers-preferences = Preferências de Containers
open-search-preferences = Preferências de Pesquisa
open-sync-preferences = Preferências de Sincronização
open-task-manager = Gerenciador de Tarefas
open-addons-manager = Gerenciar Extensões
open-home-page = Abrir Página Inicial
forget-history = Esquecer Histórico
quick-forget-history = Esquecer Histórico
clear-recent-history = Limpar Histórico Recente
restore-last-session = Restaurar Última Sessão
search-history = Pesquisar no Histórico
manage-history = Gerenciar Histórico
open-downloads = Abrir Downloads
show-bookmark-sidebar = Mostrar Barra de Favoritos Lateral
show-history-sidebar = Mostrar Barra de Histórico Lateral
show-synced-tabs-sidebar = Exibir barra lateral Abas Sincronizadas
reverse-sidebar = Inverter Posição da Barra Lateral
hide-sidebar = Ocultar Barra Lateral
toggle-sidebar = Alternar Barra Lateral
zen-toggle-web-panels = Ativar/Desativar Painéis Web
zen-toggle-compact-mode = Alternar Modo Compacto
zen-toggle-compact-mode-sidebar = Alternar Barra do Modo Compacto Lateral
zen-toggle-compact-mode-toolbar = Alternar Barra de Ferramentas no Modo Compacto
zen-change-workspace = Alternar Espaços de Trabalho
zen-split-view-grid = Exibição dividida em grade
zen-split-view-vertical = Exibição dividida vertical
zen-split-view-horizontal = Divisão Horizontal
zen-split-view-close = Fechar Visualização Dividida
zen-expand-sidebar = Toggle Sidebar Expand
