zen-panel-ui-workspaces-text = סביבות עבודה
zen-panel-ui-workspaces-create = 
    .label = Create Space
zen-panel-ui-workspaces-edit-text = ערוך סביבת עבודה
zen-panel-ui-workspaces-edit-save = 
    .label = שמור שינויים
    .accesskey = ד
zen-panel-ui-workspaces-edit-cancel = 
    .label = ביטול
    .accesskey = ב
zen-workspaces-panel-context-delete = 
    .label = מחק סיבת עבודה
    .accesskey = ג
zen-workspaces-panel-change-name = 
    .label = Change Name
zen-workspaces-panel-change-icon = 
    .label = Change Icon
zen-workspaces-panel-context-manage = 
    .label = Manage Workspaces
    .accesskey = M
zen-workspaces-panel-context-open-in-container-tab = 
    .label = הגדר מכל ברירת מחדל
    .accesskey = ם
zen-workspaces-how-to-reorder = To reorder spaces, drag and drop them from the space icons at the bottom of the sidebar.
zen-workspaces-change-theme = 
    .label = Edit Theme
zen-workspaces-panel-context-open = 
    .label = פתח סביבת עבודה
    .accesskey = ם
zen-workspaces-panel-context-set-default = 
    .label = הגדר כסביבת עבודה ברירת מחדל
    .accesskey = ד
zen-workspaces-panel-context-edit = 
    .label = ערוך סביבת עבודה
    .accesskey = ק
context-zen-change-workspace-tab = 
    .label = העבר כרטיסיות לסביבת עבודה
    .accesskey = ב
zen-bookmark-edit-panel-workspace-selector = 
    .value = סביבות עבודה
    .accesskey = '
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = משלים
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = חצוי
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = אנלוגי
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = טריאדי
zen-panel-ui-gradient-generator-algo-floating = 
    .label = מרחף
zen-panel-ui-gradient-click-to-add = לחיצה להוספת צבע
zen-workspace-creation-name = 
    .placeholder = Space Name
zen-workspaces-panel-context-reorder = 
    .label = Reorder Workspaces
zen-workspace-creation-profile = Profile
    .tooltiptext = Profiles are used to separate cookies and site data between spaces.
zen-workspace-creation-header = Create a Space
zen-workspace-creation-label = Spaces are used to organize your tabs and sessions.
