zen-panel-ui-workspaces-text = Other workspaces
zen-panel-ui-workspaces-create-text = Create Workspace
zen-panel-ui-workspaces-create-save = 
    .label = Create Workspace
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = Cancel
    .accesskey = C
zen-panel-ui-workspaces-edit-text = Edit Workspace
zen-panel-ui-workspaces-edit-save = 
    .label = Save Changes
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Cancel
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Delete Workspace
    .accesskey = D
zen-workspaces-panel-context-open = 
    .label = Open Workspace
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Set As Default Workspace
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Edit Workspace
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Change Tab(s) To Workspace
    .accesskey = C
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Set Default Container
    .accesskey = O
zen-workspaces-change-gradient = 
    .label = Change Theme Colours
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Other Workspace
    .accesskey = WWWWWorkspace
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Complementary
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Split
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Analogous
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Triadic
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Floating
zen-panel-ui-gradient-click-to-add = Click to add a colour
