zen-panel-ui-current-window-text = Поточне вікно
zen-panel-ui-workspaces-text = Інші робочі простори
zen-panel-ui-workspaces-create-text = Створити робочу область
zen-panel-ui-workspaces-create-save = 
    .label = Створити робочу область
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = Скасувати
    .accesskey = C
zen-panel-ui-workspaces-edit-text = Edit Workspace
zen-panel-ui-workspaces-edit-save = 
    .label = Save Changes
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Cancel
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Видалити робочу область
    .accesskey = D
zen-workspaces-panel-context-open = 
    .label = Відкритий робочий простір
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Встановити робочу область за замовчуванням
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Edit Workspace
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Змінити вкладку(и) на робочу область
    .accesskey = C
