zen-web-side-panel-context-mute-panel = 
    .label = Вимкнення звуку на вебпанелі
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = Увімкнути звук на вебпанелі
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = Вимкнути Mobile UserAgent
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Увімкнути Mobile UserAgent
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = Вимкнути вебпанель
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = Видалити вебпанель
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = Відкрити в новій вкладці
    .accesskey = N
zen-web-side-panel-context-add-to-panel = 
    .label = Додати на вебпанель
    .accesskey = A
zen-sidebar-introduction-title = Ласкаво просимо на Zen Sidebar
zen-sidebar-introduction-description = Zen Sidebar - це новий спосіб перегляду вебсторінок. Натисніть на будь-яку іконку, щоб відкрити вебпанель.
