zen-panel-ui-current-profile-text = поточний профіль
unified-extensions-description = Розширення використовуються, щоб додати більше функціональних можливостей до { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = Скинути закріплену вкладку
    .accesskey = Р
tab-context-zen-add-essential = 
    .label = Add to Essentials
    .accesskey = E
tab-context-zen-remove-essential = 
    .label = Remove from Essentials
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Замінити Закріплений URL на поточний
    .accesskey = C
tab-zen-unload = 
    .label = Unload Tab
    .accesskey = У
zen-tabs-unloader-tab-actions = 
    .label = Дії з завантажувачем вкладок
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Заборонити вивантаження вкладок
    .accesskey = Пн
tab-zen-ignore-unload = 
    .label = Дозволити вивантаження вкладок
    .accesskey = I
zen-themes-corrupted = Ваш файл модифікацій { -brand-short-name } пошкоджено. Вони були скинуті до типової теми.
zen-panel-ui-gradient-generator-opacity-text = Контрастність
zen-panel-ui-gradient-generator-texture-text = Текстура
zen-panel-ui-gradient-generator-custom-color = Колір за користувачем
zen-panel-ui-gradient-generator-saved-message = Градієнт успішно збережено!
