zen-panel-ui-workspaces-text = Робочі області
zen-panel-ui-workspaces-create = 
    .label = Create Space
zen-panel-ui-workspaces-edit-text = Редагувати робочу область
zen-panel-ui-workspaces-edit-save = 
    .label = Зберегти зміни
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Скасувати
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Видалити робочу область
    .accesskey = D
zen-workspaces-panel-change-name = 
    .label = Змінити назву
zen-workspaces-panel-change-icon = 
    .label = Change Icon
zen-workspaces-panel-context-manage = 
    .label = Manage Workspaces
    .accesskey = M
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Встановити типовий контейнер
    .accesskey = O
zen-workspaces-how-to-reorder = To reorder spaces, drag and drop them from the space icons at the bottom of the sidebar.
zen-workspaces-change-theme = 
    .label = Edit Theme
zen-workspaces-panel-context-open = 
    .label = Відкрити робочу область
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Встановити типову робочу область
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Редагувати робочу область
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Перемістити вкладку(и) на робочу область
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Робочі області
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Додатковий
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Роздільний
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Аналоговий
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Трійковий
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Плавучий
zen-panel-ui-gradient-click-to-add = Клацніть, щоби додати колір
zen-workspace-creation-name = 
    .placeholder = Space Name
zen-workspaces-panel-context-reorder = 
    .label = Reorder Workspaces
zen-workspace-creation-profile = Profile
    .tooltiptext = Profiles are used to separate cookies and site data between spaces.
zen-workspace-creation-title = Create a new Space
zen-workspace-creation-label = Spaces are used to organize your tabs and sessions.
