zen-toolbar-context-tabs-right = 
    .label = Вкладки праворуч
    .accesskey = R
zen-toolbar-context-compact-mode = 
    .label = Компактний режим
    .accesskey = C
zen-toolbar-context-compact-mode-enable = 
    .label = Ввімкнути компактний режим
    .accesskey = D
zen-toolbar-context-compact-mode-just-tabs = 
    .label = Приховати бічну панель
zen-toolbar-context-compact-mode-just-toolbar = 
    .label = Приховати панель інструментів
zen-toolbar-context-compact-mode-hide-both = 
    .label = Приховати обидві
    .accesskey = H
sidebar-zen-sidepanel = 
    .label = Бічні панелі
sidebar-zen-expand = 
    .label = Розгорнути бічну панель
