zen-web-side-panel-context-mute-panel = 
    .label = Вимкнути звук веб-панелі
    .accesskey = М-ль
zen-web-side-panel-context-unmute-panel = 
    .label = Увімкнути звук панелі веб-пошуку
    .accesskey = м
zen-web-side-panel-context-disable-ua = 
    .label = Вимкнути мобільний UserAgent
    .accesskey = У
zen-web-side-panel-context-enable-ua = 
    .label = Увімкнути мобільний UserAgent
    .accesskey = М-ль
zen-web-side-panel-context-unload = 
    .label = Розрядити панель для завантаження
    .accesskey = Пт
zen-web-side-panel-context-delete = 
    .label = Видалити веб-панель
    .accesskey = Ре
zen-web-side-panel-open-in-new-tab = 
    .label = Відкрити у новій вкладці
    .accesskey = Н
zen-web-side-panel-context-open-in-container-tab = 
    .label = Відкрити в вкладці контейнера
    .accesskey = До
zen-web-side-panel-context-add-to-panel = 
    .label = Додати в веб-панелі
    .accesskey = Ля
zen-sidebar-introduction-title = Ласкаво просимо до Zen Sidebar
zen-sidebar-introduction-description = Zen Sidebar - це новий спосіб перегляду веб-сторінки. Натисніть на будь-яке з іконок, щоб відкрити веб-панель.
