zen-panel-ui-workspaces-text = Робочі області
zen-panel-ui-workspaces-create-text = Створити робочу область
zen-panel-ui-workspaces-create-save = 
    .label = Створити робочу область
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = Скасувати
    .accesskey = C
zen-panel-ui-workspaces-edit-text = Редагувати робочу область
zen-panel-ui-workspaces-edit-save = 
    .label = Зберегти зміни
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Скасувати
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Видалити робочу область
    .accesskey = D
zen-workspaces-panel-change-name = 
    .label = Change Name
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Встановити типовий контейнер
    .accesskey = O
zen-workspaces-change-gradient = 
    .label = Змінити колір теми
    .accesskey = C
zen-workspaces-panel-context-open = 
    .label = Відкрити робочу область
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Встановити як типову робочу область
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Редагувати робочу область
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Змінити вкладку(и) на робочу область
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Робочі області
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Додатковий
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Роздільний
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Аналоговий
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Трійковий
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Плавучий
zen-panel-ui-gradient-click-to-add = Клацніть, щоби додати колір
