zen-panel-ui-current-profile-text = поточний профіль
unified-extensions-description = Розширення використовуються, щоб додати більше функціональних можливостей до { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = Скинути закріплену вкладку
    .accesskey = Р
tab-context-zen-replace-pinned-url-with-current = 
    .label = Замінити Закріплений URL на поточний
    .accesskey = До
tab-zen-unload = 
    .label = Unload Tab
    .accesskey = У
zen-tabs-unloader-tab-actions = 
    .label = Дії з завантажувачем вкладок
    .accesskey = Т
tab-zen-prevent-unload = 
    .label = Заборонити вивантаження вкладок
    .accesskey = Пн
tab-zen-ignore-unload = 
    .label = Дозволити вивантаження вкладок
    .accesskey = Я
zen-themes-corrupted = Ваш файл модифікацій { -brand-short-name } пошкоджено. Вони були скинуті до типової теми.
zen-panel-ui-gradient-generator-opacity-text = Contrast
zen-panel-ui-gradient-generator-texture-text = Текстура
zen-panel-ui-gradient-generator-custom-color = Колір за користувачем
zen-panel-ui-gradient-generator-saved-message = Градієнт успішно збережено!
