zen-web-side-panel-context-mute-panel = 
    .label = Ztlumit webový panel
    .accesskey = MM
zen-web-side-panel-context-unmute-panel = 
    .label = Zrušit ztlumení webového panelu
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = Zakázat mobilního UserAgent
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Povolit mobilní UserAgent
    .accesskey = MM
zen-web-side-panel-context-unload = 
    .label = Zrušit načítání webového panelu
    .accesskey = ZA
zen-web-side-panel-context-delete = 
    .label = Odstranit webový panel
    .accesskey = L 343, 22.12.2009, s. 1).
zen-web-side-panel-open-in-new-tab = 
    .label = Otevřít v nové kartě
    .accesskey = SP
zen-web-side-panel-context-open-in-container-tab = 
    .label = Otevřít na kartě Kontejneru
    .accesskey = C
zen-web-side-panel-context-add-to-panel = 
    .label = Přidat do webového panelu
    .accesskey = A
zen-sidebar-introduction-title = Vítejte v Zen Sidebar
zen-sidebar-introduction-description = Zen Sidebar je nový způsob, jak prohlížet web. Pro otevření webového panelu klikněte na kteroukoli z ikon.
