zen-panel-ui-workspaces-text = Pracovní prostory
zen-panel-ui-workspaces-create = 
    .label = Vytvořit prostor
zen-workspaces-panel-context-delete = 
    .label = Odstranit pracovní prostor
    .accesskey = D
zen-workspaces-panel-change-name = 
    .label = Změnit jméno
zen-workspaces-panel-change-icon = 
    .label = Změnit ikonu
zen-workspaces-panel-context-default-profile = 
    .label = Set Profile
zen-workspaces-how-to-reorder-title = How to reorder spaces
zen-workspaces-how-to-reorder-desc = Drag the space icons at the bottom of the sidebar to reorder them
zen-workspaces-change-theme = 
    .label = Upravit motiv
zen-workspaces-panel-context-open = 
    .label = Otevřít pracovní prostor
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Nastavit jako výchozí pracovní prostor
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Upravit pracovní prostor
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Přesunout panel(y) do pracovního prostoru
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Pracovní prostory
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Protilehlé
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Rozdělené
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Příbuzné
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Trojbarevné
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Plovoucí
zen-panel-ui-gradient-click-to-add = Kliknutím přidáte barvu
zen-workspace-creation-name = 
    .placeholder = Název prostoru
zen-workspaces-panel-context-reorder = 
    .label = Reorder Spaces
zen-workspace-creation-profile = Profil
    .tooltiptext = Profily se používají k oddělení cookies a údajů webových stránek mezi prostory.
zen-workspace-creation-header = Vytvořte si prostor
zen-workspace-creation-label = Prostory slouží k organizaci Vašich karet a relací.
zen-workspaces-delete-workspace-title = Delete Workspace?
zen-workspaces-delete-workspace-body = Are you sure you want to delete this workspace? This action cannot be undone.
