zen-web-side-panel-context-mute-panel = 
    .label = Ztlumit webový panel
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = Zrušit ztlumení webového panelu
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = Zakázat mobilního uživatelského agent
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Povolit mobilního uživatelského agenta
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = Zrušit načtené webového panelu
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = Vymazat webový panel
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = Otevřít v nové kartě
    .accesskey = N
zen-web-side-panel-context-open-in-container-tab = 
    .label = Open in Container Tab
    .accesskey = C
zen-web-side-panel-context-add-to-panel = 
    .label = Přidat do webových panelů
    .accesskey = A
zen-sidebar-introduction-title = Vítejte v Zen bočním panelu
zen-sidebar-introduction-description = Boční panel Zen je nový způsob prohlížení webu. Klikněte na kteroukoli ikonu pro otevření webového panelu.
