zen-panel-ui-current-profile-text = aktuální profil
unified-extensions-description = { -brand-short-name } podporuje rozšíření pro přidání extra funkcí.
tab-context-zen-reset-pinned-tab = 
    .label = Resetovat připnuté karty
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Nahradit připnutou URL adresu aktuální adresou
    .accesskey = C
tab-zen-unload = 
    .label = Uspat kartu
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Tabs Unloader Actions
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Zamezit uspávání karet
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Povolit uspávání karet
    .accesskey = I
zen-themes-corrupted = Your { -brand-short-name } mods file is corrupted. They have been reset to the default theme.
zen-panel-ui-gradient-generator-opacity-text = Kontrast
zen-panel-ui-gradient-generator-texture-text = Texture
zen-panel-ui-gradient-generator-custom-color = Custom Color
zen-panel-ui-gradient-generator-saved-message = Successfully saved the gradient!
