zen-panel-ui-workspaces-text = Pracovní prostory
zen-panel-ui-workspaces-create-text = Vytvořit pracovní prostor
zen-panel-ui-workspaces-create-save = 
    .label = Vytvořit pracovní prostor
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = Zrušit
    .accesskey = C
zen-panel-ui-workspaces-edit-text = Upravit pracovní prostor
zen-panel-ui-workspaces-edit-save = 
    .label = Uložit změny
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Zrušit
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Odstranit pracovní prostor
    .accesskey = D
zen-workspaces-panel-context-open = 
    .label = Otevřít pracovní prostor
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Nastavit jako výchozí pracovní prostor
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Upravit pracovní prostor
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Přesunout panel(y) do pracovního prostoru
    .accesskey = C
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Nastavit výchozí kontejner
    .accesskey = O
zen-workspaces-change-gradient = 
    .label = Změnit barvy motivu
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Pracovní prostory
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Protilehlý
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Rozdělený
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Příbuzný
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Trojbarevný
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Plovoucí
zen-panel-ui-gradient-click-to-add = Click to add a color
