zen-web-side-panel-context-mute-panel = 
    .label = Ztlumit webový panel
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = Zrušit ztlumení webového panelu
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = Zakázat mobilního UserAgent
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Povolit mobilní UserAgent
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = Uspat webový panel
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = Odstranit webový panel
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = Otevřít v nové kartě
    .accesskey = N
zen-web-side-panel-context-open-in-container-tab = 
    .label = Otevřít na kartě Kontejneru
    .accesskey = C
zen-web-side-panel-context-add-to-panel = 
    .label = Přidat do webových panelů
    .accesskey = A
zen-sidebar-introduction-title = Vítejte v Zen Sidebar
zen-sidebar-introduction-description = Zen Sidebar je nový způsob, jak prohlížet web. Pro otevření webového panelu klikněte na kteroukoli z ikon.
