zen-panel-ui-current-profile-text = aktuální profil
unified-extensions-description = Rozšíření slouží k přidání dalších funkcí do prohlížeče { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = Resetovat připnuté karty
    .accesskey = R
tab-context-zen-add-essential = 
    .label = Přidat do Essentials
    .accesskey = E
tab-context-zen-remove-essential = 
    .label = Odstranit z Essentials
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Nahradit připnutou URL adresu aktuální adresou
    .accesskey = C
tab-zen-unload = 
    .label = Uspat kartu
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Akce vyladění záložek
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Zamezit uspávání karet
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Povolit uspávání karet
    .accesskey = I
zen-themes-corrupted = Váš { -brand-short-name } mods soubor je poškozen. Byl obnoven na výchozí motiv.
zen-panel-ui-gradient-generator-opacity-text = Kontrast
zen-panel-ui-gradient-generator-texture-text = Textura
zen-panel-ui-gradient-generator-custom-color = Vlastní barva
zen-panel-ui-gradient-generator-saved-message = Gradient byl úspěšně uložen!
zen-copy-current-url-confirmation = URL adresa byla zkopírována do schránky.
zen-rice-share-name = 
    .placeholder = Jméno Rice
zen-rice-share-author = Od
zen-rice-share-author-input = 
    .placeholder = Vaše jméno
zen-rice-share-cancel = Zrušit
zen-rice-share-save = Sdílet
zen-rice-share-include-userchrome = 
    .label = Include zen window styles (userChrome.css)
zen-rice-share-include-usercontent = 
    .label = Include website styles (userContent.css)
zen-rice-share-include-mods = 
    .label = Zahrnout povolené módy
zen-rice-share-include-mod-prefs = 
    .label = Zahrnout rozložení
zen-rice-share-include-preferences = 
    .label = Include layout preferences
zen-rice-share-include-workspace-themes = 
    .label = Zahrnout gradient pracovního prostoru
zen-rice-share-success = Rice byl úspěšně vytvořen!
zen-rice-share-success-link = Odkaz na sdílení Rice
zen-rice-share-include = Exportovat nastavení
appmenu-zen-share-rice = 
    .label = Sdílet Zen Rice
zen-close-label = Zavřít
