zen-toolbar-context-tabs-right = 
    .label = Karty vpravo
    .accesskey = R
zen-toolbar-context-compact-mode = 
    .label = Kompaktní režim
    .accesskey = C
zen-toolbar-context-compact-mode-enable = 
    .label = Povolit kompaktní režim
    .accesskey = D
zen-toolbar-context-compact-mode-just-tabs = 
    .label = Hide sidebar
zen-toolbar-context-compact-mode-just-toolbar = 
    .label = Skrýt lištu nástrojů
zen-toolbar-context-compact-mode-hide-both = 
    .label = Skrýt obojí
    .accesskey = H
sidebar-zen-sidepanel = 
    .label = Boční panely
sidebar-zen-expand = 
    .label = Expand Sidebar
