zen-panel-ui-current-profile-text = aktuální profil
unified-extensions-description = Rozšíření slouží k vložení dalších funkcí do { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = Resetovat připnuté záložky
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Nahradit připnuté URL aktuální
    .accesskey = C
tab-zen-unload = 
    .label = Unload Tab
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Akce vyladění záložek
    .accesskey = TT
tab-zen-prevent-unload = 
    .label = Zabránit odpojení záložky
    .accesskey = PR
tab-zen-ignore-unload = 
    .label = Povolit vyprázdnění záložky
    .accesskey = I
zen-themes-corrupted = Váš { -brand-short-name } mods soubor je poškozen. Byl obnoven na výchozí motiv.
zen-panel-ui-gradient-generator-opacity-text = Contrast
zen-panel-ui-gradient-generator-texture-text = Textilie
zen-panel-ui-gradient-generator-custom-color = Vlastní barva
zen-panel-ui-gradient-generator-saved-message = gradient byl úspěšně uložen!
