zen-panel-ui-current-window-text = Aktuální okno
zen-panel-ui-workspaces-text = Další pracovní plochy
zen-panel-ui-workspaces-create-text = Vytvořit pracovní plochu
zen-panel-ui-workspaces-create-save = 
    .label = Vytvořit pracovní plochu
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = Zrušit
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Vymazat pracovní plochu
    .accesskey = D
zen-workspaces-panel-context-open = 
    .label = Otevřít pracovní plochu
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Nastavit jako výchozí pracovní plochu
    .accesskey = S
context-zen-change-workspace-tab = 
    .label = Změnit pracovní plochu karty (karet)
    .accesskey = C
