pane-zen-looks-title = 모양
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = 기본 언어를 변경하면 웹사이트에서 사용자를 추적하기 더 쉬워질 수 있습니다.
zen-look-and-feel-colors-header = 테마 색상
zen-look-and-feel-colors-description = { -brand-short-name } 를 내 취향에 맞게 마음껏 꾸며주세요.
zen-look-and-feel-use-workspace-colors = 
    .label = Use workspace colors as primary color
pane-zen-side-panels-title = 사이드 웹 패널
zen-side-panels-header = 웹 패널 기본 설정
zen-side-panels-description = 한 번에 여러 페이지를 보면서 생산성을 높이세요!
zen-side-panels-enabled = 
    .label = 웹 사이드 패널 활성화
zen-side-panels-close-on-blur = 
    .label = 고정되어 있지 않고 다른 곳이 선택될 때 패널 닫기
zen-vertical-tabs-show-bottom-border = 
    .label = 아랫쪽 아이콘 테두리 선 보이기
zen-vertical-tabs-layout-header = Browser Layout
zen-vertical-tabs-layout-description = Choose the layout that suits you best
zen-layout-single-toolbar = Single toolbar
zen-layout-multiple-toolbar = Multiple toolbars
zen-layout-collapsed-toolbar = Collapsed toolbar
sync-currently-syncing-workspaces = 워크스페이스
sync-engine-workspaces = 
    .label = 워크스페이스
    .tooltiptext = 여러 기기의 워크스페이스 동기화
    .accesskey = W
zen-glance-title = Glance
zen-glance-header = General settings for glance
zen-glance-description = Get a quick overview of your links without opening them in a new tab
zen-glance-trigger-label = Trigger method
zen-glance-enabled = 
    .label = Enable Glance
zen-glance-trigger-ctrl-click = 
    .label = Ctrl + Click
zen-glance-trigger-alt-click = 
    .label = Alt + Click
zen-glance-trigger-shift-click = 
    .label = Shift + Click
zen-glance-trigger-meta-click = 
    .label = Meta (Command) + Click
zen-glance-trigger-mantain-click = 
    .label = Mantain Click
zen-look-and-feel-compact-view-header = 컴팩트 모드로 보기
zen-look-and-feel-compact-view-description = 사용하는 툴바만 보세요!
zen-look-and-feel-compact-view-enabled = 
    .label = { -brand-short-name }의 컴팩트 모드 활성화
zen-look-and-feel-compact-view-top-toolbar = 
    .label = 컴팩트 모드에서 상단 툴바 숨기기
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = 컴팩트 모드에서 새 탭을 전환하거나 열 때 툴바를 간략하게 팝업으로 표시합니다.
zen-look-and-feel-buttons-header = 버튼 스타일
zen-look-and-feel-buttons-description = 보고싶은 버튼 스타일을 선택하세요
zen-look-and-feel-pilled-buttons = 
    .label = 알약 모양 버튼
pane-zen-tabs-title = 탭 관리
category-zen-workspaces = 
    .tooltiptext = { pane-zen-tabs-title }
pane-settings-workspaces-title = 워크스페이스
pane-zen-tabs-unloader-title = 탭 언로더
zen-tabs-unloader-header = 탭 언로더 일반 설정
zen-tabs-unloader-description = 자동으로 쓰이지 않는 탭을 언로드해 메모리를 아낍니다
zen-tabs-unloader-enabled = 
    .label = 탭 언로더 활성화
zen-tabs-unloader-unload-delay = 
    .label = 이 시간 후 탭 언로드
zen-tabs-unloader-unload-delay-description = 언로드될 탭이 쓰이지 않은 시간
zen-look-and-feel-compact-toolbar-themed = 
    .label = Use themed background for compact toolbar
zen-look-and-feel-compact-sidebar-themed = 
    .label = Use themed background for compact sidebar
pane-zen-pinned-tab-manager-title = 고정된 탭
zen-pinned-tab-manager-header = 고정된 탭 설정
zen-pinned-tab-manager-description = 고정된 탭 추가 설정
zen-pinned-tab-manager-restore-pinned-tabs-to-pinned-url = 
    .label = 재시작할 때 고정된 탭의 URL 초기화
zen-pinned-tab-manager-container-specific-essentials-enabled = 
    .label = Enable container-specific essentials
zen-pinned-tab-manager-close-shortcut-behavior-label = 탭 닫기 단축키의 행동
zen-pinned-tab-manager-reset-unload-switch-close-shortcut-option = 
    .label = URL 초기화, 탭 언로드 후 다음 탭으로 이동
zen-pinned-tab-manager-unload-switch-close-shortcut-option = 
    .label = 탭 언로드 후 다음 탭으로 이동
zen-pinned-tab-manager-reset-switch-close-shortcut-option = 
    .label = URL 초기화 후 다음 탭으로 이동
zen-pinned-tab-manager-switch-close-shortcut-option = 
    .label = 다음 탭으로 이동
zen-pinned-tab-manager-reset-close-shortcut-option = 
    .label = URL 초기화
zen-pinned-tab-manager-close-close-shortcut-option = 
    .label = 탭 닫기
pane-zen-workspaces-header = 워크스페이스
zen-settings-workspaces-header = 워크스페이스 기본 설정
zen-settings-workspaces-description = 워크스페이스로, 여러 개의 브라우저 세션을 동시에 사용할 수 있습니다!
zen-settings-workspaces-enabled = 
    .label = 워크스페이스 활성화 (실험적)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = 탭 표시줄에서 기본 컨테이너 표시기를 숨깁니다.
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = 워크스페이스에 자체 고정 탭 허용
zen-key-unsafed = 단축키가 저장되지 않았습니다! 다시 입력한 후 "Escape" 키를 눌러 저장하세요.
zen-key-conflict = 다른 단축키와 겹침
pane-zen-theme-title = 테마 설정
zen-vertical-tabs-title = 사이드바 및 탭 레이아웃
zen-vertical-tabs-header = 수직 탭
zen-vertical-tabs-description = 수직 레이아웃에서 탭을 관리하세요
zen-vertical-tabs-show-expand-button = 
    .label = 확장 버튼 보이기
zen-vertical-tabs-newtab-on-tab-list = 
    .label = Show New Tab Button on Tab List
zen-vertical-tabs-newtab-top-button-border = 
    .label = Show separation border for when the new tab button is at the bottom
zen-vertical-tabs-newtab-top-button-up = 
    .label = Move the new tab button to the top
zen-vertical-tabs-expand-tabs-by-default = 기본 탭이 확장됨
zen-vertical-tabs-dont-expand-tabs-by-default = 기본 탭이 확장되지 않음
zen-vertical-tabs-expand-tabs-on-hover = 커서를 올려 탭 확장 (컴팩트 모드에서는 작동하지 않음)
zen-vertical-tabs-expand-tabs-header = 탭 확장 방식
zen-vertical-tabs-expand-tabs-description = 사이드바 탭이 어떻게 확장될지 선택하세요
zen-theme-marketplace-header = Zen 모드
zen-theme-disable-all-enabled = 
    .title = 모든 테마 비활성화
zen-theme-disable-all-disabled = 
    .title = 모든 테마 활성화
zen-theme-marketplace-description = 스토어에서 테마를 찾고 설치하세요.
zen-theme-marketplace-remove-button = 
    .label = 테마 제거
zen-theme-marketplace-check-for-updates-button = 
    .label = 업데이트 확인
zen-theme-marketplace-updates-success = 테마 업데이트 성공
zen-theme-marketplace-updates-fail = 업데이트를 찾을 수 없습니다!
zen-theme-marketplace-toggle-enabled-button = 
    .title = 테마 비활성화
zen-theme-marketplace-toggle-disabled-button = 
    .title = 테마 활성화
zen-theme-marketplace-remove-confirmation = 정말 이 모드를 제거하시겠습니까?
zen-theme-marketplace-close-modal = 닫기
zen-theme-marketplace-theme-header-title = 
    .title = CSS 선택자: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = 없음
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = 입력...
pane-zen-marketplace-title = Zen 모드
zen-settings-workspaces-display-as-icon-strip = 
    .label = 워크스페이스를 아이콘으로 표시
zen-settings-workspaces-force-container-tabs-to-workspace = 
    .label = Switch to workspace where container is set as default when opening container tabs
zen-settings-workspaces-hide-deactivated-workspaces = 
    .label = Hide deactivated workspaces
zen-theme-marketplace-link = Visit Store
zen-dark-theme-styles-header = 어두운 테마 스타일
zen-dark-theme-styles-description = 어두운 테마를 취향대로 커스터마이징하세요
zen-dark-theme-styles-amoled = 밤 테마
zen-dark-theme-styles-default = 기본 어두운 테마
zen-dark-theme-styles-colorful = 화려한 어두운 테마
zen-split-view-title = 스플릿 뷰
zen-split-view-header = 스플릿 뷰 기능
zen-split-view-description = 브라우저를 여러 뷰로 쪼개 여러 웹사이트를 한번에 볼 수 있습니다
zen-split-view-change-on-hover = 
    .label = 커서를 올려 탭 바꾸기
zen-compact-mode-styles-left = 탭 바 숨기기
zen-compact-mode-styles-top = 상단 바 숨기기
zen-compact-mode-styles-both = 둘 다 숨기기
zen-urlbar-title = Zen URL Bar
zen-urlbar-header = General settings for the URL bar
zen-urlbar-description = Customize the URL bar to your liking
zen-urlbar-behavior-label = Behavior
zen-urlbar-behavior-normal = 
    .label = Normal
zen-urlbar-behavior-floating-on-type = 
    .label = Floating only when typing
zen-urlbar-behavior-float = 
    .label = Always floating
pane-zen-CKS-title = 키보드 단축키
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } 키보드 단축키
zen-settings-CKS-header = 단축키를 커스터마이징하세요
zen-settings-CKS-description = 기본 키보드 단축키를 입맛대로 바꾸고 브라우징 경험을 개선하세요
zen-settings-CKS-disable-firefox = 
    .label = { -brand-short-name }의 기본 키보드 단축키 비활성화
zen-settings-CKS-duplicate-shortcut = 
    .label = 단축키 복제
zen-settings-CKS-reset-shortcuts = 
    .label = 기본값으로 재설정
zenCKSOption-group-other = 기타
zenCKSOption-group-windowAndTabManagement = 창 & 탭 관리
zenCKSOption-group-navigation = 이동
zenCKSOption-group-searchAndFind = 검색 & 찾기
zenCKSOption-group-pageOperations = 페이지 작동
zenCKSOption-group-historyAndBookmarks = 방문기록 & 북마크
zenCKSOption-group-mediaAndDisplay = 미디어 & 화면
zenCKSOption-group-zen-compact-mode = 간소화 모드
zenCKSOption-group-zen-workspace = 워크스페이스
zenCKSOption-group-zen-other = 다른 Zen 기능들
zenCKSOption-group-zen-split-view = 나눠서 보기
zenCKSOption-group-devTools = Developer Tools
zen-key-quick-restart = 빠른 재시작
zen-window-new-shortcut = 새 창
zen-tab-new-shortcut = 새 탭
zen-key-redo = 취소 번복
zen-restore-last-closed-tab-shortcut = 마지막으로 닫힌 탭 복구
zen-location-open-shortcut = 위치 열기
zen-location-open-shortcut-alt = 위치 열기 (Alt)
zen-key-undo-close-window = 창 닫기 취소
zen-text-action-undo-shortcut = 되돌리기
zen-text-action-redo-shortcut = 되돌리기 취소
zen-text-action-cut-shortcut = 자르기
zen-text-action-copy-shortcut = 복사
zen-text-action-copy-url-shortcut = Copy current URL
zen-text-action-paste-shortcut = 붙여넣기
zen-text-action-select-all-shortcut = 모두 선택
zen-text-action-delete-shortcut = 삭제
zen-history-show-all-shortcut-mac = 모든 기록 보기 (Mac)
zen-full-screen-shortcut = 전체화면 토글
zen-reader-mode-toggle-shortcut-windows = 읽기 모드 토글 (Windows)
zen-picture-in-picture-toggle-shortcut-alt = Picture-in-Picture 토글 (Alt)
zen-picture-in-picture-toggle-shortcut-mac = Picture-in-Picture 토글 (Mac)
zen-picture-in-picture-toggle-shortcut-mac-alt = Picture-in-Picture 토글 (Mac Alt)
zen-page-source-shortcut-safari = 페이지 소스 보기 (Safari)
zen-nav-stop-shortcut = 로딩 멈추기
zen-history-sidebar-shortcut = 방문 기록 사이드바 열기
zen-window-minimize-shortcut = 창 최소화
zen-help-shortcut = 도움말 열기
zen-preferences-shortcut = 설정 열기
zen-hide-app-shortcut = 애플리케이션 숨기기
zen-hide-other-apps-shortcut = 다른 애플리케이션 숨기기
zen-search-focus-shortcut = 검색 열기
zen-search-focus-shortcut-alt = 검색 열기 (Alt)
zen-downloads-shortcut = 다운로드 열기
zen-addons-shortcut = 애드온 열기
zen-file-open-shortcut = 파일 열기
zen-save-page-shortcut = 페이지 저장
zen-print-shortcut = 페이지 출력
zen-close-shortcut-2 = 탭 닫기
zen-mute-toggle-shortcut = 음소거 토글
zen-key-delete = 삭제 키
zen-key-go-back = 뒤로 가기
zen-key-go-forward = 앞으로 가기
zen-nav-back-shortcut-alt = 뒤로 이동 (Alt)
zen-nav-fwd-shortcut-alt = 앞으로 이동 (Alt)
zen-history-show-all-shortcut = 모든 기록 보기
zen-key-enter-full-screen = 전체화면 활성화
zen-key-exit-full-screen = 전체화면 비활성화
zen-reader-mode-toggle-shortcut-other = 읽기 모드 토글
zen-picture-in-picture-toggle-shortcut = Picture-in-Picture 토글
zen-nav-reload-shortcut-2 = 페이지 새로고침
zen-key-about-processes = 프로세스 관련
zen-page-source-shortcut = 페이지 소스 보기
zen-page-info-shortcut = 페이지 정보 보기
zen-find-shortcut = 페이지에서 검색
zen-search-find-again-shortcut = 재검색
zen-search-find-again-shortcut-prev = 뒤로 검색
zen-search-find-again-shortcut-2 = 재검색 (Alt)
zen-bookmark-this-page-shortcut = 이 페이지 북마크
zen-bookmark-show-library-shortcut = 북마크 라이브러리 보기
zen-key-stop = 로딩 멈추기
zen-full-zoom-reduce-shortcut = 축소
zen-full-zoom-enlarge-shortcut = 확대
zen-full-zoom-reset-shortcut = 확대 초기화
zen-bidi-switch-direction-shortcut = 글 방향 전환
zen-private-browsing-shortcut = 프라이빗 브라우징
zen-screenshot-shortcut = 스크린샷 찍기
zen-key-sanitize = 브라우징 데이터 삭제
zen-quit-app-shortcut = 애플리케이션 종료
zen-key-wr-capture-cmd = WR 캡쳐 명령
zen-key-wr-toggle-capture-sequence-cmd = WR 캡쳐 시퀀스 토글
zen-nav-reload-shortcut = 페이지 새로고침
zen-nav-reload-shortcut-skip-cache = 페이지 새로고침 (캐시 무시)
zen-close-shortcut = 창 닫기
zen-close-tab-shortcut = 탭 닫기
zen-compact-mode-shortcut-show-sidebar = 떠 있는 사이드바 토글
zen-compact-mode-shortcut-show-toolbar = 떠 있는 툴바 토글
zen-compact-mode-shortcut-toggle = 컴팩트 모드 토글
zen-workspace-shortcut-switch-1 = 워크스페이스 1로 전환
zen-workspace-shortcut-switch-2 = 워크스페이스 2로 전환
zen-workspace-shortcut-switch-3 = 워크스페이스 3으로 전환
zen-workspace-shortcut-switch-4 = 워크스페이스 4로 전환
zen-workspace-shortcut-switch-5 = 워크스페이스 5로 전환
zen-workspace-shortcut-switch-6 = 워크스페이스 6으로 전환
zen-workspace-shortcut-switch-7 = 워크스페이스 7로 전환
zen-workspace-shortcut-switch-8 = 워크스페이스 8로 전환
zen-workspace-shortcut-switch-9 = 워크스페이스 9로 전환
zen-workspace-shortcut-switch-10 = 워크스페이스 10으로 전환
zen-workspace-shortcut-forward = 다음 워크스페이스로
zen-workspace-shortcut-backward = 이전 워크스페이스로
zen-web-panel-shortcut-toggle = 웹 패널 토글
zen-sidebar-shortcut-toggle = 사이드바 넓이 토글
zen-pinned-tab-shortcut-reset = 고정된 탭 URL 초기화
zen-split-view-shortcut-grid = 그리드 스플릿 뷰 토글
zen-split-view-shortcut-vertical = 수직 스플릿 뷰 토글
zen-split-view-shortcut-horizontal = 수평 스플릿 뷰 토글
zen-split-view-shortcut-unsplit = 스플릿 뷰 닫기
zen-key-select-tab-1 = 탭 #1 선택
zen-key-select-tab-2 = 탭 #2 선택
zen-key-select-tab-3 = 탭 #3 선택
zen-key-select-tab-4 = 탭 #4 선택
zen-key-select-tab-5 = 탭 #5 선택
zen-key-select-tab-6 = 탭 #6 선택
zen-key-select-tab-7 = 탭 #7 선택
zen-key-select-tab-8 = 탭 #8 선택
zen-key-select-tab-last = 마지막 탭 선택
zen-key-show-all-tabs = 모든 탭 보기
zen-key-goto-history = 방문 기록 열기
zen-key-go-home = 홈으로 이동
zen-bookmark-show-sidebar-shortcut = 북마크 사이드바 보기
zen-bookmark-show-toolbar-shortcut = 북마크 툴바 보기
zen-devtools-toggle-shortcut = Toggle DevTools
zen-devtools-toggle-browser-toolbox-shortcut = Toggle Browser Toolbox
zen-devtools-toggle-browser-console-shortcut = Toggle Browser Console
zen-devtools-toggle-responsive-design-mode-shortcut = Toggle Responsive Design Mode
zen-devtools-toggle-inspector-shortcut = Toggle Inspector
zen-devtools-toggle-web-console-shortcut = Toggle Web Console
zen-devtools-toggle-js-debugger-shortcut = Toggle JavaScript Debugger
zen-devtools-toggle-net-monitor-shortcut = Toggle Network Monitor
zen-devtools-toggle-style-editor-shortcut = Toggle Style Editor
zen-devtools-toggle-performance-shortcut = Toggle Performance
zen-devtools-toggle-storage-shortcut = Toggle Storage
zen-devtools-toggle-dom-shortcut = Toggle DOM
zen-devtools-toggle-accessibility-shortcut = Toggle Accessibility
