pane-zen-looks-title = 모양
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = 기본 언어를 변경하면 웹사이트에서 사용자를 추적하기 더 쉬워질 수 있습니다.
zen-look-and-feel-colors-header = 테마 색상
zen-look-and-feel-colors-description = { -brand-short-name } 를 내 취향에 맞게 마음껏 꾸며주세요.
zen-look-and-feel-themed-toolbar = 
    .label = 툴바를 테마 컬러로 물들이기
pane-zen-side-panels-title = 사이드 웹 패널
zen-side-panels-header = General settings for web panels
zen-side-panels-description = Increase productivity by having multiple views at once!
zen-side-panels-enabled = 
    .label = Enable Web Side Panels
zen-side-panels-close-on-blur = 
    .label = Close the panel when it loses focus if it's not pinned
zen-look-and-feel-compact-view-header = Show in compact view
zen-look-and-feel-compact-view-description = Only show the toolbars you use!
zen-look-and-feel-compact-view-enabled = 
    .label = Enable { -brand-short-name }'s compact mode
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Hide the top toolbar as well in compact mode
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = 컴팩트 모드에서 새 탭을 전환하거나 열 때 도구 모음을 간략하게 팝업으로 표시합니다.
zen-look-and-feel-buttons-header = 버튼 스타일
zen-look-and-feel-buttons-description = Choose the style of buttons you want to see
zen-look-and-feel-pilled-buttons = 
    .label = Pilled Buttons
pane-zen-workspaces-title = 워크스페이스
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = 워크스페이스
pane-zen-workspaces-header = 워크스페이스
zen-settings-workspaces-header = General settings for workspaces
zen-settings-workspaces-description = With workspaces, you can have multiple browsing sessions at once!
zen-settings-workspaces-enabled = 
    .label = Enable Workspaces (Experimental)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = 탭 표시줄에서 기본 컨테이너 표시기를 숨깁니다.
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = 워크스페이스에 자체 고정 탭 허용
pane-zen-theme-title = Theme Settings
zen-vertical-tabs-title = Sidebar and tabs layout
zen-vertical-tabs-header = Vertical Tabs
zen-vertical-tabs-description = Manage your tabs in a vertical layout
zen-vertical-tabs-show-expand-button = 
    .label = Show Expand Button
zen-vertical-tabs-expand-tabs-by-default = Expand Tabs by Default
zen-vertical-tabs-dont-expand-tabs-by-default = Don't Expand Tabs by Default
zen-vertical-tabs-expand-tabs-on-hover = Expand Tabs on Hover (Wont work on compact mode)
zen-vertical-tabs-expand-tabs-header = How to expand tabs
zen-vertical-tabs-expand-tabs-description = Choose how to expand tabs in the sidebar
zen-theme-marketplace-header = 테마 스토어
zen-theme-marketplace-description = Find and install themes from the store.
zen-theme-marketplace-remove-button = 
    .label = Remove Theme
zen-theme-marketplace-check-for-updates-button = 
    .label = Check for Updates
zen-theme-marketplace-updates-success = 테마 업데이트 성공
zen-theme-marketplace-updates-fail = 업데이트를 찾을 수 없습니다!
pane-zen-marketplace-title = 테마 스토어
zen-look-and-feel-legacy-toolbar = 
    .label = 레거시 도구 모음 위치를 사용합니다. 재시작이 필요합니다!
zen-theme-marketplace-link = Visit Store
zen-dark-theme-styles-header = Dark Theme Styles
zen-dark-theme-styles-description = Customize the dark theme to your liking
zen-dark-theme-styles-amoled = Night Theme
zen-dark-theme-styles-default = 기본 어두운 테마
zen-dark-theme-styles-colorful = Colorful Dark Theme
pane-zen-CKS-title = Keyboard Shortcuts
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } Keyboard Shortcuts
zen-settings-CKS-header = Customize your keyboard shortcuts
zen-settings-CKS-description = Change the default keyboard shortcuts to your liking and improve your browsing experience
zen-settings-CKS-disable-firefox = 
    .label = Disable { -brand-short-name }'s default keyboard shortcuts
zen-cks-group-tab-action = Tab Actions
zen-cks-group-page-action = Page Actions
zen-cks-group-visible-action = Visible Actions
zen-cks-group-history-action = History Actions
zen-cks-group-search-action = Search Actions
zen-cks-group-tools-action = Tools Actions
zen-cks-group-bookmark-action = Bookmark Actions
zen-cks-group-open-page-action = Open Page Actions
zen-cks-group-downloads-action = 다운로드 액션
zen-cks-group-sidebar-action = Sidebar Actions
zen-cks-group-compact-mode-action = Compact Mode Actions
zen-cks-group-split-view-action = Split View Actions
zen-cks-group-workspace-action = Workspace Actions
open-new-tab = 새 탭
close-tab = 탭 닫기
open-new-window = 새 창
open-new-private-window = 새 비공개 창
close-window = 창 닫기
restore-last-tab = 닫은 탭 다시 열기
restore-last-window = Restore Last Window
show-next-tab = Show Next Tab
show-previous-tab = Show Previous Tab
show-all-tabs-panel = Show All Tabs Panel
send-with-mail = Send Page with Mail
save-page = Save Page
print-page = Print Page
mute-current-tab = Mute Current Tab
show-source-of-page = Show Source of Page
show-page-info = Show Page Info
zoom-in = 텍스트 확대
zoom-out = 텍스트 축소
reset-zoom = 초기화
back = 뒤로
forward = 앞으로
stop = 중지
reload = 새로 고침
force-reload = Force Reload
search-in-this-page = Search in This Page
show-next-search-result = Show Next Search Result
show-previous-search-result = Show Previous Search Result
search-the-web = Search the Web
open-migration-wizard = Open Migration Wizard
quit-from-application = Quit Application
enter-into-customize-mode = Enter Customize Mode
enter-into-offline-mode = Enter Offline Mode
open-screen-capture = Open Screen Capture
bookmark-this-page = Bookmark This Page
open-bookmark-add-tool = Open Bookmark Add Tool
open-bookmarks-manager = Open Bookmarks Manager
toggle-bookmark-toolbar = Toggle Bookmark Toolbar
open-general-preferences = Open General Preferences
open-privacy-preferences = Open Privacy Preferences
open-workspaces-preferences = Open Workspaces Preferences
open-containers-preferences = Open Containers Preferences
open-search-preferences = Open Search Preferences
open-sync-preferences = Open Sync Preferences
open-task-manager = Open Task Manager
open-addons-manager = Open Add-ons Manager
open-home-page = Open Home Page
forget-history = Forget History
quick-forget-history = Quick Forget History
clear-recent-history = Clear Recent History
restore-last-session = Restore Last Session
search-history = Search History
manage-history = Manage History
open-downloads = 다운로드 열기
show-bookmark-sidebar = Show Bookmark Sidebar
show-history-sidebar = Show History Sidebar
show-synced-tabs-sidebar = Show Synced Tabs Sidebar
reverse-sidebar = Reverse Sidebar Position
hide-sidebar = Hide Sidebar
toggle-sidebar = Toggle Sidebar
zen-toggle-web-panels = Toggle Web Panels
zen-toggle-compact-mode = Toggle Compact Mode
zen-toggle-compact-mode-sidebar = Toggle Compact Mode Sidebar
zen-toggle-compact-mode-toolbar = Toggle Compact Mode Toolbar
zen-change-workspace = Cycle Workspaces
zen-split-view-grid = Split View Grid
zen-split-view-vertical = Split View Vertical
zen-split-view-horizontal = Split View Horizontal
zen-split-view-close = Close Split View
zen-expand-sidebar = 사이드바 펼치기 토글
