zen-panel-ui-current-profile-text = aktuell profil
unified-extensions-description = Tillägg används för att få fler extra funktioner i { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = Återställ Fäst flik
    .accesskey = R
tab-context-zen-pin-tab-global = 
    .label = Add tab to essentials
    .accesskey = P
tab-context-zen-replace-pinned-url-with-current = 
    .label = Ersätt Pinned URL med Current
    .accesskey = C
tab-zen-unload = 
    .label = Unload Tab
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Åtgärder för Flikar Lösare
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Förhindra flikavlastning
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Tillåt flikavlastning
    .accesskey = Jag
zen-themes-corrupted = Din { -brand-short-name } modds-fil är skadad. De har återställts till standardtemat.
zen-panel-ui-gradient-generator-opacity-text = Contrast
zen-panel-ui-gradient-generator-texture-text = Textur
zen-panel-ui-gradient-generator-custom-color = Anpassad färg
zen-panel-ui-gradient-generator-saved-message = Lyckades spara gradienten!
