zen-panel-ui-workspaces-text = Arbetsytor
zen-panel-ui-workspaces-create-text = Skapa arbetsyta
zen-panel-ui-workspaces-create-save = 
    .label = Skapa arbetsyta
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = Avbryt
    .accesskey = C
zen-panel-ui-workspaces-edit-text = Redigera arbetsyta
zen-panel-ui-workspaces-edit-save = 
    .label = Spara ändringar
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Avbryt
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Ta bort arbetsyta
    .accesskey = D
zen-workspaces-panel-change-name = 
    .label = Change Name
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Ställ in standardbehållare
    .accesskey = O
zen-workspaces-change-gradient = 
    .label = Ändra temafärger
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Workspaces
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Complementary
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Split
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Analogous
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Triadic
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Floating
zen-panel-ui-gradient-click-to-add = Click to add a color
