zen-web-side-panel-context-mute-panel = 
    .label = Tystna Webbpanel
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = Avaktivera Tystnad för Webbpanel
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = Avaktivera Mobil
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Aktivera Mobilanvändaragent
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = Avlasta Webbpanel
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = Radera Webbpanel
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = Öppna i Ny Flik
    .accesskey = N
zen-web-side-panel-context-open-in-container-tab = 
    .label = Open in Container Tab
    .accesskey = C
zen-web-side-panel-context-add-to-panel = 
    .label = Lägg till i Webbpaneler
    .accesskey = A
zen-sidebar-introduction-title = Välkommen till Zen Sidofält
zen-sidebar-introduction-description = Zen Sidofält är ett nytt sätt att surfa på nätet. Klicka på någon av ikonerna för att öppna en webbpanel.
