zen-panel-ui-current-profile-text = nuvarande profil
unified-extensions-description = Tillägg används för att lägga till extra funktionalitet i { -brand-short-name }.
tab-zen-unload = 
    .label = Avlasta Flik
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Åtgärder för avlastning av flikar
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Förhindra avlastning av flik
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Ignorera avlastning av flik
    .accesskey = I
