zen-toolbar-context-tabs-right = 
    .label = Flikar till höger
    .accesskey = R
zen-toolbar-context-compact-mode = 
    .label = Kompakt läge
    .accesskey = C
zen-toolbar-context-compact-mode-enable = 
    .label = Aktivera kompakt läge
    .accesskey = D
zen-toolbar-context-compact-mode-just-tabs = 
    .label = Hide sidebar
zen-toolbar-context-compact-mode-just-toolbar = 
    .label = Dölj verktygsfältet
zen-toolbar-context-compact-mode-hide-both = 
    .label = Dölj båda
    .accesskey = H
sidebar-zen-sidepanel = 
    .label = Sidopaneler
sidebar-zen-expand = 
    .label = Expand Sidebar
