zen-web-side-panel-context-mute-panel = 
    .label = Stäng av ljud på webbpanelen
    .accesskey = S
zen-web-side-panel-context-unmute-panel = 
    .label = Slå på ljud på webbpanelen
    .accesskey = L
zen-web-side-panel-context-disable-ua = 
    .label = Inaktivera mobil UserAgent
    .accesskey = I
zen-web-side-panel-context-enable-ua = 
    .label = Aktivera mobil UserAgent
    .accesskey = A
zen-web-side-panel-context-unload = 
    .label = Avlasta webbpanel
    .accesskey = A
zen-web-side-panel-context-delete = 
    .label = Ta bort webbpanel
    .accesskey = T
zen-web-side-panel-open-in-new-tab = 
    .label = Öppna i ny flik
    .accesskey = Ö
zen-web-side-panel-context-add-to-panel = 
    .label = Lägg till i webbpaneler
    .accesskey = L
zen-sidebar-introduction-title = Välkommen till Zen Sidopanel
zen-sidebar-introduction-description = Zen Sidopanel är ett nytt sätt att surfa på webben. Klicka på någon av ikonerna för att öppna en webbpanel.
