zen-panel-ui-current-profile-text = nuvarande profil
unified-extensions-description = Tillägg används för att lägga till extra funktionalitet i { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = Reset Pinned Tab
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Replace Pinned URL with Current
    .accesskey = C
tab-zen-unload = 
    .label = Avlasta Flik
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Åtgärder för avlastning av flikar
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Förhindra avlastning av flik
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Allow Tab Unload
    .accesskey = I
zen-themes-corrupted = Your { -brand-short-name } mods file is corrupted. They have been reset to the default theme.
zen-panel-ui-gradient-generator-opacity-text = Contrast
zen-panel-ui-gradient-generator-texture-text = Texture
zen-panel-ui-gradient-generator-custom-color = Custom Color
zen-panel-ui-gradient-generator-saved-message = Successfully saved the gradient!
