zen-web-side-panel-context-mute-panel = 
    .label = Webpaneel dempen
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = Webpaneel inschakelen
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = Mobiele UserAgent uitschakelen
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Mobiele UserAgent inschakelen
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = Webpaneel uitschakelen
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = Webpaneel verwijderen
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = Openen in nieuw tabblad
    .accesskey = N
zen-web-side-panel-context-open-in-container-tab = 
    .label = Open in Container Tab
    .accesskey = C
zen-web-side-panel-context-add-to-panel = 
    .label = Toevoegen aan webpanelen
    .accesskey = A
zen-sidebar-introduction-title = Welkom bij de Zen Zijbalk
zen-sidebar-introduction-description = Zen Zijbalk is een nieuwe manier om te bladeren op het web. Klik op een van de iconen om een webpaneel te openen.
