zen-toolbar-context-tabs-right = 
    .label = Tabbladen aan de rechterkant
    .accesskey = R
zen-toolbar-context-compact-mode = 
    .label = Compacte modus
    .accesskey = C
zen-toolbar-context-compact-mode-enable = 
    .label = Schakel compacte modus in
    .accesskey = D
zen-toolbar-context-compact-mode-just-tabs = 
    .label = Hide sidebar
zen-toolbar-context-compact-mode-just-toolbar = 
    .label = Werkbalk verbergen
zen-toolbar-context-compact-mode-hide-both = 
    .label = Beide verbergen
    .accesskey = U
sidebar-zen-sidepanel = 
    .label = Zijkant Panelen
sidebar-zen-expand = 
    .label = Expand Sidebar
