zen-web-side-panel-context-mute-panel = 
    .label = Geluid webpaneel uitzetten
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = Geluid webpaneel aanzetten
    .accesskey = min
zen-web-side-panel-context-disable-ua = 
    .label = Mobiele UserAgent uitschakelen
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Mobiele UserAgent inschakelen
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = Webpaneel ontladen
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = Webpaneel verwijderen
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = Openen in nieuw tabblad
    .accesskey = N
zen-web-side-panel-context-open-in-container-tab = 
    .label = Openen in container tabblad
    .accesskey = C
zen-web-side-panel-context-add-to-panel = 
    .label = Toevoegen aan webpanelen
    .accesskey = A
zen-webpanel-introduction-title = Welcome to Zen Web Panels
zen-webpanel-introduction-description = Web Panels are a way to keep your favorite websites at your fingertips.
