zen-panel-ui-workspaces-text = Werkruimtes
zen-panel-ui-workspaces-create = 
    .label = Create Space
zen-panel-ui-workspaces-edit-text = Werkruimte bewerken
zen-panel-ui-workspaces-edit-save = 
    .label = Wijzigingen opslaan
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Annuleren
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Werkruimte verwijderen
    .accesskey = D
zen-workspaces-panel-change-name = 
    .label = Change Name
zen-workspaces-panel-change-icon = 
    .label = Change Icon
zen-workspaces-panel-context-manage = 
    .label = Manage Workspaces
    .accesskey = M
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Standaard container instellen
    .accesskey = O
zen-workspaces-how-to-reorder = To reorder spaces, drag and drop them from the space icons at the bottom of the sidebar.
zen-workspaces-change-theme = 
    .label = Edit Theme
zen-workspaces-panel-context-open = 
    .label = Werkruimte openen
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Als standaard werkruimte instellen
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Werkruimte bewerken
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Tabblad(en) naar werkruimte verplaatsen
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Werkruimtes
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Aanvullend
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Splitsen
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Vergelijkbaar
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Driezijdig
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Zwevend
zen-panel-ui-gradient-click-to-add = Klik om een kleur toe te voegen
zen-workspace-creation-name = 
    .placeholder = Space Name
zen-workspaces-panel-context-reorder = 
    .label = Reorder Workspaces
zen-workspace-creation-profile = Profile
    .tooltiptext = Profiles are used to separate cookies and site data between spaces.
zen-workspace-creation-title = Create a new Space
zen-workspace-creation-label = Spaces are used to organize your tabs and sessions.
