zen-panel-ui-current-profile-text = huidig profiel
unified-extensions-description = Extensies worden gebruikt om extra functionaliteit toe te voegen aan { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = Reset vastgezet tabblad
    .accesskey = R
tab-context-zen-add-essential = 
    .label = Toevoegen aan Essentials
    .accesskey = E
tab-context-zen-remove-essential = 
    .label = Verwijderen van Essentials
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Vervang Vastgepende URL met Huidige
    .accesskey = C
tab-zen-unload = 
    .label = Ontlaad Tabblad
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Acties voor Tabblad ontlader
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Voorkom Ontladen van Tabblad
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Tabblad ontladen toestaan
    .accesskey = I
zen-themes-corrupted = Uw { -brand-short-name } mods bestand is beschadigd. Ze zijn gereset naar het standaardthema.
zen-panel-ui-gradient-generator-opacity-text = Contrast
zen-panel-ui-gradient-generator-texture-text = Textuur
zen-panel-ui-gradient-generator-custom-color = Aangepaste kleur
zen-panel-ui-gradient-generator-saved-message = Het verloop is succesvol opgeslagen!
zen-copy-current-url-confirmation = The URL has been copied to the clipboard.
