zen-panel-ui-workspaces-text = Andere Werkruimtes
zen-panel-ui-workspaces-create-text = Werkruimte Maken
zen-panel-ui-workspaces-create-save = 
    .label = Werkruimte Maken
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = Annuleren
    .accesskey = C
zen-panel-ui-workspaces-edit-text = Werkruimte Bewerken
zen-panel-ui-workspaces-edit-save = 
    .label = Wijzigingen Opslaan
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Annuleren
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Werkruimte Verwijderen
    .accesskey = D
zen-workspaces-panel-context-open = 
    .label = Werkruimte Openen
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Instellen als Standaard Werkruimte
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Werkruimte Bewerken
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Tab(s) Verplaatsen Naar Werkruimte
    .accesskey = C
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Stel Standaardcontainer in
    .accesskey = O
zen-workspaces-change-gradient = 
    .label = Change Theme Colors
    .accesskey = C
