zen-panel-ui-current-profile-text = huidig profiel
unified-extensions-description = Extensies worden gebruikt om extra functionaliteit toe te voegen aan { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = Reset Vastgepend Tabblad
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Vervang Vastgepende URL met Huidige
    .accesskey = C
tab-zen-unload = 
    .label = Ontlaad Tabblad
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Acties voor Tabblad ontlader
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Voorkom Ontladen van Tabblad
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Allow Tab Unload
    .accesskey = I
zen-themes-corrupted = Your { -brand-short-name } mods file is corrupted. They have been reset to the default theme.
