zen-toolbar-context-tabs-right = 
    .label = Tabbladen aan de rechterkant
    .accesskey = R
zen-toolbar-context-compact-mode = 
    .label = Compacte modus
    .accesskey = C
zen-toolbar-context-compact-mode-enable = 
    .label = Compacte modus inschakelen
    .accesskey = D
zen-toolbar-context-compact-mode-just-tabs = 
    .label = Zijbalk verbergen
zen-toolbar-context-compact-mode-just-toolbar = 
    .label = Werkbalk verbergen
zen-toolbar-context-compact-mode-hide-both = 
    .label = Beide verbergen
    .accesskey = H
sidebar-zen-sidepanel = 
    .label = Zijpanelen
sidebar-zen-expand = 
    .label = Zijbalk uitvouwen
