zen-panel-ui-workspaces-text = Werkruimtes
zen-panel-ui-workspaces-create-text = Maak werkruimte aan
zen-panel-ui-workspaces-create-save = 
    .label = Maak werkruimte aan
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = annuleren
    .accesskey = C
zen-panel-ui-workspaces-edit-text = Werkruimte bewerken
zen-panel-ui-workspaces-edit-save = 
    .label = Wijzigingen opslaan
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = annuleren
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Werkruimte verwijderen
    .accesskey = D
zen-workspaces-panel-context-open = 
    .label = Open werkruimte
    .accesskey = OO
zen-workspaces-panel-context-set-default = 
    .label = Als standaard werkruimte instellen
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Werkruimte bewerken
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Tabblad(en) naar werkruimte verplaatsen
    .accesskey = C
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Stel standaard container in
    .accesskey = OO
zen-workspaces-change-gradient = 
    .label = Themakleuren wijzigen
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Werkruimtes
    .accesskey = W
