zen-web-side-panel-context-mute-panel = 
    .label = Mutificar el panell web
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = Desmutificar Web Panel 
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = Desactivar l'agent d'usuari mòbil
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Activar l'agent d'usuari mòbil
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = Descarregar el panell web
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = Esborrar el panell web
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = Obrir a una pestanya nova
    .accesskey = N
zen-web-side-panel-context-open-in-container-tab = 
    .label = Obrir a una pestanya de contenidor
    .accesskey = C
zen-web-side-panel-context-add-to-panel = 
    .label = Afegir a panells web
    .accesskey = A
zen-webpanel-introduction-title = Benvingut a Zen Web Panels
zen-webpanel-introduction-description = Els panells web són una manera de mantenir els teus llocs web preferits a l'abast.
