zen-panel-ui-workspaces-text = Espais de treball
zen-panel-ui-workspaces-create-text = Crea un espai de treball
zen-panel-ui-workspaces-create-save = 
    .label = Crea un espai de treball
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = Cancel·la
    .accesskey = C
zen-panel-ui-workspaces-edit-text = Edita l'espai de treball
zen-panel-ui-workspaces-edit-save = 
    .label = Desa els canvis
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Cancel·la
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Suprimeix l'espai de treball
    .accesskey = D
zen-workspaces-panel-change-name = 
    .label = Canvia el nom
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Estableix el contenidor per defecte
    .accesskey = O
zen-workspaces-change-gradient = 
    .label = Canvia els colors del tema
    .accesskey = C
zen-workspaces-panel-context-open = 
    .label = Open Workspace
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Set As Default Workspace
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Edit Workspace
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Change Tab(s) To Workspace
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Espais de treball
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Complementari
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Divideix
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Anàleg
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Triàdic
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Flotant
zen-panel-ui-gradient-click-to-add = Feu clic per afegir un color
