zen-panel-ui-workspaces-text = Altres espais de treball
zen-panel-ui-workspaces-create-text = Nou espai de treball
zen-panel-ui-workspaces-create-save = 
    .label = Desa l'espai de treball
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = Cancel·lar
    .accesskey = C
zen-panel-ui-workspaces-edit-text = Edita l'espai de treball
zen-panel-ui-workspaces-edit-save = 
    .label = Desa els canvis
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Cancel·lar
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Esborra l'espai de treball
    .accesskey = D
zen-workspaces-panel-context-open = 
    .label = Obrir l'espai de treball
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Posar com a espai de treball per defecte
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Edita l'espai de treball
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Cambiar les pestanyes a l'espai de treball
    .accesskey = C
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Indicar l'espai de treball per defecte
    .accesskey = O
zen-workspaces-change-gradient = 
    .label = Cambiar els colors del l'Aparença
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Espais de treball
    .accesskey = W
