zen-panel-ui-current-window-text = Current Window
zen-panel-ui-workspaces-text = Other Workspaces
zen-panel-ui-workspaces-create-text = Create Workspace
zen-panel-ui-workspaces-create-save = 
    .label = Create Workspace
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = Cancel·la
    .accesskey = C
zen-panel-ui-workspaces-edit-text = Edita l'espai de treball
zen-panel-ui-workspaces-edit-save = 
    .label = Desa els canvis
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Cancel
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Delete Workspace
    .accesskey = D
zen-workspaces-panel-context-open = 
    .label = Open Workspace
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Set As Default Workspace
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Edit Workspace
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Change Tab(s) To Workspace
    .accesskey = C
