zen-web-side-panel-context-mute-panel = 
    .label = Mute Web Panel
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = Unmute Web Panel
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = Disable Mobile UserAgent
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Enable Mobile UserAgent
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = Unload Web Panel
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = Delete Web Panel
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = Obri en una pestanya nova
    .accesskey = N
zen-web-side-panel-context-open-in-container-tab = 
    .label = Open in Container Tab
    .accesskey = C
zen-web-side-panel-context-add-to-panel = 
    .label = Add to Web Panels
    .accesskey = A
zen-sidebar-introduction-title = Us donem la benvinguda a la Barra lateral de Zen
zen-sidebar-introduction-description = La Barra lateral de Zen és una nova manera de navegar per internet. Feu clic en qualsevol de les icones per a obrir un panell.
