zen-panel-ui-current-profile-text = perfil actual
unified-extensions-description = Les extensions aporten funcionalitats addicionals a { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = Tornar la Finestra Fixada
    .accesskey = R
tab-context-zen-add-essential = 
    .label = Incloure a Essencials
    .accesskey = E
tab-context-zen-remove-essential = 
    .label = Esborrar dels Essencials
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Intercanviar el Marcador amb l'URL actual
    .accesskey = C
tab-zen-unload = 
    .label = Alliberar Finestra
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Accions d'Alliberar Finestres
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Alliberament de la Finestra
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Permetre l'Alliberament de Finestres
    .accesskey = I
zen-themes-corrupted = La modificació { -brand-short-name } és corrupta. S'ha canviat a l'aparença per defecte.
zen-shortcuts-corrupted =  L'arxiu { -brand-short-name } d'accessos ràpids és corrupte. S'han refet als per defecte.
zen-panel-ui-gradient-generator-opacity-text = Contrast
zen-panel-ui-gradient-generator-texture-text = Aparença
zen-panel-ui-gradient-generator-custom-color = Color Personalitzat
zen-panel-ui-gradient-generator-saved-message = S'ha desat correctament el gradient!
zen-copy-current-url-confirmation = L'URL s'ha copiat amb èxit al Porta-retalls.
zen-rice-share-name = 
    .placeholder = Nombre de l'Estilització
zen-rice-share-author = Fet per
zen-rice-share-author-input = 
    .placeholder = El teu nom
zen-rice-share-cancel = Tornar
zen-rice-share-save = Compartir
zen-rice-share-include-userchrome = 
    .label = Incloure les aparences de Zen a Windows (userChrome.css)
zen-rice-share-include-usercontent = 
    .label = Incloure les aparences (userContent.css)
zen-rice-share-include-mods = 
    .label = Incloure les modificacions actives
zen-rice-share-include-mod-prefs = 
    .label = Incloure preferències de modificacions
zen-rice-share-include-preferences = 
    .label = Incloure les preferències de disposició
zen-rice-share-include-workspace-themes = 
    .label = Incloure aparences d'espais de treball
zen-rice-share-success = S'ha fet una Nova Aparença amb Èxit
zen-rice-share-success-link = Compartir Aparença amb un Enllaç
zen-rice-share-accept = Acceptar
zen-rice-share-notice = Abans de compartir, has d'entendre
# note: Do not translate the "<br/>" tags in the following string
zen-rice-share-notice-description =
    Una Aparença és un munt d'opcions que es poden compartir amb altres.<br/> 
    Això inclou les preferències de finestra, pàgines web, modificadors actius i les seves preferències, també la disposició de finestra i els colors o gradients.<br/>
    Si decideixes compartir la teva Aparença, vostè compartirà tot això amb els altres. Ha de ser conscient, tingui cuidat del qual compartiu per favor.
zen-learn-more-text = Més informació
zen-rice-share-include = Exportar Opcions
appmenu-zen-share-rice = 
    .label = Compartir Aparença
zen-close-label = Tancar
