zen-toolbar-context-tabs-right = 
    .label = Tab di sebelah kanan
    .accesskey = R
zen-toolbar-context-compact-mode = 
    .label = Mode Ringkas
    .accesskey = C
zen-toolbar-context-compact-mode-enable = 
    .label = Nyalakan mode ringkas
    .accesskey = D
zen-toolbar-context-compact-mode-just-tabs = 
    .label = Sembunyikan bilah sisi
zen-toolbar-context-compact-mode-just-toolbar = 
    .label = Sembunyikan bilah alat
zen-toolbar-context-compact-mode-hide-both = 
    .label = Sembunyikan keduanya
    .accesskey = H
sidebar-zen-sidepanel = 
    .label = Panel Samping
sidebar-zen-expand = 
    .label = Perluas Bilah Sisi
