zen-panel-ui-workspaces-text = Ruang Kerja Lainnya
zen-panel-ui-workspaces-create-text = Buat Ruang Kerja
zen-panel-ui-workspaces-create-save = 
    .label = Buat Ruang Kerja
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = Batal
    .accesskey = C
zen-panel-ui-workspaces-edit-text = Edit Ruang Kerja
zen-panel-ui-workspaces-edit-save = 
    .label = Simpan Perubahan
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Batal
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Hapus Ruang Kerja
    .accesskey = D
zen-workspaces-panel-context-open = 
    .label = Buka Ruang Kerja
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Atur Sebagai Ruang Kerja Default
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Edit Ruang Kerja
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Pindahkan Tab ke Ruang Kerja
    .accesskey = C
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Atur Kontainer Default
    .accesskey = O
zen-workspaces-change-gradient = 
    .label = Ubah Warna Tema
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Ruang Kerja
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Complementary
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Split
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Analogous
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Triadic
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Floating
zen-panel-ui-gradient-click-to-add = Klik untuk menambahkan warna
