zen-web-side-panel-context-mute-panel = 
    .label = Bisukan Panel Web
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = Nyalakan Suara Panel Web
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = Nonaktifkan UserAgent Mobile
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Aktifkan UserAgent Mobile
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = Bongkar Muat Panel Web
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = Hapus Panel Web
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = Buka di Tab Baru
    .accesskey = N
zen-web-side-panel-context-add-to-panel = 
    .label = Tambahkan ke Panel Web
    .accesskey = A
zen-sidebar-introduction-title = Selamat Datang di Zen Sidebar
zen-sidebar-introduction-description = Zen Sidebar adalah cara baru untuk menjelajahi web. Klik salah satu ikon untuk membuka panel web.
