zen-panel-ui-workspaces-text = Ruang Kerja Lainnya
zen-panel-ui-workspaces-create = 
    .label = Create Space
zen-panel-ui-workspaces-edit-text = Edit Ruang Kerja
zen-panel-ui-workspaces-edit-save = 
    .label = Simpan Perubahan
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Batal
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Hapus Ruang Kerja
    .accesskey = D
zen-workspaces-panel-change-name = 
    .label = Ubah Nama
zen-workspaces-panel-change-icon = 
    .label = Change Icon
zen-workspaces-panel-context-manage = 
    .label = Manage Workspaces
    .accesskey = M
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Atur Kontainer Default
    .accesskey = O
zen-workspaces-change-theme = 
    .label = Edit Theme
zen-workspaces-panel-context-open = 
    .label = Buka Ruang Kerja
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Atur Sebagai Ruang Kerja bawaan
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Edit Ruang Kerja
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Pindahkan Tab ke Ruang Kerja
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Ruang Kerja
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Komplementer
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Pisahkan
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Analog
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Triadik
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Melayang
zen-panel-ui-gradient-click-to-add = Klik untuk menambahkan warna
zen-workspace-creation-name = 
    .placeholder = Space Name
zen-workspace-creation-profile = Profile
    .tooltiptext = Profiles are used to separate cookies and site data between spaces.
zen-workspace-creation-title = Create a new Space
zen-workspace-creation-label = Spaces are used to organize your tabs and sessions.
