zen-panel-ui-current-profile-text = profil saat ini
unified-extensions-description = Ekstensi digunakan untuk menambahkan lebih banyak fungsi ekstra ke { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = Setel Ulang Tab yang Disematkan
    .accesskey = R
tab-context-zen-add-essential = 
    .label = Add to Essentials
    .accesskey = E
tab-context-zen-remove-essential = 
    .label = Remove from Essentials
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Ganti URL yang Disematkan dengan yang Saat Ini
    .accesskey = C
tab-zen-unload = 
    .label = Lepaskan Tab
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Tindakan Pelepasan Tab
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Cegah Pelepasan Tab
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Izinkan Pelepasan Tab
    .accesskey = I
zen-themes-corrupted = Tidak dapat memuat file mod { -brand-short-name } Anda karena rusakan. File tersebut telah diatur ulang ke tema default.
zen-panel-ui-gradient-generator-opacity-text = Contrast
zen-panel-ui-gradient-generator-texture-text = Texture
zen-panel-ui-gradient-generator-custom-color = Custom Color
zen-panel-ui-gradient-generator-saved-message = Successfully saved the gradient!
zen-copy-current-url-confirmation = The URL has been copied to the clipboard.
zen-rice-share-name = 
    .placeholder = Rice Name
zen-rice-share-author = By
zen-rice-share-author-input = 
    .placeholder = Your Name
zen-rice-share-cancel = Cancel
zen-rice-share-save = Share
zen-rice-share-include-userchrome = 
    .label = Include userChrome.css
zen-rice-share-include-usercontent = 
    .label = Include userContent.css
zen-rice-share-include-mods = 
    .label = Include enabled mods
zen-rice-share-include-mod-prefs = 
    .label = Include mod preferences
zen-rice-share-include-preferences = 
    .label = Include layout state
zen-rice-share-include-workspace-themes = 
    .label = Include workspace gradient themes
zen-rice-share-include = Export Options
