zen-panel-ui-current-profile-text = perfil atual
unified-extensions-description = As extensões são usadas para trazer mais funcionalidades adicionais para o { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = Resetar Aba Fixada
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Substituir URL Fixada com Atual
    .accesskey = C
tab-zen-unload = 
    .label = Unload Tab
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Ações Unloader Abas
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Impedir Tab Descarregar
    .accesskey = PT
tab-zen-ignore-unload = 
    .label = Permitir Tab Descarregar
    .accesskey = Eu
zen-themes-corrupted = Seu arquivo de mods { -brand-short-name } está corrompido. Eles foram redefinidos para o tema padrão.
zen-panel-ui-gradient-generator-opacity-text = Contrast
zen-panel-ui-gradient-generator-texture-text = Textura
zen-panel-ui-gradient-generator-custom-color = Cor personalizada
zen-panel-ui-gradient-generator-saved-message = Gradiente salvo!
