zen-panel-ui-workspaces-text = Espaços de Trabalho
zen-panel-ui-workspaces-create = 
    .label = Criar Espaço
zen-panel-ui-workspaces-edit-text = Editar Espaço de Trabalho
zen-panel-ui-workspaces-edit-save = 
    .label = Guardar Alterações
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Cancelar
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Eliminar Espaço de Trabalho
    .accesskey = D
zen-workspaces-panel-change-name = 
    .label = Alterar Nome
zen-workspaces-panel-change-icon = 
    .label = Alterar Ícone
zen-workspaces-panel-context-manage = 
    .label = Gerir Espaços de Trabalho
    .accesskey = M
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Definir Contentor Padrão
    .accesskey = O
zen-workspaces-how-to-reorder = Para reordenar os espaços, arraste-os e solte-os a partir dos ícones de espaços na parte inferior da barra lateral.
zen-workspaces-change-theme = 
    .label = Editar Tema
zen-workspaces-panel-context-open = 
    .label = Abrir Espaço de Trabalho
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Definir como Espaço de Trabalho Padrão
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Editar Espaço de Trabalho
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Mudar Separador(es) para Espaço de Trabalho
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Espaços de Trabalho
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Complementar
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Dividido
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Análogo
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Triádico
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Flutuante
zen-panel-ui-gradient-click-to-add = Clique para adicionar uma cor
zen-workspace-creation-name = 
    .placeholder = Nome do Espaço
zen-workspaces-panel-context-reorder = 
    .label = Reordenar Espaços de Trabalho
zen-workspace-creation-profile = Perfil
    .tooltiptext = Os perfis são usados para separar cookies e dados de sites entre espaços.
zen-workspace-creation-header = Criar um Espaço
zen-workspace-creation-label = Os espaços são usados para organizar os seus separadores e sessões.
