zen-panel-ui-current-profile-text = perfil atual
unified-extensions-description = As extensões são usadas para trazer funcionalidades adicionais para o { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = Repor o Separador Afixado
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Substituir o URL Afixado pelo URL Atual
    .accesskey = C
tab-zen-unload = 
    .label = Hibernar Separador
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Ações de Hibernação de Separadores
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Impedir a Hibernação do Separador
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Permitir a Hibernação do Separador
    .accesskey = I
zen-themes-corrupted = O seu ficheiro de modificações do { -brand-short-name } está corrompido. Elas foram redefinidas como iguais às do tema padrão.
