zen-web-side-panel-context-mute-panel = 
    .label = Silenciar Painel Web
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = Reativar som do Painel Web
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = Desativar UserAgent Móvel
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Ativar UserAgent Móvel
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = Descarregar Painel Web
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = Eliminar Painel Web
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = Abrir num Novo Separador
    .accesskey = N
zen-web-side-panel-context-open-in-container-tab = 
    .label = Abrir num Separador Contentor
    .accesskey = C
zen-web-side-panel-context-add-to-panel = 
    .label = Adicionar a Painéis Web
    .accesskey = A
zen-sidebar-introduction-title = Bem-vindo(a) à Barra Lateral Zen
zen-sidebar-introduction-description = A Barra Lateral Zen é uma nova maneira de navegar na internet. Clique num dos ícones para abrir um painel web.
