zen-toolbar-context-tabs-right = 
    .label = Separadores à direita
    .accesskey = R
zen-toolbar-context-compact-mode = 
    .label = Modo compacto
    .accesskey = C
zen-toolbar-context-compact-mode-enable = 
    .label = Ativar modo compacto
    .accesskey = D
zen-toolbar-context-compact-mode-just-tabs = 
    .label = Esconder a barra lateral
zen-toolbar-context-compact-mode-just-toolbar = 
    .label = Esconder a barra de ferramentas
zen-toolbar-context-compact-mode-hide-both = 
    .label = Esconder ambas
    .accesskey = H
sidebar-zen-sidepanel = 
    .label = Painéis Laterais
sidebar-zen-expand = 
    .label = Expandir Barra Lateral
