zen-panel-ui-workspaces-text = Espaços de Trabalho
zen-panel-ui-workspaces-create-text = Criar Espaço de Trabalho
zen-panel-ui-workspaces-create-save = 
    .label = Criar Espaço de Trabalho
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = Cancelar
    .accesskey = C
zen-panel-ui-workspaces-edit-text = Editar Espaço de Trabalho
zen-panel-ui-workspaces-edit-save = 
    .label = Guardar Alterações
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Cancelar
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Eliminar Espaço de Trabalho
    .accesskey = D
zen-workspaces-panel-change-name = 
    .label = Alterar Nome
zen-workspaces-panel-change-icon = 
    .label = Change Icon
zen-workspaces-panel-context-manage = 
    .label = Manage Workspaces
    .accesskey = M
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Definir Contentor Padrão
    .accesskey = O
zen-workspaces-change-gradient = 
    .label = Alterar Cores do Tema
    .accesskey = C
zen-workspaces-panel-context-open = 
    .label = Abrir Espaço de Trabalho
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Definir como Espaço de Trabalho Padrão
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Editar Espaço de Trabalho
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Mudar Separador(es) para Espaço de Trabalho
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Espaços de Trabalho
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Complementar
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Dividido
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Análogo
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Triádico
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Flutuante
zen-panel-ui-gradient-click-to-add = Clique para adicionar uma cor
