zen-web-side-panel-context-mute-panel = 
    .label = Silenciar Painel Web
    .accesskey = MM
zen-web-side-panel-context-unmute-panel = 
    .label = Reativar Painel Web
    .accesskey = min
zen-web-side-panel-context-disable-ua = 
    .label = Desativar UserAgent Móvel
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Habilitar UserAgent móvel
    .accesskey = MM
zen-web-side-panel-context-unload = 
    .label = Descarregar o Painel Web
    .accesskey = PO
zen-web-side-panel-context-delete = 
    .label = Excluir Painel Web
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = Abrir em nova aba
    .accesskey = N
zen-web-side-panel-context-open-in-container-tab = 
    .label = Abrir na aba de Contêiner
    .accesskey = C
zen-web-side-panel-context-add-to-panel = 
    .label = Adicionar aos painéis web
    .accesskey = Um
zen-sidebar-introduction-title = Bem-vindo ao Zen Sidebar
zen-sidebar-introduction-description = A barra lateral de Zen é uma nova maneira de navegar pela web. Clique em qualquer um dos ícones para abrir um painel web.
