zen-panel-ui-current-profile-text = perfil atual
unified-extensions-description = As extensões são usadas para trazer funcionalidades adicionais para o { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = Repor o Separador Fixado
    .accesskey = R
tab-context-zen-add-essential = 
    .label = Adicionar aos Essenciais
    .accesskey = E
tab-context-zen-remove-essential = 
    .label = Remover dos Essenciais
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Substituir o URL Fixado pelo URL Atual
    .accesskey = C
tab-zen-unload = 
    .label = Hibernar Separador
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Ações de Hibernação de Separadores
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Impedir a Hibernação do Separador
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Permitir a Hibernação do Separador
    .accesskey = I
zen-themes-corrupted = O seu ficheiro de modificações do { -brand-short-name } está corrompido. Elas foram redefinidas como iguais às do tema padrão.
zen-panel-ui-gradient-generator-opacity-text = Contraste
zen-panel-ui-gradient-generator-texture-text = Textura
zen-panel-ui-gradient-generator-custom-color = Cor personalizada
zen-panel-ui-gradient-generator-saved-message = Gradiente guardado com sucesso!
zen-copy-current-url-confirmation = O URL foi copiado para a área de transferência.
zen-rice-share-name = 
    .placeholder = Rice Name
zen-rice-share-author = By
zen-rice-share-author-input = 
    .placeholder = Your Name
zen-rice-share-cancel = Cancel
zen-rice-share-save = Share
zen-rice-share-include-userchrome = 
    .label = Include userChrome.css
zen-rice-share-include-usercontent = 
    .label = Include userContent.css
zen-rice-share-include-mods = 
    .label = Include enabled mods
zen-rice-share-include-mod-prefs = 
    .label = Include mod preferences
zen-rice-share-include-preferences = 
    .label = Include layout state
zen-rice-share-include-workspace-themes = 
    .label = Include workspace gradient themes
zen-rice-share-include = Export Options
appmenu-zen-share-rice = 
    .label = Share Zen Rice
