zen-panel-ui-current-profile-text = 使用中のプロファイル
unified-extensions-description = 拡張機能を使うことで、より多くの機能を{ -brand-short-name } に追加することができます。
tab-context-zen-reset-pinned-tab = 
    .label = ピン留めタブをリセット
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = ピン留めされたURLを現在のURLに変更
    .accesskey = C
tab-zen-unload = 
    .label = タブをアンロード
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = タブアンローダーアクション
    .accesskey = T
tab-zen-prevent-unload = 
    .label = タブのアンロードを防ぐ
    .accesskey = P
tab-zen-ignore-unload = 
    .label = タブのアンロードを許可する
    .accesskey = I
zen-themes-corrupted = { -brand-short-name } Modファイルが破損しています。既定のテーマにリセットされました。
zen-panel-ui-gradient-generator-opacity-text = コントラスト
zen-panel-ui-gradient-generator-texture-text = テクスチャ
zen-panel-ui-gradient-generator-custom-color = 色カスタム
