zen-panel-ui-workspaces-text = ワークスペース
zen-panel-ui-workspaces-create-text = ワークスペースを作成
zen-panel-ui-workspaces-create-save = 
    .label = ワークスペースを作成
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = キャンセル
    .accesskey = C
zen-panel-ui-workspaces-edit-text = ワークスペースを編集
zen-panel-ui-workspaces-edit-save = 
    .label = 変更を保存
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = キャンセル
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = ワークスペースを削除
    .accesskey = D
zen-workspaces-panel-context-open = 
    .label = ワークスペースを開く
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = 既定のワークスペースとして設定
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = ワークスペースを編集
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = タブをワークスペースに変更
    .accesskey = C
zen-workspaces-panel-context-open-in-container-tab = 
    .label = 既定のコンテナを設定
    .accesskey = O
zen-workspaces-change-gradient = 
    .label = テーマの色を変更
    .accesskey = C
