zen-web-side-panel-context-mute-panel = 
    .label = ウェブパネルをミュート
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = ウェブパネルのミュートを解除
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = モバイルユーザーエージェントを無効化
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = モバイルユーザーエージェントを有効化
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = ウェブパネルを閉じる
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = このウェブパネルを削除
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = 新しいタブで開く
    .accesskey = N
zen-web-side-panel-context-open-in-container-tab = 
    .label = コンテナタブで開く
    .accesskey = C
zen-web-side-panel-context-add-to-panel = 
    .label = ウェブパネルに追加
    .accesskey = A
zen-sidebar-introduction-title = Zen Sidebar へようこそ
zen-sidebar-introduction-description = Zen Sidebarは、ブラウジングをする新しい方法です。アイコンをクリックしてウェブパネルを開きましょう。
