zen-panel-ui-workspaces-text = ワークスペース
zen-panel-ui-workspaces-create = 
    .label = Create Space
zen-panel-ui-workspaces-edit-text = ワークスペースを編集
zen-panel-ui-workspaces-edit-save = 
    .label = 変更を保存
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = キャンセル
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = ワークスペースを削除
    .accesskey = D
zen-workspaces-panel-change-name = 
    .label = Change Name
zen-workspaces-panel-change-icon = 
    .label = Change Icon
zen-workspaces-panel-context-manage = 
    .label = Manage Workspaces
    .accesskey = M
zen-workspaces-panel-context-open-in-container-tab = 
    .label = デフォルトのコンテナを設定
    .accesskey = O
zen-workspaces-how-to-reorder = To reorder spaces, drag and drop them from the space icons at the bottom of the sidebar.
zen-workspaces-change-theme = 
    .label = Edit Theme
zen-workspaces-panel-context-open = 
    .label = ワークスペースを開く
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = デフォルトのワークスペースとして設定
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = ワークスペースを編集
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = タブをワークスペースに移動
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = ワークスペース
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Complementary
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = 分割
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Analogous
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Triadic
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Floating
zen-panel-ui-gradient-click-to-add = Click to add a color
zen-workspace-creation-name = 
    .placeholder = Space Name
zen-workspaces-panel-context-reorder = 
    .label = Reorder Workspaces
zen-workspace-creation-profile = Profile
    .tooltiptext = Profiles are used to separate cookies and site data between spaces.
zen-workspace-creation-title = Create a new Space
zen-workspace-creation-label = Spaces are used to organize your tabs and sessions.
