zen-panel-ui-current-profile-text = 使用中のプロファイル
unified-extensions-description = 拡張機能は、 { -brand-short-name } に多くの追加機能をもたらすために使用されます。
tab-context-zen-reset-pinned-tab = 
    .label = ピン留めされたタブをリセット
    .accesskey = R
tab-context-zen-pin-tab-global = 
    .label = Add tab to essentials
    .accesskey = P
tab-context-zen-replace-pinned-url-with-current = 
    .label = ピン留めされた URL を現在のものに置き換え
    .accesskey = C
tab-zen-unload = 
    .label = Unload Tab
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = タブアンローダーアクション
    .accesskey = T
tab-zen-prevent-unload = 
    .label = タブのアンロードを防止
    .accesskey = P
tab-zen-ignore-unload = 
    .label = タブのアンロードを許可
    .accesskey = I
zen-themes-corrupted = { -brand-short-name } mods ファイルが破損しています。既定のテーマにリセットされました。
zen-panel-ui-gradient-generator-opacity-text = Contrast
zen-panel-ui-gradient-generator-texture-text = テクスチャ
zen-panel-ui-gradient-generator-custom-color = カスタムカラー
zen-panel-ui-gradient-generator-saved-message = グラデーションを正常に保存しました！
