zen-toolbar-context-tabs-right = 
    .label = タブバーを右側に表示
    .accesskey = R
zen-toolbar-context-compact-mode = 
    .label = コンパクトモード
    .accesskey = C
zen-toolbar-context-compact-mode-enable = 
    .label = コンパクトモードを有効にする
    .accesskey = D
zen-toolbar-context-compact-mode-just-tabs = 
    .label = サイドバーを隠す
zen-toolbar-context-compact-mode-just-toolbar = 
    .label = ツールバーを隠す
zen-toolbar-context-compact-mode-hide-both = 
    .label = 両方隠す
    .accesskey = H
sidebar-zen-sidepanel = 
    .label = サイドパネル
sidebar-zen-expand = 
    .label = サイドバーを展開する
