zen-panel-ui-current-window-text = Current Window
zen-panel-ui-workspaces-text = Other Workspaces
zen-panel-ui-workspaces-create-text = Create Workspace
zen-panel-ui-workspaces-create-save = 
    .label = Create Workspace
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = Cancel
    .accesskey = C
zen-panel-ui-workspaces-edit-text = ワークスペースを編集
zen-panel-ui-workspaces-edit-save = 
    .label = 変更を保存
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = キャンセル
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = ワークスペースを削除
    .accesskey = D
zen-workspaces-panel-context-open = 
    .label = Open Workspace
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = デフォルトのワークスペースとして設定
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = ワークスペースを編集
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = タブをワークスペースに移動
    .accesskey = C
zen-workspaces-panel-context-open-in-container-tab = 
    .label = デフォルトのコンテナを設定
    .accesskey = O
