pane-zen-looks-title = Megjelenés és hangulat
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Az alapértelmezett nyelv átállításával a weboldalak könnyebben nyomon tudnak követni.
zen-look-and-feel-colors-header = Pick a theme colour
zen-look-and-feel-colors-description = Alakítsd kedvedre a { -brand-short-name } megjelenését és hangulatát
zen-look-and-feel-use-workspace-colors = 
    .label = Használja a munkakörnyezet színeit elsődleges színként
pane-zen-side-panels-title = Oldalsó web panelek
zen-side-panels-header = Web panelek általános beállításai
zen-side-panels-description = Növeld a produktivitásod több lappal egyszerre!
zen-side-panels-enabled = 
    .label = Oldalsó web panelek bekapcsolása
zen-side-panels-close-on-blur = 
    .label = Panel bezárása amikor nincs fókuszban, vagy nincs kitűzve
zen-vertical-tabs-show-bottom-border = 
    .label = Alsó ikonok keretének megjelenítése
zen-vertical-tabs-layout-header = Böngésző Elrendezés
zen-vertical-tabs-layout-description = Válassza ki az önnek legmegfelelőbb elrendezést
zen-layout-single-toolbar = Egyetlen eszköztár
zen-layout-multiple-toolbar = Több eszköztár
zen-layout-collapsed-toolbar = Összecsukott eszköztár
sync-currently-syncing-workspaces = Munkakörnyezetek
sync-engine-workspaces = 
    .label = Munkakörnyezetek
    .tooltiptext = Munkakörnyezetek szinkronizálása eszközök között
    .accesskey = W
zen-glance-title = Bepillantás
zen-glance-header = Általános beállítások a Bepillantásnak
zen-glance-description = Gyors áttekintést kaphat a hivatkozásairól anélkül, hogy új lapon nyitná meg őket
zen-glance-trigger-label = Kiváltó módszer
zen-glance-enabled = 
    .label = Bepillantás engedélyezése
zen-glance-trigger-ctrl-click = 
    .label = Ctrl + Kattintás
zen-glance-trigger-alt-click = 
    .label = Alt + Kattintás
zen-glance-trigger-shift-click = 
    .label = Shift + Kattintás
zen-glance-trigger-meta-click = 
    .label = Meta (Command) + Kattintás
zen-glance-trigger-mantain-click = 
    .label = Nyomva tartás (Hamarosan!)
zen-look-and-feel-compact-view-header = Kompakt nézet
zen-look-and-feel-compact-view-description = Csak azokat az eszköztárakat lásd amit használsz!
zen-look-and-feel-compact-view-enabled = 
    .label = A { -brand-short-name } kompakt módjának bekapcsolása
zen-look-and-feel-compact-view-top-toolbar = 
    .label = A felső eszköztár is legyen elrejtve kompakt módban
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Eszköztár megjelenítése rövid ideig lap váltás vagy új megnyitása során kompakt módban
zen-look-and-feel-buttons-header = Gomb stílus
zen-look-and-feel-buttons-description = Válaszd ki, hogy milyen stílusú gombokat szeretnél látni
zen-look-and-feel-pilled-buttons = 
    .label = Lekerekített gombok
pane-zen-tabs-title = Lap kezelés
category-zen-workspaces = 
    .tooltiptext = { pane-zen-tabs-title }
pane-settings-workspaces-title = Munkakörnyezetek
pane-zen-tabs-unloader-title = Lap ürítő
zen-tabs-unloader-header = Általános beállítások lap ürítőhöz
zen-tabs-unloader-description = Automatikusan üríti a nem használt lapokat, ezzel memóriát spórólva
zen-tabs-unloader-enabled = 
    .label = Lap ürítő engedélyezése
zen-tabs-unloader-unload-delay = 
    .label = Lapok ürítése ezek után
zen-tabs-unloader-unload-delay-description = Az idő percben megadva miután a lapok ürítődnek
zen-look-and-feel-compact-toolbar-themed = 
    .label = Tematikus háttér használata a kompakt eszköztárhoz
zen-look-and-feel-compact-sidebar-themed = 
    .label = Tematikus háttér használata a kompakt oldalsávhoz
pane-zen-pinned-tab-manager-title = Kitűzött lapok
zen-pinned-tab-manager-header = Általános beállítások kitűzött lapokhoz
zen-pinned-tab-manager-description = Kitűzött lapok további viselkedésének kezelése
zen-pinned-tab-manager-restore-pinned-tabs-to-pinned-url = 
    .label = Kitűzött lapok visszaállítása az eredetileg kitűzött URL-re indításkor
zen-pinned-tab-manager-container-specific-essentials-enabled = 
    .label = Konténerspecifikus alapvető fontosságú elemek engedélyezése
zen-pinned-tab-manager-close-shortcut-behavior-label = Lap bezárás gyorsbillentyű viselkedés
zen-pinned-tab-manager-reset-unload-switch-close-shortcut-option = 
    .label = URL visszaállítása, ürítés és váltás a következő lapra
zen-pinned-tab-manager-unload-switch-close-shortcut-option = 
    .label = Ürítés és váltás a következő lapra
zen-pinned-tab-manager-reset-switch-close-shortcut-option = 
    .label = URL visszaállítása és váltás a következő lapra
zen-pinned-tab-manager-switch-close-shortcut-option = 
    .label = Váltás a következő lapra
zen-pinned-tab-manager-reset-close-shortcut-option = 
    .label = URL visszaállítása
zen-pinned-tab-manager-close-close-shortcut-option = 
    .label = Lap bezárása
pane-zen-workspaces-header = Munkakörnyezetek
zen-settings-workspaces-header = Munkakörnyezetek általános beállításai
zen-settings-workspaces-description = A munkakörnyezetekkel egyszerre több böngészési munkameneted is lehet!
zen-settings-workspaces-enabled = 
    .label = Munkakörnyezetek Bekapcsolása (Kísérleti)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Alapértelmezett konténerjelző elrejtése a tabulátor sávban
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Munkakörnyezetek saját kitűzött lapjainak engedélyezése
zen-key-unsaved = Nem mentett gyorsbillentyű! Mentsd meg az "Escape" gomb lenyomásával, majd újraírásával.
zen-key-conflict = Ütközik egy másik gyorsbillentyűvel
pane-zen-theme-title = Téma beállítások
zen-vertical-tabs-title = Oldalsó sáv és lapok elrendezése
zen-vertical-tabs-header = Függőleges lapok
zen-vertical-tabs-description = Kezeld a lapjaidat függőleges elrendezésben
zen-vertical-tabs-show-expand-button = 
    .label = Nagyobbítás Gomb Mutatása
zen-vertical-tabs-newtab-on-tab-list = 
    .label = Új lap gomb megjelenítése a laplistán
zen-vertical-tabs-newtab-top-button-border = 
    .label = Elválasztó keret megjelenítése, amikor az új lap gomb alul helyezkedik el
zen-vertical-tabs-newtab-top-button-up = 
    .label = Új lap gomb áthelyezése a tetejére
zen-vertical-tabs-expand-tabs-by-default = Lapok Alapértelmezett Nagyobbítása
zen-vertical-tabs-dont-expand-tabs-by-default = A Lapok Alapértelmezetten Ne Legyenek Nagyobbítva
zen-vertical-tabs-expand-tabs-on-hover = Lapok kibontása fölémozgatással (Nem fog működni kompakt módban)
zen-vertical-tabs-expand-tabs-header = Hogyan legyenek a lapok nagyobbítva
zen-vertical-tabs-expand-tabs-description = Válassz, hogyan legyenek a lapok nagyobbítva az oldalsó sávon
zen-theme-marketplace-header = Zen Modok
zen-theme-disable-all-enabled = 
    .title = Minden téma kikapcsolása
zen-theme-disable-all-disabled = 
    .title = Minden téma bekapcsolása
zen-theme-marketplace-description = Keress és adj hozzá témákat az áruházból.
zen-theme-marketplace-remove-button = 
    .label = Téma Törlése
zen-theme-marketplace-check-for-updates-button = 
    .label = Frissítések Keresése
zen-theme-marketplace-updates-success = Téma sikeresen frissítve
zen-theme-marketplace-updates-fail = Nem található frissítés!
zen-theme-marketplace-toggle-enabled-button = 
    .title = Téma Kikapcsolása
zen-theme-marketplace-toggle-disabled-button = 
    .title = Téma Engedélyezése
zen-theme-marketplace-remove-confirmation = Biztosan el akarod távolítani ezt a modot?
zen-theme-marketplace-close-modal = Bezárás
zen-theme-marketplace-theme-header-title = 
    .title = CSS Selector: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = Nincs
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Írj valamit...
pane-zen-marketplace-title = Zen modok
zen-settings-workspaces-display-as-icon-strip = 
    .label = Munkakörnyezetek ikoncsíkként való megjelenítése
zen-settings-workspaces-force-container-tabs-to-workspace = 
    .label = Válts a munkakörnyezetre, ahol a konténer alapértelmezettnek van beállítva konténerlapok megnyitásakor
zen-settings-workspaces-hide-deactivated-workspaces = 
    .label = Kikapcsolt munkakörnyezetek elrejtése
zen-theme-marketplace-link = Áruház Megnyitása
zen-dark-theme-styles-header = Sötét téma stílusok
zen-dark-theme-styles-description = A sötét téma testreszabása tetszésed szerint
zen-dark-theme-styles-amoled = Éjszakai téma
zen-dark-theme-styles-default = Alapértelmezett sötét téma
zen-dark-theme-styles-colorful = Színes sötét téma
zen-split-view-title = Osztott nézet
zen-split-view-header = Osztott nézet funkció
zen-split-view-description = A böngésző több nézetre osztása, így egyszerre több webhelyet is böngészhet egyszerre
zen-split-view-change-on-hover = 
    .label = Lapok váltása fölémozgatással
zen-compact-mode-styles-left = Lapsáv elrejtése
zen-compact-mode-styles-top = Felső sáv elrejtése
zen-compact-mode-styles-both = Mindkettő elrejtése
zen-urlbar-title = Zen URL sáv
zen-urlbar-header = URL sáv általános beállításai
zen-urlbar-description = Az URL sáv testreszabása a saját ízlése szerint
zen-urlbar-behavior-label = Viselkedés
zen-urlbar-behavior-normal = 
    .label = Normális
zen-urlbar-behavior-floating-on-type = 
    .label = Lebegés csak gépelés közben
zen-urlbar-behavior-float = 
    .label = Lebegés mindig
pane-zen-CKS-title = Gyorsgombok
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } Gyorsgombok
zen-settings-CKS-header = Gyorsgombok személyre szabása
zen-settings-CKS-description = Állítsd be kedvedre az alapértelmezett gyorsgombokat, hogy növeld a böngészési élményedet
zen-settings-CKS-disable-firefox = 
    .label = A { -brand-short-name } alapértelmezett gyorsgombjainak kikapcsolása
zen-settings-CKS-duplicate-shortcut = 
    .label = Gyorsgomb Duplikálása
zen-settings-CKS-reset-shortcuts = 
    .label = Visszaállítás alapértelmezettre
zenCKSOption-group-other = Egyéb
zenCKSOption-group-windowAndTabManagement = Ablakok és lapok kezelése
zenCKSOption-group-navigation = Navigáció
zenCKSOption-group-searchAndFind = Keresés & Találat
zenCKSOption-group-pageOperations = Oldal Műveletek
zenCKSOption-group-historyAndBookmarks = Előzmények és könyvjelzők
zenCKSOption-group-mediaAndDisplay = Média & Megjelenítés
zenCKSOption-group-zen-compact-mode = Kompakt mód
zenCKSOption-group-zen-workspace = Munkakörnyezetek
zenCKSOption-group-zen-other = Egyéb Zen funkciók
zenCKSOption-group-zen-split-view = Osztott nézet
zenCKSOption-group-devTools = Fejlesztői eszközök
zen-key-quick-restart = Gyors újraindítás
zen-window-new-shortcut = Új ablak
zen-tab-new-shortcut = Új lap
zen-key-redo = Újra
zen-restore-last-closed-tab-shortcut = Utoljára bezárt lap újranyitása
zen-location-open-shortcut = Hely megnyitása
zen-location-open-shortcut-alt = Hely megnyitása (Alt)
zen-key-undo-close-window = Bezárt ablak újranyitása
zen-text-action-undo-shortcut = Visszavonás
zen-text-action-redo-shortcut = Újra
zen-text-action-cut-shortcut = Kivágás
zen-text-action-copy-shortcut = Másolás
zen-text-action-copy-url-shortcut = Jelenlegi URL másolása
zen-text-action-paste-shortcut = Beillesztés
zen-text-action-select-all-shortcut = Összes kijelölése
zen-text-action-delete-shortcut = Törlés
zen-history-show-all-shortcut-mac = Összes előzmény mutatása (Mac)
zen-full-screen-shortcut = Teljes képernyőre váltás
zen-reader-mode-toggle-shortcut-windows = Olvasó Módra váltás (Windows)
zen-picture-in-picture-toggle-shortcut-alt = Kép a képbenre váltás (Alt)
zen-picture-in-picture-toggle-shortcut-mac = Kép a képben váltás (Mac)
zen-picture-in-picture-toggle-shortcut-mac-alt = Kép a képben váltás (Mac Alt)
zen-page-source-shortcut-safari = Oldal forrásának megtekintése (Safari)
zen-nav-stop-shortcut = Betöltés leállítása
zen-history-sidebar-shortcut = Előzmény oldalsáv mutatása
zen-window-minimize-shortcut = Ablak minimalizálása
zen-help-shortcut = Súgó megnyitása
zen-preferences-shortcut = Beállítások megnyitása
zen-hide-app-shortcut = Alkalmazás elrejtése
zen-hide-other-apps-shortcut = Többi alkalmazás elrejtése
zen-search-focus-shortcut = Fókusz Keresés
zen-search-focus-shortcut-alt = Fókusz Keresés (Alt)
zen-downloads-shortcut = Letöltése megnyitása
zen-addons-shortcut = Add-onok megnyitása
zen-file-open-shortcut = Fájl Megnyitása
zen-save-page-shortcut = Oldal Mentése
zen-print-shortcut = Oldal Nyomtatása
zen-close-shortcut-2 = Lap Bezárása
zen-mute-toggle-shortcut = Némítás Bekapcsolása
zen-key-delete = Törlés Gomb
zen-key-go-back = Vissza
zen-key-go-forward = Előre
zen-nav-back-shortcut-alt = Visszanavigálás (Alt)
zen-nav-fwd-shortcut-alt = Előrenavigálás (Alt)
zen-history-show-all-shortcut = Minden Előzmény Megjelenítése
zen-key-enter-full-screen = Teljes Képernyőre Váltás
zen-key-exit-full-screen = Kilépés a Teljes Képernyős Módból
zen-reader-mode-toggle-shortcut-other = Olvasó Mód Ki-/Bekapcsolása
zen-picture-in-picture-toggle-shortcut = Kép-a-Képben Mód Ki-/Bekapcsolása
zen-nav-reload-shortcut-2 = Oldal Újratöltése
zen-key-about-processes = A Folyamatokról
zen-page-source-shortcut = Oldal Forrásának Megtekintése
zen-page-info-shortcut = Oldal Adatainak Megtekintése
zen-find-shortcut = Keresés az Oldalon
zen-search-find-again-shortcut = Keresés Újra
zen-search-find-again-shortcut-prev = Előző Keresése
zen-search-find-again-shortcut-2 = Keresés Újra (Alt)
zen-bookmark-this-page-shortcut = Ezen Oldal Könyvjelzőzése
zen-bookmark-show-library-shortcut = Könyvjelzőkönyvtár Megtekintése
zen-key-stop = Betöltés Leállítása
zen-full-zoom-reduce-shortcut = Kicsinyítés
zen-full-zoom-enlarge-shortcut = Nagyítás
zen-full-zoom-reset-shortcut = Nagyítás Visszaállítása
zen-bidi-switch-direction-shortcut = Szöveg Irányának Megfordítása
zen-private-browsing-shortcut = Privát Böngészés
zen-screenshot-shortcut = Képernyőkép-készítés
zen-key-sanitize = Böngészési Adatok Törlése
zen-quit-app-shortcut = Kilépés az Alkalmazásból
zen-key-wr-capture-cmd = WR Rögzítési Parancs
zen-key-wr-toggle-capture-sequence-cmd = WR Rögzítési Szekvencia Ki-/Bekapcsolása
zen-nav-reload-shortcut = Oldal Újratöltése
zen-nav-reload-shortcut-skip-cache = Oldal Újratöltése (Gyorsítótár Átugrása)
zen-close-shortcut = Ablak Bezárása
zen-close-tab-shortcut = Lap Bezárása
zen-compact-mode-shortcut-show-sidebar = Lebegő oldalsáv ki-/bekapcsolása
zen-compact-mode-shortcut-show-toolbar = Lebegő eszköztár ki-/bekapcsolása
zen-compact-mode-shortcut-toggle = Kompakt mód ki-/bekapcsolása
zen-workspace-shortcut-switch-1 = Első Munkakörnyezetre Váltás
zen-workspace-shortcut-switch-2 = Második Munkakörnyezetre Váltás
zen-workspace-shortcut-switch-3 = Harmadik Munkakörnyezetre Váltás
zen-workspace-shortcut-switch-4 = Negyedik Munkakörnyezetre Váltás
zen-workspace-shortcut-switch-5 = Ötödik Munkakörnyezetre Váltás
zen-workspace-shortcut-switch-6 = Hatodik Munkakörnyezetre Váltás
zen-workspace-shortcut-switch-7 = Hetedik Munkakörnyezetre Váltás
zen-workspace-shortcut-switch-8 = Nyolcadik Munkakörnyezetre Váltás
zen-workspace-shortcut-switch-9 = Kilencedik Munkakörnyezetre Váltás
zen-workspace-shortcut-switch-10 = Tizedik Munkakörnyezetre Váltás
zen-workspace-shortcut-forward = Következő Munkakörnyezet
zen-workspace-shortcut-backward = Előző Munkakörnyezet
zen-web-panel-shortcut-toggle = Web panel ki-/bekapcsolása
zen-sidebar-shortcut-toggle = Oldalsáv Szélességének Ki-/Bekapcsolása
zen-pinned-tab-shortcut-reset = Rögzített Lap Visszaállítása Rögzített URL-re
zen-split-view-shortcut-grid = Osztott Nézet Grid Ki-/Bekapcsolása
zen-split-view-shortcut-vertical = Osztott Nézet Függőlegesen
zen-split-view-shortcut-horizontal = Osztott Nézet Vízszintesen
zen-split-view-shortcut-unsplit = Osztott Nézet Bezárása
zen-key-select-tab-1 = Első Lap Kiválasztása
zen-key-select-tab-2 = Második Lap Kiválasztása
zen-key-select-tab-3 = Harmadik Lap Kiválasztása
zen-key-select-tab-4 = Negyedik Lap Kiválasztása
zen-key-select-tab-5 = Ötödik Lap Kiválasztása
zen-key-select-tab-6 = Hatodik Lap Kiválasztása
zen-key-select-tab-7 = Hetedik Lap Kiválasztása
zen-key-select-tab-8 = Nyolcadik Lap Kiválasztása
zen-key-select-tab-last = Utolsó Lap Kiválasztása
zen-key-show-all-tabs = Minden Lap Megjelenítése
zen-key-goto-history = Előzményekre váltás
zen-key-go-home = Kezdőlapra Váltás
zen-bookmark-show-sidebar-shortcut = Könyvjelző Oldalsáv Megjelenítése
zen-bookmark-show-toolbar-shortcut = Könyvjelző Eszköztár Megjelenítése
zen-devtools-toggle-shortcut = Fejlesztőeszközök kapcsolása
zen-devtools-toggle-browser-toolbox-shortcut = Toggle Browser Toolbox
zen-devtools-toggle-browser-console-shortcut = Toggle Browser Console
zen-devtools-toggle-responsive-design-mode-shortcut = Toggle Responsive Design Mode
zen-devtools-toggle-inspector-shortcut = Toggle Inspector
zen-devtools-toggle-web-console-shortcut = Toggle Web Console
zen-devtools-toggle-js-debugger-shortcut = Toggle JavaScript Debugger
zen-devtools-toggle-net-monitor-shortcut = Toggle Network Monitor
zen-devtools-toggle-style-editor-shortcut = Toggle Style Editor
zen-devtools-toggle-performance-shortcut = Toggle Performance
zen-devtools-toggle-storage-shortcut = Toggle Storage
zen-devtools-toggle-dom-shortcut = Toggle DOM
zen-devtools-toggle-accessibility-shortcut = Toggle Accessibility
