pane-zen-looks-title = Megjelenés és Hangulat
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Az alapértelmezett nyelv átállításával a weboldalak könnyebben nyomon tudnak követni.
zen-look-and-feel-colors-header = Pick a theme colour
zen-look-and-feel-colors-description = Alakítsd kedvedre a { -brand-short-name } megjelenését és hangulatát
zen-look-and-feel-themed-toolbar = 
    .label = Eszköztár színezése az általad választott színnel
pane-zen-side-panels-title = Oldalsó Web Panelek
zen-side-panels-header = Web panelek általános beállításai
zen-side-panels-description = Növeld a produktivitásod több lappal egyszerre!
zen-side-panels-enabled = 
    .label = Oldalsó Web Panelek Bekapcsolása
zen-side-panels-close-on-blur = 
    .label = Panel bezárása amikor nincs fókuszban, vagy nincs kitűzve
zen-look-and-feel-compact-view-header = Kompakt nézet
zen-look-and-feel-compact-view-description = Csak azokat az eszköztárakat lásd amit használsz!
zen-look-and-feel-compact-view-enabled = 
    .label = A { -brand-short-name } kompakt módjának bekapcsolása
zen-look-and-feel-compact-view-top-toolbar = 
    .label = A felső eszköztár is legyen elrejtve kompakt módban
zen-look-and-feel-buttons-header = Gomb stílus
zen-look-and-feel-buttons-description = Válaszd ki, hogy milyen stílusú gombokat szeretnél látni
zen-look-and-feel-pilled-buttons = 
    .label = Lekerekített Gombok
pane-zen-workspaces-title = Munkakörnyezetek
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = Munkakörnyezetek
pane-zen-workspaces-header = Munkakörnyezetek
zen-settings-workspaces-header = Munkakörnyezetek általános beállításai
zen-settings-workspaces-description = A munkakörnyezetekkel egyszerre több böngészési munkameneted is lehet!
zen-settings-workspaces-enabled = 
    .label = Munkakörnyezetek Bekapcsolása (Kísérleti)
pane-zen-theme-title = Téma Beállítások
zen-vertical-tabs-title = Oldalsó sáv és lapok elrendezése
zen-vertical-tabs-header = Függőleges Lapok
zen-vertical-tabs-description = Kezeld a lapjaidat függőleges elrendezésben
zen-vertical-tabs-show-expand-button = 
    .label = Nagyobbítás Gomb Mutatása
zen-vertical-tabs-expand-tabs-by-default = Lapok Alapértelmezett Nagyobbítása
zen-vertical-tabs-dont-expand-tabs-by-default = A Lapok Alapértelmezetten Ne Legyenek Nagyobbítva
zen-vertical-tabs-expand-tabs-on-hover = Lapok Nagyobbítása a Kurzor Mozgatásával (Kompakt módban nem fog működni)
zen-vertical-tabs-expand-tabs-header = Hogyan legyenek a lapok nagyobbítva
zen-vertical-tabs-expand-tabs-description = Válassz, hogyan legyenek a lapok nagyobbítva az oldalsó sávon
zen-theme-marketplace-header = Téma Áruház
zen-theme-marketplace-description = Keress és adj hozzá témákat az áruházból.
zen-theme-marketplace-remove-button = 
    .label = Téma Törlése
zen-theme-marketplace-check-for-updates-button = 
    .label = Frissítések Keresése
zen-theme-marketplace-updates-success = Téma sikeresen frissítve
zen-theme-marketplace-updates-fail = Nem található frissítés!
pane-zen-marketplace-title = Téma Áruház
zen-look-and-feel-legacy-toolbar = 
    .label = Use legacy toolbar position. Requires a restart!
zen-theme-marketplace-link = Áruház Megnyitása
pane-zen-CKS-title = Gyorsgombok
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } Gyorsgombok
zen-settings-CKS-header = Gyorsgombok személyre szabása
zen-settings-CKS-description = Állítsd be kedvedre az alapértelmezett gyorsgombokat, hogy növeld a böngészési élményedet
zen-settings-CKS-disable-firefox = 
    .label = A { -brand-short-name } alapértelmezett gyorsgombjainak kikapcsolása
zen-cks-group-tab-action = Lapok Kezelése
zen-cks-group-page-action = Oldalak Kezelése
zen-cks-group-visible-action = Vizuális Beállítások Kezelése
zen-cks-group-history-action = Előzmények Kezelése
zen-cks-group-search-action = Keresési Beállítások Kezelése
zen-cks-group-tools-action = Eszközök Kezelése
zen-cks-group-bookmark-action = Könyvjelzők Kezelése
zen-cks-group-open-page-action = Oldalak Megnyitásának Kezelése
zen-cks-group-downloads-action = Letöltések Kezelése
zen-cks-group-sidebar-action = Oldalsó Sáv Kezelése
zen-cks-group-compact-mode-action = Kompakt Mód Kezelése
zen-cks-group-split-view-action = Osztott Kép Kezelése
zen-cks-group-workspace-action = Munkakörnyezetek Kezelése
open-new-tab = Új Lap Megnyitása
close-tab = Lap Bezárása
open-new-window = Új Ablak Megnyitása
open-new-private-window = Új Privát Ablak Megnyitása
close-window = Ablak Bezárása
restore-last-tab = Előző Lap Visszaállítása
restore-last-window = Előző Ablak Visszaállítása
show-next-tab = Következő Lap Mutatása
show-previous-tab = Előző Lap Mutatása
show-all-tabs-panel = Összes Lap Panel Mutatása
send-with-mail = Oldal Küldése Email-ben
save-page = Oldal Mentése
print-page = Oldal Nyomtatása
mute-current-tab = Jelenlegi Lap Némítása
show-source-of-page = Oldal Forrásának Mutatása
show-page-info = Oldal Információinak Mutatása
zoom-in = Nagyítás
zoom-out = Kicsinyítés
reset-zoom = Nagyítás Visszaállítása
back = Vissza
forward = Előre
stop = Megállítás
reload = Újratöltés
force-reload = Kényszerítétt Újratöltés
search-in-this-page = Oldalon Való Keresés
show-next-search-result = Következő Keresési Eredmény Mutatása
show-previous-search-result = Előző Keresési Eredmény Mutatása
search-the-web = Keresés a Weben
open-migration-wizard = Költözési Varázsló Megnyitása
quit-from-application = Program Bezárása
enter-into-customize-mode = Belépés a Személyre Szabási Módba
enter-into-offline-mode = Offline Módba Lépés
open-screen-capture = Képernyőkép Készítése
bookmark-this-page = Oldal Mentése a Könyvjelzők Közé
open-bookmark-add-tool = Könyvjelző Készítő Megnyitása
open-bookmarks-manager = Könyvjelző Kezelő Megnyitása
toggle-bookmark-toolbar = Könyvjelző Eszköztár Ki-/Bekapcsolása
open-general-preferences = Általános Beállítások Megnyitása
open-privacy-preferences = Adatvédelmi Beállítások Megnyitása
open-workspaces-preferences = Munkakörnyezeti Beállítások Megnyitása
open-containers-preferences = Konténer Beállítások Megnyitása
open-search-preferences = Keresési Beállítások Megnyitása
open-sync-preferences = Szinkronizációs Beállítások Megnyitása
open-task-manager = Folyamatkezelő Megnyitása
open-addons-manager = Bővítménykezelő Megnyitása
open-home-page = Kezdeti Lap Megnyitása
forget-history = Előzmények Elfelejtése
quick-forget-history = Előzmények Gyors Elfelejtése
clear-recent-history = Nemrégi Előzmények Törlése
restore-last-session = Előző Munkamenet Visszaállítása
search-history = Keresés Előzmények Között
manage-history = Előzmények Kezelése
open-downloads = Letöltések Megnyitása
show-bookmark-sidebar = Oldalsó Könyjelzőkezelő Megnyitása
show-history-sidebar = Oldalsó Előzménykezelő Megnyitása
show-synced-tabs-sidebar = Szinkronizált Lapok Megnyitása az Oldalsó Sávnál
reverse-sidebar = Oldalsó Sáv Pozíciójának Megfordítása
hide-sidebar = Oldalsó Sáv Elrejtése
toggle-sidebar = Oldalsó Sáv Ki-/Bekapcsolása
zen-toggle-web-panels = Web Panelek Ki-/Bekapcsolása
zen-toggle-compact-mode = Kompakt Mód Ki-/Bekapcsolása
zen-toggle-compact-mode-sidebar = Kompakt Oldalsó Sáv Ki-/Bekapcsolása
zen-toggle-compact-mode-toolbar = Kompakt Eszköztár Ki-/Bekapcsolása
zen-change-workspace = Váltás Munkakörnyezetek Között
zen-split-view-grid = Split View Grid
zen-split-view-vertical = Függőleges Felosztás
zen-split-view-horizontal = Vízszintes Felosztás
zen-split-view-close = Osztott Mód Bezárása
