pane-zen-looks-title = Megjelenés és Hangulat
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Az alapértelmezett nyelv átállításával a weboldalak könnyebben nyomon tudnak követni.
zen-look-and-feel-colors-header = Pick a theme colour
zen-look-and-feel-colors-description = Alakítsd kedvedre a { -brand-short-name } megjelenését és hangulatát
zen-look-and-feel-themed-toolbar = 
    .label = Eszköztár színezése az általad választott színnel
pane-zen-side-panels-title = Oldalsó Web Panelek
zen-side-panels-header = Web panelek általános beállításai
zen-side-panels-description = Növeld a produktivitásod több lappal egyszerre!
zen-side-panels-enabled = 
    .label = Oldalsó Web Panelek Bekapcsolása
zen-side-panels-close-on-blur = 
    .label = Panel bezárása amikor nincs fókuszban, vagy nincs kitűzve
zen-look-and-feel-compact-view-header = Kompakt nézet
zen-look-and-feel-compact-view-description = Csak azokat az eszköztárakat lásd amit használsz!
zen-look-and-feel-compact-view-enabled = 
    .label = A { -brand-short-name } kompakt módjának bekapcsolása
zen-look-and-feel-compact-view-top-toolbar = 
    .label = A felső eszköztár is legyen elrejtve kompakt módban
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Briefly make the toolbar popup when switching or opening new tabs in compact mode
zen-look-and-feel-buttons-header = Gomb stílus
zen-look-and-feel-buttons-description = Válaszd ki, hogy milyen stílusú gombokat szeretnél látni
zen-look-and-feel-pilled-buttons = 
    .label = Lekerekített Gombok
pane-zen-workspaces-title = Munkakörnyezetek
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = Munkakörnyezetek
pane-zen-workspaces-header = Munkakörnyezetek
zen-settings-workspaces-header = Munkakörnyezetek általános beállításai
zen-settings-workspaces-description = A munkakörnyezetekkel egyszerre több böngészési munkameneted is lehet!
zen-settings-workspaces-enabled = 
    .label = Munkakörnyezetek Bekapcsolása (Kísérleti)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Hide the default container indicator in the tab bar
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Allow workspaces have their own pinned tabs
pane-zen-theme-title = Téma Beállítások
zen-vertical-tabs-title = Oldalsó sáv és lapok elrendezése
zen-vertical-tabs-header = Függőleges Lapok
zen-vertical-tabs-description = Kezeld a lapjaidat függőleges elrendezésben
zen-vertical-tabs-show-expand-button = 
    .label = Nagyobbítás Gomb Mutatása
zen-vertical-tabs-expand-tabs-by-default = Lapok Alapértelmezett Nagyobbítása
zen-vertical-tabs-dont-expand-tabs-by-default = A Lapok Alapértelmezetten Ne Legyenek Nagyobbítva
zen-vertical-tabs-expand-tabs-on-hover = Lapok Nagyobbítása a Kurzor Mozgatásával (Kompakt módban nem fog működni)
zen-vertical-tabs-expand-tabs-header = Hogyan legyenek a lapok nagyobbítva
zen-vertical-tabs-expand-tabs-description = Válassz, hogyan legyenek a lapok nagyobbítva az oldalsó sávon
zen-theme-marketplace-header = Zen Mods
zen-theme-marketplace-description = Keress és adj hozzá témákat az áruházból.
zen-theme-marketplace-remove-button = 
    .label = Téma Törlése
zen-theme-marketplace-check-for-updates-button = 
    .label = Frissítések Keresése
zen-theme-marketplace-updates-success = Téma sikeresen frissítve
zen-theme-marketplace-updates-fail = Nem található frissítés!
zen-theme-marketplace-toggle-enabled-button = 
    .title = Disable Theme
zen-theme-marketplace-toggle-disabled-button = 
    .title = Enable Theme
zen-theme-marketplace-remove-confirmation = Are you sure you want to remove this mod?
zen-theme-marketplace-close-modal = Close
zen-theme-marketplace-theme-header-title = 
    .title = CSS Selector: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = None
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Type something...
pane-zen-marketplace-title = Zen Mods
zen-settings-workspaces-display-as-icon-strip = 
    .label = Display workspaces as an icon strip
zen-theme-marketplace-link = Áruház Megnyitása
zen-dark-theme-styles-header = Dark Theme Styles
zen-dark-theme-styles-description = Customize the dark theme to your liking
zen-dark-theme-styles-amoled = Night Theme
zen-dark-theme-styles-default = Default Dark Theme
zen-dark-theme-styles-colorful = Colorful Dark Theme
zen-compact-mode-styles-left = Hide Tab bar
zen-compact-mode-styles-top = Hide Top bar
zen-compact-mode-styles-both = Hide Both
pane-zen-CKS-title = Gyorsgombok
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } Gyorsgombok
zen-settings-CKS-header = Gyorsgombok személyre szabása
zen-settings-CKS-description = Állítsd be kedvedre az alapértelmezett gyorsgombokat, hogy növeld a böngészési élményedet
zen-settings-CKS-disable-firefox = 
    .label = A { -brand-short-name } alapértelmezett gyorsgombjainak kikapcsolása
zen-settings-CKS-duplicate-shortcut = 
    .label = Duplicate Shortcut
zenCKSOption-group-other = Other
zenCKSOption-group-windowAndTabManagement = Window & Tab Management
zenCKSOption-group-navigation = Navigation
zenCKSOption-group-searchAndFind = Search & Find
zenCKSOption-group-pageOperations = Page Operations
zenCKSOption-group-historyAndBookmarks = History & Bookmarks
zenCKSOption-group-mediaAndDisplay = Media & Display
zenCKSOption-group-zen-compact-mode = Compact Mode
zenCKSOption-group-zen-workspace = Workspaces
zenCKSOption-group-zen-other = Other Zen Features
zenCKSOption-group-zen-split-view = Split View
zen-key-quick-restart = Quick Restart
zen-window-new-shortcut = New Window
zen-tab-new-shortcut = New Tab
zen-location-open-shortcut = Open Location
zen-location-open-shortcut-alt = Open Location (Alt)
zen-search-focus-shortcut = Focus Search
zen-search-focus-shortcut-alt = Focus Search (Alt)
zen-downloads-shortcut = Open Downloads
zen-addons-shortcut = Open Add-ons
zen-file-open-shortcut = Open File
zen-save-page-shortcut = Save Page
zen-print-shortcut = Print Page
zen-close-shortcut-2 = Close Tab
zen-mute-toggle-shortcut = Toggle Mute
zen-key-delete = Delete Key
zen-key-go-back = Go Back
zen-key-go-forward = Go Forward
zen-nav-back-shortcut-alt = Navigate Back (Alt)
zen-nav-fwd-shortcut-alt = Navigate Forward (Alt)
zen-history-show-all-shortcut = Show All History
zen-key-enter-full-screen = Enter Full Screen
zen-key-exit-full-screen = Exit Full Screen
zen-reader-mode-toggle-shortcut-other = Toggle Reader Mode
zen-picture-in-picture-toggle-shortcut = Toggle Picture-in-Picture
zen-nav-reload-shortcut-2 = Reload Page
zen-key-about-processes = About Processes
zen-page-source-shortcut = View Page Source
zen-page-info-shortcut = View Page Info
zen-find-shortcut = Find on Page
zen-search-find-again-shortcut = Find Again
zen-search-find-again-shortcut-prev = Find Previous
zen-search-find-again-shortcut-2 = Find Again (Alt)
zen-bookmark-this-page-shortcut = Bookmark This Page
zen-bookmark-show-library-shortcut = Show Bookmarks Library
zen-key-stop = Stop Loading
zen-full-zoom-reduce-shortcut = Zoom Out
zen-full-zoom-enlarge-shortcut = Zoom In
zen-full-zoom-reset-shortcut = Reset Zoom
zen-bidi-switch-direction-shortcut = Switch Text Direction
zen-private-browsing-shortcut = Private Browsing
zen-screenshot-shortcut = Take Screenshot
zen-key-sanitize = Clear Browsing Data
zen-quit-app-shortcut = Quit Application
zen-key-wr-capture-cmd = WR Capture Command
zen-key-wr-toggle-capture-sequence-cmd = Toggle WR Capture Sequence
zen-nav-reload-shortcut = Reload Page
zen-nav-reload-shortcut-skip-cache = Reload Page (Skip Cache)
zen-close-shortcut = Close Window
zen-close-tab-shortcut = Close Tab
zen-compact-mode-shortcut-show-sidebar = Toggle Floating Sidebar
zen-compact-mode-shortcut-show-toolbar = Toggle Floating Toolbar
zen-compact-mode-shortcut-toggle = Toggle Compact Mode
zen-workspace-shortcut-switch-1 = Switch to Workspace 1
zen-workspace-shortcut-switch-2 = Switch to Workspace 2
zen-workspace-shortcut-switch-3 = Switch to Workspace 3
zen-workspace-shortcut-switch-4 = Switch to Workspace 4
zen-workspace-shortcut-switch-5 = Switch to Workspace 5
zen-workspace-shortcut-switch-6 = Switch to Workspace 6
zen-workspace-shortcut-switch-7 = Switch to Workspace 7
zen-workspace-shortcut-switch-8 = Switch to Workspace 8
zen-workspace-shortcut-switch-9 = Switch to Workspace 9
zen-workspace-shortcut-switch-10 = Switch to Workspace 10
zen-workspace-shortcut-forward = Forward Workspace
zen-workspace-shortcut-backward = Backward Workspace
zen-web-panel-shortcut-toggle = Toggle Web Panel
zen-sidebar-shortcut-toggle = Toggle Sidebar's Width
zen-split-view-shortcut-grid = Toggle Split View Grid
zen-split-view-shortcut-vertical = Toggle Split View Vertical
zen-split-view-shortcut-horizontal = Toggle Split View Horizontal
zen-split-view-shortcut-unsplit = Close Split View
