pane-zen-looks-title = Зовнішній вигляд
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Зміна мови за замовчуванням може полегшити вебсайтам відстеження вас.
zen-look-and-feel-colors-header = Виберіть колір теми
zen-look-and-feel-colors-description = Зробіть так, щоб { -brand-short-name } виглядав так, як вам подобається
zen-look-and-feel-themed-toolbar = 
    .label = Зробіть панель інструментів тематичною з акцентним кольором
pane-zen-side-panels-title = Бічна вебпанель
zen-side-panels-header = Загальні налаштування для вебпанелі
zen-side-panels-description = Підвищуйте продуктивність, маючи кілька переглядів одночасно!
zen-side-panels-enabled = 
    .label = Увімкнути бічні вебпанелі
zen-side-panels-close-on-blur = 
    .label = Закривати панель, коли вона втрачає фокус, якщо вона не закріплена
zen-look-and-feel-compact-view-header = Показати в компактному вигляді
zen-look-and-feel-compact-view-description = Показувати тільки ті панелі інструментів, які ви використовуєте!
zen-look-and-feel-compact-view-enabled = 
    .label = Увімкнути компактний режим { -brand-short-name }
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Приховати верхню панель інструментів у компактному режимі
zen-look-and-feel-buttons-header = Стиль кнопки
zen-look-and-feel-buttons-description = Виберіть стиль кнопок, який ви хочете бачити
zen-look-and-feel-pilled-buttons = 
    .label = Круглі кнопки
pane-zen-workspaces-title = Робоче місце
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = Робоче місце
pane-zen-workspaces-header = Робоче місце
zen-settings-workspaces-header = Загальні налаштування для робочих місць
zen-settings-workspaces-description = Завдяки робочим просторам ви можете мати кілька сеансів перегляду одночасно!
zen-settings-workspaces-enabled = 
    .label = Увімкнути робочі місця (експериментально)
pane-zen-theme-title = Налаштування тем
zen-vertical-tabs-title = Розташування бічних панелей і вкладок
zen-vertical-tabs-header = Вертикальні вкладки
zen-vertical-tabs-description = Керуйте вкладками у вертикальному розташуванні
zen-vertical-tabs-show-expand-button = 
    .label = Показати кнопку Розгорнути
zen-vertical-tabs-expand-tabs-by-default = Розгорнути вкладки за замовчуванням
zen-vertical-tabs-dont-expand-tabs-by-default = Не розгортати вкладки за замовчуванням
zen-vertical-tabs-expand-tabs-on-hover = Розгорнути вкладки при наведенні (не працюватиме в компактному режимі)
zen-vertical-tabs-expand-tabs-header = Як розгорнути вкладки
zen-vertical-tabs-expand-tabs-description = Виберіть спосіб розгортання вкладок на бічній панелі
zen-theme-marketplace-header = Магазин тем
zen-theme-marketplace-description = Знайдіть і встановіть теми з магазину.
zen-theme-marketplace-remove-button = 
    .label = Видалити тему
zen-theme-marketplace-check-for-updates-button = 
    .label = Check for Updates
zen-theme-marketplace-link = Відвідати магазин
pane-zen-CKS-title = Комбінації клавіш
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } Комбінації клавіш
zen-settings-CKS-header = Налаштуйте комбінації клавіш
zen-settings-CKS-description = Змініть комбінації клавіш за замовчуванням на свої уподобання та покращить роботу в Інтернеті
zen-settings-CKS-disable-firefox = 
    .label = Вимкнути стандартні комбінації клавіш для { -brand-short-name }
zen-cks-group-tab-action = Вкладка Дії
zen-cks-group-page-action = Дії на сторінці
zen-cks-group-visible-action = Видимі дії
zen-cks-group-history-action = Історія Дії
zen-cks-group-search-action = Дії пошуку
zen-cks-group-tools-action = Інструменти Дії
zen-cks-group-bookmark-action = Дії з закладками
zen-cks-group-open-page-action = Дії відкриття сторінки
zen-cks-group-downloads-action = Дії завантаження
zen-cks-group-sidebar-action = Дії бічної панелі
zen-cks-group-compact-mode-action = Дії компактного режиму
zen-cks-group-split-view-action = Дії в режимі розділеного перегляду
zen-cks-group-workspace-action = Дії у робочій області
open-new-tab = Відкрити нову вкладку
close-tab = Закрити вкладку
open-new-window = Відкрити нове вікно
open-new-private-window = Відкрити в приватному вікні
close-window = Закрити вікно
restore-last-tab = Відновити минулу вкладку
restore-last-window = Відновити минуле вікно
show-next-tab = Показати наступну вкладку
show-previous-tab = Показати минулу вкладку
show-all-tabs-panel = Показати всі вкладки на панелі
send-with-mail = Надіслати сторінку поштою
save-page = Зберегти сторінку
print-page = Друкувати сторінку
mute-current-tab = Замутити поточну вкладку
show-source-of-page = Показати джерело сторінки
show-page-info = Показати інформацію сторінки
zoom-in = Збільшити
zoom-out = Зменшити
reset-zoom = Скинути масштаб
back = Назад
forward = Далі
stop = Зупинити
reload = Перезавантажити
force-reload = Швидке перезавантаження
search-in-this-page = Пошук на цій сторінці
show-next-search-result = Показати наступні результати пошуку
show-previous-search-result = Показати попередні результати пошуку
search-the-web = Шукати в інтернеті
open-migration-wizard = Відкрити майстра міграції
quit-from-application = Вийти з програми
enter-into-customize-mode = Увійти в режим налаштування
enter-into-offline-mode = Увійти в автономний режим
open-screen-capture = Відкрити знімок екрана
bookmark-this-page = Додати цю сторінку до закладок
open-bookmark-add-tool = Відкрити інструмент додавання закладки
open-bookmarks-manager = Відкрити менеджер закладок
toggle-bookmark-toolbar = Перемикання закладок
open-general-preferences = Відкрити Загальні налаштування
open-privacy-preferences = Відкрити налаштування конфіденційності
open-workspaces-preferences = Налаштування робочих місць
open-containers-preferences = Налаштування контейнерів
open-search-preferences = Відкрити налаштування пошуку
open-sync-preferences = Відкрити налаштування синхронізації
open-task-manager = Відкрити диспетчер завдань
open-addons-manager = Відкрити менеджер розширень
open-home-page = Відкрити головну сторінку
forget-history = Забути історію
quick-forget-history = Видалити історію
clear-recent-history = Очистити недавню історію
restore-last-session = Відновити останню сесію
search-history = Історія пошуку
manage-history = Керування історією
open-downloads = Відкрити завантаження
show-bookmark-sidebar = Показати бічну панель закладок
show-history-sidebar = Показати бічну панель історії
show-synced-tabs-sidebar = Показати бічну панель синхронізованих вкладок
reverse-sidebar = Зворотне положення бічної панелі
hide-sidebar = Приховати бічну панель
toggle-sidebar = Перемкнути бічну панель
zen-toggle-web-panels = Перемикання вебпанель
zen-toggle-compact-mode = Перемикнути компактний режим
zen-toggle-compact-mode-sidebar = Перемикнути бічну панель компактного режиму
zen-toggle-compact-mode-toolbar = Перемикнути компактний режим Панель інструментів
zen-change-workspace = Перемкнути робоче місце
zen-split-view-grid = Сітка роздільного перегляду
zen-split-view-vertical = Розділити вид по вертикалі
zen-split-view-horizontal = Розділити вид по горизонталі
zen-split-view-close = Закрити розділений вигляд
