pane-zen-looks-title = Зовнішній вигляд
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Зміна типової мови може полегшити вебсайтам відстежувати вас.
zen-look-and-feel-colors-header = Виберіть колір теми
zen-look-and-feel-colors-description = Зробіть так, щоб { -brand-short-name } виглядав так, як вам подобається
zen-look-and-feel-themed-toolbar = 
    .label = Зробіть панель інструментів тематичною з акцентним кольором
pane-zen-side-panels-title = Бічна вебпанель
zen-side-panels-header = Загальні налаштування для вебпанелі
zen-side-panels-description = Підвищуйте продуктивність, маючи кілька переглядів одночасно!
zen-side-panels-enabled = 
    .label = Увімкнути бічні вебпанелі
zen-side-panels-close-on-blur = 
    .label = Закривати панель, коли вона втрачає фокус, якщо вона не закріплена
zen-look-and-feel-compact-view-header = Показати в компактному вигляді
zen-look-and-feel-compact-view-description = Показувати тільки ті панелі інструментів, які ви використовуєте!
zen-look-and-feel-compact-view-enabled = 
    .label = Увімкнути компактний режим { -brand-short-name }
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Приховати верхню панель інструментів у компактному режимі
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Коротко показувати, щоби панель інструментів спливала при перемиканні або відкритті нових вкладок у компактному режимі
zen-look-and-feel-buttons-header = Стиль кнопки
zen-look-and-feel-buttons-description = Виберіть стиль кнопок, який ви хочете бачити
zen-look-and-feel-pilled-buttons = 
    .label = Круглі кнопки
pane-zen-workspaces-title = Робочі області
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = Робочі області
pane-zen-workspaces-header = Робочі області
zen-settings-workspaces-header = Загальні налаштування для робочих областей
zen-settings-workspaces-description = Завдяки робочим областям ви можете мати кілька сеансів перегляду одночасно!
zen-settings-workspaces-enabled = 
    .label = Увімкнути робочі області (експериментально)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Приховати індикатор типового контейнера на панелі вкладок
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Дозволити робочим областям мати власні закріплені вкладки
pane-zen-theme-title = Налаштування тем
zen-vertical-tabs-title = Розташування бічних панелей і вкладок
zen-vertical-tabs-header = Вертикальні вкладки
zen-vertical-tabs-description = Керуйте вкладками у вертикальному розташуванні
zen-vertical-tabs-show-expand-button = 
    .label = Показати кнопку «Розгорнути»
zen-vertical-tabs-expand-tabs-by-default = Розгортати вкладки по стандарту
zen-vertical-tabs-dont-expand-tabs-by-default = Не розгортати вкладки по стандарту
zen-vertical-tabs-expand-tabs-on-hover = Розгорнути вкладки при наведенні (не працюватиме в компактному режимі)
zen-vertical-tabs-expand-tabs-header = Як розгорнути вкладки
zen-vertical-tabs-expand-tabs-description = Виберіть спосіб розгортання вкладок на бічній панелі
zen-theme-marketplace-header = Модифікації Zen
zen-theme-marketplace-description = Знайдіть і встановіть теми з магазину.
zen-theme-marketplace-remove-button = 
    .label = Видалити тему
zen-theme-marketplace-check-for-updates-button = 
    .label = Перевірити наявність оновлень
zen-theme-marketplace-updates-success = Тему успішно оновлено
zen-theme-marketplace-updates-fail = Не знайдено оновлень!
zen-theme-marketplace-toggle-enabled-button = 
    .title = Вимкнути тему
zen-theme-marketplace-toggle-disabled-button = 
    .title = Ввімкнути тему
zen-theme-marketplace-remove-confirmation = Ви впевнені, що хочете видалити цей мод?
zen-theme-marketplace-close-modal = Закрити
zen-theme-marketplace-theme-header-title = 
    .title = Селектор CSS：{ $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = Нічого
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Напишіть щось...
pane-zen-marketplace-title = Модифікації Zen
zen-settings-workspaces-display-as-icon-strip = 
    .label = Показувати робочі області у вигляді смуги значків
zen-theme-marketplace-link = Відвідати магазин
zen-dark-theme-styles-header = Стилі темної теми
zen-dark-theme-styles-description = Налаштуйте темну тему на свій смак
zen-dark-theme-styles-amoled = Нічна тема
zen-dark-theme-styles-default = Типова темна тема
zen-dark-theme-styles-colorful = Кольорова темна тема
zen-compact-mode-styles-left = Приховати панель вкладок
zen-compact-mode-styles-top = Приховати верхню панель
zen-compact-mode-styles-both = Приховати обидві
pane-zen-CKS-title = Комбінації клавіш
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = Комбінації клавіш { -brand-short-name }
zen-settings-CKS-header = Налаштуйте комбінації клавіш
zen-settings-CKS-description = Змініть комбінації клавіш за замовчуванням на свої уподобання та покращить роботу в Інтернеті
zen-settings-CKS-disable-firefox = 
    .label = Вимкнути стандартні комбінації клавіш для { -brand-short-name }
zen-settings-CKS-duplicate-shortcut = 
    .label = Duplicate Shortcut
zenCKSOption-group-other = Other
zenCKSOption-group-windowAndTabManagement = Window & Tab Management
zenCKSOption-group-navigation = Navigation
zenCKSOption-group-searchAndFind = Search & Find
zenCKSOption-group-pageOperations = Page Operations
zenCKSOption-group-historyAndBookmarks = History & Bookmarks
zenCKSOption-group-mediaAndDisplay = Media & Display
zenCKSOption-group-zen-compact-mode = Compact Mode
zenCKSOption-group-zen-workspace = Workspaces
zenCKSOption-group-zen-other = Other Zen Features
zenCKSOption-group-zen-split-view = Split View
zen-key-quick-restart = Quick Restart
zen-window-new-shortcut = New Window
zen-tab-new-shortcut = New Tab
zen-location-open-shortcut = Open Location
zen-location-open-shortcut-alt = Open Location (Alt)
zen-search-focus-shortcut = Focus Search
zen-search-focus-shortcut-alt = Focus Search (Alt)
zen-downloads-shortcut = Open Downloads
zen-addons-shortcut = Open Add-ons
zen-file-open-shortcut = Open File
zen-save-page-shortcut = Save Page
zen-print-shortcut = Print Page
zen-close-shortcut-2 = Close Tab
zen-mute-toggle-shortcut = Toggle Mute
zen-key-delete = Delete Key
zen-key-go-back = Go Back
zen-key-go-forward = Go Forward
zen-nav-back-shortcut-alt = Navigate Back (Alt)
zen-nav-fwd-shortcut-alt = Navigate Forward (Alt)
zen-history-show-all-shortcut = Show All History
zen-key-enter-full-screen = Enter Full Screen
zen-key-exit-full-screen = Exit Full Screen
zen-reader-mode-toggle-shortcut-other = Toggle Reader Mode
zen-picture-in-picture-toggle-shortcut = Toggle Picture-in-Picture
zen-nav-reload-shortcut-2 = Reload Page
zen-key-about-processes = About Processes
zen-page-source-shortcut = View Page Source
zen-page-info-shortcut = View Page Info
zen-find-shortcut = Find on Page
zen-search-find-again-shortcut = Find Again
zen-search-find-again-shortcut-prev = Find Previous
zen-search-find-again-shortcut-2 = Find Again (Alt)
zen-bookmark-this-page-shortcut = Bookmark This Page
zen-bookmark-show-library-shortcut = Show Bookmarks Library
zen-key-stop = Stop Loading
zen-full-zoom-reduce-shortcut = Zoom Out
zen-full-zoom-enlarge-shortcut = Zoom In
zen-full-zoom-reset-shortcut = Reset Zoom
zen-bidi-switch-direction-shortcut = Switch Text Direction
zen-private-browsing-shortcut = Private Browsing
zen-screenshot-shortcut = Take Screenshot
zen-key-sanitize = Clear Browsing Data
zen-quit-app-shortcut = Quit Application
zen-key-wr-capture-cmd = WR Capture Command
zen-key-wr-toggle-capture-sequence-cmd = Toggle WR Capture Sequence
zen-nav-reload-shortcut = Reload Page
zen-nav-reload-shortcut-skip-cache = Reload Page (Skip Cache)
zen-close-shortcut = Close Window
zen-close-tab-shortcut = Close Tab
zen-compact-mode-shortcut-show-sidebar = Toggle Floating Sidebar
zen-compact-mode-shortcut-show-toolbar = Toggle Floating Toolbar
zen-compact-mode-shortcut-toggle = Toggle Compact Mode
zen-workspace-shortcut-switch-1 = Switch to Workspace 1
zen-workspace-shortcut-switch-2 = Switch to Workspace 2
zen-workspace-shortcut-switch-3 = Switch to Workspace 3
zen-workspace-shortcut-switch-4 = Switch to Workspace 4
zen-workspace-shortcut-switch-5 = Switch to Workspace 5
zen-workspace-shortcut-switch-6 = Switch to Workspace 6
zen-workspace-shortcut-switch-7 = Switch to Workspace 7
zen-workspace-shortcut-switch-8 = Switch to Workspace 8
zen-workspace-shortcut-switch-9 = Switch to Workspace 9
zen-workspace-shortcut-switch-10 = Switch to Workspace 10
zen-workspace-shortcut-forward = Forward Workspace
zen-workspace-shortcut-backward = Backward Workspace
zen-web-panel-shortcut-toggle = Toggle Web Panel
zen-sidebar-shortcut-toggle = Toggle Sidebar's Width
zen-split-view-shortcut-grid = Toggle Split View Grid
zen-split-view-shortcut-vertical = Toggle Split View Vertical
zen-split-view-shortcut-horizontal = Toggle Split View Horizontal
zen-split-view-shortcut-unsplit = Close Split View
