pane-zen-looks-title = Зовнішній вигляд
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Зміна типової мови може полегшити вебсайтам відстежувати вас.
zen-look-and-feel-colors-header = Виберіть колір теми
zen-look-and-feel-colors-description = Зробіть так, щоб { -brand-short-name } виглядав так, як вам подобається
zen-look-and-feel-themed-toolbar = 
    .label = Зробіть панель інструментів тематичною з акцентним кольором
pane-zen-side-panels-title = Бічна вебпанель
zen-side-panels-header = Загальні налаштування для вебпанелі
zen-side-panels-description = Підвищуйте продуктивність, маючи кілька переглядів одночасно!
zen-side-panels-enabled = 
    .label = Увімкнути бічні вебпанелі
zen-side-panels-close-on-blur = 
    .label = Закривати панель, коли вона втрачає фокус, якщо вона не закріплена
zen-look-and-feel-compact-view-header = Показати в компактному вигляді
zen-look-and-feel-compact-view-description = Показувати тільки ті панелі інструментів, які ви використовуєте!
zen-look-and-feel-compact-view-enabled = 
    .label = Увімкнути компактний режим { -brand-short-name }
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Приховати верхню панель інструментів у компактному режимі
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Коротко показувати, щоби панель інструментів спливала при перемиканні або відкритті нових вкладок у компактному режимі
zen-look-and-feel-buttons-header = Стиль кнопки
zen-look-and-feel-buttons-description = Виберіть стиль кнопок, який ви хочете бачити
zen-look-and-feel-pilled-buttons = 
    .label = Круглі кнопки
pane-zen-workspaces-title = Робочі області
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = Робочі області
pane-zen-workspaces-header = Робочі області
zen-settings-workspaces-header = Загальні налаштування для робочих областей
zen-settings-workspaces-description = Завдяки робочим областям ви можете мати кілька сеансів перегляду одночасно!
zen-settings-workspaces-enabled = 
    .label = Увімкнути робочі області (експериментально)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Приховати індикатор типового контейнера на панелі вкладок
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Дозволити робочим областям мати власні закріплені вкладки
pane-zen-theme-title = Налаштування тем
zen-vertical-tabs-title = Розташування бічних панелей і вкладок
zen-vertical-tabs-header = Вертикальні вкладки
zen-vertical-tabs-description = Керуйте вкладками у вертикальному розташуванні
zen-vertical-tabs-show-expand-button = 
    .label = Показати кнопку «Розгорнути»
zen-vertical-tabs-expand-tabs-by-default = Розгортати вкладки по стандарту
zen-vertical-tabs-dont-expand-tabs-by-default = Не розгортати вкладки по стандарту
zen-vertical-tabs-expand-tabs-on-hover = Розгорнути вкладки при наведенні (не працюватиме в компактному режимі)
zen-vertical-tabs-expand-tabs-header = Як розгорнути вкладки
zen-vertical-tabs-expand-tabs-description = Виберіть спосіб розгортання вкладок на бічній панелі
zen-theme-marketplace-header = Модифікації Zen
zen-theme-marketplace-description = Знайдіть і встановіть теми з магазину.
zen-theme-marketplace-remove-button = 
    .label = Видалити тему
zen-theme-marketplace-check-for-updates-button = 
    .label = Перевірити наявність оновлень
zen-theme-marketplace-updates-success = Тему успішно оновлено
zen-theme-marketplace-updates-fail = Не знайдено оновлень!
zen-theme-marketplace-toggle-enabled-button = 
    .title = Вимкнути тему
zen-theme-marketplace-toggle-disabled-button = 
    .title = Ввімкнути тему
zen-theme-marketplace-remove-confirmation = Ви впевнені, що хочете видалити цей мод?
zen-theme-marketplace-close-modal = Закрити
zen-theme-marketplace-theme-header-title = 
    .title = Селектор CSS：{ $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = Нічого
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Напишіть щось...
pane-zen-marketplace-title = Модифікації Zen
zen-settings-workspaces-display-as-icon-strip = 
    .label = Показувати робочі області у вигляді смуги значків
zen-theme-marketplace-link = Відвідати магазин
zen-dark-theme-styles-header = Стилі темної теми
zen-dark-theme-styles-description = Налаштуйте темну тему на свій смак
zen-dark-theme-styles-amoled = Нічна тема
zen-dark-theme-styles-default = Типова темна тема
zen-dark-theme-styles-colorful = Кольорова темна тема
zen-compact-mode-styles-left = Приховати панель вкладок
zen-compact-mode-styles-top = Приховати верхню панель
zen-compact-mode-styles-both = Приховати обидві
pane-zen-CKS-title = Комбінації клавіш
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = Комбінації клавіш { -brand-short-name }
zen-settings-CKS-header = Налаштуйте комбінації клавіш
zen-settings-CKS-description = Змініть комбінації клавіш за замовчуванням на свої уподобання та покращить роботу в Інтернеті
zen-settings-CKS-disable-firefox = 
    .label = Вимкнути стандартні комбінації клавіш для { -brand-short-name }
zen-settings-CKS-duplicate-shortcut = 
    .label = Дублювати комбінацію клавіш
zen-settings-CKS-reset-shortcuts = 
    .label = Скинути до типових
zenCKSOption-group-other = Інше
zenCKSOption-group-windowAndTabManagement = Керування вікнами та вкладками
zenCKSOption-group-navigation = Навігація
zenCKSOption-group-searchAndFind = Пошук
zenCKSOption-group-pageOperations = Дії на сторінці
zenCKSOption-group-historyAndBookmarks = Історія та закладки
zenCKSOption-group-mediaAndDisplay = Медіа та показ
zenCKSOption-group-zen-compact-mode = Компактний режим
zenCKSOption-group-zen-workspace = Робочі області
zenCKSOption-group-zen-other = Інші функції Zen
zenCKSOption-group-zen-split-view = Розділений вигляд
zen-key-quick-restart = Швидкий перезапуск
zen-window-new-shortcut = Нове вікно
zen-tab-new-shortcut = Нова вкладка
zen-location-open-shortcut = Відкрити розташування
zen-location-open-shortcut-alt = Відкрити розташування (Alt)
zen-key-undo-close-window = Скасування закриття вікна
zen-text-action-undo-shortcut = Скасувати
zen-text-action-redo-shortcut = Повторити
zen-text-action-cut-shortcut = Вирізати
zen-text-action-copy-shortcut = Копіювати
zen-text-action-paste-shortcut = Вставити
zen-text-action-select-all-shortcut = Вибрати все
zen-text-action-delete-shortcut = Видалити
zen-history-show-all-shortcut-mac = Показати всю історію (Mac)
zen-full-screen-shortcut = Перемкнути повноекранний режим
zen-reader-mode-toggle-shortcut-windows = Перемкнути режим читання (Windows)
zen-picture-in-picture-toggle-shortcut-alt = Перемкнути режим «Картинка в картинці» (Alt)
zen-picture-in-picture-toggle-shortcut-mac = Перемкнути режим «Картинка в картинці» (Mac)
zen-picture-in-picture-toggle-shortcut-mac-alt = Перемкнути режим «Картинка в картинці» (Mac Alt)
zen-page-source-shortcut-safari = Початковий код сторінки (Safari)
zen-nav-stop-shortcut = Зупинити завантаження
zen-history-sidebar-shortcut = Показати бічну панель історії
zen-window-minimize-shortcut = Згорнути вікно
zen-help-shortcut = Відкрити довідку
zen-preferences-shortcut = Відкрити налаштування
zen-hide-app-shortcut = Приховати застосунок
zen-hide-other-apps-shortcut = Приховати інші застосунки
zen-search-focus-shortcut = Пошук у фокусі
zen-search-focus-shortcut-alt = Пошук у фокусі (Alt)
zen-downloads-shortcut = Відкрити завантаження
zen-addons-shortcut = Відкрити доповнення
zen-file-open-shortcut = Відкрити файл
zen-save-page-shortcut = Зберегти сторінку
zen-print-shortcut = Друкувати сторінку
zen-close-shortcut-2 = Закрити вкладку
zen-mute-toggle-shortcut = Ввімк / вимк звук
zen-key-delete = Видалити ключ
zen-key-go-back = Назад
zen-key-go-forward = Вперед
zen-nav-back-shortcut-alt = Перейти назад (Alt)
zen-nav-fwd-shortcut-alt = Перейти вперед (Alt)
zen-history-show-all-shortcut = Показати всю історію
zen-key-enter-full-screen = Перейти в повноекранний режим
zen-key-exit-full-screen = Вийти з повноекранного режиму
zen-reader-mode-toggle-shortcut-other = Перемкнути режим читання
zen-picture-in-picture-toggle-shortcut = Перемкнути режим «Картинка в картинці»
zen-nav-reload-shortcut-2 = Перезавантажити сторінку
zen-key-about-processes = Про процеси
zen-page-source-shortcut = Початковий код сторінки
zen-page-info-shortcut = Інформація про сторінку
zen-find-shortcut = Знайти на сторінці
zen-search-find-again-shortcut = Знайти наступне
zen-search-find-again-shortcut-prev = Знайти попереднє
zen-search-find-again-shortcut-2 = Знайти наступне (Alt)
zen-bookmark-this-page-shortcut = Додати сторінку до закладок
zen-bookmark-show-library-shortcut = Показати бібліотеку закладок
zen-key-stop = Зупинити завантаження
zen-full-zoom-reduce-shortcut = Зменшити
zen-full-zoom-enlarge-shortcut = Збільшити
zen-full-zoom-reset-shortcut = Скинути масштаб
zen-bidi-switch-direction-shortcut = Змінити напрям тексту сторінки
zen-private-browsing-shortcut = Приватний перегляд
zen-screenshot-shortcut = Зробити знімок екрана
zen-key-sanitize = Очистити дані перегляду
zen-quit-app-shortcut = Вийти із застосунку
zen-key-wr-capture-cmd = Команда захоплення WR
zen-key-wr-toggle-capture-sequence-cmd = Перемкнути послідовність захоплення WR
zen-nav-reload-shortcut = Перезавантажити сторінку
zen-nav-reload-shortcut-skip-cache = Перезавантажити сторінку (пропустити кеш)
zen-close-shortcut = Зачинити вікно
zen-close-tab-shortcut = Закрити вкладку
zen-compact-mode-shortcut-show-sidebar = Перемкнути спливну бічну панель
zen-compact-mode-shortcut-show-toolbar = Перемкнути спливну панель інструментів
zen-compact-mode-shortcut-toggle = Перемикнути компактний режим
zen-workspace-shortcut-switch-1 = Перейти на робочу область 1
zen-workspace-shortcut-switch-2 = Перейти на робочу область 2
zen-workspace-shortcut-switch-3 = Перейти на робочу область 3
zen-workspace-shortcut-switch-4 = Перейти на робочу область 4
zen-workspace-shortcut-switch-5 = Перейти на робочу область 5
zen-workspace-shortcut-switch-6 = Перейти на робочу область 6
zen-workspace-shortcut-switch-7 = Перейти на робочу область 7
zen-workspace-shortcut-switch-8 = Перейти на робочу область 8
zen-workspace-shortcut-switch-9 = Перейти на робочу область 9
zen-workspace-shortcut-switch-10 = Перейти на робочу область 10
zen-workspace-shortcut-forward = Наступна робоча область
zen-workspace-shortcut-backward = Попередня робоча область
zen-web-panel-shortcut-toggle = Перемикання вебпанелі
zen-sidebar-shortcut-toggle = Змінити ширину бічної панелі
zen-split-view-shortcut-grid = Перемикання розділеної сітки перегляду
zen-split-view-shortcut-vertical = Перемкнути розділений перегляд по вертикалі
zen-split-view-shortcut-horizontal = Перемкнути розділений перегляд по горизонталі
zen-split-view-shortcut-unsplit = Закрити розділений вигляд
zen-key-select-tab-1 = Вибрати вкладку #1
zen-key-select-tab-2 = Вибрати вкладку #2
zen-key-select-tab-3 = Вибрати вкладку #3
zen-key-select-tab-4 = Вибрати вкладку #4
zen-key-select-tab-5 = Вибрати вкладку #5
zen-key-select-tab-6 = Вибрати вкладку #6
zen-key-select-tab-7 = Вибрати вкладку #7
zen-key-select-tab-8 = Вибрати вкладку #8
zen-key-select-tab-last = Вибрати останню вкладку
zen-key-show-all-tabs = Показати всі вкладки
zen-key-goto-history = Перейти до історії
zen-key-go-home = На головну
zen-bookmark-show-sidebar-shortcut = Показати бічну панель закладок
zen-bookmark-show-toolbar-shortcut = Показати бічну панель інструментів
