zen-panel-ui-current-profile-text = praegune profiil
unified-extensions-description = Laiendusi kasutatakse täiendava funktsionaalsuse lisamiseks { -brand-short-name }i.
tab-context-zen-reset-pinned-tab = 
    .label = Lähtesta püsikaart
    .accesskey = L
tab-context-zen-add-essential = 
    .label = Lisa olulistesse
    .accesskey = o
tab-context-zen-remove-essential = 
    .label = Eemalda olulistest
    .accesskey = E
tab-context-zen-replace-pinned-url-with-current = 
    .label = Asenda püsikaardi URL praegusega
    .accesskey = A
tab-zen-unload = 
    .label = Eemalda kaart mälust
    .accesskey = m
zen-tabs-unloader-tab-actions = 
    .label = Kaartide mälust eemaldamise tegevused
    .accesskey = K
tab-zen-prevent-unload = 
    .label = Tõkesta kaardi mälust eemaldamine
    .accesskey = T
tab-zen-ignore-unload = 
    .label = Luba kaardi mälust eemaldamine
    .accesskey = L
zen-themes-corrupted = Sinu { -brand-short-name } muudatuste fail on vigane. See on nüüd lähtestatud vaikimisi teemaks.
zen-panel-ui-gradient-generator-opacity-text = Kontrast
zen-panel-ui-gradient-generator-texture-text = Tekstuur
zen-panel-ui-gradient-generator-custom-color = Kohandatud värv
zen-panel-ui-gradient-generator-saved-message = Värviüleminek on edukalt salvestatud!
zen-copy-current-url-confirmation = URL kopeeriti lõikelauale.
zen-rice-share-name = 
    .placeholder = Rice Name
zen-rice-share-author = By
zen-rice-share-author-input = 
    .placeholder = Your Name
zen-rice-share-cancel = Cancel
zen-rice-share-save = Share
zen-rice-share-include-userchrome = 
    .label = Include userChrome.css
zen-rice-share-include-usercontent = 
    .label = Include userContent.css
zen-rice-share-include-mods = 
    .label = Include enabled mods
zen-rice-share-include-mod-prefs = 
    .label = Include mod preferences
zen-rice-share-include-preferences = 
    .label = Include layout state
zen-rice-share-include-workspace-themes = 
    .label = Include workspace gradient themes
zen-rice-share-include = Export Options
appmenu-zen-share-rice = 
    .label = Share Zen Rice
