zen-panel-ui-workspaces-text = Tööruumid
zen-panel-ui-workspaces-create-text = Loo tööruum
zen-panel-ui-workspaces-create-save = 
    .label = Loo tööruum
    .accesskey = L
zen-panel-ui-workspaces-create-cancel = 
    .label = Tühista
    .accesskey = T
zen-panel-ui-workspaces-edit-text = Muuda tööruumi
zen-panel-ui-workspaces-edit-save = 
    .label = Salvesta muudatused
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Tühista
    .accesskey = T
zen-workspaces-panel-context-delete = 
    .label = Kustuta tööruum
    .accesskey = K
zen-workspaces-panel-change-name = 
    .label = Change Name
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Määra vaikimisi konteineriks
    .accesskey = v
zen-workspaces-change-gradient = 
    .label = Muuda teema värve
    .accesskey = v
zen-workspaces-panel-context-open = 
    .label = Open Workspace
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Set As Default Workspace
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Edit Workspace
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Change Tab(s) To Workspace
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Tööruumid
    .accesskey = T
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Complementary
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Split
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Analogous
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Triadic
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Floating
zen-panel-ui-gradient-click-to-add = Click to add a color
