zen-panel-ui-current-profile-text = praegune profiil
unified-extensions-description = Laiendusi kasutatakse täiendava funktsionaalsuse lisamiseks { -brand-short-name }i.
tab-context-zen-reset-pinned-tab = 
    .label = Lähtesta püsikaart
    .accesskey = L
tab-context-zen-add-essential = 
    .label = Lisa olulistesse
    .accesskey = o
tab-context-zen-remove-essential = 
    .label = Eemalda olulistest
    .accesskey = E
tab-context-zen-replace-pinned-url-with-current = 
    .label = Asenda püsikaardi URL praegusega
    .accesskey = A
tab-zen-unload = 
    .label = Eemalda kaart mälust
    .accesskey = m
zen-tabs-unloader-tab-actions = 
    .label = Kaartide mälust eemaldamise tegevused
    .accesskey = K
tab-zen-prevent-unload = 
    .label = Tõkesta kaardi mälust eemaldamine
    .accesskey = T
tab-zen-ignore-unload = 
    .label = Luba kaardi mälust eemaldamine
    .accesskey = L
zen-themes-corrupted = Sinu { -brand-short-name } Mods fail on vigane. See on nüüd lähtestatud vaikimisi teemaks.
zen-panel-ui-gradient-generator-opacity-text = Kontrast
zen-panel-ui-gradient-generator-texture-text = Tekstuur
zen-panel-ui-gradient-generator-custom-color = Kohandatud värv
zen-panel-ui-gradient-generator-saved-message = Värviüleminek on edukalt salvestatud!
