zen-panel-ui-current-profile-text = praegune profiil
unified-extensions-description = Laiendusi kasutatakse täiendava funktsionaalsuse lisamiseks { -brand-short-name }i.
tab-context-zen-reset-pinned-tab = 
    .label = Lähtesta püsikaart
    .accesskey = L
tab-context-zen-add-essential = 
    .label = Lisa olulistesse
    .accesskey = o
tab-context-zen-remove-essential = 
    .label = Eemalda olulistest
    .accesskey = E
tab-context-zen-replace-pinned-url-with-current = 
    .label = Asenda püsikaardi URL praegusega
    .accesskey = A
tab-zen-unload = 
    .label = Eemalda kaart mälust
    .accesskey = m
zen-tabs-unloader-tab-actions = 
    .label = Kaartide mälust eemaldamise tegevused
    .accesskey = K
tab-zen-prevent-unload = 
    .label = Tõkesta kaardi mälust eemaldamine
    .accesskey = T
tab-zen-ignore-unload = 
    .label = Luba kaardi mälust eemaldamine
    .accesskey = L
zen-themes-corrupted = Sinu { -brand-short-name } muudatuste fail on vigane. See on nüüd lähtestatud vaikimisi teemaks.
zen-panel-ui-gradient-generator-opacity-text = Kontrast
zen-panel-ui-gradient-generator-texture-text = Tekstuur
zen-panel-ui-gradient-generator-custom-color = Kohandatud värv
zen-panel-ui-gradient-generator-saved-message = Värviüleminek on edukalt salvestatud!
zen-copy-current-url-confirmation = URL kopeeriti lõikelauale.
zen-rice-share-name = 
    .placeholder = Muganduse Nimi
zen-rice-share-author = -
zen-rice-share-author-input = 
    .placeholder = Sinu Nimi
zen-rice-share-cancel = Tühista
zen-rice-share-save = Jaga
zen-rice-share-include-userchrome = 
    .label = Include zen window styles (userChrome.css)
zen-rice-share-include-usercontent = 
    .label = Include website styles (userContent.css)
zen-rice-share-include-mods = 
    .label = Kaasa lubatud muudatused
zen-rice-share-include-mod-prefs = 
    .label = Kaasa muudatuste eelistused
zen-rice-share-include-preferences = 
    .label = Include layout preferences
zen-rice-share-include-workspace-themes = 
    .label = Kaasa tööruumi värviüleminekute teemad
zen-rice-share-success = Mugandus on loodud!
zen-rice-share-success-link = Jagamise link
zen-rice-share-accept = Accept
zen-rice-share-notice = Before sharing, please understand what a Rice is
zen-rice-share-notice-details =
    A Rice is a collection of customizations that can be shared with others.
    This includes your window styles, website styles, enabled mods, mod preferences, layout preferences, and workspace gradient themes.
    By sharing a Rice, you are sharing all of these customizations with others. Please be mindful of what you share.
zen-learn-more-text = Learn More
zen-rice-share-include = Eksportimise valikud
appmenu-zen-share-rice = 
    .label = Jaga Zen-i mugandust
zen-close-label = Sulge
