zen-panel-ui-workspaces-text = Tööruumid
zen-panel-ui-workspaces-create-text = Loo tööruum
zen-panel-ui-workspaces-create-save = 
    .label = Loo tööruum
    .accesskey = L
zen-panel-ui-workspaces-create-cancel = 
    .label = Tühista
    .accesskey = T
zen-panel-ui-workspaces-edit-text = Muuda tööruumi
zen-panel-ui-workspaces-edit-save = 
    .label = Salvesta muudatused
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Tühista
    .accesskey = T
zen-workspaces-panel-context-delete = 
    .label = Kustuta tööruum
    .accesskey = K
zen-workspaces-panel-context-open = 
    .label = Ava tööruum
    .accesskey = A
zen-workspaces-panel-context-set-default = 
    .label = Määra vaikimisi tööruumiks
    .accesskey = v
zen-workspaces-panel-context-edit = 
    .label = Muuda tööruumi
    .accesskey = M
context-zen-change-workspace-tab = 
    .label = Liiguta kaardid tööruumi
    .accesskey = L
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Määra vaikimisi konteineriks
    .accesskey = v
zen-workspaces-change-gradient = 
    .label = Muuda teema värve
    .accesskey = v
zen-bookmark-edit-panel-workspace-selector = 
    .value = Tööruumid
    .accesskey = T
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Complementary
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Split
zen-panel-ui-gradient-generator-algo-analogous = Analogous
    .label = Analogous
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Triadic
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Floating
