pane-zen-looks-title = Görünüm ve His
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Varsayılan dili değiştirmek, websitelerin sizi izlemesini kolaylaştırabilir.
zen-look-and-feel-colors-header = Bir tema rengi seç
zen-look-and-feel-colors-description = { -brand-short-name } istediğin görünüm ve hisse kavuştur
zen-look-and-feel-themed-toolbar = 
    .label = Araç çubuğunu vurgu rengiyle temalı hale getir
pane-zen-side-panels-title = Yan Web Panelleri
zen-side-panels-header = Web panelleri için genel ayarlar
zen-side-panels-description = Birden fazla görünümü aynı anda kullanarak üretkenliğini artır!
zen-side-panels-enabled = 
    .label = Yan Web Panellerini Etkinleştir
zen-side-panels-close-on-blur = 
    .label = Eğer panel sabitlenmemişse ve odağı kaybetmişse paneli kapat
zen-look-and-feel-compact-view-header = Kompakt görünümde göster
zen-look-and-feel-compact-view-description = Sadece kullandığın araç çubuklarını göster!
zen-look-and-feel-compact-view-enabled = 
    .label = { -brand-short-name }'in kompakt modunu aktifleştir
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Kompakt modda üst araç çubuğunu gizle
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Kompakt modda yeni sekmeler arasında geçiş yaparken veya yeni sekmeler açarken araç çubuğunun açılır penceresini aktif edin
zen-look-and-feel-buttons-header = Buton tarzı
zen-look-and-feel-buttons-description = Görmek istediğin buton tarzını seç
zen-look-and-feel-pilled-buttons = 
    .label = Hap Şeklinde Butonlar
pane-zen-workspaces-title = Çalışma Alanları
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = Çalışma Alanları
pane-zen-workspaces-header = Çalışma Alanları
zen-settings-workspaces-header = Çalışma alanları için genel ayarlar
zen-settings-workspaces-description = Çalışma alanları sayesinde birden fazla göz atma oturumuna aynı anda sahip olabilirsin!
zen-settings-workspaces-enabled = 
    .label = Çalışma Alanlarını Aktif Et (Deneysel)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Sekme çubuğundaki varsayılan konteyner göstergesini gizle
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Çalışma alanlarına özel sabitli sekmelere izin verin
pane-zen-theme-title = Tema Ayarları
zen-vertical-tabs-title = Kenar çubuğu ve sekme düzeni
zen-vertical-tabs-header = Dikey Sekmeler
zen-vertical-tabs-description = Sekmelerini dikey düzende yönet
zen-vertical-tabs-show-expand-button = 
    .label = Genişlet Düğmesini Göster
zen-vertical-tabs-expand-tabs-by-default = Varsayılan Olarak Sekmeleri Genişlet
zen-vertical-tabs-dont-expand-tabs-by-default = Varsayılan Olarak Sekmeler Geniş Olmasın
zen-vertical-tabs-expand-tabs-on-hover = Sekmeleri Fareyle Üzerine Gelince Göster (Kompakt modda çalışmaz)
zen-vertical-tabs-expand-tabs-header = Sekmeler nasıl genişletilir
zen-vertical-tabs-expand-tabs-description = Kenar çubuğunda sekmelerin nasıl genişletileceğini seç
zen-theme-marketplace-header = Zen Modları
zen-theme-marketplace-description = Mağazadan tema bul ve indir.
zen-theme-marketplace-remove-button = 
    .label = Temayı Kaldır
zen-theme-marketplace-check-for-updates-button = 
    .label = Güncellemeleri Kontrol Et
zen-theme-marketplace-updates-success = Tema başarıyla güncellendi
zen-theme-marketplace-updates-fail = Yeni güncelleme bulunamadı!
zen-theme-marketplace-toggle-enabled-button = 
    .title = Disable Theme
zen-theme-marketplace-toggle-disabled-button = 
    .title = Enable Theme
zen-theme-marketplace-remove-confirmation = Are you sure you want to remove this theme?
zen-theme-marketplace-close-modal = Close
zen-theme-marketplace-theme-header-title = 
    .title = CSS Selector: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = None
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Type something...
pane-zen-marketplace-title = Zen Modları
zen-settings-workspaces-display-as-icon-strip = 
    .label = Display workspaces as an icon strip
zen-theme-marketplace-link = Mağazayı Ziyaret Et
zen-dark-theme-styles-header = Koyu Tema Stilleri
zen-dark-theme-styles-description = Koyu temayı tercihlerinize göre özelleştirin
zen-dark-theme-styles-amoled = Gece Teması
zen-dark-theme-styles-default = Varsayılan Koyu Tema
zen-dark-theme-styles-colorful = Renkli Koyu Tema
zen-compact-mode-styles-left = Hide Tab bar
zen-compact-mode-styles-top = Hide Top bar
zen-compact-mode-styles-both = Hide Both
pane-zen-CKS-title = Klavye Kısayolları
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } Klavye Kısayolları
zen-settings-CKS-header = Klavye kısayollarını kişiselleştir
zen-settings-CKS-description = Varsayılan klavye kısayollarını kendi zevkine göre değiştir ve göz atma deneyimini geliştir
zen-settings-CKS-disable-firefox = 
    .label = { -brand-short-name } varsayılan klavye kısayollarını devre dışı bırak
zen-cks-group-tab-action = Sekme Eylemleri
zen-cks-group-page-action = Sayfa Eylemleri
zen-cks-group-visible-action = Görünür Eylemler
zen-cks-group-history-action = Geçmiş Eylemeri
zen-cks-group-search-action = Arama Eylemleri
zen-cks-group-tools-action = Araç Eylemleri
zen-cks-group-bookmark-action = Yer İşaretleri Eylemleri
zen-cks-group-open-page-action = Sayfa Açma Eylemleri
zen-cks-group-downloads-action = İndirilenler Eylemleri
zen-cks-group-sidebar-action = Kenar Çubuğu Eylemleri
zen-cks-group-compact-mode-action = Kompakt Mod Eylemleri
zen-cks-group-split-view-action = Bölünmüş Görünüm Eylemleri
zen-cks-group-workspace-action = Çalışma Alanı Eylemleri
open-new-tab = Yeni Sekme Aç
close-tab = Sekmeyi Kapat
open-new-window = Yeni Pencere Aç
open-new-private-window = Yeni Gizli Pencere Aç
close-window = Pencereyi Kapat
restore-last-tab = Son Sekmeyi Geri Getir
restore-last-window = Son Pencereyi Geri Getir
show-next-tab = Sonraki Sekmeyi Göster
show-previous-tab = Önceki Sekmeyi Göster
show-all-tabs-panel = Tüm Sekmeler Panelini Göster
send-with-mail = Sayfayı Postayla Gönder
save-page = Sayfayı Kaydet
print-page = Sayfayı Yazdır
mute-current-tab = Geçerli Sekmenin Sesini Kapat
show-source-of-page = Sayfa Kaynağını Göster
show-page-info = Sayfa Bilgilerini Göster
zoom-in = Yakınlaştır
zoom-out = Uzaklaştır
reset-zoom = Yakınlaştırmayı Sıfırla
back = Geri
forward = İleri
stop = Dur
reload = Yenile
force-reload = Yeniden Yüklemeye Zorla
search-in-this-page = Bu Sayfada Ara
show-next-search-result = Sonraki Arama Sonucunu Göster
show-previous-search-result = Önceki Arama Sonucunu Göster
search-the-web = İnternette arama yap
open-migration-wizard = Göç Sihirbazını Aç
quit-from-application = Uygulamayı Kapat
enter-into-customize-mode = Kişiselleştirme Moduna Gir
enter-into-offline-mode = Çevrimdışı Moda Gir
open-screen-capture = Ekran Kaydetmeyi Aç
bookmark-this-page = Bu Sayfayı Yer İşaretlerine Ekle
open-bookmark-add-tool = Yer İşareti Ekleme Aracını Aç
open-bookmarks-manager = Yer İşareti Yöneticisini Aç
toggle-bookmark-toolbar = Yer İşaretleri Araç Çubuğunu Aç/Kapat
open-general-preferences = Genel Tercihleri Aç
open-privacy-preferences = Gizlilik Tercihlerini Aç
open-workspaces-preferences = Çalışma Alanları Tercihlerini Aç
open-containers-preferences = Konteyner Tercihlerini Aç
open-search-preferences = Arama Tercihlerini Aç
open-sync-preferences = Senkronizasyon Tercihlerini Aç
open-task-manager = Görev Yöneticisini Aç
open-addons-manager = Eklenti Yöneticisini Aç
open-home-page = Ana Sayfayı Aç
forget-history = Geçmişi Unut
quick-forget-history = Geçmişi Hemen Unut
clear-recent-history = Yakın Geçmişi Temizle
restore-last-session = Son Oturumu Geri Yükle
search-history = Arama Geçmişi
manage-history = Geçmişi Yönet
open-downloads = İndirilenleri Aç
show-bookmark-sidebar = Yer İşaretleri Kenar Çubuğunu Göster
show-history-sidebar = Geçmiş Kenar Çubuğunu Göster
show-synced-tabs-sidebar = Senkronize Edilmiş Sekmeler Kenar Çubuğunu Göster
reverse-sidebar = Kenar Çubuğu Konumunu Ters Çevir
hide-sidebar = Kenar Çubuğunu Gizle
toggle-sidebar = Kenar Çubuğunu Aç/Kapat
zen-toggle-web-panels = Web Panelleri Arasında Geçiş Yap
zen-toggle-compact-mode = Kompakt Modunu Aç/Kapat
zen-toggle-compact-mode-sidebar = Kompakt Mod Kenar Çubuğunu Aç/Kapat
zen-toggle-compact-mode-toolbar = Kompakt Mod Araç Çubuğunu Aç/Kapat
zen-change-workspace = Çalışma Alanları Arasında Geçiş Yap
zen-split-view-grid = Izgaralı Bölünmüş Görünüm
zen-split-view-vertical = Dikey Bölünmüş Görünüm
zen-split-view-horizontal = Yatay Bölünmüş Görünüm
zen-split-view-close = Bölünmüş Görünümü Kapat
zen-expand-sidebar = Kenar Çubuğu Genişletmesini Aç/Kapat
