pane-zen-looks-title = Look and Feel
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Changing the default language could make it easier for Websites to track you.
zen-look-and-feel-colors-header = Pick a theme colour
zen-look-and-feel-colors-description = Make { -brand-short-name } look and feel the way you like
zen-look-and-feel-themed-toolbar = 
    .label = Make the toolbar themed with the accent color
pane-zen-side-panels-title = Side Web Panels
zen-side-panels-header = General settings for web panels
zen-side-panels-description = Increase productivity by having multiple views at once!
zen-side-panels-enabled = 
    .label = Enable Web Side Panels
zen-side-panels-close-on-blur = 
    .label = Close the panel when it loses focus if it's not pinned
zen-look-and-feel-compact-view-header = Show in compact view
zen-look-and-feel-compact-view-description = Only show the toolbars you use!
zen-look-and-feel-compact-view-enabled = 
    .label = Enable { -brand-short-name }'s compact mode
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Hide the top toolbar as well in compact mode
zen-look-and-feel-buttons-header = Button style
zen-look-and-feel-buttons-description = Choose the style of buttons you want to see
zen-look-and-feel-pilled-buttons = 
    .label = Pilled Buttons
pane-zen-workspaces-title = Workspaces
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = Workspaces
pane-zen-workspaces-header = Workspaces
zen-settings-workspaces-header = General settings for workspaces
zen-settings-workspaces-description = With workspaces, you can have multiple browsing sessions at once!
zen-settings-workspaces-enabled = 
    .label = Çalışma Alanlarını Aktif Et (Deneysel)
pane-zen-theme-title = Theme Settings
zen-vertical-tabs-title = Sidebar and tabs layout
zen-vertical-tabs-header = Vertical Tabs
zen-vertical-tabs-description = Manage your tabs in a vertical layout
zen-vertical-tabs-show-expand-button = 
    .label = Show Expand Button
zen-vertical-tabs-expand-tabs-by-default = Expand Tabs by Default
zen-vertical-tabs-dont-expand-tabs-by-default = Don't Expand Tabs by Default
zen-vertical-tabs-expand-tabs-on-hover = Expand Tabs on Hover (Wont work on compact mode)
zen-vertical-tabs-expand-tabs-header = How to expand tabs
zen-vertical-tabs-expand-tabs-description = Choose how to expand tabs in the sidebar
zen-theme-marketplace-header = Theme Store
zen-theme-marketplace-description = Find and install themes from the store.
zen-theme-marketplace-remove-button = 
    .label = Temayı Kaldır
zen-theme-marketplace-link = Visit Store
pane-zen-CKS-title = Klavye Kısayolları
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } Keyboard Shortcuts
zen-settings-CKS-header = Klavye kısayollarınızı kişiselleştirin
zen-settings-CKS-description = Change the default keyboard shortcuts to your liking and improve your browsing experience
zen-settings-CKS-disable-firefox = 
    .label = Disable { -brand-short-name }'s default keyboard shortcuts
zen-cks-group-tab-action = Sekme Aksiyonları
zen-cks-group-page-action = Page Actions
zen-cks-group-visible-action = Görünen Aksiyonlar
zen-cks-group-history-action = Geçmiş Aksiyonları
zen-cks-group-search-action = Arama Aksiyonları
zen-cks-group-tools-action = Araç Aksiyonları
zen-cks-group-bookmark-action = Yer İşaretleri Aksiyonları
zen-cks-group-open-page-action = Sayfa Açma Aksiyonları
zen-cks-group-downloads-action = İndirilenler Aksiyonları
zen-cks-group-sidebar-action = Yan Çubuk Aksiyonları
zen-cks-group-compact-mode-action = Kompakt Modu Aksiyonları
zen-cks-group-split-view-action = Bölünmüş Görünüm Aksiyonları
zen-cks-group-workspace-action = Çalışma Alanı Aksiyonları
open-new-tab = Yeni Sekme Aç
close-tab = Sekmeyi Kapat
open-new-window = Yeni Pencere Aç
open-new-private-window = Yeni Gizli Pencere Aç
close-window = Pencereyi Kapat
restore-last-tab = En Sonki Sekmeleri Yenile
restore-last-window = En Sonki Pencereyi Yenile
show-next-tab = İlerideki Sekmeyi Göster
show-previous-tab = Gerideki Sekmeyi Göster
show-all-tabs-panel = Tüm Sekmeler Panelini Göster
send-with-mail = Mail Kullanarak Sayfayı Gönder
save-page = Sayfayı Kaydet
print-page = Sayfayı Yazdır
mute-current-tab = Mevcut Sekmeyi Sessize Al
show-source-of-page = Sayfanın Kaynağını Göster
show-page-info = Sayfanın Bilgilerini Göster
zoom-in = Yakınlaştır
zoom-out = Uzaklaştır
reset-zoom = Yakınlaştırmayı Sıfırla
back = Geri
forward = İleri
stop = Dur
reload = Yenile
force-reload = Yenilemeyi Zorla
search-in-this-page = Bu Sayfada Ara
show-next-search-result = Sıradaki Arama Sonucunu Göster
show-previous-search-result = Önceki Arama Sonucunu Göster
search-the-web = Web'i Ara
open-migration-wizard = Taşıma Sihirbazını Aç
quit-from-application = Uygulamayı Kapat
enter-into-customize-mode = Kişiselleştirme Moduna Gir
enter-into-offline-mode = Çevrimdışı Moduna Gir
open-screen-capture = Ekran Kaydetmeyi Aç
bookmark-this-page = Bu Sayfayı Yer İşaretlerine Ekle
open-bookmark-add-tool = Yer İşareti Ekleme Aracını Aç
open-bookmarks-manager = Yer İşareti Yöneticisini Aç
toggle-bookmark-toolbar = Yer İşaretleri Araç Çubuğunu Aç/Kapat
open-general-preferences = Genel Tercihleri Aç
open-privacy-preferences = Gizlilik Tercihlerini Aç
open-workspaces-preferences = Çalışma Alanları Tercihlerini Aç
open-containers-preferences = Konteyner Tercihlerini Aç
open-search-preferences = Arama Tercihlerini Aç
open-sync-preferences = Senkronizasyon Tercihlerini Aç
open-task-manager = Görev Yöneticisini Aç
open-addons-manager = Eklentiler Yöneticisini Aç
open-home-page = Ana Sayfayı Aç
forget-history = Geçmişi Unut
quick-forget-history = Geçmişi Hemen Unut
clear-recent-history = Yakın Geçmişi Temizle
restore-last-session = Son Oturumu Geri Yükle
search-history = Arama Geçmişi
manage-history = Geçmişi Yönet
open-downloads = İndirilenleri Aç
show-bookmark-sidebar = Yer İşaretleri Yan Panelini Göster
show-history-sidebar = Geçmiş Yan Panelini Göster
show-synced-tabs-sidebar = Sekronize Edilmiş Sekmeleri Göster
reverse-sidebar = Yan Paneli Konumunu Geri Çevir
hide-sidebar = Yan Paneli Gizle
toggle-sidebar = Yan Paneli Aç/Kapat
zen-toggle-web-panels = Web Panelleri Arasında Geçiş Yap
zen-toggle-compact-mode = Kompakt Modunu Aç/Kapat
zen-toggle-compact-mode-sidebar = Kompakt Modu Yan Panelini Aç/Kapat
zen-toggle-compact-mode-toolbar = Kompakt Modu Araç Çubuğunu Aç/Kapat
zen-change-workspace = Çalışma Alanları Arasında Geçiş Yap
zen-split-view-grid = Izgaralı Bölünmüş Görünüm
zen-split-view-vertical = Dikey Bölünmüş Görünüm
zen-split-view-horizontal = Yatay Bölünmüş Görünüm
zen-split-view-close = Bölünmüş Görünümü Kapat
