pane-zen-looks-title = Görünüm ve His
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Varsayılan dili değiştirmek, websitelerin sizi izlemesini kolaylaştırabilir.
zen-look-and-feel-colors-header = Bir tema rengi seç
zen-look-and-feel-colors-description = { -brand-short-name } istediğin görünüm ve hisse kavuştur
zen-look-and-feel-themed-toolbar = 
    .label = Araç çubuğunu vurgu rengiyle temalı hale getir
pane-zen-side-panels-title = Yan Web Panelleri
zen-side-panels-header = Web panelleri için genel ayarlar
zen-side-panels-description = Birden fazla görünümü aynı anda kullanarak üretkenliğini artır!
zen-side-panels-enabled = 
    .label = Yan Web Panellerini Etkinleştir
zen-side-panels-close-on-blur = 
    .label = Eğer panel sabitlenmemişse ve odağı kaybetmişse paneli kapat
zen-look-and-feel-compact-view-header = Kompakt görünümde göster
zen-look-and-feel-compact-view-description = Sadece kullandığın araç çubuklarını göster!
zen-look-and-feel-compact-view-enabled = 
    .label = { -brand-short-name }'in kompakt modunu aktifleştir
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Kompakt modda üst araç çubuğunu gizle
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Kompakt modda yeni sekmeler arasında geçiş yaparken veya yeni sekmeler açarken araç çubuğunun açılır penceresini aktif edin
zen-look-and-feel-buttons-header = Buton tarzı
zen-look-and-feel-buttons-description = Görmek istediğin buton tarzını seç
zen-look-and-feel-pilled-buttons = 
    .label = Hap Şeklinde Butonlar
pane-zen-workspaces-title = Çalışma Alanları
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = Çalışma Alanları
pane-zen-workspaces-header = Çalışma Alanları
zen-settings-workspaces-header = Çalışma alanları için genel ayarlar
zen-settings-workspaces-description = Çalışma alanları sayesinde birden fazla göz atma oturumuna aynı anda sahip olabilirsin!
zen-settings-workspaces-enabled = 
    .label = Çalışma Alanlarını Aktif Et (Deneysel)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Sekme çubuğundaki varsayılan konteyner göstergesini gizle
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Çalışma alanlarına özel sabitli sekmelere izin verin
pane-zen-theme-title = Tema Ayarları
zen-vertical-tabs-title = Kenar çubuğu ve sekme düzeni
zen-vertical-tabs-header = Dikey Sekmeler
zen-vertical-tabs-description = Sekmelerini dikey düzende yönet
zen-vertical-tabs-show-expand-button = 
    .label = Genişlet Düğmesini Göster
zen-vertical-tabs-expand-tabs-by-default = Varsayılan Olarak Sekmeleri Genişlet
zen-vertical-tabs-dont-expand-tabs-by-default = Varsayılan Olarak Sekmeler Geniş Olmasın
zen-vertical-tabs-expand-tabs-on-hover = Sekmeleri Fareyle Üzerine Gelince Göster (Kompakt modda çalışmaz)
zen-vertical-tabs-expand-tabs-header = Sekmeler nasıl genişletilir
zen-vertical-tabs-expand-tabs-description = Kenar çubuğunda sekmelerin nasıl genişletileceğini seç
zen-theme-marketplace-header = Zen Modları
zen-theme-marketplace-description = Mağazadan tema bul ve indir.
zen-theme-marketplace-remove-button = 
    .label = Temayı Kaldır
zen-theme-marketplace-check-for-updates-button = 
    .label = Güncellemeleri Kontrol Et
zen-theme-marketplace-updates-success = Tema başarıyla güncellendi
zen-theme-marketplace-updates-fail = Yeni güncelleme bulunamadı!
zen-theme-marketplace-toggle-enabled-button = 
    .title = Temayı Devre Dışı Bırak
zen-theme-marketplace-toggle-disabled-button = 
    .title = Temayı Aktif Et
zen-theme-marketplace-remove-confirmation = Bu modu kaldırmak istediğinizden emin misiniz?
zen-theme-marketplace-close-modal = Kapat
zen-theme-marketplace-theme-header-title = 
    .title = CSS Seçici: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = Hiçbiri
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Bir şey yazın...
pane-zen-marketplace-title = Zen Modları
zen-settings-workspaces-display-as-icon-strip = 
    .label = Çalışma alanlarını simge şeridi olarak görüntüle
zen-theme-marketplace-link = Mağazayı Ziyaret Et
zen-dark-theme-styles-header = Koyu Tema Stilleri
zen-dark-theme-styles-description = Koyu temayı tercihlerinize göre özelleştirin
zen-dark-theme-styles-amoled = Gece Teması
zen-dark-theme-styles-default = Varsayılan Koyu Tema
zen-dark-theme-styles-colorful = Renkli Koyu Tema
zen-compact-mode-styles-left = Dikey sekmeleri gizle
zen-compact-mode-styles-top = Üst çubuğu gizle
zen-compact-mode-styles-both = Her iksini de gizle
pane-zen-CKS-title = Klavye Kısayolları
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } Klavye Kısayolları
zen-settings-CKS-header = Klavye kısayollarını kişiselleştir
zen-settings-CKS-description = Varsayılan klavye kısayollarını kendi zevkine göre değiştir ve göz atma deneyimini geliştir
zen-settings-CKS-disable-firefox = 
    .label = { -brand-short-name } varsayılan klavye kısayollarını devre dışı bırak
zen-settings-CKS-duplicate-shortcut = 
    .label = Duplicate Shortcut
zenCKSOption-group-other = Diğer
zenCKSOption-group-windowAndTabManagement = Pencere ve Sekme Yönetimi
zenCKSOption-group-navigation = Navigation
zenCKSOption-group-searchAndFind = Ara ve Bul
zenCKSOption-group-pageOperations = Page Operations
zenCKSOption-group-historyAndBookmarks = Geçmiş ve Yer İmleri
zenCKSOption-group-mediaAndDisplay = Medya ve Görüntü
zenCKSOption-group-zen-compact-mode = Kompakt Mod
zenCKSOption-group-zen-workspace = Çalışma Alanları
zenCKSOption-group-zen-other = Diğer Zen Özellikleri
zenCKSOption-group-zen-split-view = Split View
zen-key-quick-restart = Hızlı Yeniden Başlatma
zen-window-new-shortcut = Yeni Pencere
zen-tab-new-shortcut = Yeni Sekme
zen-location-open-shortcut = Open Location
zen-location-open-shortcut-alt = Open Location (Alt)
zen-search-focus-shortcut = Focus Search
zen-search-focus-shortcut-alt = Focus Search (Alt)
zen-downloads-shortcut = İndirmeleri Aç
zen-addons-shortcut = Eklentileri Aç
zen-file-open-shortcut = Dosya Aç
zen-save-page-shortcut = Sayfayı Kaydet
zen-print-shortcut = Sayfayı Yazdır
zen-close-shortcut-2 = Sekmeyi Kapat
zen-mute-toggle-shortcut = Susturmayı Aç/Kapat
zen-key-delete = Tuşu Sil
zen-key-go-back = Geri Git
zen-key-go-forward = İleri Git
zen-nav-back-shortcut-alt = Navigate Back (Alt)
zen-nav-fwd-shortcut-alt = Navigate Forward (Alt)
zen-history-show-all-shortcut = Show All History
zen-key-enter-full-screen = Enter Full Screen
zen-key-exit-full-screen = Exit Full Screen
zen-reader-mode-toggle-shortcut-other = Toggle Reader Mode
zen-picture-in-picture-toggle-shortcut = Toggle Picture-in-Picture
zen-nav-reload-shortcut-2 = Sayfayı Yenile
zen-key-about-processes = About Processes
zen-page-source-shortcut = Sayfa Kaynağını Görüntüle
zen-page-info-shortcut = Sayfa Detaylarını Görüntüle
zen-find-shortcut = Sayfada Bul
zen-search-find-again-shortcut = Find Again
zen-search-find-again-shortcut-prev = Find Previous
zen-search-find-again-shortcut-2 = Find Again (Alt)
zen-bookmark-this-page-shortcut = Bookmark This Page
zen-bookmark-show-library-shortcut = Show Bookmarks Library
zen-key-stop = Stop Loading
zen-full-zoom-reduce-shortcut = Uzaklaştır
zen-full-zoom-enlarge-shortcut = Yakınlaştır
zen-full-zoom-reset-shortcut = Zoom'u Sıfırla
zen-bidi-switch-direction-shortcut = Switch Text Direction
zen-private-browsing-shortcut = Gizli Arama
zen-screenshot-shortcut = Ekran Görüntüsü Al
zen-key-sanitize = Arama Verilerini Temizle
zen-quit-app-shortcut = Uygulamadan Çık
zen-key-wr-capture-cmd = WR Capture Command
zen-key-wr-toggle-capture-sequence-cmd = Toggle WR Capture Sequence
zen-nav-reload-shortcut = Sayfayı Yenile
zen-nav-reload-shortcut-skip-cache = Sayfayı Yenile (Cache'i Geç)
zen-close-shortcut = Pencereyi Kapat
zen-close-tab-shortcut = Sekmeyi Kapat
zen-compact-mode-shortcut-show-sidebar = Toggle Floating Sidebar
zen-compact-mode-shortcut-show-toolbar = Toggle Floating Toolbar
zen-compact-mode-shortcut-toggle = Kompakt Modu Aktifleştir
zen-workspace-shortcut-switch-1 = 1. Çalışma Alanına Geç
zen-workspace-shortcut-switch-2 = 2. Çalışma Alanına Geç
zen-workspace-shortcut-switch-3 = 3. Çalışma Alanına Geç
zen-workspace-shortcut-switch-4 = 4. Çalışma Alanına Geç
zen-workspace-shortcut-switch-5 = 5. Çalışma Alanına Geç
zen-workspace-shortcut-switch-6 = 6. Çalışma Alanına Geç
zen-workspace-shortcut-switch-7 = 7. Çalışma Alanına Geç
zen-workspace-shortcut-switch-8 = 8. Çalışma Alanına Geç
zen-workspace-shortcut-switch-9 = 9. Çalışma Alanına Geç
zen-workspace-shortcut-switch-10 = 10. Çalışma Alanına Geç
zen-workspace-shortcut-forward = Sonraki Çalışma Alanı
zen-workspace-shortcut-backward = Önceki Çalışma Alanı
zen-web-panel-shortcut-toggle = Web Paneli Aç/Kapat
zen-sidebar-shortcut-toggle = Toggle Sidebar's Width
zen-split-view-shortcut-grid = Toggle Split View Grid
zen-split-view-shortcut-vertical = Toggle Split View Vertical
zen-split-view-shortcut-horizontal = Toggle Split View Horizontal
zen-split-view-shortcut-unsplit = Close Split View
