pane-zen-looks-title = Erscheinungsbild
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Das Ändern der Standardsprache könnte es Webseiten einfacher machen, Sie zu verfolgen.
zen-look-and-feel-colors-header = Wähle ein Farb-Design
zen-look-and-feel-colors-description = Lass { -brand-short-name } so aussehen wie du es willst
zen-look-and-feel-themed-toolbar = 
    .label = Das Design der Symbolleiste an die Akzentfarbe anpassen
pane-zen-side-panels-title = Seitliche Web-Panels
zen-side-panels-header = Allgemeine Einstellungen für Web-Panels
zen-side-panels-description = Steigere deine Produktivität, indem du mehr auf einmal siehst!
zen-side-panels-enabled = 
    .label = Web-Seitenbereich aktivieren
zen-side-panels-close-on-blur = 
    .label = Schließe das Panel, wenn es den Fokus verliert und nicht angeheftet ist
zen-vertical-tabs-show-bottom-border = 
    .label = Rahmen für die unteren Symbole anzeigen
sync-currently-syncing-workspaces = Arbeitsbereiche
sync-engine-workspaces = 
    .label = Arbeitsbereiche
    .tooltiptext = Synchronisiere deine Arbeitsbereiche mit anderen Geräten
    .accesskey = W
zen-look-and-feel-compact-view-header = In der Kompaktansicht anzeigen
zen-look-and-feel-compact-view-description = Nur die Werkzeugleisten anzeigen, die du verwendest!
zen-look-and-feel-compact-view-enabled = 
    .label = Schalte { -brand-short-name }s Kompaktmodus ein
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Die obere Werkzeugleiste im Kompaktmodus ebenfalls ausblenden
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Lasse die Werkzeugleiste im Kompaktmodus beim Wechseln oder Öffnen von neuen Tabs kurzzeitig erscheinen
zen-look-and-feel-buttons-header = Tasten-Stil
zen-look-and-feel-buttons-description = Wähle den Stil der Knöpfe, den du sehen willst
zen-look-and-feel-pilled-buttons = 
    .label = Pillenförmige Tasten
pane-zen-tabs-title = Tabverwaltung
category-zen-workspaces = 
    .tooltiptext = { pane-zen-tabs-title }
pane-settings-workspaces-title = Arbeitsbereiche
pane-zen-tabs-unloader-title = Tab-Entlader
zen-tabs-unloader-header = Allgemeine Einstellungen für den Tab-Entlader
zen-tabs-unloader-description = Ungenutzte Tabs automatisch entladen, um Arbeitsspeicher freizugeben
zen-tabs-unloader-enabled = 
    .label = Tab-Entlader aktivieren
zen-tabs-unloader-unload-delay = 
    .label = Tabs entladen nach
zen-tabs-unloader-unload-delay-description = Die Zeit, in Minuten, nach der Tabs entladen werden
pane-zen-pinned-tab-manager-title = Angeheftete Tabs
zen-pinned-tab-manager-header = Allgemeine Einstellungen für angeheftete Tabs
zen-pinned-tab-manager-description = Zusätzliches Verhalten angehefteter Tabs verwalten
zen-pinned-tab-manager-restore-pinned-tabs-to-pinned-url = 
    .label = Angeheftete Tabs beim Start auf ihre ursprünglich angeheftete URL zurücksetzen
zen-pinned-tab-manager-close-shortcut-behavior-label = Verhalten der Tastenkürzel zum Schließen von Tabs
zen-pinned-tab-manager-reset-unload-switch-close-shortcut-option = 
    .label = URL zurücksetzen, entladen und zum nächsten Tab wechseln
zen-pinned-tab-manager-unload-switch-close-shortcut-option = 
    .label = Entladen und zum nächsten Tab wechseln
zen-pinned-tab-manager-reset-switch-close-shortcut-option = 
    .label = URL zurücksetzen und zum nächsten Tab wechseln
zen-pinned-tab-manager-switch-close-shortcut-option = 
    .label = Zum nächsten Tab wechseln
zen-pinned-tab-manager-reset-close-shortcut-option = 
    .label = URL zurücksetzen
zen-pinned-tab-manager-close-close-shortcut-option = 
    .label = Tab schließen
pane-zen-workspaces-header = Arbeitsbereiche
zen-settings-workspaces-header = Allgemeine Einstellungen für Arbeitsbereiche
zen-settings-workspaces-description = Mit Arbeitsbereichen kannst du mehrere Browsing-Sessions auf einmal haben!
zen-settings-workspaces-enabled = 
    .label = Arbeitsbereiche Einschalten (Experimentell)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Verstecke den Standard Container Indikator in der Tab-Leiste
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Arbeitsbereichen erlauben eigene angeheftete Tabs zu haben
zen-key-unsafed = Ungesicherte Änderung der Tastenkürzel! Bitte speichern, indem Escape nach der erneuten Eingabe gedrückt wird.
zen-key-conflict = Konflikt mit einem anderen Tastenkürzel
pane-zen-theme-title = Design Einstellungen
zen-vertical-tabs-title = Layout der Seitenleiste und Tabs
zen-vertical-tabs-header = Vertikale Tabs
zen-vertical-tabs-description = Verwalte deine Tabs in einem vertikalen Layout
zen-vertical-tabs-show-expand-button = 
    .label = Ausklapp-Knopf anzeigen
zen-vertical-tabs-expand-tabs-by-default = Tabs standardmäßig ausklappen
zen-vertical-tabs-dont-expand-tabs-by-default = Tabs nicht standardmäßig ausklappen
zen-vertical-tabs-expand-tabs-on-hover = Tabs beim Hovern ausklappen (Funktioniert nicht im Kompaktmodus)
zen-vertical-tabs-expand-tabs-header = Wie Tabs ausgeklappt werden sollen
zen-vertical-tabs-expand-tabs-description = Wähle, wie du Tabs in der Seitenleiste ausklappst
zen-theme-marketplace-header = Zen Mods
zen-theme-marketplace-description = Suche und installiere Designs aus dem Shop.
zen-theme-marketplace-remove-button = 
    .label = Design entfernen
zen-theme-marketplace-check-for-updates-button = 
    .label = Auf Updates prüfen
zen-theme-marketplace-updates-success = Design wurde erfolgreich aktualisiert
zen-theme-marketplace-updates-fail = Es konnten keine Updates gefunden werden!
zen-theme-marketplace-toggle-enabled-button = 
    .title = Design deaktivieren
zen-theme-marketplace-toggle-disabled-button = 
    .title = Design aktivieren
zen-theme-marketplace-remove-confirmation = Bist Du sicher, dass Du diesen Mod entfernen willst?
zen-theme-marketplace-close-modal = Schliessen
zen-theme-marketplace-theme-header-title = 
    .title = CSS-Selektor: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = Keine
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Gebe etwas ein...
pane-zen-marketplace-title = Zen Mods
zen-settings-workspaces-display-as-icon-strip = 
    .label = Arbeitsbereiche als Symbolleiste anzeigen
zen-settings-workspaces-force-container-tabs-to-workspace = 
    .label = Switch to workspace where container is set as default when opening container tabs
zen-theme-marketplace-link = Store besuchen
zen-dark-theme-styles-header = Dunkle Design Stile
zen-dark-theme-styles-description = Passe das dunkle Design deinen Vorstellungen an
zen-dark-theme-styles-amoled = Nacht-Design
zen-dark-theme-styles-default = Dunkles Design (Standard)
zen-dark-theme-styles-colorful = Dunkles Design (Farbenfroh)
zen-split-view-title = Geteilte Ansicht
zen-split-view-header = Funktionalität der geteilten Ansicht
zen-split-view-description = Teile deinen Browser in mehrere Ansichten, um auf mehreren Webseiten gleichzeitig zu browsen
zen-split-view-change-on-hover = 
    .label = Ändere Tabs beim Hovern
zen-compact-mode-styles-left = Tab-Leiste ausblenden
zen-compact-mode-styles-top = Obere Leiste ausblenden
zen-compact-mode-styles-both = Beide ausblenden
pane-zen-CKS-title = Tastaturkürzel
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } Tastenkürzel
zen-settings-CKS-header = Passe deine Tastenkürzel an
zen-settings-CKS-description = Passe die Standard-Tastenkürzel an deine Präferenzen an, um deine Nutzungserfahrung zu verbessern
zen-settings-CKS-disable-firefox = 
    .label = { -brand-short-name }s Standard-Tastenkürzel deaktivieren
zen-settings-CKS-duplicate-shortcut = 
    .label = Duplizieren Tastenkürzel
zen-settings-CKS-reset-shortcuts = 
    .label = Auf Standard zurücksetzen
zenCKSOption-group-other = Sonstiges
zenCKSOption-group-windowAndTabManagement = Fenster- & Tab-Verwaltung
zenCKSOption-group-navigation = Navigation
zenCKSOption-group-searchAndFind = Suchen & Finden
zenCKSOption-group-pageOperations = Seitenaktionen
zenCKSOption-group-historyAndBookmarks = Verlauf & Lesezeichen
zenCKSOption-group-mediaAndDisplay = Medien & Anzeige
zenCKSOption-group-zen-compact-mode = Kompakter Modus
zenCKSOption-group-zen-workspace = Arbeitsbereiche
zenCKSOption-group-zen-other = Andere Zen-Funktionen
zenCKSOption-group-zen-split-view = Geteilte Ansicht
zen-key-quick-restart = Schneller Neustart
zen-window-new-shortcut = Neues Fenster
zen-tab-new-shortcut = Neuer Tab
zen-key-redo = Wiederherstellen
zen-restore-last-closed-tab-shortcut = Zuletzt geschlossenen Tab wiederherstellen
zen-location-open-shortcut = Adresse öffnen
zen-location-open-shortcut-alt = Adresse öffnen (Alternativ)
zen-key-undo-close-window = Fenster schließen rückgängig machen
zen-text-action-undo-shortcut = Rückgängig
zen-text-action-redo-shortcut = Wiederherstellen
zen-text-action-cut-shortcut = Ausschneiden
zen-text-action-copy-shortcut = Kopieren
zen-text-action-paste-shortcut = Einfügen
zen-text-action-select-all-shortcut = Alles auswählen
zen-text-action-delete-shortcut = Entfernen
zen-history-show-all-shortcut-mac = Gesamten Verlauf anzeigen (Mac)
zen-full-screen-shortcut = Vollbildmodus umschalten
zen-reader-mode-toggle-shortcut-windows = Lesemodus umschalten (Windows)
zen-picture-in-picture-toggle-shortcut-alt = Bild-in-Bild umschalten (Alternativ)
zen-picture-in-picture-toggle-shortcut-mac = Bild-in-Bild umschalten (Mac)
zen-picture-in-picture-toggle-shortcut-mac-alt = Bild-in-Bild umschalten (Mac Alternativ)
zen-page-source-shortcut-safari = Seitenquelltext anzeigen (Safari)
zen-nav-stop-shortcut = Laden stoppen
zen-history-sidebar-shortcut = Verlaufsseitenleiste anzeigen
zen-window-minimize-shortcut = Fenster minimieren
zen-help-shortcut = Hilfe öffnen
zen-preferences-shortcut = Einstellungen öffnen
zen-hide-app-shortcut = Programm verstecken
zen-hide-other-apps-shortcut = Andere Programme verstecken
zen-search-focus-shortcut = Suche fokussieren
zen-search-focus-shortcut-alt = Suche fokussieren (Alternativ)
zen-downloads-shortcut = Downloads öffnen
zen-addons-shortcut = Erweiterungen öffnen
zen-file-open-shortcut = Datei öffnen
zen-save-page-shortcut = Seite speichern
zen-print-shortcut = Seite drucken
zen-close-shortcut-2 = Tab schließen
zen-mute-toggle-shortcut = Stummschaltung umschalten
zen-key-delete = Entfernen Taste
zen-key-go-back = Zurück
zen-key-go-forward = Vorwärts
zen-nav-back-shortcut-alt = Zurück (Alternativ)
zen-nav-fwd-shortcut-alt = Vorwärts (Alternativ)
zen-history-show-all-shortcut = Gesamten Verlauf anzeigen
zen-key-enter-full-screen = Vollbild aktivieren
zen-key-exit-full-screen = Vollbild deaktivieren
zen-reader-mode-toggle-shortcut-other = Lesemodus umschalten
zen-picture-in-picture-toggle-shortcut = Bild-in-Bild umschalten
zen-nav-reload-shortcut-2 = Seite neu laden
zen-key-about-processes = Über Prozesse (Taskmanager)
zen-page-source-shortcut = Seitenquelltext anzeigen
zen-page-info-shortcut = Seiteninfo anzeigen
zen-find-shortcut = Seite durchsuchen
zen-search-find-again-shortcut = Erneut suchen
zen-search-find-again-shortcut-prev = Vorheriges suchen
zen-search-find-again-shortcut-2 = Erneut suchen (Alternativ)
zen-bookmark-this-page-shortcut = Lesezeichen für diese Seite erstellen
zen-bookmark-show-library-shortcut = Lesezeichenbibliothek anzeigen
zen-key-stop = Laden stoppen
zen-full-zoom-reduce-shortcut = Herauszoomen (verkleinern)
zen-full-zoom-enlarge-shortcut = Hineinzoomen (vergrößern)
zen-full-zoom-reset-shortcut = Zoom zurücksetzen
zen-bidi-switch-direction-shortcut = Textrichtung umschalten
zen-private-browsing-shortcut = Privates Browsen
zen-screenshot-shortcut = Bildschirmaufnahme
zen-key-sanitize = Browserdaten löschen
zen-quit-app-shortcut = Programm schließen
zen-key-wr-capture-cmd = Aufnahmebefehl für WebRender
zen-key-wr-toggle-capture-sequence-cmd = WebRender-Aufnahmesequenz umschalten
zen-nav-reload-shortcut = Seite neu laden
zen-nav-reload-shortcut-skip-cache = Seite neu laden (Cache überspringen)
zen-close-shortcut = Fenster schließen
zen-close-tab-shortcut = Tab schließen
zen-compact-mode-shortcut-show-sidebar = Schwebende Seitenleiste umschalten
zen-compact-mode-shortcut-show-toolbar = Schwebende Werkzeugleiste umschalten
zen-compact-mode-shortcut-toggle = Kompakten Modus umschalten
zen-workspace-shortcut-switch-1 = Zum Arbeitsbereich 1 wechseln
zen-workspace-shortcut-switch-2 = Zum Arbeitsbereich 2 wechseln
zen-workspace-shortcut-switch-3 = Zum Arbeitsbereich 3 wechseln
zen-workspace-shortcut-switch-4 = Zum Arbeitsbereich 4 wechseln
zen-workspace-shortcut-switch-5 = Zum Arbeitsbereich 5 wechseln
zen-workspace-shortcut-switch-6 = Zum Arbeitsbereich 6 wechseln
zen-workspace-shortcut-switch-7 = Zum Arbeitsbereich 7 wechseln
zen-workspace-shortcut-switch-8 = Zum Arbeitsbereich 8 wechseln
zen-workspace-shortcut-switch-9 = Zum Arbeitsbereich 9 wechseln
zen-workspace-shortcut-switch-10 = Zum Arbeitsbereich 10 wechseln
zen-workspace-shortcut-forward = Nächster Arbeitsbereich
zen-workspace-shortcut-backward = Vorheriger Arbeitsbereich
zen-web-panel-shortcut-toggle = Web-Panel umschalten
zen-sidebar-shortcut-toggle = Breite der Seitenleiste umschalten
zen-pinned-tab-shortcut-reset = Angehefteten Tab auf angeheftete URL zurücksetzen
zen-split-view-shortcut-grid = Geteilte Ansicht als Raster umschalten
zen-split-view-shortcut-vertical = Geteilte Ansicht vertikal umschalten
zen-split-view-shortcut-horizontal = Geteilte Ansicht horizontal umschalten
zen-split-view-shortcut-unsplit = Geteilte Ansicht schließen
zen-key-select-tab-1 = Tab #1 auswählen
zen-key-select-tab-2 = Tab #2 auswählen
zen-key-select-tab-3 = Tab #3 auswählen
zen-key-select-tab-4 = Tab #4 auswählen
zen-key-select-tab-5 = Tab #5 auswählen
zen-key-select-tab-6 = Tab #6 auswählen
zen-key-select-tab-7 = Tab #7 auswählen
zen-key-select-tab-8 = Tab #8 auswählen
zen-key-select-tab-last = Letzten Tab auswählen
zen-key-show-all-tabs = Alle Tabs anzeigen
zen-key-goto-history = Zum Verlauf gehen
zen-key-go-home = Zur Startseite
zen-bookmark-show-sidebar-shortcut = Lesezeichenseitenleiste anzeigen
zen-bookmark-show-toolbar-shortcut = Lesezeichenwerkzeugleiste anzeigen
