pane-zen-looks-title = Erscheinungsbild
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Wenn du deine Standardsprache änderst, kann es für Websites einfacher werden, dich zu verfolgen.
zen-look-and-feel-colors-header = Wähle ein Farb-Design
zen-look-and-feel-colors-description = Lass { -brand-short-name } so aussehen wie du es willst
zen-look-and-feel-themed-toolbar = 
    .label = Das Design der Symbolleiste an die Akzentfarbe anpassen
pane-zen-side-panels-title = Seitliche Web-Panels
zen-side-panels-header = Allgemeine Einstellungen für Web-Panels
zen-side-panels-description = Steigere deine Produktivität, indem du mehr auf einmal siehst!
zen-side-panels-enabled = 
    .label = Web-Seitenbereich aktivieren
zen-side-panels-close-on-blur = 
    .label = Schließe das Panel, wenn es den Fokus verliert und nicht angeheftet ist
zen-look-and-feel-compact-view-header = In der Kompaktansicht anzeigen
zen-look-and-feel-compact-view-description = Nur die Werkzeugleisten anzeigen, die du verwendest!
zen-look-and-feel-compact-view-enabled = 
    .label = Schalte { -brand-short-name }s Kompaktmodus ein
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Die obere Werkzeugleiste im Kompaktmodus ebenfalls ausblenden
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = Lasse die Werkzeugleiste im Kompaktmodus beim Wechseln oder Öffnen von neuen Tabs kurzzeitig erscheinen
zen-look-and-feel-buttons-header = Tasten-Stil
zen-look-and-feel-buttons-description = Wähle den Stil der Knöpfe, den du sehen willst
zen-look-and-feel-pilled-buttons = 
    .label = Pillenförmige Tasten
pane-zen-workspaces-title = Arbeitsbereiche
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = Arbeitsbereiche
pane-zen-workspaces-header = Arbeitsbereiche
zen-settings-workspaces-header = Allgemeine Einstellungen für Arbeitsbereiche
zen-settings-workspaces-description = Mit Arbeitsbereichen kannst du mehrere Browsing-Sessions auf einmal haben!
zen-settings-workspaces-enabled = 
    .label = Arbeitsbereiche Einschalten (Experimentell)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = Verstecke den Standard Container Indikator in der Tab-Leiste
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = Allow workspaces have their own pinned tabs
pane-zen-theme-title = Design Einstellungen
zen-vertical-tabs-title = Layout der Seitenleiste und Tabs
zen-vertical-tabs-header = Vertikale Tabs
zen-vertical-tabs-description = Verwalte deine Tabs in einem vertikalen Layout
zen-vertical-tabs-show-expand-button = 
    .label = Ausklapp-Knopf anzeigen
zen-vertical-tabs-expand-tabs-by-default = Tabs standardmäßig ausklappen
zen-vertical-tabs-dont-expand-tabs-by-default = Tabs nicht standardmäßig ausklappen
zen-vertical-tabs-expand-tabs-on-hover = Tabs beim Hovern ausklappen (Funktioniert nicht im Kompaktmodus)
zen-vertical-tabs-expand-tabs-header = Wie Tabs ausgeklappt werden sollen
zen-vertical-tabs-expand-tabs-description = Wähle, wie du Tabs in der Seitenleiste ausklappst
zen-theme-marketplace-header = Zen Mods
zen-theme-marketplace-description = Suche und installiere Designs aus dem Shop.
zen-theme-marketplace-remove-button = 
    .label = Design entfernen
zen-theme-marketplace-check-for-updates-button = 
    .label = Auf Updates prüfen
zen-theme-marketplace-updates-success = Design wurde erfolgreich aktualisiert
zen-theme-marketplace-updates-fail = Es konnten keine Updates gefunden werden!
zen-theme-marketplace-toggle-enabled-button = 
    .title = Disable Theme
zen-theme-marketplace-toggle-disabled-button = 
    .title = Enable Theme
zen-theme-marketplace-remove-confirmation = Are you sure you want to remove this theme?
zen-theme-marketplace-close-modal = Close
zen-theme-marketplace-theme-header-title = 
    .title = CSS Selector: { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = None
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = Type something...
pane-zen-marketplace-title = Zen Mods
zen-settings-workspaces-display-as-icon-strip = 
    .label = Display workspaces as an icon strip
zen-theme-marketplace-link = Store besuchen
zen-dark-theme-styles-header = Dunkle Design Stile
zen-dark-theme-styles-description = Passe das dunkle Design deinen Vorstellungen an
zen-dark-theme-styles-amoled = Night Theme
zen-dark-theme-styles-default = Dunkles Design (Standard)
zen-dark-theme-styles-colorful = Dunkles Design (Farbenfroh)
pane-zen-CKS-title = Tastaturkürzel
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } Tastenkürzel
zen-settings-CKS-header = Passe deine Tastenkürzel an
zen-settings-CKS-description = Passe die Standard-Tastenkürzel an deine Präferenzen an, um deine Nutzungserfahrung zu verbessern
zen-settings-CKS-disable-firefox = 
    .label = { -brand-short-name }s Standard-Tastenkürzel deaktivieren
zen-cks-group-tab-action = Tab-Aktionen
zen-cks-group-page-action = Seiten-Aktionen
zen-cks-group-visible-action = Sichtbare Aktionen
zen-cks-group-history-action = Verlaufsaktionen
zen-cks-group-search-action = Suchaktionen
zen-cks-group-tools-action = Werkzeug-Aktionen
zen-cks-group-bookmark-action = Lesezeichen-Aktionen
zen-cks-group-open-page-action = Open Page Actions
zen-cks-group-downloads-action = Download-Aktionen
zen-cks-group-sidebar-action = Sidebar-Aktionen
zen-cks-group-compact-mode-action = Kompaktmodus-Aktionen
zen-cks-group-split-view-action = Ansichts-Aktionen
zen-cks-group-workspace-action = Arbeitsbereich-Aktionen
open-new-tab = Neuen Tab öffnen
close-tab = Tab schließen
open-new-window = Neues Fenster öffnen
open-new-private-window = Neues privates Fenster öffnen
close-window = Fenster schließen
restore-last-tab = Letzten Tab wiederherstellen
restore-last-window = Letztes Fenster wiederherstellen
show-next-tab = Nächsten Tab anzeigen
show-previous-tab = Vorherigen Tab anzeigen
show-all-tabs-panel = Zeige Alle-Tabs Panel
send-with-mail = Seite über Mail versenden
save-page = Seite Speichern
print-page = Seite Drucken
mute-current-tab = Aktuellen Tab stummschalten
show-source-of-page = Seitenquelltext anzeigen
show-page-info = Seiteninfo anzeigen
zoom-in = Vergrößern
zoom-out = Verkleinern
reset-zoom = Vergrößerung zurücksetzen
back = Zurück
forward = Weiter
stop = Stopp
reload = Neu laden
force-reload = Neu laden erzwingen
search-in-this-page = Auf dieser Seite suchen
show-next-search-result = Nächstes Suchergebnis anzeigen
show-previous-search-result = Vorherige Suchergebnisse anzeigen
search-the-web = Im Netz suchen
open-migration-wizard = Migrationsassistent öffnen
quit-from-application = Anwendung beenden
enter-into-customize-mode = Anpassungsmodus betreten
enter-into-offline-mode = Offline-Modus aktivieren
open-screen-capture = Bildschirmaufnahme öffnen
bookmark-this-page = Lesezeichen für diese Seite erstellen
open-bookmark-add-tool = Lesezeichen hinzufügen Tool öffnen
open-bookmarks-manager = Lesezeichen-Manager öffnen
toggle-bookmark-toolbar = Lesezeichen-Symbolleiste umschalten
open-general-preferences = Allgemeine Einstellungen öffnen
open-privacy-preferences = Privatsphäre-Einstellungen öffnen
open-workspaces-preferences = Arbeitsbereich-Einstellungen öffnen
open-containers-preferences = Container-Einstellungen öffnen
open-search-preferences = Sucheinstellungen öffnen
open-sync-preferences = Synchronisations-Einstellungen öffnen
open-task-manager = Task-Manager öffnen
open-addons-manager = Add-ons-Manager öffnen
open-home-page = Startseite öffnen
forget-history = Verlauf vergessen
quick-forget-history = Verlauf schnell vergessen
clear-recent-history = Kürzlichen Verlauf löschen
restore-last-session = Letzte Sitzung wiederherstellen
search-history = Verlauf durchsuchen
manage-history = Verlauf verwalten
open-downloads = Downloads öffnen
show-bookmark-sidebar = Lesezeichen-Sidebar anzeigen
show-history-sidebar = Verlauf-Sidebar anzeigen
show-synced-tabs-sidebar = Synchronisierte-Tabs-Sidebar anzeigen
reverse-sidebar = Sidebar Position umkehren
hide-sidebar = Sidebar verstecken
toggle-sidebar = Sidebar umschalten
zen-toggle-web-panels = Web-Panels umschalten
zen-toggle-compact-mode = Kompakt-Modus umschalten
zen-toggle-compact-mode-sidebar = Kompakt-Modus-Sidebar umschalten
zen-toggle-compact-mode-toolbar = Kompakt-Modus-Toolbar umschalten
zen-change-workspace = Arbeitsbereiche wechseln
zen-split-view-grid = Rasteransicht
zen-split-view-vertical = Vertikal geteilte Ansicht
zen-split-view-horizontal = Horizontal geteilte Ansicht
zen-split-view-close = Geteilte Ansicht schliessen
zen-expand-sidebar = Schalte Seitenleisten Vergrößerung um
