pane-zen-looks-title = Erscheinungsbild
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = Wenn du deine Standardsprache änderst, kann es für Websites einfacher werden, dich zu verfolgen.
zen-look-and-feel-colors-header = Wähle ein Farb-Design
zen-look-and-feel-colors-description = Lass { -brand-short-name } so aussehen wie du willst
zen-look-and-feel-themed-toolbar = 
    .label = Make the toolbar themed with the accent color
pane-zen-side-panels-title = Side Web Panels
zen-side-panels-header = Allgemeine Einstellungen für Web-Panels
zen-side-panels-description = Steigere deine Produktivität, indem du mehr auf einmal siehst!
zen-side-panels-enabled = 
    .label = Enable Web Side Panels
zen-side-panels-close-on-blur = 
    .label = Schließe das Panel, wenn es den Fokus verliert und nicht angeheftet ist
zen-look-and-feel-compact-view-header = In der Kompaktansicht anzeigen
zen-look-and-feel-compact-view-description = Nur die Werkzeugleisten anzeigen, die du verwendest!
zen-look-and-feel-compact-view-enabled = 
    .label = Schalte { -brand-short-name }s Kompaktmodus ein
zen-look-and-feel-compact-view-top-toolbar = 
    .label = Die obere Werkzeugleiste im Kompaktmodus ebenfalls ausblenden
zen-look-and-feel-buttons-header = Knopf-Stil
zen-look-and-feel-buttons-description = Wähle den Stil der Knöpfe, den du sehen willst
zen-look-and-feel-pilled-buttons = 
    .label = Pilled Buttons
pane-zen-workspaces-title = Arbeitsbereiche
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = Arbeitsbereiche
pane-zen-workspaces-header = Arbeitsbereiche
zen-settings-workspaces-header = Allgemeine Einstellungen für Arbeitsbereiche
zen-settings-workspaces-description = Mit Arbeitsbereichen kannst du mehrere Browsing-Sessions auf einmal haben!
zen-settings-workspaces-enabled = 
    .label = Arbeitsbereiche Einschalten (Experimentell)
pane-zen-theme-title = Design Einstellungen
zen-vertical-tabs-title = Layout der Seitenleiste und Tabs
zen-vertical-tabs-header = Vertikale Tabs
zen-vertical-tabs-description = Verwalte deine Tabs in einem vertikalen Layout
zen-vertical-tabs-show-expand-button = 
    .label = Ausklapp-Knopf anzeigen
zen-vertical-tabs-expand-tabs-by-default = Tabs standardmäßig ausklappen
zen-vertical-tabs-dont-expand-tabs-by-default = Tabs nicht standardmäßig ausklappen
zen-vertical-tabs-expand-tabs-on-hover = Tabs beim Hovern ausklappen (Funktioniert nicht im Kompaktmodus)
zen-vertical-tabs-expand-tabs-header = Wie man Tabs ausklappt
zen-vertical-tabs-expand-tabs-description = Wähle, wie du Tabs in der Seitenleiste ausklappst
zen-theme-marketplace-header = Theme Store
zen-theme-marketplace-description = Find and install themes from the store.
zen-theme-marketplace-remove-button = 
    .label = Remove Theme
zen-theme-marketplace-link = Visit Store
pane-zen-CKS-title = Keyboard Shortcuts
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } Keyboard Shortcuts
zen-settings-CKS-header = Customize your keyboard shortcuts
zen-settings-CKS-description = Change the default keyboard shortcuts to your liking and improve your browsing experience
zen-settings-CKS-disable-firefox = 
    .label = Disable { -brand-short-name }'s default keyboard shortcuts
zen-cks-group-tab-action = Tab Actions
zen-cks-group-page-action = Page Actions
zen-cks-group-visible-action = Visible Actions
zen-cks-group-history-action = History Actions
zen-cks-group-search-action = Search Actions
zen-cks-group-tools-action = Tools Actions
zen-cks-group-bookmark-action = Bookmark Actions
zen-cks-group-open-page-action = Open Page Actions
zen-cks-group-downloads-action = Downloads Actions
zen-cks-group-sidebar-action = Sidebar Actions
zen-cks-group-compact-mode-action = Compact Mode Actions
zen-cks-group-split-view-action = Split View Actions
zen-cks-group-workspace-action = Workspace Actions
open-new-tab = Open New Tab
close-tab = Close Tab
open-new-window = Open New Window
open-new-private-window = Open New Private Window
close-window = Close Window
restore-last-tab = Restore Last Tab
restore-last-window = Restore Last Window
show-next-tab = Nächsten Tab anzeigen
show-previous-tab = Vorherigen Tab anzeigen
show-all-tabs-panel = Show All Tabs Panel
send-with-mail = Send Page with Mail
save-page = Seite Speichern
print-page = Seite Drucken
mute-current-tab = Aktuellen Tab stummschalten
show-source-of-page = Show Source of Page
show-page-info = Show Page Info
zoom-in = Vergrößern
zoom-out = Verkleinern
reset-zoom = Vergrößerung zurücksetzen
back = Zurück
forward = Weiter
stop = Stopp
reload = Neu laden
force-reload = Neu laden erzwingen
search-in-this-page = Auf dieser Seite suchen
show-next-search-result = Nächstes Suchergebnis anzeigen
show-previous-search-result = Vorherige Suchergebnisse anzeigen
search-the-web = Search the Web
open-migration-wizard = Open Migration Wizard
quit-from-application = Quit Application
enter-into-customize-mode = Enter Customize Mode
enter-into-offline-mode = Enter Offline Mode
open-screen-capture = Open Screen Capture
bookmark-this-page = Bookmark This Page
open-bookmark-add-tool = Open Bookmark Add Tool
open-bookmarks-manager = Open Bookmarks Manager
toggle-bookmark-toolbar = Toggle Bookmark Toolbar
open-general-preferences = Open General Preferences
open-privacy-preferences = Open Privacy Preferences
open-workspaces-preferences = Open Workspaces Preferences
open-containers-preferences = Open Containers Preferences
open-search-preferences = Open Search Preferences
open-sync-preferences = Open Sync Preferences
open-task-manager = Open Task Manager
open-addons-manager = Open Add-ons Manager
open-home-page = Open Home Page
forget-history = Forget History
quick-forget-history = Quick Forget History
clear-recent-history = Clear Recent History
restore-last-session = Restore Last Session
search-history = Search History
manage-history = Manage History
open-downloads = Open Downloads
show-bookmark-sidebar = Show Bookmark Sidebar
show-history-sidebar = Show History Sidebar
show-synced-tabs-sidebar = Show Synced Tabs Sidebar
reverse-sidebar = Reverse Sidebar Position
hide-sidebar = Hide Sidebar
toggle-sidebar = Toggle Sidebar
zen-toggle-web-panels = Toggle Web Panels
zen-toggle-compact-mode = Toggle Compact Mode
zen-toggle-compact-mode-sidebar = Toggle Compact Mode Sidebar
zen-toggle-compact-mode-toolbar = Toggle Compact Mode Toolbar
zen-change-workspace = Cycle Workspaces
zen-split-view-grid = Split View Grid
zen-split-view-vertical = Split View Vertical
zen-split-view-horizontal = Split View Horizontal
zen-split-view-close = Close Split View
