zen-panel-ui-current-profile-text = الملف الشخصي الحالي
unified-extensions-description = تستخدم الإضافات لجلب المزيد من الوظائف الإضافية إلى { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = إعادة تعيين علامة التبويب المثبتة
    .accesskey = ر
tab-context-zen-add-essential = 
    .label = Add to Essentials
    .accesskey = E
tab-context-zen-remove-essential = 
    .label = Remove from Essentials
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = استبدال الرابط المثبت بالرابط الحالي
    .accesskey = C
tab-zen-unload = 
    .label = Unload Tab
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = إجراءات إلغاء تحميل علامات التبويب
    .accesskey = ت
tab-zen-prevent-unload = 
    .label = Allow Tab Unload
    .accesskey = ب
tab-zen-ignore-unload = 
    .label = السماح بإلغاء تحميل علامة التبويب
    .accesskey = I
zen-themes-corrupted = ملف التعديل { -brand-short-name } الخاص بك تالف. تم إعادة تعيينه إلى السمة الافتراضية.
zen-panel-ui-gradient-generator-opacity-text = Contrast
zen-panel-ui-gradient-generator-texture-text = نسيج
zen-panel-ui-gradient-generator-custom-color = لون مخصص
zen-panel-ui-gradient-generator-saved-message = حفظ معامل التدرج بنجاح!
