zen-panel-ui-workspaces-text = مساحات العمل
zen-panel-ui-workspaces-create =
    .label = إنشاء مساحة عمل
zen-workspaces-panel-context-delete =
    .label = حذف مساحة العمل
    .accesskey = د
zen-workspaces-panel-change-name =
    .label = تغيير الاسم
zen-workspaces-panel-change-icon =
    .label = تغيير الأيقونة
zen-workspaces-panel-context-default-profile =
    .label = تعيين الملف الشخصي
zen-workspaces-how-to-reorder-title = كيفية إعادة ترتيب المساحات
zen-workspaces-how-to-reorder-desc = اسحب أيقونات المساحات أسفل الشريط الجانبي لإعادة ترتيبها
zen-workspaces-change-theme =
    .label = تعديل السمة
zen-workspaces-panel-context-open =
    .label = فتح مساحة العمل
    .accesskey = ف
zen-workspaces-panel-context-edit =
    .label = تعديل مساحة العمل
    .accesskey = ت
context-zen-change-workspace-tab =
    .label = نقل علامة التبويب إلى مساحة عمل
    .accesskey = ن
zen-bookmark-edit-panel-workspace-selector =
    .value = مساحات العمل
    .accesskey = م
zen-panel-ui-gradient-generator-algo-complementary =
    .label = مكمل
zen-panel-ui-gradient-generator-algo-splitComplementary =
    .label = تقسيم مكمل
zen-panel-ui-gradient-generator-algo-analogous =
    .label = متشابه
zen-panel-ui-gradient-generator-algo-triadic =
    .label = ثلاثي
zen-panel-ui-gradient-generator-algo-floating =
    .label = عائم
zen-panel-ui-gradient-click-to-add = اضغط لإضافة لون
zen-workspace-creation-name =
    .placeholder = اسم مساحة العمل
zen-workspaces-panel-context-reorder =
    .label = إعادة ترتيب المساحات
zen-workspace-creation-profile = الملف الشخصي
    .tooltiptext = تُستخدم الملفات الشخصية لفصل ملفات تعريف الارتباط وبيانات المواقع بين المساحات.
zen-workspace-creation-header = إنشاء مساحة عمل
zen-workspace-creation-label = تُستخدم مساحات العمل لتنظيم علامات التبويب والجلسات الخاصة بك.
zen-workspaces-delete-workspace-title = حذف مساحة العمل؟
zen-workspaces-delete-workspace-body = هل أنت متأكد أنك تريد حذف هذه المساحة؟ هذا الإجراء لا يمكن التراجع عنه.

