zen-panel-ui-current-profile-text = الملف الشخصي الحالي
unified-extensions-description = تستخدم الإضافات لجلب المزيد من الوظائف الإضافية إلى { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = إعادة تعيين علامة التبويب المثبتة
    .accesskey = ر
tab-context-zen-add-essential = 
    .label = Add to Essentials
    .accesskey = E
tab-context-zen-remove-essential = 
    .label = Remove from Essentials
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = استبدال الرابط المثبت بالرابط الحالي
    .accesskey = C
tab-zen-unload = 
    .label = Unload Tab
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = إجراءات إلغاء تحميل علامات التبويب
    .accesskey = ت
tab-zen-prevent-unload = 
    .label = Allow Tab Unload
    .accesskey = ب
tab-zen-ignore-unload = 
    .label = السماح بإلغاء تحميل علامة التبويب
    .accesskey = I
zen-themes-corrupted = ملف التعديل { -brand-short-name } الخاص بك تالف. تم إعادة تعيينه إلى السمة الافتراضية.
zen-panel-ui-gradient-generator-opacity-text = Contrast
zen-panel-ui-gradient-generator-texture-text = نسيج
zen-panel-ui-gradient-generator-custom-color = لون مخصص
zen-panel-ui-gradient-generator-saved-message = حفظ معامل التدرج بنجاح!
zen-copy-current-url-confirmation = The URL has been copied to the clipboard.
zen-rice-share-name = 
    .placeholder = Rice Name
zen-rice-share-author = By
zen-rice-share-author-input = 
    .placeholder = Your Name
zen-rice-share-cancel = Cancel
zen-rice-share-save = Share
zen-rice-share-include-userchrome = 
    .label = Include userChrome.css
zen-rice-share-include-usercontent = 
    .label = Include userContent.css
zen-rice-share-include-mods = 
    .label = Include enabled mods
zen-rice-share-include-mod-prefs = 
    .label = Include mod preferences
zen-rice-share-include-preferences = 
    .label = Include layout state
zen-rice-share-include-workspace-themes = 
    .label = Include workspace gradient themes
zen-rice-share-include = Export Options
