zen-panel-ui-workspaces-text = مساحات العمل
zen-panel-ui-workspaces-create-text = إنشاء فضاء عمل
zen-panel-ui-workspaces-create-save = 
    .label = إنشاء فضاء عمل
    .accesskey = س
zen-panel-ui-workspaces-create-cancel = 
    .label = إلغاء
    .accesskey = ج
zen-panel-ui-workspaces-edit-text = تعديل فضاء العمل
zen-panel-ui-workspaces-edit-save = 
    .label = حفظ التغييرات
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = إلغاء
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = حذف مساحة العمل
    .accesskey = د
zen-workspaces-panel-change-name = 
    .label = Change Name
zen-workspaces-panel-context-open-in-container-tab = 
    .label = تعيين الحاوية الافتراضية
    .accesskey = O
zen-workspaces-change-gradient = 
    .label = تغيير ألوان السمة
    .accesskey = C
zen-workspaces-panel-context-open = 
    .label = Open Workspace
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Set As Default Workspace
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Edit Workspace
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Change Tab(s) To Workspace
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Workspaces
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Complementary
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Split
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Analogous
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Triadic
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Floating
zen-panel-ui-gradient-click-to-add = Click to add a color
