zen-panel-ui-current-window-text = Cửa sổ hiện tại
zen-panel-ui-workspaces-text = Không gian làm việc khác
zen-panel-ui-workspaces-create-text = Tạo không gian làm việc
zen-panel-ui-workspaces-create-save = 
    .label = Tạo không gian làm việc
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = Hủy bỏ
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Xóa không gian làm việc
    .accesskey = D
zen-workspaces-panel-context-open = 
    .label = Mở không gian làm việc
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Đặt làm không gian làm việc mặt định
    .accesskey = S
context-zen-change-workspace-tab = 
    .label = Di chuyển (nhiều) Tab đến không gian làm việc
    .accesskey = C
