zen-web-side-panel-context-mute-panel = 
    .label = Tắt tiếng bảng điều khiển web
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = Mở tiếng bảng điều khiển web
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = Hủy chế độ người dùng di động
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = Kích hoạt chế độ người dùng di động
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = Dừng tải bảng điều khiển web
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = Xóa bảng điều khiển web
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = Mở trong một tab mới
    .accesskey = N
zen-web-side-panel-context-add-to-panel = 
    .label = Thêm vào bảng điều khiển web
    .accesskey = A
zen-sidebar-introduction-title = Chào mừng đến với Zen Sidebar
zen-sidebar-introduction-description = Zen Sidebar là một cách mới để duyệt web. Nhấp vào bất kỳ biểu tượng nào để mở bảng điều khiển web.
