zen-panel-ui-current-profile-text = hồ sơ hiện tại
unified-extensions-description = Các tiện ích mở rộng được sử dụng để mang thêm tính năng vào { -brand-short-name }.
tab-context-zen-reset-pinned-tab = 
    .label = Đặt lại tab đã ghim
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Replace Pinned URL with Current
    .accesskey = C
tab-zen-unload = 
    .label = Giải phóng Tab
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Các hành động giải phóng tab
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Tránh Tab bị giải phóng
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Bỏ qua việc giải phóng tab
    .accesskey = I
