zen-panel-ui-workspaces-text = Không gian làm việc khác
zen-panel-ui-workspaces-create-text = Tạo không gian làm việc
zen-panel-ui-workspaces-create-save = 
    .label = Tạo không gian làm việc
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = Hủy bỏ
    .accesskey = C
zen-panel-ui-workspaces-edit-text = Tùy chỉnh không gian làm việc
zen-panel-ui-workspaces-edit-save = 
    .label = Lưu các thay đổi
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = Hủy bỏ
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = Xóa không gian làm việc
    .accesskey = D
zen-workspaces-panel-context-open = 
    .label = Mở không gian làm việc
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Đặt làm không gian làm việc mặt định
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Tùy chỉnh không gian làm việc
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Di chuyển (nhiều) Tab đến không gian làm việc
    .accesskey = C
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Đặt vùng chứa mặc định
    .accesskey = O
zen-workspaces-change-gradient = 
    .label = Thay đổi màu sắc chủ đề
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Không gian làm việc
    .accesskey = W
