pane-zen-looks-title = 界面外观
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = 更改默认语言可能会让网站更容易追踪您。
zen-look-and-feel-colors-header = 选择一个主题颜色
zen-look-and-feel-colors-description = 让 { -brand-short-name } 界面外观符合您的喜好
zen-look-and-feel-use-workspace-colors = 
    .label = 将工作空间颜色用作主颜色
pane-zen-side-panels-title = 侧边网页面板
zen-side-panels-header = 网页面板的常规设置
zen-side-panels-description = 通过同时拥有多个视图来提高生产力！
zen-side-panels-enabled = 
    .label = 启用侧边网页面板
zen-side-panels-close-on-blur = 
    .label = 如果面板没有置顶，失去焦点时关闭面板
zen-vertical-tabs-show-bottom-border = 
    .label = 显示底部图标的边框
zen-vertical-tabs-layout-header = 浏览器布局
zen-vertical-tabs-layout-description = 选择最适合您的布局
zen-layout-single-toolbar = 单工具栏
zen-layout-multiple-toolbar = 多工具栏
zen-layout-collapsed-toolbar = 折叠工具栏
sync-currently-syncing-workspaces = 工作区
sync-engine-workspaces = 
    .label = 工作区
    .tooltiptext = 在不同设备之间同步您的工作区
    .accesskey = W
zen-glance-title = 浮窗预览
zen-glance-header = 浮窗预览常规设置
zen-glance-description = 无需打开新标签页，即可快速预览链接内容
zen-glance-trigger-label = 触发方式
zen-glance-enabled = 
    .label = 启用浮窗预览
zen-glance-trigger-ctrl-click = 
    .label = Ctrl + Click
zen-glance-trigger-alt-click = 
    .label = Alt + 点击
zen-glance-trigger-shift-click = 
    .label = Shift + 点击
zen-glance-trigger-meta-click = 
    .label = Meta (Command) + 点击
zen-glance-trigger-mantain-click = 
    .label = 长按（即将上线）
zen-look-and-feel-compact-view-header = 以紧凑视图显示
zen-look-and-feel-compact-view-description = 只显示你使用的工具栏！
zen-look-and-feel-compact-view-enabled = 
    .label = 启用 { -brand-short-name } 的紧凑模式
zen-look-and-feel-compact-view-top-toolbar = 
    .label = 在紧凑模式下隐藏顶部工具栏
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = 简洁模式下，切换或打开新标签页时短暂弹出工具栏
zen-look-and-feel-buttons-header = 按钮风格
zen-look-and-feel-buttons-description = 选择您想看到的按钮样式
zen-look-and-feel-pilled-buttons = 
    .label = Pilled 按钮
pane-zen-tabs-title = 标签页管理
category-zen-workspaces = 
    .tooltiptext = { pane-zen-tabs-title }
pane-settings-workspaces-title = 工作空间
pane-zen-tabs-unloader-title = 标签页卸载器
zen-tabs-unloader-header = 标签页卸载器常规设置
zen-tabs-unloader-description = 自动卸载未使用的标签页以节省内存
zen-tabs-unloader-enabled = 
    .label = 启用标签页卸载器
zen-tabs-unloader-unload-delay = 
    .label = 在指定时间后卸载标签页
zen-tabs-unloader-unload-delay-description = 标签页将在指定的分钟数后卸载
zen-look-and-feel-compact-toolbar-themed = 
    .label = 在简洁模式下，将主题背景应用到工具栏
zen-look-and-feel-compact-sidebar-themed = 
    .label = 在简洁模式下，将主题背景应用到侧边栏
pane-zen-pinned-tab-manager-title = 固定标签页
zen-pinned-tab-manager-header = 固定标签页的常规设置
zen-pinned-tab-manager-description = 管理固定标签页的附加行为
zen-pinned-tab-manager-restore-pinned-tabs-to-pinned-url = 
    .label = 启动时恢复固定标签页至初始固定时的 URL
zen-pinned-tab-manager-container-specific-essentials-enabled = 
    .label = 启用容器专属 essentials
zen-pinned-tab-manager-close-shortcut-behavior-label = 关闭标签页快捷键的行为
zen-pinned-tab-manager-reset-unload-switch-close-shortcut-option = 
    .label = 重置 URL，卸载并切换到下一个标签页
zen-pinned-tab-manager-unload-switch-close-shortcut-option = 
    .label = 卸载并切换到下一个标签页
zen-pinned-tab-manager-reset-switch-close-shortcut-option = 
    .label = 重置 URL 并切换到下一个标签页
zen-pinned-tab-manager-switch-close-shortcut-option = 
    .label = 切换到下一个标签页
zen-pinned-tab-manager-reset-close-shortcut-option = 
    .label = 重置 URL
zen-pinned-tab-manager-close-close-shortcut-option = 
    .label = 关闭标签页
pane-zen-workspaces-header = 工作空间
zen-settings-workspaces-header = 工作空间的常规设置
zen-settings-workspaces-description = 使用工作空间，您可以同时进行多个浏览会话！
zen-settings-workspaces-enabled = 
    .label = 启用工作空间 (实验性)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = 隐藏在标签页栏中的默认容器指示器
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = 允许工作区有自己的固定标签页
zen-key-unsafed = 快捷键未保存！请重新输入并按下“Escape”键保存。
zen-key-conflict = 和其它快捷键冲突
pane-zen-theme-title = 主题设置
zen-vertical-tabs-title = 侧边栏和标签页布局
zen-vertical-tabs-header = 垂直标签页
zen-vertical-tabs-description = 使用垂直布局管理您的标签页
zen-vertical-tabs-show-expand-button = 
    .label = 显示展开按钮
zen-vertical-tabs-newtab-on-tab-list = 
    .label = 在标签页列表中显示新建按钮
zen-vertical-tabs-newtab-top-button-border = 
    .label = 当新建标签页按钮位于底部时，显示分隔边框
zen-vertical-tabs-newtab-top-button-up = 
    .label = 将新建标签页按钮移动到顶部
zen-vertical-tabs-expand-tabs-by-default = 默认展开标签页
zen-vertical-tabs-dont-expand-tabs-by-default = 默认不展开标签页
zen-vertical-tabs-expand-tabs-on-hover = 鼠标悬停时展开标签页（不适用于简洁模式）
zen-vertical-tabs-expand-tabs-header = 如何展开标签页
zen-vertical-tabs-expand-tabs-description = 选择如何在侧边栏展开标签页
zen-theme-marketplace-header = Zen 模组
zen-theme-disable-all-enabled = 
    .title = 禁用所有主题
zen-theme-disable-all-disabled = 
    .title = 启用所有主题
zen-theme-marketplace-description = 从商店查找和安装主题。
zen-theme-marketplace-remove-button = 
    .label = 移除主题
zen-theme-marketplace-check-for-updates-button = 
    .label = 检查更新
zen-theme-marketplace-updates-success = 主题更新成功
zen-theme-marketplace-updates-fail = 没有找到任何更新！
zen-theme-marketplace-toggle-enabled-button = 
    .title = 禁用主题
zen-theme-marketplace-toggle-disabled-button = 
    .title = 启用主题
zen-theme-marketplace-remove-confirmation = 您确定要删除此版主吗？
zen-theme-marketplace-close-modal = 关闭
zen-theme-marketplace-theme-header-title = 
    .title = CSS 选择器： { $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = 无
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = 输入什么...
pane-zen-marketplace-title = Zen 模组
zen-settings-workspaces-display-as-icon-strip = 
    .label = 将工作区作为图标条显示
zen-settings-workspaces-force-container-tabs-to-workspace = 
    .label = 在对应的容器工作区中，打开容器标签页
zen-settings-workspaces-hide-deactivated-workspaces = 
    .label = 隐藏停用的工作区
zen-theme-marketplace-link = 访问商店
zen-dark-theme-styles-header = 深色主题样式
zen-dark-theme-styles-description = 自定义您喜欢的深色主题
zen-dark-theme-styles-amoled = 夜间主题
zen-dark-theme-styles-default = 默认深色主题
zen-dark-theme-styles-colorful = 多彩的深色主题
zen-split-view-title = 拆分视图
zen-split-view-header = 拆分视图功能
zen-split-view-description = 将浏览器拆分为多个视图，以同时浏览多个网页
zen-split-view-change-on-hover = 
    .label = 悬停时切换标签页
zen-compact-mode-styles-left = 隐藏标签页栏
zen-compact-mode-styles-top = 隐藏顶部栏
zen-compact-mode-styles-both = 两者都隐藏
zen-urlbar-title = Zen 地址栏
zen-urlbar-header = 地址栏的常规设置
zen-urlbar-description = 自定义您喜欢的地址栏
zen-urlbar-behavior-label = 行为
zen-urlbar-behavior-normal = 
    .label = 默认
zen-urlbar-behavior-floating-on-type = 
    .label = 仅输入时浮动
zen-urlbar-behavior-float = 
    .label = 始终浮动
pane-zen-CKS-title = 键盘快捷键
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } 键盘快捷键
zen-settings-CKS-header = 自定义您的键盘快捷键
zen-settings-CKS-description = 根据喜好更改您的默认键盘快捷键，并改进您的浏览体验
zen-settings-CKS-disable-firefox = 
    .label = 禁用 { -brand-short-name } 的默认键盘快捷键
zen-settings-CKS-duplicate-shortcut = 
    .label = 重复的快捷键
zen-settings-CKS-reset-shortcuts = 
    .label = 重置为默认值
zenCKSOption-group-other = 其他
zenCKSOption-group-windowAndTabManagement = 窗口和标签页管理
zenCKSOption-group-navigation = 导航
zenCKSOption-group-searchAndFind = 搜索与查找
zenCKSOption-group-pageOperations = 页面操作
zenCKSOption-group-historyAndBookmarks = 历史记录与书签
zenCKSOption-group-mediaAndDisplay = 媒体与显示
zenCKSOption-group-zen-compact-mode = 简洁模式
zenCKSOption-group-zen-workspace = 工作区
zenCKSOption-group-zen-other = 其他Zen功能
zenCKSOption-group-zen-split-view = 拆分视图
zenCKSOption-group-devTools = Developer Tools
zen-key-quick-restart = 快速重启
zen-window-new-shortcut = 新建窗口
zen-tab-new-shortcut = 新建标签页
zen-key-redo = 重做
zen-restore-last-closed-tab-shortcut = 恢复上次关闭的标签页
zen-location-open-shortcut = 打开位置
zen-location-open-shortcut-alt = 打开位置 (Alt)
zen-key-undo-close-window = 撤消关闭窗口
zen-text-action-undo-shortcut = 撤消操作
zen-text-action-redo-shortcut = 重做
zen-text-action-cut-shortcut = 剪切
zen-text-action-copy-shortcut = 复制
zen-text-action-copy-url-shortcut = 复制当前网址
zen-text-action-paste-shortcut = 粘贴
zen-text-action-select-all-shortcut = 选择所有
zen-text-action-delete-shortcut = 删除
zen-history-show-all-shortcut-mac = 显示所有历史记录(Mac)
zen-full-screen-shortcut = 切换全屏
zen-reader-mode-toggle-shortcut-windows = 切换阅读模式（Windows）
zen-picture-in-picture-toggle-shortcut-alt = 切换画中画模式（备用）
zen-picture-in-picture-toggle-shortcut-mac = 切换画中画模式（Mac）
zen-picture-in-picture-toggle-shortcut-mac-alt = 切换画中画模式（Mac备用）
zen-page-source-shortcut-safari = 显示页面源代码（Safari）
zen-nav-stop-shortcut = 停止加载
zen-history-sidebar-shortcut = 显示历史记录侧边栏
zen-window-minimize-shortcut = 最小化窗口
zen-help-shortcut = 打开帮助
zen-preferences-shortcut = 打开首选项
zen-hide-app-shortcut = 隐藏应用程序
zen-hide-other-apps-shortcut = 隐藏其他应用程序
zen-search-focus-shortcut = 聚焦搜索
zen-search-focus-shortcut-alt = 聚焦搜索（备用）
zen-downloads-shortcut = 打开下载
zen-addons-shortcut = 打开附加组件
zen-file-open-shortcut = 打开文件
zen-save-page-shortcut = 保存页面
zen-print-shortcut = 打印页面
zen-close-shortcut-2 = 关闭标签页
zen-mute-toggle-shortcut = 切换静音
zen-key-delete = 删除键
zen-key-go-back = 返回
zen-key-go-forward = 前进
zen-nav-back-shortcut-alt = 导航返回（备用）
zen-nav-fwd-shortcut-alt = 导航前进（备用）
zen-history-show-all-shortcut = 显示所有历史
zen-key-enter-full-screen = 进入全屏
zen-key-exit-full-screen = 退出全屏
zen-reader-mode-toggle-shortcut-other = 切换阅读模式
zen-picture-in-picture-toggle-shortcut = 切换图片到图片
zen-nav-reload-shortcut-2 = 重新加载页面
zen-key-about-processes = 关于进程
zen-page-source-shortcut = 查看页面来源
zen-page-info-shortcut = 查看页面信息
zen-find-shortcut = 在页面上查找
zen-search-find-again-shortcut = 再次查找
zen-search-find-again-shortcut-prev = 查找上一个
zen-search-find-again-shortcut-2 = 再次查找（备用）
zen-bookmark-this-page-shortcut = 将此页面加入书签
zen-bookmark-show-library-shortcut = 显示书签库
zen-key-stop = 停止加载
zen-full-zoom-reduce-shortcut = 缩放
zen-full-zoom-enlarge-shortcut = 放大区域
zen-full-zoom-reset-shortcut = 重置缩放
zen-bidi-switch-direction-shortcut = 切换文本方向
zen-private-browsing-shortcut = 隐私浏览
zen-screenshot-shortcut = 截图
zen-key-sanitize = 清除浏览数据
zen-quit-app-shortcut = 退出应用程序
zen-key-wr-capture-cmd = WR 捕获命令
zen-key-wr-toggle-capture-sequence-cmd = 切换 WR 捕获序列
zen-nav-reload-shortcut = 刷新页面
zen-nav-reload-shortcut-skip-cache = 刷新页面（忽略缓存）
zen-close-shortcut = 关闭窗口
zen-close-tab-shortcut = 关闭标签页
zen-compact-mode-shortcut-show-sidebar = 切换浮动侧边栏
zen-compact-mode-shortcut-show-toolbar = 切换浮动工具栏
zen-compact-mode-shortcut-toggle = 切换简洁模式
zen-workspace-shortcut-switch-1 = 切换到工作区 1
zen-workspace-shortcut-switch-2 = 切换到工作区 2
zen-workspace-shortcut-switch-3 = 切换到工作区 3
zen-workspace-shortcut-switch-4 = 切换到工作区 4
zen-workspace-shortcut-switch-5 = 切换到工作区 5
zen-workspace-shortcut-switch-6 = 切换到工作区 6
zen-workspace-shortcut-switch-7 = 切换到工作区 7
zen-workspace-shortcut-switch-8 = 切换到工作区 8
zen-workspace-shortcut-switch-9 = 切换到工作区 9
zen-workspace-shortcut-switch-10 = 切换到工作区 10
zen-workspace-shortcut-forward = 下一个工作区
zen-workspace-shortcut-backward = 上一个工作区
zen-web-panel-shortcut-toggle = 切换侧边网页面板
zen-sidebar-shortcut-toggle = 切换侧边栏宽度
zen-pinned-tab-shortcut-reset = 重置固定标签页至其固定的 URL
zen-split-view-shortcut-grid = 切换网格拆分视图
zen-split-view-shortcut-vertical = 切换垂直拆分视图
zen-split-view-shortcut-horizontal = 切换水平拆分视图
zen-split-view-shortcut-unsplit = 关闭拆分视图
zen-key-select-tab-1 = 选择标签页 #1
zen-key-select-tab-2 = 选择标签页 #2
zen-key-select-tab-3 = 选择标签页 #3
zen-key-select-tab-4 = 选择标签页 #4
zen-key-select-tab-5 = 选择标签页 #5
zen-key-select-tab-6 = 选择标签页 #6
zen-key-select-tab-7 = 选择标签页 #7
zen-key-select-tab-8 = 选择标签页 #8
zen-key-select-tab-last = 选择最后一个标签页
zen-key-show-all-tabs = 显示所有标签页
zen-key-goto-history = 转到历史记录
zen-key-go-home = 回到首页
zen-bookmark-show-sidebar-shortcut = 显示书签侧边栏
zen-bookmark-show-toolbar-shortcut = 显示书签工具栏
zen-devtools-toggle-shortcut = Toggle DevTools
zen-devtools-toggle-browser-toolbox-shortcut = Toggle Browser Toolbox
zen-devtools-toggle-browser-console-shortcut = Toggle Browser Console
zen-devtools-toggle-responsive-design-mode-shortcut = Toggle Responsive Design Mode
zen-devtools-toggle-inspector-shortcut = Toggle Inspector
zen-devtools-toggle-web-console-shortcut = Toggle Web Console
zen-devtools-toggle-js-debugger-shortcut = Toggle JavaScript Debugger
zen-devtools-toggle-net-monitor-shortcut = Toggle Network Monitor
zen-devtools-toggle-style-editor-shortcut = Toggle Style Editor
zen-devtools-toggle-performance-shortcut = Toggle Performance
zen-devtools-toggle-storage-shortcut = Toggle Storage
zen-devtools-toggle-dom-shortcut = Toggle DOM
zen-devtools-toggle-accessibility-shortcut = Toggle Accessibility
