pane-zen-looks-title = 界面外观
category-zen-looks = 
    .tooltiptext = { pane-zen-looks-title }
zen-warning-language = 更改默认语言可能会让网站更容易追踪您。
zen-look-and-feel-colors-header = 选择一个主题颜色
zen-look-and-feel-colors-description = 让 { -brand-short-name } 界面外观符合您的喜好
zen-look-and-feel-themed-toolbar = 
    .label = 为工具栏使用强调色
pane-zen-side-panels-title = 侧边网页面板
zen-side-panels-header = 网页面板的常规设置
zen-side-panels-description = 通过同时拥有多个视图来提高生产力！
zen-side-panels-enabled = 
    .label = 启用侧边网页面板
zen-side-panels-close-on-blur = 
    .label = 如果面板没有置顶，失去焦点时关闭面板
zen-look-and-feel-compact-view-header = 以紧凑视图显示
zen-look-and-feel-compact-view-description = 只显示你使用的工具栏！
zen-look-and-feel-compact-view-enabled = 
    .label = 启用 { -brand-short-name } 的紧凑模式
zen-look-and-feel-compact-view-top-toolbar = 
    .label = 在紧凑模式下隐藏顶部工具栏
zen-look-and-feel-compact-toolbar-flash-popup = 
    .label = 在紧凑模式下切换或打开新标签页时短暂弹出工具栏
zen-look-and-feel-buttons-header = 按钮风格
zen-look-and-feel-buttons-description = 选择您想看到的按钮样式
zen-look-and-feel-pilled-buttons = 
    .label = Pilled Buttons
pane-zen-workspaces-title = 工作空间
category-zen-workspaces = 
    .tooltiptext = { pane-workspaces-title }
pane-settings-workspaces-title = 工作空间
pane-zen-workspaces-header = 工作空间
zen-settings-workspaces-header = 工作空间的常规设置
zen-settings-workspaces-description = 使用工作空间，您可以同时进行多个浏览会话！
zen-settings-workspaces-enabled = 
    .label = 启用工作空间 (实验性)
zen-settings-workspaces-hide-default-container-indicator = 
    .label = 隐藏在标签页栏中的默认容器指示器
zen-settings-workspaces-allow-pinned-tabs-for-different-workspaces = 
    .label = 允许工作区有自己的固定标签页
pane-zen-theme-title = 主题设置
zen-vertical-tabs-title = 侧边栏和标签布局
zen-vertical-tabs-header = 垂直标签页
zen-vertical-tabs-description = 使用垂直布局管理您的标签页
zen-vertical-tabs-show-expand-button = 
    .label = 显示展开按钮
zen-vertical-tabs-expand-tabs-by-default = 默认展开标签
zen-vertical-tabs-dont-expand-tabs-by-default = 默认不展开标签
zen-vertical-tabs-expand-tabs-on-hover = 悬停时展开标签（在紧凑模式下无法工作）
zen-vertical-tabs-expand-tabs-header = 如何展开标签页
zen-vertical-tabs-expand-tabs-description = 选择如何在侧边栏展开标签页
zen-theme-marketplace-header = Zen模组
zen-theme-marketplace-description = 从商店查找和安装主题。
zen-theme-marketplace-remove-button = 
    .label = 移除主题
zen-theme-marketplace-check-for-updates-button = 
    .label = 检查更新
zen-theme-marketplace-updates-success = 主题更新成功
zen-theme-marketplace-updates-fail = 没有找到任何更新！
zen-theme-marketplace-toggle-enabled-button = 
    .title = 禁用主题
zen-theme-marketplace-toggle-disabled-button = 
    .title = 启用主题
zen-theme-marketplace-remove-confirmation = 您确定要移除此模组吗？
zen-theme-marketplace-close-modal = 关闭
zen-theme-marketplace-theme-header-title = 
    .title = CSS 选择器：{ $name }
zen-theme-marketplace-dropdown-default-label = 
    .label = 空
zen-theme-marketplace-input-default-placeholder = 
    .placeholder = 请在此输入
pane-zen-marketplace-title = Zen模组
zen-settings-workspaces-display-as-icon-strip = 
    .label = 将工作空间显示为图标条
zen-theme-marketplace-link = 访问商店
zen-dark-theme-styles-header = 深色主题样式
zen-dark-theme-styles-description = 自定义您喜欢的深色主题
zen-dark-theme-styles-amoled = 夜间主题
zen-dark-theme-styles-default = 默认深色主题
zen-dark-theme-styles-colorful = 多彩的深色主题
zen-compact-mode-styles-left = 隐藏标签页栏
zen-compact-mode-styles-top = 隐藏顶边栏
zen-compact-mode-styles-both = 两者同时隐藏
pane-zen-CKS-title = 键盘快捷键
category-zen-CKS = 
    .tooltiptext = { pane-zen-CKS-title }
pane-settings-CKS-title = { -brand-short-name } 键盘快捷键
zen-settings-CKS-header = 自定义您的键盘快捷键
zen-settings-CKS-description = 根据喜好更改您的默认键盘快捷键，并改进您的浏览体验
zen-settings-CKS-disable-firefox = 
    .label = 禁用 { -brand-short-name } 的默认键盘快捷键
zen-settings-CKS-duplicate-shortcut = 
    .label = Duplicate Shortcut
zenCKSOption-group-other = Other
zenCKSOption-group-windowAndTabManagement = Window & Tab Management
zenCKSOption-group-navigation = Navigation
zenCKSOption-group-searchAndFind = Search & Find
zenCKSOption-group-pageOperations = Page Operations
zenCKSOption-group-historyAndBookmarks = History & Bookmarks
zenCKSOption-group-mediaAndDisplay = Media & Display
zenCKSOption-group-zen-compact-mode = Compact Mode
zenCKSOption-group-zen-workspace = Workspaces
zenCKSOption-group-zen-other = Other Zen Features
zen-key-quick-restart = Quick Restart
zen-window-new-shortcut = New Window
zen-tab-new-shortcut = New Tab
zen-location-open-shortcut = Open Location
zen-location-open-shortcut-alt = Open Location (Alt)
zen-search-focus-shortcut = Focus Search
zen-search-focus-shortcut-alt = Focus Search (Alt)
zen-downloads-shortcut = Open Downloads
zen-addons-shortcut = Open Add-ons
zen-file-open-shortcut = Open File
zen-save-page-shortcut = Save Page
zen-print-shortcut = Print Page
zen-close-shortcut-2 = Close Tab
zen-mute-toggle-shortcut = Toggle Mute
zen-key-delete = Delete Key
zen-key-go-back = Go Back
zen-key-go-forward = Go Forward
zen-nav-back-shortcut-alt = Navigate Back (Alt)
zen-nav-fwd-shortcut-alt = Navigate Forward (Alt)
zen-history-show-all-shortcut = Show All History
zen-key-enter-full-screen = Enter Full Screen
zen-key-exit-full-screen = Exit Full Screen
zen-reader-mode-toggle-shortcut-other = Toggle Reader Mode
zen-picture-in-picture-toggle-shortcut = Toggle Picture-in-Picture
zen-nav-reload-shortcut-2 = Reload Page
zen-key-about-processes = About Processes
zen-page-source-shortcut = View Page Source
zen-page-info-shortcut = View Page Info
zen-find-shortcut = Find on Page
zen-search-find-again-shortcut = Find Again
zen-search-find-again-shortcut-prev = Find Previous
zen-search-find-again-shortcut-2 = Find Again (Alt)
zen-bookmark-this-page-shortcut = Bookmark This Page
zen-bookmark-show-library-shortcut = Show Bookmarks Library
zen-key-stop = Stop Loading
zen-full-zoom-reduce-shortcut = Zoom Out
zen-full-zoom-enlarge-shortcut = Zoom In
zen-full-zoom-reset-shortcut = Reset Zoom
zen-bidi-switch-direction-shortcut = Switch Text Direction
zen-private-browsing-shortcut = Private Browsing
zen-screenshot-shortcut = Take Screenshot
zen-key-sanitize = Clear Browsing Data
zen-quit-app-shortcut = Quit Application
zen-key-wr-capture-cmd = WR Capture Command
zen-key-wr-toggle-capture-sequence-cmd = Toggle WR Capture Sequence
zen-nav-reload-shortcut = Reload Page
zen-nav-reload-shortcut-skip-cache = Reload Page (Skip Cache)
zen-close-shortcut = Close Window
zen-close-tab-shortcut = Close Tab
zen-compact-mode-shortcut-show-sidebar = Toggle Floating Sidebar
zen-compact-mode-shortcut-show-toolbar = Toggle Floating Toolbar
zen-compact-mode-shortcut-toggle = Toggle Compact Mode
zen-workspace-shortcut-switch-1 = Switch to Workspace 1
zen-workspace-shortcut-switch-2 = Switch to Workspace 2
zen-workspace-shortcut-switch-3 = Switch to Workspace 3
zen-workspace-shortcut-switch-4 = Switch to Workspace 4
zen-workspace-shortcut-switch-5 = Switch to Workspace 5
zen-workspace-shortcut-switch-6 = Switch to Workspace 6
zen-workspace-shortcut-switch-7 = Switch to Workspace 7
zen-workspace-shortcut-switch-8 = Switch to Workspace 8
zen-workspace-shortcut-switch-9 = Switch to Workspace 9
zen-workspace-shortcut-switch-10 = Switch to Workspace 10
zen-workspace-shortcut-forward = Forward Workspace
zen-workspace-shortcut-backward = Backward Workspace
zen-web-panel-shortcut-toggle = Toggle Web Panel
zen-sidebar-shortcut-toggle = Toggle Sidebar's Width
