zen-panel-ui-workspaces-text = دیگر فضاهای کاری
zen-panel-ui-workspaces-create-text = ساخت فضای کاری
zen-panel-ui-workspaces-create-save = 
    .label = ساخت فضای کاری
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = لغو
    .accesskey = C
zen-panel-ui-workspaces-edit-text = ویرایش فضای کاری
zen-panel-ui-workspaces-edit-save = 
    .label = ذخیرهٔ تغییرات
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = لغو
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = حذف فضای کاری
    .accesskey = D
zen-workspaces-panel-change-name = 
    .label = Change Name
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Set Default Container
    .accesskey = O
zen-workspaces-change-gradient = 
    .label = Change Theme Colors
    .accesskey = C
zen-bookmark-edit-panel-workspace-selector = 
    .value = Workspaces
    .accesskey = W
zen-panel-ui-gradient-generator-algo-complementary = 
    .label = Complementary
zen-panel-ui-gradient-generator-algo-splitComplementary = 
    .label = Split
zen-panel-ui-gradient-generator-algo-analogous = 
    .label = Analogous
zen-panel-ui-gradient-generator-algo-triadic = 
    .label = Triadic
zen-panel-ui-gradient-generator-algo-floating = 
    .label = Floating
zen-panel-ui-gradient-click-to-add = Click to add a color
