zen-panel-ui-current-profile-text = نمایهٔ کنونی
unified-extensions-description = افزونه‌های در حال استفاده عملکردهای بیشتری به { -brand-short-name } می‌دهند.
tab-context-zen-reset-pinned-tab = 
    .label = Reset Pinned Tab
    .accesskey = R
tab-context-zen-add-essential = 
    .label = Add to Essentials
    .accesskey = E
tab-context-zen-remove-essential = 
    .label = Remove from Essentials
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = Replace Pinned URL with Current
    .accesskey = C
tab-zen-unload = 
    .label = Unload Tab
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = Tabs Unloader Actions
    .accesskey = T
tab-zen-prevent-unload = 
    .label = Allow Tab Unload
    .accesskey = P
tab-zen-ignore-unload = 
    .label = Allow Tab Unload
    .accesskey = I
zen-themes-corrupted = Your { -brand-short-name } mods file is corrupted. They have been reset to the default theme.
zen-panel-ui-gradient-generator-opacity-text = Contrast
zen-panel-ui-gradient-generator-texture-text = Texture
zen-panel-ui-gradient-generator-custom-color = Custom Color
zen-panel-ui-gradient-generator-saved-message = Successfully saved the gradient!
zen-copy-current-url-confirmation = The URL has been copied to the clipboard.
zen-rice-share-name = 
    .placeholder = Rice Name
zen-rice-share-author = By
zen-rice-share-author-input = 
    .placeholder = Your Name
zen-rice-share-cancel = Cancel
zen-rice-share-save = Share
zen-rice-share-include-userchrome = 
    .label = Include userChrome.css
zen-rice-share-include-usercontent = 
    .label = Include userContent.css
zen-rice-share-include-mods = 
    .label = Include enabled mods
zen-rice-share-include-mod-prefs = 
    .label = Include mod preferences
zen-rice-share-include-preferences = 
    .label = Include layout state
zen-rice-share-include-workspace-themes = 
    .label = Include workspace gradient themes
zen-rice-share-include = Export Options
