zen-panel-ui-workspaces-text = Workspaces
zen-panel-ui-workspaces-create-text = ساخت فضای کاری
zen-panel-ui-workspaces-create-save = 
    .label = ساخت فضای کاری
    .accesskey = S
zen-panel-ui-workspaces-create-cancel = 
    .label = لغو
    .accesskey = C
zen-panel-ui-workspaces-edit-text = ویرایش فضای کاری
zen-panel-ui-workspaces-edit-save = 
    .label = ذخیرهٔ تغییرات
    .accesskey = S
zen-panel-ui-workspaces-edit-cancel = 
    .label = لغو
    .accesskey = C
zen-workspaces-panel-context-delete = 
    .label = حذف فضای کاری
    .accesskey = D
zen-workspaces-panel-context-open = 
    .label = Open Workspace
    .accesskey = O
zen-workspaces-panel-context-set-default = 
    .label = Set As Default Workspace
    .accesskey = S
zen-workspaces-panel-context-edit = 
    .label = Edit Workspace
    .accesskey = E
context-zen-change-workspace-tab = 
    .label = Change Tab(s) To Workspace
    .accesskey = C
zen-workspaces-panel-context-open-in-container-tab = 
    .label = Set Default Container
    .accesskey = O
